### ISSUE TITLE
Will you still support UIA in Windows10. or replace it with WinAppDriver?

### ISSUE THREAD

**Issue by EthanJiang** [Microsoft/WinAppDriver#10]
Hi

What's your plans for UIA on Window10? Is WebDriver a replacement for UIA? Or Will you be continued to be fully supported in parallel?

Currently the automation test solution we used is based on UIA, So the changes maybe become a big impact on current solution. 

Thanks
Ethan

**Comment by khouzam** [comment]
WinAppDriver is built on top of UIA. This will not replace UIA, we're just trying to enable more scenarios.

Thanks

**Comment by EthanJiang** [comment]
Thanks
