### ISSUE TITLE
Is it posible to connect to an running app process, not a new instance ?

### ISSUE THREAD

**Issue by wzlsquall** [microsoft/WinAppDriver#1003]
## It always create an new instance

Is it posible to connect to an running app process, not a new instance ?

**Comment by anunay1** [comment]
Yes its possible. You can start the application manually and switch to that application with the below code 

  DesiredCapabilities desktopCapabilities = new DesiredCapabilities();
                    desktopCapabilities.SetCapability("app","Root");
                    desktopSession = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), desktopCapabilities);
                    Assert.IsNotNull(desktopSession);


                    var ShellWindow = desktopSession.FindElementByClassName("ApplicationFrameWindow");
                    var XXXShellTopLevelWindowHandle = ShellWindow.GetAttribute("NativeWindowHandle");
                    XXXShellTopLevelWindowHandle = (int.Parse(XXXShellTopLevelWindowHandle)).ToString("x");

                    DesiredCapabilities appcapabilities = new DesiredCapabilities();
                    appcapabilities.SetCapability("appTopLevelWindow", XXXShellTopLevelWindowHandle);
                    session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl),appcapabilities);

**Comment by hassanuz** [comment]
@wzlsquall, hoping the response above resolved it for you. If not feel free to create another ticket.
