### ISSUE TITLE
can it surpport win7 application?

### ISSUE THREAD

**Issue by hp-web** [microsoft/WinAppDriver#1004]
like tittle!

**Comment by moonkey124** [comment]
If the application was initially released for Windows 7 but runs fine on Windows 10, then yes. The tests however can only be run on a Windows 10 system.

**Comment by hassanuz** [comment]
Hi @hp-web,

As @moonkey124 mentioned, if it is a legacy Win32 application **running on Windows 10**, then it should be fine.

WinAppDriver isn't supported on Windows 7, or any other OS prior to Windows 10.
