### ISSUE TITLE
Nothing appear in Instagram app on windows 10

### ISSUE THREAD

**Issue by momenimohammad23** [Microsoft/WinAppDriver#101]
Hi 
i want to do automate something on Instagram 
I fount Button by name , But I Cant Click on it

**Comment by ianceicys** [comment]
@momenimohammad23 Can you post a link to your git hub where we can look at repoing the issue? For example it'd be really helpful to have a recording like this too. https://www.youtube.com/watch?v=xvJ2ALe0mt8

**Comment by yodurr** [comment]
closing, please open new issue if you still want help.  Thanks.
