### ISSUE TITLE
Missing api-ms-win-shcore-scaling-l1-1-1.dll when running

### ISSUE THREAD

**Issue by melegant** [Microsoft/WinAppDriver#102]
Getting an error that "The Program can't start because api-ms-win-shcore-scaling-l1-1-1.dll is missing from your computer".

I did some digging around but can't find a place to get this dll.

Thanks,
M

![image](https://cloud.githubusercontent.com/assets/19844309/20836007/7764e730-b86b-11e6-87f9-5ee4bd0d29a8.png)

**Comment by ianceicys** [comment]
@melegant Can you check your Visual Studio installation? Are you running Visaul Studio 2015 with Update 3? It looks like you may have to re-install a missing the Visual studio redistributable package.

https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by melegant** [comment]
Hi,
Thanks Ian.
I have Update 3:
![image](https://cloud.githubusercontent.com/assets/19844309/20837233/2819c3ac-b871-11e6-8b1e-858a3cd101a1.png)

Also I have all those RD:
![image](https://cloud.githubusercontent.com/assets/19844309/20837241/3a679034-b871-11e6-92a1-6e422504ed7c.png)

I suppose I will try to re-install those redistributables...

**Comment by melegant** [comment]
Hi,
So I tried to re-install but I am still getting that same error. Is there somewhere I can just get that file so I can put it in the folder that has the .exe?
Thanks,
M

**Comment by khouzam** [comment]
Hi,

WinAppDriver is not supported on Windows 7, only Windows 10 at the moment.. We'll update the setup to prevent installation on older OSes.

**Comment by melegant** [comment]
Ah...well that solves that one then. I guess Windows 10 here I come.
