### ISSUE TITLE
Control + click

### ISSUE THREAD

**Issue by jira-zz** [microsoft/WinAppDriver#1037]
How can I send control + click when selecting items in a list?

elem.SendKeys(Keys.Control);
elem.Click();
elem.SendKeys(Keys.Control):

doesn't work

**Comment by PandaMagnus** [comment]
The Actions API in Selenium has a way to do this. I don't remember the exact syntax off hand, but (in pseudo-C#) it'd be something like:

```
Actions ctrlClick = new Actions(Driver);
ctrlClick
   .KeyDown(Keys.Ctrl)
   .Click(elem)
   .KeyUp(Keys.Ctrl)
   .Perform();
```

**Comment by Shakevg** [comment]
@jira-zz https://stackoverflow.com/questions/11503736/key-press-in-ctrla-selenium-webdriver

**Comment by jira-zz** [comment]
> Actions actions = new Actions(Driver);
> actions.KeyDown(OpenQA.Selenium.Keys.Control)
> 	.Click(elem)
> 	.KeyUp(OpenQA.Selenium.Keys.Control)
> 	.Build()
> 	.Perform();
> ```

That worked. Thanks!
