### ISSUE TITLE
FindElementByXPath threw an exception 'System.InvalidOperationException'

### ISSUE THREAD

**Issue by krabobor** [Microsoft/WinAppDriver#106]
Great thanks for the bug fix and release v0.7, but findByXPath meyhod still does not work :( https://gyazo.com/985ebe777b226d77c8b531d8b363efc5

**Comment by timotiusmargo** [comment]
Hi @krabobor, from the attached URL above, it looks like you are trying to access an HTML element using HTML id attribute that may not be exposed in the default context UI tree. The [Inspect Tool](https://github.com/Microsoft/WinAppDriver#inspecting-ui-elements) shows every UI element that WinAppDriver has access to along with its attribute such as **AutomationId**, **Name**, **ClassName** etc.

Could you please use the tool to see if the element you are looking for is indeed exposed in the application UI tree and addressable through one of it's attribute such as **AutomationId**?

**Comment by krabobor** [comment]
this is what Inspect Tool shows https://gyazo.com/12d82adf902e6abd4afbff881e1158a0
I know that I can find this button by FindElementByAccessibilityId method. 
but how can I find the dynamic elements that have no id (without FindElementByXPath method)?

**Comment by timotiusmargo** [comment]
Hi @krabobor. FindElementByXpath should definitely work as well. What I was trying to say is you can use different attributes such as AutomationId, Name, and ClassName in your XPath query. You can test the API using the sample test we wrote for this particular scenario in https://github.com/Microsoft/WinAppDriver/blob/master/Tests/W3CWebDriver/Element.cs#L156

If for whatever reason the FindElementByXPath doesn't work for your application, could you please share the UI tree snapshot along with the XPath query you made (the request you send to Windows Application Driver).

**Comment by johleung** [comment]
Hi @timotiusmargo , I am new to WinappDriver. I received the same error message when I execute the sample calculator test. Error occured on class: Basic Scenario > ClassInitialize, line 42: CalculatorSession.FindElementByXPath("//Button[starts-with(@Name, \"Menu\")]").Click();

I'm using WIN10, VS2015, Selenium 3.0, WinAppDriver 0.7. 

Log from WinAppDriver
==========================================
POST /session/D006F3F7-7A34-4C13-B01E-957FB9EC24EA/element HTTP/1.1
Accept: application/json, image/png
Content-Length: 66
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"using":"xpath","value":"//Button[starts-with(@Name, \"Menu\")]"}
HTTP/1.1 500 Internal Error
Content-Length: 133
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}

**Comment by FatihBekdemir** [comment]
Hi,
Having the same issue with @johleung .
**Is it could be the difference between region & language settings ?**
My computers language is English, but Windows apps use my country or region to give local content.
For example, my calculator app is not English, it is my own country's language.

I'm using WIN10 build 14393.693, version 1607,  VS2015 update 3
When I execute the sample calculator test. Error occured on class: Basic Scenario > ClassInitialize, line 43:
OriginalCalculatorMode = CalculatorSession.FindElementByXPath("//List[@AutomationId=\"FlyoutNav\"]//ListItem[@IsSelected=\"True\"]").Text;

**StackTrace**
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByXPath(String xpath)
   at CalculatorTest.BasicScenarios.Setup(TestContext context) in C:\dev\WinAppDriver\Samples\C#\CalculatorTest\BasicScenarios.cs:line 43 

POST /session/6ECC9B0A-031A-415B-B63E-6DA3AC0150A5/element HTTP/1.1
Accept: application/json, image/png
Content-Length: 95
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

**Log From WinAppDriver**
HTTP/1.1 404 Not Found
Content-Length: 139
Content-Type: application/json

{"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}

**Comment by FatihBekdemir** [comment]
Any help about above problem ? @timotiusmargo @yodurr @alakshmi1030 @khouzam

**Comment by khouzam** [comment]
Yes, the problem is the localization. If you look at the tree in inspect.exe. the name of the elements change based on the language. If you change the test to look for the localized name of the element then it should work.

**Comment by dhapolapankaj** [comment]
Team,
Can we have a look at issue #201 
Can we rule out issue is not with FindElement() and issue is actually with Click() or SendKeys() ?

Regards
PD

**Comment by dhapolapankaj** [comment]
@johleung 
Can you replace the double quote inside XPath with double quote. Like below
".//Button[starts-with(@name, 'Menu')]"
".//Button[contains(@name, 'Menu')]"

**Comment by timotiusmargo** [comment]
Hi all,

We have recently updated our C# sample test including the [CalculatorTest](https://github.com/Microsoft/WinAppDriver/tree/master/Samples/C%23/CalculatorTest). In this version, we tried our best to make it work for Windows 10 PC with the latest Windows 10 version (Version 1607 or later). However, some test scenarios still depends on localized name as finding element by name is one of the feature we are trying to demonstrate. Please give it a try.
