### ISSUE TITLE
Use winappdriver instead of AutoIT.

### ISSUE THREAD

**Issue by jadhavpn1993** [microsoft/WinAppDriver#1074]
Can we use winappdriver to handle the Windows popup while automating web applications using selenium Webdriver .Please suggest.

**Comment by anunay1** [comment]
Have you tried it, what kind of pops are these.

**Comment by jadhavpn1993** [comment]
Yes I have tried it , but i am not able to create a new session for windows popup.
For example - If you want to upload a file,using AutoIT you just need to call exe file generated by the AutoIt.
I am trying to automate the part of AutoIT using winappdriver.

**Comment by anunay1** [comment]
You can use the below code to achieve that: 
 DesiredCapabilities desktopCapabilities = new DesiredCapabilities();
 desktopCapabilities.SetCapability("app","Root");
 desktopSession = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), desktopCapabilities);
 Assert.IsNotNull(desktopSession);


var ShellWindow = desktopSession.FindElementByClassName("XXXXXX");
var ShellTopLevelWindowHandle = ShellWindow.GetAttribute("NativeWindowHandle");
ShellTopLevelWindowHandle = (int.Parse(ShellTopLevelWindowHandle)).ToString("x");

DesiredCapabilities appcapabilities = new DesiredCapabilities();
appcapabilities.SetCapability("appTopLevelWindow", ShellTopLevelWindowHandle);
session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl),appcapabilities);

**Comment by jadhavpn1993** [comment]
Hi ,
It's working for me , Thank you.
