### ISSUE TITLE
WinAppDrivere doesn't see elements in tab, loaded from .dll .

### ISSUE THREAD

**Issue by noob001** [microsoft/WinAppDriver#1078]
We have a wpf application, and we have tabs in it, that loads from modules of this app and packed in .dll with another parts of this module. In tabs we have DevExpress controls. Inspect.exe doesn't see elements in tab, But Snoop - can see all of them. 
How can we make WinAppDriver see these elements to automate UI testing? It looks like I can see TAB from winAppDriver, but cannot see child elements of this tab, see only like what i can see in inspect.exe

![image](https://user-images.githubusercontent.com/14805568/75235242-f7c43f80-57cc-11ea-9fa6-b389c2e7bc7c.png)

**Comment by naeemakram** [comment]
DevExpress controls are different from other Windows controls. I remember in a past project we had to buy a license from DevExpress to automate an application with Coded UI which was using DevExpress.

**Comment by noob001** [comment]
> DevExpress controls are different from other Windows controls. I remember in a past project we had to buy a license from DevExpress to automate an application with Coded UI which was using DevExpress.

After a few days of researching i think, that problem is in application architecture. Looks like WinAppDriver can't see elements of tab, which packed in another module dll's. Maybe someone know how to fix it?

**Comment by noob001** [comment]
Fix them by this - https://www.colinsalmcorner.com/genericautomationpeer--helping-the-coded-ui-framework-find-your-custom-controls/

We add in our custom controls AutomationPeers (And also makes a child of TabControl with AutomationPeers) and it works.
