### ISSUE TITLE
WinAppDriver does not work with WinForms applications

### ISSUE THREAD

**Issue by kfrajtak** [Microsoft/WinAppDriver#108]
Hi,

I was trying to use WinAppDriver for a WinForms application. Before release 0.7 the test code was hanging on the line where the session was created. With release 0.7 a session for WinForms application is created (previously it was hanging on that line).

However, now I have a problem with selecting an element. I have a simple WinForms app with a `TextBox` called `textBox1`, but neither `session.FindElementById` nor `session.FindElementByName` methods are not able to find that element:

> System.InvalidOperationException: An element could not be located on the page using the given search parameters.

The PageSource property of the session contains this fragment

```
<Edit AcceleratorKey="" AccessKey="" AutomationId="textBox1"
 ClassName="WindowsForms10.EDIT.app.0.2bf8098_r9_ad1" FrameworkId="WinForm" 
 HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True"
 IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="False" IsPassword="False"
 IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="edit"
 Name="" Orientation="None" ProcessId="13860" RuntimeId="42.331658"
 x="151" y="158" width="100" height="20" />
```

The element can be located using `FindElementByTagName` method.

I have also created a test for WPF application and it works there. I noticed that elements in WPF app do have Name and do not have AutomationId (at least in the PageSource XML document):

```
<MenuItem AcceleratorKey="" AccessKey="Alt+F" AutomationId="" ClassName="MenuItem"
 FrameworkId="WPF" HasKeyboardFocus="False" HelpText=""
 IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True"
 IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType=""
 LocalizedControlType="menu item" Name="File" Orientation="None" ProcessId="27144"
 RuntimeId="7.27144.34576242" x="138" y="161" width="33" height="21"
 ExpandCollapseState="Collapsed" IsAvailable="True" />
```

I have put together a project for reproduction [https://github.com/kfrajtak/UITesting](https://github.com/kfrajtak/UITesting) (you'll have to change the hard-coded paths). 

This issue was created from the discussion for issue #83.

Thanks, 
Karel

**Comment by ianceicys** [comment]
@khouzam I repo'd this issue and did a bit of investigation. Seems like a possible bug for WinForms Applications. 

Additional documentation would help understand how to work with each Find() method and their intended uses.

 [![FindElementWinForms](http://i.imgur.com/vBhPStj.png)]https://www.youtube.com/watch?v=iK9q3_fahZE

**Comment by kfrajtak** [comment]
Nice summary @ianceicys!

**Comment by timotiusmargo** [comment]
Hi @kfrajtak & @ianceicys,

Thank you for the extensive and clear description above. It is apparent that the **FindElement** selectors need to be documented better under the readme, samples, and tests. **WPF** and **WinForms** applications are supported by Windows Application Driver. Finding the element in those apps may differ but is consistently based on the following attributes:

| Locator Strategy 	| Client API                   	| Matched Attribute                      	|
|------------------	|------------------------------	|----------------------------------------	|
| accessibility id 	| FindElementByAccessibilityId 	| AutomationId                           	|
| class name       	| FindElementByClassName       	| ClassName                              	|
| id               	| FindElementById              	| RuntimeId (decimal)                    	|
| name             	| FindElementByName            	| Name                                   	|
| tag name         	| FindElementByTagName         	| LocalizedControlType (upper camel case)	|

Using the [inspect tool](https://github.com/Microsoft/WinAppDriver/blob/master/README.md#inspecting-ui-elements) or page source, you can identify and use any suitable attribute to locate your element based on the rules above.

**Comment by aczoll** [comment]
I had the exact same issue with WinAppDriver and WinForm application. All you need to do is run WinAppDriver.exe as Administrator.

**Comment by NadeemBader** [comment]
Hi
I'm facing some issues with WinAppDriver and WinForms. I'm not able to set the value of he following values from the application side, and as a result:

```
<Edit **AcceleratorKey="" AccessKey=""** AutomationId="textBox1"
 ClassName="WindowsForms10.EDIT.app.0.2bf8098_r9_ad1" FrameworkId="WinForm" 
 HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True"
 IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="False" IsPassword="False"
 IsRequiredForForm="False" **ItemStatus="" ItemType=""** LocalizedControlType="edit"
 **Name=""** Orientation="None" ProcessId="13860" RuntimeId="42.331658"
 x="151" y="158" width="100" height="20" />
```

Any suggestions? 

Best Regards,
Nadeem Bader
