### ISSUE TITLE
Doubts: Can I run App installed on my surface pro 4(having windows 10 in it ) with my laptop(having windows 10 in it).

### ISSUE THREAD

**Issue by anand16593** [Microsoft/WinAppDriver#109]
Doubts: 
Can I run App installed on my surface pro 4(having windows 10 in it ) with my laptop(having windows 10 in it).

**Comment by ianceicys** [comment]
@anand16593 You should be able to. Can you please watch the following walkthrough and try out the calculator sample and see if that works? 

[![walkthrough]([Imgur](http://i.imgur.com/lhlYFs1.png))](https://www.youtube.com/watch?v=XAJVpvaEchY)

**Comment by anand16593** [comment]
@ianceicys 
This video describe how to run app on same machine.
I am writing program on my laptop which is having window 10
I was asking how can I connect my surface pro using capabilities and running App which is installed on the Surface pro.

Thanks

**Comment by ianceicys** [comment]
Ah ok, I wasn't clear on your configuration. It sounds like you want to remotely execute tests on a different machine, in say a selenium remote control configuration. Take a look at the readme for [steps](https://github.com/Microsoft/WinAppDriver/blob/master/README.md): on how to do this.  

If you've tried this with the .7 release and are encountering an error please post more information. 

Running on a Remote machine

On the machine you want to run the test application on, open up "Windows Firewall with Advanced Security"
Select "Inbound Rules" -> "New Rule"
Rule type -> port
Select TCP
Choose specific local port (4723 is WinAppDriver standard)
Action -> allow the connection
Profile -> select all
Name -> optional, choose name for rule (e.g. WinAppDriver remote)
Run ipconfig to determine your machine's local IP address
Note that setting * as the IP address command line option will cause it to bind to all bound IP addresses on the machine
Run WinAppDriver.exe with command line arguments as seen above specifying local IP and port (must be in admin cmd)
On the machine with the test runner, make sure the URL in the test script is pointing to the IP of the remote machine
If the test app is installed on the remote machine run your test script and see the results!

**Comment by anand16593** [comment]
Thanks
