### ISSUE TITLE
Getting Internal Error

### ISSUE THREAD

**Issue by rkumarrb** [Microsoft/WinAppDriver#11]
I have tried few samples and I'm getting internal error all the time. Attached the image for your review.(This image is taken when I try to open notepad and type "something" on it

![image](https://cloud.githubusercontent.com/assets/6379299/14619319/090f3c20-0585-11e6-995b-30b1d11ffe32.png)

**Comment by rkumarrb** [comment]
I have went through your demos and they are in win 10 and currently I'm using it in win 7. I hope its not a problem but would like to keep you posted with more information related to this issue.

**Comment by rkumarrb** [comment]
Ok I just read the below line,

Windows Application Driver supports testing Universal Windows Platform (UWP) and Classic Windows (Win32) apps on Windows 10 PC

At this moment it supports only Win 10. Could you please let me know when are we planning for the support for Win 7 or 8 or do we have any work around (like copying set of libraries or so) for these versions

**Comment by yodurr** [comment]
Win7 and Win8 are not on the near term roadmap.  Would be nice to support it but right now we're focused on features still needed on Win10.  

You can add the request here so others can vote it up: https://wpdev.uservoice.com/forums/110705-universal-windows-platform/category/161358-ui-testing

**Comment by rkumarrb** [comment]
Thank you. :)
