### ISSUE TITLE
How can I get any of Patterns value?

### ISSUE THREAD

**Issue by erohinalexey** [microsoft/WinAppDriver#1117]
Hi all! 
I've tried to get ToggleState pattern value, but couldn't.
[http://i.piccy.info/i9/d6946a15d45d615151e994bf8cc87313/1585819410/105535/1369185/Screenshot_1.png](url)
The code like this is not working: 
` winDriver.findElement(By.findElementByAccessibilityId("MyID")).getAttribute("ToggleState")`
Could you please help me?

**Comment by naeemakram** [comment]
You can use XPath to find controls based on attribute patterns.

**Comment by PandaMagnus** [comment]
@erohinalexey If this is a checkbox and you want to see if it's checked or not, instead of getting ToggleState, you can use .selected() instead of .getAttribute().

**Comment by erohinalexey** [comment]
> @erohinalexey If this is a checkbox and you want to see if it's checked or not, instead of getting ToggleState, you can use .selected() instead of .getAttribute().

Thanks a lot! This is exactly what was needed :)
