### ISSUE TITLE
Problem with getting several elements from list

### ISSUE THREAD

**Issue by adrozdowski** [microsoft/WinAppDriver#1118]
I am developing automation tests to my company's warehouse management application. It is written in Windows Forms. My problem is about getting data (Serial Numbers) from List. I get Serial Numbers successfully when count of all Serial Numbers in a list is less than about 300.

Code to get Serial Numbers

```
for (int inc = 1; inc <= Convert.ToInt32(itemLVS.ItemCountLVS); inc++)
{
    itemLVS.ItemSerialNumbers.Add(LVSSession.FindElementByXPath("//ListItem[" + inc + "]/Text[1]").Text);
}
```
 If there are more I get exception: 
 
`OpenQA.Selenium.WebDriverException: 'The HTTP request to the remote WebDriver server for URL http://127.0.0.1:4723/session/7D1517D8-E462-40BF-B113-66A68AF1D067/element timed out after 60 seconds.'`

I think there is a problem with `LVSSession.FindElementByXPath("//ListItem[" + inc + "]/Text[1]`" . It always iterates through entire collection. Is there a hack to overcome this issue and get several elements what I need?

Thank you for help in advance.

**Comment by naeemakram** [comment]
Most likely the XPath element search implementation is broken.
 Perhaps you can do something like below: 
```
var items= LVSSession.FindELementsByTagName("ListItem");
foreach(var i in items)
{
// do some work with i
}
```
I hope this helps.

**Comment by adrozdowski** [comment]
Thank you for your advice but I overcame this issue in other way. I clicked on list in a desktop application. I marked first rows of SNs with details from the top of list using Shift+ArrowDown. Then I copied them to Clipboard. Next I "manipulated" copied string to get only SNs. At the end I added them to my list of SNs.

```
WindowsElement SNList = LVSSession.FindElementByAccessibilityId("lvwSN");
SNList.Click();
LVSSession.Keyboard.PressKey(OpenQA.Selenium.Keys.LeftShift);
LVSSession.Keyboard.PressKey(OpenQA.Selenium.Keys.ArrowUp);
LVSSession.Keyboard.ReleaseKey(OpenQA.Selenium.Keys.ArrowUp);
for (int inc = 1; inc <= Convert.ToInt32(itemLVS.ItemCountLVS); inc++)
{
LVSSession.Keyboard.PressKey(OpenQA.Selenium.Keys.ArrowDown);
}
LVSSession.Keyboard.ReleaseKey(OpenQA.Selenium.Keys.LeftShift);
LVSSession.Keyboard.PressKey(OpenQA.Selenium.Keys.LeftControl);
LVSSession.Keyboard.PressKey("c");
LVSSession.Keyboard.ReleaseKey("c");
LVSSession.Keyboard.ReleaseKey(OpenQA.Selenium.Keys.LeftControl);
string SelectedSNs = string.Empty;
while (true)
{   
   try
   {
      SelectedSNs = Clipboard.GetText();
      if (SelectedSNs != string.Empty)
      {
         break;
      }
   }
   catch (System.Runtime.InteropServices.ExternalException)
   {
      continue;
   }
}
string[] SelectedSNsSplitted = SelectedSNs.Split(new string[] { "\t\r\n" }, StringSplitOptions.None);
SelectedSNsSplitted = SelectedSNsSplitted.Where(w => w != "SN\tKod pozycji\tOpis\tDepozytor" && w != "").ToArray();
foreach(var element in SelectedSNsSplitted)
{
   itemLVS.ItemSerialNumbers.Add(element.Remove(element.IndexOf("\t")));
}
