### ISSUE TITLE
Not able to get the Name/ClassName/AutomationId for Outlook--> Inbox when it has unread msgs

### ISSUE THREAD

**Issue by faizmidway** [microsoft/WinAppDriver#1119]
Hi all,
I am trying to do some automation on my outlook with Winappdriver.
But not able to get the Name/ClassName/AutomationId for outlook --> Inbox when it has mails.

My scenario requires to add "Inbox" to "fav list" of outlook. It is only possible when the inbox has no unread emails as then the element Inbox name is easy to catch up to but when it has unread emails then it's difficult to select inbox. 
 Can anyone please guide me, how can I get "Inbox" id on Outlook that is constant throughout.

**Comment by naeemakram** [comment]
Look into the GitHub repo linked below, I created a few examples with Outlook 2019 in this repo. I am looking for a folder name and it is easy to find. I'm also going through mail items in the list of messages. 
https://github.com/naeemakram/Outlook2019AutomationWinAppDriver

**Comment by faizmidway** [comment]
Thanks alot @naeemakram . Your code solved my problem 👍

**Comment by naeemakram** [comment]
That's great, please note that [here](https://www.udemy.com/course/appium-winappdriver-automation-testing/?couponCode=GITHUBAPRIL2020) I'm teaching a Udemy course about UI test automation with WinAppDriver and C# and the course can be helpful for people looking forward to get started with automation.
