### ISSUE TITLE
Please implement LongPressKeyCode 

### ISSUE THREAD

**Issue by naeemakram** [microsoft/WinAppDriver#1123]
Hi, 

Please implement the method LongPressKeyCode. Right now it is not implemented. A student of my course asked me how could he select multiple items in a listbox by ctrl+click. 

I tried and the following error message was returned by scripts:

Message: Test method WinFormsUITesting.WinFormTests.ListBoxMultiSelectWhileHoldingCtrlKey threw exception: 
OpenQA.Selenium.WebDriverException: Command not recognized: POST: /session/A3FFFD5A-69B4-4EB6-8F4F-CE6C5E41D09F/appium/device/long_press_keycode

**Comment by Jteve-Sobs** [comment]
According to this test on line 94: https://github.com/microsoft/WinAppDriver/blob/master/Tests/WebDriverAPI/SendKeys.cs, control is active the entire time until it is pressed again.

In this example, I first pressed control and then executed the paste command and it pasted 3 times:
```
            DesktopSession.Keyboard.SendKeys(Keys.Control);
            DesktopSession.Keyboard.SendKeys("v");
            DesktopSession.Keyboard.SendKeys("v");
            DesktopSession.Keyboard.SendKeys("v");
```

So you can press control and then execute the clicks to select multiple entries.

**Comment by naeemakram** [comment]
A student of my course complained that this doesn't work all the time. 
If we do it as shown below, it works always: 
`desktopSession.Keyboard.SendKeys(OpenQA.Selenium.Keys.Meta + "s" + OpenQA.Selenium.Keys.Meta);`
