### ISSUE TITLE
Unified Service Desk 4.1 - Dynamics 365 - Automation Help

### ISSUE THREAD

**Issue by jjbright** [microsoft/WinAppDriver#1127]
We have to do test automation in Unified Service Desk 4.1 Dynamics 365.  Can we use WinAppDriver and Appium for test automation?
@timotiusmargo @paulcam206 @hassanuz @yodurr

**Comment by zadjii-msft** [comment]
Hey just as a heads up - I'm not sure that anyone you tagged is actually a member of the WinAppDriver project 😄 

I know that @timotiusmargo is but I don't know who the PM is anymore.

**Comment by anunay1** [comment]
You can check using inspect.exe , if you get the elements in inspect, you are good to go.

**Comment by Shakevg** [comment]
@jjbright Yes, it possible. 
I used WinAppDriver for USD automation.
[You just need to turn on accessibility support](https://github.com/microsoft/WinAppDriver/issues/916#issuecomment-543908600)

**Comment by Navyapalvai** [comment]
Hi @jjbright,
I tried to automate USD 4 using UFT and problem started at case classification fields once after new case is clicked and could not move any further. Please let me know if you find any solution and how you are automating this USD 4. Thanks in advance!

**Comment by jjbright** [comment]
other API's are used, closed #1127

**Comment by Shakevg** [comment]
@jjbright What API are you going to use?
