### ISSUE TITLE
How to correctly start and use on Azure, or doesn't it work?

### ISSUE THREAD

**Issue by a-einstein** [microsoft/WinAppDriver#1136]
I am lost using the WinAppDriver Task in an Azure pipeline.

- I used to start it without parameters, but got a WebDriverTimeoutException (set on 30 seconds).
- I concluded that I had to set IP and port to "127.0.0.1:4723", which I previously assumed to be default. I followed the suggestion in the information, it was also referred to in my own testing code. But now I got "System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:4723".
- I even tried to set the parameters as "127.0.0.1 4723" (without the ':'), but then I was back at the WebDriverTimeoutException.

So, Does it work at all currently? If so, what is the correct way to start and use it?  Or what else am I missing?

**Comment by anunay1** [comment]
I was not able to configure the task in the pipeline because of organisational restriction, so I use power shell script to start and stop win app driver as a work around.

To start  WIN app driver: 
Start-Process -FilePath "C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe"

To stop win app driver: 
Stop-Process -Name "WinAppDriver"

**Comment by a-einstein** [comment]
Hi, I got this working. A couple of remarks which might help others.
- My problems mainly seem to have stemmed from the wrong environment. In fact the above exception is not the real one, I overlooked the familiar 'element could not be located on the page'.
- I got it working with a self hosted interactive agent. Main instructions to follow are over here: [Self-hosted Windows agents](https://docs.microsoft.com/en-gb/azure/devops/pipelines/agents/v2-windows).

**Comment by NikitaTurakhia** [comment]
@a-einstein @anunay1 I have windows application tests that I want to run with azure devops and it gives me below error : 

![image](https://user-images.githubusercontent.com/21182650/207993838-ae07e6fc-9f54-45b5-9ee1-482ad9a1e588.png)

I have my tasks here : 

![image](https://user-images.githubusercontent.com/21182650/207993981-6702983e-80e0-4f6c-9b57-bd34898a8194.png)

and my code for winappdriver is in visual studio below:

![image](https://user-images.githubusercontent.com/21182650/207994140-d474ec63-5da3-4a28-bc23-a6b07bd772e7.png)

Will you please help me why I am getting timeout error on azure pipeline?
