### ISSUE TITLE
Which version do I have installed?

### ISSUE THREAD

**Issue by oatsoda** [microsoft/WinAppDriver#1137]
There appears to be an issue with the versioning.  I have `1.1.1` installed (I think!) but it is reported like this:

![image](https://user-images.githubusercontent.com/3919587/80572607-766c7180-89f6-11ea-92e9-9d5800836688.png)

I don't think there even was a `1.1.4` version!

It would be useful to know which version is installed in case of problems/compatibility.  That could be by correctly setting the File/Assembly versions correctly, or even if there was a command switch e.g. `WinAppDriver.exe -v`

**Comment by icnocop** [comment]
See https://github.com/microsoft/WinAppDriver/issues/604
