### ISSUE TITLE
Double click option is not available in Winappdriver

### ISSUE THREAD

**Issue by viji-123** [Microsoft/WinAppDriver#114]
In my application I have a scenario where i need to double click on an element to open a feature. But **double click** option is not available in Winappdriver. Please enhance winappdriver with double click option .

We have double click option in Selenium Webdriver. Need a similar option in Winappdriver also

Thanks

**Comment by timotiusmargo** [comment]
Hi @viji-123,

Windows Application Driver supports mouse double click as specified in the JSON Wire Protocol. Unfortunately we don't have a sample or test for it yet. If you are writing your test in C# using [Appium .NET driver](https://github.com/appium/appium-dotnet-driver),  you can use the following sample code snippet to perform mouse double click on an element:

`var title = calculatorSession.FindElementByAccessibilityId("AppNameTitle");
calculatorSession.Mouse.MouseMove(title.Coordinates);
calculatorSession.Mouse.DoubleClick(null);`

**Comment by viji-123** [comment]
@timotiusmargo 

Thanks for letting me know.  I will try to implement that !

**Comment by ragham431** [comment]
There is no coordinates for widows element.

var title = calculatorSession.FindElementByAccessibilityId("AppNameTitle");
calculatorSession.Mouse.MouseMove(title.Coordinates);
--
can you please let me know,how to achieve this

**Comment by yodurr** [comment]
please post new questions as new issues, thanks.

**Comment by jnicelap** [comment]
Session.Mouse object is not available in Java.5.0.0-BETA9 for the Java.  When will this get added?  If this is available how will I achieve access to this object.

Code Snippet:
    @BeforeClass
    public static void setup() {
        try {
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability("deviceName", "Windows");
            capabilities.setCapability("app", "Root");
            SymedicalSession = new WindowsDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
