### ISSUE TITLE
How highlighting works?

### ISSUE THREAD

**Issue by luvukr** [microsoft/WinAppDriver#1143]
I am unable to figure out how element highlighting is working. I commented out all implementation of `HighlightPath() `and `NativeMethods.HighlightCachedUI()`. Still, It's highlighting. Can anyone help me out here?

**Comment by anunay1** [comment]
which version of WAD are you using can you share the code for highlighting.

**Comment by luvukr** [comment]
Hi anunay1, Thanks for responding.
Although I found out how it's highlighting. It was getting highlighted from uixpathlib.dll. I was looking into the managed code eventually I found out

**Comment by anunay1** [comment]
@luvukr Can you please share how did you manage to highlight the elements, as I am unable to do so, also it will be helpful for others.
