### ISSUE TITLE
How to remote debug with WinAppDriver on test machine

### ISSUE THREAD

**Issue by Milly89** [microsoft/WinAppDriver#1145]
We start WinAppDriver.exe with below command line on test machine, can't start the driver:
C:\Program Files (x86)\Windows Application Driver> runas /user:Administrator "WinAppDriver.exe the ip of test machine 4723"
Also had tried on dev machine with below command line :
runas /user:Administrator "WinAppDriver.exe the ip of test machine 4723"

**Comment by anunay1** [comment]
What exactly are you trying to achieve?

**Comment by meilinfan** [comment]
The driver can’t be started and only splash one time then disappeared




| |
范美林
邮箱：meilinfan@163.com
|

签名由 网易邮箱大师 定制

On 05/08/2020 02:02, anunay1 wrote:

What exactly are you trying to achieve?

**Comment by pm90pl** [comment]
Run WAD from opened cmd (to have WAD exit output not disappeared) and give us the message you're receiving .
