### ISSUE TITLE
Interacting with element where IsKeyboardFocusable equals false

### ISSUE THREAD

**Issue by Tree55Topz** [microsoft/WinAppDriver#1152]
I can not figure out why I can not interact with this element..

The only thing that seems to make sense is that the IsKeyboardFocusable property is set to false. Does this prevent WinAppDriver from actually interacting with this element? From the screenshot you can see I have a unique AutomationId.

I try to access it like 
`session.FindElementByAccessibilityId("ItemsControlScrollViewer")`

But it does not work.. I get element not found error..

Is it because of this property? Is there a way to ignore this if so?

![image](https://user-images.githubusercontent.com/15693599/81699946-01595d00-9436-11ea-8ca3-e39a488fe9cd.png)

**Comment by anunay1** [comment]
Is the element part of the same tree
