### ISSUE TITLE
sendKey throw excption

### ISSUE THREAD

**Issue by WaterIsWater** [Microsoft/WinAppDriver#116]
Hello
First of all, Thanks you for this great program.

I used WinAppDirver for UniversialWindowsApp.
During UI test, my test code finds TextBox with automationID.
and uses 'SendKey' method.
But exception is occured.
System.InvalidOperationException: An unknown error occurred in the remote end while processing the command.

Sample Code is below.
----------------
IOSElement testTextBox = SamsungNotesSession.FindElementByAccessibilityId("Text_box_for_test");
Assert.IsNotNull(testTextBox);
testTextBox.SendKeys("This is test"); <= this point.

Questions,
1. Is it impossible that TextBox uses SendKey mthod?
2. If yes, how to set text for TextBox?

Thank you very much.

**Comment by timotiusmargo** [comment]
Hi @WaterIsWater!

It is absolutely possible to use SendKey on UWP TextBox elements. You can see some examples from the samples and tests below:
https://github.com/Microsoft/WinAppDriver/blob/v0.7-beta/Samples/C%23/AlarmClockTest/Scenario.cs#L187
https://github.com/Microsoft/WinAppDriver/blob/v0.7-beta/Tests/W3CWebDriver/Back.cs#L37

You can also the [Inspect tool](https://github.com/Microsoft/WinAppDriver#inspecting-ui-elements) to ensure that the element retrieved from the Text_box_for_test is indeed TextBox/EditControl.

**Comment by WaterIsWater** [comment]
Hi @timotiusmargo 
Thank you very much.

With your comments, I re-checked my test code and tried to test it.
But I could not find solution.
And I tried AlarmClockTest in Sample folder, I found same exception on it.
https://github.com/Microsoft/WinAppDriver/blob/v0.7-beta/Samples/C%23/AlarmClockTest/Scenario.cs#L186
It's called Clear() for TextBox. and InvalidException is occured.

1. Could you please check this? If you have more information about environment, please let me know that.
2. I'm stranger in OpenSource (github). In this case, I want to debug this error, for that, what can i do or how can i do? 

Thank you in advanced.

**Comment by timotiusmargo** [comment]
Hi @WaterIsWater,

Could you please ensure that you are running the latest WinAppDriver (i.e. [v0.7-beta](https://github.com/Microsoft/WinAppDriver/releases/tag/v0.7-beta)? It would also be useful to paste the log from the `WinAppDriver.exe` console window especially the one that sends the `Clear `and `SendKeys`.

**Comment by WaterIsWater** [comment]
Hi @timotiusmargo,

The below is log for Clear().
--------------------
==========================================
POST /session/49049406-011D-4BBE-B576-7BBFF44D7D47/element HTTP/1.1
Accept: application/json, image/png
Content-Length: 55
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"using":"accessibility id","value":"AlarmNameTextBox"}
HTTP/1.1 404 Not Found
Content-Length: 139
Content-Type: application/json

{"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}
---------------------------------
If you need more information, please let me know.

Thanks you very much.

**Comment by timotiusmargo** [comment]
Hi @WaterIsWater,

Thank you for the log. The error in the log above shows that element with AlarmNameTextBox accessibility id could not be found. If you have the alarm app launching and interactable, you may be running an older version of Windows 10 that is not in synced with the AlarmClock sample. This is something on our part that we will improve by making the samples work with all latest version of Windows 10.

To get to the original issue you reported, could you use the Edge browser text box as shown in the test below?
https://github.com/Microsoft/WinAppDriver/blob/v0.7-beta/Tests/W3CWebDriver/Back.cs#L37

The Edge browser text box should take the string you passed through the Element.SendKeys method.

**Comment by WaterIsWater** [comment]
Hi @timotiusmargo,

Thank you for your comment.
And Happy New Year!

I checked Edge Browser with your comment.
From Inspect.exe, 'addressEditBox' is RichEditBox class.
But in my test code, sendkey is not working for TextBox class .

PS.Edge Browser version is 'Microsoft Edge 38.14393.0.0'

Thank you very much.

**Comment by wuarthur** [comment]
I have the same problem, I can use sendKey() for richtextboxes but not Textboxes in my WPF program

**Comment by timotiusmargo** [comment]
The `SendKeys` test scenario in the `TextBox` test class below showcases how you can send keyboard input to a simple text box UI control.
https://github.com/Microsoft/WinAppDriver/blob/master/Tests/UWPControls/TextBox.cs

Please follow the instruction and run the test to see it in action.

**Comment by byunghwl** [comment]
Both sendKey() or Keyboard.SendKeys() throws the following error for WPF textbox:  
`{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}`

**Comment by byunghwl** [comment]
The issue was solved after putting IsReadOnly="False" into Textbox. This trick seems to make LegacyIAccessible.Role: to be "Editable".
