### ISSUE TITLE
Cannot create a new Actions object using WAD Desktop Session driver object

### ISSUE THREAD

**Issue by pradeipp** [microsoft/WinAppDriver#1173]
I tried creating an Actions object using WAD but, while executing it, I got this error:

> System.ArgumentException : **The IWebDriver object must implement or wrap a driver that implements IHasInputDevices.**
> Parameter name: driver

Here's how my desktop session instantiation looks:
```C#
var options = new AppiumOptions();
options.AddAdditionalCapability("app", "Root");
options.AddAdditionalCapability("deviceName", pcName);
desktopSession = new WindowsDriver<WindowsElement>(new Uri(winAppDriverURL), options);
```

And when I try to create a new Actions object, 

```C#
Actions actionObject= new Actions(desktopSession);
```
and when I try to execute it, it gives me the aforementioned error. 
> System.ArgumentException : **The IWebDriver object must implement or wrap a driver that implements IHasInputDevices.**
> Parameter name: driver

_Note: I don't get any compiler error, the error is only thrown at runtime._
What could I be missing? 
I saw other code snippets online and none seem to use the `new WindowsDriver<WindowsElement>` method to create a session

**Comment by anunay1** [comment]
It works perfectly for me. Please find the project as attached.
[UnitTestProject11.zip](https://github.com/microsoft/WinAppDriver/files/4690769/UnitTestProject11.zip)

**Comment by pradeipp** [comment]
Hi @anunay1 
Yes it doesn't throw any compiler error but could you run it?

**Comment by anunay1** [comment]
Yes

**Comment by pradeipp** [comment]
Looks like my desktop session wasn't instantiated properly somehow. Now it works, thanks @anunay1 for your help.
