### ISSUE TITLE
Mouse click offsets unavailable

### ISSUE THREAD

**Issue by daghb** [Microsoft/WinAppDriver#118]
I use the WinAppDriver to test a WPF app with some custom controls from a third party control provider. One of these controls is a split button control, but I cannot use the WinAppDriver to click on the secondary button inside this control. When clicking using WinAppDriver, I hit the wrong button.

The element returned from the FindElementByAccessibilityId method gives me the coordinates of the element by using the Coordinates property, but currently, there is no way to offset a mouse click event. I can move the mouse by using 

    session.Mouse.MouseMove(element.Coordinates, offsetX, offsetY)

but no method exists to either click using offsets or click using the current mouse position. I'd wish there would be methods like

    session.Mouse.Click() // Click on current coordinate
    element.Click(offsetX, offsetY) // Click on current element with offset

Workarounds welcome!

**Comment by timotiusmargo** [comment]
Hello @daghb,

The missing API surface you mentioned is an issue with [appium-dotnet-driver](https://github.com/appium/appium-dotnet-driver) or other language specific appium client. However, you can do use the following simple methods to perform exactly the same behavior:

```
session.Mouse.MouseMove(element.Coordinates, offsetX, offsetY);
session.Mouse.Click(null);
```

For example:
```
session.Mouse.MouseMove(buttonElement.Coordinates, 50, 20);
session.Mouse.Click(null);
```

This is obviously not very apparent and we may either add the convenient API in the other project (appium-dotnet-driver) or simply provide better examples in this project. Thanks for bringing this up. You were extremely close to the workaround above.

**Comment by daghb** [comment]
Thanks, @timotiusmargo! I was just a <null> value away!

I made another workaround by introducing key bindings in the testable client instead and sending the bound keys to the client, thus bypassing the need for clicking on the target.
