### ISSUE TITLE
We cannot use WinApp driver for project targeting framework as .NetCore

### ISSUE THREAD

**Issue by Pratiky2j007** [microsoft/WinAppDriver#1180]
I have created a project whose target framework is .NetCore 2.2, but when I install nuget package for WinApp Driver it gives a warning that this package is not compatible with the target framework. So how can I use WinApp driver for .NetCore framework

**Comment by anunay1** [comment]
you need to install Appium drivers.

**Comment by anunay1** [comment]
I tried with netcoreapp3.0 and it works.

**Comment by anunay1** [comment]
it works also with .NET core 2.2 also 
![image](https://user-images.githubusercontent.com/7989610/83532564-09c02780-a50c-11ea-990b-9d4873e55df7.png)

**Comment by Pratiky2j007** [comment]
Could you please let me know which nuget package are you using for WinAppDriver

**Comment by anunay1** [comment]
![image](https://user-images.githubusercontent.com/7989610/83600891-37998080-a58d-11ea-87ac-dd056809af2d.png)

**Comment by anunay1** [comment]
Try this.

**Comment by Dima-Kal** [comment]
> Try this.

Trying this nuget is not compatible with samples provided here, it does not allow using DesiredCapabilities

**Comment by Pratiky2j007** [comment]
AppiumOptions appCapabilities = new AppiumOptions();
                appCapabilities.AddAdditionalCapability("app", pathOfApplication exe file);
                appCapabilities.AddAdditionalCapability("deviceName", "WindowsPC");
                session = new WindowsDriver<WindowsElement>(new Uri("path displayed when launched WinAppDriver"), appCapabilities);

                session.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(15);
