### ISSUE TITLE
editBox.SendKeys(TextValue) in localolized OS (FRA) send US keys

### ISSUE THREAD

**Issue by testaca** [Microsoft/WinAppDriver#119]
Hello,

I have tried on my FRA system the notepad sample, and the sent text in the edit is incorrect.
As you can see hereafter, the text is displayed in "Bloc-notes" as This is qn quto,qted test on Clqssic Windozs Applicqtion!09:25 28/12/2016
![winappdriver-sans titre - bloc-notes](https://cloud.githubusercontent.com/assets/24806333/21517913/091c6a28-cce3-11e6-9478-27841fa43445.png)

Regards.

**Comment by yodurr** [comment]
The device where the tested app is running needs to be set to US keyboard layout per the json wire protocol spec:
https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidelementidvalue
