### ISSUE TITLE
Double click using Actions throw an error

### ISSUE THREAD

**Issue by ahaleaditya** [microsoft/WinAppDriver#1191]
Hi,

While performing double click in the application it gives error "An element could not be found", but when I do click() operation it works with no problem

Below is my code for double click to open a project:
```
var selectProj = lbProj.FindElementByName(projectName);

            Actions actions = new Actions(CommonManager.autoSession);
            actions.MoveToElement(selectProj).Click().DoubleClick().Build().Perform();
```
While performing the same code to open an application it works well, but while opening the project it throws an error even though the selectProj.Click() seems to work fine

**Comment by erohinalexey** [comment]
Hi, this code works for me:

`    public void doubleClick(By by) {
        WebElement element = getActions.getElement(by);
        actions.doubleClick(element).build().perform();
    }`

Why do you use also .Click() method?

**Comment by ahaleaditya** [comment]
Hi, your code works for Java I guess. I am using C# and I used .Click() because it was mentioned in issue [https://github.com/microsoft/WinAppDriver/issues/344](url)

**Comment by VijayHugar** [comment]
You can try below code(C#), this works for us.

Actions actions = new Actions(CommonManager.autoSession);
actions.DoubleClick(selectProj).Perform();

**Comment by ahaleaditya** [comment]
@VijayHugar  This works Thank you so much!!
