### ISSUE TITLE
Testing a running AUT

### ISSUE THREAD

**Issue by fasterfish** [Microsoft/WinAppDriver#12]
Can I test the already running application or this feature is not yet implemented?

**Comment by alakshmi1030** [comment]
Yes you can, specifically for single-instance modern apps.

**Comment by timotiusmargo** [comment]
The built in Windows 10 Alarms & Clock is an example of single-instance modern apps. A sample test can be found on: https://github.com/Microsoft/WinAppDriver/tree/master/Samples/AlarmClockTest

With this sample, you can have the application running before starting the test. In such case the test will be performed on the already running application.

**Comment by fasterfish** [comment]
So to test the running application, need i to specify the DesiredCapability "app" to value "Root"?

**Comment by timotiusmargo** [comment]
Hi @fasterfish,

To test an already running application, simply set the **app** capabilities to the **appId** the same way you would do it when the application is not running. E.g.

```
DesiredCapabilities appCapabilities = new DesiredCapabilities();
appCapabilities.SetCapability("app", "Microsoft.WindowsAlarms_8wekyb3d8bbwe!App");
AlarmClockSession = new IOSDriver<IOSElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities);
```

Setting the **app** capabilities to **root** will give you the **root UI element** (desktop) session that you can use to access the peripheral UI such as **toast notifications**.
