### ISSUE TITLE
Having the tests open the WPF Application

### ISSUE THREAD

**Issue by evansct** [microsoft/WinAppDriver#1209]
I am trying to use Appium to test my WPF application using automation, and I am running into an interesting error. I can get everything working fine if the app is already opened when I got to run the tests and everything passes, but something that I would like for it to do is to open the app when I start the test. The setup method that is run at the beginning of the test looks like this: 

```
public static void Setup(TestContext context)
{
    // Sets up the session so that testing can be done on the application
    if (session == null)
    {
        // Create a new session to bring up an instance of the app
        var capabilities = new AppiumOptions();
        capabilities.AddAdditionalCapability("app", AppId);
        capabilities.AddAdditionalCapability("platformName", "Windows");
        capabilities.AddAdditionalCapability("deviceName", "WindowsPC");
        session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), capabilities);

        Assert.IsNotNull(session);
        Assert.IsNotNull(session.SessionId);

        // Set implicit timeout to 1.5 seconds to make element search to retry every 500 ms for at most 3 times(??)
        session.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(1.5);
    }
}
```

And again, when I go to run the test, if the application is not open, I get the following exception: `OpenQA.Selenium.WebDriverException: OpenQA.Selenium.WebDriverException: Failed to locate opened application window with appId: AppId, and processId: 26896`

Is there any way to make is so that you can fix this so that the tests will open the application instead?

**Comment by liljohnak** [comment]
@evansct Try using the path to the Application that is what we use. `capabilities.AddAdditionalCapability("app", "App.exe");`

**Comment by evansct** [comment]
That's what I'm doing as well, I saw somewhere that the appid for a WPF app has to be the path to the executable, so that's what I was using.

**Comment by anunay1** [comment]
You can use a try and catch block. In the catch block create a session with root and attach the session to the top level window of you app. 

You can also attach a process please have a look #1091

**Comment by anunay1** [comment]
You can get more info in the wiki.

**Comment by evansct** [comment]
@anunay1 I'm looking into that, will try to see if I can get it working from there tomorrow! Thank you

**Comment by evansct** [comment]
@anunay1 I'm looking into it now, and I'm not sure I understand what attaching the process would do. If the process is already running it finds it fine. I'm trying to have the tests start the application (and therefore process) when I go to run the application. It may also just be that I don't fully understand what the try/catch block is actually doing.

Also, just an update to the original question as well, but I tried using Process.Start() and that didn't seem to work either. I'm not sure if it's because of the application, or if I'm just doing something incorrectly.

**Comment by anunay1** [comment]
What you are doing is correct. As I also do the same way what you are doing, but if the application does not even start with Process.Start that that is a problem with you application, we can have a hangout call(I am available now)anunayathakur1@gmail.com

**Comment by evansct** [comment]
I was doing a bit more looking and I found this stackoverflow question that fixed the issue. For whatever reason I just had to set the working directory to the path of the WPF app. But this is solved now!

https://stackoverflow.com/questions/19969693/launch-wpf-application-using-process-start
