### ISSUE TITLE
OpenQA.Selenium.WebDriverException while creating an object for Windows Driver

### ISSUE THREAD

**Issue by MahVer** [microsoft/WinAppDriver#1211]
I am facing "OpenQA.Selenium.WebDriverException" very frequently when I execute the unit test.
I had executed WinAppDriver.exe with admin rights and when I execute the unit test it throws an exception. This exception is primarily observed after adding the Desired Capabilities.
Below is the code snippet where this exception is observed.

`AppiumOptions capabilities = new AppiumOptions();
 capabilities.AddAdditionalCapability("app", "Root");
 WindowsDriver<WindowsElement> localSession = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), capabilities);`

Issue is observed when creating WindowsDriver object.

Exception Details:
OpenQA.Selenium.WebDriverException: 'Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 127.0.0.1:4723
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Appium.Service.AppiumCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)'

NOTE: 
1. Added WinAppDriver to the Firewall exception list. 
2. It opens the application but throws the above exception on line where we create object localSession.

Kindly let me know where the issue is and how do I fix it permanently.
I am new to Automation Development environment.

Thanks in advance.

**Comment by anunay1** [comment]
WindowsDriver<WindowsElement> localSession = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), capabilities,TimeSpan.FromMinutes(3));

**Comment by anunay1** [comment]
Can you try the above?

**Comment by MahVer** [comment]
Thanks @anunay1 for suggestion.
I realized that splash screen was blocking my way. Hence I added below code which fixed the issue.
`var currentWindowHandle = session.CurrentWindowHandle;
Thread.Sleep(TimeSpan.FromSeconds(5));
var allWindowHandles = session.WindowHandles;
 session.SwitchTo().Window(allWindowHandles[0]);`

But there is another issue which I have updated in my question.
It will be grateful if you can suggest some fix for that.

**Comment by anunay1** [comment]
Whats the other issue?

**Comment by MahVer** [comment]
Below is the details of the issue which I am facing post fixing the above one.

I want to click on the first menu item (Options) and then select the first sub menu item (One). Below is the code snippet.

WebDriverWait wdv = new WebDriverWait(session, TimeSpan.FromSeconds(10));
foreach (var element in menuItem)
{
    if (!string.IsNullOrEmpty(element.Text))
    {
        if (element.GetAttribute("Name").Equals("Options"))
        {
            element.Click();
            var optionsMenuItem = element.FindElementByName("One");
            wdv.Until(x => element.Displayed);
            optionsMenuItem.Click();
         }
    }
}
Here it is able to find the 'Options' menu item but when I perform Click() operation on it, it throws the below exception.
![Exception](https://user-images.githubusercontent.com/67688247/86459426-60f02c80-bd44-11ea-8937-f8b4ca432927.JPG)

**Comment by anunay1** [comment]
Nothing wrong with your code, what is the value of IsKeyboardFocusable: in inspect.

**Comment by MahVer** [comment]
Thanks @anunay1 for pointing out to this. 
The IsKeyboardFocusable property is True but it was my mistake that I accidentally moved the mouse pointer before it tracks and clicks the menu item.
