### ISSUE TITLE
Not able to access an desktop uwp app element which has only automationid to locate.

### ISSUE THREAD

**Issue by shibananda21** [microsoft/WinAppDriver#1214]
Not able to access an UWP app element by automationid. Please help.

**Comment by Tree55Topz** [comment]
Need more details to help you... What are you seeing on the spy tool?

**Comment by shibananda21** [comment]
Hi,
Thank You for your response.
From spying tool i am getting only automationid and processid,except this all places are blank " ". I am using python3 for current project. I am trying to acces this particular element, which api i should choose to access this[find_element_by_?].I cant use process id as it is keep on changing after every fresh start.

**Comment by Tree55Topz** [comment]
find_element_by_accessibility_id
