### ISSUE TITLE
Please wait Dialog

### ISSUE THREAD

**Issue by kverm41** [microsoft/WinAppDriver#1215]
Hi,
I am using WinAppDriver to automate my desktop application but i am stuck where a Please wait dialog comes as attached in the issue, How to put a wait statement to wait till that please wait Dialog disappears .

![image](https://user-images.githubusercontent.com/53211166/86508737-0f0cdc80-be00-11ea-9e35-947db0053709.png)

As it disappears in a while, I am unable to get its locators.

Thanks in advance !

**Comment by Druzle** [comment]
Why was this closed. No comment ?
