### ISSUE TITLE
Wait till element Disappears

### ISSUE THREAD

**Issue by kverm41** [microsoft/WinAppDriver#1216]
I am using WinappDriver to automate desktop applications. I am having a "Please wait" progress bar with name locator="status" and i have added a wait statement to wait till this progress bar disappears as below:

public static void WaitUntilConditionIsMet(int timeoutInSeconds, string status )
        {
            var wait = new DefaultWait<WindowsDriver<WindowsElement>>(Session)
            {
                Timeout = TimeSpan.FromSeconds(timeoutInSeconds),
                PollingInterval = TimeSpan.FromSeconds(1)
            };
            wait.IgnoreExceptionTypes(typeof(InvalidOperationException));
            wait.Until(session =>
            {
                var elementUnderTest = Session.FindElementByName(status );
                return elementUnderTest==null;

            });
        }
But it is not working. Can anyone help me out in what other condition i can provide to make it happen?

Thanks in Advance !

**Comment by Tree55Topz** [comment]
Yeah this approach will not work well in cases where you are trying to validate something is not there.

This can be achieved using the FindElements rather than FindElement. When you use FindElements, you can then get the Count. This will not care if it is zero or not. From here you can just wrap this in a while loop. So something like...

int currentTime = 0;
int maxTime = 30;
bool complete = false;

```
while (currentTime < maxTime && !complete){
     
     var elements = _driver.FindElementsByName("...");
  
     if (elements.Count == 0){
          complete = true;
     } else {
          currentTime++
     }
}
```

**Comment by kverm41** [comment]
Thanks for the help ! It worked :)

**Comment by sweiguny** [comment]
```c#
public bool WaitUntilElementBecomesInvisible(WindowsElement element)
{
    WebDriverWait wait = new WebDriverWait(this.session, TimeSpan.FromSeconds(5));

    wait.Until((IWebDriver Driver) => { return !element.Displayed; });

    return !element.Displayed;
}
```
With this Method you can use the `wait.until` method.
