### ISSUE TITLE
Program closes unexpected on UI access

### ISSUE THREAD

**Issue by JoppeJoppinger** [microsoft/WinAppDriver#1218]
**The problem**
Running a test with WinAppDriver and Appium.Webdriver sometimes ends in an unexpected exit of the tested program - it just closes. No errors, no message. Just like clicking the "Close" button.
The behavior is not really reproducable, not every test fails in this behavior. A test can run 10 times, and then it suddenly stops again.
Appium.Webdriver runs on a test agent and accesses a remote machine running WinAppdriver.

**Environment**
Appium.Webdriver 4.1.1

Desktop OS/version used to run Appium: Windows 10
Real device or emulator/simulator: -Real Device over CLI

**Details**
Since there's no really exception or error in the log, I can't give you anything.
If WinAppDriver tries to click again on a window Element, it fails with the specific exceptions, because it cannot find any window element. I am testing native windows programs.
As I'm new in this area, I'd please you to tell me exactly how I can help you finding my problem. Hopefully we can manage that.
By the way, the closing happens with every selected program, so it's not program specific.
Thank you in advance for your help.

Log of test itself, after the error:
```
2020-07-06T09:47:50.8429838Z ##[error]Error Message:
2020-07-06T09:47:50.8430560Z ##[error] Test method UpdateService.SystemTest.KusReleaseTests.InstallAndDeinstallMsiOnController threw exception:
2020-07-06T09:47:50.8431011Z ##[error]OpenQA.Selenium.WebDriverException: An element command failed because the referenced element is no longer attached to the DOM.
2020-07-06T09:47:50.8431321Z ##[error]Stack Trace:
2020-07-06T09:47:50.8431633Z ##[error] bei OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
2020-07-06T09:47:50.8431957Z ##[error] bei OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary2 parameters) 2020-07-06T09:47:50.8432601Z ##[error] bei OpenQA.Selenium.Appium.AppiumDriver1.Execute(String driverCommandToExecute, Dictionary2 parameters) 2020-07-06T09:47:50.8432923Z ##[error] bei OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary2 parameters)
2020-07-06T09:47:50.8433237Z ##[error] bei OpenQA.Selenium.Remote.RemoteWebElement.get_Text()
2020-07-06T09:47:50.8433561Z ##[error] bei OpenQA.Selenium.Appium.AppiumWebElement.<get_Text>b__8_0()
2020-07-06T09:47:50.8433891Z ##[error] bei OpenQA.Selenium.Appium.AppiumWebElement.CacheValue(String key, Func`1 getter)
2020-07-06T09:47:50.8434196Z ##[error] bei OpenQA.Selenium.Appium.AppiumWebElement.get_Text()
```

**Comment by anunay1** [comment]
2020-07-06T09:47:50.8431011Z ##[error]OpenQA.Selenium.WebDriverException: An element command failed because the referenced element is no longer attached to the DOM.

The exception that you are getting is an stale element exception i.e. you application is refreshing and the element is no longer a part of DOM. 

when you get this exception, in the catch block you again need to search for the element. 

The moment there is any exception, the test runner calls the clean up attribute &  the driver.quit() will close the application.

**Comment by JoppeJoppinger** [comment]
Hello and thank you for your answer. 
Your info is right, but then I would be able to catch an exception during the execution in the moment the application closes. This isn't happening. I only get an exception after the application closes - the WebDriverException because the element  can not be found. 
Perhaps I didn't understand you correctly, or have less knowledge about working with the webdriver. 
If you have an idea I'd be happy to hear from you. Meanwhile I will try to get more informations about the bug. 
If you have no idea and you think this is no bug then we can close this issue.

**Comment by anunay1** [comment]
if the application closed then the exception would be different "Currently selected window is closed." but that does not seem to be the case with you, I assume that you application is crashing.

**Comment by anunay1** [comment]
In case if you need to discuss more we can have a hangout call anunayathakur1@gmail.com

**Comment by JoppeJoppinger** [comment]
Since the tested program doesn't crash, just closing as someone pressed the "Close" button, it thought it could be our wrapper of Appium.Webdriver. But also here, no Exception is thrown (except Error 500 after the program closes). But this is just the symptome, not the cause...
I'm just writing an endurance test without this wrapper and try to open Notepad.exe (and our program) many times. Let's see if something happens. 
Is there a way to enable more logging on WinAppDriver? Is there any logfile? I just pipe out the logs from cli...they are not really useful for my problem I think...

**Comment by liljohnak** [comment]
@JoppeJoppinger Some of our testers get this by hitting the Enter key when the dialog is in focus.  Do your tests have anything like that?

**Comment by JoppeJoppinger** [comment]
No, not at all. It happens random on each access to the window. Just tried to reproduce it with notepad.exe, and I think I have the same issue here: 

`namespace UnitTestProject2
{
   using System;

   using Microsoft.VisualStudio.TestTools.UnitTesting;

   using OpenQA.Selenium.Appium.Windows;

   [TestClass]
   public class UnitTest1
   {
      #region Properties

      private static WindowsDriver<WindowsElement> NotepadSession { get; set; }

      #endregion

      #region Public Methods and Operators

      [ClassCleanup]
      public static void TestClassDeinit()
      {
         NotepadSession.CloseApp();
      }

      [ClassInitialize]
      public static void TestInit(TestContext testContext)
      {
         var appiumOptions = new OpenQA.Selenium.Appium.AppiumOptions();
         appiumOptions.AddAdditionalCapability("app", @"C:\Windows\System32\notepad.exe");
         appiumOptions.AddAdditionalCapability("appArguments", @"MyTestFile.txt");
         appiumOptions.AddAdditionalCapability("appWorkingDir", @"C:\test\");
         NotepadSession = new WindowsDriver<WindowsElement>(new Uri("http://kleinmane:4723"), appiumOptions);
      }

      [TestMethod]
      public void TestMethod1()
      {
         int count = 0;
         while (true)
         {
            count++;
            // Use the session to control the app
            NotepadSession.FindElementByClassName("Edit").SendKeys("This is test number " + count + " \n");
            NotepadSession.FindElementByName("Edit").Click();
            NotepadSession.FindElementByName("Format").Click();
            NotepadSession.FindElementByName("View").Click();
         }
      }

      #endregion
   }
}`

It ends in an "ServerError 500" without further information and loads of exceptions after about 30 minutes, notepad closes then. 
I'm not sure if it's the same error but it looks like the same.

**Comment by liljohnak** [comment]
@JoppeJoppinger I see one error, maybe a suggestion/question, try to resolve these and then try again.
```
NotepadSession.FindElementByClassName("Edit").SendKeys($"This is test number {count}"); //Need to change to string unless you are in python land :)
NotepadSession.FindElementByClassName("Edit").SendKeys(Keys.Enter);
```
Also, the test will timeout since it has no way of getting out of the while loop?  Maybe put a timer to exit?

**Comment by JoppeJoppinger** [comment]
> Also, the test will timeout since it has no way of getting out of the while loop? 

That's just my try to reproduce, as our tests working very long (about 10 minutes per test, session is restored after each test)
The only way I got a similar result to the described error was this way. 
How long can a session be active in WinAppDriver?

**Comment by anunay1** [comment]
> No, not at all. It happens random on each access to the window. Just tried to reproduce it with notepad.exe, and I think I have the same issue here:
> 
> `namespace UnitTestProject2
> {
> using System;
> 
> using Microsoft.VisualStudio.TestTools.UnitTesting;
> 
> using OpenQA.Selenium.Appium.Windows;
> 
> [TestClass]
> public class UnitTest1
> {
> #region Properties
> 
> ```
>   private static WindowsDriver<WindowsElement> NotepadSession { get; set; }
> 
>   #endregion
> 
>   #region Public Methods and Operators
> 
>   [ClassCleanup]
>   public static void TestClassDeinit()
>   {
>      NotepadSession.CloseApp();
>   }
> 
>   [ClassInitialize]
>   public static void TestInit(TestContext testContext)
>   {
>      var appiumOptions = new OpenQA.Selenium.Appium.AppiumOptions();
>      appiumOptions.AddAdditionalCapability("app", @"C:\Windows\System32\notepad.exe");
>      appiumOptions.AddAdditionalCapability("appArguments", @"MyTestFile.txt");
>      appiumOptions.AddAdditionalCapability("appWorkingDir", @"C:\test\");
>      NotepadSession = new WindowsDriver<WindowsElement>(new Uri("http://kleinmane:4723"), appiumOptions);
>   }
> 
>   [TestMethod]
>   public void TestMethod1()
>   {
>      int count = 0;
>      while (true)
>      {
>         count++;
>         // Use the session to control the app
>         NotepadSession.FindElementByClassName("Edit").SendKeys("This is test number " + count + " \n");
>         NotepadSession.FindElementByName("Edit").Click();
>         NotepadSession.FindElementByName("Format").Click();
>         NotepadSession.FindElementByName("View").Click();
>      }
>   }
> 
>   #endregion
> ```
> 
> }
> }`
> 
> It ends in an "ServerError 500" without further information and loads of exceptions after about 30 minutes, notepad closes then.
> I'm not sure if it's the same error but it looks like the same.

The default timeout for any test case is 30 minutes, after that clean up method is called, if you need to increase the timeout, then  use the Timeout attribute to increase the timeout. 

e.g. Timeout(60), please note that the time is in minutes.

**Comment by anunay1** [comment]
@JoppeJoppinger if you want infinite time use this Timeout(TestTimeout.Infinite)

**Comment by JoppeJoppinger** [comment]
Excuse the silly question, but where should I set the tiomout? 
Do you mean the session-ImplicitWait?


```
 protected WindowsDriver<WindowsElement> CreateWindowsDriverWithRetry(AppiumOptions appiumOptions, int retries, TimeSpan retryDelay,
         TimeSpan driverAttachTime)
      {
         var policy = Policy.Handle<WebDriverException>(FilterNonAvailability).WaitAndRetry(retries, i => retryDelay);
         var session = policy.Execute(() => CreateWindowDriver(appiumOptions));

         Thread.Sleep(driverAttachTime);
         session.Manage().Timeouts().ImplicitWait = ImplicitWaitTimeout;

         return session;
      }
```

**Comment by anunay1** [comment]
> Excuse the silly question, but where should I set the timeout?
> Do you mean the session-ImplicitWait?
> 
> ```
>  protected WindowsDriver<WindowsElement> CreateWindowsDriverWithRetry(AppiumOptions appiumOptions, int retries, TimeSpan retryDelay,
>          TimeSpan driverAttachTime)
>       {
>          var policy = Policy.Handle<WebDriverException>(FilterNonAvailability).WaitAndRetry(retries, i => retryDelay);
>          var session = policy.Execute(() => CreateWindowDriver(appiumOptions));
> 
>          Thread.Sleep(driverAttachTime);
>          session.Manage().Timeouts().ImplicitWait = ImplicitWaitTimeout;
> 
>          return session;
>       }
> ```

No not the implicit wait, you need to declare the timeout where you declare the test method something like: 
 [TestMethod]
 [Description("Test infinitely"), Timeout(TestTimeout.Infinite), TestCategory("Performance"),  ]

**Comment by anunay1** [comment]
@JoppeJoppinger Did it work?

**Comment by JoppeJoppinger** [comment]
Can't tell you right now, just changed the tests to your suggestion, they're running overnight. Will tell you as soon as I know more.

**Comment by JoppeJoppinger** [comment]
So it seems my tests ran without errors this night - if the next run is also okay then I think you found my problem. 
Don't know how to thank you @anunay1, you helped me a lot.

**Comment by JoppeJoppinger** [comment]
Our tests are green! It's really dependent on that timout @anunay1  marked as solution. 
So now I'm not sure if there's a misfunction because each of our test opens and closes a new solution and none of them take over 30 minutes but I will check that by time again. Eventually we can close this issue, reopening one if I find something new. Thank you very much for your help.
