### ISSUE TITLE
Running WinAppDriver under a Selenium Grid

### ISSUE THREAD

**Issue by Tecuanotl** [Microsoft/WinAppDriver#122]
Hello,  
I'm trying to use the WinAppDriver under a Selenium Grid. I setup a Hub and a Node with Selenium 3.0.1. 

- The Hub has the standard Selenium config (java.exe -jar selenium-server-standalone-3.0.1.jar -role hub -hubConfig  %DEFAULTHUBCONFIG% -port %DEFAULTHUBPORT%) 

- The Node is configured like this: java.exe **-Dwebdriver.ie.driver=WinAppDriver.exe** -jar selenium-server-standalone-3.0.1.jar -role node -hub %hubAddress% -nodeConfig %nodeConfigLocation%
Where the config is the default config from [here](https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/common/defaults/DefaultNodeWebDriver.json )

I run this code:
`var capabilitiesDesktopApp = DesiredCapabilities.InternetExplorer();
capabilitiesDesktopApp.SetCapability("app", "Root");
var capabilitiesCortanaApp = DesiredCapabilities.InternetExplorer();
driverDesktop = new RemoteWebDriver(new Uri(localDevHub), capabilitiesDesktopApp);`

I get an error (see [Log.txt](https://github.com/Microsoft/WinAppDriver/files/685903/Log.txt)) on the Node and then nothing happens.  

Has anyone successfully configured WinAppDriver to work in a Selenium grid? What's your configuration? 

Thanks!

**Comment by Tecuanotl** [comment]
# **Instructions to setup Appium with WinAppDriver on the node VM**
## Install Appium and dependencies
1. Install Java Development Kit
1. Add to the Environment Variables JAVA_HOME and set it to the base path of your installation, for example "C:\Program Files\Java\jdk1.8.0_121"
1. Add to the Path environment variable the folder where "Jar.exe" is located, for example, you'd add "C:\Program Files\Java\jdk1.8.0_121\bin" to the path
1. Download latest node and npm tools MSI (version >= 6.0) and install it. 
1. Verify that the npm and nodejs paths are in your PATH environment variable. If not, add them manually to the PATH, should be: %APPDATA%\npm;C:\Program Files\nodejs\
1. Open a Command Prompt in Administrative mode 
1. Run the command "npm install appium"
This will install Appium from NPM

## Connecting to a Selenium Grid**
### Hub
1. Download latest Selenium Jar
1. Launch a command line
1. Run "java -jar selenium-server-standalone-3.0.1.jar -role hub -port 4444"

### Node

1. Edit a JSon configuration file for Appium to let Appium know where the Selenium grid is located. See here for more information. Look at the bolded rows, those indicate where the Selenium hub is located. The JSon looks something like this
```
	{
	  "capabilities":
	      [
	        {
	          "browserName": "",
	          "version":"",
	          "maxInstances": 3,
	          "platform":"WINDOWS"
	        }
	      ],
	  "configuration":
	  {
		"cleanUpCycle":2000, 
		"timeout":30000, 
		"proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
		"url":"http://127.0.0.1:4723/wd/hub",
		"host":"127.0.0.1",
		"port":4723, 
		"maxSession":3,
		"register":true,
		"registerCycle":10000,
		"hub": "127.0.0.1:4444/grid/register",
		"hubPort":4444,
		"hubHost":"127.0.0.1",
		"nodeTimeout":120, 
		"nodePolling":2000
	  }
	}
```

1. Launch a Command line
1. Run this, assuming AppiumNode.json is the config file you created
`node appium --nodeconfig AppiumNode.json -p 4723`

**Comment by yodurr** [comment]
I've posted these instructions to the FAQ.  Thank you!
https://github.com/Microsoft/WinAppDriver/wiki/Working-with-the-Selenium-Grid

**Comment by rajender451** [comment]
@DHowett @Tecuanotl 

we tried to do the same like you mentioned above but while running scripting getting  below errors,

![image](https://user-images.githubusercontent.com/124247055/216273853-b69c1dc0-3ea0-4545-adf1-ee8659c6ecbe.png)

2023-02-01 23:26:57.961:WARN:osjs.HttpChannel:qtp988800485-21: /wd/hub/session java.io.IOException: org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request: {
  "desiredCapabilities": {
    "app": "E:\\Perforce\\P4V.exe",
    "platformName": "Windows"
  },
  "requiredCapabilities": {},
  "capabilities": {
    "desiredCapabilities": {
      "app": "E:\\Perforce\\P4V.exe",
      "platformName": "Windows"
    },
    "requiredCapabilities": {},
    "alwaysMatch": {
      "platformName": "Windows"
    },
    "firstMatch": []
  }
}


can you please help on this to work fine.
Thanks..
