### ISSUE TITLE
Update Selenium Grid for WinAppDriver information

### ISSUE THREAD

**Issue by Tree55Topz** [microsoft/WinAppDriver#1220]
I am looking at this guide here.

https://github.com/Microsoft/WinAppDriver/wiki/Working-with-the-Selenium-Grid

There is some good information, and there is a link for 'here' where there is supposed to be more information. This link is no longer working. 

Anyone else know what resource this took you too or any other guides as far as getting started with WinAppDriver Selenium Grid?

**Comment by liljohnak** [comment]
@Tree55Topz What are you trying to do?  Reading to what goal?

**Comment by Tree55Topz** [comment]
@liljohnak sorry I ment to close this one - I have since gotten further, but am now stuck trying to get the Hub to actually pass tests out to the nodes. Here is the latest Issue, closing this one 

https://github.com/microsoft/WinAppDriver/issues/1231
