### ISSUE TITLE
When WPF app starts it's not focused so tests fail

### ISSUE THREAD

**Issue by rodsantest1** [microsoft/WinAppDriver#1221]
When I start my test and it starts WPF application (system under test), the application is not in focused (can't tell if minimized or just behind Visual Studio) so the tests fail. The tests passed if I click on the app at the start of the test to give it focus.

Any ideas?
[zoom_0.zip](https://github.com/microsoft/WinAppDriver/files/4890446/zoom_0.zip)

**Comment by Tree55Topz** [comment]
Is the app actually launching when you start your tests, are you doing something like this? 

```
appCapabilities.AddAdditionalCapability("app", "pathToApp");
                    session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities, TimeSpan.FromMinutes(2));
```

Another thing you can try to do is to maximize the app, so at the end of all that you would add something like

`session.Manage().Window.Maximize();`

**Comment by anunay1** [comment]
Also for the video I observe that you have a Winform application solution, use the below to open the winform application in maximized mode. 

private void Form1_Load(object sender, EventArgs e)
{
    this.TopMost = true;
    this.FormBorderStyle = FormBorderStyle.None;
    this.WindowState = FormWindowState.Maximized;
}

**Comment by rodsantest1** [comment]
I updated all my NuGet packages and it works properly now.

**Comment by rodsantest1** [comment]
Thanks for all the feedback.
