### ISSUE TITLE
Selenium Grid not running tests

### ISSUE THREAD

**Issue by Tree55Topz** [microsoft/WinAppDriver#1231]
I have configured my Selenium Grid Hub and one node. I see that the node is registered correctly, no errors appear to be showing on the Hub console. 

However, when I launch my tests the selenium grid just appears to be unresponsive.. No logging or anything that its about to start passing out tests or things like that. I am starting to wonder if it may be related to how i am handling the capabilities?

Here is my Hub, you can see the node configured

![image](https://user-images.githubusercontent.com/15693599/87350656-34979580-c526-11ea-9aa7-b9e9544171ac.png)

Here is my AppiumNode.json file. I have my host set to the nodes IP address and the hubHost set to the hubs IP address. 

![image](https://user-images.githubusercontent.com/15693599/87350853-7a545e00-c526-11ea-87cd-beb6c6a1fea5.png)

And then here is my code that does the WinAppDriver startup

```
appCapabilities.AddAdditionalCapability("platformName", "WINDOWS");
appCapabilities.AddAdditionalCapability("app", GetLaunchFile());
                    appCapabilities.AddAdditionalCapability("appArguments", "enableautomation");
                    session = new WindowsDriver<WindowsElement>(new Uri(HubIP), appCapabilities, TimeSpan.FromMinutes(2));
                    session.Manage().Window.Maximize(); 
```

Shouldnt I see atleast something happening in the cmd prompt window thats running the Hub acknowledging that its going to pass it out to the node? Could it be something with how im specifying the platformName?

**Comment by anunay1** [comment]
The hub command line will show the registered nodes, but on the web interface it will not show anything, that's how it is

**Comment by Tree55Topz** [comment]
@anunay1 Right, I see on the cmd line that it registered the node but what I was expecting was that when it receives a test, it should atleast log something saying it received that request right? Nothing is shown on the cmd line for the Hub. 

Is anything off about my above setup? Why would the tests not be passed to the node?

**Comment by AutoMcG** [comment]
You are correct that the hub should be logging a message as it receives a driver.start command. It will look something like "Trying to create a new session on test slot [blahblahblah]" 

I'd be willing to bet the HubIP you're passing to it is not targeting the right port or endpoint. That URI should end with :portnumber/wd/hub for a hub session whereas for local driver sessions it accepts the direct ip:port combo for starting sessions.
