### ISSUE TITLE
Button click & issuing commands using SendAccessKeys unstable

### ISSUE THREAD

**Issue by daghb** [Microsoft/WinAppDriver#124]
I have a stability problem with UI automation using the WinAppDriver. When running my WPF exe file without any strings attached to the WinAppDriver I can use shortcut keys to open modal dialogs in my UI. However, when I try to use the same shortcut keys to open modal dialogs some of them fail all the time (no UI reaction at all) and some seem to work all the time.

If I leave my application open after running a test suite, I can press the shortcut key that didn't work using WinAppDriver and the application opens up the modal dialog immediately without me even clicking inside the app to ensure that focus/most foreground app/window is set. There seems to be a discrepancy somewhere - between my app running when manually started and my app started by WinAppDriver.

The reason why I use shortcut keys is that normal button click behaviour does not work - I am using third party user controls with several controls within and do not have the Automation IDs to access the buttons directly. Using mouse click functions do not work either.

**Comment by timotiusmargo** [comment]
Hi @daghb,

What is the shortcut sequence that you are sending? Can you come up with a sample app or existing app that can repro the issue you are seeing?

Could you also open another issue if you have a separate issue with the mouse click? Similarly steps to reproduce the issue would greatly help.

**Comment by daghb** [comment]
Looks like this problem is caused by closed modal dialogs. Will investigate this further and open further issues based on findings.
