### ISSUE TITLE
WinAppDriver cannot identify file explorer search campuses by name or id

### ISSUE THREAD

**Issue by BrenoSantos2019** [microsoft/WinAppDriver#1243]
I'm trying to run a program on winappdriver, but right after opening the program and selecting the option to import files, an error occurs when searching for the file explorer research campus by id.The error is this: OpenQA.Selenium.WebDriverException: 'An element could not be located on the page using the given search parameters.' 

   
            
            WindowsDriver<WindowsElement> leafSession;
            AppiumOptions desiredCapabilities = new AppiumOptions();
            desiredCapabilities.AddAdditionalCapability("app", @"C:\Program Files (x86)\Viewer.lnk");
           

            leafSession = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), desiredCapabilities);
            System.Threading.Thread.Sleep(5000);
           
            
            //Open import option using the keyboard
            leafSession.Keyboard.SendKeys(Keys.Control + Keys.Shift + 'I');
            System.Threading.Thread.Sleep(2000);
           
            
            /*Id "1148" is the campus to do the search in the file explorer and the value of 
            this search is "2328.lsc" o with Id "1" is the open button*/
            leafSession.FindElementById("1148").SendKeys("2328.lsc");
            leafSession.FindElementById("1").Click();
      

            //Execute and stop
            leafSession.FindElementByName("Executar").Click();
            leafSession.FindElementByName("Sim Enter").Click();
            System.Threading.Thread.Sleep(2000); ;
            leafSession.FindElementByName("Parar").Click();

The error occurs in leafSession.FindElementById ("1148"). SendKeys ("2328.lsc"); 

The locations that I need that I need to identify are represented in red in the image.
![Importar](https://user-images.githubusercontent.com/49909668/88331011-afb93280-cd02-11ea-85d5-3c56748020bd.png)

**Comment by anunay1** [comment]
This is how I handle these kind of scenarios: 

  WebDriverWait driverWait = new WebDriverWait(driver, TimeSpan.FromMinutes(2));
            driverWait.Until(ExpectedConditions.ElementExists(By.Name("Organize")));
            driver.FindElementsByAccessibilityId("1148")[1].SendKeys(path);
            Logger.Logger.LogInfo("Clicked on the filename");
            Logger.Logger.LogInfo("Sending  path " + "C:\\Myfiles\\1.txt");
            driver.FindElementsByName("Open")[1].Click();

**Comment by BrenoSantos2019** [comment]
Hello, I tried to implement the code that you passed, but there are several exceptions like in the "driver" and in the FindElements. I made an adaptation so that it could run with my script, but the same error still appears An element could not be located on the page using the given search parameters. ' This code that passed it is from winappdriver? I noticed that it looks a lot like Winium.
![WinAppDriver](https://user-images.githubusercontent.com/49909668/88538415-b804bc80-cfe5-11ea-9baa-25ead3e68978.jpg)

**Comment by anunay1** [comment]
Can you check in inspect.exe if the dialog window is part of the same window?

**Comment by anunay1** [comment]
Your adaptation of your code is correct.

**Comment by BrenoSantos2019** [comment]
how do I see if the dialog is part of the same window in inspect.exe?

**Comment by anunay1** [comment]
Can we have a hangout call anunayathakur1@gmail.com

**Comment by anunay1** [comment]
> how do I see if the dialog is part of the same window in inspect.exe?

In inspect check if the dialog box is in the same tree structure as that of the main application, if possible please share the screen shot of inspect

**Comment by BrenoSantos2019** [comment]
Hi, @ anunay1
First of all, thank you very much for your help.
I found the solution to my problem through the following issue:
https://stackoverflow.com/questions/56363713/appium-desktop-app-test-throws-element-could-not-be-located-exception-but-passe
According to my interpretation, the cause of WinAppdriver not identifying the elements is because my code was not directing the search in the correct window.
After implementing the search for the elements within the structure below it worked perfect for me. 
if (leafSession.CurrentWindowHandle! = leafSession.WindowHandles.Last ())
{
leafSession.SwitchTo().Window(leafSession.WindowHandles.Last());
//Open import option using the keyboard
leafSession.Keyboard.SendKeys(Keys.Control + Keys.Shift + 'I');
System.Threading.Thread.Sleep(2000);
 leafSession.FindElementById("1148").SendKeys("2328.lsc");
 leafSession.FindElementById("1").Click();
// [...]
}
Once again, thank you for your attention.
