### ISSUE TITLE
Failed to locate open application window issue appID and Processid.

### ISSUE THREAD

**Issue by Noelf21** [microsoft/WinAppDriver#1246]
Hi,

I am having a problem with an application, I've successfully managed sessions for other apps using the root session. This app is behaving differently though for that code path just at the basic launch app steps, the app when launched manually seems to from monitoring task manager getting and retaining the same process ID.

However when run through a coded WinAppDriver session, I can see the session launch with a processID and then it closes then my code crashes.

`            var capabilities = new AppiumOptions();

            capabilities.AddAdditionalCapability(MobileCapabilityType.App, @"C:\Program Files\QDAQ\QDAQ.exe");
            capabilities.AddAdditionalCapability(MobileCapabilityType.PlatformName, "Windows");
            capabilities.AddAdditionalCapability(MobileCapabilityType.DeviceName, "NOELF-L-W10");

            WindowsDriver<WindowsElement> session = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), capabilities);`

I am not really sure how to handle this, do I need to somehow ignore the initial process ID?

I am getting some developer help this afternoon but wanted to know if there was a standard way to address this.

**Comment by anunay1** [comment]
Does you application have a splash screen?

**Comment by Noelf21** [comment]
@anunay1 yes it does but that's not the problem here, nothing is loading at all from the launch. I've successfully handled the splash screen in our other applications, my problem here is how do I handle a process that is only available briefly and then disappears before the driver can even recognise it.

**Comment by anunay1** [comment]
Try this: 

 var allProcesses1 = Process.GetProcesses();
                foreach (Process process in allProcesses1)
                {
                    if (process.ProcessName.Contains("Your application"))
                    {
                        mainWindowTitle = process.MainWindowTitle;
                        Logger.Logger.LogInfo("The main window title is " + mainWindowTitle);
                        
                    }
                }

**Comment by anunay1** [comment]
And then 

` DesiredCapabilities desktopCapabilities = new DesiredCapabilities();
                desktopCapabilities.SetCapability("app", "Root");
                desktopSession = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), desktopCapabilities);
                Assert.IsNotNull(desktopSession);

                var RSWindow = desktopSession.FindElementByName(mainWindowTitle);
                var RSTopLevelWindowHandle = RSWindow.GetAttribute("NativeWindowHandle");
                RSTopLevelWindowHandle = (int.Parse(RSTopLevelWindowHandle)).ToString("x");

                DesiredCapabilities appcapabilities = new DesiredCapabilities();
                appcapabilities.SetCapability("appTopLevelWindow", RSTopLevelWindowHandle);
                driver = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appcapabilities);`

**Comment by anunay1** [comment]
`
 DesiredCapabilities desktopCapabilities = new DesiredCapabilities();
                desktopCapabilities.SetCapability("app", "Root");
                desktopSession = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), desktopCapabilities);
                Assert.IsNotNull(desktopSession);

                var RSWindow = desktopSession.FindElementByName(mainWindowTitle);
                var RSTopLevelWindowHandle = RSWindow.GetAttribute("NativeWindowHandle");
                RSTopLevelWindowHandle = (int.Parse(RSTopLevelWindowHandle)).ToString("x");

                DesiredCapabilities appcapabilities = new DesiredCapabilities();
                appcapabilities.SetCapability("appTopLevelWindow", RSTopLevelWindowHandle);
                driver = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appcapabilities);

`

**Comment by Noelf21** [comment]
Thanks @anunay1 , getting some more experience code help now and we seem to have found a problem where WinAppDriver is launching the application but then crashing as Nlog file path can't be found even though it exists. It does launch manually. Any thoughts on what that might be?

**Comment by anunay1** [comment]
"Nlog file path can't be found" are you using Nlog for logging?

**Comment by Noelf21** [comment]
Yes we used Nlog for this application, we've narrowed the problem now to the launching through WinAppDriver the app launches but then checks for the Nlog.config file in the Windows Application Driver root instead.

![image](https://user-images.githubusercontent.com/67745378/88670663-3db76380-d0dd-11ea-8cbd-320c08d798cf.png)
