### ISSUE TITLE
Appium not finding WPF elements

### ISSUE THREAD

**Issue by evansct** [microsoft/WinAppDriver#1249]
Copied over from [Appium Github Issues](https://github.com/appium/appium/issues/14609) as I was recommended that it was more of a WAD issue than one with Appium.

## The problem

I am working on a team that is creating a WPF application, and I am tasked with doing automated testing on it. For the most part I haven't have any issues at all and work has gone smoothly. However, there are a few elements that appium isn't able to see. Most of them are TextBlock elements, where I am trying to grab the text so that I can confirm that the correct element is selected. When I look inside the visual tree on Appium Desktop, I see this: 
![image](https://user-images.githubusercontent.com/31485935/88707719-ac49f080-d0e0-11ea-9afc-ba33f33948ba.png).

However the actual application also has a TextBlock that should be above and below the ComboBox. 
![image](https://user-images.githubusercontent.com/31485935/88708780-2fb81180-d0e2-11ea-9e7f-6ee4ba6857b3.png)
Even though I have the TextBlocks ID'd in my code, it gives me an exception that says: `OpenQA.Selenium.WebDriverException: An element could not be located on the page using the given search parameters.` 

The elements just seem to be completely invisible to Appium.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Desktop OS/version used to run Appium: Windows 10
* Type of application under test: WPF 

## Code To Reproduce Issue

```
var partNumDropdownTxt = partNumTile.FindElementByAccessibilityId("PartNumberDesc").Text;
```

This is what I'm using to find the element, which exists, but is not seen by appium, leading to the exception given above.

Edit: I'm posting a screenshot of inspece.exe to show that it is there and visible, but for whatever reason is not being found. Inspect is also noticing the AutomationID that the element has.
![image](https://user-images.githubusercontent.com/31485935/88930028-ed5d1480-d248-11ea-9e0d-92ebab507441.png)
(sorry for the blurryness)

**Comment by anunay1** [comment]
You can try with the below; 
Assuming you have already created a driver instance: 
string text =  string text = driver.FindElementByName("button").FindElmentByClassname("comboBox1").Text

if you have multiple comboboxes: 
string text =  string text = driver.FindElementByName("button").FindElmentsByClassname("comboBox1")[Index].Text

**Comment by evansct** [comment]
@anunay1 It isn't the combo box that I'm trying to get, it's the text that is next to the combo box that I want. It's just a regular text box, but for whatever reason (unlike every other text box) it isn't visible to be grabbed. I can get the combo box just fine!

**Comment by PandaMagnus** [comment]
Can you show the description from Inspect for that text control?

**Comment by evansct** [comment]
@PandaMagnus Yes, here it is

![image](https://user-images.githubusercontent.com/31485935/88959950-c61a3d80-d270-11ea-9e61-464fddc39584.png)

**Comment by anunay1** [comment]
This is really weird, can you check the page source, what is grabbed by WAD, I don't see any good reason for this not to work.

**Comment by evansct** [comment]
I'm not sure I understand what you mean by that/how I would do that

**Comment by anunay1** [comment]
This is how you get the page source: 
  var source =  session.PageSource;
File.WriteAllText(@"C:\AutomationResults\Source.xml", source);

**Comment by evansct** [comment]
@anunay1 
![image](https://user-images.githubusercontent.com/31485935/89042041-52ca0780-d314-11ea-87a9-5923ccf8950a.png)
It seems that the page source does not have it in the file. So inspect is finding it, but for whatever reason it's not being loaded in/seen by WAD?

**Comment by anunay1** [comment]
Apologies for silly question, but does this combo box open after you click on any button, then it appears like timing issue, can you try adding sleep in case if you are not doing it after you click on the button to open comboBox and then take the page source. 

based on you last comment can you try this 
var partNumDropdownTxt = driver.FindElementByName("Button").FindElementByAccessibilityId("PartNumberDesc").Text;

**Comment by evansct** [comment]
The combo box is disabled until everything on the page is loaded in. Then it only opens if you click on it. The button that it's on being clicked has no effect on the combo box. I believe I have already tried finding the button and then finding the PartNumberDesc that is on it, but I will try again just to be sure.

**Comment by anunay1** [comment]
Will it be possible to share a small video of the scenario, what I assume is, its a timing issue.

**Comment by evansct** [comment]
I thought that as well, but the "Part Number" textblock is available immediately on the page (at least visually) but it cannot be found either. I also tried putting a ridiculous sleep of 60 seconds on to let the page load in before doing anything on the page, and it still didn't see the textblocks.

Is it possible that the WAD cannot see textblocks that are located on top of buttons?

**Comment by anunay1** [comment]
> I thought that as well, but the "Part Number" textblock is available immediately on the page (at least visually) but it cannot be found either. I also tried putting a ridiculous sleep of 60 seconds on to let the page load in before doing anything on the page, and it still didn't see the textblocks.
> 
> Is it possible that the WAD cannot see textblocks that are located on top of buttons?

No.

**Comment by evansct** [comment]
I can try recording something and sending it, but as stated I did put a sleep in to try and allow everything to load and that didn't help. So I'm not sure if the recording would do much other than show that it doesn't work.

**Comment by anunay1** [comment]
I want a recording of the application, not the test

**Comment by evansct** [comment]
@anunay1 What email would I be able to share that with?

**Comment by anunay1** [comment]
anunayathakur1@gmail.com

**Comment by anunay1** [comment]
> I tried changing it to a textbox rather than a textblock just to see what happened, and it had no issues at all finding/using it.

Great

**Comment by evansct** [comment]
I'm looking into if there's some special way that we're setting up the textblock that's different from all the other ones I'm already able to access, but it needs to be a block rather than a box in the end. Do you have any thoughts/ideas why it might be doing this other than timing? Also, if you didn't see I did send the video

**Comment by anunay1** [comment]
> I'm looking into if there's some special way that we're setting up the textblock that's different from all the other ones I'm already able to access, but it needs to be a block rather than a box in the end. Do you have any thoughts/ideas why it might be doing this other than timing? Also, if you didn't see I did send the video

Thanks, I saw the video and it appears pretty straight forward, why it searches with testbox and text block I don't know.

**Comment by evansct** [comment]
This issue was never solved, but we changed from a textblock to a label and it is seeming to work fine/can find the element and compare it.

**Comment by fernandreu** [comment]
For anybody having the same issue: it seems the `TextBlockAutomationPeer` is explicitly forcing the `TextBlock` not to appear when it is part of a `ControlTemplate`, for reasons I'm unaware of: https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Automation/Peers/TextBlockAutomationPeer.cs,66

There's no such attempt for labels, hence why the label swapping workaround works. Probably not much WinAppDriver, or any other .NET-based UI automation tool (e.g. UISpy), can do.

Our workaround was to use [Harmony](https://github.com/pardeike/Harmony) to patch this. The simplest way is to patch `TextBlockAutomationPeer.IsControlElementCore()` so that the return value is always true.

**Comment by fkurzyk** [comment]
> Our workaround was to use [Harmony](https://github.com/pardeike/Harmony) to patch this. The simplest way is to patch `TextBlockAutomationPeer.IsControlElementCore()` so that the return value is always true.

@fernandreu Can you elaborate a bit on how did you managed to pull that workaround? Did you patch that method in the application project, or in the test automation project?
