### ISSUE TITLE
Getting Internal error

### ISSUE THREAD

**Issue by sampadrout** [Microsoft/WinAppDriver#125]
I am getting the below error while executing the script. Any help on this.
Windows Application Driver Beta listening for requests at: http://127.0.0.1:4723/
Press ENTER to exit.

==========================================
POST /session HTTP/1.1
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
Content-Length: 68
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5.1 (Java/1.8.0_91)

SessionManager - Creating session
SessionManager - WinAppDriver succeeded loading MitaBroker
HTTP/1.1 500 Internal Error
Content-Length: 133
Content-Type: application/json

**Comment by timotiusmargo** [comment]
Hi @sampadrout,

Can you provide the capabilities (e.g. app name) that you passed in when instantiating the driver? For example:

==========================================
POST /session HTTP/1.1
Accept: application/json, image/png
Connection: Keep-Alive
Content-Length: 100
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

**{"desiredCapabilities":{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","platformName":"iOS"}}**
SessionManager - Creating session
SessionManager - WinAppDriver succeeded loading MitaBroker
SessionManager - Application launched
SessionManager - Session successfully created: 4BD46109-E6B4-400D-8EE3-581443EF52F3
HTTP/1.1 200 OK
Content-Length: 148
Content-Type: application/json

{"sessionId":"4BD46109-E6B4-400D-8EE3-581443EF52F3","status":0,"value":{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","platformName":"iOS"}}

**Comment by sampadrout** [comment]
Here is the detail:
POST /session HTTP/1.1
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
Content-Length: 74
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5.1 (Java/1.8.0_91)

{"desiredCapabilities":{"app":"C:\\test\\AutomationID_AllControls-4.jar"}}
SessionManager - Creating session
SessionManager - WinAppDriver succeeded loading MitaBroker
HTTP/1.1 500 Internal Error
Content-Length: 133
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}

**Comment by timotiusmargo** [comment]
A jar file is not an application as it requires a java executable to launch it e.g. `javaw.exe`. You could actually set the java executable as the app, but we don't have the mechanism to pass argument to the executable yet. This argument passing is planned and coming in the near future.

**Comment by sampadrout** [comment]
Thanks @timotiusmargo. I did try with an exe and its now not showing the internal error. But yes, its not performing any actions though. I will come back with more info. Thanks for your time
