### ISSUE TITLE
Feature Request: Ability to bind on all interfaces (0.0.0.0)

### ISSUE THREAD

**Issue by paulreimer** [microsoft/WinAppDriver#1254]
I am configuring a Windows image for generic CI purposes that runs WinAppDriver at logon. Currently I have to detect the local IP and update my Windows "scheduled task" every time I boot a new VM and/or the IP changes.

It would be a lot easier if I could specify a command line parameter to bind to all interfaces (or the first non-local interface or ...), or just specify 0.0.0.0 as a special case to select that behaviour.

**Comment by anunay1** [comment]
You can start start winappdriver with IP from command line 
for eg. WinAppDriver.exe 192.168.29.71 4725

NOTE: CMD should be started in admin mode.

**Comment by paulreimer** [comment]
Hi there,

Yes, that is what I do now. But I use the same Windows image for multiple different IPs, so if I have e.g. 2 VMs running then they will have different IPs; I have to login to modify the script to change the IP address every time. For CI purposes then I will have very many IPs and I need some way they can all use the same image (so hard-coded 0.0.0.0 would work even if the IP does change).

**Comment by anunay1** [comment]
Why not start WIN app driver programatically? I don't know which language binding you are using, In my case I am using C#, 
From the code I read the IP and then start my WAD with the same IP.

**Comment by paulreimer** [comment]
I wrote a `*.bat` file which can do it, it works so I can close this:
```
@echo off
for /f "tokens=1-2 delims=:" %%a in ('ipconfig^|find "IPv4"') do set ip=%%b
  set ip=%ip:~1%
  @echo on
  "C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe" %ip% 4723
  exit
```
