### ISSUE TITLE
Get Name of an Element

### ISSUE THREAD

**Issue by negue** [Microsoft/WinAppDriver#126]
Scenario: I'm trying to test, if a popup was opened and what content it has.

I can find the Button of this Popup by using `MobileBy.AccessibilityId("Button0")` , but I don't get any Information about the Name or yet better the Text, cause this one is empty too.

I'd like to access an element's name too, since we also have FindElement`By.Name("Button Text")`.

App-Platform: UWP 
Test-Lanuage: C#

The only way I can get the Element-Name, is by loading the current `/source` and looking for the Element inside the XML-Result. 

I also tried using `btn.GetAttribute("name")` or any other of the source xml result, but all just return null.

**Comment by timotiusmargo** [comment]
Hello @negue,

Can you use the [inspect tool](https://github.com/Microsoft/WinAppDriver#inspecting-ui-elements) and ensure that Button0 indeed has a name? A lot of times the name is set to the button text which is accessible through the **Text** properties. E.g. https://github.com/Microsoft/WinAppDriver/blob/master/Tests/UWPControls/Button.cs#L109

**Comment by negue** [comment]
I did a simple test to check if Buttons of a `MessageDialog` have a Text-Property using the inspect tool:

A `MessageDialog` with Ok/Cancel Buttons:
![dialog](https://cloud.githubusercontent.com/assets/842273/21882575/5c478718-d8ab-11e6-8674-8ef3bb5cc902.png)

Inspect tool:
![cancel_button0_inspect](https://cloud.githubusercontent.com/assets/842273/21882582/64bb820a-d8ab-11e6-976c-940694ec17d8.png)
As you can see the Button has the Content as Name

Debug IOSElement:
![btn_element_inspect_in_debug](https://cloud.githubusercontent.com/assets/842273/21882596/73f100c4-d8ab-11e6-8a1b-6dbe63efcc9f.png)

I guess `MessageDialog`-Buttons handle the Labels different.


I also tried simple Buttons (in the normal View, not `MessageDialog`)
- A Button without a Content but with x:Name , the Text Property is Empty (not x:Name)
- A Button with Content, the Text Property is "Content".

**Comment by ernidhi20** [comment]
Hello,

I am seeing same issue in getting the name attribute for an element, please let me know if this is resolved or if there is a workaround to get the name attribute?

Thanks

**Comment by timotiusmargo** [comment]
Starting in [v1.0-RC](https://github.com/Microsoft/WinAppDriver/tree/v1.0-RC) release, you can use the `GetAttribute` API to get any element attributes shown on [inspect.exe](https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/README.md#inspecting-ui-elements). You can find more examples of getting various attributes on the following sample test:
https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/Tests/WebDriverAPI/ElementAttribute.cs#L38

If the button element `Text` API does not return the value you want, use the `inspect.exe` to identify the right attribute and `GetAttribute` API to get the value.
