### ISSUE TITLE
Using 'localhost' makes tests run 10x slower

### ISSUE THREAD

**Issue by TroyWalshProf** [microsoft/WinAppDriver#1269]
If I use "http://127.0.0.1:4723" as the remote address when running tests locally, my test run fairly fast.
However, if I use 'http://localhost:4723' all my interactions are extremely slow, and my test execution time goes way up. - All interactions take about 10 times as long.

Sample test code:
https://github.com/Magenic/MAQS/blob/master/Framework/AppiumUnitTests/AppiumWinAppUnitTests.cs#L30
Line to change remote address:
https://github.com/Magenic/MAQS/blob/master/Framework/AppiumUnitTests/AppiumWinAppUnitTests.cs#L56

**Comment by Wolfe1** [comment]
Hmmm I tried replicating on my end using this same code: https://github.com/Accruent/robotframework-zoomba/blob/master/samples/DesktopTests.robot (I work in python/robotframework) and I am not getting any noticeable difference between the two (average over 3 runs each).

How many lines do you have in your Windows Hosts file (aside from the commented out bits:
C:\Windows\System32\Drivers\etc\hosts

A large hosts file could cause a slowdown here.

**Comment by Wolfe1** [comment]
Or perhaps you are using a proxy without this checked?
![image](https://user-images.githubusercontent.com/3010366/90441547-bf782c80-e09e-11ea-820e-f664e3929ff5.png)

**Comment by naeemakram** [comment]
WinAppDriver is innocent in this case, it is not responsible for translating the localhost. 
The slowness is not the root cause, it is the symptom of some other problem with the system.
The simple solution would be to not use localhost, just go with 127.0.0.1.

**Comment by TroyWalshProf** [comment]
Did some more investigation and it appears this is a .Net core issue.
  
Notes* 
- Only happens on Dotnet Core.
- Have reproduced this behavior with the [Microsoft.AspNet.WebApi.Client](https://github.com/aspnet/AspNetWebStack) 
- 99% sure this is is the real issue - https://github.com/dotnet/runtime/issues/23581#issuecomment-354391321

**Comment by hemantattri1499** [comment]
Thanks @TroyWalshProf  this finally resolve my issue of slow execution of test.
Now My tests are running pretty fast when using the http://127.0.0.1:4723/ instead of localhost.
