### ISSUE TITLE
Finding Elements by AccessibilityId in WPF data templates 

### ISSUE THREAD

**Issue by wuarthur** [Microsoft/WinAppDriver#127]
Hi,

I have a WPF app, and for one of the textboxes in my datatemplate i gave it a AutomationId.
 <control:MaskedTextBox x:Name="DisplayNameText"
                                         AutomationProperties.AutomationId="DisplayNameText"
                                         Grid.Row="1"
                                         Grid.Column="1"
                                         VerticalAlignment="Center"
                                         IsEnabled="{Binding Path=IsDisplayNameReadOnly,
                                                             Converter={StaticResource BoolInverterConverter}}"
                                         TabIndex="2"
                                         Template="{DynamicResource myInputFieldClearlyDisabled}"
                                         Text="{Binding Path=Name,
                                                        UpdateSourceTrigger=PropertyChanged,
                                                        Mode=TwoWay}" />

however when i run "WpfnotepadSession.FindElementByAccessibilityId("DisplayName").Click();" in my test script, i get the An element could not be located error

POST /session/119BFB8A-82E7-4108-B9F3-369AD4644548/element HTTP/1.1
Accept: application/json, image/png
Content-Length: 50
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"using":"accessibility id","value":"DisplayName"}
HTTP/1.1 404 Not Found
Content-Length: 139
Content-Type: application/json

{"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}

**Comment by yodurr** [comment]
you mention "DisplayNameText" in the control description, but the test then refers to "DisplayName".  These strings need to match.

Use inspect.exe which comes with the windows sdk to take a look at your application and see if there's confusion over what the attribute value is.

**Comment by HppZ** [comment]
I had a similar issue, I set AutomationProperties.AutomationId on the root element of a Datatemplete for ListView, and I got empty result from FindElementsByAccessibilityId, what is wrong?
