### ISSUE TITLE
WinAppDriver - GetProperty(propName) throw an exception

### ISSUE THREAD

**Issue by NadeemBader** [microsoft/WinAppDriver#1277]
Hi

In my c# project, I have a windows form which contains different properties:
* public bool IsInit {get; set; }
* public string Module {get; set; }
* public Collection<Matrix> MatrixCollection {get; set;} (Matrix is a module class which contains only properties)
* public ImageList ImageList {get; set;}

In another project, I'm using WinAppDriver to access the different elements, and I was able to locate the above form.
My goal is to get the value of all above properties of the located form element.
I tried to use the GetProperty(***) method, but it throws null exception.

Any idea? Is that possible to access properties using WinAppDriver?

Best Regards,
Nadeem Bader

**Comment by anunay1** [comment]
you will have to use get attributes.

**Comment by NadeemBader** [comment]
Thank you for your reply
GetAttribute() method always returns null for that properties, but it returns values for AutomationId, Id, Class Name (etc..) attributes

**Comment by liljohnak** [comment]
@NadeemBader I use Inspect.exe to see the properties, then I attempt to use 
```
public bool IsOffscreen(this AppiumWebElement elm)
{
if(bool.TryParse(elm.GetAttribute("Offscreen"), out bool offscreen)) return offscreen;
else true;
}
```

**Comment by NadeemBader** [comment]
Thank you for the code, but unfortunately, that properties are not even displayed in the Inspect.exe tool.
Any suggestions?

**Comment by anunay1** [comment]
> Thank you for the code, but unfortunately, that properties are not even displayed in the Inspect.exe tool.
> Any suggestions?

Is the properties are not displayed in inspect then windows application driver can't get that

**Comment by NadeemBader** [comment]
Ok.... thats is interesting. Why inspect.exe doesnt locate that properties, while Test Complete does locate all properties?

**Comment by anunay1** [comment]
What all properties are visible in test complete that are not visible in inspect

**Comment by anunay1** [comment]
And this question should be posted to Microsoft on why these properties are not exposed

**Comment by NadeemBader** [comment]
For example, when inspecting the application using Test Complete, i can see the property MatrixCollection, but it is not inspected using inspect.exe. 
My goal is to use WinAppDriver. So, is there any way (Even Workarround) to access all properties that I mentioned in the first post?

**Comment by NadeemBader** [comment]
Hi

In my case, the frame contains many shapes that created based on a Collection of Items.
That's mean, there is a Collection of Items (Called Buttons) defined in the frame and based on its items the frame is shaped.
How can I access that collection of items using WinAppDriver?

Here is the collection:

    [DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
    [Editor(typeof(System.ComponentModel.Design.CollectionEditor), typeof(UITypeEditor))]
    [RefreshProperties(RefreshProperties.Repaint)]
    public GenericEditableCollection<ButtonMatrixItem> Buttons
    {
        get
        {
            return buttons;
        }
    }
Hope you can assist

Best Regards,
Nadeem Bader

**Comment by NadeemBader** [comment]
Hi again - any suggestions\comments regarding my last comment? 
It is important since I'm trying to use the properties and they are not seen in inspect.exe and UI Recorder.

**Comment by liljohnak** [comment]
The Developer moved the information I needed to the status field.  I  don't think this is a good answer though.

**Comment by NadeemBader** [comment]
liljohnak, didn't understand your reply - sorry.
My question, why it is not possible to get the properties (Of the different forms) from the application similar to Test Complete?

**Comment by liljohnak** [comment]
@NadeemBader not everything is available.  My solution was to change where the information was stored in the product I am testing, via requesting a change.  The `Status` field was used by our developer to move the information we needed.

**Comment by NadeemBader** [comment]
Regarding "Status" filed, is that the same as "ItemStatus" which I see in the return value of PageSource? For example:
"<Pane AcceleratorKey="" AccessKey="" AutomationId="595595785" ClassName="WindowsForms10.Window.8.app.0.292f24a_r9_ad1" FrameworkId="WinForm" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="pane" Name="" Orientation="None" ProcessId="20900" RuntimeId="42.595595568" x="265" y="1010" width="1372" height="27">"

My second q, which change in c# should be made from the product side in order to fill in this attribute? Hope to provide a simple example. 

Hope you can assist

**Comment by liljohnak** [comment]
@NadeemBader yes, `ItemStatus` is correct.  Sorry, not sure how the other guy changed the field.

**Comment by NadeemBader** [comment]
Thank you - I investigated it in deep and I found how to control that property (ItemStatus) in WPF applications. 
But i didn't find how to control the ItemStatus property in Windows Forms applications. Any idea?

**Comment by NadeemBader** [comment]
Hi again - In WinForms, I found that it is possible to do the same using a different property, called: AccessibleDescription
Any comments?

**Comment by NadeemBader** [comment]
Hi again Any comments regarding the latest 2 posts? 
It is appreciated to share your thoughts and suggestions.

**Comment by NadeemBader** [comment]
> @NadeemBader not everything is available. My solution was to change where the information was stored in the product I am testing, via requesting a change. The `Status` field was used by our developer to move the information we needed.

Hi

After investigation, seems that the approach of making changes in product side may not work. 
Is that possible to make changes in the WinAppDriver tool itself in order to make it get the public properties of the located control (Similar to Test Complete)? I think that this point is a blocker and may cause us not to use WinAppDriver.

Hope to get a reply 

Best Regards,
Nadeem Bader
