### ISSUE TITLE
Unable to use the WinAppDriver

### ISSUE THREAD

**Issue by guruprasadsr** [Microsoft/WinAppDriver#128]
Hi,

I started using WinAppDriver along with Appium for Windows. I installed Appium and then downloaded the WinAppDriver. When I try to start the WinAppDriver, I get an error message "This programme can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing. Try to reinstall this." Can you please help me with this.

Regards
Guru

**Comment by yodurr** [comment]
Hi @guruprasadsr what version of Windows are you using?  WinAppDriver requires Windows 10.

**Comment by guruprasadsr** [comment]
Hi @yodurr . Currently I am using a VM with Windows Server 2012R2. Are there any specific Microsoft updates that ahve to be installed? Please help me.

**Comment by yodurr** [comment]
Windows Server 2012 is part of the Windows 8 family, so it's not currently supported by WinAppDriver.

Here's another thread where we discuss this topic, and a link to where you can upvote adding Windows 8 support.
https://github.com/Microsoft/WinAppDriver/issues/84
