### ISSUE TITLE
Files to Upload - windows pop - Nothing entered

### ISSUE THREAD

**Issue by psurya2** [Microsoft/WinAppDriver#1294]
HI,
I am using windows Appium driver to enter the path in "Files to Upload" - windows pop .
Windows driver is able to find the element, but not entering path. can you pls help.

Pramod

**Comment by anunay1** [comment]
Can you share some code?

**Comment by psurya2** [comment]
DesiredCapabilities desktopCapabilities = new DesiredCapabilities();
			 desktopCapabilities.setCapability("app","Root");
			 desktopSession = new WindowsDriver(new URL("http://127.0.0.1:4723"),desktopCapabilities);
			 Assert.assertNotNull(desktopSession);
			 desktopSession.findElementByName("File name:").sendKeys(path);

**Comment by anunay1** [comment]
Try this
```
File file = new File(arg1);
	String path=file.getAbsolutePath();			
                     DesiredCapabilities desktopCapabilities = new DesiredCapabilities();
		 desktopCapabilities.setCapability("app","Root");
		 desktopSession = new WindowsDriver(new URL("http://127.0.0.1:4723"),desktopCapabilities);
		 Assert.assertNotNull(desktopSession);
		 desktopSession.FindElementsByAccessibilityId("1148")[1].sendKeys(path);

```

**Comment by psurya2** [comment]
getting this error in the last line. The type of the expression must be an array type but it resolved to WebElement
can you pls provide the correct code.

**Comment by anunay1** [comment]
Which language binding are you using

**Comment by psurya2** [comment]
i m using JAVA.

**Comment by anunay1** [comment]
```
 File file = new File(arg1);
        String path=file.getAbsolutePath();
        DesiredCapabilities desktopCapabilities = new DesiredCapabilities();
        desktopCapabilities.setCapability("app","Root");
        WindowsDriver desktopSession = new WindowsDriver(new URL("http://127.0.0.1:4723"), desktopCapabilities);
        Assert.assertNotNull(desktopSession);
        WebElement element = (WebElement) desktopSession.findElementsByAccessibilityId("1148").get(1);
        element.sendKeys(path);

```

**Comment by psurya2** [comment]
Thanks, it worked :)
