### ISSUE TITLE
how to run the app have some setting file

### ISSUE THREAD

**Issue by sukekes** [microsoft/WinAppDriver#1295]
it has some params need to added when launch  the app . such as :
`C:\Progam File\Test.exe  -wc C:\user\tester\testfile.cfg.` 

using the winappdriver+appium how to run the application

**Comment by anunay1** [comment]
You can try something like below: 
```
// Launch Notepad
DesiredCapabilities appCapabilities = new DesiredCapabilities();
appCapabilities.SetCapability("app", @"C:\Windows\System32\notepad.exe");
appCapabilities.SetCapability("appArguments", @"MyTestFile.txt");
appCapabilities.SetCapability("appWorkingDir", @"C:\MyTestFolder\");
WindowsDriver<WindowsElement> NotepadSession = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), appCapabilities);

```

**Comment by anunay1** [comment]
have a look at #110

**Comment by anunay1** [comment]
Did it work?

**Comment by sukekes** [comment]
my param is "-wc" and "C:\user\tester\testfile.cfg", I don't know how to set it

**Comment by anunay1** [comment]
Will it be possible to share the exe and

**Comment by sukekes** [comment]
The software is OpenBuildings Designer ，You can download it yourself。 the cfg file contents is：
`#Launch_RSTN
%include ${_ROOTDIR}config/mslocal.cfg
_RSTN_ = $(devdir(MS_CONFIG))
%include ${_RSTN_}Config/ReStation.cfg`

**Comment by sukekes** [comment]
It's not  like open the edit file. it's a setting file loaded before open the software

**Comment by sukekes** [comment]
like Extensions of chrome

**Comment by sukekes** [comment]
it's the commandline screenshot:
![image](https://user-images.githubusercontent.com/38717537/92476345-6325aa00-f211-11ea-92fe-2789df87f64a.png)

**Comment by sukekes** [comment]
or  you can tell me  how to switch window In the following case：

after open the 1st app ,the 2nd  app can run automacautomatically .

Automated testing needs to be done on the 2nd APP

**Comment by sukekes** [comment]
@anunay1 Is there any solution？please

**Comment by sukekes** [comment]
Can I resolve this issue through open the shortcut

**Comment by sukekes** [comment]
The below code will solved my problem, thank you very much to @anunay1 : 

subprocess.Popen(['powershell.exe', 'App to opened'])
time.sleep(10);
desired_caps = {}
desired_caps["platformName"] = "Windows"
desired_caps["app"] = "Root"
driver = webdriver.Remote(
    command_executor='http://127.0.0.1:4723/wd/hub',
    desired_capabilities=desired_caps)
print('Appium handles ', driver.window_handles)
appWindow = driver.find_element_by_name('Yourapp title')
appWindowHandle = appWindow.get_attribute("NativeWindowHandle")
winHandle = format(int(appWindowHandle), 'x')
desired_caps3 = {}
desired_caps3["platformName"] = "Windows"
desired_caps3["appTopLevelWindow"] = winHandle
driver3 = webdriver.Remote(
    command_executor='http://127.0.0.1:4723/wd/hub',
    desired_capabilities=desired_caps3
)
driver3.switch_to.window(winHandle)
driver3.find_element_by_accessibility_id('your id')
