### ISSUE TITLE
Find parent element

### ISSUE THREAD

**Issue by Jteve-Sobs** [microsoft/WinAppDriver#1297]
How do I get the parent element (or ancestor / ancestors ) of an element? The next element would also be usefull.
I tried the following: 
`element.GetAttribute("Ancestors")`
`FindElement(By.XPath("./.."), element)`

Both queries return null.

**Comment by Shakevg** [comment]
@Jteve-Sobs I also faced with the same issue and just found workaround to use full xpath with parent:
session.FindElement(By.XPath(parentXPath +"/..")

**Comment by trashbat** [comment]
Another workaround, using the `RuntimeId` property to build an XPath expression for the parent:

```python
# Get the immediate parent:
runtime_id = element.get_attribute('RuntimeId')
xpath = f"//*[@RuntimeId='{runtime_id}']/parent::*"
parent = driver.find_element(By.XPATH, xpath)

# Get the first ancestor of type "Pane" named "foo":
runtime_id = element.get_attribute('RuntimeId')
xpath = f"//*[@RuntimeId='{runtime_id}']/ancestor::Pane[@Name='foo']"
parent = driver.find_element(By.XPATH, xpath)
```

**Comment by Jteve-Sobs** [comment]
@trashbat This worked. Thanks for the help.

**Comment by forconz** [comment]
@Jteve-Sobs could you give some C# code to build an XPath expression for the parent:
# Get the immediate parent:
xpath = f"//*[@RuntimeId='{element.id}']/parent::*"

# Get the first ancestor of type "Pane" named "foo":
xpath = f"//*[@RuntimeId='{element.id}']/ancestor::Pane[@Name='foo']"

I can not do it well

**Comment by liljohnak** [comment]
@forconz are you searching using the session?  The parent and sibling axis do not work for elements.

**Comment by Jteve-Sobs** [comment]
I had the code from trashbat working but somehow it doesn't work recently. Have not updated WinAppDriver or Appium either

**Comment by huster-songtao** [comment]
@liljohnak many thanks

I search the parent node successfully using the session.

```
public static WindowsElement? GetParent(this WindowsDriver<WindowsElement> session, string xpath)
        {
            try
            {
                return session.FindElementByXPath($"{xpath.TrimEnd('/')}/parent::*");
            }
            catch (Exception)
            {
                return null;
            }
        }
```

The code above work well.

**Comment by huster-songtao** [comment]
> var parent = _driver.Current.FindElementByXPath("//_[@RuntimeId= "+element.Id+ "]/parent::_")

var parent = _driver.Current.FindElementByXPath("//[@RuntimeId= "+element.Id+ "]/parent::*")
