### ISSUE TITLE
Impossible to create connection via Java-client

### ISSUE THREAD

**Issue by ignatenko-paul** [Microsoft/WinAppDriver#13]
I've created a class based on Java Selenium binding:
        DesiredCapabilities appCapabilities = new DesiredCapabilities();
        appCapabilities.setCapability("app", "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App");
        appCapabilities.setPlatform(Platform..WINDOWS);
        RemoteWebDriver CalculatorSession = new RemoteWebDriver(new URL("http://127.0.0.1:4723"), appCapabilities);

During calling **startSession**(...) **execute**(...) method returns response with '**sessionID**' but '**value**' property is null.

Thanks for assistance.

**Comment by yodurr** [comment]
I've got a repro, am looking into it

**Comment by yodurr** [comment]
Hi, could you confirm that this sometimes succeeds?  If so then I'm seeing the same thing you are.

Am running the following code and sometimes it does not succeed.  Sometimes it does succeed and clicks the 5 button.

        DesiredCapabilities appCapabilities = new DesiredCapabilities();
        appCapabilities.setCapability("app", "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App");
        appCapabilities.setCapability("platform", "Windows");

        try {
            URL u = new URL("http://127.0.0.1:4723");
            RemoteWebDriver CalculatorSession = new RemoteWebDriver(u, appCapabilities);

            WebElement we = CalculatorSession.findElementByName("Five");
            if (we != null){
                we.click();
            }
        }
        catch (MalformedURLException mfe) {
        }

**Comment by ignatenko-paul** [comment]
Unfortunately, I'm not succeed with your code. I've run it many times, but
the same error and exception happens.
(Moreover if I close calculator and run script again even session can't be
established)

ImmutableMap parameters = paramBuilder.build();
Response response = this.execute("newSession", parameters); <-- return
object which seen below
Map rawCapabilities = (Map)response.getValue();
DesiredCapabilities returnedCapabilities = new DesiredCapabilities();
Iterator platformString = rawCapabilities.entrySet().iterator(); <--
here NullPointerException occurs

java.lang.NullPointerException
at
org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
  at
org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
  at
org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)

[image: Встроенное изображение 1]

From the server console.
==========================================
POST /session HTTP/1.1
Accept: application/json, image/png
Connection: Keep-Alive
Content-Length: 100
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723

{"desiredCapabilities":{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","platform":"Windows"}}
SessionManager - Creating session for
Microsoft.WindowsCalculator_8wekyb3d8bbwe!App
SessionManager - WinAppDriver succeeded loading MitaBroker
SessionManager - Application launched
SessionManager - Session successfully created:
1B9B6298-768D-4C33-8AC7-FA9ACCE268BE

HTTP/1.1 200 OK
Content-Length: 134
Content-Type: application/json

{"capabilities":{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"},"sessionId":"1B9B6298-768D-4C33-8AC7-FA9ACCE268BE","status":0}


2016-04-24 1:01 GMT+03:00 Yosef Durr <notifications@github.com>:

**Comment by yodurr** [comment]
server log looks correct.

Would it be possible for you to attach the test file so I can run the exact same thing?  Also mention what version of Selenium.  I'm using 2.53.0.

**Comment by ignatenko-paul** [comment]
I had *2.41.0*. After updating up to *2.53.0* it gets to work.
Thanks a lot and sorry for disturbing.

2016-04-25 0:07 GMT+03:00 Yosef Durr <notifications@github.com>:

**Comment by yodurr** [comment]
Glad it's working!
