### ISSUE TITLE
Big driver delay after the application start

### ISSUE THREAD

**Issue by Korop** [Microsoft/WinAppDriver#130]
If instead of Calculator app you will use even AppUIBasics(mentioned in the source repo) the delay  after IOSDriver<IOSElement> initialization completed is more than 1 minute. The app has been already started and it is look like hang in the test.
But when the "big" app already started  the driver starts immediately, without the "hang" .
This issue also happens with my Windows Universal app too.
I am not sure may be I can reduce some session timeout or this is the real issue.

Thanks,
Ivan

**Comment by khouzam** [comment]
We think we understand the underlying issue, we're investigating potential fixes.

**Comment by timotiusmargo** [comment]
We have made some optimizations on application launching during session creation In [v1.0-RC release](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.0-RC). It now takes less than 1 second from the moment the application window is open for the session (driver) to be ready.
