### ISSUE TITLE
Problem with starting session for Microsoft Store application (WPF)

### ISSUE THREAD

**Issue by brontesprocessing** [microsoft/WinAppDriver#1303]
Problem is related to WPF application packed into MSIX package and uploaded to Microsoft Store. While starting the session the application starts successfully, but the test is throwing the "OpenQA.Selenium.WebDriverException: 'Failed to locate opened application window with appId: AA198C8B.VAST.RehabTherapistPanel_vkkdgxxye1vfe!App, and processId: 16756'" exception. The processId is displayed correctly (matches the id of the process of the app started).

![2020-09-08 13_34_31-VR (Debugging) - Microsoft Visual Studio (Administrator)](https://user-images.githubusercontent.com/70581143/92471539-66507400-f1d8-11ea-9499-6a79e87e5e12.jpg)

**The problem appears in older an newest version of WinAppDriver and corresponding Nuget packages.**

Any help will be greatly appreciated!

**Comment by anunay1** [comment]
Does your application have a splash screen?

**Comment by brontesprocessing** [comment]
It has, but starting the session for the *.exe file directly (without Microsoft Store) works as expected. Anyhow - I'll prepare test version without splash screen.

**Comment by anunay1** [comment]
Which language binding are you using

**Comment by brontesprocessing** [comment]
Actually I've just checked it and the splash screen is turned off already and the problem persists. I'm using XAML implementing the MVVM concept.

**Comment by brontesprocessing** [comment]
I've checked also other 3rd party apps that I know are not native UWP apps and they have the same problem. On the other hand the native apps like Calculator, Microsoft Todo, etc. work correctly.

**Comment by anunay1** [comment]
Can you implement a tray and catch block and in the catch block use the below code: 

```
string mainWindowTitle = "";
                var allProcesses1 = Process.GetProcesses();
                foreach (Process process in allProcesses1)
                {
                    if (process.ProcessName.Contains("Your Application"))
                    {
                        mainWindowTitle = process.MainWindowTitle;
                        Logger.Logger.LogInfo("The main window title is " + mainWindowTitle);
                        
                    }
                }

                DesiredCapabilities desktopCapabilities = new DesiredCapabilities();
                desktopCapabilities.SetCapability("app", "Root");
                desktopSession = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), desktopCapabilities);
                Assert.IsNotNull(desktopSession);

                var RSWindow = desktopSession.FindElementByName(mainWindowTitle);
                var RSTopLevelWindowHandle = RSWindow.GetAttribute("NativeWindowHandle");
                RSTopLevelWindowHandle = (int.Parse(RSTopLevelWindowHandle)).ToString("x");

                DesiredCapabilities appcapabilities = new DesiredCapabilities();
                appcapabilities.SetCapability("appTopLevelWindow", RSTopLevelWindowHandle);
                driver = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appcapabilities);

```

**Comment by brontesprocessing** [comment]
Thank you! Your suggestion works!
