### ISSUE TITLE
WinAppDriver Does not create Session

### ISSUE THREAD

**Issue by NagarjunaSK-Git** [microsoft/WinAppDriver#1311]
I am not able to create session and run my desktop application using WinAppDriver.

My code : 

DesiredCapabilities cap = new DesiredCapabilities();
			cap.setCapability("app", "C:/Program Files (x86)/Kofax/Power PDF 40/bin/PowerPDF.exe");
			powerPDF = new WindowsDriver(new URL("http://127.0.0.1:4723"), cap);

Error in console : 

Caused by: org.openqa.selenium.WebDriverException: Failed to locate opened application window with appId: C:/Program Files (x86)/Kofax/Power PDF 40/bin/PowerPDF.exe, and processId: 9888 (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 5.85 seconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-XXXXXX', ip: 'XXXXXXXXX', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_251'
Driver info: driver.version: WindowsDriver

Error in Server : 

{
  "desiredCapabilities": {
    "app": "C:\u002fProgram Files (x86)\u002fKofax\u002fPower PDF 40\u002fbin\u002fPowerPDF.exe",
    "platformName": "Windows"
  },
  "capabilities": {
    "firstMatch": [
      {
        "appium:app": "C:\u002fProgram Files (x86)\u002fKofax\u002fPower PDF 40\u002fbin\u002fPowerPDF.exe",
        "platformName": "windows"
      }
    ]
  }
}
HTTP/1.1 500 Internal Error
Content-Length: 194
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"Failed to locate opened application window with appId: C:/Program Files (x86)/Kofax/Power PDF 40/bin/PowerPDF.exe, and processId: 9888"}}

OS : Windows 10
Driver : WinAppDriver  v1.2-RC
Runner : TestNG
Appium Java Client JAR Version : 7.3.0
Selenium Java : 3.141.59

WinAppDriver was open before running the test.

Any help appreciated. Stuck with this for many days. 
If there is any workaround without manual intervention, Please provide link/guide to implement the same.
Do not want to attach desktop session as this code will run remotely and cant open the desktop app everytime.

Thanks
Arjun
![IsSplash](https://user-images.githubusercontent.com/65765913/92994688-1811dc80-f51a-11ea-904d-efdb8bdcbc63.png)

**Comment by anunay1** [comment]
Your application has a splash screen, you need to create a session with root and then you need to acquire the session with the top window handle [Desktop Session](https://github.com/microsoft/WinAppDriver/wiki/Frequently-Asked-Questions)

**Comment by NagarjunaSK-Git** [comment]
@anunay1  The link says the below logs for Splash Screen.
{"status":23,"value":{"error":"no such window","message":"Currently selected window has been closed"}}

But where as my log has different status code. Are you sure this is due to Splash screen?

**Comment by anunay1** [comment]
Yes i am 200 %sure

**Comment by NagarjunaSK-Git** [comment]
I was able to  create session. Thanks for the workaround @anunay1

**Comment by laomaolaile** [comment]
> Your application has a splash screen, you need to create a session with root and then you need to acquire the session with the top window handle [Desktop Session](https://github.com/microsoft/WinAppDriver/wiki/Frequently-Asked-Questions)

hello,my application has a splash screen too,and i create a session with root,the code can run on my pc ,but run on other pc ,the DesktopSession is null ,how can i do it .
I hope you can answer my question
