### ISSUE TITLE
How to close session without killing the application

### ISSUE THREAD

**Issue by bswhb** [microsoft/WinAppDriver#1320]
Hi there,

I would like to use WinAppDriver to automate an existing Windows application, and I have learned to set caps `appTopLevelWindow` to attach the existing app. But the issue is when I quit the session, this application will be closed as well. Even if I did not invoke session.close(), it seems the session will be timed out and the application will be killed as well.

Please shed some light on how to keep the application running after session closed. Thanks a lot!

p.s. I'm using Appium to manage WinAppDriver, which will automatically start / stop the driver.

**Comment by anunay1** [comment]
If you use appium the driver session in closed after 60 seconds, you can set the attribute newCommanTimeout to increase the timeout for the session.

**Comment by bswhb** [comment]
Hi @anunay1 , thanks for your hint. I've tried to set `newCommandTimeout:0`, now it seems the session will not be closed even I called session.close(). Don't know if this is an Appium issue or not.

Anyway I will mark this issue as closed, thanks again!
