### ISSUE TITLE
WinAppDriver resize window

### ISSUE THREAD

**Issue by rachitgoel89** [microsoft/WinAppDriver#1327]
Hello,

Is there a way to resize the window using WinAppDriver? I do not want to maximize the window or use the fullScreen feature but I want to set my window to a particular size. 

Width = 1845
Height = 1096

driver.Manage().Window.Size.Width does not let me set these values. 

Is there a way to achieve this with WinAppDriver usig C#?

**Comment by Ranganui** [comment]
I ran into the same issue, fortunately the application we are testing takes it height and width from the registry as a binary value. Which we set in  [ClassInitialize]

        RegistryKey WindowSizeKey;
        WindowSizeKey = Registry.CurrentUser.CreateSubKey("SOFTWARE\\Location");
            WindowSizeKey.SetValue("Visible", 0, RegistryValueKind.DWord);
            WindowSizeKey.SetValue("Rect", new byte[] 
            { 
                0x05, 0x02, 0x00, 0x00,
                0x0F, 0x07, 0x00, 0x00, 
                0x31, 0x03, 0x00, 0x00, 
                0x3B, 0x08, 0x00, 0x00 
            }, 

Hopefully this helps

**Comment by anunay1** [comment]
This is how you can set the size:

driver.Manage().Window.Size = new Size(1845, 1096);

**Comment by rachitgoel89** [comment]
> This is how you can set the size:
> 
> driver.Manage().Window.Size = new Size(1845, 1096);

Thanks @anunay1 Worked like a charm!

**Comment by Liqun-Ma** [comment]
when I use a WindowsDriver session and Appium:
Run this line:
`session.Manage().Window.Size = new Size(1000,1000);` 
Get below message:
Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["x","y","width","height"]} and you sent ["x","y"]

**Comment by Janagar-Adappt** [comment]
how to resize the window on java selenium?

**Comment by Janagar-Adappt** [comment]
still appium supports winappdriver(for java)
