### ISSUE TITLE
Selecting a specific email in outlook 

### ISSUE THREAD

**Issue by VladMoc** [microsoft/WinAppDriver#1329]
I'm trying to select a specific email in outlook.  If I want to select the item by name the name is something similar to this:

`From reporter-user-1, Subject testing sendmail, Received 10:33 AM, Size 62 KB, Flag Status Unflagged, `.

Because I don't know the full name of the email I want to select I tried selecting it by xpath:

` $browser.find_element(:xpath, '//*[contains(text(), "Subject testing sendmail")]')`  

` $browser.find_element(:xpath, '//@Name[contains(text(), "Subject testing sendmail")]')`

I get the following error: 

  An element could not be located on the page using the given search parameters.

When using windriverUi  recorder, I can't record Outlook. 

Any idea on how to find the email?

**Comment by anunay1** [comment]
I do not have a project with java script will it be possible to share with me

**Comment by Shakevg** [comment]
@VladMoc Try this:
`
$browser.find_element(:xpath, '//*[contains(@Name, "Subject testing sendmail")]')
`

**Comment by VladMoc** [comment]
@Shakevg it works, thanks!

@anunay1 this is a ruby framework.
