### ISSUE TITLE
http request not able to reach the remote web driver

### ISSUE THREAD

**Issue by sampadrout** [Microsoft/WinAppDriver#133]
When i am execution the test on a javafx application, getting the following error. May i know why the http request not able to reach the remote web driver?
Test Name:	Addition
Test Outcome:	Failed
Result Message:	Class Initialization method CalculatorTest.BasicScenarios.Setup threw exception. OpenQA.Selenium.WebDriverException: OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://127.0.0.1:4723/session timed out after 60 seconds. ---> System.Net.WebException: The request was aborted: The operation has timed out..
Here is the code:
//******************************************************************************
//
// Copyright (c) 2016 Microsoft Corporation. All rights reserved.
//
// This code is licensed under the MIT License (MIT).
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
//******************************************************************************

using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using OpenQA.Selenium.Remote;
using System.Diagnostics;

namespace CalculatorTest
{
    [TestClass]
    public class BasicScenarios
    {
        protected const string WindowsApplicationDriverUrl = "http://127.0.0.1:4723";
        protected static RemoteWebDriver CalculatorSession;
        protected static RemoteWebElement CalculatorResult;
        protected static string OriginalCalculatorMode;

        [ClassInitialize]
        public static void Setup(TestContext context)
        {
            // Launch the calculator app
            DesiredCapabilities appCapabilities = new DesiredCapabilities();
            Debug.WriteLine("test starting");
            appCapabilities.SetCapability("app", "C:\\Program Files\\MyDesktopApp\\MyDesktopApp.exe");
            CalculatorSession = new RemoteWebDriver(new Uri(WindowsApplicationDriverUrl), appCapabilities);
            Assert.IsNotNull(CalculatorSession);
            CalculatorSession.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(20));

            CalculatorSession.FindElementByTagName("input Text").SendKeys("srout@thinkrite.com");
            //CalculatorResult = CalculatorSession.FindElementByName("Display is  7 ") as RemoteWebElement;
            //Assert.IsNotNull(CalculatorResult);
        }

        [ClassCleanup]
        public static void TearDown()
        {
            CalculatorResult = null;
            CalculatorSession.Dispose();
            CalculatorSession = null;
        }

        [TestMethod]
        public void Addition()
        {
            Debug.WriteLine("Just a test");
        }
    }
}

**Comment by khouzam** [comment]
@sampadrout 

Can you send us the WinAppDriver log when running this test?

Thanks

**Comment by sampadrout** [comment]
Here you go. After the Session created, the driver is freezed. Nothing happening here. I did try to run this as a C# test, there i saw its saying the http request are not reaching http://127.0.0.1:4723/.
Windows Application Driver Beta listening for requests at: http://127.0.0.1:4723/
Press ENTER to exit.


==========================================
POST /session HTTP/1.1
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
Content-Length: 279
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_91)

SessionManager - Creating session
SessionManager - WinAppDriver succeeded loading MitaBroker

**Comment by yodurr** [comment]
So the session gets created, does your app launch?
You're not reaching this line correct?  CalculatorSession.FindElementByTagName("input Text")

**Comment by sampadrout** [comment]
Yes, the ap is launching but then its not reaching the WinApp server and the CalculatorSession.FindElementByTagName("input Text") line is not executing.

**Comment by yodurr** [comment]
What is likely happening is WinAppDriver can't find your app window.  Not finding the window causes WinAppDriver to keep looking for it rather than return a session ID to you.

Can you tell me more about the app you're launching, any chance you use a splash screen?  The more you can share about what your app is doing, or share the .exe itself, the better.

**Comment by sampadrout** [comment]
Thanks for your response. I am glad to share the required details. This application developed using JavaFX. It does have a splash screen and takes some time to initialize due to lots of REST calls happening at the back end. After initialization completes, the login screen displays. Somewhere around a min it always wait for the same. Interestingly, even if I kept the application open and run the test, driver does bring it up to the front but then after does nothing. Unfortunately the application is yet to release for public beta, so can't share the same at the moment. Please do let me know if you need any other further info to help you on this. Thanks for your time.

**Comment by yodurr** [comment]
What I think you should try given current constraints is start up a desktop session and look for the Window you intend to run the tests on.  It's done using the "Root" app name and some of the samples use this approach.  This way you separate your startup events from the logic that attaches to the correct window to run the tests.
 appCapabilities.SetCapability("app", "Root");

In addition I'm wondering if giving you a way to describe the window you want to attach to and telling us to wait for that window would solve your issue.  It's a feature we've considered for the backlog.

**Comment by yodurr** [comment]
closing - please see last comment on how to attach to a window that takes some time to open, using a Desktop session.  Let us know if this doesn't resolve your problem.  Thanks.
