### ISSUE TITLE
unable to access a button in a groupBox 

### ISSUE THREAD

**Issue by alvperagu** [microsoft/WinAppDriver#1337]
Hi, I am trying to access a button which is included in a GroupBox. Here, I drop xaml snippet code where I create this buttom.

`        <GroupBox Grid.Row="2" Grid.Column="1" 
                  VerticalContentAlignment="Stretch" 
                  HorizontalContentAlignment="Stretch"
                  Margin="5,5,5,5"
                  x:Name="LayerSelectionWall"
                  Header="{x:Static properties:WallsEditorProResources.LayerSelectSplitLayersText}">`
... I omit unnecessary code  
`  <Button Grid.Column="2" 
                                IsEnabled="{Binding IsEnable, Mode=OneWay}"
                                Style="{DynamicResource SquareButtonStyle}"
                                x:Name="RemoveLayerSet"
                                Content="{x:Static properties:WallsEditorProResources.LayerCreatorSplitInSingleLayerText}"                  
                                FontSize="12" 
                                HorizontalAlignment="Stretch" 
                                VerticalAlignment="Stretch" 
                                Margin="5,5,5,5"
                                VerticalContentAlignment="Center" 
                                HorizontalContentAlignment="Center"
                                ToolTip="{x:Static properties:WallsEditorProResources.LayerCreatorSplitLayer}"
                                Click="Split_OnClick"/>`

In order to find the button I do the following, where "Split Wall Layers" is the window where groupBox is 
      `      rootSession.FindElementByName("Split Wall Layers").FindElementByAccessibilityId("LayerSelectionWall")..FindElementByWindowsUIAutomation("RemoveLayerSet").Click();`

Unfortunately I cannot find this element. While debugging it I found the problem with the GroupBox, I can't find it. Is there a problem with this component?

**Comment by anunay1** [comment]
Is the element found in inspect.exe?

**Comment by alvperagu** [comment]
There are no problems, It just needed more time than it was expected. I added a delay. 
`            Thread.Sleep(5000);
`
It may be a problem in my Pc. It is too slow for that operation.
