### ISSUE TITLE
Can winappdriver access dyalog apl based elements/applications.

### ISSUE THREAD

**Issue by varun210619** [microsoft/WinAppDriver#1338]
I would be working on application based on c# and dyalog apl. I wanted to know if winappdriver can access dyalog apl application

**Comment by anunay1** [comment]
Does inspect show the UI elements?

**Comment by varun210619** [comment]
I am working on setting up inspect.exe. 
I wanted to know if there is any prior experience or documentation regarding dyalog apl elements with winappdriver.

**Comment by anunay1** [comment]
if you can get the elements in inspect.exe, you can use WAD. 
There is no documentation

**Comment by naeemakram** [comment]
You can also use WinAppDriver UI Recorder to inspect the elements of your application. It can be downloaded from the releases section of this repository. No installation needed, just unzip & use.

**Comment by varun210619** [comment]
closing issue as i am using inspect exe and as per anunay1, no documentation is present.
