### ISSUE TITLE
SendKeys with function key not working properly

### ISSUE THREAD

**Issue by dukesmike** [Microsoft/WinAppDriver#134]
Hi there,

I have gone through all issues but seems like no one has the same issue as I have.
I'm not sure if I used the function in a wrong way or it was not covered yet:
session.Keyboard.SendKeys(Keys.Alt), instead of pressing Alt key, it keeps holding the Alt key down all the time, as same as Ctrl key.

Please help.

Thanks a lot!

**Comment by taran311** [comment]
This is normal, I have this same issue. The way I fixed this is pressing Alt twice like so...

session.Keyboard.SendKeys(Keys.Alt + Keys.Alt)

That way it press down, and then back up again

**Comment by dukesmike** [comment]
@taran311 Thanks for the advice but this approach seems not working for me.

**Comment by timotiusmargo** [comment]
Hi @dukesmike,

As suggested by @taran311, you need to terminate the modifier key by issuing another `Alt` button press to explicitly terminate when using `/session/:sesionId/keys` API endpoint. This particular API keeps the state of the modifier keys between calls. This is not a bug and exactly as specified below:
https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidkeys

Can you use the latest release of WinAppDriver and run the `SendModifierAlt()` test method in https://github.com/Microsoft/WinAppDriver/blob/v0.7-beta/Tests/W3CWebDriver/Keys.cs#L93 and verify if this works for you?

```
[TestMethod]
public void SendModifierAlt()
{
    session.Keyboard.PressKey(OpenQA.Selenium.Keys.Alt + "ED" + OpenQA.Selenium.Keys.Alt); // Insert Time/Date
    Assert.IsTrue(editBox.Text.Length > 0);
}
```

**Comment by huster-songtao** [comment]
session.Keyboard
This property was never intended to be used in user code. Use the Actions or ActionBuilder class to send direct keyboard input.
