### ISSUE TITLE
Get the pid from winappdriver 

### ISSUE THREAD

**Issue by Milly89** [microsoft/WinAppDriver#1341]
After created a session with winappdriver, how to get the pid from session which the pid is associated with application process id in task manager ?

![image](https://user-images.githubusercontent.com/64124223/96410416-7452d500-1219-11eb-8c23-30a5a6c29173.png)

**Comment by anunay1** [comment]
Your application have a splash screen? You need to create a session with desktop session and attach the application to that session[Desktop Session](https://github.com/microsoft/WinAppDriver/wiki/Frequently-Asked-Questions)

**Comment by Wolfe1** [comment]
@meilinfan Like anunay1 said it look like your app launches another window that ends up being your final window. So winappdriver is still looking for that original window. You can take a look here at how we handle the issue in python for inspiration: https://github.com/Accruent/robotframework-zoomba/blob/master/src/Zoomba/DesktopLibrary.py#L163

**Comment by meilinfan** [comment]
Thanks @Wolfe1 @anunay1 for your reply:
I just Create a session like below:
![image](https://user-images.githubusercontent.com/64124223/96527828-ad3f8800-12b3-11eb-86a4-e45a3be73674.png)

Then my application will be show up . But when I want to close the app using Driver.quit, the app is still opened . So I want to know how to get the pid from app which created by session , and better the pid is the same with task Manager?

**Comment by alexserov** [comment]
@meilinfan I think, in your case, you can try using the `/forcequit` parameter like mentioned in the https://github.com/Microsoft/WinAppDriver/issues/159#issuecomment-323234509

**Comment by anunay1** [comment]
@meilinfan There are two ways to handle it, on is to check whether application is running and if its true, then kill the application, the other would be to to kill the application in the tear down method.

**Comment by Milly89** [comment]
Thanks all a lot.
