### ISSUE TITLE
Is there a way to edit or write in a MS word document using winappdriver?

### ISSUE THREAD

**Issue by maryPetla20** [microsoft/WinAppDriver#1346]
Word.findElementByName("Page 1 content").findElement(By.tagName("Edit")).sendKeys("editing");

I am trying to write some text to a blank word document using winapp driver and I see following error
```

{
  "id": "42.2099282.4.2",
  "value": [
    "editing"
  ]
}
HTTP/1.1 500 Internal Error
Content-Length: 133
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
```

**Comment by maryPetla20** [comment]
Not going with edit at this time

**Comment by elprofesor999** [comment]
> Not going with edit at this time

So is that mean that , we cannot write in MS Word document using Winapp driver???
