### ISSUE TITLE
Is there any way to get all elements as list?

### ISSUE THREAD

**Issue by dkuba** [microsoft/WinAppDriver#1347]
I try to write gui test for Qt5 app using Appium WinDriver. Qt5 gui elements aren't recognizable by inspect.exe so I can't get elements id or name.
Is there any way to get all elements as list without specifying its id or name?

**Comment by Jteve-Sobs** [comment]
Could you try using `session.FindElementsByXPath("//*");` ? 
This should get all the elements in of your driver.

**Comment by trashbat** [comment]
I ended up dumping the page source to an XML file when automating a QT5 app, and then in my tests I created a JSON file to map friendly descriptions to the horrendous XPath expressions that needed to be used (I didn't have access to the source code).

**Comment by dkuba** [comment]
How to dump an XML file of ui elements map from Qt5 app?
I use WAD UI Recorder to get xpath for the element.
I noticed some elements don't have and unique identifier and they have the same xpath, e.g. the several QToolButton in row on a QToolBar don't have accessible id or name. I can access it only by number in list. Is there any way to set uniqe name for element in source code?

**Comment by trashbat** [comment]
Python example of how to write the XML file:

```python
with open("app.xml", "w", encoding="utf-16") as f:
    f.write(driver.page_source)
```
