### ISSUE TITLE
Unable to navigate between tabs 

### ISSUE THREAD

**Issue by maryPetla20** [microsoft/WinAppDriver#1348]
I am trying to navigate between three tabs.

![image](https://user-images.githubusercontent.com/73177135/96742513-a171c580-1388-11eb-93b3-05a0d7b4713f.png)

        driver.findElementByName("Non-critical").sendKeys(Keys.ENTER);

This is what I have and winappdriver returns 200 (OK) status but no action is performed

**Comment by Jteve-Sobs** [comment]
Is the navigation done by clicking or by using the enter key?
Does it work with `driver.findElementByName("Non-critical").Click();` ?

**Comment by maryPetla20** [comment]
I tried Click(), Keys.ENTER, Keys.TAB. None of them worked.

**Comment by Jteve-Sobs** [comment]
Does `driver.Mouse.MouseMove(driver.findElementByName("Non-critical").Coordniates);` work?
A click can be executed afterwards with `driver.Mouse.Click(null)`.
I know the methods are marked as obsolete but this could be a last resort.

**Comment by maryPetla20** [comment]
I am using Java and I can't find an equivalent to 'driver.Coordinates'

**Comment by maryPetla20** [comment]
I figured it out. Don't know how it's different but here is the solution

findElement(By.xpath("//TabItem[@Name='Critical']")).sendKeys(Keys.ENTER)

Thank you for looking into this.
