### ISSUE TITLE
Keyboard.SendKeys(); not excecuted

### ISSUE THREAD

**Issue by wuarthur** [Microsoft/WinAppDriver#135]
WpfnotepadSession.Keyboard.SendKeys("7272");
System.Threading.Thread.Sleep(1000);
WpfnotepadSession.Keyboard.SendKeys("7272");
WpfnotepadSession.Keyboard.PressKey(Keys.Tab);
System.Threading.Thread.Sleep(1000);
WpfnotepadSession.Keyboard.SendKeys("dave");
WpfnotepadSession.Keyboard.PressKey(Keys.Tab);

sometimes for the above code it always always skips the two "7272" and starts typing "dave"

However restarting the Winappdriver.exe will fix the problem. Is this a possible bug?

Edit/////////////////////////

Seems to be actually caused by switching from the MSTestFramework to the UnitTestFramework

**Comment by yodurr** [comment]
Hi, can you elaborate on which test framework has this issue, and which framework does not?  That's something we definitely need to dig into further.

**Comment by timotiusmargo** [comment]
Closed as it is not an issue with WinAppDriver. More examples on `Keyboard.SendKeys` can be found on https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/Tests/WebDriverAPI/SendKeys.cs and are tested on Windows 10 PC with the latest Windows 10 version (Version 1607 or later).
