### ISSUE TITLE
A way to refresh the RemoteDriver?

### ISSUE THREAD

**Issue by taran311** [Microsoft/WinAppDriver#136]
Currently I have to completely re-instantiate the driver each time a new popup is triggered, to allow the driver to attach to the new window. Is there anyway to simply refresh the driver to say okay, I want to be on the new window triggered now and I want to be able to grab the Window Title for implicit waiting. (Rather then grabbing the old window title, like it would normally)

Current functionality I use to re-instantiate the driver...

```
public static void Init()
        { 
            var appCapabilities = new DesiredCapabilities();

            appCapabilities.SetCapability("app", UrlHelper.GetAppPath());
            Driver = new IOSDriver<IOSElement>(new Uri("http://127.0.0.1:4723"), appCapabilities);
        }
```

**Comment by wuarthur** [comment]
#99

**Comment by yodurr** [comment]
Use a desktop session as shown here:
https://github.com/Microsoft/WinAppDriver/blob/master/Samples/C%23/AlarmClockTest/Scenario.cs

**Comment by viji-123** [comment]
The link above leads to 404 not found. Is there a way to reload the webelements ?

**Comment by timotiusmargo** [comment]
Hi @viji-123,

The sample that @yodurr trying to refer to was https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/Samples/C%23/AlarmClockTest/Scenario.cs#L44

It was a sample of using the [Desktop Session](https://github.com/Microsoft/WinAppDriver/tree/v1.0#creating-a-desktop-session) to locate a popup window that is not part of your application (not parented to the application UI tree).

But when the popup is part of the UI tree, you can switch through all windows as shown here:
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/Window.cs#L155

To answer your question about reloading a **RemoteWebElement** or **WindowsElement**, you should just re-locate the element using find element as you found it in the first place.

**Comment by viji-123** [comment]
Thanks @timotiusmargo I am now able to locate the webelement once i tried to re-locate it like as you said.
