### ISSUE TITLE
{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}

### ISSUE THREAD

**Issue by smilinrobin** [microsoft/WinAppDriver#1360]
**Problem Statement**: We are trying to launch excel on a remote machine and perform some operations (take screenshot etc. ) .
While the Excel session is successfully started , the method call to take a screenshot fails with the below error:
{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}

**Error log:** Here is the complete error log from JENKINS's console output for reference:
18:24:24 [35m[Appium][39m Welcome to Appium v1.18.3
18:24:24 [35m[Appium][39m Non-default server args:
18:24:24 [35m[Appium][39m   port: 13709
18:24:24 [35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:13709
18:24:25 [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/status[39m
18:24:25 [35m[HTTP][39m [90m{}[39m
18:24:25 [debug] [35m[GENERIC][39m Calling AppiumDriver.getStatus() with args: []
18:24:25 [debug] [35m[GENERIC][39m Responding to client with driver.getStatus() result: {"build":{"version":"1.18.3"}}
18:24:25 [35m[HTTP][39m [37m<-- GET /wd/hub/status [39m[32m200[39m [90m9 ms - 68[39m
18:24:25 [35m[HTTP][39m [90m[39m
18:24:25 Appium URL http://0.0.0.0:13709/wd/hub
18:24:25 SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
18:24:25 SLF4J: Defaulting to no-operation MDCAdapter implementation.
18:24:25 SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
18:24:25 Executed command for stopping windriver
18:24:25 Started WINAPPDRIVER using : startWinAppDriverProcess
18:24:27 Windows Application Driver listening for requests at: http://10.X.X.X:4723/wd/hub
18:24:27 Press ENTER to exit.
18:24:27 ==========================================
18:24:27 POST /wd/hub/session HTTP/1.1
18:24:27 Accept-Encoding: gzip
18:24:27 Connection: Keep-Alive
18:24:27 Content-Length: 287
18:24:27 Content-Type: application/json; charset=utf-8
18:24:27 Host: 10.X.X.X:4723
18:24:27 User-Agent: selenium/3.141.59 (java windows)
18:24:27 {
18:24:27   "desiredCapabilities": {
18:24:27     "app": "Root",
18:24:27     "platformName": "Windows",
18:24:27     "deviceName": "WindowsPC"
18:24:27   },
18:24:27   "capabilities": {
18:24:27     "firstMatch": [
18:24:27       {
18:24:27         "appium:app": "Root",
18:24:27         "appium:deviceName": "WindowsPC",
18:24:27         "platformName": "windows"
18:24:27       }
18:24:27     ]
18:24:27   }
18:24:27 }
18:24:29 HTTP/1.1 200 OK
18:24:29 Content-Length: 111
18:24:29 Content-Type: application/json
18:24:29 {"sessionId":"EEA752AF-9076-4C63-A528-F75CBC215866","status":0,"value":{"app":"Root","platformName":"Windows"}}
18:24:29 4,1,windows-1252,Nov 04\2C 2020 7:54:29 AM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0\0D\0AINFO: Detected dialect: OSS\0D\0A
18:24:29 ==========================================
18:24:29 POST /wd/hub/session/EEA752AF-9076-4C63-A528-F75CBC215866/timeouts HTTP/1.1
18:24:29 Accept-Encoding: gzip
18:24:29 Connection: Keep-Alive
18:24:29 Content-Length: 38
18:24:29 Content-Type: application/json; charset=utf-8
18:24:29 Host: 10.X.X.X:4723
18:24:29 User-Agent: selenium/3.141.59 (java windows)
18:24:29 HTTP/1.1 200 OK
18:24:29 Content-Length: 63
18:24:29 Content-Type: application/json
18:24:29 {"sessionId":"EEA752AF-9076-4C63-A528-F75CBC215866","status":0}
18:24:59 5,1,com.AT.testscripts.ExcelTestServer,SomeTest(com.AT.testscripts.ExcelTestServer),com.AT.testscripts.ExcelTestServer,null,null
18:24:59 Excel session started with :io.appium.java_client.windows.WindowsDriver, Capabilities: {app=Root, javascriptEnabled=true, platform=WINDOWS, platformName=Windows}
18:24:59 ==========================================
18:24:59 GET /wd/hub/session/EEA752AF-9076-4C63-A528-F75CBC215866/window_handles HTTP/1.1
18:24:59 Accept-Encoding: gzip
18:24:59 Cache-Control: no-cache
18:24:59 Connection: Keep-Alive
18:24:59 Host: 10.X.X.X:4723
18:24:59 User-Agent: selenium/3.141.59 (java windows)
18:25:00 HTTP/1.1 200 OK
18:25:00 Content-Length: 74
18:25:00 Content-Type: application/json
18:25:00 {"sessionId":"EEA752AF-9076-4C63-A528-F75CBC215866","status":0,"value":[]}
18:25:00 3,1,windows-1252,All the open windows are : :[]\0A
18:25:08 ==========================================
18:25:08 GET /wd/hub/session/EEA752AF-9076-4C63-A528-F75CBC215866/screenshot HTTP/1.1
18:25:08 Accept-Encoding: gzip
18:25:08 Cache-Control: no-cache
18:25:08 Connection: Keep-Alive
18:25:08 Host: 10.X.X.X:4723
18:25:08 User-Agent: selenium/3.141.59 (java windows)
**18:25:08 HTTP/1.1 500 Internal Error**
18:25:08 Content-Length: 133
18:25:08 Content-Type: application/json
**18:25:08 {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}**
18:25:08 3,1,windows-1252,exception is An unknown error occurred in the remote end while processing the command. (WARNING: The server did not provide any stacktrace information)\0ACommand duration or timeout: 0 milliseconds\0ABuild info: version: '3.141.59'\2C revision: 'e82be7d358'\2C time: '2018-11-14T08:17:03'\0ASystem info: host: 'SERVERNAME'\2C ip: '10.X.X.X'\2C os.name: 'Windows Server 2016'\2C os.arch: 'amd64'\2C os.version: '10.0'\2C java.version: '11.0.6'\0ADriver info: io.appium.java_client.windows.WindowsDriver\0ACapabilities {app: Root\2C javascriptEnabled: true\2C platform: WINDOWS\2C platformName: Windows}\0ASession ID: EEA752AF-9076-4C63-A528-F75CBC215866\0A
18:25:08 ==========================================
18:25:08 DELETE /wd/hub/session/EEA752AF-9076-4C63-A528-F75CBC215866 HTTP/1.1
18:25:08 Accept-Encoding: gzip
18:25:08 Connection: Keep-Alive
18:25:08 Content-Length: 0
18:25:08 Host: 10.X.X.X:4723
18:25:08 User-Agent: selenium/3.141.59 (java windows)
18:25:08 HTTP/1.1 200 OK
18:25:08 Content-Length: 12
18:25:08 Content-Type: application/json
18:25:08 {"status":0}
18:25:08 2,1,org.apache.maven.surefire.testng.TestNGXmlTestSuite,TestSuite,null,null,null
18:25:09 Exiting...

**Code in Question:**
`

public class ExcelTestServer {

	private static WindowsDriver<RemoteWebElement> ExcelSession = null;
	private static AppiumDriverLocalService appiumService = null;

	@BeforeClass
	public static void setup() throws InterruptedException, IOException, TimeoutException, ExecutionException {

		
		String Appium_Node_Path = "path1";
		String Appium_JS_Path = "path2";

		appiumService = AppiumDriverLocalService.buildService(new AppiumServiceBuilder().usingAnyFreePort()
				.usingDriverExecutable(new File(Appium_Node_Path)).withAppiumJS(new File(Appium_JS_Path)));
		appiumService.start();

		String appiumServiceUrl = appiumService.getUrl().toString();
		

		// Stopping Older Winappdriver using taskkill /im WinAppDriver.exe /f:
		PageBase.stoppingWinAppDriverServerCmdTool();

		//Starting WinAppDriver : 
		ProcessBuilder pb = new ProcessBuilder("cmd", "start", "cmd.exe", "/K",
				"\"WinAppDriver.exe 10.X.XX.XX 4723/wd/hub\"");
		File dir = new File("C:/Program Files (x86)/Windows Application Driver");
		pb.directory(dir);
		Process p = null;
		try {
			p = pb.inheritIO().start();
		
		} catch (Exception e) {
			
			System.out.println("Exception is +" + e.getMessage());
		}

		

		// Setting the capabilities for Winappdriver
		DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability("app", "C:\\Program Files\\Microsoft Office\\Office16\\EXCEL.EXE");
		cap.setCapability("app", "Root");
		cap.setCapability("platformName", "Windows");
		cap.setCapability("deviceName", "WindowsPC");
		// ExcelSession = new WindowsDriver<RemoteWebElement>(new URL(appiumServiceUrl),
		// cap);
		ExcelSession = new WindowsDriver<RemoteWebElement>(new URL("http://10.X.XX.XX:4723/wd/hub"), cap);
		Assert.assertNotNull(ExcelSession);

		ExcelSession.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		Thread.sleep(30000);

	}

	@AfterClass
	public static void TearDown() throws InterruptedException, IOException, AWTException, UnsupportedFlavorException {

		if (ExcelSession != null) {
			ExcelSession.quit();
		}
		ExcelSession = null;
		appiumService.stop();
	}

	@Test
	public void SomeTest() throws InterruptedException, IOException, AWTException, UnsupportedFlavorException {
		try {
			System.out.println("Excel session started with :" + ExcelSession.toString());
			System.out.println("All the open windows are : :" + ExcelSession.getWindowHandles());

			File s = ExcelSession.getScreenshotAs(OutputType.FILE);
			System.out.println("Taking screenshot");
			FileUtils.copyFile(s, new File(System.getProperty("user.dir")
					+ "DesktopScreenshotStarting"  + ".png"));
			

		} catch (Exception e) {

			System.out.println("exception is " + e.getMessage());
		}

	}

}
`

**Things we have tried:** We have also tried attaching to an existing session , but that didnt work as well . And adding sleep methods for splash screens (as above). 

**Other notes:** 

- The same code works flawlessly on local 

- When the admin on the system **manually** navigates to the Winappdriver directory and triggers the command as "WinAppDriver.exe 10.X.XX.XX 4723/wd/hub" on a command prompt window, the code above works fine and the Excel operations are completed successfully. But in our CI/CD setup, we dont want to have the manual interventions. 

@timotiusmargo @hassanuz  @licanhua  - Folks-  Any leads would be appreciated here as its turning out to be a blocker for us.

**Comment by smilinrobin** [comment]
@kat-y @DHowett - can you please help us with the same?

**Comment by smilinrobin** [comment]
While we dont have a conclusive RCA for the issue , given the vague error message. We were able to solve the issue, by manually triggering the Winappdriver service on our server with ADMIN rights.

**Comment by bwomsm1** [comment]
@smilinrobin did you get any solution on that?
