### ISSUE TITLE
Implicit wait doesn't work for WinAppDriver - Java

### ISSUE THREAD

**Issue by nitish122** [microsoft/WinAppDriver#1363]
Implicit wait is not working for WinApp Driver. If an element is not present, it takes around 10 to 12 minutes for the script to fail. Instead of the time set by Implicit Wait. Please find the piece of code below:

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("deviceName","WindowsPC");
capabilities.setCapability("platformName","Windows");
capabilities.setCapability("app","Root");
		
winappDriver = new WindowsDriver(new URL("http://127.0.0.1:4723"), capabilities);
winappDriver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);

winappDriver.findElement(By.name("File")).click();

If File object is present, it clicks on it. 

If File object is not present. The script won't fail after 30 seconds as mentioned in the implicit wait.
It fails after 10 to 12 minutes.

Can you please help on the same ?

**Comment by nitish122** [comment]
@anunay1  - can you please help me on this

**Comment by nitish122** [comment]
@DHowett Can you please help ?

**Comment by anunay1** [comment]
capabilities.setCapability("app","Root"); is been set to root, 
Are you trying to create a session with particular application also there can be multiple names with File.

**Comment by nitish122** [comment]
Yes I set the capability to Root. Then the script is like.
Click on Microsoft Teams object. And then click on Files Object. 

Positive scenario works fine. 

Negative scenario. If the Files Object is not present. It takes 12 mins to fail. Instead of 30 seconds set in the implicit wait.

**Comment by nitish122** [comment]
For any else who faces this issue when implementing with java. If implicit wait of 2 seconds is given , driver checks for 1 min for element visibility. 4 seconds -> waits for 2 min.

Since , I had set 30 seconds as implicit wait. It was waiting for 15 mins before failing in negative scenarios.

Have updated implicit wait to 4 seconds now. And it's working as expected. This is weird behaviour. But is slowing my problem. So closing this issue.
