### ISSUE TITLE
How to get an element using regex?

### ISSUE THREAD

**Issue by dkuba** [microsoft/WinAppDriver#1367]
I use python to automate ui by appium windriver.
I want to get an element using partial name. Any idea?

**Comment by anunay1** [comment]
You can use xpath with starts with.

**Comment by Imperixal** [comment]
@dkuba  as @anunay1 said, you can use xpath `driver.find_element_by_xpath(element_name[@contains, 'searched text'])` But you should know that using XPATH with Appium and WinAppDriver is really, reeeeeraly slow comparing to `find_elements_by_name` or `find_element_by_accessibility_id`. 

If you care about the speed of your code, your only chance is using method `driver.find_elements_by_name` or `driver.find_element_by_accessibility_id` (note the 's' in 'elements'). You will get a list of all found elements with the appium webElement pointer. You then need create inner python method that will somehow find the element containing the name you are looking for.

Miroslav

**Comment by dkuba** [comment]
Thanks! How to get all of all elements?

**Comment by Imperixal** [comment]
@dkuba what do you mean by "get all of all elements" ? You mean except using "find_elements_by_..." ?

**Comment by dkuba** [comment]
Is there any way to get all elements names list?

**Comment by Imperixal** [comment]
I don't know about any such way. Why would you need that?

**Comment by dkuba** [comment]
Method find_elements_by_name requires certain name of element I’m looking for. So, to get a list of elements to find an element among them I need a name of element. Right?
But I have only the part on name, that’s why I need to find the element by regex.
Does find_element_by_name support finding by regex?

**Comment by anunay1** [comment]
Can you explain a bit more? What do you mean by only the part of the element?

**Comment by Imperixal** [comment]
@dkuba Okey, I guess i know what you need right now. 
there is an element called, lets say `1dDS232_closeWindowButton11` and string `1dDS232` is always there, but it is not a unique name, but rather dynamic name. And you need to localize the element by the second part of the name `closeWindowButton11` right?
If this is the scenario you want to use it for, then I understand the regex, but as far as I know ( and I am NOT a know-all-guru), this is not possible in WinAppDriver. Appium could have such method, but WinAppDriver doesn't support that.

Only way how you could probably do it is by trying to localize the element in different way (such as XPATH (but it will be slow).

**Comment by dkuba** [comment]
Thanks, but how to get it by xpat? driver.find_element_by_xpath(element_name[@contains, 'searched text']) doesnt work

**Comment by anunay1** [comment]
Can you share the pagesource.xml?

**Comment by dkuba** [comment]
I've found solution, it should be `find_element_by_xpath("//*[contains(@Name, 'part_of_the_name')]")`
