### ISSUE TITLE
Question: Usage of /react-native-windows/webdriver.git

### ISSUE THREAD

**Issue by serhatbolsu** [microsoft/WinAppDriver#1370]
Hi,

Knowing that this README is written last year, does it still make sense to use
"webdriver": "git+https://github.com/react-native-windows/webdriver.git",
while using with JS.

Can you please share why is it required or is it better to stick with default webdriver now

fyi: I am using webdriverIO to drive winappdriver for now

**Comment by licanhua** [comment]
It's for Azure pipeline only, and you don't need it anymore.

**Comment by serhatbolsu** [comment]
Thank you
