### ISSUE TITLE
WinAppDriver: find and attach to already running application

### ISSUE THREAD

**Issue by hroe** [Microsoft/WinAppDriver#138]
Hi, is there a way to find and attach to the ui of an  already running application? Thanks for any guidance.

**Comment by yodurr** [comment]
yes, start with a desktop session and then find your window from that starting point.  
For a desktop session example take a look at this sample:

https://github.com/Microsoft/WinAppDriver/blob/master/Samples/C%23/NotepadTest/Scenario.cs

**Comment by hroe** [comment]
Thanks for the explanation
