### ISSUE TITLE
 org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session.

### ISSUE THREAD

**Issue by chandruks83** [microsoft/WinAppDriver#1384]
This issue has been seen in multiple applications, can easily be reproduced when using "C:\Windows\System32\calc.exe" as the application path as in below code. Tried multiple suggestions, none of them worked.
capabilities.setCapability("app", "C:\\Windows\\System32\\calc.exe");

**Comment by anunay1** [comment]
Did you start WinAppdriver.exe?

**Comment by chandruks83** [comment]
Yes sure... tried multiple suggestions.. none of them worked...U can try with the calculator.exe available in system32 doesn't work... you can easily reproduce in your system also.Thanks and Regards,Chandrakanth ks 
-------- Original message --------From: anunay1 <notifications@github.com> Date: 30/11/2020  16:25  (GMT+05:30) To: microsoft/WinAppDriver <WinAppDriver@noreply.github.com> Cc: chandruks83 <chandruks83@gmail.com>, Author <author@noreply.github.com> Subject: Re: [microsoft/WinAppDriver]  org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. (#1384) 
Did you start WinAppdriver.exe?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/microsoft/WinAppDriver/issues/1384#issuecomment-735712330",
"url": "https://github.com/microsoft/WinAppDriver/issues/1384#issuecomment-735712330",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by licanhua** [comment]
dup of #1372. Please use app=Microsoft.WindowsCalculator_8wekyb3d8bbwe!App for UWP app

**Comment by DHowett** [comment]
Closing as a duplicate. Thanks!

**Comment by chandruks83** [comment]
Hi,I know using app=Microsoft.WindowsCalculator_8wekyb3d8bbwe!App works.But many of our applications are failing with the below exceptikn similar to calculator, so i want to know if there is a fix for this.It would help a lot.Thanks.Chandrakanth
-------- Original message --------From: Canhua Li <notifications@github.com> Date: 01/12/2020  01:36  (GMT+05:30) To: microsoft/WinAppDriver <WinAppDriver@noreply.github.com> Cc: chandruks83 <chandruks83@gmail.com>, Author <author@noreply.github.com> Subject: Re: [microsoft/WinAppDriver]  org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. (#1384) 
dup of #1372. Please use app=Microsoft.WindowsCalculator_8wekyb3d8bbwe!App for UWP app

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/microsoft/WinAppDriver/issues/1384#issuecomment-736012975",
"url": "https://github.com/microsoft/WinAppDriver/issues/1384#issuecomment-736012975",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
