### ISSUE TITLE
Test is failing via appium

### ISSUE THREAD

**Issue by menyp** [Microsoft/WinAppDriver#139]
Hi,

When I am starting the WinAppDriver.exe the code is running & our app is launched.

When I start the appium instead of the WinAppDriver it fails with the following error:
Any idea what I am missing? 

==========================
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Windows\system32>appium --address 127.0.0.1 --port 4723
[Appium] Welcome to Appium v1.6.4-beta
[Appium] Non-default server args:
[Appium]   address: '127.0.0.1'
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> POST /session {"capabilities":{"desiredCapabilities":{"app":"C:\\Program Files (x86)\\SkyGiraffe\\Studio\\Studio.exe","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{}},"desiredCapabilities":{"app":"C:\\Program Files (x86)\\SkyGiraffe\\Studio\\Studio.exe","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{}}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- POST /session 404 9 ms - 50
[HTTP] --> POST /session {"desiredCapabilities":{"app":"C:\\Program Files (x86)\\SkyGiraffe\\Studio\\Studio.exe","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{}}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- POST /session 404 4 ms - 50
[HTTP] --> POST /session {"capabilities":{"desiredCapabilities":{"app":"C:\\Program Files (x86)\\SkyGiraffe\\Studio\\Studio.exe","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{}}}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- POST /session 404 3 ms - 50

**Comment by yodurr** [comment]
Hi, one detail is you need to set the URL to Appium as127.0.0.1:4723/wd/hub in order for Appium to work.  Was that your issue?

**Comment by menyp** [comment]
Hi Y,
you are right on the target!
I set the URL as you pointed & it worked.
Thanks for the fast respond!

**Comment by yodurr** [comment]
glad to hear that fixed it!
