### ISSUE TITLE
Failed while run .Net + Winform System

### ISSUE THREAD

**Issue by Heidernlee** [microsoft/WinAppDriver#1398]
I'm using UIRecorder to get AbsoluteXPath and convert it to XPath 
so I can use it on WinAppDriver (C#), so far it's OK.
But today I get a AbsoluteXPath using UIRecorder like this
"/Pane[@ClassName=\"#32769\"][@Name=\"Desktop\"]/Window[@Name=\"AAA1\"][starts-with(@AutomationId,\"frm\")]/Button[@Name=\"BBB1\"][starts-with(@AutomationId,\"cmdbtn_\")]"
and I conver it to XPath like this
"//Window[@Name='AAA1'][starts-with(@AutomationId,'frm')]/Button[@Name='BBB1'][starts-with(@AutomationId,'cmdbtn_')]"
Didn't work using [FindElementByXPath(this XPath)]
Is it because of the [starts-with] node or [AutomationId] node ? it's only recorded by .Net + Winform.

**Comment by Shakevg** [comment]
@Heidernlee Looks like an error in Xpath (should be @Name instead of @name).
Could you try 
"//Window[@**N**ame='AAA1'][starts-with(@AutomationId,'frm')]/Button[@**N**ame='BBB1'][starts-with(@AutomationId,'cmdbtn_')]"

**Comment by Heidernlee** [comment]
@Shakevg Thanks for your response. what I wrote is @Name(Upper N),
Github changed to lower "n" character automatically.....
I think this issue cause of [starts-with] or [AutomationId] node....
I don't know how to use them for XPath

**Comment by Heidernlee** [comment]
Issue Solved.
Turns out ,  It's not because of [starts-with] or [AutomationId] node...
My Windows App runs .Hide() and .Show() to open or close windows ,
and in this case ,we should create new Window Session
Issue closed
