### ISSUE TITLE
Unable to get Windows application Handle Id

### ISSUE THREAD

**Issue by smilinrobin** [microsoft/WinAppDriver#1400]
We are using the below code to get the handle ID for an open Excel sheet:
`String topWindow = ExcelSession1.findElementByName("Home").getAttribute("NativeWindowHandle");
System.out.println("topWindow is" + topWindow);`

However, it is printing the "topWindow" value as 0 . 
How can we get the window handle ID so as to switch to the active window ?

**Comment by thinski** [comment]
I tried this by using findElementByXpath, and it worked.
I got the xpath by using WAD UI Recoder.

**Comment by smilinrobin** [comment]
@thinski  - ExcelSession1 is not a Root session. We'll try findElementByXpath and check it out. But, I am not sure, how findElementByName vs findElementByXpath would impact the Window handle ID

**Comment by thinski** [comment]
@smilinrobin 
ExcelSession1 must be a Root session.
`DesiredCapabilities appCapabilities = new DesiredCapabilities();
appCapabilities.SetCapability("app", "Root");
ExcelSession1= new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), appCapabilities);`
You can have a look at https://github.com/microsoft/WinAppDriver/blob/master/Docs/FAQ.md#when-and-how-to-attach-to-an-existing-app-window
