### ISSUE TITLE
Using VS code to creat tests

### ISSUE THREAD

**Issue by ankugarg** [microsoft/WinAppDriver#1403]
Please share steps how to use VS code for implementing/creating tests

**Comment by anunay1** [comment]
Have you tried anything yet.

**Comment by ankugarg** [comment]
I didn't tried anything. Wanted to know if there are any steps to achieve same.

**Comment by anunay1** [comment]
Which language binding are you planning to use?

**Comment by ankugarg** [comment]
Want to use Java.

**Comment by anunay1** [comment]
Check the link
https://code.visualstudio.com/docs/java/java-tutorial

**Comment by anunay1** [comment]
This will help you to get started

**Comment by ankugarg** [comment]
Thanks, I will try it.
