### ISSUE TITLE
WindowsDriver constructor throws 'org.openqa.selenium.UnsupportedCommandException'

### ISSUE THREAD

**Issue by rszmacinski** [Microsoft/WinAppDriver#141]
Code :
 DesiredCapabilities capabilities = new DesiredCapabilities();
 capabilities.setCapability(MobileCapabilityType.APP, System.getProperty("mobileAppLocation", "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"));
 new WindowsDriver(new URL("http://192.168.1.71:7777"), capabilities)

Exception :           
Method threw 'org.openqa.selenium.UnsupportedCommandException' exception.
Command not recognized: GET: /session/B2B0C140-8B22-4733-B7EF-939AF26D3A00/context (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 13 milliseconds

WinAppDriver log :
{"sessionId":"70F5FA09-915B-479C-B060-FDC54909372D","status":0,"value":{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","platformName":"Windows"}}
==========================================
GET /session/70F5FA09-915B-479C-B060-FDC54909372D/context HTTP/1.1
Accept-Encoding: gzip,deflate
Cache-Control: no-cache
Connection: Keep-Alive
Host: 192.168.1.71:7777
User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_92)
### WinAppDriver::CommandHandler::Session::HandleCommandAsMidPoint - Command context is not recognized
HTTP/1.1 404 Not Found
Content-Length: 143
Content-Type: application/json
{"status":9,"value":{"error":"unknown command","message":"Command not recognized: GET: /session/70F5FA09-915B-479C-B060-FDC54909372D/context"}}

**Comment by yodurr** [comment]
Hi, what is the WindowsDriver class?
new WindowsDriver

Can you share more info about your test code, are you using the .Net driver nuget package?

**Comment by yodurr** [comment]
closing with no reply after a week - please open new bug if this is still an open issue and in that bug include more info on your test code.

It looks like you're targeting a remote machine, and if so your issue may be firewall related on the remote machine.

**Comment by gadgadskiy** [comment]
@yodurr I've got the same error, but on much newer soft
Appium Desktop 1.9.1
WinAppDriver 1.1.3.0
appium-java-client.version 6.1.0
(tried selenium 3.12.0, 3.14.0 or without explicit reference of selenium dependencies)
For `/context`, `/contexts` etc commands, every time error is: 
```
{
  "status": 9,
  "value": {
    "message": "Command not recognized: GET: /session/D3EEBB15-3B6D-4736-9A3D-E1E09F83ADC0/contexts"
  },
  "sessionId": "00828418-aa03-4ba3-8e33-a791f98458f8"
}
```
My capabilities
```
{
  "status": 0,
  "value": {
    "app": "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App",
    "platformName": "Windows"
  }
}
```
Please, help, what can be wrong?
