### ISSUE TITLE
WinAppDriver does not detect elements

### ISSUE THREAD

**Issue by ereminmax** [microsoft/WinAppDriver#1410]
So, I spend several days trying to figure out how to solve that issue. Let me explain.
I run my automation tests by executing the exe file containing the test itself. Inside that test I start a new process by invoking 

`Process process = new Process(); `
`ProcessStartInfo startInfo = new ProcessStartInfo();`
`process.EnableRaisingEvents = false;`
`startInfo.FileName = config.Path;`
`startInfo.RedirectStandardError = false;`
`startInfo.RedirectStandardOutput = true;`
`startInfo.UseShellExecute = false;`
`process.StartInfo = startInfo;`
`process.Start();` 
Then I try to test it but simply the WindowsDriver attached to Root desktop session can not click on a button giving the error that the element is not found. Interestingly, I can click on the elements if I run the test from Visual Studio but not by running the exe file. 

I successfully can click on different elements of the desktop even the icon of the started process inside the tray but everything which is enclosed by the edges of the target window is not accessible. I successfully managed to attach the WindowsDriver session to that process using the Handle of the process and take the screenshot of that window. It's clear that the elements are presented. Also, I could navigate the button and other elements of the target window inside inspector.exe (part of Microsoft Development Kit). But the UIRecorder still does not detect elements.

**Comment by Shakevg** [comment]
@ereminmax You can try next #1236

**Comment by guillaume-ansquer** [comment]
WinAppDriver don't find element if one of a parent element have an empty AutomationID.
Use Inspect.exe to verify it.
If one or many parent element have a empty AutomationID, you have to modify your tested application (you can also add name if there are missing).

**Comment by ereminmax** [comment]
Solved this problem by running the process with psexec64
