### ISSUE TITLE
Not able to identify the popups and controls in popups

### ISSUE THREAD

**Issue by praveenvinnakota** [microsoft/WinAppDriver#1416]
Hi,

I am launching an application and I am able to identify all the controls/elements in the application using WinAppDriver. Now when I click on login button, it will open a new window/dialog with user id, password text boxes, in this dialog I am not able to identify any element.
Any help or suggestions please?
Also, any idea on how to switch focus from one window to another window?

Thanks,
Praveen.

**Comment by anunay1** [comment]
What is shown in the inspect. Is the window part of the same tree or its a separate window Al together

**Comment by praveenvinnakota** [comment]
> What is shown in the inspect. Is the window part of the same tree or its a separate window Al together

Its a separate window altogether, its not in the same tree.. and when I try to get the title using getTitle(), its showing the first window name. Not able to switch to the second window.

**Comment by anunay1** [comment]
Which language binding are you using

**Comment by praveenvinnakota** [comment]
> Which language binding are you using

I am using Java..

**Here is the sample code :**
DesiredCapabilities cap = new DesiredCapabilities();
cap.setCapability("app", appPath);
cap.setCapability("platformName", "Windows");
cap.setCapability("deviceName", "WindowsPC");

winDriver = new WindowsDriver(new URL("http://127.0.0.1:4723"), cap);
System.out.println("Title : " + winDriver.getTitle()); // lets say, here I am getting the title as "My Application"
winDriver.findElementByXPath("//Button[@Name='Login']").click(); // This will open a new window "Login"
Thread.sleep(3000);
System.out.println("Title : " + winDriver.getTitle()); // here also I am getting the title as "My Application"
winDriver.findElementByXPath("//TextBox[@AutomationId='UserName']").sendKeys("jasdfj"); // entering some text in user name text box, and its not working as the control is in "Login" window not in "My Application" window
- Not able to switch from "My Application" window to "Login" window

**Comment by anunay1** [comment]
use the below code
`
DesiredCapabilities capabilities = new DesiredCapabilities();
					capabilities.setCapability("app", "Root");
					desktopsession = new WindowsDriver<WindowsElement>(new
					URL(WindowsApplicationDriverUrl),capabilities);


					String topWindow = desktopsession.findElementByClassName("Your popup window").getAttribute("NativeWindowHandle");
					int MAWinHandleInt = Integer.parseInt(topWindow);
					String MAWinHandleHex = Integer.toHexString(MAWinHandleInt);

					DesiredCapabilities caps = new DesiredCapabilities();
					caps.setCapability("appTopLevelWindow", MAWinHandleHex);
					session = new WindowsDriver<WindowsElement>(new URL(WindowsApplicationDriverUrl), caps);
                                        session.findElementsByName("Your control").click();

`

**Comment by praveenvinnakota** [comment]
> use the below code
> `
> DesiredCapabilities capabilities = new DesiredCapabilities();
> capabilities.setCapability("app", "Root");
> desktopsession = new WindowsDriver(new
> URL(WindowsApplicationDriverUrl),capabilities);
> 
> ```
> 				String topWindow = desktopsession.findElementByClassName("Your popup window").getAttribute("NativeWindowHandle");
> 				int MAWinHandleInt = Integer.parseInt(topWindow);
> 				String MAWinHandleHex = Integer.toHexString(MAWinHandleInt);
> 
> 				DesiredCapabilities caps = new DesiredCapabilities();
> 				caps.setCapability("appTopLevelWindow", MAWinHandleHex);
> 				session = new WindowsDriver<WindowsElement>(new URL(WindowsApplicationDriverUrl), caps);
>                                     session.findElementByName("Your control").click();
> ```
> 
> `



> use the below code
> `
> DesiredCapabilities capabilities = new DesiredCapabilities();
> capabilities.setCapability("app", "Root");
> desktopsession = new WindowsDriver(new
> URL(WindowsApplicationDriverUrl),capabilities);
> 
> ```
> 				String topWindow = desktopsession.findElementByClassName("Your popup window").getAttribute("NativeWindowHandle");
> 				int MAWinHandleInt = Integer.parseInt(topWindow);
> 				String MAWinHandleHex = Integer.toHexString(MAWinHandleInt);
> 
> 				DesiredCapabilities caps = new DesiredCapabilities();
> 				caps.setCapability("appTopLevelWindow", MAWinHandleHex);
> 				session = new WindowsDriver<WindowsElement>(new URL(WindowsApplicationDriverUrl), caps);
>                                     session.findElementByName("Your control").click();
> ```
> 
> `

Thank you very much Anunay.. it worked..

**Comment by praveenvinnakota** [comment]
Thanks Anunay.. The above code worked. Closing the issue..
