### ISSUE TITLE
Unable to launch WPF click-once application using WinAppDriver

### ISSUE THREAD

**Issue by Surya0413** [microsoft/WinAppDriver#1430]
![WinApp_DriverError](https://user-images.githubusercontent.com/78079851/105982818-d2ffd880-60bd-11eb-9318-f1d2ce284144.png)
I am new to Windows Application Driver, I am trying to automate WPF application it is click-once application.
I am getting null reference for my session. My code is like: 

        private const string appiumDriverURI = "http://127.0.0.1:4723/";
         private string notepadAppid = @"https://abc.superapp.biz/Main/Mainten.Shell.Application";       
        protected static WindowsDriver<WindowsElement> drivers;

       [SetUp]
        public void Setups()
        {
            try
            {
                AppiumOptions appCapabilities = new AppiumOptions();
                appCapabilities.AddAdditionalCapability("app", notepadAppid);
                appCapabilities.AddAdditionalCapability("deviceName", "WindowsPC");
                drivers = new WindowsDriver<WindowsElement>(new Uri(appiumDriverURI), appCapabilities);
            }
            catch (Exception ex)
            {
                throw new Exception();
            }
        }

        [Test]
        public void DemoLogin()
        {
            WaitForAppLoginPage();
        }

I am not getting any exception, but 'drivers' is showing null

**Comment by shoaibmansoor** [comment]
Hi @Surya0413  As far as I know, `app` capability accepts executable full path or app id.

Refer https://github.com/Microsoft/WinAppDriver/issues/9#issuecomment-210407800 to get application id.

However, mostly I end up using the executable path as app id is not available for older windows applications

**Comment by Surya0413** [comment]
Thanks for reply @shoaibmansoor, in my case my application is click-once application. There is no direct exe available for this.

**Comment by anunay1** [comment]
In that case you need to use cortana to search for the app and then select the app. You can get get the code for cortana in the sample application.

**Comment by Surya0413** [comment]
Thanks @anunay1 for reply:
  protected static WindowsDriver<WindowsElement> session;
        protected static WindowsDriver<WindowsElement> CortanaSession;

        [Test]

        public void TPM_()
        {


            var ao = new AppiumOptions();
            ao.AddAdditionalCapability("app", "Root");
            session = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), ao);
            

            WindowsElement ele = session.FindElement(By.Name("Running applications"));


            var sss = ele.FindElements(By.XPath("//child::*")).ToList();
            String MAWinHandleHex = string.Empty;


            var appCapabilities = new AppiumOptions();

            foreach (WindowsElement el in sss)
            {
                if (el.Text.Contains("Myapplication"))
                {
                    el.Click();
                    var CortanaTopLevelWindowHandle = el.GetAttribute("NativeWindowHandle");

                    CortanaTopLevelWindowHandle = (int.Parse(CortanaTopLevelWindowHandle)).ToString("x"); // Convert to Hex

                    


                    appCapabilities.AddAdditionalCapability("appTopLevelWindow", CortanaTopLevelWindowHandle);


                    break;
                }
            }


            CortanaSession = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), appCapabilities, TimeSpan.FromMinutes(3));

        }
I am getting error at CortanaSession :
 CortanaSession = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), appCapabilities, TimeSpan.FromMinutes(3));

**Comment by anunay1** [comment]
Does el.click work? After this the cortana window will disappear I believe.

**Comment by Surya0413** [comment]
Yes it is click, ok i will comment that part and check.

**Comment by Surya0413** [comment]
I am getting Same error .

**Comment by anunay1** [comment]
No you do not need to comment that, after clicking the cortana window will disappear, then you need to create a root session and then switch to your application and after that it should work

**Comment by anunay1** [comment]
The exception is because you do not have any cortana window opened

**Comment by Surya0413** [comment]
I did not get you @anunay1 ...

**Comment by anunay1** [comment]
Give me a hangout call anunayathakur1@gmail.com

**Comment by anunay1** [comment]
This is how it will work 
`
 [Test]

    public void TPM_()
    {


        var ao = new AppiumOptions();
        ao.AddAdditionalCapability("app", "Root");
        session = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), ao);
        

        WindowsElement ele = session.FindElement(By.Name("Running applications"));


        var sss = ele.FindElements(By.XPath("//child::*")).ToList();
        String MAWinHandleHex = string.Empty;


        var appCapabilities = new AppiumOptions();

        foreach (WindowsElement el in sss)
        {
            if (el.Text.Contains("Myapplication"))
            {
                el.Click();
               
            }
        }
		
		

       string mainWindowTitle = "";
                var allProcesses1 = Process.GetProcesses();
                foreach (Process process in allProcesses1)
                {
                    if (process.ProcessName.Contains("Your Application"))
                    {
                        mainWindowTitle = process.MainWindowTitle;
                        Logger.Logger.LogInfo("The main window title is " + mainWindowTitle);
                        
                    }
                }

                DesiredCapabilities desktopCapabilities = new DesiredCapabilities();
                desktopCapabilities.SetCapability("app", "Root");
                desktopSession = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), desktopCapabilities);
                Assert.IsNotNull(desktopSession);

                var RSWindow = desktopSession.FindElementByName(mainWindowTitle);
                var RSTopLevelWindowHandle = RSWindow.GetAttribute("NativeWindowHandle");
                RSTopLevelWindowHandle = (int.Parse(RSTopLevelWindowHandle)).ToString("x");

                DesiredCapabilities appcapabilities = new DesiredCapabilities();
                appcapabilities.SetCapability("appTopLevelWindow", RSTopLevelWindowHandle);
                driver = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appcapabilities, TimeSpan.FromSeconds(50));
				
				//then use this driver session

    }

`

**Comment by Surya0413** [comment]
ok Thanks @anunay1 I will try and let you know

**Comment by Surya0413** [comment]
Thanks @anunay1 it is working fine now for me. Thanks

**Comment by anunay1** [comment]
Good 👍
