### ISSUE TITLE
X-path is not working after login to application ?

### ISSUE THREAD

**Issue by Surya0413** [microsoft/WinAppDriver#1431]
In WPF application after login to the application with WinAppDriver, I am unable to find the control with x-path I am able to find the control only with "CortanaSession.FindElementByName("Subdivision Search").Click()"  even I switch the "CortanaSession.SwitchTo().Window(CortanaSession.WindowHandles.First())" but X-path is not working I am getting 'unable to locate the element' message when I am using X-path "CortanaSession.FindElement(By.XPath("//*[@Name='Subdivision']")).Click()". 
Do I need to create root session again after login because it is another window?

**Comment by Shakevg** [comment]
@Surya0413 It depends on the application. The application may create a new window and you need to attach one more time after login.

**Comment by Surya0413** [comment]
OK thanks @Shakevg , I will try and let you know.

**Comment by shoaibm-aurea** [comment]
@Surya0413 It could be related [this issue](https://github.com/microsoft/WinAppDriver/issues/583#issuecomment-472216606) as well. Please try to find element by `//*` xpath and if it doesn't work then options are to use WAD 1.1 or other locator strategies.

**Comment by Surya0413** [comment]
Hi @Shakevg  created root session again, now I am able to make finding the elements using X-path, Thanks
