### ISSUE TITLE
Will Windows 7 be supported in the future?

### ISSUE THREAD

**Issue by congzhangzh** [Microsoft/WinAppDriver#144]
Hi,
  There are many classical applications designed and run on windows 7, so that will be very convince if the driver can proper work on windows 7(which not now!).
  Does Microsoft has a plan? If the developer want to develop app just work for windows 10, they may not choose win32, winform or even wpf  as the toolbox! But, if the developer has a wpf application, they may want to test the application on both windows 7 and windows 10.
  So do not just expand the driver to more widely like win32, winform, wpf, hybird, but also make the support available to so broadly used windows like windows 7. 
  Tks,
Cong

**Comment by yodurr** [comment]
Hi, please upvote and add comments here.  Thanks.  
https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/13518501-winappdriver-support-to-win-7-and-8

**Comment by congzhangzh** [comment]
ok, got it:)
