### ISSUE TITLE
getting Unable to load DLL 'UIXPathLib.dll': The specified module could not be found.

### ISSUE THREAD

**Issue by lmadaka** [microsoft/WinAppDriver#1445]
Getting error when i run UIRecorder solution==> Unable to load DLL 'UIXPathLib.dll': The specified module could not be found.
got latest version, installed c++ extension too.
please advise

**Comment by lmadaka** [comment]
after targeting to 2019 VS version its worked fine

**Comment by razvanroscalgim** [comment]
@lmadaka  how do you change target?
