### ISSUE TITLE
Scroll function doesn't work on v0.7-beta release.

### ISSUE THREAD

**Issue by dino-su** [Microsoft/WinAppDriver#145]
Hi,

I'm using v0.7-beta release and the TouchScroll sample doesn't works for me

I can see the touch/scroll command has been accepted by WinAppDriver but the Edge Browser doesn't scroll at all.

https://github.com/Microsoft/WinAppDriver/blob/master/Tests/W3CWebDriver/TouchScroll.cs.

**Comment by timotiusmargo** [comment]
Hi @dino-su,

We have made some improvements in the past months to the touch mechanism. In addition, we also made the scroll test simpler and more reliable by using the Alarms & Clock app instead.
https://github.com/Microsoft/WinAppDriver/blob/v0.9-beta/Tests/W3CWebDriver/TouchScroll.cs

Would you please check the latest [v0.9 release ](https://github.com/Microsoft/WinAppDriver/tree/v0.9-beta) out?
