### ISSUE TITLE
Windows 10  Word Testing - No handle to identify certain objects

### ISSUE THREAD

**Issue by chrber** [Microsoft/WinAppDriver#146]
It might just be me being inexperienced with the framework, but I tried the following for Office 2016 Word App:

// FindElementByAccessibilityId - AutomationId empty
// FindElementByClassName - ClassName is the same for all buttons
// FindElementById - RuntimeId is dynamic, new with every restart
// FindElementByName - Name is "Close", element is not found with this name
// FindElementByTagName - LocalizedControlType is Button, which is also the same for all buttons

Could you advice me how I can access elements in MS Word?

Thank you.
Christian

**Comment by yodurr** [comment]
Hi @chrber if you are writing a test in C# using the Appium .Net Driver nuget package, you can use the WindowsDriver class to create the session.  With that session you can use FindElementByAccessibilityId and it should work.  

Watch for getting attached to splash screens - if you aren't finding anything in your session you may need to create a separate desktop session and find the Word window that you're testing.  A desktop session is created this way:
    DesiredCapabilities desktopCapabilities = new DesiredCapabilities();
    desktopCapabilities.SetCapability("app", "Root");

**Comment by chrber** [comment]
I use Java 8 to develop. I have a running session and I can manipulate things with other apps (e.g. Notepad, and calculator). My initial post should be read in a way that I tried all of the methods and the part behind the dash states the results. I use inspect to check for the values in the required field. So I have no problem using the framework, but a very specific problem with a window in the Word application. Specifically the close button in this popup does not have a value in the AutomationId field and the other problems I stated behind the dashed.

**Comment by yodurr** [comment]
Regarding "Specifically the close button in this popup"
Which popup in particular?  Word is big :)

**Comment by chrber** [comment]
Let's take Office 2016, the Font Ribbon, when you click in the lower right corner and you get the extended Font popup. There I would like to click the "Cancel" Button.

The following can not be used to identify the object (at least looking at inspect)
  - AutomationID, because does not exist for this button
  - ClassName
  - RuntimeID, because it  changes with every startup of the program
  - Name, is set, but since, as you say: "Word is big", this does not uniquly identify the button
  - LocalizedControlType is Button

Am I missing something or is inspect not showing everything, is there a better way?

**Comment by stockwep** [comment]
You can locate the specific button by traversing the tree you see in `inspect.exe`.

This will get the Font windows cancel button:

```csharp
var cancelButton = session
    .FindElementByClassName("OpusApp")
    .FindElementByXPath("/Window/Window[@ClassName=\"bosa_sdm_msword\"]/Button[@Name=\"Cancel\"]");
cancelButton.Click();
```

Assuming you are interacting with the Word and Font windows multiple times it is best to locate key elements and use them as a root when locating other elements, as below:

```csharp
var wordApp = session.FindElementByClassName("OpusApp");
var fontWindow = wordApp.FindElementByClassName("bosa_sdm_msword");
var cancelButton = fontWindow.FindElementByName("Cancel");
cancelButton.Click();
```

**Comment by timotiusmargo** [comment]
Hi @chrber,

As @stockwep suggested, finding nested element by locating the parent node first and work your way through works very well. When you get to the point that you can no longer specify the target element without ambiguity, you can use XPath or finding multiple elements to select the item.

In [v1.0-RC release](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.0-RC), the element `GetAttribute` API now supports arbitrary attributes. Thus, you can use any of the attributes shown in `inspect.exe` to identify your element as well when iterating through the list of elements.

**Comment by dhapolapankaj** [comment]
I would suggest not always depend on FindElementByAccessibilityId
Finding element by XPath is the most trusted way.
