### ISSUE TITLE
在程序已经启动的情况下WinAppDriver监控操作该软件

### ISSUE THREAD

**Issue by duyumoyan** [microsoft/WinAppDriver#1462]
产品是由浏览器拉起的实时视频会话软件，WinAppDriver是否可以在浏览器拉起视频会话软件后监控该软件，进行自动化测试任务
试着使用过autoLaunch参数，但不起作用

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("deviceName", "WindowsPC");
capabilities.setCapability("platformName", "Windows");
capabilities.setCapability("app", "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App");
capabilities.setCapability("autoLaunch","False");   //   "false"  ,  false 都试过
WindowsDriver windowsDriver = new WindowsDriver(new URL("http://127.0.0.1:4723/"), capabilities);
windowsDriver.manage().timeouts().implicitlyWait(200, TimeUnit.SECONDS);

**Comment by liljohnak** [comment]
Google translate:
The product is a real-time video session software pulled up by the browser. Can WinAppDriver monitor the software after the browser pulls up the video session software and perform automated test tasks? Tried to use the autoLaunch parameter, but it doesn't work
