### ISSUE TITLE
A group of elements can't be detected by WinAppDriverUiRecorder or Inspect.exe (urgent)

### ISSUE THREAD

**Issue by zahraazezo** [microsoft/WinAppDriver#1466]
I'm facing a problem while automating a desktop App using WinAppDriver , To proceed automating my App a certain button should be clicked , but neither the WinAppDriverUiRecorder nor Inspect.exe can detect this button 

<img width="960" alt="Not detected button" src="https://user-images.githubusercontent.com/39830260/110558386-13398880-814b-11eb-9698-3739f6e07787.png">

Windows 10
WindowsApplicationDriver_1.2.1

**Comment by anunay1** [comment]
Automation properties are not there for elements that is the reason its not shown in inspect.

**Comment by zahraazezo** [comment]
@anunay1  thanks for reply , but is there any workaround , I have to proceed automating the app
and what is the wrong with these elements , why they aren't shown in inspect  ???

**Comment by zahraazezo** [comment]
@anunay1  thanks for reply , but there is any workaround ? and excuse me , I want to ask what are the automation prosperities ? and why are they aren't there ?

**Comment by zahraazezo** [comment]
We asked our developers to maintain the buttons HTML to be interactable
