### ISSUE TITLE
System.NullReferenceException : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by dishantrath** [microsoft/WinAppDriver#1474]
private static void WhenSearchedForCitrix()
        {
            DesktopTestLibs.ContainerUtil.whenApplicationIsLaunched("Root"); c   //internally calling root app
            DesktopTestLibs.ContainerUtil.GetDriver().FindElementByName("Start").Click(); //DesktopTestLibs.ContainerUtil.GetDriver() is nothing but calling the driver
            Thread.Sleep(2000);
            DesktopTestLibs.ContainerUtil.GetDriver().FindElementByName("Start").SendKeys("Add or Remove Prgrams");

            var fileExplorerElemenet = DesktopTestLibs.ContainerUtil.GetDriver().FindElementByName("Cortana");
            var topLevel = fileExplorerElemenet.GetAttribute("NativeWindowHandle");
            topLevel = int.Parse(topLevel).ToString("X");

            AppiumOptions appium2 = new AppiumOptions();
            appium2.AddAdditionalCapability("appTopLevelWindow", topLevel);
            WindowsDriver<WindowsElement> SearchSession = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), appium2);
            SearchSession.FindElementByName("Search box").SendKeys(Keys.Enter);
            SearchSession.CloseApp();
            DesktopTestLibs.ContainerUtil.GetDriver().CloseApp();

        }

        private static void WhenExtractedVersionOfCitrix()
        {
            DesktopTestLibs.ContainerUtil.whenApplicationIsLaunched("Root");

            var settings = DesktopTestLibs.ContainerUtil.GetDriver().FindElementByName("Settings");
            var setting_TopLevel = settings.GetAttribute("NativeWindowHandle");
            var topLevel1 = int.Parse(setting_TopLevel).ToString("X");

            AppiumOptions appium3 = new AppiumOptions();
            appium3.AddAdditionalCapability("appTopLevelWindow", topLevel1);
            WindowsDriver<WindowsElement> SettingSession = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), appium3);

            SettingSession.FindElementByName("Search box, Search this list").Click();
            Thread.Sleep(2000);
            SettingSession.FindElementByName("Search box, Search this list").SendKeys("Citrix Workspace");
            Thread.Sleep(10000);

            SettingSession.FindElementByXPath("//Text[@AutomationId='CitrixOnlinePluginPackWeb_TitleTextBlock']").Click();

            var versionCitrixWrospace = SettingSession.FindElementByXPath("//ListItem/Text[@AutomationId='CitrixOnlinePluginPackWeb_DescriptionTextBlock']").Text;
            Thread.Sleep(6000);
            Common.LogInfo("The version of Citrix Workspace installed is " + versionCitrixWrospace);
            //SettingSession.CloseApp();

        }

        public static void VerfiyCitrixReceiver()
        {
            WhenSearchedForCitrix();
            WhenExtractedVersionOfCitrix();

            //action = new Actions(DesktopSession);
            //action.ContextClick(DesktopSession.FindElementByXPath("//Button[@Name='Citrix Workspace']")).Perform();
            //Thread.Sleep(5000);
            //DesktopSession.FindElementByXPath("//Menu[@ClassName='#32768'][@Name='Context']/MenuItem[@Name='Advanced Preferences']").Click();

            //DesktopSession.FindElementByName("Name	PrefPanel – 1 running window");
            //var version = DesktopSession.FindElementByXPath("//Pane[@AutomationId='topPane']/Text[@AutomationId='verInfo']");
            //DesktopSession.FindElementByName("Notification Overflow").FindElementByName("Citrix Workspace").Click();
            //DesktopSession.FindElementByName("Taskbar").FindElementByName("Notification Chevron").Click();
        }

Error received:
TearDown : **System.NullReferenceException : Object reference not set to an instance of an object.**
  Stack Trace: 
    --TearDown
    ContainerUtil.WhenBrowserWindowIsClosed()

Ideally post every completed script "ContainerUtil.WhenBrowserWindowIsClosed()" would run

**Comment by anunay1** [comment]
not a WAD issue issue with your code.

**Comment by dishantrath** [comment]
Yes the issue was with my code itself. I was trying to close the web browser thinking i am closing the driver session.
