### ISSUE TITLE
Not able to click on print button when the window application under test triggers the print dialogue window. Please help.

### ISSUE THREAD

**Issue by sahaiswat** [microsoft/WinAppDriver#1477]

**Comment by anunay1** [comment]
What have you already tried mere giving the title does not help much, which language binding are you using.

**Comment by sahaiswat** [comment]
Sorry
I am using C# 
I have tried finding the xpath for the print dialogue window and then clicking on print button. But somehow that does not work.

**Comment by anunay1** [comment]
Check inspect it might be a separate window altogether

**Comment by sahaiswat** [comment]
It opens up as a seperate window. Well in that case what should be done?

**Comment by anunay1** [comment]
then you need to create a desktop session with root and switch to the print window.

**Comment by anunay1** [comment]
check wiki on how to create a root session and jump to the opened window.

**Comment by sahaiswat** [comment]
Thank you. Will do that and post my result.

**Comment by anunay1** [comment]
check the bug #894 I have also uploaded a C# project. will save you time

**Comment by sahaiswat** [comment]
Thanks i tried this...now i am able to focus on the print window but still not able to click print.
It somehow focuses on one element and does not move to other element. I used action class to move to the print element.
Any suggestions..

**Comment by anunay1** [comment]
Can you how many print element are there? There might be more than 1.

**Comment by sahaiswat** [comment]
Yes there are more than one...but it is not getting clicked with automation id

**Comment by anunay1** [comment]
check with all the index values.

**Comment by sahaiswat** [comment]
Can you please elaborate a little?

**Comment by anunay1** [comment]
can you share the code how you are getting the count.

**Comment by sahaiswat** [comment]
I was able to get the xpath. Thanks a lot for your help.

**Comment by anunay1** [comment]
If it's resolved please close the bug
