### ISSUE TITLE
Cannot connect to ApplicationSession and DesktopSession on the same Appium Server

### ISSUE THREAD

**Issue by plosty** [Microsoft/WinAppDriver#148]
Hi,

We are starting using WinAppDriver/Appium to automate testing a Windows desktop product; we have found that to get to a window outside the main application we need to setup a DesktopSession as in the [Alarm Clock](https://github.com/Microsoft/WinAppDriver/tree/master/Samples/C%23/AlarmClockTest) sample, but we have to set up two separate Appium servers to get this to work.

In the Alarm Clock example you just have the single WindowsApplicationDriverUrl that both sessions connect to:

AlarmClockSession = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities);
...
DesktopSession = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), desktopCapabilities);
                   
However the second session cannot connect to the Appium server, and is therefore null, throwing an error message. We are curious how you got this to work?

Result Message:	
Class Initialization method AlarmClockTest.Scenario.Setup threw exception. System.InvalidOperationException: System.InvalidOperationException: A new session could not be created. Details: Problem getting session data for driver type WindowsDriver; does it implement 'get driverData'? (33).

Also from the example I had to add /wd/hub to the end of the WindowsApplicationDriverUrl to get the connection to work initially. I'm not sure if that's relevant?

Thanks,

Phil

**Comment by yodurr** [comment]
Hi @plosty 
To use Appium and multiple sessions you need the 1.6.4 beta of Appium.  Here's the install command:
npm install appium@1.6.4-beta

This will allow you to create multiple sessions with only one app server.  Correct you do need to add /wd/hub to the URL when pointing your test at Appium.

Please let me know if this unblocks you.  Thanks.

**Comment by plosty** [comment]
Hi Yosef,

That makes sense, we will move to the beta driver tomorrow and let you know how it goes.

Thanks,

Phil

Phil Losty QA Manager



   London

   phil@piriform.com
                     •
   +44 7949 034 592







________________________________

**Comment by plosty** [comment]
@yodurr - we switched to the Appium 1.6.4 Beta and that worked, we were able to open both the application and the desktop in the same session.

Many thanks,

Phil

**Comment by yodurr** [comment]
Great to hear!
