### ISSUE TITLE
The desktop application has an authentication step which opens up new browser and has a pop up attached to it which has a checkbox. 

### ISSUE THREAD

**Issue by sahaiswat** [microsoft/WinAppDriver#1488]
The desktop application has an authentication step which opens up new chrome browser and has a pop up attached to it which has a checkbox. 
![image](https://user-images.githubusercontent.com/61317806/113059240-b3934200-920b-11eb-9882-6022e7360054.png)

I need to select the checkbox and click on the button to move ahead. How can this be achieved?

**Comment by sahaiswat** [comment]
can you please elaborate? 
The elements are not inspect able as the right click is disabled

**Comment by liljohnak** [comment]
Something like this.  https://intellitect.com/selenium-chrome-csharp/
We add a static ChromeDriverService in ou assemblyInitalization clean up the chrome driver instances.  Also, remembering to do chromedriver.Quit() in test cleanup prevents weird errors in downstream tests.

**Comment by shoaibmansoor** [comment]
Hi @sahaiswat I can think of three ways to handle this case but all involve using [desktop session](https://github.com/microsoft/WinAppDriver/blob/master/Docs/FAQ.md#when-and-how-to-attach-to-an-existing-app-window)

1. Attach opened browser using desktop session and then find root element by '//*' and calculator 'OK' button offsets by using paint application. Use [move_to_element_with_offset](https://selenium-python.readthedocs.io/api.html#selenium.webdriver.common.action_chains.ActionChains.move_to_element_with_offset) method to click on detected element with coordinates.
2. Create a desktop session and perform the steps in #1 without attaching it to the application. (It will be slow)
3. Create a desktop session and find element using an image. You might have to create your own implementation as winappdriver natively doesn't support this feature.

**Comment by sahaiswat** [comment]
Thanks will try this.
