### ISSUE TITLE
How can I handle WinAppDriver element exceptions ?

### ISSUE THREAD

**Issue by zahraazezo** [microsoft/WinAppDriver#1489]
I want to handle the exceptions that thrown when the elements can't be found by any locator (id , class , Name, ......)

How can I do that in C# ?

**Comment by anunay1** [comment]
Try and catch block, You should have googled it before raining an issue here.

**Comment by zahraazezo** [comment]
@anunay1 

Yes , I know it is very easy , but what should I write in the catch block ? Can you give me an example 

can I do something like that ?

WindowsElement element = session.FindElementByClassName(AlarmTabClassName);
 Assert.IsNotNull(element);

and if I have question regarding WinAppDriver where should I ask ???!

**Comment by Shakevg** [comment]
@zahraazezo Could you explain your scenario in more detail with an example (what does it mean 'handle')?

You can create WindowsDriverExtension with custom implementation for each method.

Example, for FindElementByClassName:
```csharp
public static class WindowsDriverExtension
{      
	public static WindowsElement? FindElementByClassNameCustom(this WindowsDriver<WindowsElement> session, string className)
	{
		try
		{
			return session.FindElementByClassName(className);
		}
		catch (Exception e)
		{
			// Handle Exception here
		}
		return null;
	}
}
```

**Comment by zahraazezo** [comment]
@Shakevg  I think that is what I want , really appreciated
