### ISSUE TITLE
Is there ability to test with switching to tablet mode on Windows 10 and back to normal mode ?

### ISSUE THREAD

**Issue by tlytvyn** [Microsoft/WinAppDriver#149]
We need to test our desktop app in normal mode and in tablet mode. Is that possible using current driver ?

**Comment by yodurr** [comment]
There's currently no API to switch to tablet mode but you should be able to find the UI elements to switch between modes.  

To do this you would need to create a desktop session with WinAppDriver and find the UI elements you want to click to change mode.  Looks like this would work: find the Action Center button on the taskbar and click it.  Now find the "mode" button and click it.

**Comment by timotiusmargo** [comment]
Below is a snippet on how to use **Root** session to toggle the tablet mode as suggested by Yosef.

```c#
DesiredCapabilities appCapabilities = new DesiredCapabilities();
appCapabilities.SetCapability("app", "Root");
desktopSession= new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), appCapabilities);

// Launch action center using Window Keys + A
desktopSession.Keyboard.PressKey(Keys.Command + "a" + Keys.Command);
Thread.Sleep(TimeSpan.FromSeconds(2));
WindowsElement actionCenterElement = null;
            
actionCenterElement = desktopSession.FindElementByName("Action center");
Assert.IsNotNull(actionCenterElement);

// Toggle Tablet Mode
actionCenterElement.FindElementByName("Tablet mode").Click();
```
