### ISSUE TITLE
WinAppDriver not working after Windows Update on Windows Server 2019

### ISSUE THREAD

**Issue by benzionyunger** [microsoft/WinAppDriver#1492]
I was running the driver without any issues for a few months, after performing a Windows Update today and restarting the machine, Windows will not let me start the driver, and displays a notification "This app can't run on your PC. To find a version for your PC, check with the software publisher."

**Comment by benzionyunger** [comment]
uninstalling WAD and reinstalling resolved the issue

**Comment by TimorMuzi** [comment]
Hi, I use the same version of the system(Window Server 2019),But I can't run WinAppDriver
error message：Developer mode is not enabled. Enable it through Settings and restart Windows Application Driver

Do you have any suggestions that can help me? thank you.

**Comment by TimorMuzi** [comment]
@benzionyunger 
Hi, I use the same version of the system(Window Server 2019),But I can't run WinAppDriver
error message：Developer mode is not enabled. Enable it through Settings and restart Windows Application Driver

Do you have any suggestions that can help me? thank you.

**Comment by benzionyunger** [comment]
Do exactly like the error message said. Developer mode is a settings
requirement for WinAppDriver regardless of the system.
