### ISSUE TITLE
WinAppDriver fails to create first new session for new application. 

### ISSUE THREAD

**Issue by denys-rwd** [Microsoft/WinAppDriver#15]
Hi,

I run WinAppDriver on Surface with Windows 10 as **Administrator.
The below selenium script fails on creating RemoteWebDriver  with error message:

_org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (WARNING: The server did not provide any stacktrace information)_

**Selenium Java Script**

        RemoteWebDriver rwd = null;
        try {
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability("app", "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App");
            rwd = new RemoteWebDriver(new URL("http://YYY.30.201.ZZZ:80"), capabilities);
            rwd.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
            rwd.findElementByName("Clear").click();
            rwd.findElementByName("Seven").click();
            WebElement result = rwd.findElementByName("Display is  7 ");
        }catch(Exception e){
            e.printStackTrace();
        } finally {
            if(rwd != null){
                rwd.quit();
            }
       }

**On server side**, WinAppDriver launches Calculator application successfully.

There is a message on console _'{"status":33,"value":{"message":"A new session could not be created."}}'_

If I close the Calculator application and run the Selenium script again, then the scenario will fail again.
If I don't close the Calculator application and run the Selenium script again, then the scenario will success and WinAppDriver will close the Calculator by itself and all next runs will success too.
If I run a new scenario for different application ("Microsoft.WindowsAlarms_8wekyb3d8bbwe!App"), the above scenario will be repeated.

How to get the selenium script runs successfully on the first time?
:)

Thanks in advance,
Denys

**Comment by yodurr** [comment]
It's working fine for me.  
We will get a new release out shortly as it's possible you're hitting a bug that's been fixed but not released yet.

Here's my pom.xml.  I'm running IntelliJ IDEA 2016.1.1.
    <dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>2.53.0</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.11</version>
        </dependency>
    </dependencies>

**Comment by denys-rwd** [comment]
Classic answer. :)
Looking forward for new release. 
What does status '33' mean?

**Comment by yodurr** [comment]
just published a new release, please let us know if this is working for you now.  Also will be adding a Java sample today

**Comment by yodurr** [comment]
Closing this.  Please let us know if you run into this issue again.  thanks.

**Comment by gdsushma** [comment]
I am getting this exception when try to launch the calculator ,notepad i am using latest relese of winappdriver.
package WinCalTrial;
import java.net.MalformedURLException;
import java.net.URL;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import io.appium.java_client.windows.WindowsDriver;

public class Caculater {
	 private static WindowsDriver CalculatorSession = null;
	 private static WebElement CalculatorResult = null;
	 
	 public static void main() throws MalformedURLException {
		
	
	 DesiredCapabilities capabilities = new DesiredCapabilities();
	 capabilities.setCapability("app","C:\\Windows\\System32\\notepad.exe");
	 CalculatorSession = new WindowsDriver(new URL("http://127.0.0.1:4723"),capabilities);

}
}
Starting ChromeDriver 2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1) on port 6850
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.29 seconds
Build info: version: '3.141.0', revision: '2ecb7d9a', time: '2018-10-31T20:22:52'
System info: host: 'DESKTOP-DU27VG5', ip: '192.168.79.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
Driver info: driver.version: ChromeDriver......
