### ISSUE TITLE
Cannot get new windowhandle

### ISSUE THREAD

**Issue by konman750** [microsoft/WinAppDriver#1505]
When listening on a session, close the current window and redirect to another window in the same.exe. The same session's windoWhandle is null，but inspect.exe can get this new window,and the new window as the same of the old window.

**Comment by Shakevg** [comment]
@konman750 Could you provide a code example.

**Comment by anunay1** [comment]
Better create a root session and then switch to that opened window as a work around

**Comment by konman750** [comment]
@Shakevg  I  got a great ways from this[1464](https://github.com/microsoft/WinAppDriver/issues/1464)，thanks!

**Comment by konman750** [comment]
@anunay1 I found the best anwser in this link [1464](https://github.com/microsoft/WinAppDriver/issues/1464), I got the process catch my window's name and  put handle in  appTopLevelWindow for a root session's Capability.**thanks**
