### ISSUE TITLE
System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'

### ISSUE THREAD

**Issue by dahanj95** [microsoft/WinAppDriver#1508]
I'm getting this exception when I try to create an instance of WindowsDriver<WindowsElement>.

Code:

    `DesiredCapabilities capabilities = new DesiredCapabilities();
    capabilities.SetCapability("app", filePath);

    var session = new WindowsDriver<WindowsElement>(new Uri(gameUrl), capabilities); <-- this line
    session.LaunchApp();`

I have installed the driver and it's running, i tried with lower versions of nuget (3.0.0.2) and even latest one (4.3.1). I'm still not able to create a basic automation with my code.

**Comment by anunay1** [comment]
exception might be happening in this line 
session.LaunchApp();` as its not support it will launch the app the moment session is created.

**Comment by Tree55Topz** [comment]
what is session.LaunchApp() trying to accomplish? when you instantiate the session it should attempt to launch the app as well. I do not think you need this step. Additionally, that is not an exception. Can you post the actual error you are getting? 

Also, you do have Developer Mode turned on right?

**Comment by dahanj95** [comment]
Closing, no longer relevant. This issue could be deleted too.
