### ISSUE TITLE
UT test not able to connect to server

### ISSUE THREAD

**Issue by bharatsangale1** [microsoft/WinAppDriver#1511]
the tool is not able to connect to server when winappdriver tests launched from batch file but works fine when tests fired from visual studio (Right click on test -> Run).

Batch script:
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\MSTest.exe" /testContainer:TEST_DLL_PATH

Am I missing something here?

**Comment by Tree55Topz** [comment]
This doesnt sound like a WinAppDriver issue. Looks like you are using MSTest?

1. Make sure your batch script is correct syntax wise. For debugging you can use cmd /k to keep your cmd window open after it fails. This should give you the actual error which would help in assisting you.
2. How are your tests starting up and tearing down? Including that code would also help because maybe you are not cleaning up your sessions properly in between test runs.

**Comment by bharatsangale1** [comment]
1. Batch file seems OK. Purpose of batch file is to start UI tests and UI tests are starting properly.
2. We have created the session in  [ClassInitialize] by calling one static method and method code is like this
                 opt = new AppiumOptions();             
                opt.AddAdditionalCapability("app", ToolAppId);
                opt.AddAdditionalCapability("deviceName", "WindowsPC");
                opt.AddAdditionalCapability("ms:waitForAppLaunch", 15);
               session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), opt);
   Once session is created we are using same session in number of  [TestMethod] methods
    For tearing down we calling [ClassCleanup] inside that we just closes our tool.

Do I need to clear the session for each and every test?

**Comment by liljohnak** [comment]
@bharatsangale1 we make a session each test, but you do not need to restart the app each time.  We have a method to attach to the existing application if it is open.

**Comment by bharatsangale1** [comment]
We are using static variable for session like protected static WindowsDriver<WindowsElement> session and only creating new session if it is null otherwise using same session

**Comment by bharatsangale1** [comment]
It seems issue is not related to WinAppDriver. Thanks for the support :)
