### ISSUE TITLE
Best way to run Winappdriver test cases?

### ISSUE THREAD

**Issue by bharatsangale1** [microsoft/WinAppDriver#1512]
Hi I have created the task in task scheduler to launch the batch file which is written to run the test cases.
When the Test Cases runs it gives exception "unknown error occurred in the remote end while processing the command"
When we manually run the task (Right Click -> Run) it is not giving that exception.

**Comment by anunay1** [comment]
I get this error when the system is locked, please check while running UI tests the system should not get locked.

**Comment by bharatsangale1** [comment]
You mean to say WinAppDriver has dependency on system lock? Means should always in ON state?

**Comment by anunay1** [comment]
Yes the system should always be in unlock mode.

**Comment by bharatsangale1** [comment]
Is there any way to bypass that one?

**Comment by anunay1** [comment]
That's the ground rule for any UI automation even web applications using selenium needs the PC to be unlocked unless you are running in a headless mode.
