### ISSUE TITLE
Silent installation of WinAppDriver 

### ISSUE THREAD

**Issue by rieslma** [microsoft/WinAppDriver#1514]
I'm creating Azure Pipelines and want to install the WinAppDriver silent over a CMD script. is this possible. Cant find any hints in the readme. Or is there some other way to install the WAD automatically.

**Comment by anunay1** [comment]
You have a start and stop task in Azure, you can use the same,

**Comment by rieslma** [comment]
i know the task, when i read the requirements
```
    Pipeline must be using an Agent running Windows 10 with WinAppDriver pre-installed ...
```
and this pre-installed is my problem. the pipeline must install it. every machine in my pool is completely empty when i start my test.  
with a silent installation from cmd the pipeline can do it for me. but there is no option atm.

**Comment by Shakevg** [comment]
@rieslma This is works for me for running locally, but I didn't check from Azure task:
`msiexec /i WindowsApplicationDriver1.2.1.msi /quiet /qn /norestart /log WindowsApplicationDriver_install.log`

Also WinAppDriver require node JS. I used next command for silent setup:
`msiexec /i node-v14.16.1-x64.msi /quiet /qn /norestart /log node-v14.16.1-x64_install.log`

**Comment by rieslma** [comment]
Tested on azure pipeline with cmd task working without any problems. Thanks to @Shakevg
