### ISSUE TITLE
element interaction is too much slow

### ISSUE THREAD

**Issue by nabilalakhani** [microsoft/WinAppDriver#1521]
hey
i am a newbie trying to automate a windows app which starts from a RDP file
earlier i was facing issue that code was not able to interact with the app and i tried some tweaks now its interacting means clicking and sending keys is happening but its taking too long time like 20-30 seconds to click and sendkeys even thought i dont put waits why it takes so much time perform a action
please find code below
i have mentioned the click and send keys action in def test_connect(self): method

`
import subprocess
import unittest
from time import sleep

from appium import webdriver
from appium.webdriver.extensions import session

class SimpleCalculatorTests(unittest.TestCase):

@classmethod
def setUpClass(self):
    # set up appium
    global driver

    subprocess.Popen(['powershell.exe',r"C:\jtracker\myrdp.rdp"])
    desired_caps = {}
    desired_caps["platformName"] = "Windows"
    desired_caps["app"] = "Root"
    self.driver = webdriver.Remote(
        command_executor='http://127.0.0.1:4723',
        desired_capabilities=desired_caps)

@classmethod
def tearDownClass(self):
    self.driver.quit()

def getresults(self):
   
    displaytext = displaytext.lstrip(' ')
    return displaytext

def test_connect(self):
   

    self.driver.find_element_by_xpath("//Button[@ClassName=\"Button\"][@Name=\"Connect\"]").click()
    self.driver.find_element_by_xpath("//Edit[@Name=\"Password\"][starts-with(@AutomationId,\"PasswordField_\")]").send_keys("pass")
    self.driver.find_element_by_xpath("//Button[@Name=\"OK\"][@AutomationId=\"OkButton\"]").click()
if name == 'main':
suite = unittest.TestLoader().loadTestsFromTestCase(SimpleCalculatorTests)
unittest.TextTestRunner(verbosity=2).run(suite)

`

**Comment by anunay1** [comment]
There is a known issue with slowness in xpath, better use some other method to locate elements.

**Comment by nabilalakhani** [comment]
> There is a known issue with slowness in xpath, better use some other method to locate elements.

thanks resolved
