### ISSUE TITLE
Does the WinAppDriver not have a control click?

### ISSUE THREAD

**Issue by GreyHa** [microsoft/WinAppDriver#1527]
I want to send a click event without moving the mouse.

Is there a way?

Current Behavior
- element.click()
> CLICK_ELEMENT = "clickElement" > mouse move > click

**Comment by anunay1** [comment]
What's the use case?

**Comment by GreyHa** [comment]
I am automating several programs with one desktop, and the mouse movement is a problem.

**Comment by anunay1** [comment]
Can you also share some code?

**Comment by GreyHa** [comment]
element = driver.find_element(By.XPATH, {xpath})
element.click()

**Comment by GreyHa** [comment]
from selenium.webdriver.common.keys import Keys
element = driver.find_element(By.XPATH, {xpath})
element.send_keys(Keys.ENTER)

not mouse move event!
