### ISSUE TITLE
WinAppDriver cannot locate elements on Modal window's Modal window

### ISSUE THREAD

**Issue by ivercan** [microsoft/WinAppDriver#1528]
I'm trying to automate a Windows Printer Driver Application on windows 10 pro with newest WinAppDriver v1.2.1.[WinAppDriver](https://github.com/Microsoft/WinAppDriver/releases).
The test script cannot locate any element on the Preferences Window, which is a Modal window's Modal Window.
The test scenario is as below:
1. The test script starts notepad.exe, locate and click Print menu item, the Print Modal window shows.
2. Then locate and click the Preferences button on the Print Modal window, the Preferences Modal window shows.
3. Then try to click elements on the Preferences Modal Window, it fails.

Here is my sample code, using Appium-Python-Client library:
```
from appium import webdriver

desired_caps = {}
desired_caps["app"] = "C:\\Windows\\notepad.exe"
desired_caps["platformName"] = "windows"

driver = webdriver.Remote(
    command_executor='http://127.0.0.1:4723',
    desired_capabilities= desired_caps)

driver.find_element_by_name("ファイル(F)").click()
driver.find_element_by_accessibility_id("6").click()

# click elements on the Print modal window
driver.find_element_by_accessibility_id("1010").click()

# click elements on the Preferences modal window
driver.find_element_by_xpath("/Pane[@ClassName=\"#32769\"][@Name=\"デスクトップ 1\"]/Window[@ClassName=\"#32770\"][@Name=\"印刷設定\"]/Tab[@ClassName=\"SysTabControl32\"]/TabItem[@Name=\" 拡張機能 \"]").click() 
driver.find_element_by_xpath("/Pane[@ClassName=\"#32769\"][@Name=\"デスクトップ 1\"]/Window[@ClassName=\"#32770\"][@Name=\"印刷設定\"]/Button[@ClassName=\"Button\"][@Name=\"設定(E)...\"]").click()
driver.find_element_by_xpath("/Pane[@ClassName=\"#32769\"][@Name=\"デスクトップ 1\"]/Window[@ClassName=\"#32770\"][@Name=\"印刷設定\"]/Window[@ClassName=\"#32770\"][@Name=\"セキュリティ印刷設定\"]/CheckBox[@ClassName=\"Button\"][@Name=\"セキュリティ印刷(S)\"]").click()

```

The WinAppDriver's log:
```
{"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}
```
- I also have tried relative xpath expressions, and by name or by accessibility id. Did not succeed.
- I also have tried the [WADLibrary client library](https://github.com/Adwisit/WADLibrary). It had same phenomenon.
- I also have tried some other versions of WinAppDriver, all failed except the old version of **WinAppDriver v1.1.4**

Is there any other way to locate elements on the descendant Modal window (i.e the Preferences Modal window)?

**Comment by Shakevg** [comment]
@ivercan I suppose that "Preferences Modal Window" is a new window, try to switch https://github.com/microsoft/WinAppDriver/blob/master/Docs/FAQ.md
```
var allWindowHandles = session.WindowHandles;
// Assuming you only have only one window entry in allWindowHandles and it is in fact the correct one,
// switch the session to that window as follows. You can repeat this logic with any top window with the same
// process id (any entry of allWindowHandles)
session.SwitchTo().Window(allWindowHandles[0]);
```

**Comment by ivercan** [comment]
@Shakevg your reply is very helpful! 
I tried treating it as a new window, and using relative xpath. it works.
thanks!
