### ISSUE TITLE
Windows Application Testing: The Webview elements are not recognising.

### ISSUE THREAD

**Issue by dayanacgeorge** [Microsoft/WinAppDriver#153]
Hi,

I am successfully opened a Sample Windows App using Appium+Selenium Webdriver. But the Webview / Html Elements are not recognising by the Appium. I am getting an Exception. Please find the details below.
Appium 1.6.3
Selenium WebDriver
Java
Java Client: 5.0.0-BETA3
App : MS Visual Studio, C#

**Used UI code :** 
driver.findElement(By.xpath("/html/body/center[1]/table/tbody/tr/td[2]/code/a[2]")).click();
driver.findElement(By.className("#32769"));
List<WebElement>we=driver.findElementsByXPath("/html/body/center[1]/table/tbody/tr/td[1]/h1");
driver.findElement(By.tagName("button"));
driver.findElementById("2A.10010");
**Used UI Inspect Tools:** 
 * Inspect.exe
* Chrome Inspect
**App Screen shot:** Please find the attached Screenshot.
![sampleapp](https://cloud.githubusercontent.com/assets/22546701/23252851/8efb8b5a-f9b2-11e6-8bc8-41a44deea071.JPG)

**Capabilities Given:**

  DesiredCapabilities capabilities = new DesiredCapabilities();
	 capabilities.setCapability("app", "bccb6174-9004-40e4-b26e-7f1859c4b4e1_r6mxmex0vgwxj!App");
			 capabilities.setCapability("platformName", "Windows");
			capabilities.setCapability("deviceName", "WindowsPC");
				 driver = new WindowsDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
				driver.manage().timeouts().implicitlyWait(250, TimeUnit.SECONDS);
**Exception Details:
The Appium Log result.**

[Appium] Welcome to Appium v1.6.3
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"capabilities":{"desiredCapabilities":{"app":"bccb6174-9004-40e4-b26e-7f1859c4b4e1_r6mxmex0vgwxj!App","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{}},"desiredCapabilities":{"app":"bccb6174-9004-40e4-b26e-7f1859c4b4e1_r6mxmex0vgwxj!App","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"bccb6174-9004-40e4-b26e-7f1859c4b4e1_r6mxmex0vgwxj!App","platformName":"Windows","deviceName":"WindowsPC"},{},{"desiredCapabilities":{"app":"bccb6174-9004-40e4-b26e-7f1859c4b4e1_r6mxmex0vgwxj!App","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{}},null,null]
[Appium] Creating new WindowsDriver session
[Appium] Capabilities:
[Appium]   app: 'bccb6174-9004-40e4-b26e-7f1859c4b4e1_r6mxmex0vgwxj!App'
[Appium]   platformName: 'Windows'
[Appium]   deviceName: 'WindowsPC'
[BaseDriver] The following capabilities were provided, but are not recognized by appium: app.
[BaseDriver] Session created with session id: 5df6891f-cfbd-45b7-bb44-319ececa6fd0
[WinAppDriver] Verifying WinAppDriver is installed with correct checksum
[debug] [WinAppDriver] WinAppDriver changed state to 'starting'
[WinAppDriver] Killing any old WinAppDrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"4823 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I winappdriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
[WinAppDriver] No old WinAppDrivers seemed to exist
[WinAppDriver] Spawning winappdriver with: undefined 4823/wd/hub
[WinAppDriver] [STDOUT] Windows Application Driver Beta listening for requests at: http://127.0.0.1:4823/wd/hub
[debug] [WinAppDriver] WinAppDriver changed state to 'online'
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:4823/wd/hub/session] with body: {"desiredCapabilities":{"app":"bccb6174-9004-40e4-b26e-7f1859c4b4e1_r6mxmex0vgwxj!App","platformName":"Windows","deviceName":"WindowsPC"}}
[WinAppDriver] [STDOUT] Press ENTER to exit.
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 138
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4823
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] {"desiredCapabilities":{"app":"bccb6174-9004-40e4-b26e-7f1859c4b4e1_r6mxmex0vgwxj!App","platformName":"Windows","deviceName":"WindowsPC"}}
[WinAppDriver] [STDOUT] SessionManager - Creating session
[WinAppDriver] [STDOUT] SessionManager - WinAppDriver succeeded loading MitaBroker
[WinAppDriver] [STDOUT] SessionManager - Application launched
[WinAppDriver] [STDOUT] SessionManager - Session successfully created: D7D03725-237F-4BD9-AFBE-38BED18ABCAE
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 161
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] {"sessionId":"D7D03725-237F-4BD9-AFBE-38BED18ABCAE","status":0,"value":{"app":"bccb6174-9004-40e4-b26e-7f1859c4b4e1_r6mxmex0vgwxj!App","platformName":"Windows"}}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"D7D03725-237F-4BD9-AFBE-38BED18ABCAE","status":0,"value":{"app":"bccb6174-9004-40e4-b26e-7f1859c4b4e1_r6mxmex0vgwxj!App","platformName":"Windows"}}
[Appium] New WindowsDriver session created successfully, session 5df6891f-cfbd-45b7-bb44-319ececa6fd0 added to master session list
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"app":"bccb6174-9004-40e4-b26e-7f1859c4b4e1_r6mxmex0vgwxj!App","platformName":"Windows","deviceName":"WindowsPC"}
[HTTP] <-- POST /wd/hub/session 200 3237 ms - 186
[HTTP] --> GET /wd/hub/session/5df6891f-cfbd-45b7-bb44-319ececa6fd0 {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/5df6891f-cfbd-45b7-bb44-319ececa6fd0] to [GET http://127.0.0.1:4823/wd/hub/session/D7D03725-237F-4BD9-AFBE-38BED18ABCAE] with body: {}
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] GET /wd/hub/session/D7D03725-237F-4BD9-AFBE-38BED18ABCAE HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4823
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 161
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] {"sessionId":"D7D03725-237F-4BD9-AFBE-38BED18ABCAE","status":0,"value":{"app":"bccb6174-9004-40e4-b26e-7f1859c4b4e1_r6mxmex0vgwxj!App","platformName":"Windows"}}
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"D7D03725-237F-4BD9-AFBE-38BED18ABCAE\",\"status\":0,\"value\":{\"app\":\"bccb6174-9004-40e4-b26e-7f1859c4b4e1_r6mxmex0vgwxj!App\",\"platformName\":\"Windows\"}}"
[JSONWP Proxy] Replacing sessionId D7D03725-237F-4BD9-AFBE-38BED18ABCAE with 5df6891f-cfbd-45b7-bb44-319ececa6fd0
[HTTP] <-- GET /wd/hub/session/5df6891f-cfbd-45b7-bb44-319ececa6fd0 200 63 ms - 161
[HTTP] --> GET /wd/hub/session/5df6891f-cfbd-45b7-bb44-319ececa6fd0 {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/5df6891f-cfbd-45b7-bb44-319ececa6fd0] to [GET http://127.0.0.1:4823/wd/hub/session/D7D03725-237F-4BD9-AFBE-38BED18ABCAE] with body: {}
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] GET /wd/hub/session/D7D03725-237F-4BD9-AFBE-38BED18ABCAE HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4823
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 161
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] {"sessionId":"D7D03725-237F-4BD9-AFBE-38BED18ABCAE","status":0,"value":{"app":"bccb6174-9004-40e4-b26e-7f1859c4b4e1_r6mxmex0vgwxj!App","platformName":"Windows"}}
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"D7D03725-237F-4BD9-AFBE-38BED18ABCAE\",\"status\":0,\"value\":{\"app\":\"bccb6174-9004-40e4-b26e-7f1859c4b4e1_r6mxmex0vgwxj!App\",\"platformName\":\"Windows\"}}"
[JSONWP Proxy] Replacing sessionId D7D03725-237F-4BD9-AFBE-38BED18ABCAE with 5df6891f-cfbd-45b7-bb44-319ececa6fd0
[HTTP] <-- GET /wd/hub/session/5df6891f-cfbd-45b7-bb44-319ececa6fd0 200 33 ms - 161
[HTTP] --> POST /wd/hub/session/5df6891f-cfbd-45b7-bb44-319ececa6fd0/timeouts {"type":"implicit","ms":250000}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/5df6891f-cfbd-45b7-bb44-319ececa6fd0/timeouts] to [POST http://127.0.0.1:4823/wd/hub/session/D7D03725-237F-4BD9-AFBE-38BED18ABCAE/timeouts] with body: {"type":"implicit","ms":250000}
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session/D7D03725-237F-4BD9-AFBE-38BED18ABCAE/timeouts HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 31
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4823
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 63
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] {"sessionId":"D7D03725-237F-4BD9-AFBE-38BED18ABCAE","status":0}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"D7D03725-237F-4BD9-AFBE-38BED18ABCAE","status":0}
[JSONWP Proxy] Replacing sessionId D7D03725-237F-4BD9-AFBE-38BED18ABCAE with 5df6891f-cfbd-45b7-bb44-319ececa6fd0
[HTTP] <-- POST /wd/hub/session/5df6891f-cfbd-45b7-bb44-319ececa6fd0/timeouts 200 30 ms - 63
[BaseDriver] Shutting down because we waited 60 seconds for a command
[debug] [WinAppDriver] Deleting WinAppDriver session
[debug] [WinAppDriver] Deleting WinAppDriver server session
[debug] [JSONWP Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:4823/wd/hub/session/D7D03725-237F-4BD9-AFBE-38BED18ABCAE] with no body
[Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session 5df6891f-cfbd-45b7-bb44-319ececa6fd0 from our master session list
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] DELETE /wd/hub/session/D7D03725-237F-4BD9-AFBE-38BED18ABCAE HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 0
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4823
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 63
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] {"sessionId":"D7D03725-237F-4BD9-AFBE-38BED18ABCAE","status":0}
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"D7D03725-237F-4BD9-AFBE-38BED18ABCAE\",\"status\":0}"
[WinAppDriver] Did not get confirmation WinAppDriver deleteSession worked; Error was: Error: Did not get a valid response object. Object was: {"sessionId":"D7D03725-237F-4BD9-AFBE-38BED18ABCAE","status":0}
[debug] [WinAppDriver] WinAppDriver changed state to 'stopping'
[debug] [WinAppDriver] WinAppDriver changed state to 'stopped'

**Comment by yodurr** [comment]
Hi @dayanacgeorge  we currently don't support DOM inspection from WinAppDriver.  For web browser testing of this sort you should look at the Edge WebDriver: 
https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/

We hope to someday support DOM inspection from WinAppDriver by integrating Edge's webdriver, but such a feature is not available today.
