### ISSUE TITLE
How does win app driver work with CEF

### ISSUE THREAD

**Issue by samkhayal** [microsoft/WinAppDriver#1533]
any suggestion on how to debug a wpf application using cef ? when running test using win app driver

**Comment by anunay1** [comment]
You need to use selenium or any other tool, using chrome debug options you can switch to an existing open browser

**Comment by samkhayal** [comment]
> You need to use selenium or any other tool, using chrome debug options you can switch to an existing open browser

can you share an example or code sample for that ?

**Comment by anunay1** [comment]
No
