### ISSUE TITLE
Cannot get ("app", "Root") session on 2019 server VM

### ISSUE THREAD

**Issue by bonislav** [microsoft/WinAppDriver#1536]
Hello,
we are trying to run automated tests using Appium Driver for a desktop application on a remote machine that is on Windows 2019.
We are using [this](https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/README.md#attaching-to-an-existing-app-window) solution to start the application, and it works on the VM I am writing tests,
But when run on the 2019 server machine the "DesktopSession" is returning null.
We have developer mode enabled on the machine and also we are using AppiumServceBuilder to automatically start the winApp driver.

Sample of the code which is returning a null on the Win 2019 Server:

```
            var appiumServiceBuilder = new AppiumServiceBuilder().UsingPort(4723).Build();
            appiumServiceBuilder.Start();
            var appiumOptions = new AppiumOptions();
            appiumOptions.AddAdditionalCapability("app", "Root");
            var desktopSession = new WindowsDriver<WindowsElement>(appiumServiceBuilder, appiumOptions);
            Assert.NotNull(desktopSession);
```

This is working properly on the Win 10 VM.

I was wondering if it is possible that the 2019 server machine is missing some rights and that is why it does not have access to "find" the desktopSession.

Any advice would be greatly appreciated!

Regards

**Comment by anunay1** [comment]
As per the FAQ its supported on Windows server 2016. Will it be possible for you to check on Windows Server 2016.

**Comment by bonislav** [comment]
Hello, currently cannot test on a 2016 server, I saw in the documentation 2019 should be supported and is the recommended one compared to 2016. We've already requested a Win 10 VM as we tested with a Win 10 agent and it worked properly.
Some more details:

The WinAppDriver is starting the application on the 2019 Server VM, but cannot find any Window Sessions.

Regards

**Comment by benzionyunger** [comment]
I have been running tests on both Windows Server 2019 and Microsoft host agent 2019 without any issues, if you post your WinAppDriver logs maybe I can help. Here is my code (Java) to connect:

try {
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability("app", "Root");
            capabilities.setCapability("platformName", "Windows");
            capabilities.setCapability("deviceName","WindowsPC");
           capabilities.setCapability("ms:experimental-webdriver", false);
            driver = new WindowsDriver<WindowsElement>(new URL("http://127.0.0.1:4723"), capabilities);
            sleep(3);
            WebElement session = driver.findElementByName("My app name");
            String hex = session.getAttribute("NativeWindowHandle");
            int handle = Integer.parseInt(hex);
            String windowHandle = Integer.toHexString(handle);
            windowHandle = "0x"+windowHandle;
            DesiredCapabilities caps = new DesiredCapabilities();
            caps.setCapability("appTopLevelWindow", windowHandle);
            caps.setCapability("platformName", "Windows");
            caps.setCapability("deviceName","WindowsPC");
            capabilities.setCapability("ms:experimental-webdriver", false);
            driver = new WindowsDriver<WindowsElement>(new URL("http://127.0.0.1:4723"), caps);
        } catch (MalformedURLException | InterruptedException e) {
            e.printStackTrace();
        }

**Comment by laomaolaile** [comment]
> I have been running tests on both Windows Server 2019 and Microsoft host agent 2019 without any issues, if you post your WinAppDriver logs maybe I can help. Here is my code (Java) to connect:
> 
> try { DesiredCapabilities capabilities = new DesiredCapabilities(); capabilities.setCapability("app", "Root"); capabilities.setCapability("platformName", "Windows"); capabilities.setCapability("deviceName","WindowsPC"); capabilities.setCapability("ms:experimental-webdriver", false); driver = new WindowsDriver(new URL("http://127.0.0.1:4723"), capabilities); sleep(3); WebElement session = driver.findElementByName("My app name"); String hex = session.getAttribute("NativeWindowHandle"); int handle = Integer.parseInt(hex); String windowHandle = Integer.toHexString(handle); windowHandle = "0x"+windowHandle; DesiredCapabilities caps = new DesiredCapabilities(); caps.setCapability("appTopLevelWindow", windowHandle); caps.setCapability("platformName", "Windows"); caps.setCapability("deviceName","WindowsPC"); capabilities.setCapability("ms:experimental-webdriver", false); driver = new WindowsDriver(new URL("http://127.0.0.1:4723"), caps); } catch (MalformedURLException | InterruptedException e) { e.printStackTrace(); }

I have the same problem. Can you help me to see it，the testcode run on  my pc is ok,but run on VM,desktopSession is null.

![image](https://user-images.githubusercontent.com/19726057/216238349-97e2fbed-02ce-443e-9233-b40d2557d471.png)
![image](https://user-images.githubusercontent.com/19726057/216238623-802b8524-fe55-4f8d-9b7e-781301acff9f.png)
