### ISSUE TITLE
Code is working while opening the WinAppDriver manually but on opening programmatically same code is not working.

### ISSUE THREAD

**Issue by sandeep91anand** [microsoft/WinAppDriver#1549]
I have tried opening the WinAppDriver by help of .bat file and also process.start() also faced same issue 

Process process = Runtime.getRuntime().exec(
		        "cmd /c start.bat", null, new File("C:\\Users\\xnxnx\\Desktop"));

ProcessBuilder p = new ProcessBuilder();
p.command("C:\Users\Administrator\WinAppDriver\WinAppDriverTool\WinAppDriver.exe");
Process process = p.start();

Need Help to resolve above issue

**Comment by anunay1** [comment]
What's happening, does the console opens or closes.. or the application does not start at all.

**Comment by anunay1** [comment]
the path does not appear correct ""C:\Users\Administrator\WinAppDriver\WinAppDriverTool\WinAppDriver.exe", it should be in program 86 folder.

**Comment by sandeep91anand** [comment]
What's happening, does the console opens or closes.. or WInAppDriver.exe does not start at all. ----> It starts but application doesn't start

**Comment by sandeep91anand** [comment]
I upgraded my application with new version seems to working now.
Thanks for replying. :) .
