### ISSUE TITLE
Win UI 3 Support

### ISSUE THREAD

**Issue by LadderLogic** [microsoft/WinAppDriver#1562]
*feature request*
Is there a planned Win UI 3 / Project Reunion support? Would that be different from the current UWP support?

**Comment by DHowett** [comment]
WinAppDriver 1.2.1 shipped with support for WinUI 3 and the Windows App SDK. Are you encountering an issue?

**Comment by LadderLogic** [comment]
> WinAppDriver 1.2.1 shipped with support for WinUI 3 and the Windows App SDK. Are you encountering an issue?

No, I haven't encountered any issues yet. The Readme didn't list Win UI 3 as one of the UI "frameworks". I was trying to get some clarification as we evaluate Win UI 3 readiness for our applications. Thank you.

> This service supports testing Universal Windows Platform (UWP), Windows Forms (WinForms), Windows Presentation Foundation (WPF), and Classic Windows (Win32) apps on Windows 10 PCs.
