### ISSUE TITLE
Issue identifying element with same Automation Id

### ISSUE THREAD

**Issue by skotian2** [microsoft/WinAppDriver#1563]
Hello Folks,
I have multiple element with AutomationId as txtBox and having a tough time to find a way to invoke an automation id following to the first one.

1. Following option tried
2. Indexing option tried

WindowsElement E1 = DesktopSession.FindElement(By.XPath("//*[@AutomationId='txtBox']"));
E1 .SendKeys("123456");

Any suggestion would be highly appreciated.

**Comment by anunay1** [comment]
Better use a nested approach i.e. try to find the element with it's parent.

**Comment by anunay1** [comment]
Better use a nested approach i.e. try to find the element with it's parent.

**Comment by anunay1** [comment]
Better use a nested approach i.e. try to find the element with it's parent.

**Comment by liljohnak** [comment]
Yeah, it doesn't work from the session.  If you search from an AppiumWebElement it will work.
`element.FindElementByXPath("*//*[@AutomationId='txtBox']");`

**Comment by skotian2** [comment]
> element.FindElementByXPath("*//*[@AutomationId='txtBox']");

FindElementByXPath("*//*[@AutomationId='txtBox'][2]"); // I have element with same automation id txtbox and need to click the following element.

Thanks for your suggestion. I do not have issue finding with first textbox but when I try to loop through the second element there is an issue.

{"using":"xpath","value":"*//*[@AutomationId='txtBox'][2]"}
HTTP/1.1 404 Not Found
Content-Length: 139
Content-Type: application/json

{"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}

**Comment by skotian2** [comment]
> We had issues with this too. We used linq.
> 
> ```
> var elements = element.FindElementsByXPath("*//*[@AutomationId='txtBox']");
> secondElement = elements.ElementAt(1);
> ```
> 
> `.FindElements` does not wait for existence, so you may need a wait for `elements.Count().Equals(2)`

It worked perfectly !!!

var elements = DesktopSession.FindElementsByXPath("*//*[@AutomationId='txtBox']");
                var secondElement = elements.ElementAt(5);
                Thread.Sleep(60000);
                secondElement.SendKeys("123456");
