### ISSUE TITLE
WinAppDriver behavior different in local Windows machines and Azure cloud Virtual machines

### ISSUE THREAD

**Issue by james-miami** [microsoft/WinAppDriver#1572]
We use a set of virtual machines on Azure cloud to test our windows WPF application. We noticed some buttons can be clicked in all our 10 developers machines but can not be clicked in Azure cloud. Any one experiences the same issue?

**Comment by Shakevg** [comment]
@james-miami I suppose Windows versions are not the same.
Per my experience, WinAppDriver often returns different App controls tree for a different version of the window.
Could you save the page source on Azure Cloud and check that button control really presents (use driver.PageSource) and then check that XPath working using http://xpather.com/?

**Comment by james-miami** [comment]
Thank you for the suggestion. I will log the PageSource to figure out what
the difference is between those two systems.

James

**Comment by james-miami** [comment]
By comparing PageSources from Azure cloud CIT machine and local development machine, they are identical. This is not a WinAppDriver issue, the application itself behaviors different in those two different environment.
