### ISSUE TITLE
How to access context menu after right click on the file in the file explorer with selenium windows application driver

### ISSUE THREAD

**Issue by NikitaTurakhia** [microsoft/WinAppDriver#1581]
Hello,

I am trying to Access the context menu in the file explorer after right click the file but it just let me access Properties via my automation code and somehow if I try to click on another option, it won't work. Below id the picture of what I am trying to do.

![Untitled](https://user-images.githubusercontent.com/21182650/131175113-bd20ee6a-73b2-4305-87f0-1164f298db0d.png)

Here I am trying to click on Rename button but somehow it isn't working. I trued with findelementbyname, findelementbyxpath and with automationid also. But nothing happens.
Please let me know if you have any idea on this.

**Comment by Shakevg** [comment]
@NikitaTurakhia Could you please post a code example that not working

**Comment by anunay1** [comment]
Why not programmatically change rename?

**Comment by anunay1** [comment]
Context menu is a separate window altogether in inspect, you need to create a root session and then click on the rename button, but renaming it programmatically will be a better option.

**Comment by NikitaTurakhia** [comment]
Thank you. I will try to do that.

Thank You,
Nikita Shah
________________________________

**Comment by NikitaTurakhia** [comment]
> Context menu is a separate window altogether in inspect, you need to create a root session and then click on the rename button, but renaming it programmatically will be a better option.

Thank you @anunay1. Can you show me the code how to create a root session in selenium c#?

**Comment by anunay1** [comment]
were you able to solve this @NikitaTurakhia

**Comment by NikitaTurakhia** [comment]
> were you able to solve this @NikitaTurakhia

Yes. I was able to. Thank you for your help.

**Comment by anunay1** [comment]
> > were you able to solve this @NikitaTurakhia
> 
> Yes. I was able to. Thank you for your help.

You can close the bug now.

**Comment by NikitaShah2492** [comment]
@timotiusmargo I am trying to access options from the context menu in the file explorer but it’s not working with automation Id or even with the name. The only thing is working is properties. I am only able to click on properties with findelementbyname. Is there a way I can click on the option with arrow down and arrow up key?

**Comment by anunay1** [comment]
@NikitaTurakhia But you mentioned that you were able to solve the issue.

**Comment by NikitaShah2492** [comment]
@anunay1 yes. So i was just able to access the context menu to do arrow down and up. Then I tried to click on the button inside and it did not work.

**Comment by anunay1** [comment]
Can you share the code

**Comment by NikitaTurakhia** [comment]
session.FindElementByName("Patents").Click();
            IWebElement link = session.FindElementByName("Patents");
            Actions rightClickAction = new Actions(session).ContextClick(link);
            rightClickAction.Build().Perform();
            

            for (int i = 0; i < 12; i++)
            {
                link.SendKeys(Keys.ArrowDown);
                Thread.Sleep(1000);
                
            }

Here I am trying to get the value of the option from the context menu when I right click on the "Patent" folder in the file explorer.

**Comment by anunay1** [comment]
Your code will not work. Try the below: 
`
session.FindElementByName("Patents").Click();
IWebElement link = session.FindElementByName("Patents");
Actions rightClickAction = new Actions(session).ContextClick(link);
rightClickAction.Build().Perform();

        for (int i = 0; i < 12; i++)
        {
            session.SendKeys(Keys.ArrowDown);
            Thread.Sleep(1000);
            
        }
`

**Comment by NikitaTurakhia** [comment]
@anunay1  I think you sent the same that I gave you.

**Comment by anunay1** [comment]
no check the for loop

**Comment by anunay1** [comment]
Can you share the snap shot which value you want to get?

**Comment by anunay1** [comment]
Also share the expanded view of what you get in inspect.

**Comment by NikitaTurakhia** [comment]
![Untitled1](https://user-images.githubusercontent.com/21182650/131671026-69ef1ec1-cafb-4a09-9a36-837d98ea7b42.png)

![Untitled2](https://user-images.githubusercontent.com/21182650/131670952-2b5f84e2-8e93-41fa-adf9-238cc3cf71d7.png)

**Comment by NikitaTurakhia** [comment]
Now here I want to check if that button is exist when the arrowdown comes to that button in the context menu

**Comment by anunay1** [comment]
The button does not have any automation properties implemented, al tough you have an automation ID 31005(check if it does not change every time you do a right click) if it does not change use the below code to check if the button exists before you move the arrow key: 

session.FindElementByName("Context").FindElementByAccessibilityId("31005").Displayed;

Incase if the automation id changes every tie you right click, then ask the developers to implement automation properties.

**Comment by NikitaTurakhia** [comment]
![image](https://user-images.githubusercontent.com/21182650/131676671-8533e2a5-eadc-4ddc-a051-c2228cf8c18e.png)
got this error.
But then why it can only able to click on properties and not the other options by findlementbyname?

**Comment by NikitaTurakhia** [comment]
@anunay1 I don't think it is able to find it by the name "context".

**Comment by anunay1** [comment]
Because its not the root session, you need to create a root session and then look to context menu then you will get that.

**Comment by NikitaTurakhia** [comment]
@anunay1   How to get the root session? Will you please give me the example?

**Comment by anunay1** [comment]
> ![image](https://user-images.githubusercontent.com/7989610/131341685-6e8554e6-f5f7-44a3-80c0-c0a41eb8607c.png)
> 
> And the use the desktop session to switch to the context menu.

check this comment.

**Comment by anunay1** [comment]
its better you send me a zoom call request anunayathakur1@gmail.om

**Comment by NikitaTurakhia** [comment]
I am not bale to schedule it. It says address not found

**Comment by anunay1** [comment]
anunayathakur1@gmail.com,

**Comment by NikitaTurakhia** [comment]
@anunay1 did you get the email?

**Comment by anunay1** [comment]
yes you can start the meeting.

**Comment by anunay1** [comment]
@NikitaShah2492 please close the bug.
