### ISSUE TITLE
How to switch the window between file explorer and browser window

### ISSUE THREAD

**Issue by NikitaTurakhia** [microsoft/WinAppDriver#1582]
Hello,

I am trying to open file explorer from the browser button and then I want to focus from the browser window to file explorer for next step.
Does anybody know how to switch between browser window to desktop window with selenium c#?

**Comment by anunay1** [comment]
The focus will be on the explorer window just use the send keys to enter the filename.

**Comment by anunay1** [comment]
Is the use case to save or upload the file.

**Comment by NikitaTurakhia** [comment]
> The focus will be on the explorer window just use the send keys to enter the filename.

I am trying to do that but it is not working and it tries to search in the browser only.

**Comment by anunay1** [comment]
Is it a dialog window can you share screenshot.

**Comment by NikitaTurakhia** [comment]
No. I am opening file explorer from the browser and then it opens file explorer and I want to click on the folder in  he file explorer but it is not focusing the file explorer then.

![image](https://user-images.githubusercontent.com/21182650/131565660-b2c32b6f-654f-431b-9f97-c3df3d5e3a4a.png)

So, in the above image, I opened file explorer from the button in he browser and now I want to select the folder in the file explorer.

**Comment by anunay1** [comment]
Check in inspect the file explorer might be a seperate window and not part of the same UI tree

**Comment by anunay1** [comment]
It shows file explorer but it does not have any child elements

**Comment by NikitaTurakhia** [comment]
I know.

**Comment by anunay1** [comment]
Then the elements inside the file explorer does not have automation properties implemented windows application driver will not work, it only works if the elements are identified in inspect, if the SW is under your control ask the developers to implement automation properties
