### ISSUE TITLE
Occasional unknown error occurred failures after trying to close and re open app

### ISSUE THREAD

**Issue by Tree55Topz** [microsoft/WinAppDriver#1597]
This seems to happen sporadically for me, and its occurring with my logout function. The logout function just attempts to close and relaunch the app, which 80% of the time seems to work fine but now I am getting `'an unknown error occurred in the remote end while processing the command'`

I have this logout method

```
public void Logout()
        {
            _session.CloseApp();
            TestClassBase.CloseApp();
            _session.LaunchApp();
        }
```

_session.CloseApp didnt seem to do anything so I made a method in my TestClassBase class that manually closes the app. The method looks like this.

```
public static void CloseApp()
        {
            DisposeProcess("myapp");
            DisposeProcess("myapplaunch");
            KillProcess("myapp");
            KillProcess("myapplaunch");
        }
```
DisposeProcess is a method that calls the C# process.Dispose() and KillProcess is a method that calls the C# process.Kill().

Keep in mind, this does seem to work in a majority of cases. Not sure why it throws this error sometimes. Should I add waits in between some of these processes? I would rather not as I feel like there should be a way to do this smoothly. What I want is to be able to restart the app mid test if needed without any issues. 

I am wondering if this might have to do with how I am starting the app? I have this as my startup

```
appCapabilities.AddAdditionalCapability("app", "path/to/app");
appCapabilities.AddAdditionalCapability("appWorkingDir", "directory/of/executable");
appCapabilities.AddAdditionalCapability("appArguments", "enableautomation");
session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities, TimeSpan.FromMinutes(3));
session.Manage().Window.Maximize();
```

Could the reason the CloseApp() method not be working in the first place is because I also use the appWorkingDir capability? Not sure just a thought, but I need to specify this in order for the tests to run.

**Comment by anunay1** [comment]
_session.CloseApp is not supported and does not do anything(it's mainly for android), why not close all the process asynchronously.
And _session.quit() will close the app anyways.

**Comment by Tree55Topz** [comment]
@anunay1 _session.quit will also kill the driver session so would not work for a mid test relaunch of the app.

What do you mean by asynchronously? I was able to wrap this in a try catch and if failed wait a second and then recall _session.LaunchApp(). Seems to work pretty smoothly. 

Going to close.
