### ISSUE TITLE
Snapshot captures about 1/4 of application  window

### ISSUE THREAD

**Issue by denys-rwd** [Microsoft/WinAppDriver#16]
Hi,

Background: Running application. 
Foreground: Snapshot (via Selenium).

![capture](https://cloud.githubusercontent.com/assets/18639833/14767218/03c78008-0a29-11e6-848e-29c324a87a27.PNG)

Script:

DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability("app", "Microsoft.Windows.Photos_8wekyb3d8bbwe!App");

            rwd = new RemoteWebDriver(new URL("http://XXX.30.201.YYY:4723"), capabilities);
            WebDriver augmentedDriver = new Augmenter().augment(rwd);
            File screenshot = ((TakesScreenshot)augmentedDriver).getScreenshotAs(OutputType.FILE);

            //Close the browser
            Path destPath = Paths.get("C:\\Root\\selenium\\reports\\").resolve("Windows.Photos.png");
            com.google.common.io.Files.copy(screenshot, destPath.toFile());

In addition, although selenium script has already   brought snapshot, WinAppDriver continues to print a lot of data on console and that takes about 2.5 minutes. Eventually, it finishes the command.

![capture2](https://cloud.githubusercontent.com/assets/18639833/14767321/439c61ba-0a2b-11e6-950b-9854aa08099c.PNG)

Thanks in advance,
Denys

**Comment by paulcam206** [comment]
I'm working on a fix for this. :)

**Comment by yodurr** [comment]
Fix is included in today's release

**Comment by yodurr** [comment]
closing this issue as fixed in the latest WinAppDriver release.  denys-rwd please let us know if you still have an issue here.  thanks.
