### ISSUE TITLE
Open .exe as Admin with WinAppDriver

### ISSUE THREAD

**Issue by danielemarinelli** [microsoft/WinAppDriver#1602]
Hello,
Under the folder UNITAM SW, I have a window application. Via script I open the folder with the below code (Java):
  public void thisPC() throws Exception {
        DesiredCapabilities pc = new DesiredCapabilities();
        pc.setCapability("app", "C:\\UNITAM SW");
        pc.setCapability("platformName", "Windows");
        pc.setCapability("deviceName", "WindowsPC");
        driver = new WindowsDriver(new URL("http://127.0.0.1:4723/"), pc);
    }

Is there a way to run an app as Admin like in the screen (with a right mouse click)?
![image](https://user-images.githubusercontent.com/64636628/135053404-0aec00f1-ee60-4729-af78-82aa3a05d096.png)
I try with:
 Actions actions = new Actions(driver);
 actions.moveToElement(driver.findElementByName("Publisher")).contextClick().build().perform();

but doesn't work....
![image](https://user-images.githubusercontent.com/64636628/135053867-123cbe90-de0f-49a9-ae95-9ed7188caa1a.png)
inspector:
![image](https://user-images.githubusercontent.com/64636628/135054465-4270f038-94ac-4eb2-9a63-39ea55442b7e.png)

**Comment by anunay1** [comment]
Does you application have splash screen?

**Comment by anunay1** [comment]
If you see inspect, publisher as a name is not shown in inspect, so this piece of code will not work: 

Actions actions = new Actions(driver);
actions.moveToElement(driver.findElementByName("Publisher")).contextClick().build().perform();

Run the exe programmatically as admin.

**Comment by danielemarinelli** [comment]
The weird thing is that if I click on Publisher , the inspect Name is PUBLISHER
![image](https://user-images.githubusercontent.com/64636628/135393609-e6c04c69-2599-41d7-b092-6fd8c9608bf3.png)

I am not sure that is the meaning of splash screen.
you say: 'Run the exe programmatically as admin.'  --> how can I do it? is there a way to run as admin coding?
thanks

**Comment by anunay1** [comment]
![image](https://user-images.githubusercontent.com/7989610/135394073-7968adba-6bfd-4d97-bd0a-4f776d5f60d0.png)

**Comment by anunay1** [comment]
public void thisPC() throws Exception {
DesiredCapabilities pc = new DesiredCapabilities();
pc.setCapability("app", "C:\UNITAM SW\Publisher.exe");
pc.setCapability("platformName", "Windows");
pc.setCapability("deviceName", "WindowsPC");
driver = new WindowsDriver(new URL("http://127.0.0.1:4723/"), pc);
}

**Comment by danielemarinelli** [comment]
So opening app through the desired caps, the app will be launched as admin (by default)?

**Comment by anunay1** [comment]
no if you start WinappDriver.exe in admin mode, then you application will be launched as admin.

**Comment by danielemarinelli** [comment]
ok, you can close this topic, thanks
