### ISSUE TITLE
Application opened but session not created

### ISSUE THREAD

**Issue by git-chao** [microsoft/WinAppDriver#1604]
Hi,
May I seek the knowledge of those people who have encountered this and able to resolved it. 
The application that I needed to test is opened through CMD and powershell. However when I run the code, the application (CMD) is opened but it didn't create a session.

The Server:
POST /session HTTP/1.1
Accept-Encoding: gzip
Connection: Keep-Alive
Content-Length: 470
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.59 (java windows)
X-Idempotency-Key: 0c95c00d-b746-4ce8-a0a9-70466bea9436

HTTP/1.1 500 Internal Error
Content-Length: 166
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"Failed to locate opened application window with appId: C:\\Windows\\System32\\cmd.exe, and processId: 5584"}}

The Code:
DesiredCapabilities cap = new DesiredCapabilities();
cap.setCapability("app", "C:\\Windows\\System32\\cmd.exe");
cap.setCapability("Platform", "Windows 10");
cap.setCapability("Device Name", "Windows PC");
driver = new WindowsDriver(new URL("http://127.0.0.1:4723/"), cap);

**Comment by anunay1** [comment]
You need to create a root session and then switch to the opened window.

**Comment by git-chao** [comment]
Thanks! 
Checked the other questions and this becomes redundant :)
