### ISSUE TITLE
Open and automate a window folder, not a win app .exe

### ISSUE THREAD

**Issue by danielemarinelli** [microsoft/WinAppDriver#1619]
Hello, 
I am wondering if there is a possibility to automate not windows applications (.exe) , but windows folders.
I mean copying files from one folder to another folder. 
I created a session of my folder:
@BeforeSuite
public void folderHHSettingsToPanel() {
DesiredCapabilities HHSettings = new DesiredCapabilities();
HHSettings.setCapability("app", "C:\\UNITAM\\FileMaster\\Files\\HHSettings\\ToPanel\\Settings");
HHSettings.setCapability("platformName", "HH");
HHSettings.setCapability("deviceName", "HHfolder");
windowHHSettingsToPanel = new WindowsDriver(new URL("http://127.0.0.1:4723/"), HHSettings);
}

When I launch the code, my folder opens, but I receive the error below: 
![image](https://user-images.githubusercontent.com/64636628/137466142-71d5fbb9-9d98-40ef-8153-65950450cf30.png)

is this Exception displayed because I am not launching a window app .exe??
The doubt is: Can WinAppDriver  interact with dialogs windows??

thanks

**Comment by danielemarinelli** [comment]
I see, your right from cmd line. thanks

**Comment by DHowett** [comment]
The best way for you to move/copy files using C# is to [write native C# code to move the files](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/file-system/how-to-copy-delete-and-move-files-and-folders). You do not need to ask CMD to do the work for you, and you do not need to ask File Explorer to do the work for you.

It is immensely more complicated to tell CMD to rename a folder than it is to "do it yourself" :smile:
