### ISSUE TITLE
Winappdriver.exe - throws "api-ms-win-core-registry-l1-1-0.dll" missing while installing selenium webdriver

### ISSUE THREAD

**Issue by Manvibha** [Microsoft/WinAppDriver#162]
Hi, 

I have downloaded v0.7-beta November 30, 2016 version from https://github.com/Microsoft/WinAppDriver/releases . 
Upon executing Winappdriver.exe it throws error ""The program can't start because api-ms-win-core-registry-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem. "

Is there a bug in latest winappdriver? 

regards,
Mahendra 
![winappdriver](https://cloud.githubusercontent.com/assets/13233125/23697885/7c0eaca4-040f-11e7-9bb7-05878ca091a1.JPG)

**Comment by GURU82** [comment]
I too noticed this issue when open the WinAppDriver.exe.
I'm using win8.1 Pro windows OS

**Comment by Manvibha** [comment]
I am using Win7.
However, are you able to automate any windows app winappdriver ?

**Comment by jmaxxz** [comment]
Right now this tool only appears to support windows 10 .

**Comment by Manvibha** [comment]
Thanks for info @jmaxxz

**Comment by jmaxxz** [comment]
@Manvibha if like me you would love to see this project support other versions of windows vote for it here:
https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/13518501-winappdriver-support-to-win-7-and-8

**Comment by yodurr** [comment]
@jmaxxz is correct we currently only support Win10.  Thanks @jmaxxz for helping out on the issue board.

**Comment by Slesa** [comment]
Great that you only support Win10 - but I am trying to use WinAppDriver on our BuildServer. What about Windows Server 2012 R2?
