### ISSUE TITLE
Failed to locate opened application for applications requires administrative privilege

### ISSUE THREAD

**Issue by Zou-Jia** [microsoft/WinAppDriver#1620]
HI, I am trying to automate some applications that requires administrative privilege.
I keep getting "Failed to located opened application window with app id:xxx and Process Id:xxx"

To reproduce the problem:
1.Run WinAppDriver.exe in admin mode
2. `AppiumOptions Options = new AppiumOptions();
  Options.AddAdditionalCapability("app", @"C:\WINDOWS\system32\eventvwr.exe");
new WindowsDriver<WindowsElement>(new Uri(DriverUrl), Options);`
3. Application opened but get `{"status":13,"value":{"error":"unknown error","message":"Failed to locate opened application window with appId: C:\\WINDOWS\\system32\\eventvwr.exe, and processId: 32828"}}`

Am I missing something?

**Comment by liljohnak** [comment]
Just copied the answer from a previous post.

>Since Teams has a splash screen when starting you probably have to attach to the new window that it creates. Some details linked in this other issue:
>#1341

**Comment by Zou-Jia** [comment]
Thanks for the reply.
Although `eventvwr.exe` do not seem to have a splash screen, the application I am working on do.
