### ISSUE TITLE
Need help using get_attribute()

### ISSUE THREAD

**Issue by danielwilliamsmith** [Microsoft/WinAppDriver#163]
I am using Appium V1.6.3 and Appium Python Client V0.14.

WebElement get_attribute is always returning a value of None when automating the Windows Calculator app.  I have tried many different properties but I have found nothing that returns a value.  

I am doing something like this for the '9' button:

```
something = self.driver.find_element_by_xpath("//Button[(@Name='Nine' and @LocalizedControlType='button')]")

print("\nHello: " + str(something.get_attribute('Name')))
```

The find is successful but get_attribute is always None.

Am I doing this wrong or is it not expected to work?

**Comment by timotiusmargo** [comment]
Hi @danielwilliamsmith,

This feature is only recently added in [v1.0-RC](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.0-RC). From this release forward you should be able to get any element attribute shown in [inspect.exe](https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/README.md#inspecting-ui-elements). More example on `GetAttribute` API can be found on https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/Tests/WebDriverAPI/ElementAttribute.cs#L38.

**Comment by Abhishekkawathekar** [comment]
Hi,

I tried to get the attribute from the methods suggested. I was able to get the attributes for my application for sum of the attributes. But, for some reason I can not find the element attributes which are shown in  inspect.exe. I am getting the null pointer exception for some of them.

I have attached my code, inspect output for the element as well as winappdriver output.

My Code:

`WebElement Element = driver.findElementByAccessibilityId(arg1);
					
					//.getText().toString();
			
			System.out.println("This is the Voucher No " + Element.getAttribute("AutomationId").toString());
			
			System.out.println("This is the Voucher No " + Element.getAttribute("ProviderDescription").toString());
			
			System.out.println("This is the Voucher No " + Element.getAttribute("IsAnnotationPatternAvailable").toString());
			
			
			
			System.out.println("This is the Voucher No " + Element.getAttribute("LegacyIAccessible.Value").toString());`
			

Inspect Output
`How found:	Focus
	hwnd=0x00211C38 64bit class="WindowsForms10.EDIT.app.0.a0f91b_r6_ad1" style=0x560108C0 ex=0x200
Name:	""
ControlType:	UIA_EditControlTypeId (0xC354)
LocalizedControlType:	"edit"
BoundingRectangle:	{l:463 t:191 r:600 b:211}
IsEnabled:	true
IsOffscreen:	false
IsKeyboardFocusable:	true
HasKeyboardFocus:	true
AccessKey:	""
ProcessId:	10356
RuntimeId:	[2A.211C38]
AutomationId:	"TextVoucherNo"
FrameworkId:	"WinForm"
ClassName:	"WindowsForms10.EDIT.app.0.a0f91b_r6_ad1"
NativeWindowHandle:	0x211C38
ProviderDescription:	"[pid:17356,providerId:0x211C38 Main:Nested [pid:10356,providerId:0x211C38 Main(parent link):Microsoft: MSAA Proxy (unmanaged:uiautomationcore.dll)]; Nonclient:Microsoft: Non-Client Proxy (unmanaged:uiautomationcore.dll); Hwnd(parent link):Microsoft: HWND Proxy (unmanaged:uiautomationcore.dll)]"
IsPassword:	false
HelpText:	""
LegacyIAccessible.ChildId:	0
LegacyIAccessible.DefaultAction:	""
LegacyIAccessible.Description:	""
LegacyIAccessible.Help:	""
LegacyIAccessible.KeyboardShortcut:	""
LegacyIAccessible.Name:	""
LegacyIAccessible.Role:	editable text (0x2A)
LegacyIAccessible.State:	focused,read only,focusable (0x100044)
LegacyIAccessible.Value:	"BNKP18000040"
Value.IsReadOnly:	true
Value.Value:	"BNKP18000040"
IsAnnotationPatternAvailable:	false
IsDragPatternAvailable:	false
IsDockPatternAvailable:	false
IsDropTargetPatternAvailable:	false
IsExpandCollapsePatternAvailable:	false
IsGridItemPatternAvailable:	false
IsGridPatternAvailable:	false
IsInvokePatternAvailable:	false
IsItemContainerPatternAvailable:	false
IsLegacyIAccessiblePatternAvailable:	true
IsMultipleViewPatternAvailable:	false
IsObjectModelPatternAvailable:	false
IsRangeValuePatternAvailable:	false
IsScrollItemPatternAvailable:	false
IsScrollPatternAvailable:	false
IsSelectionItemPatternAvailable:	false
IsSelectionPatternAvailable:	false
IsSpreadsheetItemPatternAvailable:	false
IsSpreadsheetPatternAvailable:	false
IsStylesPatternAvailable:	false
IsSynchronizedInputPatternAvailable:	false
IsTableItemPatternAvailable:	false
IsTablePatternAvailable:	false
IsTextChildPatternAvailable:	false
IsTextEditPatternAvailable:	false
IsTextPatternAvailable:	false
IsTextPattern2Available:	false
IsTogglePatternAvailable:	false
IsTransformPatternAvailable:	false
IsTransform2PatternAvailable:	false
IsValuePatternAvailable:	true
IsVirtualizedItemPatternAvailable:	false
IsWindowPatternAvailable:	false
IsCustomNavigationPatternAvailable:	false
IsSelectionPattern2Available:	false
FirstChild:	[null]
LastChild:	[null]
Next:	"" edit
Previous:	"Voucher Ref. No : " text
Other Props:	Object has no additional properties
Children:	Container has no children
Ancestors:	"Header" pane
	"" tab
	"Contra Entry Form- (Cash to Bank)" window
	"API Payments Completed for RBL Regular Payments" pane
	"Enterprise Resource Planning S/w - [MSWIPE TECHNOLOGIES PVT. LTD. (Dev UAT)] Version : 5.1.5.0 FY : 1/4/2010 - 1/3/2019" window
	"Desktop 1" pane
	[ No Parent ]
`

Winappdriver output:
`POST /session/21468240-50BD-4955-8EF0-B7F5478205F0/element HTTP/1.1
Accept-Encoding: gzip
Connection: Keep-Alive
Content-Length: 61
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.14.0 (java windows)

{
  "using": "accessibility id",
  "value": "Btn_VoucherNo"
}
HTTP/1.1 200 OK
Content-Length: 96
Content-Type: application/json

{"sessionId":"21468240-50BD-4955-8EF0-B7F5478205F0","status":0,"value":{"ELEMENT":"42.3675302"}}


==========================================
GET /session/21468240-50BD-4955-8EF0-B7F5478205F0/element/42.3675302/attribute/AutomationId HTTP/1.1
Accept-Encoding: gzip
Cache-Control: no-cache
Connection: Keep-Alive
Host: 127.0.0.1:4723
User-Agent: selenium/3.14.0 (java windows)


HTTP/1.1 200 OK
Content-Length: 87
Content-Type: application/json

{"sessionId":"21468240-50BD-4955-8EF0-B7F5478205F0","status":0,"value":"Btn_VoucherNo"}


==========================================
GET /session/21468240-50BD-4955-8EF0-B7F5478205F0/element/42.3675302/attribute/ProviderDescription HTTP/1.1
Accept-Encoding: gzip
Cache-Control: no-cache
Connection: Keep-Alive
Host: 127.0.0.1:4723
User-Agent: selenium/3.14.0 (java windows)


HTTP/1.1 200 OK
Content-Length: 296
Content-Type: application/json

{"sessionId":"21468240-50BD-4955-8EF0-B7F5478205F0","status":0,"value":"[pid:11028,providerId:0x3814A6 Main:Nested [pid:10356,providerId:0x3814A6 Main(parent link):Microsoft: MSAA Proxy (unmanaged:uiautomationcore.dll)]; Hwnd(parent link):Microsoft: HWND Proxy (unmanaged:uiautomationcore.dll)]"}


==========================================
GET /session/21468240-50BD-4955-8EF0-B7F5478205F0/element/42.3675302/attribute/IsAnnotationPatternAvailable HTTP/1.1
Accept-Encoding: gzip
Cache-Control: no-cache
Connection: Keep-Alive
Host: 127.0.0.1:4723
User-Agent: selenium/3.14.0 (java windows)


HTTP/1.1 200 OK
Content-Length: 79
Content-Type: application/json

{"sessionId":"21468240-50BD-4955-8EF0-B7F5478205F0","status":0,"value":"False"}


==========================================
GET /session/21468240-50BD-4955-8EF0-B7F5478205F0/element/42.3675302/attribute/LegacyIAccessible.Value HTTP/1.1
Accept-Encoding: gzip
Cache-Control: no-cache
Connection: Keep-Alive
Host: 127.0.0.1:4723
User-Agent: selenium/3.14.0 (java windows)


HTTP/1.1 200 OK
Content-Length: 76
Content-Type: application/json

{"sessionId":"21468240-50BD-4955-8EF0-B7F5478205F0","status":0,"value":null}

`
Can you please comment on the same
