### ISSUE TITLE
The positioning of an app using winappdriver is incorrect.

### ISSUE THREAD

**Issue by rogerst8** [Microsoft/WinAppDriver#164]
Repro Steps:
1. Open the calculator sample.
2. Add `CalculatorSession.Manage().Window.Position = new System.Drawing.Point(0, 0)` around L45 in `CalculatorTestBase.cs` (should be in the `BaseSetup` method).
3. Add `System.Drawing.Point pos = CalculatorSession.Manage().Window.Position` on the next line.
4. Set a breakpoint on the next code line after (3).
3. Run the win app driver.
4. Debug the addition test.
5. Check the window position (from (3) and physically).

Result:
the x is offset from (0, 0) by some small amount (we have found it to be 8-13px).

Expected:
The app is positioned correctly.

Impact:
This prevents us from using the position of the app to accurately calculate screen positioning while snapshotting apps for testing.

**Comment by miniksa** [comment]
I've made a fix targeting the 8-13px offset in the window corner for v0.8

**Comment by rogerst8** [comment]
@miniksa is there a date for v0.8 yet?

**Comment by miniksa** [comment]
Looks like it's out: https://github.com/Microsoft/WinAppDriver/releases/tag/v0.8-beta :)

**Comment by rogerst8** [comment]
@miniksa Haha, must have been just after I asked! Thanks~
