### ISSUE TITLE
How can I switch to the app that has just launched?

### ISSUE THREAD

**Issue by aakilb** [microsoft/WinAppDriver#1646]
My Application Under Test (AUT) is launched in the background. This results in:
`selenium.common.exceptions.TimeoutException` 

This is because the element cannot be found on the page at that time since the app is running in the background and is not in focus. How can I switch to the newly opened app after it launches?

I have used the below code to launch the app:

```
desired_caps = {}
desired_caps["app"] = app
desired_caps["ms:waitForAppLaunch"] = 10
driver = webdriver.Remote(
        command_executor='http://127.0.0.1:4723',
        desired_capabilities= desired_caps)
driver.maximize_window()


```

So far, I have tried to switch to the new window by running: 
`driver.switch_to.window(driver.window_handles[0])`

This does not work.

**Comment by anunay1** [comment]
You need to create a root session and then switch to the opened window.

**Comment by aakilb** [comment]
Right now in the line: `desired_caps["app"] = app`, the `app` variable contains the path to my app. If I do the following `desired_caps["app"] = "Root"`, how will the app open?

**Comment by anunay1** [comment]
Once you launch your app and create a session with 

driver = webdriver.Remote(
        command_executor='http://127.0.0.1:4723',
        desired_capabilities= desired_caps)

You need to create another driver session with root and switch to the opened window to bring the widow in focus.

**Comment by aakilb** [comment]
I added the following code and I am getting error message: `selenium.common.exceptions.WebDriverException: Message: Window handle does not belong to the same process/application`:

```
desired_caps_root = {}
desired_caps_root["app"] = "Root"
rootDriver = webdriver.Remote(
       command_executor='http://127.0.0.1:4723',
       desired_capabilities= desired_caps_root)

driver.maximize_window()

rootDriver.switch_to.window(driver.window_handles[0])
```

I am not sure what I am doing wrong and request your help.

**Comment by aakilb** [comment]
Thank you anunay1.

For anyone reading this in the future, the solution can be found at:

https://github.com/microsoft/WinAppDriver/issues/92#issuecomment-464620988
