### ISSUE TITLE
Why does WinAppDriver.exe require developer mode?

### ISSUE THREAD

**Issue by amervitz** [Microsoft/WinAppDriver#165]
I would like to use WinAppDriver on a computer that doesn't have developer mode turned on. Is there a technical limitation or reason why it requires developer mode? It starts up just fine even when developer mode isn't turned on with the message:

> Developer mode is not enabled. Enable it through Settings and restart Windows Application Driver

**Comment by marc-mueller** [comment]
We have the same issue. Any reason for that?

**Comment by rajeeshmenoth** [comment]
We have the same issue in WinAppDriver !! Any solution for this thread @timotiusmargo  ?

**Comment by khouzam** [comment]
Hi,

WinAppDriver's requirement on DeveloperMode is based on the premise that it is a developer tool. Enabling DeveloperMode requires Administrative access to the machine, and therefore enforces that the user has the right set of permissions to control the machine.

**Comment by amervitz** [comment]
Please remove this restriction.

**Comment by Purus** [comment]
This is a blocker for using WiAppDriver in many corporates as developer mode can't be enabled for all developers.

**Comment by 4alexbo** [comment]
So this is just an artificially created annoyance. 
Please remove it!

> Hi,
> 
> WinAppDriver's requirement on DeveloperMode is based on the premise that it is a developer tool. Enabling DeveloperMode requires Administrative access to the machine, and therefore enforces that the user has the right set of permissions to control the machine.

**Comment by Purus** [comment]
Yes. Rightly said. It's an unwanted restriction.

Thanks,

Purusothaman Ramanujam

**Comment by ramezah** [comment]
> We have the same issue. Any reason for that? What is the requirement for that?
> 
> We simply enable developer mode before running our tests by executing the following PowerShell bevor starting up WinAppDriver.exe:
> `reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock" /t REG_DWORD /f /v "AllowDevelopmentWithoutDevLicense" /d "1"`

The above command worked for me. My company policy require Avecto Priviledges. So run the Powershell as Administrator or with Avecto defendpoint and add the reg add command above and you'll see that the dev mode is switched on. 

![DevMode](https://user-images.githubusercontent.com/1126062/62121020-ae555580-b2ba-11e9-9f89-a246392e7f40.PNG)

**Comment by Taldren76** [comment]
This is a blocker for all automation as this is an unacceptable change in the environment in which we are performing QA. Users don't run in developer mode, so we aren't allowed to QA in it. It's as simple as that.

**Comment by peteferraro** [comment]
For what it's worth I am using WinAppDriver in a production environment to do Robotic Process Automation (RPA) Validation of application availability.  Developer Mode has been identified by our security team as a no no.  It's a show stopper.  Why FORCE developer mode?

**Comment by vkuppa1** [comment]
This is really frustrating, Our IT Team doesn't want us to Enable developer mode, this restriction is not required. It would be better if they lift off this restriction.

**Comment by douniwan5788** [comment]
This is stupid! Administrative permissions can be verified through other means, not by open a secure leak on the machine!

**Comment by DHowett** [comment]
It’s a developer tool that _opens a listening port on your machine that allows anybody who connects without authentication to drive and screen scrape any application your account can access_. It’s a developer tool.
