### ISSUE TITLE
Cannot find WinForm Form Dialog triggered from Word Add-In

### ISSUE THREAD

**Issue by hicks86** [microsoft/WinAppDriver#1655]
Hello,

I'm using WinAppDriver driven by Appium, trying to test a Word Add-In WinForms application, currently running into an issue trying to locate a dialog that appears.

**The issue:** We have a Microsoft Word COM Add-In that has a button on it that we use to open up a Form Dialog (calling `xxx.ShowDialog(this)`. We have been using the both sessions and the wordElement calling`xxxSession.FindByName`, `xxxSession.FindByAccessibilityId`, xxxSession.FindByXpath, and `xxxSession.FindByClass` but still cannot find it. 

I have opened up Inspect.exe and can hover over the dialog and it will bring show properties of the Dialog (confirming the Name and AutomationId and other values like Children controls and it's Ancestors), _it does not show where it this element exists in the TreeView view of Inspect.exe which is on the left hand side._ 

Has anyone had this issue?

```csharp
//This is how we are setting up the Sessions:
WindowsDriver<WindowsElement> driverWinWord;
WindowsDriver<WindowsElement> driverDesktop;
AppiumOptions optionsWinWord;
AppiumOptions optionsDesktop;

optionsWinWord = new AppiumOptions();
optionsWinWord.AddAdditionalCapability("app", "winword");
optionsWinWord.AddAdditionalCapability("appArguments", fileName);
optionsWinWord.AddAdditionalCapability("ms:waitForAppLaunch", "6");

driverWinWord = new WindowsDriver<WindowsElement>(new Uri(url), optionsWinWord);

optionsDesktop = new AppiumOptions();
optionsDesktop.AddAdditionalCapability("app", "Root");

driverDesktop = new WindowsDriver<WindowsElement>(new Uri(url), optionsDesktop);

var wordElement = driverWinWord.FindElementByClassName("OpusApp");

```

We have tried calling `FindXXX` within retry logic and tried using Appiums WebDriverWait technique in case it needed more time to find the element.

I have also looked at the PageSource of both of our sessions and cannot see the dialog in the XML, so I am pretty confident it isn't a timing issue, just that WAD cannot see it (even though Inspect.exe sees it, but just doesn't know where it is with regards to the rest of the controls on the desktop).

Any advice? 

Let me know if you need some more information.

**Comment by DLightstone** [comment]
Get a WindowsElement to the word document 
Navigate xml search for the popup relative to than element

I generally search by window title, rather than class

**Comment by hicks86** [comment]
Thanks for getting back to me. We already get a WindowsElement for the instance of Word, can you show me what you mean to do an XML Search? Or do you mean XPath?

**Comment by DLightstone** [comment]
My guess based on 
driverWinWord = new WindowsDriver<WindowsElement>(new Uri(url), optionsWinWord);

is
popupWindow = driverWinWord.FindElementByName(popupName) as WindowsElement;

**Comment by hicks86** [comment]
> At the moment we are unable to find this element within our session (I have tried FindByName, FindByAccessibilityId, FindByClass etc).

We are already trying this.

**Comment by anunay1** [comment]
", it does not show where it this element exists in the TreeView view of Inspect.exe which is on the left hand side." Do you mean that inspect does not show the element.

**Comment by DLightstone** [comment]
Its not the entire code base, but it should get you started.
You will have to prune away the sanity checks (window visible etc)

     parentWindowName is the title of the word document being edited. 
         for the file SpellCheck.docx is would be "SpellCheck.docx - Word"
    StrWindowClass is the class name of the popup
        for the spell check popup it is "bosa_sdm_msword"
    popupName is the name of the popup
        for spell check it is "Spelling: English (United States)"

    GetRootWindow returns a WindowsElement to the Word application relative to the root

      public static WindowsElement FindClassPopupWindow(string parentwindowName,
                                                          string strWindowClass,
                                                          string popupName,
                                                          Int32 intDelayInSeconds)
      {
         Boolean bIsVisible;
         IntPtr intHandle;
         WindowsElement CreateNewProjectWindow;
         WindowsElement popupWindow;
         Int32 intTimeout;
         Int32 loopCount;
         Int32 loopLimit;

         bIsVisible = GuiTestUtilities.GuiRootAccess.IsRootWindowVisible(parentwindowName, 16);
         Assert.IsTrue(bIsVisible, "Root window not visible " + parentwindowName);

         intHandle = Utilities.OSWindowApi.FindClassPopUp(parentwindowName,
                                                          strWindowClass,
                                                          popupName);
         Assert.AreNotEqual(0, intHandle, "Popup window not visible" + popupName);

         Utilities.OSWindowApi.SetWindowFocus(intHandle);
         intTimeout = intDelayInSeconds + 10;
         CreateNewProjectWindow = GetRootWindow(parentwindowName, intTimeout);
         Assert.IsNotNull(CreateNewProjectWindow);

         loopCount = 0;
         loopLimit = (intDelayInSeconds + 2) / 3;
         popupWindow = null;
         while ((popupWindow == null) && (loopCount < loopLimit))
         {
            try
            {
               popupWindow = CreateNewProjectWindow.FindElementByName(popupName) as WindowsElement;
            }
            catch
            {
               loopCount += 1;
               popupWindow = null;

            }
         }
         return (popupWindow);

      }

**Comment by hicks86** [comment]
> ", it does not show where it this element exists in the TreeView view of Inspect.exe which is on the left hand side." Do you mean that inspect does not show the element.

In the Inspect.exe tool there is a Left and Right view, the Left is a Treeview of all the controls laid out as a tree (parent > child etc), on the right is information about a highlighted tool. When I hover over the dialog I have information appearing about the dialog element in the Right  view, but not in the Left (as in it cannot show me who the parent element is).

Below is an example of an element appearing correctly in both left and right views (it is the "Paste" button in MSWord)
![image](https://user-images.githubusercontent.com/11144895/146935927-2b19bb87-f683-43ca-9fe0-e0d94bcc5c5d.png)

For our dialog it does not show or highlight it in the left view. I have tried going through each node and it is not there. However I can see information about it in the right hand control

Hope that makes sense?

**Comment by hicks86** [comment]
> Its not the entire code base, but it should get you started. You will have to prune away the sanity checks (window visible etc)
> 
> ```
>  parentWindowName is the title of the word document being edited. 
>      for the file SpellCheck.docx is would be "SpellCheck.docx - Word"
> StrWindowClass is the class name of the popup
>     for the spell check popup it is "bosa_sdm_msword"
> popupName is the name of the popup
>     for spell check it is "Spelling: English (United States)"
> 
> GetRootWindow returns a WindowsElement to the Word application relative to the root
> 
>   public static WindowsElement FindClassPopupWindow(string parentwindowName,
>                                                       string strWindowClass,
>                                                       string popupName,
>                                                       Int32 intDelayInSeconds)
>   {
>      Boolean bIsVisible;
>      IntPtr intHandle;
>      WindowsElement CreateNewProjectWindow;
>      WindowsElement popupWindow;
>      Int32 intTimeout;
>      Int32 loopCount;
>      Int32 loopLimit;
> 
>      bIsVisible = GuiTestUtilities.GuiRootAccess.IsRootWindowVisible(parentwindowName, 16);
>      Assert.IsTrue(bIsVisible, "Root window not visible " + parentwindowName);
> 
>      intHandle = Utilities.OSWindowApi.FindClassPopUp(parentwindowName,
>                                                       strWindowClass,
>                                                       popupName);
>      Assert.AreNotEqual(0, intHandle, "Popup window not visible" + popupName);
> 
>      Utilities.OSWindowApi.SetWindowFocus(intHandle);
>      intTimeout = intDelayInSeconds + 10;
>      CreateNewProjectWindow = GetRootWindow(parentwindowName, intTimeout);
>      Assert.IsNotNull(CreateNewProjectWindow);
> 
>      loopCount = 0;
>      loopLimit = (intDelayInSeconds + 2) / 3;
>      popupWindow = null;
>      while ((popupWindow == null) && (loopCount < loopLimit))
>      {
>         try
>         {
>            popupWindow = CreateNewProjectWindow.FindElementByName(popupName) as WindowsElement;
>         }
>         catch
>         {
>            loopCount += 1;
>            popupWindow = null;
> 
>         }
>      }
>      return (popupWindow);
> 
>   } 
> ```

Ok great thank you. I will see if this helps and will report back.

**Comment by anunay1** [comment]
> > ", it does not show where it this element exists in the TreeView view of Inspect.exe which is on the left hand side." Do you mean that inspect does not show the element.
> 
> In the Inspect.exe tool there is a Left and Right view, the Left is a Treeview of all the controls laid out as a tree (parent > child etc), on the right is information about a selected/highlighted element. When I hover over the dialog I have information appearing about the dialog element in the Right view (like Name, ControlType, AutomationId, ClassName etc etc), but not in the Left (as in it cannot show me who the parent element is).
> 
> Below is an example of an element appearing correctly in both left and right views (it is the "Paste" button in MSWord) ![image](https://user-images.githubusercontent.com/11144895/146936778-08358461-e434-4689-aba3-51b9e6c1da19.png) For our dialog it does not show or highlight it in the left view. I have tried going through each node and it is not there. However I can see information about it in the right hand control
> 
> Hope that makes sense?

Apologies for stupid question, but did you try using the refresh button in inspect.

**Comment by DLightstone** [comment]
It do not particularly like using Inspect or Accessibility Insights.
Sometime it is necessarily to get the actual XML time synchronous with the execution of the testing code. (ie what Inspect see and what your test code sees may be different)

You can dump the session XML using

      public static void SaveSourceToFile(WindowsDriver<WindowsElement> session,
                                          string strFile)

      {
         bool bExists;      
          var source = session.PageSource;

         Assert.AreNotEqual(source.Length, 0);

         bExists = Utilities.OSFileUtilities.DoesFileExist(strFile);
         if (bExists)
         {
            Utilities.OSFileUtilities.DeleteFile(strFile);
         }

         System.Xml.XmlDocument xmlDoc = new System.Xml.XmlDocument();
         System.Xml.XmlTextWriter w = new System.Xml.XmlTextWriter(strFile,
                                                                  System.Text.Encoding.BigEndianUnicode);
         xmlDoc.LoadXml(source);

         xmlDoc.WriteTo(w);
         w.Close();

      }

**Comment by hicks86** [comment]
> It do not particularly like using Inspect or Accessibility Insights. Sometime it is necessarily to get the actual XML time synchronous with the execution of the testing code. (ie what Inspect see and what your test code sees may be different)
> 
> You can dump the session XML using
> 
> ```
>   public static void SaveSourceToFile(WindowsDriver<WindowsElement> session,
>                                       string strFile)
> 
>   {
>      bool bExists;      
>       var source = session.PageSource;
> 
>      Assert.AreNotEqual(source.Length, 0);
> 
>      bExists = Utilities.OSFileUtilities.DoesFileExist(strFile);
>      if (bExists)
>      {
>         Utilities.OSFileUtilities.DeleteFile(strFile);
>      }
> 
>      System.Xml.XmlDocument xmlDoc = new System.Xml.XmlDocument();
>      System.Xml.XmlTextWriter w = new System.Xml.XmlTextWriter(strFile,
>                                                               System.Text.Encoding.BigEndianUnicode);
>      xmlDoc.LoadXml(source);
> 
>      xmlDoc.WriteTo(w);
>      w.Close();
> 
>   }
> ```

Amazing thank!!

**Comment by hicks86** [comment]
@DLightstone so for the above attached code `FindClassPopup()` I have assumed the line `Utilities.OSWindowApi.SetWindowFocus(intHandle);` is essentially:
```csharp
[DllImport("user32.dll")]
public static extern bool SetForegroundWindow(IntPtr hWnd);
```
Is that correct?

At the moment I am struggling with what is: `Utilities.OSWindowApi.FindClassPopUp(parentwindowName, strWindowClass,popupName);`.

Are you able to share some light what these do please, I am trying to follow your example to find the dialog form. Cheers

**Comment by DLightstone** [comment]
FindClassPopUp is part of the sanity checks
It get the Windows window handle to the popup

you can eliminate the sanity checks 
===============

     bIsVisible = GuiTestUtilities.GuiRootAccess.IsRootWindowVisible(parentwindowName, 16);
     Assert.IsTrue(bIsVisible, "Root window not visible " + parentwindowName);

     intHandle = Utilities.OSWindowApi.FindClassPopUp(parentwindowName,
                                                      strWindowClass,
                                                      popupName);
     Assert.AreNotEqual(0, intHandle, "Popup window not visible" + popupName);

     Utilities.OSWindowApi.SetWindowFocus(intHandle);

=======================

**Comment by hicks86** [comment]
@DLightstone  Ah I see! Thank you for confirming that.

**Comment by hicks86** [comment]
@DLightstone apologies for not getting back to this sooner, with the holidays and ramping back up into work only just getting a chance to get back to you.

Unfortunately approach didn't make the difference. I appreciate the process that this code is essentially refreshing our Driver when there are changes made to the UI (like in my scenario the new Dialog box). However I was still unable to locate the Dialog using this.

Does anyone have any other ideas?

**Comment by DLightstone** [comment]
To dump the XML just before you want to look for the popup. 
using  public static void SaveSourceToFile(WindowsDriver<WindowsElement> session,
                                      string strFile)

See which windows are visible.

**Comment by hicks86** [comment]
I will do that now.

**Comment by hicks86** [comment]
Thank you @DLightstone for your assistance.

Finally figured out what was going on (well sort of) - essentially the framework we use to create a COM Add-In (AddinExpres) seemed to be sandboxing the dialog so we could never see or access it through Appium. Basically the way we instantiated the dialog it seemed to appear underneath the AddinExpress panel, however by calling the instantiation code in a different way was able to run it so that it would appear in Word as a control that I could access via Appium.

I think I may raise this with the framework and see if they can provide me with a reason it didn't work the original way.

**Comment by DLightstone** [comment]
@[hicks86](https://github.com/hicks86)

Good to learn that.
I also made some discoveries.
In particular locating Word Documents via the document title (ie document name) is not a good idea.
Seems Microsoft used the title to convey status information as part of the title.
If you search on the document name only you may not find anything

To locate popups,  I decided FindByClass (of the popup) is more reliable

**Comment by hicks86** [comment]
Ah yes @DLightstone  we have since moved away from trying to find it by name and do so via FindByClass() as well. 
Thank you again I have learnt a fair bit during this invetigation proces aswell!!
