### ISSUE TITLE
Unable to send keys to the MS Word Editor and getting "error":"no such element".

### ISSUE THREAD

**Issue by elprofesor999** [microsoft/WinAppDriver#1660]
IWebElement textEditor = wordSession.FindElementByName("Page 1 Content");
textEditor.Click();
textEditor.SendKeys("Hello Word");

wordSession ~ WAD with MS Word session

Element located, Click happened but this send keys is throwing the below error:
POST /session/B85CF67F-9330-4D51-8ADD-CD05846ED7E5/element HTTP/1.1
Accept: application/json, image/png
Content-Length: 41
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.0 (.net windows)

{"using":"name","value":"Page 1 content"}
HTTP/1.1 200 OK
Content-Length: 100
Content-Type: application/json

{"sessionId":"B85CF67F-9330-4D51-8ADD-CD05846ED7E5","status":0,"value":{"ELEMENT":"42.1379376.4.2"}}

==========================================
POST /session/B85CF67F-9330-4D51-8ADD-CD05846ED7E5/element/42.1379376.4.2/click HTTP/1.1
Accept: application/json, image/png
Content-Length: 2
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.0 (.net windows)

{}
HTTP/1.1 200 OK
Content-Length: 63
Content-Type: application/json

{"sessionId":"B85CF67F-9330-4D51-8ADD-CD05846ED7E5","status":0}

==========================================
POST /session/B85CF67F-9330-4D51-8ADD-CD05846ED7E5/element/42.1379376.4.2/value HTTP/1.1
Accept: application/json, image/png
Content-Length: 24
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.0 (.net windows)

{"value":["Hello Word"]}
HTTP/1.1 500 Internal Error
Content-Length: 133
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}

**Comment by Tree55Topz** [comment]
Does this always happen or does it happen intermittently? One thing you could try is to actually switch to the active element (which should be the editable text box once you click) and then sendKeys to that element. Try something like this...

```
textEditor.Click();
WindowsElement editable = (WindowsElement)_session.SwitchTo().ActiveElement();
editable.SendKeys("Hello Word");
```

In some cases that element you are identifying as textEditor may not actually be the editable text box once active. Switching to the active element after clicking should work. or just drill a bit more into that text box using the inspect tool to see if theres another element you should instead be accessing. The example above you may or may not need to cast to WindowsElement, I know I need to with mine.

**Comment by elprofesor999** [comment]
> Does this always happen or does it happen intermittently? One thing you could try is to actually switch to the active element (which should be the editable text box once you click) and then sendKeys to that element. Try something like this...
> 
> ```
> textEditor.Click();
> WindowsElement editable = (WindowsElement)_session.SwitchTo().ActiveElement();
> editable.SendKeys("Hello Word");
> ```
> 
> In some cases that element you are identifying as textEditor may not actually be the editable text box once active. Switching to the active element after clicking should work. or just drill a bit more into that text box using the inspect tool to see if theres another element you should instead be accessing. The example above you may or may not need to cast to WindowsElement, I know I need to with mine.

**Comment by elprofesor999** [comment]
Closed in error. @Tree55Topz  Thanks for the comment. But the thing here is, it is not a text box. It is a editor. I tried normally sending keys to the specific text boxes , which is working fine. But curious to check whether we can send the keys to the editor or not. There is already a closed issue #1346.

**Comment by Tree55Topz** [comment]
@elprofesor999 I am confused, so did my suggestion work? You could also try the click and then just generically sendingKeys via the session, that shouldn't depend on any sort of element as long as the click enabled the editor..

```
textEditor.Click();
_session.Keyboard.SendKeys("Hello World");
```

**Comment by Tree55Topz** [comment]
@elprofesor999 can this be closed or did that suggestion not work?

**Comment by elprofesor999** [comment]
> WindowsElement editable = (WindowsElement)_session.SwitchTo().ActiveElement();
> editable.SendKeys("Hello Word");

This is working fine @Tree55Topz . Thanks for your support.
