### ISSUE TITLE
How to attach to existing opened windows application

### ISSUE THREAD

**Issue by danielemarinelli** [microsoft/WinAppDriver#1662]
Hello,
I am using Appium and trying to attach to an existing app, but I always receive the following error SessionNotCreated below:
![image](https://user-images.githubusercontent.com/64636628/148515348-8912bb2e-68d8-43ff-808a-6f1d3257fb53.png)

My code is same of issue #569:
![image](https://user-images.githubusercontent.com/64636628/148515540-c663800e-cc9a-4373-8035-95c8ba4820f7.png)

can someone understand why?
During the framework execution , I have open 3 applications before the one I am calling (that gives the error). 
I am using this way to open the application because it has unusual long startup time.

thanks

**Comment by Shakevg** [comment]
@danielemarinelli Looks like you are trying to attach to the incorrect window ("...is not top level window...")
Maybe the title of the main window is not the same as you expected... (you can try to look on app title in 'process explorer' app).
Also, try to find all windows by title and attach to each of them.
I suggest attaching by process #534 (comment)

**Comment by danielemarinelli** [comment]
Thanks for the answer @Shakevg. 
Probably I wasn't catching the window title.
I will try #534 too.
