### ISSUE TITLE
WinAppDriver: allow 'app' capabilities to contain paths w/ double-backslashes

### ISSUE THREAD

**Issue by jayruffing** [Microsoft/WinAppDriver#167]
# description
python does not like backslashes since they are used as escape characters. because of this, when I pass arguments to my testing framework (py.test) via the command line (eg. a Windows app path), python is adding an extra backspace to my path (see my python request below). To be clear, this issue is regarding command-line arguments specifically, in python, not a problem with python or in using python as this problem can be solved using the language. 

as a result of python adding an extra backslash to the backslashes in my windows path argument passed into the command line, WinAppDriver does not like my path containing double-backslashes and returns the following error to my request:

# WinAppDriver error:
```
{
	"status": 13,
	"value": {
		"error": "unknown error",
		"message": "An unknown error occurred in the remote end while processing the command."
	}
}
```

# my command line argument passed in to py.test:
'C:\Program Files(x86)\Microsoft Office\root\Office16.exe'

# my request sent from py.test to WinAppDriver:
```
{
	"desiredCapabilities": {
		"app": "C:\\Program Files(x86)\\Microsoft Office\\root\\Office16.exe",
	},
	"requiredCapabilities": {}
}
```

FYI if I send this same request but just remove the backslashes, this error is not encountered although obviously the path to the app is incorrect.

So, my request here is to two-fold:
1. allow me to pass Windows paths in 'app' capability for Win32 app paths which contain double-backslashes and treat them as if they contained single backslashes to play nice with cmd-line args in python (and in support of easier CI).
2. If you don't want to make this enhancement, at the very least please provide a more detailed/actionable error here when things fail with handling the app path to make troubleshooting issues here much easier.

**Comment by timotiusmargo** [comment]
Hi @jayruffing,

On the latest [v1.0-RC](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.0-RC) release, I have attempted the following two tests in C#

```c#
DesiredCapabilities appCapabilities = new DesiredCapabilities();
appCapabilities.SetCapability("app", @"C:\Windows\System32\notepad.exe");
session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities);

// and

DesiredCapabilities appCapabilities = new DesiredCapabilities();
appCapabilities.SetCapability("app", @"C:\\Windows\\System32\\notepad.exe");
session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities);
```

The test scripts above send the following JSON payload to `WinAppDriver.exe` and both of them successfully launch the **Notepad** application without any issue.

```
==========================================
POST /session HTTP/1.1
Accept: application/json, image/png
Connection: Keep-Alive
Content-Length: 93
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"desiredCapabilities":{"app":"C:\\Windows\\System32\\notepad.exe","platformName":"Windows"}}
HTTP/1.1 200 OK
Content-Length: 141
Content-Type: application/json

{"sessionId":"34F59DE0-8F02-4F33-871B-0C16B77E273A","status":0,"value":{"app":"C:\\Windows\\System32\\notepad.exe","platformName":"Windows"}}


==========================================
POST /session HTTP/1.1
Accept: application/json, image/png
Connection: Keep-Alive
Content-Length: 99
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"desiredCapabilities":{"app":"C:\\\\Windows\\\\System32\\\\notepad.exe","platformName":"Windows"}}
HTTP/1.1 200 OK
Content-Length: 147
Content-Type: application/json

{"sessionId":"80AE83AA-77BA-4987-96F1-D44BE819FA09","status":0,"value":{"app":"C:\\\\Windows\\\\System32\\\\notepad.exe","platformName":"Windows"}}
```

From what I see, Windows Application Driver indeed supports the double backslashes you mentioned above. Could you please retry your scenario and see if the error you saw came from somewhere else but the path? The latest release should also return more detailed exception on failure.
