### ISSUE TITLE
SendKeys fails to push repeated characters

### ISSUE THREAD

**Issue by sachinerandecapita** [microsoft/WinAppDriver#1675]
expected : ......gNPPumwQw......
actual sent: ......gNPumwQw......

we noticed on azure microsoft hosted agents, win app driver sendkeys sometimes skips the repeated character in string. 
(e.g. see portion of string above when PP is sent then it just takes 1 P instead of both)
Locally it works fine so it is something specific to environment where it runs. any workaround to this ? 
anything env specific stuff we should set on the pipeline agent may be a powershell script ?
Version of winappdriver is `1.2.1`

**Comment by anunay1** [comment]
Send keys has issues not only on Microsoft hosted agent but also on self agents . Which language binding are you using?

**Comment by sachinerandecapita** [comment]
We use the win app driver via appium .Net client libraries. 
Never noticed issues with sendkeys api on local machine windows 10.

**Comment by anunay1** [comment]
You can use the custom method which can be used like set Immediate text

```
public void SetText(WindowsElement editField, string text)
        {
            Thread STAThread = new Thread(
                delegate ()
                {
                    System.Windows.Forms.Clipboard.SetText(text);
                    editField.Click();
                    driver.Keyboard.SendKeys(OpenQA.Selenium.Keys.Control + "v" + OpenQA.Selenium.Keys.Control);
                });
            STAThread.SetApartmentState(ApartmentState.STA);
            STAThread.Start();
            STAThread.Join();
        }
```

**Comment by sachinerandecapita** [comment]
Hi @anunay1 
Thanks very much for suggesting alternative. 
Actually we have .net core 5 project which runs on linux as well, so clipboard api `System.Windows.Forms.Clipboard.SetText(text);` is not available. 
I'll try to put on clipboard using some powershell stuff, and update you.

**Comment by anunay1** [comment]
Which version of .net core are you using?

**Comment by sachinerandecapita** [comment]
> Which version of .net core are you using?

.NET 5

**Comment by anunay1** [comment]
Seems like that's a bug with VS2019 where in System.Windows.Form is not see at part of .net core 5. See this [this](https://developercommunity.visualstudio.com/t/systemwindowsforms-disappears-after-upgrading-to-n/1218167). Using power shell will have its own set of problems. Please let me know if you succeed.

**Comment by sachinerandecapita** [comment]
I was able to put the content on clipboard using powershell. (not using powershell sdk). 
And it works fine and consistent success both on pipeline and local machine.

Didn't use `System.Windows.Forms` because to use it project must be set to use windows .net 5     `<TargetFramework>net5.0-windows</TargetFramework>`, which wasn't suitable for us to keep things platform independent.
