### ISSUE TITLE
Compability with Appium .NET v4.3.1

### ISSUE THREAD

**Issue by owenfunkhouser** [microsoft/WinAppDriver#1679]
Is WinAppDriver 1.2.1 compatible with Appium .NET v4.3.1? We are wanting to utilize some of the search for element by image features in our tests of a .NET 4.8 WPF application.

**Comment by anunay1** [comment]
no it's not if you have to use image features then you need to use Appium desktop or Appium CLI.

**Comment by owenfunkhouser** [comment]
Yes, the drive to upgrade to v4.3.1 is to utilize the image features.
