### ISSUE TITLE
How to locate elements in URL page launched by Launcher.LaunchUriAsync？

### ISSUE THREAD

**Issue by headsea** [microsoft/WinAppDriver#1687]
We have an windows app to use Launcher.LaunchUriAsync to open a default browser to fill something. But I can't find any APIs to locate UI elements of page in the browser through WindowsDriver. Is there anyway to automate this scenario? Thanks.

**Comment by Tree55Topz** [comment]
@headsea WinAppDriver is for automating Windows apps.. you would probably just need to add in some selenium libraries and use selenium to perform these actions once the browser is launched.

**Comment by headsea** [comment]
thanks @Tree55Topz. How to connected to the launched browser need to be considered. I have find a workaround, basic idea is the same as what you said.

**Comment by Tree55Topz** [comment]
@headsea there are tons of examples of things like this online, for instance heres one https://www.tutorialspoint.com/how-to-connect-to-an-already-open-browser-using-selenium-webdriver

Just research and try different approaches, should be pretty simple.
