### ISSUE TITLE
Unable to interact with bing map elements using Appium

### ISSUE THREAD

**Issue by harshcapita** [microsoft/WinAppDriver#1688]
**Problem Description**

Appium is unable to interact with the Marker pin elements available on bing map. Even though the pins are visible on the map by a naked eye, still Appium returns false when we try to check the visibility using Displayed method. However when we do a FindElement for that map pin then that is able to find that particular map pin, but all the other methods like Displayed, Click(), etc, are unable to interact with the marker pins.

**Environment**

Appium version (or git revision) that exhibits the issue: 1.21.0
Last Appium version that did not exhibit the issue (if applicable): NA
Desktop OS/version used to run Appium: Windows 10 64-bit
Node.js version (unless using Appium.app|exe): v16.13.2
Npm or Yarn package manager: 8.1.2
Mobile platform/version under test: UWP app
Real device or emulator/simulator: Running on Windows 10 64-bit machine
Appium CLI or Appium.app|exe: Appium CLI

**Code To Reproduce Issue**

void MapMarkerInteraction()
{
// This line works fine, it is able to find the element with a name MapPin_1.
var mapMarkerElement = AppiumDriver.FindElementByName("MapPin_1");

// This line always returns false even if the Map pin is displayed on map.
bool displayed = mapMarkerElement.Displayed;

// This line throws an exception saying element not interactable.
mapMarkerElement.Click();
}

**Exception that comes when WinAppDriver is unable to click on the map pin**

OpenQA.Selenium.ElementNotInteractableException: 'An element command could not be completed because the element is not pointer- or keyboard interactable.'

Please refer to the attachment for relevant logs.
[ElementNotInteractable_ServerLogs.txt](https://github.com/microsoft/WinAppDriver/files/8150787/ElementNotInteractable_ServerLogs.txt)

**Comment by anunay1** [comment]
Is it shown in inspect?

**Comment by harshcapita** [comment]
Yes, its visible on inspect. I can see multiple properties of this map pin, but unable to interact with it.

**Comment by anunay1** [comment]
can you share what is shown in inspect, is it part of the same tree structure?

**Comment by harshcapita** [comment]
Yes its 1. Tried by using FindElements(By.Name("MapPin_1")).Count; . This returns 1 as count.

**Comment by anunay1** [comment]
Can you mouse hover to that location?

**Comment by anunay1** [comment]
As a workaround can you try: 
'''
session.Mouse.MouseMove(session.FindElementByName("Site").Coordinates);
session.Mouse.ContextClick(null);
'''

**Comment by harshcapita** [comment]
Thanks Anunay for your support. The above suggestion didn't workout as expected. But then I tried clicking using PointerInputDevice and it worked. 
Pasting below code for anyone else who face the same issue-

                var touchDevice = new OpenQA.Selenium.Appium.Interactions.PointerInputDevice(PointerKind.Touch);
                var sequence = new ActionSequence(touchDevice, 0);

                sequence.AddAction(touchDevice.CreatePointerMove(element, 0, 0, TimeSpan.Zero));
                sequence.AddAction(touchDevice.CreatePointerDown(PointerButton.TouchContact));
                sequence.AddAction(touchDevice.CreatePointerUp(PointerButton.TouchContact));
                AppiumDriver.PerformActions(new List<ActionSequence> { sequence });
