### ISSUE TITLE
How to Scroll or swipe windows 8.1 native store app running on Windows 10 desktop

### ISSUE THREAD

**Issue by seenals** [Microsoft/WinAppDriver#169]
Please refer the issue raised in Appium Issue board.
https://github.com/appium/appium-dotnet-driver/issues/172

I was referred to raise it in WinAppDriver issue board. Below is the issue faced.
---------------------------------------------------------------------------------------------
I am working on automating a Windows 8.1 store app. I am unable to perform an action of swipe or scroll using this appium dotnet driver.

My application runs on a Windows 10 PC and the application under test is a windows store app written using XAML and C#. It runs on the PC as well as on Windows tablet. For the UI automation, I'm running this in local machine ie. in the Windows 10 PC.

**Environment**
- Appium.WebDriver 3.0.0.2
- Mobile platform/version under test: Windows 8.1 store app.
- Windows 10 desktop. Deployed using Visual studio in local machine. 

**Code I tried**
-------------
IOSElement gridView = EAMUISession.FindElementByAccessibilityId("GridView");
Point location = gridView.Location;
Size size = gridView.Size;
driver.Swipe(location.X + size.Width / 2, location.Y + size.Height / 2, location.X - 1, location.Y + size.Height / 2, 3000);

This gives the below exception
-------------------------------------
Test Name:	TestMethod1
Test FullName:	EAMAutomation.EAMStructureTests.TestMethod1
Test Source: D:\BNSF_TFS\EAM\OffShore\AutomationPoCs\Version1\EAMAutomation\EAMAutomation\EAMStructureTests.cs : line 134
Test Outcome:	Failed
Test Duration:	0:00:25.4036544

Result StackTrace:
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary2 parameters) at OpenQA.Selenium.Appium.AppiumDriver1.Execute(String driverCommandToExecute, Dictionary2 parameters) at OpenQA.Selenium.Appium.AppiumDriver1.PerformTouchAction(ITouchAction touchAction)
at OpenQA.Selenium.Appium.AppiumDriver1.DoSwipe(Int32 startx, Int32 starty, Int32 endx, Int32 endy, Int32 duration) at OpenQA.Selenium.Appium.iOS.IOSDriver1.Swipe(Int32 startx, Int32 starty, Int32 endx, Int32 endy, Int32 duration)
at EAMAutomation.UnitTest1.HorizontalScroll() in ...\TestAppAutomation\TestAppAutomation\UnitTest1.cs:line 193
at TestAppAutomation.UnitTest1.TestMethod1() in ...TestAppAutomation\TestAppAutomation\UnitTest1.cs:line 177
Result Message:
Test method TestAppAutomation.UnitTest1.TestMethod1 threw exception:
System.InvalidOperationException: Missing Command Parameter: element
-----------------------------------------------------------------------------------------
Tried Touchbase as suggested by Yosef In Appium issue reply. But TouchBase class seems to handle HttpRequest and HttpWebResponse. My app is Windows native app.  I tried the below code snippet

RemoteTouchScreen touchScreen = new RemoteTouchScreen(driver);
touchScreen.Scroll(0, 100);

It compiles, but no scrolling happening. Will it scroll to the screen which is not visible on the viewport currently. I need to scroll or swipe horizontally on the screen, to make some elements to the right visible and be in viewport to perform some action on them.

Please let me know how to handle the scenario. Is the appium webdriver i'm using correct? Should I any different package? The application under test has a gridview with lot of elements and scrolls horizontally. The elements are clickable. 

Thanks & Regards,
Seena L.S.

**Comment by timotiusmargo** [comment]
Hi @seenals,

Would you please try the **TouchScroll** test scenarios below against the latest [v0.9-beta](https://github.com/Microsoft/WinAppDriver/releases/tag/v0.9-beta) release?
https://github.com/Microsoft/WinAppDriver/blob/v0.9-beta/Tests/W3CWebDriver/TouchScroll.cs

There is a horizontal scrolling example that you should be able to copy and reuse for your scenario. E.g.
```
// Perform scroll left touch action to switch from Alarm tab to WorldClock tab
touchScreen.Scroll(homePagePivot.Coordinates, -100, 0);

// Perform scroll right touch action to scroll back from WorldClock tab to Alarm tab
touchScreen.Scroll(homePagePivot.Coordinates, 100, 0);
```

**Comment by Jazzz42** [comment]
Hi @timotiusmargo . Currenty with Appium version 1.11.0 i get error 500 when trying to scroll in a WPF application on Windows 10. Does it work for you?
RemoteTouchScreen touchScreen;
touchScreen = new RemoteTouchScreen(WinDriverSession);
Assert.IsNotNull(touchScreen);
touchScreen.Scroll(0,-10);
