### ISSUE TITLE
Azure WinAppDriver seems to close immediately after beeing launched

### ISSUE THREAD

**Issue by HugoRomat** [microsoft/WinAppDriver#1691]
Here is a screenshot of what I am facing in the pipeline when closing the driver.
This leads me to think that the driver never started..

![image](https://user-images.githubusercontent.com/6485982/156758726-7fb37286-9b1b-4f70-bf14-71312f71053b.png)

Any ideas?

Hugo

**Comment by anunay1** [comment]
Can you share the yaml pipeline?

**Comment by anunay1** [comment]
Are you using WIndows-latest

**Comment by HugoRomat** [comment]
Hello @anunay1, sorry for late reply I was talking to my team about the bug. 
In fact we had to install it manually on the agent, because it seems that the command launched in the pipe do not install it.
After having installed it, and launching the command through the pipe, everything works well.
