### ISSUE TITLE
WebDriverWait on CI Agent

### ISSUE THREAD

**Issue by alinasofting** [microsoft/WinAppDriver#1693]
Hello,

  I have this code on an agent that runs winappdriver tests and I saw that this does not work without remote connection :

` var wait = new WebDriverWait(ParentMap.Window.WrappedDriver, TimeSpan.FromSeconds(seconds));
            wait.Until(ExpectedConditions.PresenceOfAllElementsLocatedBy(By
                .ClassName("MyView")));`

Does anybody know why or other code that will work in that scenario?

**Comment by Shakevg** [comment]
@alinasofting Could you describe you scenario more detail: screenshot from inspector,exe, error from WinAppDriver log, .... 
It is simple code and should work, looks like it just related with some specific on the agent. 
Can you try to save page source and save the video and check that you control exactly present on the page

**Comment by alinasofting** [comment]
It worked after a restart.
