### ISSUE TITLE
App source is not loading

### ISSUE THREAD

**Issue by Ramkrish26** [microsoft/WinAppDriver#1697]
When I try to create a session for calculator application, I am able to locate the element like below:

![image](https://user-images.githubusercontent.com/39208833/160806153-0f89da45-5656-449d-b9aa-9a33fc14403c.png)

But when I try to open another windows application, its not loading the app source or its loading for long time

![image](https://user-images.githubusercontent.com/39208833/160806419-d3a50c70-248d-4be9-936d-cb507c169d81.png)

**Comment by anunay1** [comment]
Better use inspect.exe
