### ISSUE TITLE
.ini file is not loading when launching the application via appium

### ISSUE THREAD

**Issue by Ramkrish26** [microsoft/WinAppDriver#1699]
Our desktop application has .ini file that contains the basic settings that are loaded when launching the application.
When I manually launch the application, settings in .ini file is getting loaded where as when I try to launch the application via appium desired caps, the settings are not loaded. 

Appium version: 1.22.3

desired_caps = {
    "deviceName": "<device name>",
    "platformName": "Windows",    
    "app": "<path of the application>"    
}

**Comment by Tree55Topz** [comment]
2 things to try

1. Try including another capability of "appWorkingDir" and then specify the parent folder that your application.exe is found in. Maybe that will pull in those settings? Havent had to use .ini files for our application but I do know that I needed to include this capability as well as the "app" capability.
2. Are these essentially just optional command line arguments? You can add these with the "appArguments" capability

**Comment by Ramkrish26** [comment]
Great!! Thanks @Tree55Topz  @Shakevg . Adding the appWorkingDir works for me.
{
    "deviceName": "",
    "platformName": "Windows",    
    "app": "",
    "appWorkingDir": "" 
}
