### ISSUE TITLE
What diffirence to Winium?

### ISSUE THREAD

**Issue by clicman** [Microsoft/WinAppDriver#17]
Hello. There is an another implimentation: https://github.com/2gis/Winium
What`s the difference?

**Comment by xied75** [comment]
Their Readme is confusing:

>  tested on emulators (currently it supports only testing of Windows Phone apps).

So looks like they don't really support UWP yet?

**Comment by clicman** [comment]
Dont know about phone apps, but Desktop apps testable well.

**Comment by xied75** [comment]
That's why I said it's confusing, because all I get is that they DON'T support UWP except phone app. I can't speak for others, but I develop for Windows 10 UWP and this is the only thing that support it.

**Comment by yodurr** [comment]
The WinAppDriver roadmap includes Phone and XBox
