### ISSUE TITLE
Does drag and drop in app and cross app be support for none windows store application？

### ISSUE THREAD

**Issue by congzhangzh** [Microsoft/WinAppDriver#170]
As title。

**Comment by holphi** [comment]
Answer your 2nd question:

I used to use Appium for Android automation, I had same requirements to interactive with different apps, however, the Appium doesn't support it, as WinAppDriver shares the same interface with Appium, I don't think it WinAppDriver can do this.

**Comment by hassanuz** [comment]
This can be done through using a Desktop session and a supported Win32, UWP, WinForms, WPF app. Please see sample [here](https://github.com/Microsoft/WinAppDriver/blob/8bb91f06ef9cbc798c88099a586c15d74fd17870/Tests/WebDriverAPI/Mouse.cs#L117).

If you have any further questions please feel free to reopen!
