### ISSUE TITLE
Failed to start winappdriver session for Win app associated with Windows Store Account for push feature

### ISSUE THREAD

**Issue by binchu** [microsoft/WinAppDriver#1709]
I have WinAppDriver 1.2.1.0 and a Windows UWP app installed on my Windows pc. I have a unit test project to test this app. Here is the code to initialize the winappdriver session:
                appCapabilities = new DesiredCapabilities();
                appCapabilities.SetCapability("app", packageID));
                WinAppSession = new IOSDriver<IOSElement>(new Uri(AppDriverUrl), appCapabilities);
Here "packageID" is the $package.PackageFamilyName + "!" + $package.Name returned from PowerShell, such as "com.pact.testapp1.win_bzbj8h50hftv4!com.pact.testapp1.win". 

It works very well. Then I want to test the Push function for this app. So I associate this app with my Windows Store account. After association, it will generate a new package name. So I use the new package name to run the code, it failed to initialize the winappdriver session with the error: This app does not support the contract specified or is not installed. (Exception from HRESULT: 0x80270254). The new packageID returned from PS is like this: 25940TestDT.TestPushApplicationForApp_234q43rvecrsg!25940TestDT.TestPushApplicationForApp.

I searched the issued reported in this repository but none matched my scenario - works for app but failed for app with Push. I also googled the error but still not fixed this issue. Do you have any clue about this problem? Is there any string length limitation for the packageID passed to SetCapability method since the new packageID is too long? Thanks.

**Comment by anunay1** [comment]
@DHowett Can you please help?

**Comment by liljohnak** [comment]
If the path becomes too long have you used the `appWorkingDir` arguement?

Example:
```
            var exe = System.IO.Path.Combine(System.IO.Directory.GetCurrentDirectory(), @"..\..\Sandbox.win\net5.0\sandbox.exe");
            var appCapabilities = new DesiredCapabilities();
            appCapabilities.SetCapability("app", exe);
            appCapabilities.SetCapability("appArguments", @"");
            appCapabilities.SetCapability("appWorkingDir", @"");
            var sandboxSession= new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), appCapabilities);
```

**Comment by binchu** [comment]
@liljohnak it is not the path string too long issue. I have resolved this problem.

According to [this](https://docs.microsoft.com/en-us/windows/configuration/find-the-application-user-model-id-of-an-installed-app), I got the correct AUMID and winappdriver session could be initialized successfully. Thanks.
