### ISSUE TITLE
Empty Element String Returned for Element that exists

### ISSUE THREAD

**Issue by davidlandreman** [Microsoft/WinAppDriver#171]
This is being ran against an older win32 application with tabs across the top of the app.  Goal is to click on a specific tab.

My expectation would be that if WinAppDriver didn't think an element existed it would return an empty array instead of [{"ELEMENT": ""}].  In other cases I have tested I usually get an empty array back if the element does not exist.

==========================================
POST /session/93A8B412-5BEB-450B-A90F-FD84DD0FB3A1/element/42.3474156/elements HTTP/1.1
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
Content-Length: 54
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_121)

{"id":"42.3474156","using":"name","value":"Search By"}
HTTP/1.1 200 OK
Content-Length: 88
Content-Type: application/json

{"sessionId":"93A8B412-5BEB-450B-A90F-FD84DD0FB3A1","status":0,"value":**[{"ELEMENT":""}]**}

**Comment by Korop** [comment]
I can confirm that issue exist in  my case too. That happens with app store confirm purchase dialog("Store Purchase App") when test clicks on "confirmButton"  and waits for disappearing of the dialog.

**Comment by Korop** [comment]
We detected that the issue can happen even when the purchase confirmation page is created. So it is an stale related issue. Look like that the driver should return empty array or STALE_ELEMENT_REFERENCE error.
```.add(new KnownError(STALE_ELEMENT_REFERENCE, "stale element reference", 400, ```
StaleElementReferenceException.class, true, true)).

For example we find "PriceContainer" text element.
``` java
//Check that that this will be test order = Price is 0
 wait.until(ExpectedConditions.textToBePresentInElementLocated(AccessibilityId("PriceContainer"), "$0.00"));
```

**Comment by timotiusmargo** [comment]
There have been some improvement on tracking the stale element and finding elements in WinAppDriver [v1.0-RC](https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/README.md#windows-application-driver). Would you please retry your scenario?
