### ISSUE TITLE
Cannot install on Windows Server 2019 Azure VM

### ISSUE THREAD

**Issue by WindowsWrangler** [microsoft/WinAppDriver#1714]
On a VM - Windows Server 2019 version 6.3.9600

Added group policy to domain, enabling:

Computer Configuration | Policies | Administrative Templates | Windows Components | App Package Deployment
-Allow all trusted apps to install
-Allow development of Windows stores apps

Windows Application Driver Setup fails with the message:

"Windows Application Driver is only supported on Windows 10, Windows  Server 2016, or higher."

How do we make this work in order to replace Coded UI Tests?

**Comment by DHowett** [comment]
Which version of WinAppDriver are you trying to install?

**Comment by WindowsWrangler** [comment]
I tried both Windows Application Driver 1.2.1 and 1.2.99 x64. I received the same message in both.

**Comment by WindowsWrangler** [comment]
1.2.1 Installer succeeds on Windows Server 2016 Azure VM (Version 10.0.14393)

**Comment by DHowett** [comment]
I am somewhat confused about the Windows versions here:

The version you mentioned, Windows Server with a build number of "**6.3**", is based on Windows 8.1. As far as I know, the last version of Windows Server based on Windows 8.1 was _Windows Server 2012_.

"Windows Server 2016" (10.0.14393) is based on Windows 10.

WinAppDriver requires a Windows build number of 10.0.14393 or higher.

**Comment by WindowsWrangler** [comment]
OK my bad. All of our labs use Windows Server 2019 - except this one. When I reviewed the creation scripts, I discovered the author had specified an old server version.
