### ISSUE TITLE
Unable to click on an element using xpath from WAD UIRecorder

### ISSUE THREAD

**Issue by kaj10477** [microsoft/WinAppDriver#1716]
I am trying to click on a button that has no name and accessibility ID, so I used WAD UI recorder to get XPATH, but even that is not detecting the element. 

I am adding **screenshot** of inspect.exe and WAD UIRecorder 
**I am trying to click on button-1**
![Screen Shot 2022-05-16 at 08 38 29](https://user-images.githubusercontent.com/53016566/169146986-a54e2e3f-c53f-4370-b27b-f2f5bdf06370.png)

**Code:** 
chart_categories = self.driver.find_element_by_xpath(".//*[@Name='ArcGIS Insights']/Group/Group/Group/Group/Group/Group/Group/Window/Button")
        chart_categories.click()

**Error**
<img width="1392" alt="Screen Shot 2022-05-18 at 13 18 28" src="https://user-images.githubusercontent.com/53016566/169148579-96a7fa54-1a96-4ce8-a13e-a864ae2d71bc.png">

**Comment by igorrecioh** [comment]
Hi @kaj10477,

not sure if you introduced a typo when writing the issue but it could be that the N for Name should be capital letter:
- Your XPath:
```python
chart_categories = self.driver.find_element_by_xpath(".//*[@name='ArcGIS Insights']/Group/Group/Group/Group/Group/Group/Group/Window/Button")
```

- With capital N for name:
```python
chart_categories = self.driver.find_element_by_xpath(".//*[@Name='ArcGIS Insights']/Group/Group/Group/Group/Group/Group/Group/Window/Button")
```

**Comment by kaj10477** [comment]
Hi @igorrecioh Thank you for your quick response. I have tried it with capital N. It's just that when I write it in here, It convert's 'N' to 'n'. Anyways, it's giving me the same error even with the 'N'. 

**Here's the screenshot of the UIRecorder, inspect, and my code in PyCharm
<img width="1680" alt="Screen Shot 2022-05-19 at 09 06 43" src="https://user-images.githubusercontent.com/53016566/169347617-ea8c3263-36a4-4753-9238-ddf63aaf7dbe.png">


I am not sure if I am missing anything in the xpath that I am using.

**Comment by igorrecioh** [comment]
Hi @kaj10477! Happy to help you,!

I would try this XPath, just to check.
```python
chart_categories = self.driver.find_element_by_xpath("//Document[@Name='ArcGIS Insights']/Group/Group/Group/Group/Group/Group/Group/Window/Button")
```

Anyway, it is strange, it should work with yours too. I would recommend you to try with a long sleep before searching the problematic xpath, just to verify that the application is where you need. Sometimes test is too fast and application response is not so quick... Just thinking loud :S

**Comment by kaj10477** [comment]
Hi @igorrecioh I was able to get to the dropdown button using below xpath using following child. Strangely none of the XPATH worked from UIRecorder. Thank you so much for your help. I'll close this issue. 

driver.find_element(by=By.XPATH, value="//*[@Name='Select data to create a chart.']/following-sibling::*")
![Screen Shot 2022-05-24 at 10 46 42](https://user-images.githubusercontent.com/53016566/170100100-c021e47d-c329-4ad5-b04b-3120c603a128.png)
