### ISSUE TITLE
Clicking app screen coordinates from a Python script

### ISSUE THREAD

**Issue by rg-software** [Microsoft/WinAppDriver#172]
Hello,
I have an application that consists of a single drawing surface only (a computer game), and I want to click the given coordinates from a Python script. Is it possible?

I tried creating TouchAction(session) instances, but this approach does not work, and it seems that only C# samples show how to perform mouse clicks. Thanks!

**Comment by yodurr** [comment]
Hi, we're enabling TouchActions now in WinAppDriver 1.1.  The Python library's TouchAction should work with WinAppDriver 1.1.

**Comment by hassanuz** [comment]
Hi @rg-software,

[WinAppDriver v1.1](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.1) supports TouchActions - if you are facing any issues / bugs with is, please feel free to create a new ticket with the relevant details.

Thanks!
