### ISSUE TITLE
[Windows 10  Tab] Cordova App: Not all the elements are recognized

### ISSUE THREAD

**Issue by maesiva** [Microsoft/WinAppDriver#173]
Hi All,

I'm trying to automate a Cordova based Windows 10 Mobile Hybrid app.

Win App Driver does not recognise few elements on the screen. (inspect.exe does not give any usable property for such elements)

Below is my sample code for Sign in page, where id and password are working, but not the Sign In button:
```
	IOSDriver dr;
	DesiredCapabilities caps = new DesiredCapabilities();
	caps.setCapability("app", "CompanyName.AppName_es6cz9x8cqxbg!com.company.application");
	dr = new IOSDriver(new URL("http://10.102.173.184:4723"), caps);
	dr.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);

	//Login 
	dr.findElement(By.name("Username")).sendKeys("user"); //works!
	dr.findElement(By.name("Password")).sendKeys("pwd"); //works!
	
       //dr.findElement(By.id("btnlogin")).click(); // id taken from developer // fails
	//dr.findElement(By.name("Sign in")).click(); //Sign In button is not identified. Click manually!

	//Print page source
	System.out.println("dr.getPageSource() @ Login page:\n" + dr.getPageSource());
```

Page source xml contain the information about the Username and Password Edit elements. but, there is no information on Sign In button. Id of Sign In button was taken from the developer. But, WAD fails to identify the button. Below is the logs:

> org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters...
> Driver info: io.appium.java_client.ios.IOSDriver
> *** Element info: {Using=id, value=btnlogin}
> 

I tried to get context handles (to try to switch to WEB_VIEW context), but, getContextHandles Command is not recognized by WAD (org.openqa.selenium.UnsupportedCommandException).

Does WAD driver support Cordova based hybrid apps on windows 10 Mobile? 

I highly appreciate any inputs on getting through this. Please let me know if any further information is required.

**Comment by maesiva** [comment]
A related query:

findElement(By.name("Sign in")).click() >>> works
findElement(By.xpath("//*[@name='Sign in']")).click  >>> doesn't work

After investigating the login screen's html, it seems WAD is using the "placeholder" attribute value, but not the actual "name" value. Same thing was observed for other UI elements for my app. 

inspect.exe also seem to display the "Name" value from "placeholder" attribute in the page. And inspector doesn't distinctly identify the elements that doesn't have placeholder values.

Please correct me if I'm doing it wrong.

**Comment by paulcam206** [comment]
Are you sure that the attribute is `name` and not `Name`?

**Comment by maesiva** [comment]
@paulcam206 
Yes.

**Comment by paulcam206** [comment]
Can you send us the result of getting the source of the app?

**Comment by maesiva** [comment]
Please share your email id or send me a test email at maesiva@gmail.com
Thanks.

**Comment by paulcam206** [comment]
The proper xpath query is probably `//*[@Name='xyz']`, since it matches against what you see in Inspector.

**Comment by maesiva** [comment]
Ok. I will check with @Name. 

I emailed the Screen Details xml. 
Please let me know if any further details required to look into “not all the elements are recognized”.

**Comment by hassanuz** [comment]
Please create new issue if this still persists on the latest version of WinAppDriver.
