### ISSUE TITLE
how to check listview count?

### ISSUE THREAD

**Issue by YeonwooJeong** [microsoft/WinAppDriver#1731]
I want to find out the number of files in Windows Explorer.
How do you figure it out?
I found the xpath path, but I don't know which function to use.

![image](https://user-images.githubusercontent.com/8816386/172356089-f60290e5-c752-44d8-ae3d-f91fce755ff6.png)

my code
![image](https://user-images.githubusercontent.com/8816386/172356388-736ac35e-5402-4d58-b7e5-637b4ddd4689.png)

**Comment by Tree55Topz** [comment]
@YeonwooJeong you want to use Session.findElementsByXPath. This should have a Count() function or something similar. (I use C#, so might be a bit different for you)

Big difference between findElement and findElements. Hope that helps

**Comment by YeonwooJeong** [comment]
> [YeonwooJeong](https://github.com/YeonwooJeong) Your method will find just the first folder control. Are you using Java? Try next code `i = Session.findElementsByXPath(folder_path).size();`

Thanks bro
