### ISSUE TITLE
Unable to inspect outlook using inspect.exe

### ISSUE THREAD

**Issue by vinothannamalai** [Microsoft/WinAppDriver#174]
I am trying to automate email configurations for networking team. I am unable to inspect outlook using inspect.exe . Getting " cannot get object from point: [Error: From Point : hr=0xFFFFFFFF8070005 - Access is denied.] 

Also I tried to inspect few elements for Cisco jabber . I was not getting exact elements for few windows in it. 

Could anyone help me on this issue. 

Thanks in advance.

Vinoth

**Comment by yodurr** [comment]
Which version of Outlook are you using?

Inspect seems to see the Outlook 2016 UI tree fine for me.  Probably something about your particular scenario or version of Outlook.  Can you share more about what UI elements your trying to interact with?

**Comment by vinothannamalai** [comment]
I use outlook 2013 for my testing. 

I am talking about uiautomation elements . When I inspect the window of outlook, it says  'access is denied ' error . 

I might have missed installation of Microsoft SDK completely. Would that cause issue for me ?

**Comment by vinothannamalai** [comment]
I am able to inspect outlook now after updating windows SDK. But I face another problem in inspecting. I am able to see most of the attributes shown in inspect.exe are not working.  Element which has automation id only works fine . Could you please suggest me how to write xpath for Windows application

**Comment by vinothannamalai** [comment]
I am able to inspect outlook now after updating windows SDK. But I face another problem in inspecting.  Most of the attributes shown in inspect.exe are not working.  Element which has automation id only works fine . Could you please suggest me how to write xpath for Windows application.

It is not working for name attribute as well. Which attribute will work for winappdriver. And also put some samples for outlook automation . 

Thanks in advance

**Comment by vinothannamalai** [comment]
![img_20170404_174125_hdr](https://cloud.githubusercontent.com/assets/7838752/24656292/88c0f4c4-195f-11e7-9e1d-998e58e79ddd.jpg)

**Comment by vinothannamalai** [comment]
![img_20170404_174125_hdr](https://cloud.githubusercontent.com/assets/7838752/24658005/04367380-1966-11e7-98af-89e4be9d6a24.jpg)

**Comment by yodurr** [comment]
Glad to hear inspect is working now.

For how to map attributes in inspect to XPath queries please use the table at the bottom of the readme, the Inspecting UI Elements section, as a reference.

If you have a particular xpath query that isn't working please open a new issue with more details on that.  Thanks.

**Comment by shaktim121** [comment]
Hi @yodurr ,
I am trying to spy on the objects of one of my application, and inspect.exe shows the same error:
Cannot get object from point:
[Error: FromPoint: hr=0xFFFFFFFF80070005 - Access is denied.]

While inspect is working with other WPF and Windows applications. To my surprise, neither UIAVerify nor any other Recorder works on that windows application.

What can be done for this? Is there anything from the Application side which is preventing from doing so?
Thanks
