### ISSUE TITLE
Appium WebDriver NuGet package getting outdated

### ISSUE THREAD

**Issue by RameshR66** [microsoft/WinAppDriver#1755]
Hello,
We have created an application to automate windows application using Appium. Our code uses the following NuGet Packages as mentioned below - 
- Appium.WebDriver [_Installed and Latest Version_ - 4.3.1, _Last Release Date_ - 14 Jan 2021]
- Selenium.Support [_Installed Version_ - 4.2.0, _Latest Version_ - 4.3.0, _Last Release Date_ - 24 Jun 2022]
- Selenium.WebDriver [_Installed Version_ - 4.2.0, _Latest Version_ - 4.3.0, _Last Release Date_ - 24 Jun 2022]

When we upgraded Selenium packages to latest versions, the Appium codes were shown as error. It seems some of the driver components in Selenium have been changed and that their latest changes don't support the latest version of Appium web drivers. 

Also, Git repository source code for Appium web driver only consumes Selenium version 3.141.0 which is a much older version, when upgraded to 4.2.0 leaves most of the code in Appium web driver either deprecated or obsolete. 

![image](https://user-images.githubusercontent.com/106594946/176595684-4b22bc03-da50-4b61-8eb7-f3ec1f141353.png)

Also, we noticed there is a beta release for Appium drivers as shown below - 

![image](https://user-images.githubusercontent.com/106594946/176596130-03756ccb-e122-4124-8102-e529f351235d.png)

Note sure entirely if this is the right approach to keep packages up to date in our applications. 

**Will we ever get any official newer release for Appium Web Driver NuGet package? Any news regarding this would be nice.**  
Thanks.

**Comment by ChristoWolf** [comment]
`Appium.WebDriver` is completely separate from WinAppdriver.
They have just released a bugfix release a few days ago though, see [here](https://github.com/appium/appium-dotnet-driver).

**Comment by RameshR66** [comment]
@ChristoWolf  
Yes, WinAppDriver and Appium.WebDriver are different. As stated above, our concern is only with Appium.WebDriver dependency with Selenium packages. It seems Appium has stopped releasing newer versions to make it compatible with the latest selenium releases. Detailed description is mentioned above as well. 
Does this latest bugfix release has anything to do with support for selenium latest versions?

**Comment by RameshR66** [comment]
Its explicitly stated in the Appium.WebDriver NuGet Gallery that the package is dependent on the specific version of Selenium. So, I think it is not recommended to upgrade any selenium drivers in our applications and it is a risk that we take if we need Appium.WebDriver package. 

![image](https://user-images.githubusercontent.com/106594946/177265949-398530de-c118-410e-a828-88c50b7d79ab.png)

**Comment by ChristoWolf** [comment]
@RameshR66: I still don't see the relevance to WinAppDriver.

**Comment by RameshR66** [comment]
@ChristoWolf 
My apologies, I just now noticed I raised the issue under WinAppDriver section. Thank you for pointing that out. I will raise the issue accordingly in the correct section of the forum. Thanks.
