### ISSUE TITLE
Is there a way i can launch an application which is pinned to taskbar 

### ISSUE THREAD

**Issue by LisaAga** [microsoft/WinAppDriver#1759]
Hi Team,

I have a scenario where i need to launch an application from task bar and then at end i also want to remove it from taskbar and validate if its removed . Is there any way i can do it ?

Similar to this https://github.com/Microsoft/WinAppDriver/issues/78 , but for application pinned to taskbar i cant see any info in inspect

**Comment by anunay1** [comment]
Have you tried anything?
