### ISSUE TITLE
Movies and TV app play hdr video (encoded by h264) Problem

### ISSUE THREAD

**Issue by ByteYIFFF** [microsoft/WinAppDriver#1768]
Movies and TV app play hdr video (encoded by h264), and there is an abnormal color problem, but the picture is normal when played with potplayer or dxva checker. May I ask if this is an extra feature made by film and television for this type of video?
Supplement: The movie and TV app  playback screen is abnormal under the nvidia graphics card environment, and the movie and TV app playback screen is normal under the Intel graphics card environment.(https://drive.google.com/file/d/1TRXRHig7XPdp-K-vj4UfpijN4AbSYqly/view?usp=sharing)

**Comment by anunay1** [comment]
How is it related to WAD?

**Comment by DHowett** [comment]
It doesn't seem to be related to WinAppDriver. Thanks @anunay1 :)
