### ISSUE TITLE
driver.window_handles return null some time?

### ISSUE THREAD

**Issue by congzhangzh** [Microsoft/WinAppDriver#177]
As title, I try to do some wait.until for a pop up be show, but the driver.window_handles return empty

**Comment by timotiusmargo** [comment]
Hi @congzhangzh, would you be able to provide a sample test that reproduce the issue you saw?

**Comment by timotiusmargo** [comment]
There have been some improvement on enumerating all top level windows in WinAppDriver [v1.0-RC](https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/README.md#windows-application-driver). Would you please retry your scenario and provide steps to reproduce if you still encounter the same issue?
