### ISSUE TITLE
The WinAppDriver needs an open the VM, it can not be locked in order for the WinAppDriver to be able to click Buttons.

### ISSUE THREAD

**Issue by rehamkotb** [microsoft/WinAppDriver#1771]
Can't run the Azure pipeline while the VM locked, the run will be failed. (display internal error & App will no be opened)
while when run the pipeline with open VM the project will run successfully

**Comment by Shakevg** [comment]
@rehamkotb You should configure the azure agent according to documentation
https://github.com/microsoft/WinAppDriver/blob/master/Docs/CI_AzureDevOps.md#recommended-reads

**Comment by rehamkotb** [comment]
@Shakevg 
I've sent the below command in the pipeline and this fix the issue

tscon $sessionID /dest:console
