### ISSUE TITLE
Unable to get the parent of an element

### ISSUE THREAD

**Issue by ritusenleo** [microsoft/WinAppDriver#1777]
Tool: WinAppdriver

Objective of my test is to get the name of 'Desktop' pane where the application is open, hence trying to get the parent of an element:

the parent of an element its returning null..

var parent = _driver.Current.FindElementByXPath("//[@RuntimeId= "+element.Id+ "]/parent::")

any solution plz.

**Comment by anunay1** [comment]
Can you be a little more specific? more or less the runtime id are dynamic.

**Comment by ritusenleo** [comment]
@anunay1 

under inspect.exe the dropdown list of the application appears under the 'Desktop 1' pane, which is outside the application (GetTheList.png). Hence unable to access this dropdown list.

To achieve this, trying to use the logic : -  Get the parent/ancestors (Ancestors.png) of any element of the application, and thus fetch the desktop pane name where the application is open and then try to access  the list under desktop pane. But failed to get the parent of the element. 

I am also not sure if this logic will work.

 [.png attached
![Ancestors](https://user-images.githubusercontent.com/52369330/186648110-721e39c4-a367-4501-9c30-34bf9f928514.png)
![GetTheList](https://user-images.githubusercontent.com/52369330/186648132-17af6857-0a84-4099-a256-2dcb7940a4f9.png)
]

**Comment by anunay1** [comment]
oh ok. Then you need to create a root session and jumped to the list, to select the item in the list. Based on the language binding please check the below issues. 
if C# see https://github.com/microsoft/WinAppDriver/issues/1341 
if python check https://github.com/microsoft/WinAppDriver/issues/1646

**Comment by ritusenleo** [comment]
@anunay1 :Its not very clear to me from here #1341, if you kindly assist..
i have a driver session:
 private WindowsDriver<WindowsElement> GetCurrentDriver()
        {
                var appiumOptions = new AppiumOptions();
                appiumOptions.AddAdditionalCapability("app", _applicationNameOrPath);
                appiumOptions.AddAdditionalCapability("appArguments", _applicationArg);
                appiumOptions.AddAdditionalCapability("deviceName", "WindowsPC");
                string appSetting = _configurationDriver.Configuration["winAppUri"];
                var remoteAddress = new Uri(appSetting);
                var driver = new WindowsDriver<WindowsElement>(remoteAddress, appiumOptions);
                driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(1.5);
                return driver;
        }

**Comment by anunay1** [comment]
Look into the closed issues i have given the code.

**Comment by ritusenleo** [comment]
could you please share the link of the code in c#

**Comment by anunay1** [comment]
Search in the closed bug with Id anunay1

**Comment by anunay1** [comment]
Check #1246

**Comment by ritusenleo** [comment]
@anunay1 

I made different root driver session:
 private WindowsDriver<WindowsElement> GetRootDriver()
        {
            
            var appiumOptions = new AppiumOptions();
            appiumOptions.AddAdditionalCapability("app", "Root");
            string appSetting = _configurationDriver.Configuration["winAppUri"];
            var remoteAddress = new Uri(appSetting);
            var driverRoot = new WindowsDriver<WindowsElement>(remoteAddress, appiumOptions);
             Assert.IsNotNull(driverRoot);
            return driverRoot;

            //var RSWindow = driverRoot.FindElementByName(mainWindowTitle);
            //var RSTopLevelWindowHandle = RSWindow.GetAttribute("NativeWindowHandle");
            //RSTopLevelWindowHandle = (int.Parse(RSTopLevelWindowHandle)).ToString("x");

            //DesiredCapabilities appcapabilities = new DesiredCapabilities();
            //appcapabilities.SetCapability("appTopLevelWindow", RSTopLevelWindowHandle);
            //driver = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appcapabilities);`


        }
private WindowsDriver<WindowsElement> GetCurrentDriver()
        {
                var appiumOptions = new AppiumOptions();
                appiumOptions.AddAdditionalCapability("app", _applicationNameOrPath);
                appiumOptions.AddAdditionalCapability("appArguments", _applicationArg);
                appiumOptions.AddAdditionalCapability("deviceName", "WindowsPC");
                string appSetting = _configurationDriver.Configuration["winAppUri"];
                var remoteAddress = new Uri(appSetting);
                var driver = new WindowsDriver<WindowsElement>(remoteAddress, appiumOptions);
                driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(1.5);
                return driver;
        }

and then trying to get the list : 

var list=_driverRoot.Current.FindElementByXPath("//*[@LocalizedControlType='list'");

its throwing eror: error: The HTTP request to the remote WebDriver server for URL http://127.0.0.1:4723/session/A6944998-F547-42DC-BF7A-EAEF2577A9B5/element timed out after 60 seconds. (92.1s)

Any suggestion on this please?

**Comment by anunay1** [comment]
try this _driverRoot.FindElementByName("Listname").
               FindElementsByTagName("ListItem");

Try not to use the xpath it's terribly slow.

**Comment by ritusenleo** [comment]
@anunay1 
tried using : 
            var list = _driverRoot.Current.FindElementByTagName("List");
            var count = list.FindElementByTagName("List item");
            Console.WriteLine("Count=" + count);
but throwing message: The HTTP request to the remote WebDriver server for URL http://127.0.0.1:4723/session/4C8F5B41-F302-4F5B-96A0-755A776DE583/element timed out after 60 seconds. -> The operation has timed out.

Two screenshots from inspect.exe. 
The 'List' is named as 'list' and 'List Item' as 'list item'
![List](https://user-images.githubusercontent.com/52369330/186880412-a78b7eef-23ee-47d5-923b-22385e81baba.png)
![GetTheList](https://user-images.githubusercontent.com/52369330/186880355-c6fa80bd-d7d1-4dc9-97b2-01e5a6676eee.png)

**Comment by anunay1** [comment]
Can you set up a teams call?

**Comment by ritusenleo** [comment]
can we do it on skype plz...

**Comment by anunay1** [comment]
@ritusenleo Based on the communication, if you cannot show me the application, I will not be able to help now or even in future.

**Comment by ritusenleo** [comment]
@anunay1 As per the communication, the suggestion which you gave solved my problem.
Thank you very much.
var list = _driverRoot.Current.FindElementByClassName("ComboLBox");
var count = list.FindElementsByTagName("ListItem").Count;

Sure will look into it from next time.

**Comment by anunay1** [comment]
I am in the meeting start the call.

**Comment by ritusenleo** [comment]
Sorry Ananya,
At present I am in my office meeting... Any meeting request you got from my
end??
