### ISSUE TITLE
Cannot Run Selected Tests

### ISSUE THREAD

**Issue by gaurang011** [Microsoft/WinAppDriver#178]
OUTPUT

------ Run test started ------
An exception occurred while invoking executor 'executor://mstestadapter/v2': Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
========== Run test finished: 0 run (0:00:00.4866497) ==========

**Comment by gaurang011** [comment]
Sorted! Had to update NuGet package.

**Comment by yodurr** [comment]
Hi, which version of Visual Studio are you using?
Is this one of the sample projects you're loading?

**Comment by gaurang011** [comment]
Hi,
Thanks for the quick reply.
I'm using VS 2015 Community version & yes I'm running NotepadTest (C#)

**Comment by jcmcbeth** [comment]
I'm not sure if this is related:
https://developercommunity.visualstudio.com/content/problem/14673/unit-test-fail-cannot-load-microsoftvisualstudiote.html

But updating the MSTest.TestAdapter and MSTest.TestFramework nuget packages to the latest version fixed this issue.

**Comment by timotiusmargo** [comment]
Closing this issue as @jcmcbeth's solution seems to fix it.
