### ISSUE TITLE
Arrow keys don't work (just get symbols)

### ISSUE THREAD

**Issue by mitchcapper** [Microsoft/WinAppDriver#18]
try with something like notepad:

```
session.FindElementByClassName("Edit").SendKeys(Keys.Up);
session.FindElementByClassName("Edit").SendKeys(Keys.ArrowUp);
session.FindElementByClassName("Edit").SendKeys(Keys.PageUp);
```

You will get 3 symbols.

**Comment by timotiusmargo** [comment]
Hello Mitch. Thanks for the feedback and for your patience. We recently released [v0.6-beta](https://github.com/Microsoft/WinAppDriver/releases/tag/v0.6-beta) that should address the issue above. The scenario is tested on **Notepad** in https://github.com/Microsoft/WinAppDriver/blob/v0.6-beta/Tests/W3CWebDriver/ElementSendKeys.cs#L123
