### ISSUE TITLE
WPF / .Net Forms

### ISSUE THREAD

**Issue by claytonneal** [Microsoft/WinAppDriver#180]
Hello,
Does WinAppDriver support WFP / .Net Forms / MSAA ui automation? (using ui automation under the hood perhaps).
Thanks

**Comment by yodurr** [comment]
Yes, please let us know if you run into any trouble.  WinAppDriver does use UI Automation API's under the hood.  
Thanks!

**Comment by claytonneal** [comment]
Many thanks for the reply, and hats off to Microsoft for this!
