### ISSUE TITLE
is winappdriver support to windows 11

### ISSUE THREAD

**Issue by SireeshaDuvvuri** [microsoft/WinAppDriver#1803]
Hello Team,

We were looking for a window application automation tool to test. Came across WinAppDriver by Microsoft and we thought it would be fitting for our automation development. But before we proceed, would like to know more about the forecast for this tool.

1. Will there be frequent releases and support for the tool in the future?
2.  Will there be any change in Licensing for the tool?
3. Is it support windows 11?

**Comment by DHowett** [comment]
WinAppDriver currently supports Windows 10 _and Windows 11_. There is not expected to be any change in the licensing.
I do not have additional information about the release frequency or roadmap at this time. I apologize.

**Comment by Knight-Shen** [comment]
Is it support windows 11?

**Comment by liljohnak** [comment]
It works in Windows 11.

**Comment by xuconghua** [comment]
But it doesn't goes well in windows 11, exception:"Bad capabilities. Specify either app or appTopLevelWindow to create a session"
does anyone know why?

**Comment by noobcoconut** [comment]
> But it doesn't goes well in windows 11, exception:"Bad capabilities. Specify either app or appTopLevelWindow to create a session" does anyone know why?

if you are using appium, afaik appium version mismatch causes this problem. I m using windows 11 and solved it by downgrading appium to 4.0.0
