### ISSUE TITLE
The HTTP request to the remote WebDriver server

### ISSUE THREAD

**Issue by skotian2** [microsoft/WinAppDriver#1808]
OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:49719/session/fd495cece53f3013b447f334d2658916/elements timed out after 60 seconds. ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request.

Selenium 4.5.1 ( .net Core ) - Any resolution

**Comment by ChristoWolf** [comment]
Can you give a bit more context?

**Comment by skotian2** [comment]
Test method  exception: 
OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:49707/session/16df674e735c388d463d5ae9f4ba12cf/elements timed out after 60 seconds. ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request.. ---> System.Net.Sockets.SocketException: The I/O operation has been aborted because of either a thread exit or an application request.

**Comment by skotian2** [comment]
> Can you give a bit more context?

We are running a selenium script and execution fails after 2-3min

**Comment by ChristoWolf** [comment]
Excuse me, but you didn't really give more context.
- Is the timeout that you configured in the capabilities 60 seconds?
- Have you tried executing the request manually?
- What kind of element are you targeting there?
- Which browser do you target?
- Does it happen in all browsers?

**Comment by ChristoWolf** [comment]
> driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(60);

So this should not be related to the problem, but I would in general advice against setting (high) implicit timeouts.
Instead, it would be best to explicitly wait for certain things if needed.

> Have you tried executing the request manually? - Yes

So, same outcome?
Did you then attempt to inspect the affected element manually before and after the timeout triggers?

> Element Targeted - XPATH element , Web Based Application

I figured.
What I meant was what kind of UI element that is, e.g. pop-up, but, etc.?

> Other Browser - I need the test to be run in Chrome only.

I think it could be worth a shot, but let's try some other stuff first.

Can you share any other stuff that might be helpful for debugging? E.g. screenshots, page source dumps, logs, request logs?

**Comment by skotian2** [comment]
Thanks for your help ChristoWolf.
I was able to get some stacktrace if that helps :

AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
HttpCommandExecutor.Execute(Command commandToExecute)
--- End of inner exception stack trace ---
HttpCommandExecutor.Execute(Command commandToExecute)
DriverServiceCommandExecutor.Execute(Command commandToExecute)
WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
WebDriver.FindElements(String mechanism, String value)
<.ctor>b__11_1(ISearchContext context)

I can attach few similar error : https://stackoverflow.com/questions/22322596/selenium-error-the-http-request-to-the-remote-webdriver-timed-out-after-60-sec

**Comment by skotian2** [comment]
Adding Fluent wait updated the issue.

**Comment by ChristoWolf** [comment]
You mean that it's fixed now?
What exactly was the cause?
My only suspicion from your extended exception would have been that there were so many matching elements being found by `FindElements` that it timed out.

**Comment by skotian2** [comment]
I tried with explicit wait as you mentioned but Fluent wait was working better , We were trying to reach the element after the selenium timeout. I just increased the wait time in fluent wait and it kept polling till the element was found.

**Comment by ChristoWolf** [comment]
They are equivalent, but whatever works best for you.
Great that your issues are resolved!
