### ISSUE TITLE
Win App driver 

### ISSUE THREAD

**Issue by Dhru231** [microsoft/WinAppDriver#1809]
{"status":23,"value":{"error":"no such window","message":"Currently selected window has been closed"}

**Comment by igorrecioh** [comment]
@Dhru231 Could you please provide more info related to your issue?

**Comment by Dhru231** [comment]
Log For Windows App Driver
Error Type : "Currently selected window has been closed , Launching the app but code fail to click on given window element here I have attached code and Server log 

 Windows Application Driver listening for requests at: http://127.0.0.1:4723/
Press ENTER to exit.


==========================================
POST /session HTTP/1.1
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
Content-Length: 310
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5.2 (Java/17.0.4.1)

{"capabilities":[{"desiredCapabilities":{"app":"C:\\Apps\\Seqent\\EXE\\WFMAdmin.exe","platformName":"Windows","deviceName":"WindowsPC"}},{"requiredCapabilities":{}}],"desiredCapabilities":{"app":"C:\\Apps\\******\\EXE\\******.exe","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{}}
HTTP/1.1 200 OK
Content-Length: 142
Content-Type: application/json

{"sessionId":"F429B166-7F8F-438A-983E-1CD293C909A7","status":0,"value":{"app":"C:\\Apps\\*******\\EXE\\*****.exe","platformName":"Windows"}}


==========================================
GET /session/F429B166-7F8F-438A-983E-1CD293C909A7 HTTP/1.1
Accept-Encoding: gzip,deflate
Cache-Control: no-cache
Connection: Keep-Alive
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5.2 (Java/17.0.4.1)


HTTP/1.1 200 OK
Content-Length: 91
Content-Type: application/json

{"status":0,"value":{"app":"C:\\Apps\\******\\******.exe","platformName":"Windows"}}


==========================================
GET /session/F429B166-7F8F-438A-983E-1CD293C909A7 HTTP/1.1
Accept-Encoding: gzip,deflate
Cache-Control: no-cache
Connection: Keep-Alive
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5.2 (Java/17.0.4.1)


HTTP/1.1 200 OK
Content-Length: 91
Content-Type: application/json

{"status":0,"value":{"app":"C:\\Apps\\******\\******.exe","platformName":"Windows"}}

==========================================

POST /session/F429B166-7F8F-438A-983E-1CD293C909A7/timeouts HTTP/1.1
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
Content-Length: 30
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5.2 (Java/17.0.4.1)

{"type":"implicit","ms":10000}
HTTP/1.1 200 OK
Content-Length: 63
Content-Type: application/json

{"sessionId":"F429B166-7F8F-438A-983E-1CD293C909A7","status":0}


==========================================
POST /session/F429B166-7F8F-438A-983E-1CD293C909A7/element HTTP/1.1
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
Content-Length: 31
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5.2 (Java/17.0.4.1)

{"using":"name","value":"File"}
HTTP/1.1 400 Bad Request
Content-Length: 102
Content-Type: application/json

{"status":23,"value":{"error":"no such window","message":"Currently selected window has been closed"}}

==========================================

DELETE /session/F429B166-7F8F-438A-983E-1CD293C909A7 HTTP/1.1
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5.2 (Java/17.0.4.1)


HTTP/1.1 200 OK
Content-Length: 12
Content-Type: application/json

{"status":0}
----------------------------------------------------------------------------------------------------------------------------------------
Code : 
package OpenWFMA;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebElement;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import io.appium.java_client.windows.WindowsDriver;
import io.appium.java_client.windows.WindowsElement;

public class ClickOnNewServer {
	
	  public static WindowsDriver driver = null;
	  private static WindowsDriver AdminSession = null;
	  public  static  WindowsDriver desktopsession = null;
	  public  String WindowsApplicationDriverUrl = "http://127.0.0.1:4723";



	@BeforeClass
	 public static void setUp() throws MalformedURLException {
		
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("app", "C:\\Apps\\****.exe");
		capabilities.setCapability("deviceName", "WindowsPC");
		capabilities.setCapability("platformName", "Windows");

		driver = new WindowsDriver<RemoteWebElement>(new URL("http://127.0.0.1:4723"), capabilities);
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
 }
	
	
	@AfterMethod
	public void cleanup() throws MalformedURLException{
		driver.quit();
		
}
	/*	
	@AfterSuite
	private void tearDown() {
		driver.quit();
		}
		*/
	
	@Test
	 public void NewserverSteps() throws InterruptedException { 
	
	Thread.sleep(2000);
	
	driver.findElementByName("File").click();
	 System.out.println("File has been clicked ");
			  
}

}

**Comment by Shakevg** [comment]
@Dhru231 You posted different errors in the first and second messages. What is actual?
Could you describe your scenario in more detail?
Do yu have a splash screen during the start of your app?

**Comment by Dhru231** [comment]
Yes splash screen during start of the app and please consider second issue

**Comment by anunay1** [comment]
If you have a splash screen then you need to create a root session and then switched to the opened window.

**Comment by anunay1** [comment]
check 
https://github.com/microsoft/WinAppDriver/blob/master/Docs/FAQ.md

**Comment by Dhru231** [comment]
Thanks every one its fixed
