### ISSUE TITLE
AutoScroll to Element inside DataGridView not working during Click event

### ISSUE THREAD

**Issue by kathipavan** [microsoft/WinAppDriver#1829]
Hi Team, 
We are trying to automate testing of windows form application by making use of Appium. 
One of the form contains System.Windows.Forms.DataGridView which is used to display records on the windows form.
As part of scenario we have to perform Click event on given Row and if the Row to be Clicked is not visible (i.e, if it requires to scroll to see it), Such control is not allowing click action to be performed. We can see IsScrollItemPatternAvailable set to false for all rows in DataGridView.  
We referred similar thread (https://github.com/microsoft/WinAppDriver/issues/753)  on this forum.  It is suggested to manually scrolling into view either via keyboard injection or the Actions Touch injection APIs. Could you please provide any sample code for them..
I have say 1000 records on my grid and I want to scroll to row that is satisfied by a filter condition, irrespective of its location on grid and whether it requires scroll to view the element or not.

I tried below piece of code and is resulting into exception "An unknown error occurred in the remote end while processing the command"

```
 RemoteTouchScreen objRemoteTouchScreen = new RemoteTouchScreen(DesktopSession);
   objRemoteTouchScreen.SingleTap(filteredRow.Coordinates);
```

```
POST /session/E1F798FE-D8F2-4CD5-878A-A7048A14E80A/touch/click HTTP/1.1
Accept: application/json, image/png
Content-Length: 34
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.0 (.net windows)
X-Idempotency-Key: 3a42bb61-5c55-479b-bb45-3a8d96afdca2

{"element":"42.43332040.16157963"}
HTTP/1.1 500 Internal Error
Content-Length: 133
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}


==========================================
POST /session/E1F798FE-D8F2-4CD5-878A-A7048A14E80A/appium/app/close HTTP/1.1
Accept: application/json, image/png
Content-Length: 2
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.0 (.net windows)
X-Idempotency-Key: cd9d741c-b3bf-4c4c-ae8e-d967adad14cb

{}
HTTP/1.1 200 OK
Content-Length: 63
Content-Type: application/json

{"sessionId":"E1F798FE-D8F2-4CD5-878A-A7048A14E80A","status":0}
```

Below code didn't result in any exception, but click action is not working at all
```
Actions actions = new Actions(DesktopSession);
            actions.DoubleClick(GridView.FindElementByName("Row 120"));
```

```
POST /session/93287D1D-65BA-43D6-B158-8359345BD363/element/42.2035012/element HTTP/1.1
Accept: application/json, image/png
Content-Length: 34
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.0 (.net windows)
X-Idempotency-Key: de7d2922-1bf8-4f9d-805e-18fef718f958

{"using":"name","value":"Row 120"}
HTTP/1.1 200 OK
Content-Length: 106
Content-Type: application/json

{"sessionId":"93287D1D-65BA-43D6-B158-8359345BD363","status":0,"value":{"ELEMENT":"42.43332040.16157963"}}


==========================================
POST /session/93287D1D-65BA-43D6-B158-8359345BD363/appium/app/close HTTP/1.1
Accept: application/json, image/png
Content-Length: 2
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.0 (.net windows)
X-Idempotency-Key: d0f3ea89-1312-4445-8b87-c2afa48f36cf

{}
HTTP/1.1 200 OK
Content-Length: 63
Content-Type: application/json

{"sessionId":"93287D1D-65BA-43D6-B158-8359345BD363","status":0}
```

Thank you...

**Comment by liljohnak** [comment]
@kathipavan can you send a screenshot of the UI tree?  
Wondering if your grid has virtual items.
Also, the row usually has the following to help filter a specific row:
`AppiumWebElement.GetAttribute("GridItem.Row");`

**Comment by kathipavan** [comment]
Thank you for your inputs @liljohnak . Please find attached screen shot for the same.
![ControlTree](https://user-images.githubusercontent.com/62210147/205483918-7b2e3110-a5dc-4e9c-82e5-26b6b2edc6e4.png)
Highlighted Name Row 24, Not Sorted is element, I am trying to click/double click /Highlight by scrolling to that element, if that is not in the visible portion of grid.
`row.Click(); `
resulting in below error 
```
POST /session/A907E169-AB9B-4732-BABD-E375DCF6F5ED/element/42.56608836/click HTTP/1.1
Accept: application/json, image/png
Content-Length: 2
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.0 (.net windows)
X-Idempotency-Key: 9b6ac81d-32bd-45a2-b061-84a1b81b33d4

{}
HTTP/1.1 400 Bad Request
Content-Length: 175
Content-Type: application/json

{"status":105,"value":{"error":"element not interactable","message":"An element command could not be completed because the element is not pointer- or keyboard interactable."}}
```
Below Code as well resulting into exception
```
RemoteTouchScreen objRemoteTouchScreen = new RemoteTouchScreen(DesktopSession);
objRemoteTouchScreen.SingleTap(row.Coordinates);
```
```
POST /session/6D62698C-F679-4886-87C5-17ED66B69141/touch/click HTTP/1.1
Accept: application/json, image/png
Content-Length: 25
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.0 (.net windows)
X-Idempotency-Key: 9b5a30ef-c0c2-47a6-88b5-a86978e3290b

{"element":"42.56608836"}
HTTP/1.1 500 Internal Error
Content-Length: 133
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
```
Below Code is resulting in No Action
```
Actions actions = new Actions(DesktopSession);
actions.DoubleClick(row);
```
Thank you...

**Comment by kathipavan** [comment]
Also I can see "Name Row 24, Not Sorted" Display property as False, where as its Parent "Row 24" display property as true. And click event on Parent "Row 24" is not resulting in anything..

**Comment by kathipavan** [comment]
Thank you @liljohnak , I believe I resolved this issue with help of this thread https://stackoverflow.com/questions/60201568/how-to-scroll-the-area-like-drop-down-and-list-box-in-winapp-driver-with-c  . I scrolled until  I can see "Name Row 24, Not Sorted" Display property as True, after that I invoked click action which resolved the issue, I was facing.

**Comment by liljohnak** [comment]
@kathipavan glad this helped. per your UI tree screenshot you do not have virtual items.
Virtual items are known to exist by the parent control but, are not rendered yet because the user has not scrolled to them yet.  Searching for these is more challenging because AppiumWebElement.Id is recycled from elements scrolling out of view to elements that are coming into view.

**Comment by kathipavan** [comment]
Thank you @liljohnak..
