### ISSUE TITLE
WinAppDriver pauses after application start on UWP

### ISSUE THREAD

**Issue by djm181** [Microsoft/WinAppDriver#183]
I'm running into a problem on UWP where WinAppDriver will start the application in response to a /POST session but will then not respond to the calling appium tests for several seconds. eg:

> ==========================================
> POST /session HTTP/1.1
> Accept: application/json
> Accept-Encoding: identity
> Connection: close
> Content-Length: 118
> Content-Type: application/json;charset=UTF-8
> Host: 172.16.2.83:4723
> User-Agent: Python-urllib/2.7
> 
> 
> SessionManager - Creating session
> SessionManager - WinAppDriver succeeded loading MitaBroker

The winappdriver hangs here, even though the application is fully started and functional. Then subsequently continues with:
 
> SessionManager - Application launched
> SessionManager - Session successfully created: 6EBB923F-BD94-4E0E-8096-57FEA78505A9
> HTTP/1.1 200 OK
> Content-Length: 136
> Content-Type: application/json
> 
> {"sessionId":"6EBB923F-BD94-4E0E-8096-57FEA78505A9","status":0,"value":{"app":"57b011a8-cb1d-487b-ac4c-5ae501af534a_damzpawhsp48w!App"}}

I noticed that there was a part of my UI that was a dynamically generated list that when removed allowed the WinAppDriver to start and execute just as you would expect. I refactored this so that it was handled differently and WinAppDriver was once again fast.

However, as additional complex elements are added to the application the delay for winappdriver to respond is growing again.

I've been unsuccessful reproducing this with a smaller test app.

**Comment by Korop** [comment]
It lool like the issue similar to 
https://github.com/Microsoft/WinAppDriver/issues/130

**Comment by djm181** [comment]
Agree, I think this can be closed as a Dupe

**Comment by timotiusmargo** [comment]
We have performed some optimizations on application launching during session creation In [v1.0-RC release](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.0-RC). It now takes less than 1 second from the moment the application window is open for the session (driver) to be ready.
