### ISSUE TITLE
How to minimize the UWP app by the WinAppDriver?

### ISSUE THREAD

**Issue by holphi** [Microsoft/WinAppDriver#184]
Hi there,

I am evaluating the Windows application driver for UWP APP automation. In order to suspend the UWP apps, I need to minimize it, however, I went through all the methods of the Windows driver but seems the driver doesn't provide methods for this operation. 

Is there any other workarounds for us to do such work? 

Best regards,
Alex

**Comment by timotiusmargo** [comment]
You can use Windows Key shortcut to minimize current active window or all windows as follows.

```
// Press Windows keys followed by two Arrow Down keys to minimize current active window
session.Keyboard.SendKeys(OpenQA.Selenium.Keys.Meta + OpenQA.Selenium.Keys.ArrowDown + OpenQA.Selenium.Keys.ArrowDown + OpenQA.Selenium.Keys.Meta);

// Press Windows keys followed by 'm' to minimize all windows
session.Keyboard.SendKeys(OpenQA.Selenium.Keys.Meta + 'm' + OpenQA.Selenium.Keys.Meta);
```

**Comment by holphi** [comment]
Hi Timotius,

Thanks for your response. The keyboard shortcut works for me!

Cheers,
Alex
