### ISSUE TITLE
WinForms MenuStrip's ToolStripMenuItem children are not accessible

### ISSUE THREAD

**Issue by JonHeaton** [Microsoft/WinAppDriver#185]
I am trying to automate a menu in my application and the MenuBar comes in but not the MenuItems that are inside of it.

Here is the menubar from the page source on the driver:

`<MenuBar AcceleratorKey="" AccessKey="" AutomationId="menuStrip1" ClassName="WindowsForms10.Window.8.app.0.141b42a_r9_ad1" FrameworkId="WinForm" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="menu bar" Name="menuStrip1" Orientation="None" ProcessId="16340" RuntimeId="42.5048014" x="60" y="83" width="284" height="24" />`

I know that the MenuStrip does not implement UIAutomation and are only exposed to UIAutomation via MSAA.  [MSDN Supported Controls for UIAutomation](https://msdn.microsoft.com/en-us/library/ms744822(v=vs.110).aspx)

The Inspect tool does show the menu items whether I am in UIAutomation mode or MSAA mode.

The only inkling that it could be something in my setup is that when I catch ALL exceptions, there is a COMException in Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll
Retrieving the COM class factory for component with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).

Is this supposed to work?  I have a small sample project that illustrates the issue if needed.

Thanks,
Jon

**Comment by KanstantsinSudzilouski** [comment]
I saw people in https://github.com/Microsoft/WinAppDriver/issues/83 also complains that WinForms does not work properly. We have to reject WinAppDriver and Winium and start with White instead to test WinForms application.

**Comment by yodurr** [comment]
At the moment WinAppDriver does not support MSAA.  Is this control provided by a 3rd party?  Would be good to find out if they are open to updating the control to support UI Automation.

**Comment by PandaMagnus** [comment]
Are there plans to support MSAA at some point? The MSDN documentation I've found makes it pretty clear they have no plans to continue to develop it, which is understandable. But when looking for solutions to test legacy apps, we've been pretty pigeonholed into writing our own CodedUI tests... which while slightly more manageable than using record and playback is still not an ideal solution.

**Comment by hassanuz** [comment]
Hi @JonHeaton ,

There was an issue prior to the 1.0 release where a few elements were not appearing. Controls that are properly implemented in MSAA are projected into UIA, they should be generally interactable. 

If you still see this on the latest WinAppDriver, let us know.

**Comment by edw-c** [comment]
I'm using WinAppDriver v1.1.1809.18001 and am having problem seeing items within a dropdown menu. I'm testing with a new C# WinForms application in VS2015, adding a MDIForm and editing program.cs to open the MDI form on startup. I can see and click the menus along the menu bar (File / Edit / Help). I can see items within the menu (e.g. Help / About) using Inspect.exe in MSAA mode. I can't see items within the menu using inspect.exe in UI Automation mode. Can you advise if there's anything I can do to help this control project into UIA properly? Many thanks.
