### ISSUE TITLE
Multiple Instances Running

### ISSUE THREAD

**Issue by jfclancey** [microsoft/WinAppDriver#1856]
WinappDriver is currently installed on a VM. Can I have multiple instances of WinAppDriver running to support the different users who are logged in? It doesn't appear to be the case.

**Comment by Shakevg** [comment]
[jfclancey](https://github.com/jfclancey) Why do you need several instances?
You can create any session count in one instance of WinAppDriver for different apps or several instances of one app.

**Comment by jfclancey** [comment]
I want to know if multiple people can be using WinAppDriver at the same time. Another instance would be 2 Azure pipelines running test on the same server.

**Comment by Shakevg** [comment]
[jfclancey](https://github.com/jfclancey) it is not recommended to run tests in parallel with WinAppDriver https://github.com/microsoft/WinAppDriver/issues/592#issuecomment-463085275
