### ISSUE TITLE
How to set date on datepicker control for a UWP application

### ISSUE THREAD

**Issue by ernidhi20** [Microsoft/WinAppDriver#186]
Hi,

I am trying to set date on a datepicker control for a UWP application with below C# code:

Approach #1 :
WindowsElement datepicker =  AppDriver.FindElementByClassName("DatePicker");
datepicker.SendKeys("03/05/2013");
AppDriver.FindElementByAccessibilityId("AcceptButton").Click();

Approach #2:

Tried setting values for date, month and year individually:

 WindowsElement day = AppDriver.FindElementByXPath("//attribute::*[contains(., 'Day')]/..");
                day.SendKeys("20");
               WindowsElement month = AppDriver.FindElementByXPath("//attribute::*[contains(., 'Month')]/..");
                month.SendKeys("2");
                WindowsElement year = AppDriver.FindElementByXPath("//attribute::*[contains(., 'Year')]/..");
                year.SendKeys("2014");
                AppDriver.FindElementByAccessibilityId("AcceptButton").Click();

Both the code snippets above does not throw any exception but fails to set date on the control. Is sendkeys() the right API to set date on datepicker or should it be done differently?
Is setting datepicker value for UWP supported by winappdriver at this point?

Thanks,
Nidhi

**Comment by timotiusmargo** [comment]
Hello @ernidhi20,

Please check out our sample test below that highlight all interaction with UWP **DatePicker** control.
https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/Tests/UWPControls/DatePicker.cs

In summary, below is how you can set the value.

```c#
// Set the year to 2000
datePickerFlyout = session.FindElementByAccessibilityId("DatePickerFlyoutPresenter");
var yearLoopingSelector = datePickerFlyout.FindElementByAccessibilityId("YearLoopingSelector");
var currentYear = yearLoopingSelector.Text;
yearLoopingSelector.FindElementByName("2000").Click();

System.Threading.Thread.Sleep(1000);
Assert.AreNotEqual(currentYear, yearLoopingSelector.Text);
```

And below is how to retrieve the value of individual selector.

```c#
var datePickerFlyout = session.FindElementByAccessibilityId("DatePickerFlyoutPresenter");
Assert.AreNotEqual(string.Empty, datePickerFlyout.FindElementByAccessibilityId("DayLoopingSelector").Text);
Assert.AreNotEqual(string.Empty, datePickerFlyout.FindElementByAccessibilityId("MonthLoopingSelector").Text);
```

**Comment by MinoEclairs** [comment]
hello I am automating a Win32 application. I am having trouble selecting the date from calendar control. I tried the following:

session.FindElementByAccessibilityId("dtpFromDate").SendKeys("23/Apr/2010");

it doesn't throw any error but it also doesn't select the date. Can some one please help? It doesn't have a unique selector.
The test that you mention are for UWP applications so they are not helpful at all. Does winAppDriver support picking date of Win32 applications? 


my inspect and calendar screenshots are below:
https://www.screencast.com/t/ihCXKN2hRSV
