### ISSUE TITLE
windows application path is not directly providing instead stored in some variable are sending it but it not working

### ISSUE THREAD

**Issue by SireeshaDuvvuri** [microsoft/WinAppDriver#1865]
Hi team.

I want to make a windows application path in the config.properties file, and from there I am trying to access the properties. but with that variable application is not up. Help me in this

DesiredCapabilities capabilities = new DesiredCapabilities();
	loadProperties();
	capabilities.setCapability("app", exepath); ---here while debugging I am able see the path.
	capabilities.setCapability("platformName","Windows"); ---from here it is not working
	capabilities.setCapability("deviceName", "WindowsPC");
	logger = LoggerFunctions.setLogger(CLASS_NAME);
	LoggerFunctions.setup(logger, CLASS_NAME);
	Session = new WindowsDriver(new URL("http://127.0.0.1:4723"), capabilities);  ----gettng null

**Comment by anunay1** [comment]
What is shown in winappdriver console? What's the exception?

**Comment by SireeshaDuvvuri** [comment]
Unable to create a new remote session. Please check the server log for more details. Original error: The system cannot find the file specified (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 3.27 seconds

**Comment by SireeshaDuvvuri** [comment]
This is my complete code.

public static WindowsDriver Session = null;
	
	
   public static String exepath;
    
  public static Properties properties;

  public static void loadProperties() {
      FileInputStream fis = null;
      
      try {
          properties = new Properties();
          fis = new FileInputStream("src\\test\\resources\\Configuration\\config.properties");
          properties.load(fis);
          exepath = properties.getProperty("path");
      } catch (FileNotFoundException e) {
          e.printStackTrace();
      } catch (IOException e) {
          e.printStackTrace();
      } finally {
          try {
              fis.close();
          } catch (IOException e) {
              e.printStackTrace();
          }
      }
  }

@BeforeClass
public static void setUp() {
try {
	
	
	DesiredCapabilities capabilities = new DesiredCapabilities();
	loadProperties();
	capabilities.setCapability("app", exepath);
	capabilities.setCapability("platformName","Windows");
	capabilities.setCapability("deviceName", "WindowsPC");
	logger = LoggerFunctions.setLogger(CLASS_NAME);
	LoggerFunctions.setup(logger, CLASS_NAME);
	Session = new WindowsDriver(new URL("http://127.0.0.1:4723"), capabilities);
	

  }
catch (Exception e) {
 e.printStackTrace();
}
}

**Comment by anunay1** [comment]
The return type of the load properties function is void. In the setup function you are only calling load properties,  exepath will always be null in the setup function.

**Comment by SireeshaDuvvuri** [comment]
Issue Resolved. Thank you
