### ISSUE TITLE
Best patter for waiting for a condition.

### ISSUE THREAD

**Issue by ghost** [Microsoft/WinAppDriver#187]
I am test some old Delphi code using the Appium Windows driver. Users of this LOB application spend a lot of time waiting for screens to change and pull up database bound forms.

What is the best pattern for waiting for a change in the UI, such as a form transition, new window or discreet property change, from within Visual Studio test? Do I have access to events somehow? Or do I need to keep polling at interval?

**Comment by hassanuz** [comment]
This is a feature request to get [explicit waits](https://www.seleniumhq.org/docs/04_webdriver_advanced.jsp) implemented into the appium.net driver.

Unfortunately the bindings commonly used by WinAppDriver (Appium.NetDriver) do not support explicit wait at the moment.  

If you're interested in this support, please file a request at the [appium-dotnet-driver issue board](https://github.com/appium/appium-dotnet-driver/issues).
