### ISSUE TITLE
InvalidOperationException and NullReferenceException

### ISSUE THREAD

**Issue by caulfield2** [Microsoft/WinAppDriver#189]
I am having a bit of an issue automating testing on an application. When writing a simple test program, I can get the application to open fine in [ClassInitialize] with the code below, but an InvalidOperationException is thrown with the description "an unknown error occurred in the remote end while processing the command.." once the app opens. 

`using Microsoft.VisualStudio.TestTools.UnitTesting;
using OpenQA.Selenium.Appium.Windows;
using OpenQA.Selenium.Remote;
using System;

namespace UnitTestProject1
{
    [TestClass]
    public class UnitTest1
    {
        protected const string WindowsApplicationDriverUrl = "http://127.0.0.1:4723";
        protected static WindowsElement Result;
        protected static WindowsDriver<WindowsElement> Session;
        protected static string OriginalMode;
       
        [ClassInitialize]
        public static void Setup(TestContext context)
        {
            if (Session == null)
            {
                    DesiredCapabilities appCapabilities = new DesiredCapabilities();
                    appCapabilities.SetCapability("app", "Application");
                    appCapabilities.SetCapability("deviceName", "WindowsPC");
                    Session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities);
                    Assert.IsNotNull(Session);
                    Session.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(7));
            }
        }
          
        [TestMethod]
        public void TestMethod1()
        { 
        }
    }
}`

Since the app opened fine, I just used a try-catch to catch the InvalidOperationException, allowing the code to proceed to [TestMethod]. However, in the unit test any attempt to use Session is met with a NullReferenceException with the message "Object reference not set to an instance of an object." Debugging confirms that Session enters the test method as null. 
`
using Microsoft.VisualStudio.TestTools.UnitTesting;
using OpenQA.Selenium.Appium.Windows;
using OpenQA.Selenium.Remote;
using System;

namespace UnitTestProject1
{
    [TestClass]
    public class UnitTest1
    {
        protected const string WindowsApplicationDriverUrl = "http://127.0.0.1:4723";
        protected static WindowsElement Result;
        protected static WindowsDriver<WindowsElement> Session;
        protected static string OriginalMode;
       
        [ClassInitialize]
        public static void Setup(TestContext context)
        {
            if (Session == null)
            {
               try
               {
                    DesiredCapabilities appCapabilities = new DesiredCapabilities();
                    appCapabilities.SetCapability("app", "Application");
                    appCapabilities.SetCapability("deviceName", "WindowsPC");
                    Session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities);
                    Assert.IsNotNull(Session);
                    Session.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(7));
                }
                catch (InvalidOperationException e)
                {  
                }
            }
        }
          
        [TestMethod]
        public void TestMethod1()
        {
            Session.FindElementByName("Name").Click();
        }
    }
}`

I find this very strange, as I have successfully run through many of the provided samples without any issues. What is even more strange is that some of these issues seem to come and go without any explanation. During one test, I had the script running fine with the addition of the try-catch and  appCapabilities.SetCapability("app", "Root"); line. Running it again brought me back two steps. Now, the addition of that line prevents the application from opening. 

Unfortunately, I cannot provide the name of the application being used. Any suggestions are much appreciated.

**Comment by caulfield2** [comment]
> https://discuss.appium.io/t/windows-driver-doesnt-connect-to-application-50-of-time/14219 here is another user with the same issue

**Comment by caulfield2** [comment]
Workaround identified: Still having issue with InvalidOperationException, but try-catch allows code to proceed with test after app is launched. Creating a new instance of DesiredCapabilities and WindowsDriver<WindowsElement>  with the SetCapability("app", "Root") addition allows me to find the app once it is opened. Not elegant, but it works for now.

**Comment by sachinDV** [comment]
How you resoved this issue?.I'm facing the same issue
