### ISSUE TITLE
{"status":13,"value":{"error":"unknown error","message":"Failed to locate opened application window with appId:

### ISSUE THREAD

**Issue by skotian2** [microsoft/WinAppDriver#1890]
Hi All -
I am trying to launch a windows based application using WinAppDriver latest version. Application launches successfully but the test keeps on failing because of the following error:
 OpenQA.Selenium.WebDriverException: Failed to locate opened application window with appId: C:\XXX\XXX.exe, and processId: 18368

Any insight or help would be highly appreciated.
I have tried following solutions:
1. Options.AddAdditionalCapability("ms:waitForAppLaunch", "25");
2. Adding Thread
3. Invoking exe as a admin

**Comment by Shakevg** [comment]
[skotian2](https://github.com/skotian2) Do you have a splash screen in your app?

**Comment by skotian2** [comment]
Nope - I do not have any splash screen. I am trying to launch Cisco Jabber messenger app if that helps.

**Comment by Shakevg** [comment]
Try this approach https://github.com/microsoft/WinAppDriver/issues/1323#issuecomment-1022542052

**Comment by skotian2** [comment]
@Shakevg - I have tried the approach and still having the same error. I also tried with changing the path type by adding quotes no luck still.


System.Diagnostics.Process.Start("C:\\Program Files (x86)\\Windows Application Driver\\WinAppDriver.exe");
AppiumOptions Options = new AppiumOptions();
Options.AddAdditionalCapability("app", "C:\\Program Files (x86)\\Cisco Systems\\Cisco Jabber\\CiscoJabber.exe");
Options.AddAdditionalCapability("deviceName", "WindowsPC");
Options.AddAdditionalCapability("isHeadless", true);
Options.SetLoggingPreference(OpenQA.Selenium.LogType.Server, OpenQA.Selenium.LogLevel.All);
Options.AddAdditionalCapability("ms:waitForAppLaunch", "25");
CiscoJabberSession = new WindowsDriver<WindowsElement>(new Uri(DriverUrl), Options);

{"status":13,"value":{"error":"unknown error","message":"Failed to locate opened application window with appId: C:\\Program Files (x86)\\Cisco Systems\\Cisco Jabber\\CiscoJabber.exe, and processId: 18020"}}

**Comment by skotian2** [comment]
@Shakevg - This approach is working now Reference : Launching application using application parameters #1323

  System.Diagnostics.Process.Start("C:\\Program Files (x86)\\Windows Application Driver\\WinAppDriver.exe");
            System.Diagnostics.Process.Start("C:\\Cisco Systems\\Cisco Jabber\\CiscoJabber.exe");
            Thread.Sleep(15000);

            // Create a session for Desktop
            AppiumOptions Options = new AppiumOptions();
            Options.AddAdditionalCapability("app", "Root");
            desktopSession = new WindowsDriver<WindowsElement>(new Uri(DriverUrl), Options);
            Assert.IsNotNull(desktopSession);

            //WindowsElement CortanaWindow = desktopSession.FindElementByName("Cisco Jabber");
            WindowsElement ACDLaunch = desktopSession.FindElementByName("Cisco Jabber");

**Comment by Shakevg** [comment]
[skotian2](https://github.com/skotian2) Instead of Thread.Sleep(15000); better to use wait

```csharp
WebDriverWait wait = new WebDriverWait(desktopSession, TimeSpan.FromSeconds(15000));
wait.Until(ExpectedConditions.ElementExists(By.Name("Cisco Jabber")));
WindowsElement ACDLaunch = desktopSession.FindElementByName("Cisco Jabber");
```
