### ISSUE TITLE
Need help in converting absolute xPath to relative xPath recorded by WinAppDriver UI Recorder

### ISSUE THREAD

**Issue by saurabhsule82** [microsoft/WinAppDriver#1893]
Hi,

I'm trying to automate Pulse Secure VPN client using Java with WinAppDriver. Pulse Secure VPN client is running in the Windows Tray. I'm able to automate it by using absolute xPaths recorded in WinAppDriver UI Recorder, but I'm unable to covert those absolute xPaths to relative xPaths. I've tried several options but none of them work. Any help is really appreciated.

For starts, here is an absolute xPath for the opening the Windows Tray:

"/Pane[@Name=\"Desktop 1\"][@ClassName=\"#32769\"]/Pane[@Name=\"Taskbar\"][@ClassName=\"Shell_TrayWnd\"]/Pane[@ClassName=\"TrayNotifyWnd\"]/Button[@Name=\"Notification Chevron\"][@ClassName=\"Button\"]"

I cannot find a way to make this xPath relative. Need help in understanding how can I covert such absolute xPaths to relative xPaths.

Thank you.

**Comment by saurabhsule82** [comment]
![inspect](https://github.com/microsoft/WinAppDriver/assets/130485911/5d90b7df-498a-4040-9d70-614c6fa48d3c)

Here is my sample java code:

`
public class TestClientWithAbsoluteXpath 

	private static WindowsDriver windowTray = null;
	
	public static void main(String[] args) throws Exception 
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("app", "Root");
		windowTray = new WindowsDriver(new URL("http://127.0.0.1:4723"), capabilities);
		windowTray.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
		windowTray.findElementByXPath("/Pane[@Name=\"Desktop 1\"][@ClassName=\"#32769\"]/Pane[@Name=\"Taskbar\"][@ClassName=\"Shell_TrayWnd\"]/Pane[@ClassName=\"TrayNotifyWnd\"]/Button[@Name=\"Notification Chevron\"][@ClassName=\"Button\"]").click();
`

If I include windowTray.getPageSource(), it just hangs and doesn't print anything.

**Comment by Shakevg** [comment]
Try //*[@ClassName="TrayNotifyWnd"]//Button[@Name="Notification Chevron"][@ClassName="Button"]
Could you also post screenshot of tree from the left panel in Inspector.

**Comment by saurabhsule82** [comment]
I tried, but it didn't work. On the console of the WinAppDriver.exe, I see:

POST /session/3FA09EE3-09B7-45C1-88B2-2E3A1DB888C6/element HTTP/1.1
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
Content-Length: 124
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5.2 (Java/17.0.5)

{"using":"xpath","value":"//*[@classname=\"TrayNotifyWnd\"]//Button[@name=\"Notification Chevron\"][@classname=\"Button\"]"}

Exception: Encountered element sharing the same runtimeId 42.264930.4.-20

    new Object {Maximize, , 42.264930.4.-20}
    runtimeId 42.264930.4.-20
    className
    name Maximize
    NativeWindowHandle 0

    existing Object {Minimize, , 42.264930.4.-20}
    runtimeId 42.264930.4.-20
    className
    name Minimize
    NativeWindowHandle 0


Ignoring new object and keeping existing one


Exception: Encountered element sharing the same runtimeId 42.68538.4.-16

    new Object {Search, , 42.68538.4.-16}
    runtimeId 42.68538.4.-16
    className
    name Search
    NativeWindowHandle 0

    existing Object {Problems, , 42.68538.4.-16}
    runtimeId 42.68538.4.-16
    className
    name Problems
    NativeWindowHandle 0


Ignoring new object and keeping existing one


Exception: Encountered element sharing the same runtimeId 42.68538.4.-16

    new Object {Console, , 42.68538.4.-16}
    runtimeId 42.68538.4.-16
    className
    name Console
    NativeWindowHandle 0

    existing Object {Problems, , 42.68538.4.-16}
    runtimeId 42.68538.4.-16
    className
    name Problems
    NativeWindowHandle 0


Ignoring new object and keeping existing one


Exception: Encountered element sharing the same runtimeId 42.68538.4.-16

    new Object {Progress, , 42.68538.4.-16}
    runtimeId 42.68538.4.-16
    className
    name Progress
    NativeWindowHandle 0

    existing Object {Problems, , 42.68538.4.-16}
    runtimeId 42.68538.4.-16
    className
    name Problems
    NativeWindowHandle 0


Ignoring new object and keeping existing one


Unfortunately, I'm unable to provide the screenshot of the tree view from Inspector because my Inspector.exe doesn't have that view and I'm not in a position to install the Windows SDK that contains the Inspector.exe. This Inspector.exe is the direct binary I downloaded from the Github project.

**Comment by saurabhsule82** [comment]
Thank you Shakevg. Appreciate all your help here. For now, I'll have to continue with the absolute xPath.
