### ISSUE TITLE
self.w3c = "specificationLevel" in self.capabilities ;TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by rsmrahul1** [Microsoft/WinAppDriver#19]
import unittest
from appium import webdriver

desired_caps = {
    'platformName': 'WindowsModern',
    'app': 'Microsoft.WindowsCalculator_8wekyb3d8bbwe!App',    
}
print desired_caps
driver = webdriver.Remote('http://127.0.0.1:4723', desired_caps)
print driver
print driver.find_element_by_name('One')

----------------------------------------------------------------------------------------------------
Tried the WinAppDriver with python and getting the below error from appium  driver

 in <module>
    driver = webdriver.Remote('http://127.0.0.1:4723', desired_caps)
  File "C:\Python27\lib\site-packages\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 91, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 181, in start_session
    self.w3c = "specificationLevel" in self.capabilities
TypeError: argument of type 'NoneType' is not iterable

--------------------------------------------------------------------------------------
In webdriver.py
In the line
self.capabilities = response['value']
response['value'] seems to be null.

Did I miss anything in the python script ?

**Comment by alakshmi1030** [comment]
We are planning on creating a Python sample with WinAppDriver soon and we will look into this.

**Comment by alakshmi1030** [comment]
As of release v0.3, Python support should be enabled. Please view the release here: https://github.com/Microsoft/WinAppDriver/releases/tag/v0.3-beta

Let us know if you are still experiencing this issue.
