### ISSUE TITLE
OpenQA.Selenium.WebDriverException: An unknown error occurred in the remote end while processing the command.

### ISSUE THREAD

**Issue by ravi46kom** [microsoft/WinAppDriver#1901]
Hi
I upgraded a User Interface project, .NET 4.7 to .NET core, I'm getting all test case passes on local but, while trying on VM i always got "OpenQA.Selenium.WebDriverException: An unknown error occurred in the remote end while processing the command." 
I tried some approach which i found on old [ticket](https://github.com/microsoft/WinAppDriver/issues/104) .

1. enable developer mode.
2. Run WinAppDriver.exe as admin
3.  I used "session.SwitchTo().Window(session.CurrentWindowHandle)" to focus on current window.
4. I'm using winappdriver version "1.2.2009.2003"
5.  Appium Version: 
<img width="200" alt="image" src="https://github.com/microsoft/WinAppDriver/assets/74744300/ca344855-f72e-49f4-b91a-53df7a89b87e">
Error:
<img width="543" alt="image" src="https://github.com/microsoft/WinAppDriver/assets/74744300/5e884710-53ff-44cd-8423-05e590ca8758">

Please let me know if any required info.

**Comment by anunay1** [comment]
I get this exception when the system gets' locked. Are you staring winappdriver.exe once or in every test case.

**Comment by ravi46kom** [comment]
Hello @anunay1 
i'm starting once but my system isn't getting locked.

**Comment by anunay1** [comment]
ok, do you get this exception randomly or none of the test cases are working. There is a bug with winappdriver.exe that it does not flush the message the the messages are buffered, it's always better to start the winaddpdriver.exe before the test case and close it after the test case.

**Comment by ravi46kom** [comment]
i'm doing same but getting error. it's random but i didn't found any complete run without error. while trying with single test case it runs fine. i got confused in it.

**Comment by anunay1** [comment]
Was it working fine with .net 4.7

**Comment by ravi46kom** [comment]
no but a bit good as compare to net 6

**Comment by anunay1** [comment]
Can you share the code?

**Comment by anunay1** [comment]
Is the VM in cloud?

**Comment by ravi46kom** [comment]
yes

**Comment by anunay1** [comment]
Azure

**Comment by ravi46kom** [comment]
and all the test case running fine on local

**Comment by anunay1** [comment]
Are you using the default port 4623? Are you launching the VM through the pipeline? I don't know whether it will fix the issue or not but try changing the port.

**Comment by ravi46kom** [comment]
4273

**Comment by ravi46kom** [comment]
thanks I'll try with other port. let see it'll fix or not, i'll reply tomorrow about the result. Thanks @anunay1 for the response.

**Comment by ravi46kom** [comment]
same errors with other ports.

**Comment by anunay1** [comment]
I am not sure what's wrong at ur end, can you schedule a teams call?

**Comment by ajimiathul** [comment]
@anunay1 @ravi46kom Is this issue resolved? Any inputs ?

**Comment by ravi46kom** [comment]
Hi @anunay1 
I got the solution. In my case I got my VM locked while running test cases. I've worked on that. And it looks fine to close this ticket, Thanks for your support.

**Comment by Aswin-Victor** [comment]
Hey @ravi46kom  @anunay1 

i am also facing this issue.
"OpenQA.Selenium.UnknownErrorException : An unknown server-side error occurred while processing the command. Original error: An unknown error occurred in the remote end while processing the command."

In my case, when i trigger the job in Jenkins and Keep the Azure VM RDP session open in my machine, then the Windows UI Tests runs fine. But if the RDP session isn't open then the tests gets failed with the above exception. Stuck in this case for a couple of days.
Could you please help me with your finding?

How can i keep the the tests running with out RDP into my Azure VM?

**Comment by anunay1** [comment]
You would need to have a batch file with tscon.exe to auto login.

**Comment by anunay1** [comment]
https://support.smartbear.com/testcomplete/docs/testing-with/running/via-rdp/keeping-computer-unlocked.html

**Comment by anunay1** [comment]
Please update the settings in azure VM to never time out.

**Comment by Aswin-Victor** [comment]
Thanks for the response @anunay1 .

But even after doing these steps, still i am getting the same exception.
I have executed the command, then the VM RDP session got disconnected. Then i triggered the Jenkins job immediately. But the run failed with the same exception.

Is there any other alternatives i can do to resolve this issue?

**Comment by anunay1** [comment]
Is the VM launched using Jenkins pipeline?

**Comment by Aswin-Victor** [comment]
No. I have manually connected the Jenkins with the Azure VM by executing the "agent.jar" command, before disconnecting the RDP session. Then i triggered the Job in Jenkins.

**Comment by anunay1** [comment]
Then VM is not launched successfully using Jenkins job. Can you check in the Jenkins job that the VM has launched successfully.

**Comment by Aswin-Victor** [comment]
Yes it is launched successfully. 
The previous stages mentioned in the JenkinsFile (Cleanws , Clone, Restore, Build ) are working fine. When it comes to the "Run UI test" stage only i am getting this exception.
Since it is an windows application, it is unable to interact with the UI elements without having the VM RDP session in open

**Comment by anunay1** [comment]
Interesting!!! Can you verify if the winappdriver.exe is successfully launched on VM.

**Comment by Aswin-Victor** [comment]
Yes it is.
Because earlier i tried to keep the VM window open when the "UI test run" stage was started. I could see the test running. After a couple of test runs, i minimized the RDP session. From then the tests started failing with that exception.
Don't know how to resolve it..

**Comment by anunay1** [comment]
Can you verify theses settings on azure VM 
![image](https://github.com/user-attachments/assets/077d47a9-72f0-4a42-b617-803a6ea1ef44)

**Comment by anunay1** [comment]
UI tests will not run in minimise mode. If it's a system then one needs to modify the registry. I had given a solution to some one. Let me find out and share.

**Comment by anunay1** [comment]
https://support.smartbear.com/testcomplete/docs/testing-with/running/via-rdp/in-minimized-window.html

**Comment by Aswin-Victor** [comment]
Thanks for sharing these. Let me try out..
But my ultimate AIM is to run the Windows application UI tests in my Azure VM (Without RDP) by triggering the Jenkins Job.
It can be achieved right?

**Comment by anunay1** [comment]
Yes it should be.

**Comment by Aswin-Victor** [comment]
After following the above steps, now i can successfully run my UI tests with RDP session minimized. 
But when i tried to run the same **without taking RDP**, i am getting the **same exception.**
ie, I executed the "**tscon 4 /dest:console**" command as an administrator to come out of the RDP session.

Note: I don't have the following path in my machine "HKEY_CURRENT_USER\Software\Wow6432\Microsoft\Terminal Server Client" as mentioned in this doc "https://support.smartbear.com/testcomplete/docs/testing-with/running/via-rdp/in-minimized-window.html"

**Comment by anunay1** [comment]
Issue is there with azure VM. It appears that the UI is not up in VM. I had implemented the same solution with azure pipeline but not with Jenkins and it worked flawlessly. Raise a support ticket in azure.

**Comment by Aswin-Victor** [comment]
Yeah sure. Thanks for the support @anunay1
