### ISSUE TITLE
WinAppDriver not able to find WPF elements

### ISSUE THREAD

**Issue by joshmansky** [microsoft/WinAppDriver#1917]
Hello, I am using WinAppDriver to connect to an application that says it is Win32 but that inspect.exe lists as WPF(for at least the window and contents frameworkID). I can find all of the content(which is WPF) in the application window through inspect; however, when I tried to find any element in the window Selenium threw an error saying that none could be found using my search parameters, so I printed out the page source for the application, but it only had the correct title bar but none of the WPF content inside. Therefore, I am hoping someone knows what my error is, so that I can access all of the content in my window. I currently think it could have something to do with the page source saying the frameworkID for the window is Win32 but in inspect it says it should be WPF. My code for getting the page source is(PYTHON):

        desired_caps = {
            'app' : gui_exec_path,
        'platformName' : 'Windows',
        'deviceName' : 'WindowsPC',
        'automationName' : 'Windows',
        "appWorkingDir": gui_working_dir,
        "win_app_driver_host": "http://127.0.0.1:4723",
        "ms:waitForAppLaunch" : 15,
    }
    driver = webdriver.Remote(command_executor="http://127.0.0.1:4723",
        desired_capabilities= desired_caps)
    time.sleep(5)
    print(driver.page_source)
    driver.quit()

Page Source Output(should be able to click on it to see better resolution):

![PageSourceOut](https://github.com/microsoft/WinAppDriver/assets/113480306/5e72f9e8-feb6-4576-814d-a2b25f4f1695)

Inspect Output:
![inspect_menuview](https://github.com/microsoft/WinAppDriver/assets/113480306/7221964a-964a-41df-88ec-f7910bbef52a)
![inspect_window_content](https://github.com/microsoft/WinAppDriver/assets/113480306/aca0a032-68c5-47da-b72b-503e30d280e2)

**Comment by Shakevg** [comment]
[joshmansky](https://github.com/joshmansky) may be several windows, can you try to create a session after the app starts by process or window title and then check page source?
https://github.com/microsoft/WinAppDriver/issues/534#issuecomment-562030077 (Python code you can find in comments)
