### ISSUE TITLE
Request to WinAppDriver times out while searching for element in app

### ISSUE THREAD

**Issue by caulfield2** [Microsoft/WinAppDriver#192]
When executing a unit test, WinAppDriver times out before an element on the app in test can be located, causing my tests to fail. I have tried adding desktopCapabilities.SetCapability("newCommandTimeout", 180); as well as an implicitly wait command, but the tests still time out after 60 seconds. 
![image](https://cloud.githubusercontent.com/assets/25783833/26496828/a596ac6c-41ee-11e7-83db-3b06a90d8644.png)

Is there any way to extend the amount of time WinAppDriver waits to time out?

**Comment by caulfield2** [comment]
My solution to this was to "nest" my search by narrowing down the search field, significantly reducing the search time. See example below:

`protected static WindowsElement Parent;`
`protected static WindowsElement Child;`

`Parent = driver.FindElementByName("parentName");`
`Child = (WindowsElement)Parent.FindElementByName("childName");`
`Child.Click();`

**Comment by timotiusmargo** [comment]
Hello @caulfield2,

The 60 seconds timeout you encountered above didn't come from **WinAppDriver**. Instead it is the default **commandTimeout** that is enforced by the client (Appium DotNet Driver and others).

When using [Appium DotNet Driver](https://github.com/appium/appium-dotnet-driver) like the one we use in our samples and test, you can override the **commandTimeout** as follows:

```c#
 // Launch Notepad Classic Windows Application
WindowsDriver<WindowsElement> NotepadSession;
DesiredCapabilities appCapabilities = new DesiredCapabilities();
appCapabilities.SetCapability("app", NotepadAppId);
NotepadSession = new WindowsDriver<WindowsElement>(new Uri(AppDriverUrl), appCapabilities, TimeSpan.FromMinutes(5));
```

Notice the last argument passed into the WindowsDriver argument:
```c#
//
// Summary:
//     Initializes a new instance of the WindowsDriver class using the specified remote
//     address, desired capabilities, and command timeout.
//
// Parameters:
//   remoteAddress:
//     URI containing the address of the WebDriver remote server (e.g. http://127.0.0.1:4723/wd/hub).
//
//   desiredCapabilities:
//     An OpenQA.Selenium.Remote.DesiredCapabilities object containing the desired capabilities.
//
//   commandTimeout:
//     The maximum amount of time to wait for each command.
public WindowsDriver(Uri remoteAddress, DesiredCapabilities desiredCapabilities, TimeSpan commandTimeout);
```

**Comment by naeemakram** [comment]
Thanks for sharing, this was helpful.
