### ISSUE TITLE
Testing Windows 10 Desktop Application

### ISSUE THREAD

**Issue by mzbedat** [Microsoft/WinAppDriver#195]
Hi,
I'm trying to figure out how to test Windows application with WinAppDriver (the other option is to use codedUI which cost money). 

I have some doubts:

1. Windows Application Driver supports testing Universal Windows Platform (UWP), and Classic Windows (Win32 ONLY!) apps on Windows 10 PC.
Does that means that it's only support Windows 10, older windows versions can be supported as well? 
Can't run Win64 Apps at all?

2. We can choose any programming language or tools supported by Appium/Selenium to write our own test scripts.
I'm tryingto use Java with eclipse:
><dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            
            <version>LATEST</version>
        </dependency>
        
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>LATEST</version>
    		<scope>test</scope>
        </dependency>

`private static WindowsDriver<WindowsElement> NotepadSession;
	
	@BeforeClass
    public static void setup() {
        try {
        	// Launch Notepad
        	DesiredCapabilities appCapabilities = new DesiredCapabilities();
        	appCapabilities.setCapability("app", "C:\\Windows\\System32\\notepad.exe");
        	//appCapabilities.setCapability("platformName", "Windows");
        	//appCapabilities.setCapability("deviceName", "WindowsPC");
        	NotepadSession = new WindowsDriver<WindowsElement>(new URL("http://127.0.0.1:4723"), appCapabilities);

        	// Control the Notepad app
        	//NotepadSession.findElementByClassName("Edit").sendKeys("This is some text");

        }catch(Exception e){
            e.printStackTrace();
        } finally {
        }
    }
	
	@Test
	public void edit(){
		// Control the Notepad app
    	NotepadSession.findElementByClassName("Edit").sendKeys("This is some text");
	}`

At the beginning I got some MethodNotFound exception then I understood that its something with versions so I changed the dependencies to use latest.
But Now I'm getting:

> org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{app=C:\Windows\System32\notepad.exe, platformName=Windows}], required capabilities = Capabilities [{}]
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-DJ1UAII', ip: 'xxxxxxx', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_92'
Driver info: driver.version: WindowsDriver
	at io.appium.java_client.remote.AppiumProtocolHandShake.lambda$1(AppiumProtocolHandShake.java:96)
	at java.util.Optional.orElseThrow(Optional.java:290)

I guess the root cause that the WindowsDriver wasn't created as expected and then the test that is trying to use it failed with SessionNotCreated.

What I had tried:

- Installing the AppiumDesktop application and giving it the same capabilities, but when trying to run it am getting:
Error
An unknown server-side error occurred while processing the command. Original error: Could not verify WinAppDriver install; re-run install

- WinAppDriver is installed, but when I try to run it (from: C:\Program Files (x86)\Windows Application Driver) a console window is opened and closed immediately!

In general, do I need to use the AppiumDesktop or its enough just to load the WinAppDriver console?
The AppiumDesktop is more effective for windows application on mobile phones, am I correct?

Please help, I'm confused.

Best.

**Comment by mzbedat** [comment]
Regarding opening the WinAppDriver issue (and based on other issue that I found talking about the same), I ran it from command line and realized that there is a Developer Mode on windows 10 that needs to be enabled.
Now the WinAppDriver console is opened and listening to the port (that answers my question if AppiumDesktop is needed or not as well).

The notepad application was opened.
Just if you can please answer my doubts if it can be used win64 apps as well and if it support older versions of window.
One more doubt is about best practice for identifying elements, what is recommended? I found UISpy.exe

**Comment by yodurr** [comment]
Hi @mzbedat yes you can test 64bit apps as well.

Yes, recommend using inspect.exe to identify elements.  The Appium Desktop product will also be a viable tool once a few bugs are addressed (and helping enable a great Appium Desktop experience for Windows Apps is on our backlog).

**Comment by yodurr** [comment]
You don't need to use Appium to run your tests.  You can use Appium but pointing your tests directly at WinAppDriver will also work.

We only support Windows PC at the moment, so there currently is no solution for Windows Phone.  Appium works with Windows desktop apps - take a look at the Appium documentation.  While Appium has been a mobile focused effort the vision is to expand test any type of device.  And now with WinAppDriver you can test Windows desktop apps with Appium :)

**Comment by mzbedat** [comment]
Thanks Yousef for your clarifications.
I'm still missing how to use Appium Desktop for testing Windows app, I tried setting up the capabilities as follow:
app = path to my app.exe 
platformName = Windows
deviceName = WindowsPC

but when starting a new session am getting:
![image](https://cloud.githubusercontent.com/assets/17043182/26723622/066cff1e-479e-11e7-97d9-7cea51948de9.png)
The WinAppDriver is installed, but I can't run it in parallel to Appium cause its using the same port! should I change the default port for one of them in order to work together?

**Comment by jsingh-qualitrol** [comment]
I am also facing the same issue 

The server is running

[Appium] Welcome to Appium v1.7.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 5 ms - 40 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"C:\\Windows\\System32\\notepad.exe","deviceName":"WindowsPC","platformName":"Windows","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"C:\\Windows\\System32\\notepad.exe","deviceName":"WindowsPC","platformName":"Windows","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1510044529079 (14:18:49 GMT+0530 (India Standard Time))
[Appium] Creating new WindowsDriver (v0.5.0) session
[Appium] Capabilities:
[Appium]   app: 'C:\\Windows\\System32\\notepad.exe'
[Appium]   deviceName: 'WindowsPC'
[Appium]   platformName: 'Windows'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] The following capabilities were provided, but are not recognized by appium: app, connectHardwareKeyboard.
[BaseDriver] Session created with session id: 634708dc-199b-470e-9c66-4fd1f835bc06
[WinAppDriver] Verifying WinAppDriver is installed with correct checksum
[WinAppDriver] Deleting WinAppDriver session
[MJSONWP] Encountered internal error running command: Error: Could not verify WinAppDriver install; re-run install
    at WinAppDriver.start$ (C:\Users\jsingh\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-windows-driver\lib\winappdriver.js:35:13)
    at tryCatch (C:\Users\jsingh\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\jsingh\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\jsingh\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\jsingh\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 71 ms - 190 
@mzbedat @yodurr @timheuer @jonstoneman @cmaneu  
I am using latest version of appium , already tried unistall / reintall appium through npm .But of no luck . 
Manuall running Winapp driver then it shows success ...Pls help !!

**Comment by angirachowdhury** [comment]
facing the same issue... Pls Help!!

**Comment by yodurr** [comment]
in the case of this message: 
[MJSONWP] Encountered internal error running command: Error: Could not verify WinAppDriver install; re-run install

It means one of two things:
1) you don't have WinAppDriver installed (look to c:\program files (x86)\Windows Application Driver\winappdriver.exe)
1) you have WinAppDriver installed but it's not the version that Appium is looking for.  We have a code change coming to Appium to make the error message tell you which version it is looking for.  

For the latest version of Appium Desktop v1.2.7 you need WinAppDriver version v0.9-beta.  Apologies this is confusing - hopefully the logging additions which will ship in future versions of Appium will help.

**Comment by Archer456** [comment]
Hello every I have resolved this problem.
just

解决掉了这种报错:
MSBUILD : error MSB3428: 未能加载 Visual C++ 组件“VCBuild.exe”。要解决此问题，1) 安装 .NET Framework 2.0 SDK；2) 安装 Microsoft Vis ual Studio 2005；或 3)
如果将该组件安装到了其他位置，请将其位置添加到系统路径中。 [D:\nodejs\node-global\node_modules\appium\node_modules\heapdump\build\bi nding.sln]
解决掉了这种警告:

appium-windows-driver@1.0.0 install D:\nodejs\node-global\node_modules\appium\node_modules\appium-windows-driver
node install-npm.js
info WinAppDriver You must use WinAppDriver version 1.0
info WinAppDriver Verifying WinAppDriver version 1.0 is installed via comparing the checksum.
info WinAppDriver WinAppDriver.exe doesn't exist at the correct version 1.0, setting up
WARNING: You are not running as an administrator so WinAppDriver cannot be installed for you; please reinstall as admin
WinAppDriver was not installed; please check your system and re-run npm install if you need WinAppDriver
heapdump@0.3.9 install D:\nodejs\node-global\node_modules\appium\node_modules\heapdump
node-gyp rebuild
D:\nodejs\node-global\node_modules\appium\node_modules\heapdump>if not defined npm_config_node_gyp (node "D:\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild ) else (node "D:\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
具体解决步骤:
最终的方法,期间参考一些折腾了一些其他的,反复试了几次,应该是这样的步骤:

1 卸载 npm uninstall appium -g
哦 实际 我也开启了 win10 的开发人员模式,此步是不是必要 我暂时不清楚,参考乱七八糟的帖子 折腾了许多,所以并不知道 是否此步必要

2 去 https://developer.microsoft.com/zh-cn/windows/downloads/windows-10-sdk 下载 .iso

一共760多MB 16299.15.170928-1534.rs3_release_WindowsSDK.iso win10 可以直接双击该iso 便会加载为一个光盘DVD驱动器,进去,直接双击WinSDKSetup.exe 安装即可.默
认路径,默认features全选择

3 https://github.com/Microsoft/WinAppDriver/releases 下载v1.0 的WindowsApplicationDriver.msi .
安装到默认C:\Program Files (x86)\Windows Application Driver
路径,然后命令行到该路径,尝试启动下

保证启动正常. 保证正常启动不报错后,就可以关掉了,安装其他过程中不需要保证开启该 server

4 管理员权限 powershell 执行 npm install --global --production windows-build-tools
过程很长,需要在线下载一些组件.我全程科学上网.

Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。
PS C:\WINDOWS\system32> npm install --global --production windows-build-tools

windows-build-tools@2.2.1 postinstall D:\nodejs\node-global\node_modules\windows-build-tools
node ./lib/index.js
Downloading BuildTools_Full.exe
Downloading python-2.7.14.amd64.msi
[> ] 0.0% (0 B/s)
Downloaded python-2.7.14.amd64.msi. Saved to C:\Users\cmd.windows-build-tools\python-2.7.14.amd64.msi.
Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!
Status from the installers:
---------- Visual Studio Build Tools ----------
Successfully installed Visual Studio Build Tools.
------------------- Python --------------------
Successfully installed Python 2.7

windows-build-tools@2.2.1
added 132 packages in 1365.525s
5 管理员权限 powershell 执行npm i appium -g
然后就正常了 没WARNING了.

PS C:\WINDOWS\system32> npm i appium -g
D:\nodejs\node-global\appium -> D:\nodejs\node-global\node_modules\appium\build\lib\main.js

appium-chromedriver@3.1.4 install D:\nodejs\node-global\node_modules\appium\node_modules\appium-chromedriver
node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.33' for platform 'win' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_win32 to...
info Chromedriver Install Downloading https://chromedriver.storage.googleapis.com/2.33/chromedriver_win32.zip...
info Chromedriver Install Writing binary content to C:\Users\cmd\AppData\Local\Temp\2018317-14572-briz5r.jt6ow\chromedriver_win32.zip...
info Chromedriver Install Extracting C:\Users\cmd\AppData\Local\Temp\2018317-14572-briz5r.jt6ow\chromedriver_win32.zip to C:\Users\cmd\AppData\Local\Temp\2018317-14572-briz5r.jt6ow\chromedriver_win32
info Chromedriver Install Creating D:\nodejs\node-global\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win...
info Chromedriver Install Copying unzipped binary, reading from C:\Users\cmd\AppData\Local\Temp\2018317-14572-briz5r.jt6ow\chromedriver_win32\chromedriver.exe...
info Chromedriver Install Writing to D:\nodejs\node-global\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe...
info Chromedriver Install D:\nodejs\node-global\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe successfully put in place

appium-selendroid-driver@1.6.6 install D:\nodejs\node-global\node_modules\appium\node_modules\appium-selendroid-driver> node ./bin/install.js

dbug AndroidDriver Getting Java version
info AndroidDriver Java version is: 1.8.0_121
info Selendroid Ensuring D:\nodejs\node-global\node_modules\appium\node_modules\appium-selendroid-driver\selendroid\download exists
info Selendroid Downloading Selendroid standalone server version 0.17.0 from http://repo1.maven.org/maven2/io/selendroid/selendroid-standalone/0.17.0/selendroid-standalone-0.17.0-with-dependencies.jar --> D:\nodejs\node-global\node_modules\appium\node_modules\appium-selendroid-driver\selendroid\download\selendroid-server-7cf7163ac47f1c46eff95b62f78b58c1dabdec534acc6632da3784739f6e9d82.jar
info Selendroid Writing binary content to D:\nodejs\node-global\node_modules\appium\node_modules\appium-selendroid-driver\selendroid\download\selendroid-server.jar.tmp
info Selendroid Selendroid standalone server downloaded
info Selendroid Determining AndroidManifest location
info Selendroid Determining server apk location
info Selendroid Extracting manifest and apk to D:\nodejs\node-global\node_modules\appium\node_modules\appium-selendroid-driver\selendroid\download
info Selendroid Copying manifest and apk to D:\nodejs\node-global\node_modules\appium\node_modules\appium-selendroid-driver\selendroid
info Selendroid Cleaning up temp files
info Selendroid Fixing AndroidManifest icon bug

appium-uiautomator2-driver@0.11.0 install D:\nodejs\node-global\node_modules\appium\node_modules\appium-uiautomator2-driver
node ./bin/install.js

dbug AndroidDriver Getting Java version
info AndroidDriver Java version is: 1.8.0_121
info UiAutomator2 downloading UiAutomator2 Server APK v0.3.0 : https://github.com/appium/appium-uiautomator2-server/releases/download/v0.3.0/appium-uiautomator2-server-v0.3.0.apk
info UiAutomator2 downloading UiAutomator2 Server test APK v0.3.0 : https://github.com/appium/appium-uiautomator2-server/releases/download/v0.3.0/appium-uiautomator2-server-debug-androidTest.apk
info UiAutomator2 UiAutomator2 Server APKs downloaded

appium-windows-driver@1.0.0 install D:\nodejs\node-global\node_modules\appium\node_modules\appium-windows-driver
node install-npm.js

info WinAppDriver You must use WinAppDriver version 1.0
info WinAppDriver Verifying WinAppDriver version 1.0 is installed via comparing the checksum.
info WinAppDriver WinAppDriver.exe version 1.0 already exists with correct checksum, not re-downloading

heapdump@0.3.9 install D:\nodejs\node-global\node_modules\appium\node_modules\heapdump
node-gyp rebuild

D:\nodejs\node-global\node_modules\appium\node_modules\heapdump>if not defined npm_config_node_gyp (node "D:\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild ) else (node "D:\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
heapdump.cc
Creating library D:\nodejs\node-global\node_modules\appium\node_modules\heapdump\build\Release\addon.lib and object D:\nodejs\node-global\node_modules\appium\node_modules\heapdump\build\Release\addon.exp
Generating code
Finished generating code
addon.vcxproj -> D:\nodejs\node-global\node_modules\appium\node_modules\heapdump\build\Release\addon.node
addon.vcxproj -> D:\nodejs\node-global\node_modules\appium\node_modules\heapdump\build\Release\addon.pdb (Full PDB)

pre-commit@1.2.2 install D:\nodejs\node-global\node_modules\appium\node_modules\pre-commit
node install.js

wd@1.5.0 install D:\nodejs\node-global\node_modules\appium\node_modules\wd
node scripts/build-browser-scripts

spawn-sync@1.0.15 postinstall D:\nodejs\node-global\node_modules\appium\node_modules\spawn-sync
node postinstall

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\appium\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

appium@1.7.2
added 1375 packages in 682.967s
