### ISSUE TITLE
How to access the button inside CellEditor using WinappDriver

### ISSUE THREAD

**Issue by RamyaThirumalaisamy** [microsoft/WinAppDriver#1951]
Note : The controls are WPF Controls

In UI It will looks like this
![image](https://github.com/microsoft/WinAppDriver/assets/62684045/57e4bf6e-1abe-4153-add3-988b7304aec1)
Here I want to click Detect button (Or) the near by download symbol button.

I used WinAppDriverUIRecorder to get more details about the button. If I hover over my mouse to detect button, below is the screenshot from WAD Ui Recorder
![image](https://github.com/microsoft/WinAppDriver/assets/62684045/b4fe4e13-0dc8-43b4-b575-482f8d8d9143)

So there is no detect button control item in this screenshot.

Also I have tried Visual Studio Live Visual Tree option to access the button. The Hierarchy is something like this here.
![image](https://github.com/microsoft/WinAppDriver/assets/62684045/a0717996-bc01-4ba3-ad3a-fd66cafabd99)
I have assigned automation id for this detect button using visual studio. But In page source I couldn't able to find the button. Do I need to do some more action to get enabled those buttons? or these buttons come under child elements of any other controls?

In .xaml file the buttons and combobox are  present inside DataTemplate tag. (I can able to access the combobox).

So any idea how can I get the access of the button?

**Comment by liljohnak** [comment]
Check this code out.  You do not have the button added to the AutomationPeer.
https://stackoverflow.com/questions/43230197/automationelement-for-wpf-togglebutton-have-classname-button

**Comment by RamyaThirumalaisamy** [comment]
@liljohnak But I have Automation peer for this button. See the below screenshot from live visual tree.
![image](https://github.com/microsoft/WinAppDriver/assets/62684045/56a1775c-278c-4627-be3f-2f2c3c56e364)

**Comment by liljohnak** [comment]
@RamyaThirumalaisamy have you tried .FindElementByAccessibilityId("D6BA75BA...").Click();

**Comment by RamyaThirumalaisamy** [comment]
@liljohnak Yes I have tried that. But I am getting error as "An element could not be located using given search parameters".

**Comment by liljohnak** [comment]
@RamyaThirumalaisamy .FindElement requires the button to have a clickable point.
using system.linq;
```
var buttons = FindElementsByAccessibilityId("D6BA75BA...");
var button = buttons.FirstOrDefault();
if(button == null) return;
button.Location.Click();// we extended our System.Drawing.Point class to have a click method.  
```
Also Location is limited to using 1 monitor.  You can use .GetAttrbute("BoundingRectangle") to use two monitors.

**Comment by RamyaThirumalaisamy** [comment]
@liljohnak Thanks for your patience and help! From my side I have analyzed little bit to understand this issue. So closing this issue here and opening a new[ one](https://github.com/microsoft/WinAppDriver/issues/1953#issue-1978311980).
