### ISSUE TITLE
Unable to identify the element

### ISSUE THREAD

**Issue by ritusenleo** [microsoft/WinAppDriver#1963]
In the application after clicking a button , a dialog box appear from where a button need to be clicked.
Unable to identify the floating dialog box. 

Tried the followings, but nothing worked:
1. var dialog = driver.FindElementByName("XXXX");
   dialog.FindElementByAccessibilityId("6").Click();

2.  var appiumOptions = new AppiumOptions();
 var _configurationDriver = new ConfigurationDriver();
 appiumOptions.AddAdditionalCapability("app", "Root");
 string appSetting = _configurationDriver.Configuration["winAppUri"];
 var remoteAddress = new Uri(appSetting);
 var driverRoot = new WindowsDriver<WindowsElement>(remoteAddress, appiumOptions);
var dialog = driverRoot.FindElementByName("XXXX");
  dialog.FindElementByAccessibilityId("6").Click();

3.  string topWindow = driverRoot.FindElementByName("XXXX").GetAttribute("NativeWindowHandle");
 int MAWinHandleInt = Int32.Parse(topWindow);
 string MAWinHandleHex = MAWinHandleInt.ToString();
 Console.WriteLine("Success2");
 var apOpt = new AppiumOptions();
apOpt.AddAdditionalCapability("appTopLevelWindow", MAWinHandleHex);
 var drv = new WindowsDriver<WindowsElement>(remoteAddress, apOpt);
 drv.FindElementByAccessibilityId("6").Click();

Any suggestion please

**Comment by anunay1** [comment]
Your code is correct. I don't find any reason for it not to work. Can you get the page source.

**Comment by ritusenleo** [comment]
@anunay1 can we please connect, it will be easy for me ....

**Comment by anunay1** [comment]
Were you able to solve this? if not send a zoom call request.

**Comment by ritusenleo** [comment]
Developers are doing one fix..
They asked me to test in the new build...
Will update on this, hopefully next week.

**Comment by ritusenleo** [comment]
it is  solved after the fix.

**Comment by anunay1** [comment]
But what did they fix.

**Comment by ritusenleo** [comment]
They just took the floating dialog box under the application.
