### ISSUE TITLE
FindElementById always throws

### ISSUE THREAD

**Issue by mgnsm** [Microsoft/WinAppDriver#197]
FindElementById always seems to throw an InvalidOperationException  no matter what id I pass to it. Consider the following sample code where I try to click the number 5 button in the Calculator app:

```
DesiredCapabilities appCapabilities = new DesiredCapabilities();
appCapabilities.SetCapability("app", "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App");
appCapabilities.SetCapability("deviceName", "WindowsPC");
using (var session = new WindowsDriver<AppiumWebElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities))
{
    Assert.IsNotNull(session);
    CalculatorSession.FindElementById("42.5375952.3.59").Click();
}
```
inspect.exe lists the RuntimeId property of this button as [2A.5207D0.3.3B] so I converted this to a decimal value that I pass as an argument to the FindElementById method as per above but the button cannot be found for some reason. 

I know that I can use the FindElementByName or FindElementByAccessibilityId method to find it in this particular example but but why isn't the FindElementById method working? Is this a bug or am I missing something? Shouldn't the FindElementById method look for the RuntimeId of the element?

**Comment by yodurr** [comment]
The runtime ID is not a constant like AutomationId or Name is, will change between application instances.  Why do you want to use the RuntimeID?

**Comment by mgnsm** [comment]
I'm trying to find an element on a web page in Edge that unfortunately doesn't have a name.

How is the FindElementById method supposed to be used if the RuntimeId of an element is different for each run?

**Comment by timotiusmargo** [comment]
Hello @mgnsm,

`FindElementById` does indeed work when you passed the right (valid and current) element id. Below is an example wire protocol payload of finding element by id returning the right reference to the element.

```
POST /session/C2E9172C-6109-432E-8FF2-9D964A6AEB3F/element HTTP/1.1
Accept: application/json, image/png
Content-Length: 39
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"using":"id","value":"42.5310404.3.3"}

HTTP/1.1 200 OK
Content-Length: 100
Content-Type: application/json

{"sessionId":"C2E9172C-6109-432E-8FF2-9D964A6AEB3F","status":0,"value":{"ELEMENT":"42.5310404.3.3"}}
```

Below is the C# snippet code that takes an id of a valid element and use it to find the same element.

```c#
WindowsElement navButton = session.FindElementByAccessibilityId("NavButton");
Assert.AreEqual("ControlType.Button", navButton.TagName);

WindowsElement navButtonById = session.FindElementById(navButton.Id);
Assert.AreEqual("ControlType.Button", navButtonById.TagName);

Assert.AreEqual(navButton, navButtonById);
```

As @yodurr pointed out, the **RuntimeId** will change the next time you restart the application or reconstruct that particular UI element. Hence, it is not the best method to locate your element.
