### ISSUE TITLE
Unable  to map a new winappdriver to the existing open application

### ISSUE THREAD

**Issue by ritusenleo** [microsoft/WinAppDriver#1971]
At the end of first test case, closed the winappdriver.exe and then open new winappdriver.
The application is already open but now the driver is unable to map the application.

Kindly help please

**Comment by Shakevg** [comment]
[ritusenleo](https://github.com/ritusenleo) Please post code example and error that you got.

**Comment by HowTurnRight** [comment]
You need to attach to root window, find your application by window name or class name and switch window handle to it.

**Comment by ritusenleo** [comment]
It is solved now, I just close and thenopen the driver in between the tests
