### ISSUE TITLE
Extracting data from ListBox item

### ISSUE THREAD

**Issue by mooragor** [microsoft/WinAppDriver#1990]
I'm testing an old application which has a ListBox.  In the app itself I can see the list of names in the ListBox, however when using Inspect.exe, I can't find the displayed text anywhere. 

I've been able to get hold of all of the ListBox items using WinApDriver, but again, can't find the 'text' within the item object to be able to pick the right one to click.

I'm guessing that if Inspect can't see that text that it's also not accessible to WinApDriver.  
Is there anything I can do to make that text visible? Do I need to modify the data object that is being listed to have accessor methods or something (data object below)

![image](https://github.com/microsoft/WinAppDriver/assets/29462732/71748c9f-3b84-4687-a603-d71aa3b49b72)

![image](https://github.com/microsoft/WinAppDriver/assets/29462732/bf94a3b4-3904-461c-8cab-d276494f4753)

![image](https://github.com/microsoft/WinAppDriver/assets/29462732/24e92823-7b60-43c1-8bae-6934bea85599)

![image](https://github.com/microsoft/WinAppDriver/assets/29462732/31b6e149-4ef5-41a4-ae56-6c779d1ce13b)

**Comment by HowTurnRight** [comment]
Sometimes this text is displayed from value field, sometimes from Name and sometimes from other attribute. Not always it will be accessible for winappdriver.

**Comment by mooragor** [comment]
Any details on why data may not be available to WinAppDriver, or what can be changed in the code of the application to make it available?

**Comment by HowTurnRight** [comment]
Like I mentioned in comment above. Try to find element with a locator that hold list item and try to inspect LegacyName and LegacyValue attributes for this and child element. Not always must be nested text element. If none of the elements that can be located hold any sign of that text there is possibility it is just a winappdriver limitation.

**Comment by liljohnak** [comment]
@mooragor I believe the first document after the list item has it.
AppiumWebElement document;
document.GetAttribute("Value");

Sometimes you get lucky and you can simply do:
ListItem.Text;
