### ISSUE TITLE
Not able to scroll with Touch Action class

### ISSUE THREAD

**Issue by junaid-ansari312** [microsoft/WinAppDriver#1993]
I am getting error when I try to scroll with Touch Action class as my laptop is not touch screen how can I scroll and also Touch action class supports scroll based on coordinates I want to scroll based on element is there any way to do it.

**Comment by HowTurnRight** [comment]
Try to workarround by send page up page down keys.

**Comment by junaid-ansari312** [comment]
Page down is not working it is similar to open notepad go to Format>Font then try to scroll till any Font name there is different scroll bar for this

**Comment by anunay1** [comment]
Winappdriver supports auto scroll till 41 st element. Check in inspect for the property isscrollable it should be set to true.
