### ISSUE TITLE
Unable to return to next line

### ISSUE THREAD

**Issue by isonic1** [Microsoft/WinAppDriver#20]
I’m experiencing issues with text fields and creating a new line by either \n, or sending an action to press the enter key. When the enter key is pressed it’s creating a symbol (e.g. []) instead of returning to the next line.

Ruby:
win.find_element(:name, "textField").send_keys "ENTER TEXT AND GOTO NEW LINE\n"
or
win.find_element(:name, "textField").send_keys [:return]

**Comment by khouzam** [comment]
Have you tried to send a string with \r\n instead of just \n? On Windows, both carriage-return and newline are required.

**Comment by isonic1** [comment]
That unfortunately didn't work either. Thank you for the suggestion, though.

**Comment by alakshmi1030** [comment]
As of the <a href=https://github.com/Microsoft/WinAppDriver/releases/tag/v0.4-beta>v0.4 release</a>, sending a \n escape character string with SendKeys should create a new line. Please reopen if you are still experiencing this.

**Comment by sayedsaad07** [comment]
There is still an issue 
Using \n works fine 
but using \r\n creates 2 new lines instead of one 
the output is \r\n\r\n
Any workaround?
