### ISSUE TITLE
Error occuring when establishing connection between appium inspector and windows app

### ISSUE THREAD

**Issue by Larissa09** [microsoft/WinAppDriver#2009]
Error connecting appium inspector and windows app.
Appium v2.5.3
Windows 11
Win app driver v 1.2.1
Error : Failed to create session. An unknown server-side error occurred while processing the command. Original error: The system cannot find the file specified

Capabilities : {
“appium:platformVersion”: “11”,
“appium:deviceName”: “windowsPC”,
“appium:app”: “Chrome._crx_agimnkijcamfeangaknmldooml”,
“appium:automationName”: “Windows”,
“platformName”: “windows”
}

I am trying to establish a connection between appium inspector and the youtube windows app. I keep getting errors.
When I use win app driver 1.2.1, I get error “The system cannot find the file specified”
When I use win app driver v 1.2.99, I get “Failed to create session. An unknown server-side error occurred while processing the command. Original error: WinAppDriver server is not listening within 10000ms timeout. Make sure it could be started manually”

What am I doing wrong here or how can I fix this?

**Comment by anunay1** [comment]
Have you tried this without appium just with winappdriver.exe?

**Comment by Larissa09** [comment]
> Have you tried this without appium just with winappdriver.exe?

Yes I had tried. I got this resovled by changing the port from 4723 to 4723/wd/hub in appium inspector
