### ISSUE TITLE
WinAppDriver Support on Win 2012 server

### ISSUE THREAD

**Issue by Manvibha** [Microsoft/WinAppDriver#202]
Hi Yodurr, 

Is there any plan to support Win OS 2012 server and other what other Windows OS support plan in pipeline ? If you could share some timeline, appreciate it.

thanks,
Mahi

**Comment by yodurr** [comment]
Hi @Manvibha at the moment our focus is on Win10 only and bringing WinAppDriver to more devices that run Win10.

You can upvote additional SKU support here.
https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/13518501-winappdriver-support-to-win-7-and-8

**Comment by VanKrock** [comment]
@yodurr More than 100 votes for windows 7.
