### ISSUE TITLE
Does WinAppDriver (WAD) UI Recorder natively support all frameworks or patterns used in WPF applications, including specific patterns like Caliburn Micro

### ISSUE THREAD

**Issue by ISLForum** [microsoft/WinAppDriver#2035]
Is there any solution to my issue where WPF applications, particularly those using the Caliburn Micro pattern, are not detecting any elements inside a Frame with WinAppDriver (WAD) UI Recorder? Is this expected behavior? Please provide a solution to resolve this

for the workaround added some certain key "AutomationProperties.AutomationId" but the elements never detecting in WinAppDriver (WAD) UI Recorder

please help us thanks

**Comment by liljohnak** [comment]
Can you find the controls without the UIRecorder?
Also, a screenshot from inspect.exe would be helpful.

**Comment by ISLForum** [comment]
https://github.com/user-attachments/assets/db247aa8-6aba-43d7-95b8-7c5c2f0b4aee
Can you find the result. and share your observation .thanks

**Comment by liljohnak** [comment]
@ISLForum does inspect.exe find the elements?

**Comment by ISLForum** [comment]
@liljohnak , never fetch the elements in inspect.exe. please find the result
https://github.com/user-attachments/assets/3774b1d7-58fc-485d-94d1-20bd5a502a71

**Comment by liljohnak** [comment]
@ISLForum looks like this is a limitation for all UAE type frameworks.  You may need to consider an image recognition framework.  (Or maybe something else.)

**Comment by ISLForum** [comment]
Thanks, @liljohnak , for identifying the root cause. So, you're saying it's a limitation of the UI recorder, right

**Comment by liljohnak** [comment]
@ISLForum yes and beyond it.
