### ISSUE TITLE
WPF Application and TabControl

### ISSUE THREAD

**Issue by james1301** [Microsoft/WinAppDriver#206]
Hi,

Testing a WPF application and when I try to access a control within a Tab Item, it isn't finding the element. Below is my code. The application launches correctly and logs in. The application then loads to a certain tab (able to see the elements within that tab), I then use the keyboard to call my shortcut to go to a different tab (which it changes), but then it cannot seem to see anything within the newly selected tab, even tried adding the thread.sleep if it was a timing thing. All of the tabs have basically the same controls inside. I am using a standard wpf tab control and tab items.

Anything I'm doing wrong?

Here is my code:

        [TestMethod]
        public void TestingTest()
        {
            Login();

            _session.Keyboard.PressKey(Keys.LeftControl);
            _session.Keyboard.SendKeys("1");
            _session.Keyboard.ReleaseKey(Keys.LeftControl);

            Thread.Sleep(2000);
            _session.FindElementByAccessibilityId("HomeAreaSearchControl").Click();
            //_session.FindElementByAccessibilityId("PatientsAreaButton").Click();
            //_session.FindElementByAccessibilityId("PeopleAreaButton").Click();
        }

**Comment by james1301** [comment]
Using prism to navigate to my UserControl views in the tab control, if this makes any difference.

No idea of a good way to debug this really. If I have Inspect running, it seems to trigger this to work and see the other tab item's contents.

**Comment by yodurr** [comment]
Can you tell if the tab content is there even though WinAppDriver can't find it?  Sounds like that is the case, that this isn't dynamically created UI giving your UI automation trouble.

What if you move up the UI tree to the app window and search for elements in the control?  Am just curious if where things are parented is the issue.

Could you point me to info on what prism is?

**Comment by james1301** [comment]
Prism is just an MVVM framework we use: https://github.com/PrismLibrary/Prism.

Yeah it's definitely there. I'll try if I can duplicate it in a sample project. Just didn't know if there was something else I should be doing in these scenarios.

**Comment by james1301** [comment]
Struggling to duplicate.

How do you mean to "move up the UI tree to the app window and search for elements in the control?"

**Comment by yodurr** [comment]
By moving up I mean to do your query from the Session object, not from a child element.  That ensures the UI elements you're looking for will be discoverable as we only search down the tree.

**Comment by james1301** [comment]
Ahhh I was just doing it from the session object anyway, so no it doesn't appear to be visible.

**Comment by james1301** [comment]
What seems to have forced it to work is following the following article: http://www.colinsalmcorner.com/post/genericautomationpeer--helping-the-coded-ui-framework-find-your-custom-controls

Just a bit annoying it doesn't work normally, I hope this way is OK to make the AutomationPeers and doesn't provide any problems. The default creation for a tab control just does it for the selected tab, but that doesn't seem to work. Ideally it probably would just do it for the selected tab, so you are limiting the controls that you might see, as I guess it might end up with duplicates, and harder to get the controls you actually want.

**Comment by yodurr** [comment]
If you try inspect.exe and you can see the UI elements then it's a bug with WinAppDriver.  If inspect can't see the controls then you will need to use something like the automation peer or perhaps a bug needs fixing in the framework you're using.

Please let us know if inspect.exe can see the elements.  Thanks!

**Comment by james1301** [comment]
Yeah using inspect.exe showed the elements, and would trigger my automation tests to work as this somehow triggered the elements to be visible for automation.

There does seem to be some WPF issues with Automation of the TabControl.

**Comment by LauraLaureus** [comment]
I know its quite old this thread, but if someone comes here asking how to switch the tabs in Telerik Framework (for WinForms) which uses dynamic loading for the Tabs, it can be done by sending arrow keys to the control. 

Source: 
https://www.telerik.com/forums/using-keyboard-to-move-between-tabs#2elHv9SB6k-lkai5KwvdTg 

Have a nice day.

**Comment by hassanuz** [comment]
Thanks @LauraLaureus for the info. Looks to be solved as per @james1301 's last comment.
