### ISSUE TITLE
Locate cells within data grid

### ISSUE THREAD

**Issue by MaqdoomS** [Microsoft/WinAppDriver#207]
can you help me to locate control which i have circled below,

![image](https://user-images.githubusercontent.com/19201750/27254844-e05085c2-53ae-11e7-8cfc-fbdbf0072da6.png)

I am unable to locate individual cell in data grid. Please find application links below,

[DemoForm1.exe](https://github.com/MaqdoomS/TestDemo/blob/master/Project1.exe)
[GridsDemo.exe](https://github.com/MaqdoomS/TestDemo/blob/master/GridsDemo.exe)

Also i need your help to locate COM/ActiveX control. I will come up with some sample application with such controls.

Thanks,
Maqdoom

**Comment by yodurr** [comment]
You currently can't locate a specific cell using WinAppDriver because the table doesn't expose the cells to UI Automation.  What you can automate depends on what the control provides to UI Automation.

**Comment by timotiusmargo** [comment]
The individual cell within the **DataGrid** control you have in the application is not accessible. In general, Windows Application Driver can only see elements and properties that is shown in [inspect.exe](https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/README.md#inspecting-ui-elements).

As you can see in the `inspect.exe` tool, some of the most useful information you can get from the **DataGrid** above are simply:

| Attribute              | Value                              |
|------------------------|------------------------------------|
| Name                   | "AutomationStringGrid1"            |
| ControlType            | UIA_DataGridControlTypeId (0xC36C) |
| LocalizedControlType   | "data grid"                        |
| ClassName              | "TAutomationStringGrid"            |
| Grid.ColumnCount       | 5                                  |
| Grid.RowCount          | 5                                  |
| Selection.Selection    | "Row 3, Col 2"                     |
| Value.Value            | "Row 3, Col 2"                     |
| Table.ColumnHeaders    | "Title 1"                          |
|                        | "Title 2"                          |
|                        | "Title 3"                          |
|                        | "Title 4"                          |
|                        | "Title 5"                          |
| Table.RowHeaders       |                                    |
| Table.RowOrColumnMajor | 0                                  |

**Comment by sonalinoolkar** [comment]
Hi,
Is there any way to identify  a row in datagrid?
In my scenario, I intend to click on a datagrid row and trying to read row details that are populated in different controls on the same form.

But I could not find a way to identify different rows. Is this possible?
