### ISSUE TITLE
Run local UI test with WinAppDriver for an UWP application(with embedded HTTP listener)

### ISSUE THREAD

**Issue by Korop** [Microsoft/WinAppDriver#208]
Is it possible to run a UI test via WinAppDriver for an UWP application(with internal HTTP listener)  locally when the test and app are run in different processes?

We use WinAppDriver  to  start our app game and communicate with windows native controls during the UI test.
From other side we have to use embedded TCP listener to process custom UI game framework scene element hierarchy. Without that it is just one window with graphic canvas.

In our UWP game we use Windows.Networking.Sockets.StreamSocketListener class to start custom HTTP listener internally. It was also enabled all loopback related capabilities(internetClient, internetClientServer, privateNetworkClientServer), add exemption for the  apps and  win10 host is in Developer mode. 
The test client is written with Java appium client API and run via Maven or IDEA Studio. 
It works fine for remote test clients.  They can reach the embedded HTTP service and receive  response back.

That does not work when test and game are run in different processes on the same host.
The only way I found is to stop Windows Firewall service(MpsSvc) on Local Computer. After that test process can send HTTP request to my UWP game(started on the same host). But after the last windows update I could  not stop the service anymore and windows host denied the connection between test and UWP game.
Note: we could not just disable service MpsSvc on windows startup as it is required to install any UWP application(I was surprised of that).

I will appreciate any help or an idea, success story how to do such testing on local host.  
I believe Microsoft should have a solution for such type of test.

**Comment by hassanuz** [comment]
Hi @Korop,

Are you still experiencing this on the latest version of Windows / WinAppDriver?

**Comment by hassanuz** [comment]
Please reopen if this issue persists.
