### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: [object Object] (Selenium::WebDriver::Error::UnknownError)

### ISSUE THREAD

**Issue by yuvak-vmware** [Microsoft/WinAppDriver#209]
Appium is throwing below error when we try to automate the windows apps. It is launching the app and appium is not able to start and throwing the unknown server-side error. 

Below are the appium logs 

[Appium] Welcome to Appium v1.6.3
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"WINDOWS","platform":"WINDOWS","deviceName":"myDevice","app":"windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel","newCommandTimeout":"600","url":""}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"WINDOWS","platform":"WINDOWS","deviceName":"myDevice","app":"windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel","newCommandTimeout":"600","url":""},null,null,null,null]
[Appium] Creating new WindowsDriver session
[Appium] Capabilities:
[Appium]   platformName: 'WINDOWS'
[Appium]   platform: 'WINDOWS'
[Appium]   deviceName: 'myDevice'
[Appium]   app: 'windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel'
[Appium]   newCommandTimeout: '600'
[Appium]   url: ''
[BaseDriver] Capability 'newCommandTimeout' changed from string ('600') to integer (600). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: platform, app, url.
[BaseDriver] Session created with session id: d0a31be1-3bcc-4ed5-821c-e487ccf54351
[WinAppDriver] Verifying WinAppDriver is installed with correct checksum
[debug] [WinAppDriver] WinAppDriver changed state to 'starting'
[WinAppDriver] Killing any old WinAppDrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"4823 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I winappdriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
[WinAppDriver] No old WinAppDrivers seemed to exist
[WinAppDriver] Spawning winappdriver with: undefined 4823/wd/hub
[WinAppDriver] [STDOUT] Windows Application Driver Beta listening for requests at: http://127.0.0.1:4823/wd/hub
[debug] [WinAppDriver] WinAppDriver changed state to 'online'
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:4823/wd/hub/session] with body: {"desiredCapabilities":{"platformName":"WINDOWS","platform":"WINDOWS","deviceName":"myDevice","app":"windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel","newCommandTimeout":600,"url":""}}
[WinAppDriver] [STDOUT] Press ENTER to exit.
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 220
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4823
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] SessionManager - Creating session
[WinAppDriver] [STDOUT] SessionManager - WinAppDriver succeeded loading MitaBroker
[WinAppDriver] [STDOUT] HTTP/1.1 500 Internal Error
[WinAppDriver] [STDOUT] Content-Length: 133
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [WinAppDriver] Deleting WinAppDriver session
[HTTP] <-- POST /wd/hub/session 500 12958 ms - 152

**Comment by timotiusmargo** [comment]
Hi @yuvak-vmware,

Could you please retry this with [v1.0-RC](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.0-RC) release? I consistently succeed in launching the **Settings** app by creating a session with `windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel` appId.
