### ISSUE TITLE
Calculatortest.py Issue | While running the code, the calculator opens and closes after every defined function runs

### ISSUE THREAD

**Issue by Janemareth** [Microsoft/WinAppDriver#211]
Hi,

While running the python calculator sample test, the calculator opens and closes after every defined function runs. When this occurs, WinAppDriver creates a new session for each function. This does not occur when the c# example runs. 

Thanks 

J

**Comment by Janemareth** [comment]
The issue is in the way they open and close the app with in the Python sample

@classmethod
    def setUpClass(cls):
        # This sets up the appium webdriver
        desired_caps = {}
        desired_caps["app"] = " app "
        cls.driver = webdriver.Remote(
            command_executor='http://127.0.0.1:4723',
            desired_capabilities= desired_caps)
     


    @classmethod
    def tearDownClass(cls):
        cls.driver.quit()

**Comment by timotiusmargo** [comment]
Thanks for looking into this @Janemareth! We should absolutely update our samples sometimes soon.
