### ISSUE TITLE
Menu items not visible to WinAppDriver or Inspect

### ISSUE THREAD

**Issue by eoyslebo** [Microsoft/WinAppDriver#214]
Not sure if this is a WinAppDriver issue, but I can't access menu items in [Autopsy](https://www.sleuthkit.org/autopsy/). Autopsy is a Java/NetBeans based program.

They are not accessible through WinAppDriver/Appium/RobotFramework, and they are not visible to Inspect.

![autopsy screenshot](https://user-images.githubusercontent.com/1457947/27706896-3d2af47a-5d0b-11e7-9339-7e763e40711a.png)

**Comment by yodurr** [comment]
if the elements are not visible to Inspect then WinAppDriver can't see them either.  Not being visible to Inspect means this app is also not accessible.  We recommend logging a bug on Autopsy to make their app accessible and testable.
