### ISSUE TITLE
Proposing an Enhancement in XPath Engine of WinAppDriver w.r.t Inspect.exe

### ISSUE THREAD

**Issue by dhapolapankaj** [Microsoft/WinAppDriver#218]
Hello WinAppDriver Team,

I would like to propose an enhancement in the XPath engine of WinAppDriver.

I see that all windows elements which are available in Inspect.exe have their properties in lowercase
but while building the Page source I see the first letter of Windows elements are uppercase
 like Edit, Window etc..

In below screenshot, the window object mentioned in Inspect.exe and the exported page source shows differently.
![winappdriver-xpath-engine-ehancement](https://user-images.githubusercontent.com/29034223/27833618-3cab0942-60f1-11e7-83a5-e908b4aa602f.png)

If we could have uniformity in object naming then building XPath would be very easy and object discovery would be much simpler.

I learned that W3C specification says the tags mentioned in XPath should be in lower case letter.

**Comment by Exoow** [comment]
@dhapolapankaj True but LocalizedControlType is language dependent (over here I get "venster" in Dutch). So it's a valid remark but not so useful for users whose Windows is not set to English.

On another note: does XPath even work with your WindowsDriver code? Here I get absolutely no results from XPath whatsoever... See issue 216.

**Comment by dhapolapankaj** [comment]
@Exoow It was just an example.
BTW, I am able to locate any windows element present in Page Source. I am very fond of XPath and I use it heavily in my project. The only problem is it is slower than other locators like ID or Name.

The reason I raised this enhancement proposal will resolve your issue. The case sensitivity in XPath tags and attribute is main culprit you are not able to locate elements.
While embarking on WinAppDriver it took me sufficient amount of time to understand the XPath resolution behavior. Just give the Page source, I can locate any element and can create complex XPaths too ;)

Regards
PD

**Comment by Exoow** [comment]
@dhapolapankaj Okay thanks, makes sense.

If you would be so kind to help, here you can see the first part of my Page Source, and my failing XPath. I have tried many variations but none work.
https://sqa.stackexchange.com/questions/28163/appium-why-does-xpath-not-work-at-all-as-expected

**Comment by dhapolapankaj** [comment]
@Exoow could you please try solution mentioned in issue number #216

**Comment by anunayaabb** [comment]
Hi Pankaj 

How can I export page source for a UWP app, for which I don't have the source code i.e I have to automate the UWP app after deployment.

**Comment by timotiusmargo** [comment]
HI @anunayaabb,

`PageSource` attribute is available from any element and can be retrieved as shown in the following snippet taken from https://github.com/Microsoft/WinAppDriver/blob/master/Tests/WebDriverAPI/Source.cs#L39

```c#
var source = session.PageSource;
```

**Comment by dhapolapankaj** [comment]
Hi @anunayaabb 
Please refer the code snippet from here
http://simplifyautomation.blogspot.in/2017/11/code-to-save-iwebdriverpagesource-in.html

**Comment by prasanna532** [comment]
Xpath is throwing element not found exception but through UI recorder i got the below xpath:

/Pane[@Name=\"Desktop 1\"][@ClassName=\"#32769\"]/Window[@Name=\"Calculator ‎- Calculator\"][@ClassName=\"ApplicationFrameWindow\"]/Window[@Name=\"Calculator\"][@ClassName=\"Windows.UI.Core.CoreWindow\"]/Group[@AutomationId=\"NumberPad\"]/Button[@AutomationId=\"num8Button\"][@Name=\"Eight\"]

Anyone look into this what wrong in this

**Comment by hassanuz** [comment]
Hi @prasanna532,

If you're still facing this issue with the latest [WinAppDriver v1.1.1 patch](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.1.1), can you please create a new ticket? Thanks!
