### ISSUE TITLE
Drag and drop InvalidOperationException

### ISSUE THREAD

**Issue by caulfield2** [Microsoft/WinAppDriver#219]
I'm attempting to test the movement of a thumb on a horizontal scrolling thumb and slider using:

`Actions actions = new Actions(driver);`
`var thumb = driver.FindElementByName("thumb");`
`actions.DragAndDropToOffset(thumb, 100, 0);`
`actions.Perform();`

However, I run into an InvalidOperationException on the .Perform() saying that the element could not be located using the given search parameters. Has anyone else had this issue or know of a better way to click and drag elements?

**Comment by yodurr** [comment]
Hi @caulfield2 what test runner are you using and what type of application?

The actions API is something we're investigating support for right now.  In the meantime you may need to use mouse or touch to click and drag a slider.

**Comment by caulfield2** [comment]
@yodurr VSTest on a Windows local app

**Comment by caulfield2** [comment]
@yodurr VSTest on a local Windows app

**Comment by yodurr** [comment]
marking this enhancement as the Action API support is a work in progress.

**Comment by hassanuz** [comment]
Closing as this scenario is now supported with the latest [WinAppDriver v1.1](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.1) release via the Actions API.
