### ISSUE TITLE
Using .GetAttribute() to determine if menu option is toggled on/off

### ISSUE THREAD

**Issue by caulfield2** [Microsoft/WinAppDriver#220]
I need to be able to determine if the "Hide template names" item in the menu flyout shown below is checked or not before running a test. 

![image](https://user-images.githubusercontent.com/25783833/28080031-2baac27e-6630-11e7-8c4a-71597704e58f.png)

So far, I have not been able to come up with an easy way to do this. I tried using the code below to reference the Toggle.ToggleState property that is found via Inspect, 

`Reference = driver.FindElementByName("Hide template names");`
`var isToggled = Reference.GetAttribute("Toggle.ToggleState");`

but it returns null. Is .GetAttribute() supported for WAD?

**Comment by yodurr** [comment]
GetAttribute support is coming in v1.0.  hope to have this to you later this month.  Thanks.

**Comment by timotiusmargo** [comment]
Hi @caulfield2,

In [v1.0-RC release](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.0-RC), the element `GetAttribute` API now supports arbitrary attributes. Thus, you can use any of the attributes shown in `inspect.exe` including the `Toggle.ToggleState` you specify above. More examples on using `GetAttribute` API can be found on the following sample test:
https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/Tests/WebDriverAPI/ElementAttribute.cs#L38

While the approach above works with your scenario, we recommend to reference `Selected` element property instead to determine the element toggle state. An example of using the `Selected` property can be found on the following sample tests:
https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/Tests/UWPControls/ToggleSwitch.cs#L92
https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/Tests/UWPControls/ToggleButton.cs#L97
https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/Tests/WebDriverAPI/ElementSelected.cs#L39
