### ISSUE TITLE
WinAppDriver hangs when creating session

### ISSUE THREAD

**Issue by holphi** [Microsoft/WinAppDriver#224]
Hi guys,

I am automating one of our UWP apps by WinAppDriver, however, when I execute my tests, sometimes, the UWP app to be tested can be launched but the WinAppDriver hangs, so the test code are not executed anymore. From the console log in below, it seems that the session mgr gets stuck in loading MitaBroker.

`SessionManager - Creating session
SessionManager - WinAppDriver succeeded loading MitaBroker`
 
Could you pls help look into this issue?

I use below code to initialize the web driver instance
`DesiredCapabilities appCapabilities = new DesiredCapabilities();`
`appCapabilities.SetCapability("platformName", "Windows");`
appCapabilities.SetCapability("deviceName", "WindowsPC");
appCapabilities.SetCapability("launchTimeout", 5000);
appCapabilities.SetCapability("app", "Dolby.DAX3.UI.CS_rnnrkadb60ba0!App");
new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), appCapabilities);

WindowsDriver<WindowsElement> appSession= new WindowsDriver<WindowsElement>(new Uri(app_Driver_Url), appCapabilities)`

The version of the WinAppDrive I'm using is: v0.9-beta

**Comment by yodurr** [comment]
In WinAppDriver v0.9 it can take a while to find your app window.  I expect v1.0 will address this as work was done to improve the speed of finding the app window.

**Comment by yodurr** [comment]
other possibilities we've seen that could cause this
- a splash screen which we're attaching to
- your app tries to load an application file from the current working directory instead of the app install directory

**Comment by holphi** [comment]
Thanks for your update. In my case, when I completed all tests, I didn't call Quit() method to close and release current windows driver instance, next time, when I launched the test, the windows driver would hung.

**Comment by timotiusmargo** [comment]
@holphi,

Depending on the application you test, some app supports multiple instance creation for every launch (e.g. **Notepad**) while some simply use a single instance (**Alarms & Clock**). When you create a session with the given `Dolby.DAX3.UI.CS_rnnrkadb60ba0!App` appId, WinAppDriver will attempt to launch/activate it and locate the main application window if it succeed.

Can you please retry the scenario using the latest Widows Application Driver [v1.0-RC](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.0-RC) and share your findings?

**Comment by holphi** [comment]
@timotiusmargo

Sorry for slow response. I've upgraded WinAppDriver to v1.0 and tried re-run test scenarios, I don't meet the issue anymore.
