### ISSUE TITLE
Key mapping is messed up after maximize the UWP window

### ISSUE THREAD

**Issue by holphi** [Microsoft/WinAppDriver#225]
Hi There,

I am trying to maximize the window of UWP apps by sending keys combination ALT+SPACE+M, pls refer to below code:

`win_driver.inst.Keyboard.SendKeys(OpenQA.Selenium.Keys.Alt + OpenQA.Selenium.Keys.Space  + 'x') ;`

I noticed each time when test completes, the key mapping will be messed up unless I reboot the system. I tried run the code on several devices and found this issue is reproducible on all devices.

Pls help take a look at this issue. 

Thanks,
Alex

**Comment by holphi** [comment]
Closed. I sent incorrect keys to the UWP app.

Sorry for that.

**Comment by timotiusmargo** [comment]
Also note that you would need to **release the Alt modifier** as it will be kept between calls. Quoting "https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidkeys":

> The modifiers are not released at the end of the call. Rather, the state of the modifier keys is kept between calls, so mouse interactions can be performed while modifier keys are depressed.

Thus you may want to do the following instead:
`win_driver.inst.Keyboard.SendKeys(OpenQA.Selenium.Keys.Alt + OpenQA.Selenium.Keys.Space + 'x' + OpenQA.Selenium.Keys.Alt)`

Or maybe even:
`win_driver.inst.Manage().Window.Maximize();`

**Comment by holphi** [comment]
Ah. My tests need to send may key strokes, that was the reason why my app behaved strangely when I executed my test, I didn't release the modifier key!

Thanks for pointing me out! You help me a lot
