### ISSUE TITLE
Invoking TouchAction.Perform() throws exception

### ISSUE THREAD

**Issue by holphi** [Microsoft/WinAppDriver#226]
Hi guys,

We have many slider controls(seek bars) in our UWP app, users can move it forward and backward, I'm wondering if the WinAppDriver provides specific mehto to drag the bar to some extent, I tried working around it by using touchActions, please refer to below code:

`            
            WindowsElement slider = appSession.FindElementByAccessibilityId("sliderSize");

            Console.WriteLine(slider.Size.Width);
            Console.WriteLine(slider.Location.X);
            Console.WriteLine(slider.Location.Y);

            int start = slider.Location.X;
            int end = slider.Size.Width;
            int y = slider.Location.Y;

            var touchAction = new TouchAction(appSession);
            int moveTo = (int)(end * 0.2);

            touchAction.Press(start, y).MoveTo(moveTo, y).Release().Perform();` 

When I run above code, I saw there's an InvalidOperationException returned from the server with the message: Missing Command Parameter: element 

`
HTTP/1.1 200 OK
Content-Length: 89
Content-Type: application/json

{"sessionId":"EF4B3B2F-4F78-4C18-BF10-FEFD10EC1864","status":0,"value":{"x":246,"y":397}}

==========================================
POST /session/EF4B3B2F-4F78-4C18-BF10-FEFD10EC1864/touch/perform HTTP/1.1
Accept: application/json, image/png
Content-Length: 129
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"actions":[{"action":"press","options":{"x":246,"y":397}},{"action":"moveTo","options":{"x":120,"y":397}},{"action":"release"}]}
HTTP/1.1 400 Bad Request
Content-Length: 98
Content-Type: application/json

{"status":100,"value":{"error":"invalid argument","message":"Missing Command Parameter: element"}}
`

It looks like the perform method of touch action is not implemented in WinAppDriver, pls let me know when you are going to support it?

**Comment by holphi** [comment]
After checking your sample code. Now I can move the slider by calling SendKeys() with the parameter Keys.Left/Keys.Right, so it would be a stop blocker to me, but I expect to have TouchAction.Perform() in coming releases.:)

Cheers,
Alex

**Comment by hassanuz** [comment]
Marking issue as closed as we've since introduced advanced Touch/Pen support via the Actions API with the [WinAppDriver v1.1](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.1) release.
