### ISSUE TITLE
Obtaining Value for Text control is returning selected text only.

### ISSUE THREAD

**Issue by CoreyDotCom** [Microsoft/WinAppDriver#228]
Can someone describe in more detail what is meant by: 
"Enable support for selected text retrieval"
for version 0.8 release notes?

After upgrading to 0.8 we are seeing an issue where requesting the value of a text field with partially selected text, is returning *only* the selected text, not the entire value.  (We are using, /session/:sessionId/element/:id/text).

Seems to not be inline with the WebDriver spec ? https://w3c.github.io/webdriver/webdriver-spec.html#dfn-get-element-text . 

If this is the new behavior how would we obtain the text independent of selection?

**Comment by yodurr** [comment]
we're going to fix this in the next release so it returns all the text.

**Comment by timotiusmargo** [comment]
Hi @CoreyDotCom,

This feature is removed from Windows Application Driver in [v1.0-RC release](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.0-RC) and now it will only return the full text regardless of selection.

**Comment by sayedsaad07** [comment]
How can you return the selected text using winappdriver then? and how to get the caret position
