### ISSUE TITLE
Is possible to install application on remote machine via WinAppDriver? <EOM>

### ISSUE THREAD

**Issue by denys-rwd** [Microsoft/WinAppDriver#23]

**Comment by yodurr** [comment]
Not at the moment, but it's a feature we intend to add.

**Comment by alakshmi1030** [comment]
Do you mean running an application or installing an MSI using WinAppDriver? You can run a WinAppDriver test on a remote machine by specifying an IP and port from the command line. From your directory where WinAppDriver.exe is installed, the syntax is "WinAppDriver.exe <IP> <Port>". Note that your port traffic must be open to inbound requests for this to work.

**Comment by denys-rwd** [comment]
See inline.

Thanks in advance,
Denys
