### ISSUE TITLE
Running Parallel/Simultaneous tests

### ISSUE THREAD

**Issue by JimmyDepp** [Microsoft/WinAppDriver#230]
Hi - I've managed to setup tests to run remotely on 2 VMs simultaneously. However I've encountered a problem where the winappdriver session will start and open the application I am testing on both VMs, but then continue the test run on only 1 VM. The other VM will timeout as a result

Has anyone tried running a similar test and been successful and possibly provide me with a solution?

Many thanks!

**Comment by yodurr** [comment]
can you provide a bit more detail on how you have this set up?  How many physical machines, ports, etc?

**Comment by JimmyDepp** [comment]
I have 1 physical machine which I have written the tests on. The 2 VMs that the test are configured to run on (from my physical machine), use port 4723... is it best that they run on different ports? 

The code I've written to configure is below;

using OpenQA.Selenium;
using OpenQA.Selenium.Appium;
using OpenQA.Selenium.Appium.Windows;
using OpenQA.Selenium.Remote;
using System;
using static System.Console;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Framework
{
    public static class Application
    {
        private const string AppDriverUrl0 = "http://127.0.0.1:4723/wd/hub";
        private const string AppDriverUrl1 = "http://192.168.128.140:4723/wd/hub";
        private const string AppDriverUrl2 = "http://192.168.128.150:4723/wd/hub";
        private const string XXXAppId = @"C:\Program Files\XXX\XXX64.exe";
        
        private static WindowsDriver<WindowsElement> XXXWindowsDriver;
        private static WindowsDriver<WindowsElement> DesktopWindowsDriver;

        private static void initialiseAppiumDriver()
        {
            DesiredCapabilities appCapabilities = new DesiredCapabilities();
            appCapabilities.SetCapability("app", XXXAppId);
            appCapabilities.SetCapability("platformName", "Windows");
            appCapabilities.SetCapability("deviceName", "WindowsPC");
            appCapabilities.SetCapability("newCommandTimeOut", "150");

            DesiredCapabilities desktopCapabilities = new DesiredCapabilities();
            desktopCapabilities.SetCapability("app", "Root");
            desktopCapabilities.SetCapability("platformName", "Windows");
            desktopCapabilities.SetCapability("deviceName", "WindowsPC");
            desktopCapabilities.SetCapability("newCommandTimeOut", "150");

            try
            {
                // Create a session for XXX
                XXXWindowsDriver = new WindowsDriver<WindowsElement>(new Uri(AppDriverUrl0), appCapabilities);
                XXXWindowsDriver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(100));

                XXXWindowsDriver = new WindowsDriver<WindowsElement>(new Uri(AppDriverUrl1), appCapabilities);
                XXXWindowsDriver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(100));

                XXXWindowsDriver = new WindowsDriver<WindowsElement>(new Uri(AppDriverUrl2), appCapabilities);
                XXXWindowsDriver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(100));

                //Create a session for Desktop                
                DesktopWindowsDriver = new WindowsDriver<WindowsElement>(new Uri(AppDriverUrl0), desktopCapabilities);
                DesktopWindowsDriver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(100));

                DesktopWindowsDriver = new WindowsDriver<WindowsElement>(new Uri(AppDriverUrl1), desktopCapabilities);
                DesktopWindowsDriver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(100));

                DesktopWindowsDriver = new WindowsDriver<WindowsElement>(new Uri(AppDriverUrl2), desktopCapabilities);
                //DesktopWindowsDriver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(100));
            }

**Comment by timotiusmargo** [comment]
Hi @JimmyDepp,

In your code above, you are overwriting the newly created `XXXWindowsDriver` and `DesktopWindowsDriver` sessions by assigning them another new sessions pointing to a different URL. At the end of `initialiseAppiumDriver', you would have created three `XXXAppId` and three desktop sessions in three different machines but can only use the two (`XXXAppId` and desktop) sessions on the VM with `AppDriverUrl2` as you have overwritten the sessions on `AppDriverUrl0` and `AppDriverUrl1`. At this point you no longer have a reference to the overwritten sessions and they will linger until you terminate `WinAppDriver.exe` in those machines.

To fix this issue, you should keep each session in each variable until you terminate it. For instance:
```c#
private static WindowsDriver<WindowsElement> XXXWindowsDriver0;
private static WindowsDriver<WindowsElement> XXXWindowsDriver1;
private static WindowsDriver<WindowsElement> XXXWindowsDriver2;
private static WindowsDriver<WindowsElement> DesktopWindowsDriver0;
private static WindowsDriver<WindowsElement> DesktopWindowsDriver1;
private static WindowsDriver<WindowsElement> DesktopWindowsDriver2;

// ...

// Create sessions for XXX
XXXWindowsDriver0 = new WindowsDriver<WindowsElement>(new Uri(AppDriverUrl0), appCapabilities);
XXXWindowsDriver1 = new WindowsDriver<WindowsElement>(new Uri(AppDriverUrl1), appCapabilities);
XXXWindowsDriver2 = new WindowsDriver<WindowsElement>(new Uri(AppDriverUrl2), appCapabilities);

// Create sessions for Desktop                
DesktopWindowsDriver0 = new WindowsDriver<WindowsElement>(new Uri(AppDriverUrl0), desktopCapabilities);
DesktopWindowsDriver1 = new WindowsDriver<WindowsElement>(new Uri(AppDriverUrl1), desktopCapabilities);
DesktopWindowsDriver2 = new WindowsDriver<WindowsElement>(new Uri(AppDriverUrl2), desktopCapabilities);
```

**Comment by JimmyDepp** [comment]
Hi @timotiusmargo 
Many thanks for your reply.

I have tried the fix you suggested but the same issue persists....

I have also tried separating the sessions out into initialiseAppiumDriver0, initialiseAppiumDriver1...etc... but the same issue persists

I've attached copy of the lines of code I have.  If you could review it and let me what further changes I need to make I would be very very grateful!! 

Many thanks!!
[application.cs.txt](https://github.com/Microsoft/WinAppDriver/files/1234672/application.cs.txt)

**Comment by timotiusmargo** [comment]
Hi @JimmyDepp,

I'm not sure about what you meant the same issue persist. With that code, does the application open in all three target machines? When you call `Close()`, does it close all three application instances too? The code doesn't show any test that would not be executed correctly so far unless they are being called incorrectly by other part of the code not shown.
