### ISSUE TITLE
Devexpress grid

### ISSUE THREAD

**Issue by jerry2007** [Microsoft/WinAppDriver#233]
Hello,
WinAppDriver work great, but when i want to get text from cell in GridView (Devexpress) it not work...

Can somebody help me?

**Comment by timotiusmargo** [comment]
Hi @jerry2007,

Can you use [inspect.exe](https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/README.md#inspecting-ui-elements) to inspect your target cell element and paste the information here? The `Text` attribute/property should return the proper text value if the element indeed exposed it as text. More example on getting the `Text` attribute can be found on https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/Tests/WebDriverAPI/ElementText.cs#L39

**Comment by timotiusmargo** [comment]
Hi @jerry2007,

In the most recent [v1.0-RC2](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.0-RC2) release, we added a feature to expose elements that were missing `RuntimeId` attribute. This may help your scenario if the cell in DevExpress GridView used to be inaccessible previously.

**Comment by eduarte** [comment]
Hey, I am working on a WinApp that is using DevExpress, do you have any example of how to interact with Grids or Spreadsheets using WinAppDriver?
Thanks
