### ISSUE TITLE
Unable to find "TreeViewItem" by Classname or Automationid

### ISSUE THREAD

**Issue by wuarthur** [Microsoft/WinAppDriver#234]
The value i found using inspect.exe tool:
![inspecttool](https://user-images.githubusercontent.com/15177124/28694306-ac109182-72dd-11e7-8a89-0f02ae7c4fa5.png)

Used these two method to search for the elements:
![appium](https://user-images.githubusercontent.com/15177124/28694313-b377afd2-72dd-11e7-85ac-d977db8de4d2.png)

Winappdriver Reaults:
![winappdriver](https://user-images.githubusercontent.com/15177124/28694315-b5c16bde-72dd-11e7-8b41-e3b1f4df1f4e.png)

**Comment by khouzam** [comment]
Hi @wuarthur 

This should work. Would it be possible to send more details, including the logs and screenshots. Is this something that we could reproduce in-house?

Thanks

**Comment by timotiusmargo** [comment]
Hi @wuarthur,

It looks like your session `8FF713DB-6202-4244-9D77-EC3533863C7E` may have pointed to a different window (`0x0742D0` / `00475856`) than the one shown in the `inspect.exe`. Could you verify that the `cpsi.contacts.Entity` indeed is rooted in the same window handle you returned in your script? It would be worthwhile as well to perform `session.PageSource` to get the XML dump of your current session. You should then be able to see if the element you are looking for is indeed there and has the correct **AutomationId** or **ClassName**.

**Comment by swathiJaya** [comment]
Hi, I am facing the same issue. Is there a solution for this?

Thanks!
