### ISSUE TITLE
Find control's properties

### ISSUE THREAD

**Issue by CheNMorD** [Microsoft/WinAppDriver#236]
Hi,
I'm using appium in visual studio for testing a simple WPF application,
I'm using WindowsDriver

`WindowsDriver<WindowsElement> driver = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), desiredCapabilities);`

I know how to enter text and how to get text from TextBox:

`driver.FindElementByAccessibilityId("MyTextBox").SendKeys("123");`

I wanted to know if there any way to get and set control's properties, For example: get IsChecked from CheckBox, get Background from TextBlock etc.

Thanks.

**Comment by dhapolapankaj** [comment]
You can try exporting the PageSource to an XML file and then

`driver.FindElementByAccessibilityId("MyTextBox").GetAttribute("innerHTML"));`
 
You will get clue for your Intended property or attribute values to pass as an argument in GetAttribute function from this exported XML file.

I'm not sure if we can set value of the control by setting the value of attribute, even if we can it would not be a good idea because the background events are not triggered for some controls. 

You will have to utilize the exposed methods like Click(), SendKeys() etc. to set the values.

Regards
PD

**Comment by CheNMorD** [comment]
@dhapolapankaj 
Thanks for your answer, 
I guess that your solution is for a web app,
but like I said i'm testing a desktop app and the ui of this app
is written in XAML (using WPF) , is there a way to get properties from controls in my desktop app?

Thanks.

**Comment by dhapolapankaj** [comment]
:) I would still insist you to export the PageSource

try below code

`System.Xml.XmlDocument doc = new System.Xml.XmlDocument();`
`doc.LoadXml(driver.PageSource.ToString());`
`System.Xml.XmlTextWriter writer = new System.Xml.XmlTextWriter(@"c:\App_To_XML.xml", new System.Text.UnicodeEncoding());`
`writer.Formatting = System.Xml.Formatting.Indented;`
`doc.WriteContentTo(writer);`

See if you have got the "App_To_XML.xml" file generated

**Comment by timotiusmargo** [comment]
Hi @CheNMorD,

Typically, I would use `Selected` property of the element to see if a **Checkbox** is checked. And as @dhapolapankaj mentioned, you need to perform user interaction through touch, click, or keyboard input just as what the user would need to do on your application. Below is a snippet of interaction with a XAML **CheckBox** control in a UWP app taken from https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/Tests/UWPControls/CheckBox.cs#L97

```c#
var originalState = checkBoxElement1.Selected;
checkBoxElement1.Click();
Assert.AreNotEqual(originalState, checkBoxElement1.Selected);
checkBoxElement1.Click();
Assert.AreEqual(originalState, checkBoxElement1.Selected);
```

For any other element properties shown on [inspect.exe](https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/README.md#inspecting-ui-elements), you can use the `GetAttribute` API. You can find an example of getting various attributes/properties on the following sample test:
https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/Tests/WebDriverAPI/ElementAttribute.cs#L38

Note that element properties that are not exposed to the accessibility layer such as background color and font, cannot be retrieved by Windows Application Driver nor `inspect.exe`.

**Comment by MarcoDeJesus** [comment]
As described by @bharathp666 in https://github.com/Microsoft/WinAppDriver/issues/590 we can check the whole xml document through driver.PageSource.
