### ISSUE TITLE
"Nested" FindElementsBy returns WebElements instead of WindowsElements

### ISSUE THREAD

**Issue by caulfield2** [Microsoft/WinAppDriver#237]
I am trying to narrow down a search to a certain section of my app and then find all elements within that section by a certain name. In VS2015, my initial thought was to do the following:

`WindowsElement element = driver.FindElementByName("name1");`
`IList<WindowsElement> list = (IList<WindowsElement>)element.FindElementsByName("name2");`

I do not get any complaints in VS about this before I run my test. At runtime, I get the error below on the cast:

![image](https://user-images.githubusercontent.com/25783833/28875947-0cb91cec-775d-11e7-867a-6da43b1246c0.png)

Upon further inspection, it seems that `element.FindElementsByName("name2")` is returning type

 System.Collections.ObjectModel.ReadOnlyCollection<OpenQA.Selenium.Appium.AppiumWebElement>

which is why I am getting the cast exception. My workaround to this is to just replace 

`IList<WindowsElement> list = (IList<WindowsElement>)element.FindElementsByName("name2");`

with 

`var list = element.FindElementsByName("name2");`
`list[0].Click();`

and I am able to click the desired element without issue. However, it doesn't make much sense that a WebElement should ever be returned when using WAD, especially when 

`IList<WindowsElement> list = driver.FindElementsByName("element");`

executes without error. 

I am not sure if the error is because I am converting from a ReadOnlyCollection to an IList, or from WebElement to WindowsElement because 

`WindowsElement element1 = driver.FindElementByName("name1");`
`WindowsElement element2 = (WindowsElement)element1.FindElementByName("name2").Click();`

executes without error as well, although the cast is needed which means that the "nesting" here is returning a WebElement as well. Can someone confirm whether this is a valid concern? The way I see it, a cast shouldn't be necessary when nesting a search like I do above.

**Comment by dhapolapankaj** [comment]
WinAppDriver utilizes WebDriver.dll
Hence, each element at the core is treated as WebElement.
Your concern is very Valid, this question actually belong to Appium Desktop forum
https://github.com/appium/appium-desktop

P.S. Almost all Appium Elements are type casted e.g. MobileElement, WindowsElement

**Comment by timotiusmargo** [comment]
Hi @caulfield2,

Yes this is a very valid concern indeed. However, this issue should be created in https://github.com/appium/appium-dotnet-driver which is the C# client that sends the JSON Wire Protocol commands to Windows Application Driver. We don't own that repository but we can certainly contribute if that community agree on how to proceed forward on the issue.

Would you then please file the issue there and close this by leaving a reference/link to the newly created issue? Thanks!

**Comment by caulfield2** [comment]
@timotiusmargo Issue created on the Appium GitHub page [here](https://github.com/appium/appium/issues/9057)

**Comment by shaktim121** [comment]
Hello All,
I am still seeing the above issue and I think it is redirected to appium-dot-net-driver issue, but not yet fixed. 
It is critical for us to get a solution for this. Kindly help.
