### ISSUE TITLE
ETA\Schedule\Timeline for 1.0 Release

### ISSUE THREAD

**Issue by ianceicys** [Microsoft/WinAppDriver#238]
Any idea of a schedule\timeline for the 1.0 release of winappdriver? Even high-level (Q2/Q3/heck 2018) would be helpful. Thanks!

**Comment by khouzam** [comment]
We're very close to a release candidate.

**Comment by dhapolapankaj** [comment]
Eagerly waiting for the official release.

Cheers!!!

**Comment by hroe** [comment]
Great news. 
I just noticed that @yosefdurr released it at https://github.com/Microsoft/WinAppDriver/releases/tag/v1.0-RC

Thanks to all contributors.

Can you give an eta for open sourcing winappdriver as was mentioned last year by @shanselman and @yosefdurr ?

**Comment by timotiusmargo** [comment]
Yes as @hroe mentioned, we release [v1.0-RC](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.0-RC) last week. Would you all please update, re-validate issues you posted, and create a new one for  newly found issue? Cheers!
