### ISSUE TITLE
Unable to launch app using Ruby bindings

### ISSUE THREAD

**Issue by isonic1** [Microsoft/WinAppDriver#24]
Unable to start a new session using the selenium ruby bindings. It appears the selenium server is expecting capabilities returned back from the WinAppDriver server. Though, I’m surprised other bindings are not encountering this issue too. I've tried various combinations of the capabilities but to no avail. See below for more details. 

* To work around this issue, I rescue the .dup call with an empty hash.

**#WinAppDriver and Windows**
require 'selenium-webdriver'
caps = { platformName: "ANDROID", deviceName: "android", platform: “Windows", app: "Microsoft.App_8wekyb3d8bbwe!App” }
win = Selenium::WebDriver.for(:remote, :url => "http://127.0.0.1:4723", :desired_capabilities => caps )
irb(main):004:0> win = Selenium::WebDriver.for(:remote, :url => "http://127.0.0.1:4723", :desired_capabilities => caps )

WinAppDriver successfully launches app and a session is created…

==========================================
POST /session HTTP/1.1
Accept: application/json
Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
Connection: close
Content-Length: 115
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: Ruby

{"desiredCapabilities":{"platform":"Windows","app":"Microsoft.App_8wekyb3d8bbwe!App"}}
SessionManager - Creating session for Microsoft.App_8wekyb3d8bbwe!App
SessionManager - WinAppDriver succeeded loading MitaBroker
SessionManager - Application launched
SessionManager - Session successfully created: A13C9DFE-6E0A-4DFF-988B-EBD0425A8C2B

HTTP/1.1 200 OK
Content-Length: 122
Content-Type: application/json

{"capabilities":{"app":"Microsoft.App_8wekyb3d8bbwe!App"},"sessionId":"A13C9DFE-6E0A-4DFF-988B-EBD0425A8C2B","status":0}

However, the ruby bindings then throw the error below after the session is created.

TypeError: can't dup NilClass  
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/capabilities.rb:162:in `dup'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/capabilities.rb:162:in `json_create'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/bridge.rb:126:in `create_session'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/bridge.rb:87:in `initialize'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/common/driver.rb:59:in `new'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/common/driver.rb:59:in `for'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver.rb:84:in `for'
        from (irb):4
        from C:/tools/ruby22/bin/irb:11:in `<main>'

So I wanted to see what the differences where with the Appium server. Looks like the Appium server returns the below capabilities back to the selenium server (in bold below) on , which I believe the WinAppDriver server is not doing, so it fails on [this](https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/remote/capabilities.rb#L161-L180) method.

**#Appium and Android **
require 'selenium-webdriver
caps = { platformName: "ANDROID", platform: “android”, deviceName: “android”, app: "/Users/justin/Desktop/NotesList.apk” }
android = Selenium::WebDriver.for(:remote, :url => "http://127.0.0.1:4723/wd/hub", :desired_capabilities => caps)

[Appium] Welcome to Appium v1.5.2 (REV 39da42bacb746d323e00ce5e293fc0463db7baf0)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"ANDROID","platforn":"android","deviceName":"android","app":"/Users/justin/Desktop/NotesList.apk"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"ANDROID","platforn":"android","deviceName":"android","app":"/Users/justin/Desktop/NotesList.apk"},null,null,null]
[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   platformName: 'ANDROID'
[Appium]   platforn: 'android'
[Appium]   deviceName: 'android'
[Appium]   app: '/Users/justin/Desktop/NotesList.apk'
**[MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":tr…**

**Comment by yodurr** [comment]
We're going to put a Ruby sample together soon and will look into this.  Thanks for the info!

**Comment by alakshmi1030** [comment]
As of release v0.3, Ruby support should be enabled. Please view the release here: https://github.com/Microsoft/WinAppDriver/releases/tag/v0.3-beta

Let us know if you are still experiencing this issue.

**Comment by djwgit** [comment]
@alakshmi1030 
with 0.50 beta, using ruby client,  could start windows app using it id(?)  as "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"
but could not start app using path to exe: "C:\Windows\System32\notepad.exe"

```
require 'selenium-webdriver'

$AppSession

def caps 
    {
		# this one works, could start calculator
		platformName: "WINDOWS", platform: "WINDOWS", deviceName: "mydevice", app: "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App" 
		# this one does not work, could not start notepad
		platformName: "WINDOWS", platform: "WINDOWS", deviceName: "mydevice", app: "C:\Windows\System32\notepad.exe"
    }
end

def assert &block
    raise AssertionError unless yield
end

def setup
    $AppSession = Selenium::WebDriver.for(:remote, :url => "http://127.0.0.1:4723/", :desired_capabilities => caps )
end

def teardown
    $AppSession.quit
end

# run through the tests
setup
#test-1
teardown
```
