### ISSUE TITLE
Double click option is not available in Winappdriver for Java

### ISSUE THREAD

**Issue by jnicelap** [Microsoft/WinAppDriver#245]
When will the double click option be available for the winappdriver java?

**Comment by timotiusmargo** [comment]
Hi @jnicelap,

This question would be best addressed in [Appium Java Client](https://github.com/appium/java-client) or even [Selenium](https://github.com/SeleniumHQ/selenium) project itself. When using Java, **Appium Java Client** (extension of **Selenium Java Client**) translates your test script written in Java to [JSON Wire Protocol](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol) commands that WinAppDriver understand. While Windows Application Driver supports the mouse double click and touch double tap through the JSON Wire Protocol commands, it is the responsibility of the clients ([Java Client](https://github.com/appium/java-client), [C# Client](https://github.com/appium/appium-dotnet-driver), [Python Client](https://github.com/appium/python-client), etc.) to implement the language specific classes.
