### ISSUE TITLE
HTTP/1.1 400 Bad Request 

### ISSUE THREAD

**Issue by Manvibha** [Microsoft/WinAppDriver#246]
Hi Yosef/Timotius , 

I am encountering below issue and this is the 2nd time in last 2 days I have experienced. Once this issue starts  occurring, it keep on repeating unless machine is restarted. 
HTTP/1.1 400 Bad Request
Content-Length: 102
Content-Type: application/json

{"status":23,"value":{"error":"no such window","message":"Currently selected window has been closed"}}

Application is opened, but it fails to find the application and then after none of my scripts will execute and starts failing for same reason. I am executing a test method for multiple iteration and for each iteration application is closed and launched again. 
Note: I am still using previous version v0.9-beta. I know that I need to upgrade to latest release which I will be doing ASAP. 

Regards,
Mahendra

**Comment by timotiusmargo** [comment]
Hi @Manvibha,

We have made substantial changes from v0.9 to [v1.0-RC](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.0-RC). It would be best to retest your scenario on the latest version.

In general, `no such window` error is returned when the application session window is closed but the session is not terminated or deleted. This condition can come from expected operations such as `session.Close()` or unexpected when the session was created on top of disappearing application window such as splash screen.

Could you please update to the latest version and provide more details on when you encounter the issue above? Did you encounter soon after session creation or much later after many successful commands?

**Comment by Manvibha** [comment]
sure, will keep you posted further.

**Comment by timotiusmargo** [comment]
Thanks @Manvibha. Please file a new issue with the specific details to reproduce it when you encounter one.

**Comment by gurbachan1322** [comment]
Hi , I am getting same kind of error even after updated version
I am encountering below issue and this is the 2nd time in last 2 days I have experienced. Once this issue starts occurring, it keep on repeating unless machine is restarted.
HTTP/1.1 400 Bad Request
Content-Length: 102
Content-Type: application/json

{"status":23,"value":{"error":"no such window","message":"Currently selected window has been closed"}}
