### ISSUE TITLE
Cannot execute without an opened GUI session (End2End tests in CI)

### ISSUE THREAD

**Issue by miguelsimlocal** [Microsoft/WinAppDriver#248]
Hi,
I cannot execute the driver without an opened GUI session (End2End tests in CI). Is this possible? or is it not supported yet?

**Comment by hassanuz** [comment]
Hi @miguelsimlocal,

Yes - this is possible depending on how you have your agent setup (it'll have to be in interactive mode). 

Please refer to [here ](https://github.com/Microsoft/WinAppDriver/wiki/Continuous-Integration-with-WinAppDriver/5bee38584ade51e0d71ada221a2e9eff707a423b)on setting up a proper CI environment with a custom agent. 

Furthermore if you do initiate an RDP session with the custom agent, you will have to exit out of using [tscon ](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/ui-testing-considerations?view=vsts&tabs=mstest#visible-ui-testing-using-self-hosted-windows-agents)to ensure the session doesn't get disrupted.

**Comment by hassanuz** [comment]
If anyone has any other questions regarding CI, please create a dedicated ticket. Thanks!
