### ISSUE TITLE
SendKeys is not enforcing the casing

### ISSUE THREAD

**Issue by miguelsimlocal** [Microsoft/WinAppDriver#249]
"SendKeys": independently of the "Caps Lock", when sending an string the input text is converted to uppercase randomly

**Comment by hassanuz** [comment]
Hi @miguelsimlocal, can you report back and see if you're facing the same issue with the [latest release](https://github.com/Microsoft/WinAppDriver/releases)?  Are you using a custom keyboard layout?

**Comment by hassanuz** [comment]
Closing issue. Please reopen if you are still experiencing this.
