### ISSUE TITLE
Insufficient documentation on inspecting element using inspect.exe

### ISSUE THREAD

**Issue by mani0303** [Microsoft/WinAppDriver#25]
Hi - I have seen people using FindElementByName or FindElementByAccessibilityId in the code samples,but when we inpect from Windows 10 SDK inspector,how can we assure that we are the right elements' attributes with right methods?Is there any documenation where i can find these mappings from different element finding techniques to the attributes in the inspector console just like in uiautomatorviewer?.Thank You

**Comment by yodurr** [comment]
Agree we should include this in documentation.  Assigning to myself.  Thanks for your patience.

**Comment by timotiusmargo** [comment]
Hi @mani0303! We have updated the documentation with the attributes/properties mapping table as you requested. You can find this under https://github.com/Microsoft/WinAppDriver#inspecting-ui-elements
