### ISSUE TITLE
Using regular expression to find a control 

### ISSUE THREAD

**Issue by Manvibha** [Microsoft/WinAppDriver#252]
Hi, 

Does latest release supports using regular expression to find a control? 
Ex: session.FindElementByName("Test Version -*");   // Actual value would be "Test Version - 10.0". 

I tested with regular expression and it failed with above scenario. Is there a way to do it or can I expect this feature in near future? 

Thanks,
Mahendra

**Comment by timotiusmargo** [comment]
Hi @Manvibha,

Most of the element [locators](https://github.com/Microsoft/WinAppDriver#supported-locators-to-find-ui-elements) match the element precisely as given and does NOT support regular expression. In order to do something similar, you would need to use XPath expressions.

**Comment by henry1999sg** [comment]
xpath supports regex ? It seems xpath does't support regex to me. is there any way to do partial search ?

**Comment by Shakevg** [comment]
Xpath doesn't support regex, but have other methods. It depends what is you need, e.g.
1) search for control that contains 'Test Version -' text: 
session.FindElementByXPath("//*[contains(@Name, 'Test Version -')]"); 
2) search for control that start with 'Test Version -' text:
session.FindElementByXPath("//*[starts-with(@Name, 'Test Version -')]";
