### ISSUE TITLE
Selectors in win32 - connect to childs

### ISSUE THREAD

**Issue by PeSoski** [Microsoft/WinAppDriver#253]
Hi, I have quick question

Is there any possibility to create selector to child in win32 ?
Unfortunately in 'my app' there is loot of 'NoName' controls and all 'accessible Id's ' are dynamic ... 

eg:
```
"Control01"
|- ""
|- ""
   |- ""      <--

```
?? driver.FindElementByName("Control01").Child(2).Child(1)

**Comment by timotiusmargo** [comment]
Hi @PeSoski,

You can use **XPath** expression to locate an element the way you described above. You may have to do nested query (start finding element from the one you previously located) depending on how the UI tree looks in your application. But there should always be a way to get to an element in your UI tree that is shown in [inspect.exe](https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/README.md#inspecting-ui-elements). An example of **XPath** element search can be found in the sample test below.
https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/Tests/WebDriverAPI/Element.cs#L79

**Comment by PeSoski** [comment]
Great :) 
Thanks
