### ISSUE TITLE
testing nullsoft installer/uniinstaller

### ISSUE THREAD

**Issue by djewiss** [Microsoft/WinAppDriver#256]
I am trying to test our applications installer/uninstaller, we are using Nullsoft installer scripts for this. I am having trouble with the uninstaller -

DesiredCapabilities appCapabilities = new DesiredCapabilities();
appCapabilities.SetCapability("app", @"C:/Program Files (x86)/PathToMyApplication/UnInstall.exe");
appCapabilities.SetCapability("deviceName", "WindowsPC");
installer = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities);

The uninstaller window opens and I get the following exception-
{"Failed to locate opened application window with appId: C:/Program Files (x86)/PathToMyApplication/Uninstall.exe, and processId: 1456"}

Is there a way for me to run and interact with this app?

**Comment by timotiusmargo** [comment]
Hi @djewiss,

You can create a **Desktop Session** to find the opened uninstaller window you mentioned using any of the [supported locator](https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/README.md#supported-locators-to-find-ui-elements) after attempting to launch as you specified. Once you found the window, you can create a session by attaching it as shown is the example below:
https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/README.md#attaching-to-an-existing-app-window

Out of curiosity, could you please validate if the opened uninstaller window has a different **process Id** than the one displayed on the exception? You can get this information by using the [inspect.exe](https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/README.md#inspecting-ui-elements) tool. Once you have the **processId**, can you also look for the **processName** for the corresponding **processId** in **Task Manager**?

**Comment by djewiss** [comment]
Hi There

Thanks, that's awesome! You are right, it is a different ProcessID than the one in the exception. It was 2836 instead of 1456, and the name was "Un_A.exe"
