### ISSUE TITLE
PageFactory initElements() proxyFields() error

### ISSUE THREAD

**Issue by balawider** [Microsoft/WinAppDriver#257]
Hi,
I am trying to use PageFactory support along with WinAppDriver and java-client 5.0.0-BETA9

public static AppiumDriver mobileDriver;

    public static void getWindowsDriver() throws MalformedURLException {
            mobileDriver = new WindowsDriver(new URL("http://127.0.0.1:4723"), capabilities);
            mobileDriver.manage().timeouts().implicitlyWait(10000, TimeUnit.SECONDS);
    }

PageObject class...    

 @CacheLookup
    @WindowsFindBy(xpath = "//*[@AutomationId='LoginBox']")
    private MobileElement userInput;

public LoginScreen(AppiumDriver driver) {
        this.driver = driver;
        PageFactory.initElements(new AppiumFieldDecorator(driver), this);
    }

I am getting following stack trace:
           java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field pl.azimuthit.itests.system.pageobjects.nativeos.LoginScreen.userIDinput to 

org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$dd998978
      	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
      	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
      	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
      	at java.lang.reflect.Field.set(Field.java:764)
      	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
      	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
      	at package.LoginScreen.<init>(LoginScreen.java:53)

Thanks in advance for your support.

**Comment by timotiusmargo** [comment]
Hi @balawider,

Are you getting any log from the `WinAppDriver.exe`? If so, can you paste the last few command logs? For example:

```
==========================================
POST /session HTTP/1.1
Accept: application/json, image/png
Content-Length: 93
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"desiredCapabilities":{"app":"C:\\Windows\\System32\\notepad.exe","platformName":"Windows"}}

HTTP/1.1 200 OK
Content-Length: 141
Content-Type: application/json

{"sessionId":"72108E74-1332-46C3-BD73-86188D37D7F4","status":0,"value":{"app":"C:\\Windows\\System32\\notepad.exe","platformName":"Windows"}}


==========================================
GET /session/72108E74-1332-46C3-BD73-86188D37D7F4/title HTTP/1.1
Accept: application/json, image/png
Host: 127.0.0.1:4723

HTTP/1.1 200 OK
Content-Length: 92
Content-Type: application/json

{"sessionId":"72108E74-1332-46C3-BD73-86188D37D7F4","status":0,"value":"Untitled - Notepad"}
```

This log will help us identify where the issue is.

**Comment by mlntest** [comment]
Seeing the same error while performing the below statement using WindowsDriver
 PageFactory.initElements(new AppiumFieldDecorator(screenDriver), this);

WinAppDriver Log:
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 156
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] {"desiredCapabilities":{"app":"RSASecurityLLC.41774A50BECC7_1ze70x1yhyay8!App","automationName":
"Appium","platformName":"Windows","deviceName":"WindowsPC"}}
[WinAppDriver] [STDOUT] SessionManager - Creating session
[WinAppDriver] [STDOUT] SessionManager - WinAppDriver succeeded loading MitaBroker
[WinAppDriver] [STDOUT] SessionManager - Application launched
[WinAppDriver] [STDOUT] SessionManager - Session successfully created: EA896750-9080-408F-A452-18169003BB1D
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 153
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] {"sessionId":"EA896750-9080-408F-A452-18169003BB1D","status":0,"value":{"app":"RSASecurityLLC.41
774A50BECC7_1ze70x1yhyay8!App","platformName":"Windows"}}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"EA896750-9080-408F-A452-18169003BB1D","status":0,"val
ue":{"app":"RSASecurityLLC.41774A50BECC7_1ze70x1yhyay8!App","platformName":"Windows"}}
[Appium] New WindowsDriver session created successfully, session b2465c41-d0ee-4ec5-960f-04e8ecb01e03 added to master se
ssion list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1507218355461 (08:45:55 GMT-0700 (Pacific Daylight Time))
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"app":"RSASecurityLLC.41774A50BECC7_1ze70x1y
hyay8!App","automationName":"Appium","platformName":"Windows","deviceName":"WindowsPC"}
[HTTP] <-- POST /wd/hub/session 200 812 ms - 204
[HTTP] --> GET /wd/hub/session/b2465c41-d0ee-4ec5-960f-04e8ecb01e03 {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/b2465c41-d0ee-4ec5-960f-04e8ecb01e03] to [GET http://127.0.0.1:4724
/wd/hub/session/EA896750-9080-408F-A452-18169003BB1D] with body: {}
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] GET /wd/hub/session/EA896750-9080-408F-A452-18169003BB1D HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 153
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] {"sessionId":"EA896750-9080-408F-A452-18169003BB1D","status":0,"value":{"app":"RSASecurityLLC.41
774A50BECC7_1ze70x1yhyay8!App","platformName":"Windows"}}
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"EA896750-9080-408F-A452-18169003BB1D\",\"status\"
:0,\"value\":{\"app\":\"RSASecurityLLC.41774A50BECC7_1ze70x1yhyay8!App\",\"platformName\":\"Windows\"}}"
[JSONWP Proxy] Replacing sessionId EA896750-9080-408F-A452-18169003BB1D with b2465c41-d0ee-4ec5-960f-04e8ecb01e03
[HTTP] <-- GET /wd/hub/session/b2465c41-d0ee-4ec5-960f-04e8ecb01e03 200 28 ms - 153
[HTTP] --> GET /wd/hub/session/b2465c41-d0ee-4ec5-960f-04e8ecb01e03 {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/b2465c41-d0ee-4ec5-960f-04e8ecb01e03] to [GET http://127.0.0.1:4724
/wd/hub/session/EA896750-9080-408F-A452-18169003BB1D] with body: {}
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] GET /wd/hub/session/EA896750-9080-408F-A452-18169003BB1D HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] HTTP/1.1 200 OK
[WinAppDriver] [STDOUT] Content-Length: 153
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] {"sessionId":"EA896750-9080-408F-A452-18169003BB1D","status":0,"value":{"app":"RSASecurityLLC.41
774A50BECC7_1ze70x1yhyay8!App","platformName":"Windows"}}
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"EA896750-9080-408F-A452-18169003BB1D\",\"status\"
:0,\"value\":{\"app\":\"RSASecurityLLC.41774A50BECC7_1ze70x1yhyay8!App\",\"platformName\":\"Windows\"}}"
[JSONWP Proxy] Replacing sessionId EA896750-9080-408F-A452-18169003BB1D with b2465c41-d0ee-4ec5-960f-04e8ecb01e03
[HTTP] <-- GET /wd/hub/session/b2465c41-d0ee-4ec5-960f-04e8ecb01e03 200 20 ms - 153

**Comment by yodurr** [comment]
Hi @mlntest please re-open if you're still having an issue here.  It's unclear to me where the issue is in your above trace.
