### ISSUE TITLE
Why doesn't WinAppDriver listen on /wd/hub endpoint per selenium default?

### ISSUE THREAD

**Issue by zumwald** [Microsoft/WinAppDriver#26]
FYI for other folks hitting the issue when attempting to "plug and play" Appium code from another platform. I was hitting a 404 when making my first session call.

`POST /wd/hub/session HTTP/1.1
.....
HTTP/1.1 404 Not Found`

Took me a couple minutes of debugging to realize my boilerplate server config needed to be tweaked to integrate with this. For Windows automation I have to override my server path to "/" rather than the default of "/wd/hub". It's not a _big_ deal, but kind of annoying.

**Comment by yodurr** [comment]
Thanks for posting this.  We can add /wd/hub to the path if needed.  A few areas we want to investigate further before we make the switch - so for now please apply the change zumwald recommends.

**Comment by alakshmi1030** [comment]
With the Appium 1.6 release you can point your tests at the Appium server which is listening on /wd/hub and it will broker to WinAppDriver
