### ISSUE TITLE
Can only run tests from VS in debug

### ISSUE THREAD

**Issue by tj-cappelletti** [Microsoft/WinAppDriver#263]
I just updated my `WinAppDriver` to the latest release, [v1.0-RC](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.0-RC), and I'm having issues running the test from Visual Studio 2017. If I select the test and hit "Run", the test starts up as expected, launches the application, but the application never comes into focus. So when I try to `Click` a control, the application never receives the event.

<img width="360" alt="debug" src="https://user-images.githubusercontent.com/20914729/30375901-44836ec2-9858-11e7-857a-a8b1c030ea7c.PNG">

If I run the test by clicking "Debug", the test starts up as before, the application launches, but this time it's in focus so my click events successfully get sent to the application.

<img width="360" alt="run" src="https://user-images.githubusercontent.com/20914729/30375900-447c33e6-9858-11e7-9126-ef556528e49e.PNG">

I've also noticed that this only is a problem when I'm working on a machine with one monitor. If I'm using a machine with multiple monitors, the application I'm trying to test launches on another screen that VS is not on. I've also tried in my setup method (see below) to try and force it come into focus (not sure if this was the right approach or not) without success.

``` C#
public static void Setup(TestContext context)
{
    if (WindowsDriver != null) return;

    var demoAppFullPath = Path.GetFullPath(DemoAppRelativepath);

    // Create a new session to launch application
    var desiredCapabilities = new DesiredCapabilities();
    desiredCapabilities.SetCapability("app", demoAppFullPath);
    WindowsDriver = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), desiredCapabilities);

    WindowsDriver.SwitchTo().Window(WindowsDriver.CurrentWindowHandle);

    Assert.IsNotNull(WindowsDriver);
    Assert.IsNotNull(WindowsDriver.SessionId);

    // Set implicit timeout to 1.5 seconds to make element search to retry every 500 ms for at most three times
    WindowsDriver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(1.5);
}
```

Below is the code for my test, let me know if you need any other details.

``` C#
[TestMethod]
[TestCategory("Automated"), TestCategory("Addition")]
public void TestAddTwoIntegers()
{
    WindowsDriver.FindElementByAccessibilityId("TwoButton").Click();

    var displayText = WindowsDriver.FindElementByAccessibilityId("DisplayLabelTextBlock").Text;
    Assert.AreEqual("2", displayText);

    WindowsDriver.FindElementByName("+").Click();

    WindowsDriver.FindElementByAccessibilityId("TwoButton").Click();

    displayText = WindowsDriver.FindElementByAccessibilityId("DisplayLabelTextBlock").Text;
    Assert.AreEqual("2", displayText);

    WindowsDriver.FindElementByName("=").Click();

    displayText = WindowsDriver.FindElementByAccessibilityId("DisplayLabelTextBlock").Text;
    Assert.AreEqual("4", displayText);
}
```

**Comment by hassanuz** [comment]
Hi @tj-cappelletti, 

Are you still seeing this issue on v1.1? There are known issues with multiple displays that we have on our backlog.

**Comment by hassanuz** [comment]
Closing issue. Please reopen if you still experience this.
