### ISSUE TITLE
For IE the Open, Save, Cancel buttons in toolbar is not available in WinAppDriver

### ISSUE THREAD

**Issue by dhapolapankaj** [Microsoft/WinAppDriver#265]
Hello Team,

When I click on download link, I see below download toolbar.
![ie-toolbar-opensavecancel](https://user-images.githubusercontent.com/29034223/30426958-a1a35fd6-996b-11e7-9033-ee0fcb3e65a0.png)

Now Inspect.exe is showing the buttons

![ie-toolbar-opensavecancel-inspect](https://user-images.githubusercontent.com/29034223/30427085-0c64cfd0-996c-11e7-81a3-3723311b690d.png)

I dug little deeper, exported page source and tried to find the child elements
Below is the snippet of Page SOurce

`    <Pane AcceleratorKey="" AccessKey="" AutomationId="" ClassName="Frame Notification Bar" FrameworkId="Win32" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="pane" Name="" Orientation="None" ProcessId="5312" RuntimeId="42.1643886" x="0" y="0" width="0" height="0">`      

`<ToolBar AcceleratorKey="" AccessKey="" AutomationId="IENotificationBar" ClassName="DirectUIHWND" FrameworkId="Win32" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="tool bar" Name="Notification" Orientation="None" ProcessId="5312" RuntimeId="42.988984" x="0" y="0" width="0" height="0" /> `

 `</Pane>`

findELementsByXPath do not return any child.

Please have a look.

**Comment by khouzam** [comment]
This should be addressed by our [RC2 release](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.0-RC2).

Thanks for the patience.

**Comment by dhapolapankaj** [comment]
Hi @khouzam 

Thanks for taking this on priority!

The issue seemed to be resolved, I tried the pre RC2 release version and I was able to click on those buttons.
Though my issue has been resolved, I would like to highlight that the Text inside this Pane is not available

Below is the PageSource



      <ToolBar AcceleratorKey="" AccessKey="" AutomationId="IENotificationBar" ClassName="DirectUIHWND" FrameworkId="Win32" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="tool bar" Name="Notification" Orientation="None" ProcessId="4072" RuntimeId="42.266014" x="2400" y="895" width="960" height="50">

        <Text AcceleratorKey="" AccessKey="" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="text" Name="Notification bar Text" Orientation="None" ProcessId="4072" RuntimeId="" x="2416" y="909" width="356" height="27" />

        <Button AcceleratorKey="" AccessKey="Alt+O" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="button" Name="Open" Orientation="None" ProcessId="4072" RuntimeId="" x="3093" y="910" width="73" height="25" />
        <SplitButton AcceleratorKey="" AccessKey="Alt+S" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="split button" Name="Save" Orientation="None" ProcessId="4072" RuntimeId="" x="3166" y="910" width="84" height="25">

          <SplitButton AcceleratorKey="" AccessKey="" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="split button" Name="6" Orientation="None" ProcessId="4072" RuntimeId="" x="3231" y="910" width="16" height="25" />
        </SplitButton>

        <Button AcceleratorKey="" AccessKey="Alt+C" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="button" Name="Cancel" Orientation="None" ProcessId="4072" RuntimeId="" x="3250" y="910" width="80" height="25" />

        <Button AcceleratorKey="" AccessKey="" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="button" Name="Close" Orientation="None" ProcessId="4072" RuntimeId="" x="3337" y="916" width="16" height="16" />

      </ToolBar>
    

Though we have the Text tag but the content ("**Do you want to open or save**") is missing.

**Comment by hassanuz** [comment]
Closing as original issue is resolved.
