### ISSUE TITLE
Can WinAppDriver Interact with MMC Apps As Non-Administrator?

### ISSUE THREAD

**Issue by auyong** [Microsoft/WinAppDriver#267]
I'm not sure where I can ask a question so I am asking it here.
Can WinAppDriver be used to test apps written using MMC (Microsoft Management Console) without having to be an administrator? I have tried numerous tools, like Sikuli to try to automate testing of some Windows apps written using MMC, but Sikuli only works when it is launched using administrator.

**Comment by khouzam** [comment]
Hi @auyong,

Is the MMC application running as administrator or is it running as a regular user? Does the MMC application have accessibility hooks? If you run inspect from the Windows SDK, does it show elements in the MMC application?

**Comment by auyong** [comment]
Hi Khouzam,
Thanks for getting back to me. Answers below:
1) The MMC application is running as normal user
2/3) I am not sure about accessibility hooks, but there are lots of elements that will be displayed if you use the Inspect tool from the SDK.
4) I have tried with Microsoft's UIAutomation.dll tool and it seems to be able to interact with the MMC application even when I am logged in as a non-Admin user (running the script in a normally opened Powershell window).

**Comment by khouzam** [comment]
Hi @auyong 

In this case, you can simply launch WinAppDriver as a regular user and interact with the MMC application, as long as you can see the elements in the accessibility tree.

**Comment by khouzam** [comment]
Closing as it seems to have been addressed. Please reopen otherwise.
