### ISSUE TITLE
api-ms-win-core-registry-l2-2-0.dll is missing from your computer

### ISSUE THREAD

**Issue by SanjeevKumarmn** [Microsoft/WinAppDriver#268]
While invoking the WinAppDriver.exe, I'm getting error - "api-ms-win-core-registry-l2-2-0.dll is missing from your computer. try reinstalling the program to fix this problem.' This is on windows 8. I see the dll is found in C:\Windows\System32\  folder!

**Comment by khouzam** [comment]
Hi @SanjeevKumarmn,

WinAppDriver is built to run on Windows 10. It will not run on Windows 8.

**Comment by SanjeevKumarmn** [comment]
Thanks for the reply. Does this WinApp works on Windows 10 .NET based infragistics forms?

**Comment by khouzam** [comment]
WinAppDriver should work on most applications that are enabled to use the UIAccessibility framework. The application does not need to target Windows 10, but WinAppDriver does need to run on Windows 10.

**Comment by khouzam** [comment]
Closing as it seems to have been addressed. Please reopen otherwise.

**Comment by elizhang99** [comment]
I'm now in window server 12 r2, and I'm also suggesting that this file is missing, online help.  tks a lot.
