### ISSUE TITLE
UI interface to start and stop WinAppDriver.exe

### ISSUE THREAD

**Issue by SanjeevKumarmn** [Microsoft/WinAppDriver#269]
Most of the organizations does not provide admin rights to run the software. Normally organization provide execution privileges and not the admin rights. It would be good if we have a UI interface that can work similar to Appium/ HP LeanFT. Also, to start/stop services without admin rights and works on identifying the AUT.

**Comment by khouzam** [comment]
Hi @SanjeevKumarmn,
You don't need admin rights to run WinAppDriver, you can simply launch it from either the command line or from File Explorer. You do need admin rights if you want to perform automation from a different machine and have WinAppDriver listen on a network interface other than localhost. Also we are integrated with Appium and WinAppDriver will start and stop at Appuim's request.

**Comment by SanjeevKumarmn** [comment]
Thanks for the response
