### ISSUE TITLE
Will WinAppDriver support Hybrid (HTML5) applications?

### ISSUE THREAD

**Issue by kovacserik** [Microsoft/WinAppDriver#27]
Mobile & Desktop as well

**Comment by yodurr** [comment]
You can inspect a webview as far as the narrator can see it.  A deeper dive into the DOM with WinAppDriver as your starting point is something we're evaluating with the Edge team.

**Comment by kovacserik** [comment]
Thanks for you answer, yodurr.

@yodurr I think I wasn't 100% clear, my question is will WinAppDriver support Híbrid application like Cordova-based mobile applications? 

Thanks.

**Comment by alakshmi1030** [comment]
Supporting Hybrid applications like Cordova is something we are investigating as well.

**Comment by kirankumarb4u** [comment]
Is there any timeline available for adding this feature

**Comment by yodurr** [comment]
Sorry for the delay in replying to your question.  We're still working on the answer.

**Comment by yodurr** [comment]
Yes, you can test a cordova app.  See https://github.com/Microsoft/WinAppDriver/issues/42
for info on how to get the app id when starting up the test session.

**Comment by maesiva** [comment]
Please share if any update on Cordova app support for Mobile. 
Seems, we can launch the Cordova based hybrid apps and do limited operations. 
Linking to a related issue I created:
https://github.com/Microsoft/WinAppDriver/issues/173

**Comment by YisraelV** [comment]
"A deeper dive into the DOM with WinAppDriver as your starting point is something we're evaluating with the Edge team."

@yodurr Is it possible today to automate  webview which is inside a uwp app, using DOM based locators?
