### ISSUE TITLE
Finding value of an element

### ISSUE THREAD

**Issue by djewiss** [Microsoft/WinAppDriver#270]
Hi there

I am testing a wpf app that uses Windows Report Viewer to show reports. I am trying to access elements on the report but am having trouble accessing the text. I can see the element, which has the name "Text Box", but not the value "User Text One" in this instance. Is there a way for me to access the value?

I'm using winappdriver 1.0 RC1, writing the tests in C#

![2017-09-21 11_07_40-inspect hwnd_ 0x000a04f4](https://user-images.githubusercontent.com/6746403/30671933-a1b19bee-9ebd-11e7-99c6-8b1574c471b9.png)

**Comment by dhapolapankaj** [comment]
Are you able to get the instance of this element?

If yes, you can use 
`elementObject.GetAttribute("Value")`

**Comment by timotiusmargo** [comment]
Hi @djewiss,

We are currently supporting UI Automation mode and test against it. When you set your `inspect.exe` to **UI Automation** mode, does it give you the value you need in any of the attribute?

**Comment by djewiss** [comment]
Hi timotiusmargo 

I cannot see that value when inspect.exe is in UI Automation mode. I'll try something different. Thanks
