### ISSUE TITLE
JAVA :: Get Location or Rectangle

### ISSUE THREAD

**Issue by PeSoski** [Microsoft/WinAppDriver#273]
Hi,
is there any way to get location or rectangle (same way like Inspect.exe)?
Now when I use geoLocation() appium throw an error:
`[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server.`

**Comment by dhapolapankaj** [comment]
I tried
 `GetAttribute('BoundingRectangle')`

I got output in following string

Top: int Left: int Width: int Height: int
You will have to use string manipulation functions to extract this int values

**Comment by PeSoski** [comment]
Thanks :D

**Comment by timotiusmargo** [comment]
In addition to @dhapolapankaj suggestion, you can also use [Location](https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/Tests/WebDriverAPI/ElementLocation.cs#L39) to get the **relative** element location from the application main window. For instance:

```c#
WindowsElement num5Button = session.FindElementByAccessibilityId("num5Button");
WindowsElement num7Button = session.FindElementByAccessibilityId("num7Button");
WindowsElement num8Button = session.FindElementByAccessibilityId("num8Button");

Assert.IsNotNull(num5Button);
Assert.IsNotNull(num7Button);
Assert.IsNotNull(num8Button);

// Num 8 is in the same column with Num 5 and is in the same row with Num 7
Assert.AreEqual(num8Button.Location.X, num5Button.Location.X);
Assert.AreEqual(num8Button.Location.Y, num7Button.Location.Y);

// Num 8 is on the right of Num 7 and on top of Num 5 (Y increases from top to bottom)
Assert.IsTrue(num8Button.Location.X > num7Button.Location.X);
Assert.IsTrue(num8Button.Location.Y < num5Button.Location.Y);
```

When you are interested in getting the **absolute** element location on the screen similar to what the `BoundingRectangle` attribute will return, you can add the [Window Location](https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/Tests/WebDriverAPI/Window.cs#L341) to offset the relative location retrieved above.

**Comment by dhapolapankaj** [comment]
Hey @timotiusmargo 
I am little bit confused.
I am trying to find the absolute location of a control irrespective of position of its parent window.
Do we have ways to achieve this? `BoundingRectangle` isn't helping me.

Basically what I am try to do is move the mouse pointer and click at that location. I am using `ActionBuilder` Class. 
Are you suggesting the [link](https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/Tests/WebDriverAPI/Window.cs#L341) mentioned in previous reply will help?

I shall be trying this in sometimes later.

Regards
PD

**Comment by hassanuz** [comment]
Closing ticket as issue appears to be solved.
