### ISSUE TITLE
touchscreen scroll/flick example in Java?

### ISSUE THREAD

**Issue by tarunsujit** [Microsoft/WinAppDriver#275]
Can I have a method or example for scroll in java

**Comment by prabhuak90** [comment]
I am also having the same question team please provide the workaround or solution for scrolling the windows page or swipe down i found few examples in C# but i wanna solution for java

**Comment by ravimidathala** [comment]
Hi, 
Even I have the same issue. Can anyone please give an example for horizontal scrolling on Windows app. I have been trying to use the example given in C#, but could not get it. 

Help will be appreciated.

**Comment by timotiusmargo** [comment]
Hi @ravimidathala,

Can you try the sample scenarios found in `WebDriverAPI` test below?
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/TouchScroll.cs

If somehow you encounter any issue, would you please open a new issue and paste the JSON wire protocol command log from `WinAppDriver.exe` console?

**Comment by hassanuz** [comment]
Marking issue as closed due to no furthercomments.
