### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: [object Object] while launching app which has splash screen on windows 10

### ISSUE THREAD

**Issue by KrishnaKokila** [Microsoft/WinAppDriver#277]
When i try to launch a wpf application which has a splash screen at the start gives the following error.

Test method winAppTest.UnitTest1.TestMethod1 threw exception: 
System.InvalidOperationException: An unknown server-side error occurred while processing the command. Original error: [object Object]

It does open the app but looks like its searching for the process name of the splash screen which shows no name in task manager. it does show login window after launching.

Any help?

**Comment by timotiusmargo** [comment]
Hi @KrishnaKokila,

Would you check out issue #213 and try the resolution? This resolution has addressed many splash screen behavior experienced by others.

**Comment by KrishnaKokila** [comment]
Thanks @timotiusmargo , but unfortunately that solution didnt help since i get an error while performing launch of the application.

attached exception for reference
![winapp launch](https://user-images.githubusercontent.com/32564936/31433161-12ca190e-ae96-11e7-9a39-3afb5eb06df7.jpg)

**Comment by timotiusmargo** [comment]
Hi @KrishnaKokila,

Can you provide the `WinAppDriver.exe` console output of your session creation like below?
```
==========================================
POST /session HTTP/1.1
Accept: application/json, image/png
Connection: Keep-Alive
Content-Length: 104
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"desiredCapabilities":{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","platformName":"Windows"}}
HTTP/1.1 200 OK
Content-Length: 152
Content-Type: application/json

{"sessionId":"73AA2D52-FD09-4234-A129-FF6A94913C46","status":0,"value":{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","platformName":"Windows"}}
```

This should show the reason why the session creation failed.

**Comment by KrishnaKokila** [comment]
Thanks @timotiusmargo Below is the snippet

 POST /wd/hub/session {"desiredCapabilities":{"platformName ":"Windows","deviceName":"WindowsPC","app":"C:\\Program Files (x86)\\Itron\\Toolbox\\Itron.Toolbox.exe","newCommandTimeout":"120","platformName":"Windows"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName ":"Windows","deviceName":"WindowsPC","app":"C:\\Program Files (x86)\\Itron\\Toolbox\\Itron.Toolbox.exe","newCommandTimeout":"120","platformName":"Windows"},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1507806347348 (16:35:47 GMT+0530 (India Standard Time))
[Appium] Creating new WindowsDriver (v0.5.0) session
[Appium] Capabilities:
[Appium]   platformName : 'Windows'
[Appium]   deviceName: 'WindowsPC'
[Appium]   app: 'C:\\Program Files (x86)\\Itron\\Toolbox\\Itron.Toolbox.exe'
[Appium]   newCommandTimeout: '120'
[Appium]   platformName: 'Windows'
[BaseDriver] Capability 'newCommandTimeout' changed from string ('120') to integer (120). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: platformName , app.
[BaseDriver] Session created with session id: 84981967-0bdf-4c60-b093-c1dceb8b2993
[WinAppDriver] Verifying WinAppDriver is installed with correct checksum
[debug] [WinAppDriver] WinAppDriver changed state to 'starting'
[WinAppDriver] Killing any old WinAppDrivers on same port, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"4724 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I winappdriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
[WinAppDriver] No old WinAppDrivers seemed to exist
[WinAppDriver] Spawning winappdriver with: undefined 4724/wd/hub
[WinAppDriver] [STDOUT] Windows Application Driver Beta listening for requests at: http://127.0.0.1:4724/wd/hub
[debug] [WinAppDriver] WinAppDriver changed state to 'online'
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:4724/wd/hub/session] with body: {"desiredCapabilities":{"platformName ":"Windows","deviceName":"WindowsPC","app":"C:\\Program Files (x86)\\Itron\\Toolbox\\Itron.Toolbox.exe","newCommandTimeout":120,"platformName":"Windows"}}
[WinAppDriver] [STDOUT] Press ENTER to exit.
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 192
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] {"desiredCapabilities":{"platformName ":"Windows","deviceName":"WindowsPC","app":"C:\\Program Files (x86)\\Itron\\Toolbox\\Itron.Toolbox.exe","newCommandTimeout":120,"platformName":"Windows"}}
[WinAppDriver] [STDOUT] SessionManager - Creating session
[WinAppDriver] [STDOUT] SessionManager - WinAppDriver succeeded loading MitaBroker
[WinAppDriver] [STDOUT] HTTP/1.1 500 Internal Error
[WinAppDriver] [STDOUT] Content-Length: 133
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [WinAppDriver] Deleting WinAppDriver session
[MJSONWP] Encountered internal error running command:  {"jsonwp":{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}} ProxyRequestError: Could not proxy command to remote server. Original error: 500 - {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:152:13)
    at tryCatch (C:\Users\BGH48860\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\BGH48860\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\BGH48860\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\BGH48860\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 8719 ms - 152

**Comment by khouzam** [comment]
Hi @KrishnaKokila 

Can you try this with a more current build of Appium WinAppDriver? This seems to be a fairly old version of WinAppDriver that is being invoked.

Thanks

**Comment by hassanuz** [comment]
Marking issue as closed due to no additional comments.
