### ISSUE TITLE
How to inspect a web view in a Windows app? 

### ISSUE THREAD

**Issue by ifritz7** [microsoft/WinAppDriver#278]
Hello,

I am trying to figure out how to inspect the elements in the webview of my windows app. I need to find the correct selectors. So far, inspect.exe only shows me native Windows UI elements.

**Comment by jsbakker** [comment]
Interesting...I was asking the same thing in issue #264 but it turned out that inspect.exe was actually finding elements. I wonder what is the difference...mine was a webview inside of a Universal Windows Platform app. Is yours a Win32 app, what kind of webview component are you using, etc?

**Comment by ifritz7** [comment]
It is a Win32 app using CEF3. inspect.exe is no help... any suggestions?

**Comment by khouzam** [comment]
Hi @ifritz7,

If inspect is not help, then WinAppDriver will not help either as its leveraging the same UIAutomation infrastructure.

From a quick search, you might need to use ChromeDriver which provides the functionality: https://bitbucket.org/chromiumembedded/cef/wiki/UsingChromeDriver

**Comment by ifritz7** [comment]
Thanks, maybe someone could connect ChromeDriver to WinDriver in the future somehow??

**Comment by khouzam** [comment]
Thanks for the suggestion. We'll take it into consideration.

**Comment by sasha943** [comment]
any updates

**Comment by hassanuz** [comment]
This isn't something we have in the pipeline.

**Comment by njumazhen** [comment]
> This isn't something we currently have in the pipeline.

So WinAppDriver is not support to test the hybrid desktops like win32 combined with cef?
