### ISSUE TITLE
Getting error while installing WinAppDriver.exe in my laptop

### ISSUE THREAD

**Issue by pavanturlapati** [Microsoft/WinAppDriver#28]
Hi Team,
When I trying to install the WinAppDriver.exe, I am getting the below error. Could you please let me know what prerequisites do we need before installaing the WinAppDriver.exe

My System details:
Windows 7 - OS
.Net Framework - 4.0

---------------------------
WinAppDriver.exe - System Error
---------------------------
The program can't start because api-ms-win-shcore-scaling-l1-1-1.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------

**Comment by pavanturlapati** [comment]
Any update or suggestions? I was able to run the same .exe in a laptop where I am Windows 10 + Visual Studio Ultimate. Is the .exe version or OS specific?

**Comment by pavanturlapati** [comment]
Not sure if anybody got a chance to see, but on my research I observed that the "api-ms-win-shcore-scaling-l1-1-1.dll" is windows operating system .dll and is available only from Windows 8. 
So, I assume that this WinAppDriver.exe will not work on Windows7 operating system.

Reference Links:
http://www.nirsoft.net/dll_information/windows8/api-ms-win-shcore-scaling-l1-1-0_dll.html
http://www.win7dll.info/a.html#letter_dll_links
https://msdn.microsoft.com/en-us/library/windows/desktop/dn302060(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/hh802763(v=vs.85).aspx

Could somebody please confirm..

**Comment by jonstoneman** [comment]
WinAppDriver requires Windows 10

**Comment by yodurr** [comment]
Jon is correct, we only support Win10 currently.  Supporting Win8 or Win7 is something we may consider in the future.
