### ISSUE TITLE
Running test in Windows docker or inside locked system

### ISSUE THREAD

**Issue by SanjeevKumarmn** [Microsoft/WinAppDriver#280]
Is there any solution currently available for running test inside the windows docker with Winappdriver? Or if test can be ran when the system is locked?

**Comment by SanjeevKumarmn** [comment]
Someone pls guide me?

**Comment by hassanuz** [comment]
Hi @SanjeevKumarmn, 

Can you clarify the scenario you are testing?

**Comment by SanjeevKumarmn** [comment]
I have a Windows app that we run the tests in windows 10 machine and if the tests are run from Jenkins, I need to turn off the screensaver. Also we need to keep the system unlocked for the test that are scheduled overnight for unmanned. For security reason, it's not safe to keep the system unlocked and also its a big process to get this security turn off locks in certain companies. So how we run the test with system locked in more secured way? Can we achieve something similar to selenium docker(refer hub.docker.com) for running Windows app inside the docker / headless mode? This would let us effectively use the unutilized CPU capacity for parallel windows app testing and completeing the tests much faster.

**Comment by shankarkc** [comment]
@SanjeevKumarmn Windows docker doesnt support UI..
Pls Read [this](https://social.msdn.microsoft.com/Forums/en-US/dab0d833-ff84-48f4-babf-ea776783cef7/how-to-connect-docker-container-using-rdp?forum=windowscontainers)

**Comment by SanjeevKumarmn** [comment]
Ok, I got a solution something similar to docker by installing Hyper-V with Windows 10. Then I made Hyper-V VMs as the Jenkins slaves with Maven installed. For a 16GB RAM i7 windows 10 with 120GB HD, I was able to create 3 Hyper-V VM's with  35 GB each physical c drive space.

**Comment by hassanuz** [comment]
Closing as per @SanjeevKumarmn 's resolution.
