### ISSUE TITLE
Unable to click on Text Element which is show as a pointer when hovers mouse to

### ISSUE THREAD

**Issue by watarus-nt** [Microsoft/WinAppDriver#281]
Hi,

My Cordova UWP app has some TEXT elements which will show a drop-down menu after clicking on it.
Those elements are TEXT element as shown in the Page Source. On the app, when the mouse is pointed at them, we can click to open the drop-down menu.

Can we have a fix on that so WinAppDriver can click on this type of TEXT element?
I'm using Appium v1.7.1 and WinAppDriver v0.7 (I guess, as WinAppDriver is installed along with Appium).

**_Error message:_**
```
[WinAppDriver] [STDOUT] {"status":105,"value":{"error":"element not interactable","message":"An element command could not be completed because the element is not pointer- or keyboard interactable."}}
[MJSONWP] Encountered internal error running command:  {"jsonwp":{"status":105,"value":{"error":"element not interactable","message":"An element command could not be completed because the element is not pointer- or keyboard interactable."}}} ProxyRequestError: Could not proxy command to remote server. Original error: 400 - {"status":105,"value":{"error":"element not interactable","message":"An element command could not be completed because the element is not pointer- or keyboard interactable."}}
```

_**Page Source XML:**_
```
<Text AcceleratorKey="" AccessKey="" AutomationId="" ClassName="" FrameworkId="MicrosoftEdge"
                          HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True"
                          IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="True" IsPassword="False"
                          IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="text" Name="すべて"
                          Orientation="None" ProcessId="6488" RuntimeId="42.3543334.2.787" x="463" y="56" width="43"
                          height="32"/>
```

Thanks and Regards

**Comment by timotiusmargo** [comment]
Hi @watarus-nt,

The **Page Source XML** you pasted above indicates that the text element is offscreen or hidden (i.e. `IsOffscreen="True"`) at the moment you are capturing it. Is this always the case? Is it actually displayed front and center unobstructed from any other element when you try to click it? Typically `IsOffscreen` attribute is only true when it is not displayed which prevents Windows Application Driver to perform a proper click on it.

**Comment by watarus-nt** [comment]
Oops, I didn't notice that attribute, thanks for pointing it out. I don't have access to my working machine right now to get the page source again. But I can always see that element on the GUI actually and clock to it manually, will double check and let you know on Monday.

In case IsOffScreen=False, can WinAppDriver click to that Text element?
Could you please let me know how to search for the corresponding element's attribute in JavaScript/AngularJs code as well? Thanks in advance!

**Comment by timotiusmargo** [comment]
When an element is **offscreen** (not displayed), Windows Application Driver will attempt to scroll it into view when applicable and only click the element if it is **onscreen** (displayed) then. In other words, Windows Application Driver doesn't click on the element that is not displayed on screen as it does not make sense in most scenario.

I'm not sure how the JavaScript command look like in Selenium/Appium, but typically an **element** should have a `Displayed` property that will be `True` when `IsOffScreen` is `False` and vice versa. Below is a C# snippet taken from the [ElementDisplayed](https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC2/Tests/WebDriverAPI/ElementDisplayed.cs#L39) sample test.
```c#
WindowsElement addAlarmButton = session.FindElementByAccessibilityId("AddAlarmButton");
Assert.IsTrue(addAlarmButton.Displayed);
```

Alternatively you can access the `IsOffScreen` attribute directly using `element.GetAttribute` API. See [GetElementAttribute](https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC2/Tests/WebDriverAPI/ElementAttribute.cs#L38) example.

```

**Comment by watarus-nt** [comment]
Ya, got it, thanks for your comment! 
The application which I'm testing has some drop-down menu elements with `LocalizedControlType=Text` and `IsOffScrren=True`. Hence I'm unable to click on them by Appium/WinAppDriver API while they are still clickable by a mouse click.

And even `IsOffScrren=True`, I'm still able to see the element displays on the screen.
Do we have any API which can hover/move mouse to that type of element?
If yes, it will be very helpful for automation testing. After mouse's pointer is pointed at the element, I can use another library to simulate a physical mouse click.

**Comment by timotiusmargo** [comment]
Hi @watarus-nt,

Sorry for the long delay as this issue slipped through. We actually have some sample scenarios below demonstrating ad-hoc mouse actions such as moving and clicking. I.e.
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/Mouse.cs#L55
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/Mouse.cs#L117

The [`MouseDownMoveUp`](https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/Mouse.cs#L117) sample test covers the ad-hoc mouse move where you can additionally specify the offset from the target element coordinate as follows:
```c#
// Send mouse down, move, and up actions combination to perform a drag and drop 
// action on the app title bar. These actions reposition Calculator window.
session.Mouse.MouseMove(appNameTitle.Coordinates);
session.Mouse.MouseDown(null); // Pass null as this command omit the given parameter
session.Mouse.MouseMove(appNameTitle.Coordinates, offset, offset);
session.Mouse.MouseUp(null); // Pass null as this command omit the given parameter
```

Similar ad-hoc touch actions examples can also be found on the sample tests below:
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/TouchDownMoveUp.cs#L48
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/TouchDownMoveUp.cs#L75

Hope this helps.

**Comment by sachinDV** [comment]
Menu item's sub item is showing isOffscreen false,but it is visible.How to select this with WinAppDriver?
