### ISSUE TITLE
Click Element based on Co-Ordinates

### ISSUE THREAD

**Issue by vikrampvr** [Microsoft/WinAppDriver#285]
Hello,

I am trying to click a particular point on a control. Making use of "Actions" class like below.

Actions action = new Actions(session);
action.MoveToElement(element, x, y).Click().Perform(); 

Also tried : action.MoveByOffset(x, y).Click().Perform();

Both returning the error saying "Unable to locate the element with given properties" where as i am able to perform click operation on same elements using element.click();

Please confirm if Actions class is supported while using  WinAppDriver. 
If not what is the best way to perform click based on co-ordinates.

Thank you.

**Comment by mdmamunkhan** [comment]
Yes, I am having same issue can't click abased on co-ordinates.

**Comment by vikrampvr** [comment]
Hello,

Appreciate any update on this issue.

Thank you.

**Comment by timotiusmargo** [comment]
Hi @vikrampvr, @mdmamunkhan,

Not sure exactly what JSON wire protocol commands being sent from the script you put together above. Can you please provide the generated command log from `WinAppDriver.exe` console?

Meanwhile we actually have some sample scenarios below demonstrating ad-hoc mouse actions such as moving and clicking without using the `Actions` object. I.e.
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/Mouse.cs#L55
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/Mouse.cs#L117

The [`MouseDownMoveUp`](https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/Mouse.cs#L117) sample test covers the ad-hoc mouse move where you can additionally specify the offset from the target element coordinate as follows:
```c#
// Send mouse down, move, and up actions combination to perform a drag and drop 
// action on the app title bar. These actions reposition Calculator window.
session.Mouse.MouseMove(appNameTitle.Coordinates);
session.Mouse.MouseDown(null); // Pass null as this command omit the given parameter
session.Mouse.MouseMove(appNameTitle.Coordinates, offset, offset);
session.Mouse.MouseUp(null); // Pass null as this command omit the given parameter
```

Similar ad-hoc touch actions examples can also be found on the sample tests below:
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/TouchDownMoveUp.cs#L48
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/TouchDownMoveUp.cs#L75

You can use this different approach to make progress for the time being but let's work together to identify if there's an issue with using the `Actions` object as you initially intended.

**Comment by birarroshan** [comment]
session.getMouse() is Deprecated in Java. What is alternative?

**Comment by shoaibm-aurea** [comment]
Hi @birarroshan From python I am able to click in this way:

```
from selenium.webdriver import TouchActions
TouchActions(driver).tap_and_hold(x, y).release(x, y).perform()
```

**Comment by shoaibmansoor** [comment]
Hi @birarroshan From python I am able to click in this way:

```
from selenium.webdriver import TouchActions
TouchActions(driver).tap_and_hold(x, y).release(x, y).perform()
```

**Comment by ja185311** [comment]
If I run a coordinated clicking for WinAppDriver, with a Jenkins Job and unattended.. I see test failing!
Anyone encountered this issue? Is there a workaround for unattended automation jobs especially with coordinate clicks??
