### ISSUE TITLE
java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebElement cannot be cast to io.appium.java_client.MobileElement

### ISSUE THREAD

**Issue by aeroclee** [Microsoft/WinAppDriver#286]
Hello All,

I have ClassCastException issue like following error:
java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebElement cannot be cast to io.appium.java_client.MobileElement.

I could only refer an element by WebElement, but I am having ClassCastException issue using Mobile Reference.  I am trying to use an element by AutomationId (AccessibilityID).  I believe this is most stable way to locate an element in WinAppDriver.

Please correct me if there is something I miss or misunderstand?  Please let me know.
Thanks.

Here is pom.xml file info:
<appium.version>5.0.4</appium.version>
<selenium.version>3.6.0</selenium.version> 
<dependency>
	<groupId>io.appium</groupId>
	<artifactId>java-client</artifactId>
	<version>${appium.version}</version>
</dependency>
<dependency>
   <groupId>org.seleniumhq.selenium</groupId>
   <artifactId>selenium-java</artifactId>
   <version>${selenium.version}</version>
</dependency>

Here is how I define WinAppDriver:
protected static WindowsDriver<MobileElement> driver;
// Also tried with  protected static WindowsDriver<? extends MobileElement> driver;

caps.setCapability(MobileCapabilityType.APP, ConfigHelper.getInstance().app);	
this.driver = new WindowsDriver<>(getLocalAddressURL(), caps);	
return this.driver;

// OK with WebElement
WebElement title = driver.findElementByAccessibilityId("Title"); 

List<MobileElement> listAirportInfo = (List<MobileElement>)driver.findElementsByName("DataModel.Name");	
WebElement code = ((WebElement)listAirportInfo.get(0)).findElement(By.className("Block"));

**Case1: using findElementsByName**
// CastException when I execute on the bold line: MobileElement.
List<MobileElement> listsTypeNames = (List<MobileElement>) driver.findElementsByName("DataContextItem");
**String name = listsTypeNames.get(0).findElementByAccessibilityId("Selector_Text_Name").getText();**	

**Case2: using findElementsByClassName**
List<MobileElement> listsTypeNames = (List<MobileElement>) driver.findElementsByClassName("Item");
MobileElement chartTypeName = **((MobileElement)listsTypeNames.get(0)).findElementByAccessibilityId("Selector_Text_Name");
String name = chartTypeName.getText();**

**Comment by timotiusmargo** [comment]
Hi @aeroclee,

It looks familiar with the issue on [appium-dotnet-driver](https://github.com/appium/appium-dotnet-driver) (C# counter part) in which case the `findElementsByName` returns `RemoteWebElement` entries instead of `MobileElement` you expected.
https://github.com/Microsoft/WinAppDriver/issues/237

This issue however lies in the local end implementation in Appium Java client that you should file the issue with. In the meantime, will manually cast `listsChartTypeNames.get(0)` into `MobileElement` or `WindowsElement` work before you perform an element search?

**Comment by aeroclee** [comment]
Hello @timotiusmargo,

I tried with cast into MobileElement and WindowsElement, but still same issue.
Also, tried with findElementsByClassName and findElementsByName methods.
However, still same issue.    Issue is exactly same as #237.  

I modified the original post on coding section.  
I will also log issue at here: https://github.com/appium/java-client/issues.

Thanks.

**Comment by aeroclee** [comment]
Hi @timotiusmargo ,

I also tried with cast to WebElement and works well.
String name = ((WebElement)listsTypeNames.get(0)).findElement(By.className("Block")).getText();
print("Selector Name: "+name);

I guess the best way is to use xpath along with AccessibilityID.  However, I cannot find any good example with WindowsDriver using xpath with AccessibilityID.  any tips or example?  
Thanks.

**Comment by timotiusmargo** [comment]
Hi @aeroclee,

Thanks for sharing your progress and workaround. Below is a snippet taken from our sample test in https://github.com/Microsoft/WinAppDriver/blob/master/Tests/WebDriverAPI/Element.cs#L79:

```c#
WindowsElement alarmTab = session.FindElementByXPath("//Button[@AutomationId=\"MoreButton\"]");
```

Notice that `AccessibilityID` maps to `AutomationId` attribute in Windows UI tree as described in [list of supported locators](https://github.com/Microsoft/WinAppDriver/blob/master/README.md#supported-locators-to-find-ui-elements) in our [README.md](https://github.com/Microsoft/WinAppDriver/blob/master/README.md)

**Comment by hassanuz** [comment]
@aeroclee, this issue will be closed on this thread. Please open a new issue on the Java binding for Appium. https://github.com/appium/
