### ISSUE TITLE
Can't Get it to Open My App

### ISSUE THREAD

**Issue by MelbourneDeveloper** [Microsoft/WinAppDriver#288]
I have a Windows Store app. I opened the Calculator sample. I replaced the CalculatorAppId with the Package -> Identity -> Name from my Windows Store app, and when I run the test, it doesn't open the app. Where do I get my app id from?

**Comment by MelbourneDeveloper** [comment]
It turns out that the string it's looking for is this:

[Package -> Identity -> Name]-[Store ID]!App

**Comment by hassanuz** [comment]
Marking issue as closed due to being solved.
