### ISSUE TITLE
How does the element search and location is effected with the 1.0 release

### ISSUE THREAD

**Issue by gouthamsam** [Microsoft/WinAppDriver#289]
Scenario:  clicking an image in the complex screen.
Previously, WinApp Driver does a depth search.
After finding the size of the elements with ClassName :: Image. I can click on the image using the index value.

But right now it is not possible, WinAppDriver doesn't recognize/search for the elements of the child with the same ClassName. It is not doing a depth search.

Could you please explain this? 

**Optimize element search and application launch by using BreadthFirstSearch instead of DepthFirstSearch**

**Comment by timotiusmargo** [comment]
Hi @gouthamsam,

Breadth First Search was selected as it seems to be the fastest approach to locate an element in the tree based on many applications we encountered. While the ordering may have changed, you should still be able to locate any element within the application UI tree (possibly with a different search query though). If this is not the case, would you be able to provide a sample app where WinAppDriver fails to locate the elements?
