### ISSUE TITLE
Is that possible to run application with parameters using WinAppDriver?

### ISSUE THREAD

**Issue by GitHubTestUser5** [Microsoft/WinAppDriver#29]

**Comment by GitHubTestUser5** [comment]
@timotiusmargo, is that possible to run installer using WinAppDriver? Tried the following ways, but it doesn't work.

DesiredCapabilities appCapabilities = new DesiredCapabilities();
appCapabilities.SetCapability("app", @"C:\installer.msi");

and 

DesiredCapabilities appCapabilities = new DesiredCapabilities();
appCapabilities.SetCapability("app", @"C:\Windows\System32\msiexec.exe");
appCapabilities.SetCapability("args", @"/i C:\installer.msi");

**Comment by alakshmi1030** [comment]
Hello @GitHubTestUser5 , we are trying to understand the scenario you want to run. Can you please elaborate for us?

**Comment by GitHubTestUser5** [comment]
Hello @alakshmi1030, my goal is to run installer from MSI file and test its UI.

**Comment by timotiusmargo** [comment]
Since [v1.0-RC release](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.0-RC). Windows Application Driver can now launch an application with parameters. Below is an example of launching **Notepad** opening `MyTestFile.txt` in `C:\MyTestFolder\` working directory.

```c#
// Launch Notepad
DesiredCapabilities appCapabilities = new DesiredCapabilities();
appCapabilities.SetCapability("app", @"C:\Windows\System32\notepad.exe");
appCapabilities.SetCapability("appArguments", @"MyTestFile.txt");
appCapabilities.SetCapability("appWorkingDir", @"C:\MyTestFolder\");
WindowsDriver<WindowsElement> NotepadSession = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), appCapabilities);
```

Check out the [README.md](https://github.com/Microsoft/WinAppDriver/blob/v1.0-RC/README.md#supported-capabilities) for more information on other supported capabilities.

**Comment by dhapolapankaj** [comment]
Hey @timotiusmargo and @alakshmi1030 
Even if we are able to start the msi here, would WinAppDriver be able to overcome the Windows Smart screen filter, which blocks the entire screen and provide user with Yes/No pop up?

**Comment by timotiusmargo** [comment]
Hi @dhapolapankaj ,

I haven't personally tried it myself. But Windows Application Driver should be able to control (interact with) anything that is shown in the `inspect.exe`.

Presumably, this smart screen prompt is not part of the installer msi flow you are trying to validate. Hence, this smart screen filter can be avoided by configuring the test machine settings.

**Comment by dhapolapankaj** [comment]
Hi @timotiusmargo,
Disabling the smart screen filter on Test Machine actually make sense!

**Comment by dhapolapankaj** [comment]
Guyz Just an Update here. 
I was able to install MSI silently by evoking cmd.exe and addig below switch command
/c "misexec /i "path_to_msi.msi" /quiet /passive /l "path_to_LogFile.txt""

**Comment by kazztr** [comment]
Tank you very much for this
