### ISSUE TITLE
WinAppDriver for Windows 2016 Server

### ISSUE THREAD

**Issue by Clemensreijnen** [Microsoft/WinAppDriver#291]
I thought it would work to run test with the WinAppDriver  on a Windows 2016 server. 
But I get a 404.
any thoughts if it will work or is it really limited to win10?

**Comment by Clemensreijnen** [comment]
solved, got a 404 on the test run. The WindowsDriver and Appium where out of sync. Removed both of them, cleared the temp folder (it holds a download of the WindowsDriver.msi ) and run a fresh appium install. This downloads the proper and correct WindowsDriver. Happy testing on 2016 server ...

**Comment by naeemakram** [comment]
That means Windows Server 2016 is supported!!!! Great!!!

**Comment by suresh-halubai** [comment]
i am getting error on executing winappdriver.exe on Winodws 2016 server as below. any suggestions.

" The program can't start because VCRUNTIME140_1.dll is missing from your computer. Try re-installing program to fic the problem."
