### ISSUE TITLE
IWebElement.Clear() function is failing for Editbox in Firefox Authentication popup

### ISSUE THREAD

**Issue by dhapolapankaj** [Microsoft/WinAppDriver#293]
Hi,

The Clear() function is failing for the Editbox in Firefox Authentication popup

Please find below Code

`firefoxWindow = desktopSession.FindElementByXPath(".//Window[contains(@ClassName,'Mozilla') ]");`

`IWebElement SecurityPopupWindow = firefoxWindow.FindElement(By.XPath(".//Window[@Name='Authentication Required']")); `

`SecurityPopupWindow.FindElement(By.XPath(".//Custom/Edit[@Name='User Name:']")).Clear(); //This step is failing`

`SecurityPopupWindow.FindElement(By.XPath(".//Custom/Edit[@Name='User Name:']")).SendKeys("UserID");//To Enter User Id `

Please find below source

`<Window AcceleratorKey="" AccessKey="" AutomationId="" ClassName="MozillaWindowClass" FrameworkId="Win32" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="window" Name="Loading ... - Mozilla Firefox" Orientation="None" ProcessId="7896" RuntimeId="42.593266" x="1920" y="-87" width="1920" height="1040" CanMaximize="False" CanMinimize="False" IsModal="False" WindowVisualState="Maximized" WindowInteractionState="BlockedByModalWindow" IsTopmost="False" CanRotate="False" CanResize="False" CanMove="False" IsAvailable="True"> 
<Window AcceleratorKey="" AccessKey="" AutomationId="" ClassName="MozillaDialogClass" FrameworkId="Win32" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="window" Name="Authentication Required" Orientation="None" ProcessId="7896" RuntimeId="42.3280336" x="2670" y="341" width="420" height="177" CanMaximize="False" CanMinimize="False" IsModal="True" WindowVisualState="Normal" WindowInteractionState="ReadyForUserInteraction" IsTopmost="False" CanRotate="False" CanResize="False" CanMove="True" IsAvailable="True">
      <TitleBar AcceleratorKey="" AutomationId="TitleBar" ClassName="" FrameworkId="" HasKeyboardFocus="False" IsContentElement="False" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="title bar" Orientation="None" ProcessId="7896" RuntimeId="42.3280336.2.-2147483647.3280336.-2.0" x="2671" y="344" width="418" height="28">
        <Button AcceleratorKey="" AutomationId="Close" ClassName="" FrameworkId="" HasKeyboardFocus="False" IsContentElement="False" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="button" Name="Close" Orientation="None" ProcessId="7896" RuntimeId="42.3280336.2.-2147483647.3280336.-2.5" x="3056" y="342" width="34" height="30" />
      </TitleBar>
      <Menu AcceleratorKey="" AccessKey="" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="True" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="menu" Name="" Orientation="None" ProcessId="7896" RuntimeId="" x="0" y="0" width="0" height="0" />
      <Text AcceleratorKey="" AccessKey="" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="text" Name="http://10.80.1.30 is requesting your username and password." Orientation="None" ProcessId="7896" RuntimeId="" x="2757" y="390" width="317" height="17">
        <Edit AcceleratorKey="" AccessKey="" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="edit" Name="http://10.80.1.30 is requesting your username and password." Orientation="None" ProcessId="7896" RuntimeId="" x="2757" y="390" width="317" height="17" />
      </Text>
      <Text AcceleratorKey="" AccessKey="" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="text" Name="User Name:" Orientation="None" ProcessId="7896" RuntimeId="" x="2685" y="423" width="61" height="17">
        <Edit AcceleratorKey="" AccessKey="" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="edit" Name="User Name:" Orientation="None" ProcessId="7896" RuntimeId="" x="2685" y="423" width="61" height="17" />
      </Text>
      <Custom AcceleratorKey="" AccessKey="" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="" Name="User Name:" Orientation="None" ProcessId="7896" RuntimeId="" x="2755" y="421" width="320" height="22">
        <Edit AcceleratorKey="" AccessKey="" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="edit" Name="User Name:" Orientation="None" ProcessId="7896" RuntimeId="" x="2759" y="423" width="314" height="17" />
        <Menu AcceleratorKey="" AccessKey="" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="True" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="menu" Name="" Orientation="None" ProcessId="7896" RuntimeId="" x="0" y="0" width="0" height="0" />
      </Custom>
      <Text AcceleratorKey="" AccessKey="" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="text" Name="Password:" Orientation="None" ProcessId="7896" RuntimeId="" x="2685" y="449" width="61" height="17">
        <Edit AcceleratorKey="" AccessKey="" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="edit" Name="Password:" Orientation="None" ProcessId="7896" RuntimeId="" x="2685" y="449" width="61" height="17" />
      </Text>
      <Custom AcceleratorKey="" AccessKey="" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="" Name="Password:" Orientation="None" ProcessId="7896" RuntimeId="" x="2755" y="447" width="320" height="22">
        <Edit AcceleratorKey="" AccessKey="" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="False" IsPassword="True" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="edit" Name="Password:" Orientation="None" ProcessId="7896" RuntimeId="" x="2759" y="449" width="314" height="17" />
        <Menu AcceleratorKey="" AccessKey="" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="True" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="menu" Name="" Orientation="None" ProcessId="7896" RuntimeId="" x="0" y="0" width="0" height="0" />
      </Custom>
      <Button AcceleratorKey="" AccessKey="" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="button" Name="OK" Orientation="None" ProcessId="7896" RuntimeId="" x="2798" y="477" width="76" height="28" />
      <Button AcceleratorKey="" AccessKey="" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="button" Name="Cancel" Orientation="None" ProcessId="7896" RuntimeId="" x="2884" y="477" width="76" height="28" />
    </Window>`

Please find below stack trace
==========================================
POST /session/1F01F128-8B9B-4E3A-AD94-4CE961FAB1AB/element/08ed5699-3abc-430b-b11c-69e3c2130dfe/clear HTTP/1.1
Accept: application/json, image/png
Content-Length: 2
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{}
HTTP/1.1 500 Internal Error
Content-Length: 133
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
An unknown error occurred in the remote end while processing the command.
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Clear()
   at MyProject.Program.HandlePopUp(String browser, String executionmode, String uid, String pwd) in c:\Share\MyProject\Program.cs:line 193

**Comment by hassanuz** [comment]
Thanks @dhapolapankaj, we're tracking this internally. If you are able to reproduce this with the latest RC of 1.1, please let us know.

**Comment by hassanuz** [comment]
Thanks @dhapolapankaj, we're tracking this internally. If you are able to reproduce this with the latest RC of 1.1, please let us know.

**Comment by hassanuz** [comment]
Please reopen if this can be reproduced on [v1.1](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.1). Thanks.
