### ISSUE TITLE
Running WinAppDriver on a Selenium Grid

### ISSUE THREAD

**Issue by 1Arhangel** [Microsoft/WinAppDriver#294]
Hello,

I am trying to run Windows Tests using Selenium Grid to execute those tests on multiple environments. 

My setup goes like this:
1.Installed Appium using nodeJS npm install on my local machine and on the VM where I need to run the tests
2. Install and start Selenium Grid using nodeJS
3. Register an appium node to the grid using the instructions here: https://github.com/Microsoft/WinAppDriver/issues/122

I am sending my test commands on the selenium grid on http://127.0.0.0:4444/wd/hub/
And it is not working. The application is not starting and the hub is starting the chrome driver

Running tests on a remote environment as described here works without any problems. Do I need to instantiate RemoteWindowsDriver when running tests under a selenium grid ?

Is it possible to run Windows application tests using the selenium grid by registering an appium node to the grid ?

If it is possible, is there any detailed setup that I need to follow to make the correct environment for running multiple tests on remote environments ?

Any help will be greatly appreciated.

**Comment by yodurr** [comment]
Can you confirm the capabilities are this in the grid node config file?  If chrome driver is starting up it sounds like one of these capabilities isn't quite right.

  "capabilities":
	      [
	        {
	          "browserName": "",
	          "version":"",
	          "maxInstances": 3,
	          "platform":"WINDOWS"
	        }
	      ],

**Comment by 1Arhangel** [comment]
After further torture trying to execute tests remotely using Selenium Grid, Appium and Windows Application Driver without any proper environment setup documentation, I am attaching all the information including (console logs, errors, and windows node config file) that I think that is relevant and it can help solving this problem. 

My setup goes like this:

1. Installed Appium using Node.js on the remote machine where the test should run
2. Started a Selenium Server Standalone on my local machine
3. Successfully registered an Appium Node to the selenium server
4. Point the test address to be @ the selenium server standalone

Any advice, step by step guide, or proper environment setup would mean a great deal to me, as I am stuck on this issue for more than a month now with no real success in finding the problem or the solution.

Looking forward to your response and help solving this problem.  

[RelevantErrors.zip](https://github.com/Microsoft/WinAppDriver/files/1513955/RelevantErrors.zip)

**Comment by timotiusmargo** [comment]
Hi @1Arhangel,

Sorry to hear about your trouble. The most relevant error I see is the following that is generated by Appium instead of WinAppDriver:
`Error: Could not verify WinAppDriver install; re-run install`

I'm not sure how Appium install **WinAppDriver** behind the scene and which version it currently matches up. But the logic that triggers the error message above can be found below:
https://github.com/appium/appium-windows-driver/blob/v0.5.2/lib/installer.js#L43

I believe this code exists on your Appium installation and you have better information on what is not aligned.

**Comment by 1Arhangel** [comment]
Issue resolved. The problem was in the version of the Windows Application Driver that Appium installs when using Node.js to install Appium. I cannot know why Appium installs the 1.0 version of WinAppDriver, but when you try to execute the test, it looks for the 0.9 version and fails to run the test.

Issue resolved by:

1. Uninstalling the WinAppDriver via Node.js using:
<code>npm uninstall appium-windows-driver </code>

2. Installing a specific version of WinAppDriver (in this case 0.9 version) using:
<code> npm install appium-windows-driver@0.5.0 -g </code>

Note: The latest version of the WinAppDriver is 1.0 or 0.5.1  by the Appium nomenclature.

Thanks for the help @timotiusmargo 

Issue closed.
