### ISSUE TITLE
can winappdriver execute as a service in background ? 

### ISSUE THREAD

**Issue by Manvibha** [Microsoft/WinAppDriver#297]
Hi, 

I am trying to implement CI via VSTS and have an issue with launching winappdrive via build task using PS script task. WinAppDriver.exe executes a service in background rather interactive mode . Below are the approaches that I gave a shot but no with success
1. PS script to launch driver  
2. Batchscript to launch winappdriver on remote machine 
3.  Launch via PsExec.exe 

last option that i am trying is to launch driver via our automation script for each testmethod. This approach is in progress. 

Below are queries : 
Q1: can winappdriver execute as a service in background ? 

Q2: is there a way to launch the winappdriver via VSTS build task on remote machine? 

thanks,
Mahendra

**Comment by Manvibha** [comment]
waiting for response!!! since it is a road blocker for me.

**Comment by khouzam** [comment]
Hi @Manvibha,

WinAppDriver needs to run in an interactive session for it to be able to interact with the UI and send input. The current agent setup for VSTS supports running the agent as interactive and that does work with WinAppDriver.

You should consult the following docs for details and instructions: https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/v2-windows

**Comment by Manvibha** [comment]
Thanks a lot @khouzam. It solved my issue. 
problem was I had configured agent to run as a service. I reinstalled agent and configured to run as interactive mode. 

Thanks,
Mahendra

**Comment by khouzam** [comment]
Great to hear.

Sorry it took so long to resolve.
