### ISSUE TITLE
Selecting an item from context menu

### ISSUE THREAD

**Issue by eascqt** [Microsoft/WinAppDriver#298]
Hi,

I am using Appium on Windows 10. I am testing classical windows application built with .NET. I am trying to select item from context menu that appears after I right-click edit box (through Appium's java-client). My code and logs are below.

Before I tried Appium I have been experimenting with native Windows functions from User32.dll and I have noticed that once context menu appears I am unable to send click events nor key events to it although I can get the window handle for the menu. I found online that this may have something to do with privileges or "integrity" level of applications ("UIAccess") but so far I wasn't able to bypass that. I tried running in elevated mode and changing local security policies. 

Also, I was unable to use findElementByAccessibilityId("177") which should give me access to "Select All" item in system's context menu for text box, so I couldn't use that either (element not found exception).

Am I doing something wrong or is this an issue that needs to be addressed either in documentation or code fixes?

```
WebElement elem = driver.findElement(By.xpath("/Window/Edit[2]"));
Actions action = new Actions(driver);
action.contextClick(elem).sendKeys(Keys.ARROW_DOWN).sendKeys(Keys.ARROW_DOWN).sendKeys(Keys.ENTER).build().perform();
```
The action fails and the following is logged to the console (I have replaced machine name, app's full path etc. with ...):

```
Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: [object Object] (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: '...', ip: '...', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: io.appium.java_client.windows.WindowsDriver
Capabilities [{app=...\\WindowsFormsApp1.exe, javascriptEnabled=true, platformName=WINDOWS, deviceName=WindowsPC, platform=WINDOWS}]
Session ID: 0c29a348-7dbd-4404-af8b-9cab4525a6cc
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:82)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.execute(WindowsDriver.java:1)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
	at org.openqa.selenium.remote.RemoteKeyboard.sendKeys(RemoteKeyboard.java:38)
	at org.openqa.selenium.interactions.SendKeysAction.perform(SendKeysAction.java:53)
	at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:36)
	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:641)
...

```

The Appium server logs this:

```
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session/E5958A79-2AF5-4623-9CAE-2F352BF23BF3/keys HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 17
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4736
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] {"value":[""]}
[WinAppDriver] [STDOUT] HTTP/1.1 500 Internal Error
[WinAppDriver] [STDOUT] Content-Length: 133
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[MJSONWP] Encountered internal error running command:  {"jsonwp":{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}} ProxyRequestError: Could not proxy command to remote server. Original error: 500 - {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:152:13)
    at tryCatch (...\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (...\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (...\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (...\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/0c29a348-7dbd-4404-af8b-9cab4525a6cc/keys 500 9 ms - 186

```

**Comment by hassanuz** [comment]
Hi @eascqt, 
Can you please clarify which version of WinAppDriver you are using? 

Can you also confirm if element "177" or the context menu is a child of the main application window that is being targeted in the WinAppDriver session?

Thanks

**Comment by eascqt** [comment]
Hi @hassanuz,

Thank you for replying. 

The version of WinAppDriver is: 0.9.1705.5001 and it was installed with Appium server through npm.

System provided Context menu (like the one that you get when you right-click on system provided controls such as Edit box) are child windows of desktop unfortunately, and this may be causing the issues but I would expect the driver to somehow work around it or I would expect some documentation how to work around it on my own. In the scenario above, I am trying to right click Edit box and then select "Select All" from context menu (I found AutmoationId "177" by using Inspect.exe).

**Comment by timotiusmargo** [comment]
Hi @eascqt,

One way to access the **system context menu** is by using a [desktop session](https://github.com/Microsoft/WinAppDriver#creating-a-desktop-session). It supports accessing auxiliary UI elements outside of your application such as notification toast, system context menu, etc. In short you can create a desktop session alongside your application session, and use it to locate and interact with the context menu you see.

**Comment by eascqt** [comment]
Hi @timotiusmargo,

The code you pointed to doesn't seem valid. Assuming that DesktopSession is a class, it doesn't seem to be available in Appium java client and WindowsDriver doesn't have Keyboard member. Would this code in Java match what you are referring to:

```
        DesiredCapabilities appCapabilities = new DesiredCapabilities();
        appCapabilities.setCapability("platformName", "Windows");
        appCapabilities.setCapability("deviceName", "WindowsPC");
        appCapabilities.setCapability("app", "Root");
        WindowsDriver ds = new WindowsDriver(new URL("http://127.0.0.1:4723/wd/hub"), appCapabilities);

        // Use the session to control the desktop
        Actions action3 = new Actions(ds);
        action2.sendKeys(Keys.ARROW_DOWN).sendKeys(Keys.ARROW_DOWN).build().perform();

```

I put this code after the code that invokes context menu (by simulating right click on edit box). The problem is still the same - an unknown exception is thrown at the last line of code, when the driver is instructed to insert key event.

**Comment by timotiusmargo** [comment]
Hi @eascqt,

The `DesktopSession` in the sample code is the name of the `WindowsDriver` instance. In your code above, `ds` reflects this `DesktopSession` instance. With this instance you should be able to locate the element with `AutomationId` 177 as you have been requested.

I'm not entirely sure what JSON Wire protocol HTTP requests generated from the `actions3` in your code. Is the following snippet (taken from your message above) the only request sent through that command?

```
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session/E5958A79-2AF5-4623-9CAE-2F352BF23BF3/keys HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 17
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4736
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT]
[WinAppDriver] [STDOUT] {"value":[""]}
[WinAppDriver] [STDOUT] HTTP/1.1 500 Internal Error
[WinAppDriver] [STDOUT] Content-Length: 133
[WinAppDriver] [STDOUT] Content-Type: application/json
```

**Comment by eascqt** [comment]
Hi @timotiusmargo 

After your suggestion I have modified the code to look like this:

```
        DesiredCapabilities appCapabilities = new DesiredCapabilities();
        appCapabilities.setCapability("platformName", "Windows");
        appCapabilities.setCapability("deviceName", "WindowsPC");
        appCapabilities.setCapability("app", "Root");
        WindowsDriver ds = new WindowsDriver(new URL("http://127.0.0.1:4723/wd/hub"), appCapabilities);
        ds.findElementByAccessibilityId("177").click();

```

That did the trick! "Select All" from context menu was clicked. Thank you very much for helping out.

To answer your question, the log above is generated when I attempted to insert key events (ARROW_DOWN) with original code that is on the top of this thread. The idea was to show context menu and then move highlight to the next item in the menu by simulating arrow keys.

Anyways, I have all I need now to write my test. Thank you for  support!

**Comment by hassanuz** [comment]
Thanks for reporting back. Closing ticket.
