### ISSUE TITLE
Does WinAppDriver support JS to operate the scroll-bar?

### ISSUE THREAD

**Issue by questions555** [Microsoft/WinAppDriver#299]
Hello, Team
   There is a feature of UWP to be tested with AppWinDriver, but this element is the bottom of the page, which need to be displayed by scrolling the bar, then I want to scroll bar with JS in my code, like this:
( (IJavascriptExecutor)driver).ExecuteScript("argument[0].ScrollIntoViewIfNeeded(true)",operatingElement);
  It seems it doesn't work. Pls help me to solve this problem,or provide some other solutions.

**Comment by hassanuz** [comment]
Hi @questions555,

Do you know if the element already exists on the display, or is it generated after you scroll down?

The [Alarm Clock Test](https://github.com/Microsoft/WinAppDriver/tree/v1.0/Samples/C%23/AlarmClockTest) serves as a good reference for this, and demonstrates two possible scenarios for handling elements in a list.  

### Scenario 1 - element pre-generated
As per the [spec](www.w3.org/TR/webdriver/#element-click), we implicitly scroll elements within the view when they are selected--however this relies on the UI element being generated and accessible from the start. 

The [Alarm Scenario](https://github.com/Microsoft/WinAppDriver/blob/v1.0/Samples/C%23/AlarmClockTest/ScenarioAlarm.cs) test serves as a good reference for this. From the code snippet [here](https://github.com/Microsoft/WinAppDriver/blob/8bb91f06ef9cbc798c88099a586c15d74fd17870/Samples/C%23/AlarmClockTest/ScenarioAlarm.cs#L46
):
 `minuteSelector.FindElementByName("55").Click();`, the AlarmClock test automatically scrolls to the **'55'** element and selects it - as can be seen when the alarm GUI is set to **3:55** when the test is running. 

### Scenario 2 - element dynamically generated
There exists the possibility of cases where the element UI is not generated until certain conditions are met (e.g. a list has to scroll to it's location first before element is generated). This will require automating in the steps to fulfill those requirements first before the element can be interacted with. 

The [Stopwatch Scenario](https://github.com/Microsoft/WinAppDriver/blob/v1.0/Samples/C%23/AlarmClockTest/ScenarioStopwatch.cs) serves as a good example for handling dynamically generated elements. From the code snippet [here](https://github.com/Microsoft/WinAppDriver/blob/8bb91f06ef9cbc798c88099a586c15d74fd17870/Samples/C%23/AlarmClockTest/ScenarioStopwatch.cs#L63),
`touchScreen.Scroll(lapListView.Coordinates, 0, -50);`, test sscrolls to the location of the element before taking action on the desired element. 

Please let us know if this helps clarify your question, or if can provide us with any additional details if it does not. 

Thanks

**Comment by naddison** [comment]
Hi, not to hijack this question, but are there examples of this scroll action in java? Unfortunately the Coordinates are not an accessible property when using WebElement class in Selenium.

**Comment by hassanuz** [comment]
We're happy to take contributions from the community towards improving our samples (especially when it comes to popular languages like Java or Python). Feel free to submit a PR if anyone has any regarding this.
