### ISSUE TITLE
Does WinAppDriver Support Launching and Attaching to AppV Applications?

### ISSUE THREAD

**Issue by joetouhey** [Microsoft/WinAppDriver#300]
We have a scenario where we have an AppV package of Internet Explorer, Firefox and Google Chrome. The shortcut link that we use to launch IE for example is iexplore.exe"  /appvve: {Application Package ID}. Does WinAppDriver support launching IE in this manner or attaching to the already existing IE process that is created by iexplore.exe"  /appvve: {Application Package ID}?

Thank you.

**Comment by hassanuz** [comment]
Hi @joetouhey,

Can you try running the inspect tool and report back what you find? 

Thanks

**Comment by joetouhey** [comment]
Hi @hassanuz, 

When I run spy on the AppV version of IE11 that I launched from the shortcut I see a Window caption of Google - (AppV v11.03). I navigated to http://www.google.com. I also see a number of windows beneath the main window of different classes.
Thank you,

**Comment by joetouhey** [comment]
Hi @hassanuz,
I still have not received an answer to my question.
Thank you.

**Comment by hassanuz** [comment]
Hi @joetouhey,

If the elements are picked up using Inspect, then WinAppDriver will be able to automate against it. If the IE session is already created, you can use a [desktop session ](https://github.com/Microsoft/WinAppDriver/wiki/Frequently-Asked-Questions/289a8b325d3ddab9f08b4398c49163a9a136f607#when-and-how-to-create-a-desktop-session)of WinAppDriver to attach to it. 

Apologies for not getting back to you earlier. If you were able to get this working, this would be good to know.

Thanks
