### ISSUE TITLE
how to use appium to control UAC(user account control)

### ISSUE THREAD

**Issue by cookyzhang** [Microsoft/WinAppDriver#306]
Can someone help me to solve this problem?
One button of my App will call up UAC. 
And I don't know how to control this?
I want to click YES. Then my APP will go on running the following test steps.

Thanks.
![uac](https://user-images.githubusercontent.com/33859393/33061553-62a1c8ca-ce51-11e7-93fc-6fda2eda8464.jpg)

**Comment by hassanuz** [comment]
Hi @cookyzhang ,

This is by design. As a work around, you can try turning off UAC, or by running your application as an administrator. 

Thanks

**Comment by cookyzhang** [comment]
hi @hassanuz 
Thank you for your help.
After I click YES on the UAC, the code will continue to run.
But it's inconvenient  that I have to click the UAC manually during the auto running.
For example, if I want to run the code on 100 machines, first I have to wait to see which machine will pop up the UAC, then I need to click the UAC. It will take a long time for me to finish 100 machines.

**Comment by prasanna532** [comment]
I am also having the same issue.

**Comment by PandaMagnus** [comment]
There's a registry setting you can programmatically set to turn off UAC if you don't have the option to run the program as an admin. This is a huge security risk, so only do it if you absolutely cannot run the application as an admin.

https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-lua-settings-enablelua
