### ISSUE TITLE
WinAppDriver makes snapshot of desktop instead of specific application.

### ISSUE THREAD

**Issue by denys-rwd** [Microsoft/WinAppDriver#31]
Hi,

WinAppDriver makes snapshot of whole desktop.
I expect to get snapshot of application under testing only, like what selenium makes.

![main](https://cloud.githubusercontent.com/assets/18639833/15858506/805c6b2a-2cc9-11e6-8fcc-6e605a08a7dc.png)

Thanks in advance,
Denys

**Comment by alakshmi1030** [comment]
This behavior should be modified as of the v0.4 release: https://github.com/Microsoft/WinAppDriver/releases/tag/v0.4-beta
