### ISSUE TITLE
Inspecting UI Elements  

### ISSUE THREAD

**Issue by lixiaoyudakeke** [Microsoft/WinAppDriver#311]
The project of our company is written in  nw.js, So I can't use inspect to locate elements,If anyone has a good method, I hope you can give advice,I would be most grateful if someone answered

**Comment by hassanuz** [comment]
Hi @lixiaoyudakeke , thanks for reaching out. Unfortunately we currently only support UIA compliant applications that show you the elements via inspect.exe.

**Comment by hassanuz** [comment]
Marking issue as closed due to no additional comments.
