### ISSUE TITLE
Does the latest winappdriver version support wpf apps?

### ISSUE THREAD

**Issue by viji-123** [Microsoft/WinAppDriver#314]

**Comment by AmirHNK** [comment]
I tested V1.0 release on a basic WPF application and I was able to successfully interact with buttons and textboxes.

**Comment by viji-123** [comment]
Thanks for the reply. 
I am also using WPF application. But its not working for me. Its not able to locate any of the elements.
It fails with the exception " NoSuchElementException: An element could not be located on the page using the given search parameters. "
Dont know whats wrong

**Comment by AmirHNK** [comment]
Can you read the controls info using inspect.exe? 
I you have custom controls, the automation client won't be able to see the controls unless you make certain changes to the code. For start, please check this [link](https://www.codeproject.com/Articles/172391/UIAutomation-Coded-UI-Tests-AutomationPeer-and-WPF.aspx?msg=3871872).

**Comment by timotiusmargo** [comment]
Hi @viji-123,

One way to verify that your element is indeed in your application session is by using the `PageSource` session attribute. This page source is an XML representation of your application and should reflect what you see in the `inspect.exe` tool. An example command in C# to get the page source can be found in https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/Source.cs#L41

**Comment by viji-123** [comment]
Hi @timotiusmargo 
Thanks for your input. I tried the code that you suggested. Its throwing a WebDriver exception when it hits the line  - " var source = session.PageSource"

**Comment by viji-123** [comment]
The stack trace is below 

   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.get_PageSource()

**Comment by PandaMagnus** [comment]
@viji-123 Is there more to the stack trace than that?

**Comment by viji-123** [comment]
![image](https://user-images.githubusercontent.com/22593499/33493544-65275f52-d68e-11e7-86fd-29415ce49aba.png)

Apart from stack trace , the above screenshot might give you some information. These are the details I have. Please Let me know if you need any other info

**Comment by PandaMagnus** [comment]
Do you mind linking your code surrounding how you're declaring your session, particularly around WinAppDriverUrl and your DesiredCapabilities?

**Comment by viji-123** [comment]
Please find below:


        protected const string AppDriverUrl = "http://127.0.0.1:4723";
        protected const string WpfNotepadAppId = @"C:\Location\App.exe";
        protected const string ExplorerAppId = @"AppName.exe";
        protected const string TargetSaveLocation = @"%TEMP%\";
        protected static WindowsDriver<WindowsElement> WpfnotepadSession;

        public static void Setup()
        {
                DesiredCapabilities appCapabilities = new DesiredCapabilities();
                appCapabilities.SetCapability("app", WpfNotepadAppId);
                WpfnotepadSession = new WindowsDriver<WindowsElement>(new Uri(AppDriverUrl), appCapabilities);
                System.Threading.Thread.Sleep(2000);
                Assert.IsNotNull(WpfnotepadSession);
             }

**Comment by PandaMagnus** [comment]
Right after the Assert, can you try adding the pagesource call:

`var source = WpfnotepadSession.PageSource;`

to see if it is successful before it drops out of Setup()?

**Comment by viji-123** [comment]
Yes. I did that. It failed with the exception.

**Comment by PandaMagnus** [comment]
Gotcha, thanks. When I get home I'll see if I can replicate the issue on my computer.

**Comment by timotiusmargo** [comment]
Hi @viji-123,

Alongside with @PandaMagnus suggestion, would you additionally get the `WindowHandle` and `PageSource` **immediately** after creating `WpfNotepadSession` (before sleeping for 2 seconds)?

After the 2 seconds sleep, can you then retrieve the `WindowHandles` (plural) attribute to see if the current active windows belonging to the application session are still the same window with the one you initially had.

I suspect that the session could have been capturing a splashscreen/other auxiliary window that is no longer up after the 2 seconds sleep. The steps above should show if this is the case. Sample commands to get the `WindowHandle` and `WindowHandles` attributes can be found below:

https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/Window.cs#L74
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/Window.cs#L98

**Comment by viji-123** [comment]
Hi @timotiusmargo 

Thanks for your suggestions. The reason I was getting the exception was because my application has a splashscreen, it was holding that window i guess. So I disabled the splash screen , now its able to locate the element.
Thanks everyone for helping out

**Comment by hassanuz** [comment]
Closing per @viji-123 's last comment.
