### ISSUE TITLE
WPF Combobox Selection

### ISSUE THREAD

**Issue by todoubled711** [Microsoft/WinAppDriver#318]
Hi,

My team at work has been using CodedUI for the past couple of years. Although, we have had some concerns and issues with the framework here and there. After contacting Microsoft with these they suggested us to look into Appium with the WinDriver as CodedUI is a legacy framework they don't really support anymore. We have liked Appium thus far but are running into issues with WPF Comboboxes. I have two questions about it I was hoping someone code assist with.

1- While trying to use the Click() method to select the WPF Combobox it works but selects the center of the ComboBox. In our case, the right side of the Combobox needs to be selected in order for it to drop-down with values. In CodedUI we didn't have this issue, but in areas of our application that we had similar issues we could pass in a new Point() with X, Y coordinates. I saw Appium has a Tap() method but with the WinDriver it only supports Finger and Duration. Is there any workaround for this?

2-  In CodedUI if we weren't concerned with the value being selected in the ComboBox and just needed something selected in order to complete an end-to-end test we could define the ComboBox. Once it has been defined we could call it and say get count or selected index then pick a random one from the ComboBox. Are we able to do something similar with Appium using the WinDriver? Here are some examples below:

**Example 1:**
 public void SelectItemFromConversationTypeComboBox()
        {
            var selectItemInConversationComboBox = GetConversationTypeComboBox();
            selectItemInConversationComboBox.SelectedIndex = selectItemInConversationComboBox.SelectedIndex.Equals(selectItemInConversationComboBox.SelectedIndex) ? RandomUtil.GetRandomNumber(1, selectItemInConversationComboBox.Items.Count) : selectItemInConversationComboBox.SelectedIndex;
            LoggerUtil.Log("Setting Conversation Type to " + "'" + selectItemInConversationComboBox.SelectedItem + "'");
        }

**Example 2:**
    public void TestEditClientPrefixComboboxValues()
        {
            ClientMainView.GetHeaderInformationBar().ClickEditClientInformationButton();
            var prefixCount =
                ClientMainView.GetHeaderInformationBar()
                    .GetEditClientWindow()
                    .GetEditClientGeneralInformationView()
                    .GetEditClientPrefixComboBox().Items.Count;
            for (var i = 0; i < prefixCount; i++)
            { 
                ClientMainView.GetHeaderInformationBar().GetEditClientWindow().GetWindow();
                ClientMainView.GetHeaderInformationBar().GetEditClientWindow().GetEditClientGeneralInformationView().GetEditClientPrefixComboBox().SelectedIndex = i;
                var prefixName =
                    ClientMainView.GetHeaderInformationBar()
                        .GetEditClientWindow()
                        .GetEditClientGeneralInformationView()
                        .GetEditClientPrefixComboBox()
                        .SelectedItem;
                LoggerUtil.Log("Selected Prefix " + "'" + prefixName + "'");
                ClientMainView.GetHeaderInformationBar().GetEditClientWindow().ClickOkButton();
                ClientMainView.GetHeaderInformationBar().ClickEditClientInformationButton();
                ClientMainView.GetHeaderInformationBar().GetEditClientWindow().GetWindow();
                Assert.AreEqual(prefixName, ClientMainView.GetHeaderInformationBar().GetEditClientWindow().GetEditClientGeneralInformationView().GetEditClientPrefixComboBox().SelectedItem);
            }
        }

Thanks,
Todd

**Comment by timotiusmargo** [comment]
Hi @todoubled711,

1. Often times a drop down **ComboBox** has a child element such as a button with down arrow indicator to expand the drop down selections. In such case, you should click that child element instead of the combo box element. However if your combo box has no specific element you can target, you can always click at an element with some given x, and y offset. E.g.

```c#
WindowsElement conversationTypeComboBox = session.FindElementByAccessibilityId("conversationType");
session.Mouse.MouseMove(conversationTypeComboBox .Coordinates, offset, offset);
```
Some more examples of ad-hoc/arbitrary mouse and touch actions can be found on the following samples:
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/Mouse.cs
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/TouchDownMoveUp.cs

2. You can absolutely port the given logic above into a WebDriver test script and perform the same test using Windows Application Driver. More example on how to [set](https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/UWPControls/ComboBox.cs#L48) and [get](https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/UWPControls/ComboBox.cs#L119) value from a **ComboBox** element can be found on the following sample:
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/UWPControls/ComboBox.cs

**Comment by todoubled711** [comment]
Hi @timotiusmargo ,

Thanks for the feedback. I used your logic above and was halfway successful. It did allow me to pass in X,Y coordinates but the MouseMOve() method doesn't actually select or click anything :-(. That being said it did move exactly where I wanted it too but all it did was hover over the control. I tried adding .Click() to the end and it wouldn't accept it.

For your second comment, I didn't see any examples of a selectedIndex or selectedItem such as written logic "selectItemInConversationComboBox.SelectedIndex". When I try I receive an error WindowsElement does not contain a definition for SelectedIndex.

Best regards.
Todd

**Comment by timotiusmargo** [comment]
Hi @todoubled711,

Yes I meant to point you to the [Mouse example](https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/Mouse.cs#L55) linked above where you can see the other `Mouse` actions you can do including click. Following the given example, you can add the mouse click after moving the pointer to the right position as follows:

```c#
WindowsElement conversationTypeComboBox = session.FindElementByAccessibilityId("conversationType");
session.Mouse.MouseMove(conversationTypeComboBox .Coordinates, offset, offset);
session.Mouse.Click(null);
```

**Windows Application Driver** and other WebDriver protocol compliant clients typically expose much simpler and general interface for any UI element. In this **ComboBox** case, the typical interface would be to [get](https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/UWPControls/ComboBox.cs#L119) and [set](https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/UWPControls/ComboBox.cs#L48) the item. If you follow and run the given example, you will see that the `Text` attribute gets the selected item and `Click()` action selects the item in the **ComboBox**. This interface simply reflect what a user would do when interacting with the UI element.
