### ISSUE TITLE
Microsoft/WinAppDriver: Appium cannot proxy command to the remote server

### ISSUE THREAD

**Issue by pmswatuser** [Microsoft/WinAppDriver#323]
**The problem**
Launching Windows Calculator on Windows 10 using Appium. Appium logs indicate An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server.

**Environment**
Appium version (or git revision) that exhibits the issue: 1.7.1
Desktop OS/version used to run Appium: Windows 10
Node version: 9.2
WinAppDriver: 0.9 beta as there are issues with v1.0

**Capabilities used**:
		dc.setCapability("platformName","Windows");
		dc.setCapability("deviceName","WindowsPC");
		dc.setCapability("app", "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App");
                RemoteWebDriver Calculatorsession = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub/"), dc);

**Appium logs**:

[Appium] Welcome to Appium v1.7.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{}},"alwaysMatch":{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","platformName":"Windows","deviceName":"WindowsPC"},"firstMatch":[]}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","platformName":"Windows","deviceName":"WindowsPC"},{},{"desiredCapabilities":{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{}}]
[BaseDriver] Event 'newSessionRequested' logged at 1512574995019 (09:43:15 GMT-0600 (Central Standard Time))
[Appium] Creating new WindowsDriver (v0.5.0) session
[Appium] Capabilities:
[Appium]   app: 'Microsoft.WindowsCalculator_8wekyb3d8bbwe!App'
[Appium]   platformName: 'Windows'
[Appium]   deviceName: 'WindowsPC'
[BaseDriver] The following capabilities were provided, but are not recognized by appium: app.
[BaseDriver] Session created with session id: e162a24d-c591-4a6f-b807-577655bc92dd
[WinAppDriver] Verifying WinAppDriver is installed with correct checksum
[WinAppDriver] WinAppDriver changed state to 'starting'
[WinAppDriver] Killing any old WinAppDrivers on same port, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"4724 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I winappdriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
[WinAppDriver] No old WinAppDrivers seemed to exist
[WinAppDriver] Spawning winappdriver with: undefined 4724/wd/hub
[WinAppDriver] [STDOUT] Windows Application Driver Beta listening for requests at: http://127.0.0.1:4724/wd/hub
[WinAppDriver] WinAppDriver changed state to 'online'
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:4724/wd/hub/session] with body: {"desiredCapabilities":{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","platformName":"Windows","deviceName":"WindowsPC"}}
[WinAppDriver] [STDOUT] Press ENTER to exit.
[WinAppDriver] Deleting WinAppDriver session
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: 500 - undefined
    at JWProxy.proxy$ (C:\Users\a149760\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:152:13)
    at tryCatch (C:\Users\a149760\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\a149760\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\a149760\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\a149760\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 625 ms - 210

**Comment by pmswatuser** [comment]
Update: Tried with "App" capability instead of "app". Did not help. Presents a different error. 

[BaseDriver] The following capabilities were provided, but are not recognized by appium: App.
[MJSONWP] Encountered internal error running command: Error: Option 'app' is required!

Any insight will be appreciated.

**Comment by yodurr** [comment]
If you run WinAppDriver without using Appium do you get the same error?

**Comment by pmswatuser** [comment]
Manually starting WAD (as opposed to Appium starting it) works on any port. See screenshot attached. 

From the Appium logs above, Appium seems to be starting WAD on port 4724, starts successfully, but unable to proxy the json request to WAD. WAD process is not running before the Appium test starts for it to have a session already open. 

![wad](https://user-images.githubusercontent.com/32580432/33838866-4a40e4c2-de56-11e7-962a-335f9dbade65.jpg)

**Comment by pmswatuser** [comment]
Below logs are from Appium's run. I think the issue is with Appium being able to proxy to WAD. Not sure if Jlipps/Appium team have any more thoughts?

![wad2](https://user-images.githubusercontent.com/32580432/33839206-3cc5dfea-de57-11e7-9f63-d5e94a245bb1.jpg)

**Comment by yodurr** [comment]
Yes, we need to dig into the Appium modules for what's going wrong so let's track the bug on the Appium forum going forward.  Thanks!
