### ISSUE TITLE
How to Interact with a Specific Element When Others with Same Name Exist on Other Windows

### ISSUE THREAD

**Issue by AmirHNK** [Microsoft/WinAppDriver#324]
What is the best way to interact with a UI element where another one with the same name on a different window is available?

For example,I have the "File Explorer" and "ApplicationX" windows open. They both have a close (X) button. I want to make sure that I close "File Explorer" and not close any other window or click on any other element available on the Desktop.

Is there an XPath type script that can do the job?

The reason I want to interact with "Close" button on a window is because I cannot close a window which was opened by a session. Quit(), CloseApp() don't do the job.

As a side question, do I need to start the Driver on my test machine manually every time before a test run? This is what I am doing on my VM before I run my tests and when the Driver crashes or quits for what ever reason, the tests session will close and I would have to start the driver manually before I run my tests again.

**Comment by timotiusmargo** [comment]
Hi @AmirHNK,

Both [XPath](https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/Element.cs#L240) and [FindNestedElement](https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/ElementElement.cs) will help you scoping your element search.

In terms of best practice, I would highly suggest to have one session per app and limit your usage of desktop session unless it becomes necessary. So for your example, you would have 1 `FileExplorerSession`, 1 `ApplicationXSession`, and 1 `DesktopSession`. Locating the **Close** button within `FileExplorerSession` and `ApplicationXSession` will then no longer be ambiguous.

Can you share the `WinAppDriver.exe` console log when you attempt to close the window using `session.Close()', `session.Quit()`, or `session.CloseApp()`? In multiple windows application, the following sample test demonstrate how to enumerate the windows, switching between them, and close them.
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/Window.cs#L155

For the time being, the Driver on your test machine has to be manually started once until it is terminated as you mentioned. But once started, you can run as many tests as needed without the need of restarting the Driver.

**Comment by AmirHNK** [comment]
Hi @timotiusmargo,

Thanks for the info! They are very helpful.

I will post the session logs as soon as I can. I am just a bit occupied at the moment.

Is there a good tutorial where I can learn how to use XPath for Windows application testing?  All I am able to find are Web related stuff. I really need to know how to use the information I get from inspect.exe to create a desired XPath.

**Comment by hassanuz** [comment]
Hi @AmirHNK,

We recommend taking a look at [UI Recorder](https://github.com/Microsoft/WinAppDriver/releases/tag/UiR_v1.0-RC) to generate XPath queries and using the [UI Recorder Template](https://github.com/Microsoft/WinAppDriver/tree/master/Tools/UIRecorder/UIRecorderTemplate) to play around with the generated queries. Note that the Template uses a Desktop Session, so you may have to truncate the initial part of the XPath if you're using a custom session.
