### ISSUE TITLE
Not able to run tests for App built in VS Release (Native + Optimize Toolset) mode 

### ISSUE THREAD

**Issue by jeromesadler** [Microsoft/WinAppDriver#325]
Hi, I am able to run WinAppDriver tests with my Xamarin.Forms UWP app when I deploy my app in Debug mode in Visual Studio 2017, and then run the UITest project in debug mode with a "Debug / Debug All" command. When I deploy my app in Release mode (.Net Native tool chain + Optimize Code ticked - i.e. the configuration I use for the production app) the test session fails to start with the message {"status":13,"value":{"error":"unknown error","message":"Failed to locate opened application window with appId: myAppId, and processId: xxxx"}}. It all works great in Debug (the app starts, and the tests run correctly), but it's important that the tests work with the Release mode deployment. Does WinAppDriver support .Net Native apps, and what could I be doing wrong?

**Comment by hassanuz** [comment]
Hi @jeromesadler,
Let us try this scenario, as this is something we have not looked at explicitly before. Will report within a week.

**Comment by hassanuz** [comment]
@jeromesadler,

For our sample Xamarin.Forums project, we were able to deploy our .Net Native tool chain app in release mode and able to launch it with WinAppDriver. 

Can you try a barebones sample Xamarin.Forums project and see if WinAppDriver is able to launch that app?

**Comment by hassanuz** [comment]
Marking issue as closed due to no additional comments.
