### ISSUE TITLE
WinAppDriver is unable to work with windows opened other than main application window

### ISSUE THREAD

**Issue by Pranodayd** [Microsoft/WinAppDriver#327]
Hello guys.
My application opens different windows on clicking some button controls.Now  WAD is able to work on application window which opens up after starting my application's .exe file but as soon as I click on button control to open another window of same application,WAD is not able to identify that window.This happens even when any Warning/Error alert gets opened up.

Why WAD is not able to identify newly opened application window/alert window though these windows opens up in same process's hierarchy path of which I have specified in app desired capability.
My process ID remains same even after opening these windows.

Can you guys help me out in resolving this?

Thanks and regards,
Pranoday

**Comment by timotiusmargo** [comment]
Hi @Pranodayd,

You can enumerate all top level windows belonging to an active Windows Application Driver **session** through the `WindowHandles` attribute as shown in the example below:
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/Window.cs#L120

Once you enumerate them, you can **switch** the **active session** to any of it and interact with one of them at a time.

If you don't see the newly opened window you mentioned above in the enumerated top level windows, it may not have the same process id with your active session. The best way to verify this is to use [`inspect tool`](https://github.com/Microsoft/WinAppDriver/tree/v1.0#inspecting-ui-elements) to identify the **process id** of the **current active window** and the **newly created ones**. You can also dump the page source of the currently active window through the session `PageSource` attribute as shown in the example below:
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/Source.cs#L39

**Comment by dhapolapankaj** [comment]
Another way is to take the desktop session object and find your target windows, but this is time consuming!

**Comment by hassanuz** [comment]
Closing as @Pranodayd 's issue appears to be resolved. Let us know if you are still facing issues.

**Comment by gclouds** [comment]
> Another way is to take the desktop session object and find your target windows, but this is time consuming!

how we can get the desktop session? thanks in advance

**Comment by samkhayal** [comment]
how we can get the desktop session?

**Comment by timotiusmargo** [comment]
Hi @gclouds and @samkhayal,

Please find the information on how to get the desktop session below:
https://github.com/microsoft/WinAppDriver/wiki/Frequently-Asked-Questions/a8c02cfac47b4bf0c12c571b6010c403dcfe5e7f#when-and-how-to-create-a-desktop-session

```
DesiredCapabilities appCapabilities = new DesiredCapabilities();
appCapabilities.SetCapability("app", "Root");
DesktopSession = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), appCapabilities);
```

Feel free to provide a feedback/issue on how we can make the information organized better.

**Comment by JGjumpshot** [comment]
Can you use Window Handles to navigate from a desktop app to an internet explorer window after clicking a link in the desktop app?

**Comment by bangalokesh** [comment]
> desktop session object and find your target windows
Hello Pankaj -- Can you explain how can i find the target window using desktop session object. My application after login closes and opens a new window. In appium i can see replacing session id...

**Comment by jstTester** [comment]
Just reached same problem, it was bloody appium server that I moved to other desktop that was main issue. Took my 2 hours to figure it out why it stopped working suddenly. I guess it's time to start using WindowsHandles..

**Comment by samkhayal** [comment]
thank you
