### ISSUE TITLE
Support for UWP C++/CX Apps

### ISSUE THREAD

**Issue by strentler** [Microsoft/WinAppDriver#328]
Hi,

are there any plans to support testing UWP C++/CX apps?

**Comment by higarry** [comment]
It supports testing UWP C++/CX apps. And I don't think it should have relations with the languages, C++/CX, C#, etc.

**Comment by timotiusmargo** [comment]
Hi @strentler,

Yes as @higarry mentioned, Windows Application Driver fully supports **UWP apps** written in any languages.

**Comment by hassanuz** [comment]
Closing issue as question is answered.
