### ISSUE TITLE
Does WinAppDriver support waiting for an element visible on UWP? 

### ISSUE THREAD

**Issue by higarry** [Microsoft/WinAppDriver#329]
Recently, I am using Appium+WinAppDriver to do UI testing for my UWP applications, but I encountered an issue: 
I am not able to know when does my APP has done some UI changes, I failed to find some functions like WebDiverWait which is used on WebDriver. So there are some functions like WinDriverWait ? Or do some one has a good way to do this to wait for some element become visible?
Thanks

**Comment by higarry** [comment]
Any update?

**Comment by higarry** [comment]
hi @timotiusmargo,

Yes, explicit wait is what I mean.
I installed Appium package on my desktop, and added the following namespace line: 
using OpenQA.Selenium.Appium; 
Like you mentioned, WinAppDriver already supported this, could you please specify the functions? or are there are samples ?

Thanks!

**Comment by timotiusmargo** [comment]
Hi @higarry,

Sorry for not being completely clear. Selenium [explicit wait](http://www.seleniumhq.org/docs/04_webdriver_advanced.jsp#explicit-waits) requires the client code like [appium-dotnet-driver](https://github.com/appium/appium-dotnet-driver) to implement it for you. If your test script is written in C#, you would very likely use appium-dotnet-driver to translate your script to JSON Wire Protocol commands that Windows Application Driver understand. Last time I checked, appium-dotnet-driver is missing support for the explicit wait we talked about. Hence, you should bring this issue up in their GitHub repository. Once it is implemented on appium-dotnet-driver, it will work with Windows Application Driver without any changes needed on our side.

**Comment by hassanuz** [comment]
Marking issue as closed due to no additional comments.

**Comment by Jazzz42** [comment]
Well, I would expect an issue to be closed when it is resolved or rejected. "No additional comments" does not seem as a valid reason since I just commented, because it does not seem to be resolved yet, but I might be mistaken and that is why I was searching for an answer in this thread.

**Comment by schrdori** [comment]
I am also having trouble with waiting for and finding elements.
working with c# and `WebDriverWait`
`SeleniumExtras.WaitHelpers.ExpectedConditions.ElementExists(By.Name(title)` for example is not finding elements if they tend to "pop up" while waiting for them.
Is this an issue for  appium-dotnet-driver repos or here?

**Comment by Take-A-Byte** [comment]
@schrdori  I am facing the sort of similar issue. Did you find any solution to this?

**Comment by schrdori** [comment]
> @schrdori I am facing the sort of similar issue. Did you find any solution to this?

Sadly not. A workaround could be to add a manual delay before searching.

but i have stopped working with WinAppDriver 2 years ago due to lack of updates.

**Comment by liljohnak** [comment]
@schrdori what are you using?  And how do you like it?

**Comment by schrdori** [comment]
@liljohnak  i am using Ranorex. It is pretty expensive but also pretty good. Comes with an already implemented framework and its own IDE. Also fully C# compatible. I like it a lot. 

Only thing is thier Support Team, can take quite a while to get a response and sometimes it feels like they didnt really read it… but if you insist you get an answer.
