### ISSUE TITLE
RemoteTouchScreen.scroll() in Java

### ISSUE THREAD

**Issue by naddison** [Microsoft/WinAppDriver#331]
Hi, can someone help/confirm my suspicions regarding scrolling and WindowsAppDriver?

The scroll actions available via RemoteTouchScreen is scroll(Coordinates where, int xOffset, int yOffset) and scroll(int xOffset, int yOffset).

When calling scroll(int xOffset, int yOffset) the action succeeds but does not result in the desired action. Attempting with multiple different argument values only resulted in the Start Menu being opened and closed. I suspect the scrolling action is defaulting to the absolute lower left hand corner of the active screen, or the action is completely different.

To specify a point on the screen to scroll from we can call scroll(Coordinates where, int xOffset, int yOffset), however Coordinates is an interface that is implemented on RemoteWebElement. The scroll function results in calling Coordinates.getAuxillary() which calls getId(). The id field is also available from RemoteWebElement. 

My test follows the PageObject pattern and defines the elements as follows:

```java
@FindByAccessibilityId(accessibilityId = "buttonToScrollTo")
public WebElement buttonToScrollTo;
```

I have tried to cast the WebElement to WindowsElement and RemoteWebElement but have been met by the exceptions:

1. java.lang.ClassCastException: com.sun.proxy.$Proxy22 cannot be cast to io.appium.java_client.windows.WindowsElement
2. java.lang.ClassCastException: com.sun.proxy.$Proxy22 cannot be cast to org.openqa.selenium.remote.RemoteWebElement

**Comment by hassanuz** [comment]
Hi @naddison, 

> the action succeeds but does not result in the desired action. 
Can you describe the action taking place instead of the desired one? 

Can you please also provide WinAppDriver (or Appium) server logs so we can understand what value is being received by the server. 
Thanks

**Comment by hassanuz** [comment]
Marking issue as closed due to no additional comments.
