### ISSUE TITLE
Issue in WinAppdriver unable to find element on a page

### ISSUE THREAD

**Issue by viji-123** [Microsoft/WinAppDriver#332]
After I open the app by default its on the home tab, i get to see the list of options. Now I click on appoinments tab and try to click an element corresponding to that page.
 But am unable to locate the element eventhough the id is correct. So I used pagesource . In the pagesource i see that its still holding the elements from the home page. 
So I tried refresh , but it doesnt work. 

![image](https://user-images.githubusercontent.com/22593499/34225198-8b986456-e593-11e7-8b81-72a33c6e998b.png)

please advice

**Comment by timotiusmargo** [comment]
Hi @viji-123,

Is this also the behavior you see when inspecting the UI tree through [`inspect.exe`](https://github.com/Microsoft/WinAppDriver/tree/v1.0#inspecting-ui-elements)? Application session `PageSource` attribute is supposed to reflect the UI tree shown through `inspect.exe` on a given state.

If both of these tools return the elements from the **home page** while a different tab is selected and rendered, the application you are testing may have a real accessibility bug.

**Comment by viji-123** [comment]
Thanks for your reply. When I use the inspect tool it shows the elements corresponding to the tab I select. For example, if I select appointments tab it shows it's elements. 
But if I use that id (got from inspect tool) it's not able to locate the element when I run the script

**Comment by timotiusmargo** [comment]
Hi @viji-123,

Have you given it enough time after you switch to a new tab? There's a chance that find element or page source command is executed to soon before the UI tree is updated. If you still having trouble locating the element after ensuring the UI tree is updated, can you paste your find element query and the UI Tree XML snapshot from the `PageSource` attribute?

**Comment by hassanuz** [comment]
Marking issue as closed due to no additional responses.
