### ISSUE TITLE
WinAppDriver throws ERROR : WinAppDriver loading MitaBroker 

### ISSUE THREAD

**Issue by shankarkc** [Microsoft/WinAppDriver#336]
I have created win10VM on azure and trying to run WinAppDriver.
I have opened the firewal using
```
netsh advfirewall firewall add rule name="Windows application driver" dir=in action=allow protocol=TCP localport=4723
```
In firewall UI too it shows properly
![image](https://user-images.githubusercontent.com/4651863/34809027-5aec30b8-f6b8-11e7-8a57-9c6838e2ed7b.png)
![image](https://user-images.githubusercontent.com/4651863/34809038-79b42e60-f6b8-11e7-8687-74805df738f6.png)

I try to run the WinAppDriver using below command as i want to access it from remote machine

```
c:\Program Files (x86)\Windows Application Driver>WinAppDriver.exe 10.169.55.22 4723
Windows Application Driver listening for requests at: http://127.0.0.1:4723/
Press ENTER to exit.

```

I want to run my tests from a remote machine. 
I am running this in admin prompt. I am not sure why it throws error. 
I see 
```
SessionManager - ERROR : WinAppDriver loading MitaBroker : IRequestHandlePtr::CreateInstance failed w/err 0x800401f0
HTTP/1.1 500 Internal Error
Content-Length: 85
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"Failed to create instance"}}
```
I am not sure how to run sample test on remote machine

Here is my testcode
```
   DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability("app", "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App");
            CalculatorSession = new WindowsDriver(new URL("http://10.169.55.52:4723"), capabilities);

            CalculatorSession.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);

            CalculatorResult = CalculatorSession.findElementByAccessibilityId("CalculatorResults");
```

Can someone let me know how to run the tests on remote machine? all the samples we have running tests locally...How to run tests on remote machine?
i see below error 
```
POST /session HTTP/1.1
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
Content-Length: 302
Content-Type: application/json; charset=utf-8
Host: 10.169.55.52:4723
User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_112)

{
  "desiredCapabilities": {"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","platformName":"Windows"},
  "capabilities": {
    "desiredCapabilities": {"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App","platformName":"Windows"},
    "firstMatch": [
      {"platformName":"windows"}
    ]
  }
}
SessionManager - ERROR : WinAppDriver loading MitaBroker : IRequestHandlePtr::CreateInstance failed w/err 0x800401f0
HTTP/1.1 500 Internal Error
Content-Length: 85
Content-Type: application/json
```

My tests run on a jenkins slave that is linux OS...But tests suppose to run on a remote windows VM.

**Comment by khouzam** [comment]
Hi @shankarkc,

You will need to run WinAppDriver elevated (as and Administrator) in order to listen on a different port than 127.0.0.1.

**Comment by shankarkc** [comment]
Hi @khouzam, i updated the defect details... Can you please take a look?

**Comment by shankarkc** [comment]
I want to run my test on a remote machine and I am running in admin mode.

**Comment by shankarkc** [comment]
Hi @khouzam did you get a chance to look at this?

**Comment by shankarkc** [comment]
PING...can anyone help me here?

**Comment by hassanuz** [comment]
Hi @shankarkc ,

Can you try to manually uninstall WinAppDriver, and install (or reinstall) the latest v1.0 version, and see if the problem persists?

**Comment by shankarkc** [comment]
I already had this version on my WindowsPC. The issue was different. In readme it was not clear how to run on a remote machine. I have updated the readme and created a [PullRequest](https://github.com/Microsoft/WinAppDriver/pull/342). Please merge it so that other users can refer it if they stumble on this issue.

**Comment by hassanuz** [comment]
Hi @shankarkc ,

Thanks for your feedback, we will review your PR.
