### ISSUE TITLE
Test execution on Azure windows 10 VM box is very slow

### ISSUE THREAD

**Issue by Manvibha** [Microsoft/WinAppDriver#337]
Hi Tim/Yodurr,

I am executing test suite on Azure Windows 10 VM  via VSTS build. I am experiencing test execution performance issue  as it is taking more time to complete test execution. 

A test method which is designed for data driven with 6 set of test data is  executed for 6 iterations. To complete all 6 iterations it takes 25 mins and i guess this is huge time. On an average 1 iteration takes ~5mins to complete. 
 
Test case have following steps to perform  
1. launch the application and login
2. Import a file 
3. Make some Api call's 
4. validate the status 

Any thoughts on this on how to improve performance ? 

Thanks,
Mahendra

**Comment by hassanuz** [comment]
Hi @Manvibha ,

Can you provide additional information on which steps take longer to execute? (e.g. session creation, finding elements, executing actions, etc.).

**Comment by shankarkc** [comment]
@Manvibha I too face this issue...
What i notice is WinAppDriver.exe console contents showup slowly as someone is tying it.
[Here](https://drive.google.com/file/d/1XxNDp4DuYE0b45zpQzc1LsxxsOmdGHOS/view?usp=drivesdk ) is the video for your reference. If its this slow its kind of unusable on Azure Windows machines.

**Comment by hassanuz** [comment]
Hi @shankarkc ,

Can you confirm whether the CPU is being utilized by other applications from Task Manager (CTRL-Shift-ESC).

Thanks

**Comment by shankarkc** [comment]
On that machine nothing was running except Winappdriver. So something wrong
with wad that need to be fixed. I will check cpu utilization today and
update the defect.

**Comment by Manvibha** [comment]
I have 160 test cases automated and earlier it use to take more than 9hrs to execute test suite. After I tuned for performance by enhancing few reusable methods  which were using Action builders performance have improved a bit and time taken for execution is now ~8hrs. However, working with data grid is slow irrespective of machine and may be there is a room to improve the way elements are identified by winappdriver . 

regards,
Mahendra

**Comment by timotiusmargo** [comment]
Hi @Manvibha,

Can you break down on which steps/commands/operations does the time is mostly consumed? From your sample steps above the breakdown could look like (arbitrary numbers are used below):

1. Launch the application and login (X seconds)
   - Launch application (X seconds)
     - Create session (X seconds)
   - Login (X seconds)
     - Find element (X seconds)
     - Click element (X seconds)
     - etc.
2. Import a file (X seconds)
   - Find element (X seconds)
   - Select menu element (X seconds)
   - etc.
3. etc.

This will help us identify certain commands that can be improved. In addition it will also help you to potentially refactor your test to avoid duplicating/repeating certain steps that are expensive. This approach helped us optimized our [WebDriverAPI test](https://github.com/Microsoft/WinAppDriver/tree/v1.0/Tests/WebDriverAPI) by re-using launched application instance between test cases (avoid closing and re-launching application). This optimization itself reduce the test time by close to 70%.

**Comment by hassanuz** [comment]
If issue persists on latest version of WAD please create new ticket.
