### ISSUE TITLE
Support WinAppDriver to register to grid based on JSON config.

### ISSUE THREAD

**Issue by shankarkc** [Microsoft/WinAppDriver#339]
Selenium grid Nodes that register with selenium hub and this can be specified using json config file. It would be great if winAppDriver can support similar capability to register against selenium grid. User during runtime selects one of the Windows machine from selenium grid and executes his test. This will be very much similar to browser. As of now WinAppDriver doesnt support config file. I should be able to ask selenium hub to provide me a session on windows machine which matches my desired capabilities. I need not know the IPAddress of windows node to run my tests. If this is already supported then please provide documentation on how to use winappServer with selenium grid.

**Comment by caulfield2** [comment]
These links should be able to help you create an Appium node that can connect to your Selenium grid. 

https://appium.io/docs/en/advanced-concepts/grid/
https://www.seleniumhq.org/docs/07_selenium_grid.jsp#selenium-grid
#122 
#294 
#374
