### ISSUE TITLE
Does WinAppDriver support control pattern execution?

### ISSUE THREAD

**Issue by palich-serge** [Microsoft/WinAppDriver#340]
Hi,

How I can call control patterns like InvokePattern/ScrollPattern/ValuePattern etc.?

Thanks.

**Comment by timotiusmargo** [comment]
Hi @palich-serge,

In Selenium/Appium WebDriver protocol, these patterns are translated into simple user interactions and introspections such as [click](https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/ElementClick.cs), and [text](https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/ElementText.cs). Check out the [ComboBox](https://github.com/Microsoft/WinAppDriver/blob/master/Tests/UWPControls/ComboBox.cs) sample test below to see how to select an entry in the combo box and retrieve the selected value.
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/UWPControls/ComboBox.cs
