### ISSUE TITLE
Mouse Right Click

### ISSUE THREAD

**Issue by FBorges14** [Microsoft/WinAppDriver#343]
There is no way to simulate a right button click and for some windows application it was very useful.

**Comment by timotiusmargo** [comment]
Hi @FBorges14,

Mouse right click or context click action is definitely useful and we have a proper example on how to do it on https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/Mouse.cs#L72. E.g.

```c#
session.Mouse.ContextClick(appNameTitle.Coordinates);
```

**Comment by jsbakker** [comment]
If anybody wants to know how to do it in Ruby:

```Ruby
	element = $Session.find_elements(:name, "Item name")[0]
	$Session.action.context_click(element).perform()
```

**Comment by hassanuz** [comment]
Closing ticket as issue seems to be resolved.

**Comment by Soloveykos** [comment]
Hi, I'd like to do ContextClick on my own coordinates since control is not possible to define by UIInspect. how could I define coordinates on my own?
I need something like: session.Mouse.ContextClick(MyOwnCoordinatesDependingOnControlCoordinates);

**Comment by jpalmer-miovision** [comment]
> Hi, I'd like to do ContextClick on my own coordinates since control is not possible to define by UIInspect. how could I define coordinates on my own?
> I need something like: session.Mouse.ContextClick(MyOwnCoordinatesDependingOnControlCoordinates);

Try moving the mouse where you want to click based on offsets:

session.Mouse.MouseMove(session.FindElementByName("ElementName").Coordinates, 145, 391);
session.Mouse.ContextClick(null);

This will Context Click with an offset of 145, 391 from the element named "ElementName".

**Comment by Soloveykos** [comment]
yep, offsets are the best, thanks :-)

пт, 27 сент. 2019 г. в 20:23, James Palmer <notifications@github.com>:
