### ISSUE TITLE
Unable to select element (list item) in List if is not visible (needs to scroll in order to get visible)

### ISSUE THREAD

**Issue by FBorges14** [Microsoft/WinAppDriver#345]
I'm not able to select an element that is not visible on a list. Is necessary to do scroll in order it gets visible and select it.

Is there any way to do it is a more easy way?

**Comment by timotiusmargo** [comment]
Hi @FBorges14,

When a list element is dynamically generate, Windows Application Driver will not be able to see/find/locate it until it is in fact constructed and added to the UI tree. In such case, you would really need to scroll the list or move the cursor with keyboard arrow to trigger the construction just as what a user would do.
