### ISSUE TITLE
Test takes too long to click on element using XPath

### ISSUE THREAD

**Issue by ycoliveira** [microsoft/WinAppDriver#349]
I'm doing a test where I have to click on some "Yes" buttons and I can only access those buttons using XPath but with code I'm using: 

Driver.Session.FindElementByXPath("//Pane[@AutomationId='Requisitos de Pasta']").FindElementByXPath(".//Pane[@AutomationId='picBoxYes']").Click();
or
Driver.Session.FindElementByXPath("//Pane[@AutomationId='Requisitos de Pasta']//Pane[@AutomationId='picBoxYes']").Click();

The test takes 14~15 sec to click on each element.
Is it a normal issue?

**Comment by hassanuz** [comment]
Hi @ycoliveira, 

Element search using Xpath is known to take longer than other locator attributes. We're looking into improving Xpath performance if possible.

**Comment by vaib-ag** [comment]
It would be a dirty hack but xpath performance for children level elements can be improved. 
if the starting node of xpath indicated only child level object, this would not need the inner program (object locator of driver) to trace down all the decedents, hence faster.

**Comment by hassanuz** [comment]
XPath performance was improved with [WinAppDriver v1.1.1](https://github.com/microsoft/WinAppDriver/releases/tag/v1.1.1).
