### ISSUE TITLE
Unable to get a checkbox state for UWP application

### ISSUE THREAD

**Issue by quitefire** [Microsoft/WinAppDriver#35]
Hi guys, could you suggest on how to get a checkbox state of AppiumWebElement for UWP application? 

Regards,
Bogdan

**Comment by quitefire** [comment]
Hi guys, any progress on fixing this issue? 

Thanks,
Bogdan

**Comment by alakshmi1030** [comment]
Hello Bogdan, you should be able to detect element state using the latest release of WinAppDriver:
https://github.com/Microsoft/WinAppDriver/releases/tag/v0.4-beta

You just need to use the "selected" property of the WebDriver element which will return a boolean value of whether or not the element is selected.

**Comment by quitefire** [comment]
Hi there , thanks a lot.

Regards,
Bogdan
