### ISSUE TITLE
No JavaScript / TypeScript sample

### ISSUE THREAD

**Issue by johnemau** [microsoft/WinAppDriver#350]
I would love to see [a sample](https://github.com/Microsoft/WinAppDriver/tree/master/Samples) using TypeScript (or just JavaScript) to help me bootstrap for my own app.

I am willing to help out here and create a sample if anyone can help me understand how to create a session  of WinAppDriver in JavaScript? Would it be similar to [webdriver.js](https://github.com/SeleniumHQ/selenium/blob/8f988e07cc316a48e0ff94d8ff823c95142532e9/javascript/webdriver/webdriver.js)?

**Comment by johnemau** [comment]
I think there is a bigger issue that WinAppDriver lacks a JavaScript implementation, that would be required before we can create a sample.

The JavaScript implementation could be built on top of [the library that appium uses, wd](https://github.com/admc/wd)

**Comment by committedtester** [comment]
Have a look at my github project. It's not typescript but it does have the core of what you could use to get going. 
https://github.com/committedtester/JSes6WinAppDriver

- Re-connection on slow application load
- Page Object Model
- Await/Async ES6 syntax
-Preliminary work on getting loops working to deal with loading elements

**Comment by hassanuz** [comment]
[JavaScript samples](https://github.com/microsoft/WinAppDriver/tree/master/Samples/JavaScript) have been added with the new [WinAppDriver v1.2](https://github.com/microsoft/WinAppDriver/releases/tag/v1.2-RC) release.

**Comment by lynn-fisher** [comment]
Thanks "committedTester", you are a life saver! I have been pulling my hair out for days trying to get UWP tests up and running  in Word. Lots of simple calculator tests and notepad tests but nothing that requires a window focus change. I could see lots of chat about using windows handlers and attaching to a new session but all the examples where C# or Java. This seems to be the only example out there so far. Thanks for making you solution available to others.

**Comment by committedtester** [comment]
Thanks @lynn-fisher, just glad to just give something back to the community!
