### ISSUE TITLE
Command Line Actions Using WinAppDriver- Feature Request

### ISSUE THREAD

**Issue by AmirHNK** [Microsoft/WinAppDriver#351]
I am using WinAppDriver to test an application and its installer application on a remote machine. As a part of my test procedure, I need to do the following tasks:

- Check if a folder exists (to check if the application was installed at a desired path)

- Check if a process exists/an application is running

- Kill a process

- Remove folder (testing the repair/remove feature of my installer application)

- Other command line actions ( e.g, invoking Devcon.exe with arguments)

Right now to accomplish some of the above, I have created small Windows Form applications where I click a button on the application through WinAppDriver. However, this is not the right way to do it and I would like to be able to accomplish above tasks simply through my test scripts.

**Comment by timotiusmargo** [comment]
Hi @AmirHNK,

If I read your comment right, you are trying to automate some utilities/management tasks in the remote test machine **IN ADDITION** to the UI test you are performing using Windows Application Driver. This scenario makes sense and maybe we could explore the possibilities of executing script sometimes in the future.

In the meantime, while you could attempt to perform this task using existing tools like **Command Prompt** console, **Task Manager**, and **File Explorer**, I would suggest writing a script (batch file), put it somewhere accessible (e.g. shared folder on network), and simply run it.
