### ISSUE TITLE
[Question]: Is there a way to get entire page source as xml?

### ISSUE THREAD

**Issue by vishnu45** [Microsoft/WinAppDriver#352]
The inspect tool does allow to view elements in a tree view along with the various properties we can use. However, is there a way (or tool) that would show entire page source as an xml (without having to use getPageSource() progamatically).

**Comment by hassanuz** [comment]
There isn't a tool that we are aware to generate the XML tree. We can see the general usage for this, though if you have specific usecase that you're willing share, please do.

**Comment by vishnu45** [comment]
I was asking coz the application I am testing has a very long workflow. So say there were around 50 pages that I have to traverse through to complete a single test (u can't directly jump to the page, u have to go through all pages before page 30), on page 30 I have an element which I am using XPath to identify. But I messed up the XPath locator. So when executing the test, I would have to wait for the test to reach page 30 to realize the incorrect XPath locator. On top of that WinAppDriver execution speed is a lot slower as compared to Selenium, so I would have to wait even more longer.
However, if I could get the entire XML page source, I could use tools like the XPath evaluator in Eclipse to atleast check against the page source if my XPath query is correct. For now, I have to execute script and get the page source of each page to perform this.
Also I am not aware if tools like Inspect have a capability to generate the entire XML of the tree structure.

**Comment by Darsh12345** [comment]
driver.getPageSource() should return you the complete page source, if you are using java.

**Comment by vishnu45** [comment]
@Darsh12345 , thanks for the suggestion. I am already aware driver.PageSource() can be used. I was trying to figure out a tool which might allow me to directly obtain the appSource of any particular page of the application under test. Just like right clicking a webpage within a browser and viewing pageSource (without having to call driver.getPageSource() programatically).
I figured out that you can use Appium Desktop client to get the appSource of any application capable of being launched from the client (or attached).
