### ISSUE TITLE
Splash screens and popup message boxes 

### ISSUE THREAD

**Issue by todoubled711** [Microsoft/WinAppDriver#353]
Hi All,

I am hoping that someone can help me. When I first launch our application I get a splash screen and once you close that get a message box. When I run my Appium test with the WinAppDriver it launches the application then it hangs when these popups components appear. If I don't close anything and stop the test then rerun them the Splash Screen will close. Then keep repeating these steps and the message box will close then the actual test will execute.

I am hoping others can help!

Thanks,
Todd

**Comment by hassanuz** [comment]
Hi @todoubled711,

Is WinAppDriver.exe hanging, or the target application? Can you post the WinAppDriver logs?

**Comment by hassanuz** [comment]
Apologies for the delay @todoubled711 - if you're still having specific issues, please open a new ticket and we will get back to you as soon as possible. In regards to splash screen handling, please refer to [here](https://github.com/Microsoft/WinAppDriver/wiki/Frequently-Asked-Questions/289a8b325d3ddab9f08b4398c49163a9a136f607#what-to-do-when-an-application-has-a-splash-screen-or-winappdriver-fails-to-recognize-the-correct-window).
