### ISSUE TITLE
send_keys types only first symbol from string

### ISSUE THREAD

**Issue by andreypeshko** [Microsoft/WinAppDriver#354]
Hello!  

Thank you for your attention :)

I trying out WinAppDriver with an UWP application which is built on Xamarin. I am using the modified Python sample. Here is the test code:

```
  def test_login(self):
        login_text_field = self.driver.find_element_by_accessibility_id('LoginViewLoginEntry')
        sleep(5)
        login_text_field.clear()
        sleep(5)
        login_text_field.send_keys('testtest')
        sleep(50)
        pass
```

When calling send_keys, I see only "t" printed in the text box. 
Here is driver log:

> POST /session/EF300C52-DD66-4263-A328-386385F22368/element/42.10422808.2.10/value HTTP/1.1
> Accept: application/json
> Accept-Encoding: identity
> Connection: close
> Content-Length: 150
> Content-Type: application/json;charset=UTF-8
> Host: 127.0.0.1:4723
> User-Agent: Python http auth
> 
> {"text": "testtest", "value": ["t", "e", "s", "t", "t", "e", "s", "t"], "id": "42.10422808.2.10", "sessionId": "EF300C52-DD66-4263-A328-386385F22368"}
> HTTP/1.1 200 OK
> Content-Length: 63
> Content-Type: application/json
> 
> {"sessionId":"EF300C52-DD66-4263-A328-386385F22368","status":0}

As you can see, whole string was sent, but only first item was written. 
Is it something Xamarin-related? Or am I wrong somewhere? 

Thank you for answering,
Have a nice day!

**Comment by timotiusmargo** [comment]
Hi @andreypeshko,

This is interesting. The JSON wire protocol payload seems correct to me. Are you using the WinAppDriver [v1.0](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.0) release?

One possible issue if for the textbox to somehow loose focus after one key is typed. Can you try sending just 2 keys such as "te" and see if that makes a difference?

**Comment by andreypeshko** [comment]
Hi @timotiusmargo ,

You are right, my bad, seems like old version was installed.
I re-installed the WinAppDriver v1.0 and it worked.

Thank you!

**Comment by GYingchao** [comment]
Hi, 

Same thing happened to me recently. I'm using v1.1.1 and python client on a x64 win10 PC. 
As a workaround, I have to make a for loop to send characters one by one. = =
