### ISSUE TITLE
FindElementBy option for 'Mouse Move' attribute !

### ISSUE THREAD

**Issue by QAAutomationNewbie** [microsoft/WinAppDriver#355]
Hi,

I am currently using the Win App driver along with C# for automating a windows based application. I am stuck at identifying the best way to identify a button to be clicked using 'Mouse Move' option as there are no other attributes by which it can be identified based on the actual code base (one more element has the same class name, hence could not use that attribute). 
Snip from the inspect tool for the button:
![image](https://user-images.githubusercontent.com/36305206/36036502-5200a600-0dba-11e8-82e3-f315533905f1.png)
Any suggestions / help in this regard will be highly beneficial.

Thanks in Advance!

**Comment by DGCBio** [comment]
Are you not able to assign an Automation Id to the element?

You could also try creating an xpath query for your element.

**Comment by hassanuz** [comment]
Hi @QAAutomationNewbie,

Assuming XPath wasn't able to work, you can also try using the new Actions API to hover a Touch/Pen input over the desired coordinates. We have a couple of samples on using the Actions API - you can take a look [here](https://github.com/Microsoft/WinAppDriver/blob/v1.1/Samples/C%23/Paint3DTest/ScenarioDraw.cs).

**Comment by hassanuz** [comment]
Closing issue due to lack of update.
