### ISSUE TITLE
SendKeys does not always send all characters

### ISSUE THREAD

**Issue by DGCBio** [Microsoft/WinAppDriver#356]
My team is using WinAppDriver without Appium.  We have set up the SendKeys method and have some tests to make sure it works with our test app.  Last week I had an array of strings with special characters in it to test the full functionality.  WinAppDriver performs well on these strings out of the box, but I had intermittent failures with this C# string: 
`"Multiple backslashes and quotes \\ \\\\ \\\\\\ \\\\\\\\ \"\" \"\"\" \"\"\"\" ''' '''' \"'\"'\" "`

Before we send to the host machine/WinAppDriver, we call JsonConvert.SerializeObject(new { value = new[] { text } }) on the string where 'text' is the string to send. This inserts all necessary escape characters.

Roughly 60% of the time, the string that is entered in the field on our app is missing a double quotes in either the set of 3 double quotes, or more often one is omitted from the set of 4 double quotes. The other times the string is an exact match of what we intended to send.

We believe this is a bug with WinAppDriver.

**Comment by hassanuz** [comment]
Hi @DGCBio,

Can you confirm you're using WinAppDriver v1.0, and can you paste the JSONWP payload found on the WinAppDriver.exe console? 

We tried with the following code, and we were not able to reproduce the issue/

`editBox.SendKeys("Multiple backslashes and quotes \\ \\\\ \\\\\\ \\\\\\\\ \"\" \"\"\" \"\"\"\" ''' '''' \"'\"'\" ");`

Our JSON payload as found in WinAppDriver.exe:
```
POST /session/081ACAAC-6E00-41FE-8A7B-3EC6A5B0B50B/element/42.269896/value HTTP/1.1
Accept: application/json, image/png
Content-Length: 109
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"value":["Multiple backslashes and quotes \\ \\\\ \\\\\\ \\\\\\\\ \"\" \"\"\" \"\"\"\" ''' '''' \"'\"'\" "]}
HTTP/1.1 200 OK
Content-Length: 63
Content-Type: application/json

{"sessionId":"081ACAAC-6E00-41FE-8A7B-3EC6A5B0B50B","status":0}
```

**Comment by DGCBio** [comment]
Hi @hassanuz,
Thanks for the reply.

I am sending my request to another device, so I cannot see the JSON payload (I've noticed that the payload is only shown locally when sending to WinAppDriver locally).

The device running WinAppDriver on the server side is a Windows tablet and it is running WinAppDriver 1.1.0.2.

I set up the test to run locally, and I ran it over and over.  It finally failed on maybe the 30th attempt (I set up my test to send the keys 10 times, assert that the text box has the expected text and then clear it to prepare to send again).  

Here are the payloads on the time it failed (first the sendkeys, second is the get text):

```
POST /session/9409354C-AF19-4E9E-BCD5-0BD5586F693B/element/42.2166058.3.7/value HTTP/1.1
Accept: application/json, image/png
Content-Length: 109
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"value":["Multiple backslashes and quotes \\ \\\\ \\\\\\ \\\\\\\\ \"\" \"\"\" \"\"\"\" ''' '''' \"'\"'\" "]}
HTTP/1.1 200 OK
Content-Length: 63
Content-Type: application/json

{"sessionId":"9409354C-AF19-4E9E-BCD5-0BD5586F693B","status":0}


==========================================
GET /session/9409354C-AF19-4E9E-BCD5-0BD5586F693B/element/42.2166058.3.7/text HTTP/1.1
Accept: application/json, image/png
Host: 127.0.0.1:4723


HTTP/1.1 200 OK
Content-Length: 167
Content-Type: application/json

{"sessionId":"9409354C-AF19-4E9E-BCD5-0BD5586F693B","status":0,"value":"Multiple backslashes and quotes \\ \\\\ \\\\\\ \\\\\\\\ \"\" \"\"\" \"\"\" ''' '''' \"'\"'\" "}
```

**Comment by hassanuz** [comment]
Hi @DGCBio,

Would it be possible for you try testing this string injection on to Notepad, or other text input programs?

**Comment by DGCBio** [comment]
@hassanuz,  I was able to test this on notepad.exe and after 1400 tries, it never gave the error.  Could it be an issue specific to UWP or Xamarin Forms applications?

**Comment by Chintzz** [comment]
@hassanuz,

I am facing a similar issue. I am trying to access a remote folder using run command. I am using the following command in Java

```
runTime = Runtime.getRuntime();
process = runTime.exec("c:\\windows\\system32\\rundll32.exe shell32.dll,#61");//open run dialogbox

desktopSession.findElementByName("Open:").sendKeys("\\\\remoteFolder\\childLevel1\\ChildLevel2");
```

But while executing the script, WinAPP driver just enters "er\\childLevel1\\ChildLevel2" in the search box. It appears that there is some issue when we try to enter a double backslash(i.e. \\\\) in the string for sendkeys. could you please look into it?

**Comment by mindaugasLukosiunas** [comment]
I get this issue as well. Even though in driver log you can see the exact text was sent, but the text that actually appears in the input field sometimes missing some characters.

**Comment by hassanuz** [comment]
Hi @mindaugasLukosiunas  and @Chintzz,

Could you provide the WinAppDriver.exe console logs as well? This will help us look into what's going on from the WinAppDriver server layer.

**Comment by hassanuz** [comment]
Please create a new issue if this persists. Thanks

**Comment by Michaelwan777** [comment]
> My team is using WinAppDriver without Appium. We have set up the SendKeys method and have some tests to make sure it works with our test app. Last week I had an array of strings with special characters in it to test the full functionality. WinAppDriver performs well on these strings out of the box, but I had intermittent failures with this C# string:
> `"Multiple backslashes and quotes \\ \\\\ \\\\\\ \\\\\\\\ \"\" \"\"\" \"\"\"\" ''' '''' \"'\"'\" "`
> 
> Before we send to the host machine/WinAppDriver, we call JsonConvert.SerializeObject(new { value = new[] { text } }) on the string where 'text' is the string to send. This inserts all necessary escape characters.
> 
> Roughly 60% of the time, the string that is entered in the field on our app is missing a double quotes in either the set of 3 double quotes, or more often one is omitted from the set of 4 double quotes. The other times the string is an exact match of what we intended to send.
> 
> We believe this is a bug with WinAppDriver.

Check this method. Same problem I met was solved by this.
https://github.com/microsoft/WinAppDriver/issues/1263#issuecomment-686482406
