### ISSUE TITLE
.Click() gives error "An unknown error occurred in the remote end while processing the command"

### ISSUE THREAD

**Issue by jan-coppens** [Microsoft/WinAppDriver#357]
Hi,

I modified the CalculatorTest project to test a custom UWP app.

What I changed:

1. changed the AppId to my custom UWP app
2. Added the following test method:

        [TestMethod]
        public void Register()
        {
            session.FindElementByAccessibilityId("Register").Click();
        }

Testing:

1. I start the WinAppDriver.exe
2. Launch the Register test method.

App starts successfully
After startup is complete, test stops with the following error:

![afbeelding](https://user-images.githubusercontent.com/12556207/36154513-06627e4c-10d2-11e8-9c98-f594d46c981e.png)

**Comment by hassanuz** [comment]
Hi @jan-coppens ,

Can you provide information about your custom application (e.g. where this element located, if it's hidden, or if you can access the element via inspect.exe), as well as the WinAppDriver version being used?

Thanks

**Comment by jan-coppens** [comment]
Hi,

The application is an UWP app as I already mentioned.
Below you can see a screenshot of the app.
![afbeelding](https://user-images.githubusercontent.com/12556207/36198247-54462baa-1176-11e8-829c-c0805297af8d.png)

I can access the element via inspect.exe

![afbeelding](https://user-images.githubusercontent.com/12556207/36198674-839d91b2-1177-11e8-99ef-8ea08bbf7822.png)


If I split the line in two:

var register = session.FindElementByAccessibilityId("Register");
register.Click();

I can see that the button is found.
The error occurs when executing the Click() function.

The WinAppDriver version is the latest:
![afbeelding](https://user-images.githubusercontent.com/12556207/36198391-c37596c8-1176-11e8-93ed-66ea5851e2a6.png)

**Comment by jan-coppens** [comment]
My register button was a custom usercontrol, containing a button.
Using the following code fixed the issue.

session.FindElementByAccessibilityId("Register").FindElementByClassName("Button").Click();

**Comment by vishnumbjn** [comment]
> Hi,
> 
> I modified the CalculatorTest project to test a custom UWP app.
> 
> What I changed:
> 
> 1. changed the AppId to my custom UWP app
> 2. Added the following test method:
>    ```
>     [TestMethod]
>     public void Register()
>     {
>         session.FindElementByAccessibilityId("Register").Click();
>     }
>    ```
> 
> Testing:
> 
> 1. I start the WinAppDriver.exe
> 2. Launch the Register test method.
> 
> App starts successfully After startup is complete, test stops with the following error:
> 
> ![afbeelding](https://user-images.githubusercontent.com/12556207/36154513-06627e4c-10d2-11e8-9c98-f594d46c981e.png)

Hi jan-coppens. I am trying to launch my custom uwp app and its saying cannot launch as the app id is found although I provided correct app id. Could you please help me with the code that launches the custom UWP app

**Comment by vagisha-nidhi195** [comment]
@vishnumbjn Did you find a solution to this? I am facing the same issue.

**Comment by ravi46kom** [comment]
Hi @vishnumbjn 
I'm also facing same issue with my code, there any alternate which we can execute.
