### ISSUE TITLE
findElementByName is not working ?

### ISSUE THREAD

**Issue by kumarkrish85** [Microsoft/WinAppDriver#359]
I am trying to automate an application using Java. Following are my configuration details, 

**Appium**

<dependency>
    <groupId>io.appium</groupId>
    <artifactId>java-client</artifactId>
    <version>5.0.4</version>
</dependency> 

**Driver version:** v1.0 

**Code:**

`DesiredCapabilities capability = new DesiredCapabilities();
		capability.setCapability("app", "C:\\Users\\<current user>\\Desktop\\App.lnk");
		capability.setPlatform(Platform.WIN10);
		try {
			driver = new WindowsDriver<WindowsElement>(new URL("http://127.0.0.1:4723"), capability);
			driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
			Thread.sleep(5000);
		} catch (MalformedURLException e) {
			e.printStackTrace();
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		WindowsElement element = driver.findElementByName("Folder Compare");
		element.click();`

**Exception:**

Exception in thread "main" org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'PC252611', ip: '10.219.211.41', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: io.appium.java_client.windows.WindowsDriver
Capabilities [{app=C:\Users\589103\Desktop\Beyond Compare 4.lnk, javascriptEnabled=true, platformName=WINDOWS, platform=WINDOWS}]
Session ID: 4B584146-AAB2-4875-A29A-A5C68A676C3B
*** Element info: {Using=name, value=Folder Compare}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:82)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.execute(WindowsDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:356)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:62)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.findElement(WindowsDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByName(RemoteWebDriver.java:434)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementByName(DefaultGenericMobileDriver.java:110)
	at io.appium.java_client.AppiumDriver.findElementByName(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.findElementByName(WindowsDriver.java:1)
	at WinApp.main(WinApp.java:32)

Used inspect.exe to spy an object and tried to click the button named "Folder Component"

**Comment by hassanuz** [comment]
Hi @kumarkrish85,

Can you confirm if it's "Folder Component" or if it is "Folder Compare", as your code is searching for the latter.

**Comment by kumarkrish85** [comment]
@hassanuz , I am trying to find and click button named "Folder Compare". I have tried it even with  latest 6.0.0-Beta 3 build , but it's not working.

![test](https://user-images.githubusercontent.com/27405093/36465030-3f24cb18-16f9-11e8-9301-8f6da2552fb6.png)

**Comment by hassanuz** [comment]
Hi @kumarkrish85,

Can you provide the WinAppDriver.exe logs?

**Comment by kumarkrish85** [comment]
@hassanuz , Please find the below logs

Windows Application Driver listening for requests at: http://127.0.0.1:4723/
Press ENTER to exit.


==========================================
POST /session HTTP/1.1
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
Content-Length: 472
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_121)

{
  "desiredCapabilities": {
    "app": "C:/Users/589103/Desktop/Beyond Compare 4.lnk",
    "platformName": "Windows",
    "platform": "WIN10"
  },
  "requiredCapabilities": {},
  "capabilities": {
    "desiredCapabilities": {
      "app": "C:/Users/589103/Desktop/Beyond Compare 4.lnk",
      "platformName": "Windows",
      "platform": "WIN10"
    },
    "requiredCapabilities": {},
    "alwaysMatch": {
      "platformName": "Windows"
    },
    "firstMatch": []
  }
}
HTTP/1.1 200 OK
Content-Length: 151
Content-Type: application/json

{"sessionId":"8E84151C-443F-450F-84C0-5EED1C6B76CA","status":0,"value":{"app":"C:/Users/589103/Desktop/Beyond Compare 4.lnk","platformName":"Windows"}}


==========================================
POST /session/8E84151C-443F-450F-84C0-5EED1C6B76CA/timeouts HTTP/1.1
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
Content-Length: 29
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_121)

{"type":"implicit","ms":2000}
HTTP/1.1 200 OK
Content-Length: 63
Content-Type: application/json

{"sessionId":"8E84151C-443F-450F-84C0-5EED1C6B76CA","status":0}


==========================================
POST /session/8E84151C-443F-450F-84C0-5EED1C6B76CA/element HTTP/1.1
Accept-Encoding: gzip,deflate
Connection: Keep-Alive
Content-Length: 31
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_121)

{"using":"name","value":"View"}
HTTP/1.1 404 Not Found
Content-Length: 139
Content-Type: application/json

{"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}

**Comment by hassanuz** [comment]
@kumarkrish85,

Can you provide a screen shot of the Inspect tool displaying the desired element?

**Comment by kumarkrish85** [comment]
Hi @hassanuz ,

Please refer the attached screenshot image. The name "Folder Compare" it clearly shows in  inspect tool.

![inspect](https://user-images.githubusercontent.com/27405093/37280213-2a48b1a4-2613-11e8-9841-c996e0c114c8.png)

**Comment by timotiusmargo** [comment]
Hi @kumarkrish85,

**Beyond Compare 4** application opens a temporary application window with `Tapplication` `ClassName` on application startup. **Windows Application Driver** treats this temporary window as the main application window for the created session. This window will eventually disappears when the actual main application window containing the **Folder Compare** button appears. But at this point, your WinAppDriver session is still pointing to the temporary window and as a result you will not be able to locate the button.

To overcome this scenario, you can simply switch the created session to the main application window as soon as it appears. For example:

```c#
DesiredCapabilities appCapabilities = new DesiredCapabilities();
appCapabilities.SetCapability("app", @"C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Beyond Compare 4.lnk");
session = new WindowsDriver<WindowsElement>(new Uri(CommonTestSettings.WindowsApplicationDriverUrl), appCapabilities);
Assert.IsNotNull(session);

// Wait until the main application window appears. This can also be replaced by a simple sleep
var windowHandles = session.WindowHandles;
for (int attempt = 0; attempt < 5 && windowHandles.Count > 1; attempt++)
{
    Thread.Sleep(TimeSpan.FromSeconds(1));
    windowHandles = session.WindowHandles;
}

// Switch session to the only application top level window that is still active (an indication that this is the main window)
if (windowHandles.Count >= 0)
{
    session.SwitchTo().Window(windowHandles[0]);
}

Assert.AreEqual(@"Home - Beyond Compare", session.Title);
WindowsElement folderCompareButton = session.FindElementByName("Folder Compare");
folderCompareButton.Click();
```

**Comment by Kranthi9704** [comment]
Hi timotiusmargo,

Is it possible to automate the UWP apps(implemented by Xamarin and XAMAl) automation

**Comment by Kranthi9704** [comment]
Hi Hassanuz,
i am getting below issue for xamarin uwp app,

{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}

**Comment by Kranthi9704** [comment]
Hi Hassanuz,

When i search object properties using inspection then we are getting error message in inspector.
 [for](url
![1](https://user-images.githubusercontent.com/6367159/40489965-01bd9412-5f88-11e8-9cce-06356ffefe30.png)
)

**Comment by hassanuz** [comment]
Hi @Kranthi9704, 

Can you please open a new issue with additional logs (from WinAppDriver.exe console)? 

Closing this ticket as original issue seems to be resolved.
