### ISSUE TITLE
MSAA selector

### ISSUE THREAD

**Issue by SergKV** [Microsoft/WinAppDriver#363]
Hi,

So I'm currently trying to evaluate if WinAppDriver suits for automation of our home enterprise app and I reached some obstacle which i would like to ask you if it is possible to overcome it somehow. 

So the app has table (row/column) controller window and this window is not visible for UIAutomation selection although it is visible for MSAA selector. 

Does WinAppDriver supports MSAA selectors somehow?

The app is written using WinForms and mostly all elements are reachable with help of AutomationId or XPath selectors or even combination of both of them.

Thx in advance for help.

**Comment by hassanuz** [comment]
Hi @SergKV,

Are you able to check if the inspect tool is able to pick up the element? 

If inspect is unable to detect the desired element, then WinAppDriver will not support it. However, if inspect does pick it up, then we will investigate further. 

Thanks

**Comment by SergKV** [comment]
Hi @hassanuz ,

thx for wuick reply.

The inspect can see given element only as MSAA item.

Thx for help.

**Comment by hassanuz** [comment]
Hi @SergKV,
Thanks for reporting back. Yes, unfortunately then WinAppDriver will not be able to interact with that element.
