### ISSUE TITLE
Find element or page source command is executed too soon before the UI tree is updated

### ISSUE THREAD

**Issue by ellnika** [Microsoft/WinAppDriver#368]
I am testing WPH application.
The app is launched ->Splash Screen -> Home screen.

I am trying to interact with home screen element.

Unfortunately every time I get " Can't find element.."

When I do driver.getPageSource() each time I am retrieving Splash screen UI tree.

Is there a way I can just pass the Splash Screen and only then have the driver  inspect the Home Screen  UI tree?

I tried wait (see code below) but it has no impact. It still cannot find it even though I can see the home page is displayed in the client.

WebDriverWait wait = new WebDriverWait(driver, 20);
        WebElement element = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.name("button")));
     
Appreciate ant suggestions.

**Comment by shankarkc** [comment]
@ellnika  i too hit this issue...It looks like WAD has a bug...I was using microsoft word application. To overcome this issue when i used "/q /w" flags of microsoft word. May be your app too might have some flags to suppress splash screen. Can you pls check with the developers? If you overcome that you might still hit the issue I am facing...if you are running tests on a remote machine
https://github.com/Microsoft/WinAppDriver/issues/361
Good luck.

**Comment by timotiusmargo** [comment]
Hi @ellnika,

As @shankarkc mentioned, bypassing/disabling the splash screen is a great idea unless you are testing the splash screen UI itself. If there is no easy way to disable the splash screen however, there is a few tricks/guides on how to locate the right application window in the FAQ section below:
https://github.com/Microsoft/WinAppDriver/wiki/FAQ#what-to-do-when-an-application-has-a-splash-screen-or-winappdriver-fails-to-recognize-the-correct-window
