### ISSUE TITLE
Constant Integration (CI) + WinAppDriver

### ISSUE THREAD

**Issue by brett-burkhart** [Microsoft/WinAppDriver#371]
In a CI environment, what is the recommended approach for running WinAppDriver?

1.  **Run WinAppDriver as a Windows Service?**
If so, can we get an installer?  Or, should we use a third party tool like SrvStart?  Also, what should the service use for Log On As and do you need to have "Allow service to interact with desktop" enabled?

2. **Or, startup and shutdown WinAppDriver for each test?**

**Comment by brett-burkhart** [comment]
@hassanuz - Is there anyway for anyone to label Issues as "Questions", doesn't look like I have access to set the Label.  Would it make your lives easier to know which issues are questions vs. bugs?

**Comment by hassanuz** [comment]
Hi @brett-burkhart, 
Which CI environment are you using? For VSTS, we found that adding WinAppDriver start and shutdown scripts on your build pipeline to be sufficient.

**Comment by brett-burkhart** [comment]
@hassanuz  - Thanks for the feedback.  Apparently we are using some homegrown CI solution that was developed before CI/CD pipelines were common.  Regardless, it sounds like starting/stopping WAD for each test is sufficient rather than having it constantly running and then having to deal with verifying it's still running.  I'll pass this information along to our CI person and let them add scripts to our pipeline.

**Comment by Soloveykos** [comment]
So how we should correctly shutdown driver on remote PC via TFS?
I've added script to remote environment and run on target PC task via TFS
![image](https://user-images.githubusercontent.com/42540836/45343815-9d202f00-b5aa-11e8-9779-ec6004f1a303.png)

Should I Stop running WAD in the same way?
1. Add script to remote PC
2. Run it on target PC doesn't matter if previous procedures failed, right?
