### ISSUE TITLE
What is the most efficient way to find a WPF Window in a collection of windows?

### ISSUE THREAD

**Issue by brett-burkhart** [Microsoft/WinAppDriver#375]
We have a WPF application where there could be any number of windows opened at any given time.  It is assumed that the AutomationId of each Window will be unique across the application; MainWindow, WindowA1, WindowA2, WindowB, WindowC1, WindowC2, etc. where windows of the same type should be uniquely identified by the context of that window, like an Order ID or something.

Is the best way to find a specific Window, given a specific AutomationId, to iterate over the session's WindowHandles, switching to each window, and then trying to match that window's automation ID? 

     foreach (var windowHandle in session.WindowHandles)
     {
          session.SwitchTo().Window(windowHandle);

          var window = session.FindElementByAccessibilityId(windowID);

          if (window != null)
               return window;
      }

Is this the most efficient way?  How will this perform if you have 5, 10, 20+ windows opened at the same time?

Or will simply calling session.FindElementByAccessibilityId(windowID) query across all opened windows?

**Comment by hassanuz** [comment]
> Is this the most efficient way? How will this perform if you have 5, 10, 20+ windows opened at the same time?

We believe so, and we don't expect to have much degradation in performance as the number windows increases because we only search for top level windows without considering lower level UI elements. Let us know what your findings are! 

> Or will simply calling session.FindElementByAccessibilityId(windowID) query across all opened windows?

It will not query across all opened windows--as the session is tied to the active application top-level window.

**Comment by brett-burkhart** [comment]
Interestingly enough I discovered that I have to wrap the FindElementByAccessibilityId call in a try/catch since it throws an exception which then terminates the FOR loop.  So if you have more than one window handle you need to completely iterate over, the exception would prevent that.  Took me a while to realize this, probably because I'm having to do this in Python and am just learning Python. :(

I have a helper method that runs anytime I need to "find a window" which uses the WebDriverWait class.  The try/catch had to be added to the _is_window_focused().

    def _switch_to_window(self, window_id, timeout=60, poll_frequency=1):
        """
        Attempts to find a window, by automation id, and switch focus to the specified window when the window is found or until the timeout expires.

        :Args:
            - window_id - The window's top level automation id.
            - timeout - Number of seconds before timing out. The default is 60 seconds.
            - poll_frequency - Sleep interval between calls. The default is 1 second.

        :Returns:
            True if the window was focused, otherwise is raises a NoSuchElementException.
        """

        is_focused = WebDriverWait(self._session, timeout, poll_frequency, NoSuchElementException).until(lambda session: self._is_window_focused(self._session, window_id))

        if is_focused:
            return True
        else:
            raise NoSuchElementException("Unable to locate window: %s" % window_id)

    @staticmethod
    def _is_window_focused(session, window_id):
        """
        Attempts to find a window in the handles of all windows within the current session.

        :Args:
            - session - The Appium WebDriver instance of the current session.
            - window_id - The window's top level automation id.

        :Returns:
            True if the window was found, otherwise False.
        """

        for window_handle in session.window_handles:
            session.switch_to.window(window_handle)
            try:
                window = session.find_element_by_accessibility_id(window_id)
                if window is not None:
                    return True
            except:
                # The find_element_by_accessibility_id throws a NoSuchElementException, 
                # so you have to catch the exception to allow the FOR loop to continue
                # iterating over the remaining window handles.
                continue
        else:
            return False
