### ISSUE TITLE
Driver fails to get response when executing command on remote machine and window is minimized

### ISSUE THREAD

**Issue by ashton721** [Microsoft/WinAppDriver#377]
```
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebElement.SendKeys(String text)
```
We are using tfs to deploy tasks on a remote machine. The test process excutes perfectly if you have a remote desktop session open viewing the window at all times(though you may place another window in from of the RDP sesion as long as it is not minimized). As soon as you minimize the window or close an rdp session, the test will fail to get a response when executing command such as send keys, click, clear etc. It seems to perform the first action correctly but then hangs. 
EDIT: Want to clarify that the driver is executing locally but the test case is being executed remotely and thus not attached to a monitor or viewing screen at all times which seems to cause the issue

**Comment by hassanuz** [comment]
Hi @ashton721, how is your session set up? We recommend setting up remote machine as an [interactive session](https://docs.microsoft.com/en-us/vsts/build-release/concepts/agents/agents?view=vsts#account).

**Comment by ashton721** [comment]
Hi @hassanuz We are set up as an interactive session on a user account

**Comment by ashton721** [comment]
@hassanuz  any update on this?

**Comment by hassanuz** [comment]
Hi @ashton721 - please refer to [this ](https://github.com/Microsoft/WinAppDriver/wiki/Continuous-Integration-with-WinAppDriver/dbea583a91f7a39bab9e3cfd975de4edc9d9e2ca) for setting up your TFS build pipelines. We're still growing the Wiki - so if you have any feedback /particular questions that are not already addressed, let me know.
