### ISSUE TITLE
Testing on Windows Mobile devices

### ISSUE THREAD

**Issue by NickAb** [Microsoft/WinAppDriver#38]
Can this driver be used to test UWP apps on Windows 10 Mobile devices or emulators?

There seems to be a few issues that reference mobile devices, like https://github.com/Microsoft/WinAppDriver/issues/32 and https://github.com/Microsoft/WinAppDriver/issues/33. But readme does not mention that the driver can be  used with phones.

**Comment by alakshmi1030** [comment]
Hello @NickAb , Windows 10 Mobile support is on our backlog but currently we do not support it.

**Comment by v-jaebey** [comment]
This would be great as well. There is a UserVoice on it here: https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/16533052-windows-application-driver-support-for-uwp-applica

**Comment by quincycs** [comment]
Can we get an update on the progress?

FYI I saw this https://blogs.windows.com/buildingapps/2016/10/07/introducing-the-windows-device-portal-wrapper-project/#ubEPCjKWj0AY83uZ.97

First thought is the driver program could live within this device portal and that would be the interface across all windows devices (not just mobile)

**Comment by khouzam** [comment]
We're actively looking into this. But don't have any timelines to share yet.

**Comment by mojogeorge** [comment]
Can we expect this enhancement in next few months?

**Comment by schlubbi** [comment]
Can we get an update on when it's planned to support Windows mobile devices?

**Comment by hassanuz** [comment]
Closing Issue - Windows Mobile is not currently on our roadmap.
