### ISSUE TITLE
Getting list of child from a list

### ISSUE THREAD

**Issue by AmitVerma4HP** [Microsoft/WinAppDriver#382]
I am just trying to print all discovered printers name after clicking on "Add a printer or scanner" but xpath - List<WebElement> printerList = **SettingSession.findElementsById**("SystemSettings_Printer_Add_ListView"); does not work. I noticed that FindElementsByAccessibilityId isn't available with Java instead it takes FindElementsById (in bold below)

**Here is the code -** 
    public void DiscoverPrinter(String ptr_name) throws InterruptedException, IOException
	    {   
			// Click on "Add a printer or scanner" & wait until listing is over
			
			try {
				SettingSession.findElementByName("Add a printer or scanner").click();
				}catch(Exception e){
		    	e.printStackTrace();
		    	log.info("Error clicking on -> \"Add a printer or scanner\"");
				}
			log.info("Clicked on \"Add a printer or scanner\"");
			Thread.sleep(500);
			
			do {
				log.info("Printers & Scanners Discovery is IN PROGRESS....");
				Thread.sleep(1000);
				}while(SettingSession.findElementsByName("Searching for printers and scanners").size()!=0);
				
			log.info("Printers & Scanners Discovery COMPLETED");	
							
						
			List<WebElement> printerList = **SettingSession.findElementsById**("SystemSettings_Printer_Add_ListView");
			log.info("Number of Discovered Printers => "+printerList.size());
			for(WebElement sPriner:printerList)
			{
				log.info(sPriner.getText());
			}

Below is the properties details from inspect
![image](https://user-images.githubusercontent.com/22062978/37848833-c67e4048-2e92-11e8-815d-f3012a161f6f.png)

**Comment by AmitVerma4HP** [comment]
Changing SettingSession object from RemoteWebDriver type to WindowsDriver type makes findElementsByAccessibilityId available but still below code is not getting the list of child printers

List<WebElement> printerList = SettingSession.findElementsByAccessibilityId("SystemSettings_Printer_Add_ListView");
			log.info("Number of Discovered Printers => "+printerList.size());
			for(WebElement sPriner:printerList)
			{
				log.info(sPriner.getText());
			}

**Comment by hassanuz** [comment]
Please reopen if you are still experiencing this issue.
