### ISSUE TITLE
Problem with parameters

### ISSUE THREAD

**Issue by ycoliveira** [Microsoft/WinAppDriver#383]
I'm having problems with the output of a test.
In this line of my .feature I try to pass this value "16 3/4" 10K MS700" to a textfield.

    Given that I fill the blanks with "16 3/4" 10K MS700"

But when I execute my test, it replaces the "/" for a ";"  like this: "16 3;4" 10K MS700"

Here's my method

    [Given(@"that I fill the blanks with ""(.*)"""]
    public void DadoThatIFillTheBlanksWithKMS(string sistema)
    {
        App.Session.FindElementByAccessibilityId(PageObjects.ProjetosJuck.CampoSistema).SendKeys(sistema);
    }

winappdriver info 

POST /session/47A9F9BB-8DE2-4D5C-BB3F-E802259FDA97/element/42.2559370/value HTTP/1.1
Accept: application/json, image/png
Content-Length: 32
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"value":["16 3/4\" 10K MS700"]}

HTTP/1.1 200 OK
Content-Length: 63
Content-Type: application/json

{"sessionId":"47A9F9BB-8DE2-4D5C-BB3F-E802259FDA97","status":0}

Why is it changing "/" for a semicolon?

**Comment by timotiusmargo** [comment]
Hi @ycoliveira,

Is there a chance that you are using a non standard US keyboard on your test device? At the moment we are only supporting the standard US keyboard layout as specified below by
https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidelementidvalue

**Comment by ycoliveira** [comment]
Oh, so that was the problem. My keyboard has the Portuguese (Brazilian ABNT) Keyboard Layout but if I change to US keyboard on windows the test works fine. Thanks for the help!
