### ISSUE TITLE
WindowsDriver<WindowsElement> app not getting update pagesource 

### ISSUE THREAD

**Issue by dhaval-mistry** [Microsoft/WinAppDriver#384]
Hi,

I am using winAppDrive to automation WPF application. on start of out application it show loading page and after loading necessary file actual WPF application load after 50 to 60 seconds. 

But when I check pagesource, I only see the source of loading page. 

I am automating USD (unified service desk app) Dynamics 365 APP. 

Please guide me how do I refresh WindowsDriver<WindowsElement> app value with latest page code. 

Regards,
-Dhaval M.

**Comment by dhaval-mistry** [comment]
I have also create desktop session like below 

` DesiredCapabilities appDesktop = new DesiredCapabilities();

            appDesktop.SetCapability("app", "Root");
            WindowsDriver<WindowsElement>  DesktopSession = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), appDesktop);`

planning to iterate thru windows using windowshandlers but I dont see any windowhandler under desktop. 

Can you guide me how can I move from one app window to other app window.

**Comment by dhaval-mistry** [comment]
I was able to solve this issue with below line

app.SwitchTo().Window(app.WindowHandles[0]);

**Comment by timotiusmargo** [comment]
Hi @dhaval-mistry,

I'm glad you figured out the way to switch to the active window. Bear in mind that your solution above is valid only when the application top window appears. In other word, you may need to have a fixed delay (wait) or write a logic to poll for certain UI condition. And just to be clear, WinAppDriver only allows existing application session to switch to another window belonging to the same application (same process Id).

**Comment by ant0908** [comment]
Hi @dhaval-mistry ! I'm also going create automation framework by WinAppDriver for USD app, maybe we can communicate and discuss some issues? 

Hi @timotiusmargo 
Currently, I can't get access to the element when an app was launched by WinAppDriver and got next error(see attached).  
[error.txt](https://github.com/Microsoft/WinAppDriver/files/1903764/error.txt)

**Comment by dhaval-mistry** [comment]
@ant0908 , Glad that I found some partner during USD automation journey

**Comment by ant0908** [comment]
@dhaval-mistry Yeah! Glad to hear! how are you doing with creating automation framework by WinAppDriver for USD app? What app do you use for inspecting UI elements?

**Comment by dhaval-mistry** [comment]
I use, inspect.exe. part of windows sdk 

https://msdn.microsoft.com/en-us/library/windows/desktop/dd318521(v=vs.85).aspx

**Comment by vishnu45** [comment]
@dhaval-mistry 

For how to write xpath expressions, u can refer to the following: https://devhints.io/xpath. To check if the specific xpath expression is correct, one suggestion I have is to use the XPath evaluation plugin for eclipse https://github.com/stoupa91/eclipse-xpath-evaluation-plugin. You can paste in the entire page source and then put in your xpath expression to evaluate.

As to dynamically check for when the new window appears you can easily poll for the existence of the window: example:
while (DesktopSession.findElementByAccessibilityId("automationId").size() == 0) { Thread.sleep(Time in milliseconds); }

Hope this helps!

**Comment by ant0908** [comment]
@dhaval-mistry could you please show how do you fill fields on this form
![1](https://user-images.githubusercontent.com/38247639/38806644-8fe4065a-4182-11e8-9d9f-610fd2d8f9c3.PNG) in your code? 
I have some problem and got an error "An element could not be located on the page using the given search parameters.". Thanks!
