### ISSUE TITLE
Unable to interact with dialog window

### ISSUE THREAD

**Issue by nikolavn** [Microsoft/WinAppDriver#385]
Hello All,

```csharp
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.SetCapability("app", @"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe");
            Thread.Sleep(TimeSpan.FromSeconds(10));
            WindowsDriver<WindowsElement> vsSession = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), capabilities);
            Assert.IsNotNull(vsSession);
            vsSession.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(30);

            vsSession.FindElementByName("File").Click();
            vsSession.FindElementByName("New").Click();
            vsSession.FindElementByName("Project...").Click();

```

I have this code, which opens the New Project dialog/window in Visual Studio. I want to interact with the newly opened window/dialog, but I am unable to swtich to it. I have tried to attach to it as described [here](https://github.com/Microsoft/WinAppDriver/tree/v1.0#attaching-to-an-existing-app-window) and to switch to it using [this](https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/Window.cs#L155) method, yet it doesn't seem to be recognized as a separate window. 

I've also tried the ```vsSession.SwitchTo().ActiveElement();``` method and the "active element" was the Visual Studio main window in the background. 

Any directions on how to handle this would be much appreciated.

I am using Appium 3.0.0.2 and WinAppDriver 1.0.0.

**Comment by nikolavn** [comment]
An update on the issue:
Following code all works fine:
```csharp
var searchBar = vsSession.FindElementByName("Search (Ctrl+E)");
searchBar.SendKeys("ASP.NET Core Web Application");
Assert.AreEqual(searchBar.Text, "ASP.NET Core Web Application");

var frameworkSelector = vsSession.FindElementByName("Framework:");
Assert.IsNotNull(frameworkSelector);

var projectTypesListView = vsSession.FindElementByName("Extensions");
Assert.IsNotNull(projectTypesListView);

var mediumIconsButton = vsSession.FindElementByName("Medium Icons");
Assert.IsNotNull(mediumIconsButton);
```

So individual elements can be found and used. The issue was originally logged because the New Project window itself couldn't be found. 

vsSession.FindElementsByAccessibiltyId("TitleBar") returns 1 element which is the main Visual Studio Window title bar

vsSession.WindowHandles also returns 1 element, which is the handle of the main window. 

[Here](https://www.screencast.com/t/tV51nB3ns) is what **inspect** shows for the New Project Wizard title bar. If you don't consider it's worth further investigation the issue can be closed.

**Comment by timotiusmargo** [comment]
Hi @nikolavn,

Thank you for the update with all the great information above. As shown in the UI tree snapshot captured by `inspect.exe` that you attach above, the **New Project** window in Microsoft Visual Studio is actually a child window of the **VisualStudioMainWindow**. Therefore, the session cannot be switched to it as it is not a top level window as you observed. Your observation on the single window handle being returned is also correct and consistent with the actual UI tree.

The way you access UI element you are interested in your dialog above makes sense and should work without any issue. In case you want to limit the scope of finding element(s) within your dialog, you can trigger a search of element(s) within a given element as shown in the examples below:
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/ElementElement.cs#L41
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/ElementElements.cs#L39

Hope this helps :)

**Comment by venkat2048** [comment]
Hi @timotiusmargo,

I am trying to find a windows dialog box from Internet Explorer .
I have tried to switch this window with window handle (but as you have mentioned vsts example similarly its an child for the Internet explorer window hence its not a top level window ) I cannot perform this action.
is there any way to handle this dialog box through winappdriver 
Any help on how to handle this would be much appreciated.
Thanks

**Comment by Shirisha8812** [comment]
Hi , I am getting the same error. I am automating windows application using win app driver  with Java. I am not able to locate the newly opened window through name, xpath. There is no automation id. I can still see the name with inspect tool but I can't move to the new window. When I check with windowhandles I am getting only one window. Can someone help me on this. 
Thanks

**Comment by Shakevg** [comment]
@Shirisha8812 Did you try to create a root session and create a session for a new window or attach to new windows by process name?
https://github.com/microsoft/WinAppDriver/tree/v1.0#creating-a-desktop-session
