### ISSUE TITLE
With Movies & TV App in full screen mode, not able to locate any element on App

### ISSUE THREAD

**Issue by nmohamedmahir** [Microsoft/WinAppDriver#388]
Hi,
I am trying to automate Movies & TV UWP App using Winappdriver in Python. I could launch the app and can locate the elements while video is playing in windowed mode.
When i click on FullScreen mode, i could not locate any elements on the app further. This renders me with no control on the application.
I tried find_element_by_name, find_element_by_class_name and other types also. 
I also tried to find elements with tag names but nothing worked.
Can you please let me know if this is a limitation or I'm trying wrong.

Thanks,
Mohamed Mahir N

**Comment by timotiusmargo** [comment]
Hello @nmohamedmahir,

Can you check your test script to make sure that it is not confined in an out-of-date UI tree element? When you switch to full screen mode, the **Movies & TV** application UI tree updates and previously located UI element may no longer be valid. At this point you would need to re-locate all the UI elements based on the current application state.

Below is a snippet of code I quickly put together that you can easily paste in [Session sample test](https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/Session.cs#L83) for a quick verification. This code successfully launches the **Movies & TV** application, play a trailer, switch to full screen, and trigger the next trailer using a UI control in full screen mode. This sample demonstrates that Windows Application Driver can interact with the **Movies & TV** application in both full screen and normal mode.
```c#
[TestMethod]
public void CreateSession_MoviesTV()
{
    DesiredCapabilities appCapabilities = new DesiredCapabilities();
    appCapabilities.SetCapability("app", "Microsoft.ZuneVideo_8wekyb3d8bbwe!Microsoft.ZuneVideo");
    session = new WindowsDriver<WindowsElement>(new Uri(CommonTestSettings.WindowsApplicationDriverUrl), appCapabilities);
    Assert.IsNotNull(session);
    Assert.IsNotNull(session.SessionId);
    Assert.AreEqual("Movies & TV", session.Title);
    Thread.Sleep(TimeSpan.FromSeconds(3));

    // Navigate to Movie Trailers view
    session.FindElementByAccessibilityId("Command_NavigateToTrailerGalleryCommand").Click();
    Thread.Sleep(TimeSpan.FromSeconds(3));

    // Play the first Movie Trailer
    var trailersListView = session.FindElementByAccessibilityId("ModuleListView");
    var trailers = trailersListView.FindElementsByClassName("ListViewItem");          
    if (trailers.Count > 0)
    {
        trailers[0].Click();
        Thread.Sleep(TimeSpan.FromSeconds(3));
    }
    else
    {
        Assert.Fail();
    }

    // Trigger the full screen mode
    session.FindElementByAccessibilityId("FullWindowButton").Click();
    Thread.Sleep(TimeSpan.FromSeconds(3));

    // Verify that the full screen view is interactable
    var fullWindow = session.FindElementByClassName("FullWindowMedia");
    Assert.IsNotNull(fullWindow);
    Assert.IsNotNull(fullWindow.FindElementByName("Video details"));

    // Interact with the full screen control to play the next Movie Trailer
    fullWindow.FindElementByName("Next video").Click();
    Thread.Sleep(TimeSpan.FromSeconds(3));
}
```
