### ISSUE TITLE
Select items in WinForms ComboBox

### ISSUE THREAD

**Issue by brett-burkhart** [Microsoft/WinAppDriver#389]
I've been struggling to automate a **WinForms** ComboBox control.  I've looked at the examples in the [UWP ComboBox](https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/UWPControls/ComboBox.cs#L48) file, but am still unable to get it working.

When I look in Inspect, I first see the ComboBox "Minimum Execution Size" along with the "Open" button to open the dropdown panel.

![image](https://user-images.githubusercontent.com/33559459/38054515-35d54c6e-32a5-11e8-911f-a82717a6ed40.png)

With Inspect still running I click the ComboxBox and the dropdown panel opens.  The automation tree continues to look the same.  When I move the mouse down over the panel then Inspect refreshes and now I see all the ComboBox items.

![image](https://user-images.githubusercontent.com/33559459/38054646-8e8131de-32a5-11e8-8c23-276e4968b496.png)

Now, when I try to replicate this same thing in code, sorry it's in Python...

	combobox = self._session.find_element_by_accessibility_id("_strategyComboBox")
  	combobox.click()
  	time.sleep(1)

At this point I assume the automation tree is based on the first image.  Any kind of "find by" calls from the context of the combobox element fails.

I then tried moving the mouse over the panel to hopefully trigger the same side effect I noticed in Inspect; refreshing of the automation tree.

 	ActionChains(self._session).move_by_offset(0, 20).perform()

From here I tried multiple "find by" operations which yielded no results.  The find by calls were from the session object or the combobox element:

	find_element_by_name("FOO") 
	find_element_by_class_name("ComboLBox")
	find_element_by_tag_name("list")
	find_elements_by_tag_name("list item")

None of these calls worked.  Here is the output from WAD from find_element_by_name

	POST /session/233BA645-49BD-42A7-B3F0-7ACE523162C7/element HTTP/1.1
	Accept: application/json
	Accept-Encoding: identity
	Connection: close
	Content-Length: 112
	Content-Type: application/json;charset=UTF-8
	Host: 127.0.0.1:4723
	User-Agent: Python http auth

	HTTP/1.1 200 OK
	Content-Length: 96
	Content-Type: application/json

	{"sessionId":"233BA645-49BD-42A7-B3F0-7ACE523162C7","status":0,"value":{"ELEMENT":"42.1640046"}}

	==========================================
	POST /session/233BA645-49BD-42A7-B3F0-7ACE523162C7/element/42.1640046/click HTTP/1.1
	Accept: application/json
	Accept-Encoding: identity
	Connection: close
	Content-Length: 73
	Content-Type: application/json;charset=UTF-8
	Host: 127.0.0.1:4723
	User-Agent: Python http auth

	{"sessionId": "233BA645-49BD-42A7-B3F0-7ACE523162C7", "id": "42.1640046"}
	HTTP/1.1 200 OK
	Content-Length: 63
	Content-Type: application/json

	{"sessionId":"233BA645-49BD-42A7-B3F0-7ACE523162C7","status":0}

	==========================================
	POST /session/233BA645-49BD-42A7-B3F0-7ACE523162C7/moveto HTTP/1.1
	Accept: application/json
	Accept-Encoding: identity
	Connection: close
	Content-Length: 82
	Content-Type: application/json;charset=UTF-8
	Host: 127.0.0.1:4723
	User-Agent: Python http auth

	{"sessionId": "233BA645-49BD-42A7-B3F0-7ACE523162C7", "xoffset": 0, "yoffset": 20}
	HTTP/1.1 200 OK
	Content-Length: 63
	Content-Type: application/json

	{"sessionId":"233BA645-49BD-42A7-B3F0-7ACE523162C7","status":0}

	==========================================
	POST /session/233BA645-49BD-42A7-B3F0-7ACE523162C7/element/42.1640046/element HTTP/1.1
	Accept: application/json
	Accept-Encoding: identity
	Connection: close
	Content-Length: 107
	Content-Type: application/json;charset=UTF-8
	Host: 127.0.0.1:4723
	User-Agent: Python http auth

	{"using": "name", "sessionId": "233BA645-49BD-42A7-B3F0-7ACE523162C7", "id": "42.1640046", "value": "FOO"}
	HTTP/1.1 404 Not Found
	Content-Length: 139
	Content-Type: application/json

	{"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}

Or the results from search by class name

	POST /session/3E94DCFC-9CD5-456F-82B5-082D84B0C54B/element/42.2099844/click HTTP/1.1
	Accept: application/json
	Accept-Encoding: identity
	Connection: close
	Content-Length: 73
	Content-Type: application/json;charset=UTF-8
	Host: 127.0.0.1:4723
	User-Agent: Python http auth

	{"sessionId": "3E94DCFC-9CD5-456F-82B5-082D84B0C54B", "id": "42.2099844"}
	HTTP/1.1 200 OK
	Content-Length: 63
	Content-Type: application/json

	{"sessionId":"3E94DCFC-9CD5-456F-82B5-082D84B0C54B","status":0}

	==========================================
	POST /session/3E94DCFC-9CD5-456F-82B5-082D84B0C54B/moveto HTTP/1.1
	Accept: application/json
	Accept-Encoding: identity
	Connection: close
	Content-Length: 82
	Content-Type: application/json;charset=UTF-8
	Host: 127.0.0.1:4723
	User-Agent: Python http auth

	{"sessionId": "3E94DCFC-9CD5-456F-82B5-082D84B0C54B", "xoffset": 0, "yoffset": 20}
	HTTP/1.1 200 OK
	Content-Length: 63
	Content-Type: application/json

	{"sessionId":"3E94DCFC-9CD5-456F-82B5-082D84B0C54B","status":0}

	==========================================
	POST /session/3E94DCFC-9CD5-456F-82B5-082D84B0C54B/element HTTP/1.1
	Accept: application/json
	Accept-Encoding: identity
	Connection: close
	Content-Length: 98
	Content-Type: application/json;charset=UTF-8
	Host: 127.0.0.1:4723
	User-Agent: Python http auth

	{"using": "class name", "sessionId": "3E94DCFC-9CD5-456F-82B5-082D84B0C54B", "value": "ComboLBox"}
	HTTP/1.1 404 Not Found
	Content-Length: 139
	Content-Type: application/json

	{"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}

Nothing seems to work.  I'm sure I could simply move the mouse down a predetermined y-offset, but I really need to be able to do something similar to the example provided because the ComboBox items is not always the same.  I need ultimately this to work:

	combobox = self._session.find_element_by_accessibility_id("_strategyComboBox")
  	combobox.click()
	combobox.find_element_by_name("FOO").click()

Any ideas??  What I am missing??

**Comment by timotiusmargo** [comment]
Hi @brett-burkhart,

Thanks for the detailed explanation of the issue you encounter. I noticed that you are performing nested search from the `_strategyComboBox` you located in the first place. Assuming that your script has successfully expanded the **ComboBox** you are interested in and update the UI tree, you may want to re-locate the `_strategyComboBox` element as it is possible for the original element you located previously is no longer the same instance. One quick thing that you can try is to get the script to the point that the **ComboBox** is successfully expanded, then call the [session PageSource](https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/Source.cs#L39) to see a snapshot of the UI tree that you can locate at that instance in XML format.

**Comment by brett-burkhart** [comment]
@timotiusmargo, thanks for the feedback.  So I just tried searching for the combobox element again...

        combobox = self.find_element_by_accessibility_id("_strategyComboBox")
        combobox.click()

        time.sleep(2)

        ActionChains(self._session).move_by_offset(0, 20).perform()

        time.sleep(2)

        combobox1 = self.find_element_by_accessibility_id("_strategyComboBox")

        print combobox
        print combobox1

...and they are the same instance.

       <appium.webdriver.webelement.WebElement (session="DF4D884A-051A-4533-BC5A-A9CBBF1C27C0", element="42.131878")>
       <appium.webdriver.webelement.WebElement (session="DF4D884A-051A-4533-BC5A-A9CBBF1C27C0", element="42.131878")>

I was also not able to find an element by name from the combobox1 context either.  I will try the PageSource next.

**Comment by brett-burkhart** [comment]
Ok, so after opening the combobox dropdown panel, moving the mouse down 20px, and fetching the same source...it's not showing the same tree that I see in Inspect.  It looks like it's still the tree in the first image I posted.  Hmmm...

`     <Pane AcceleratorKey="" AccessKey="" AutomationId="_strategyPanel" ClassName="WindowsForms10.Window.8.app.0.2df101_r9_ad2" FrameworkId="WinForm" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="pane" Name="Minimum Execution Size" Orientation="None" ProcessId="19312" RuntimeId="42.198948" x="102" y="394" width="406" height="28">
          <Button AcceleratorKey="" AccessKey="" AutomationId="_suggestStrategiesButton" ClassName="WindowsForms10.BUTTON.app.0.2df101_r9_ad2" FrameworkId="WinForm" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="button" Name="Get Ranking..." Orientation="None" ProcessId="19312" RuntimeId="42.1574458" x="388" y="395" width="100" height="24" />
          <Button AcceleratorKey="" AccessKey="" AutomationId="_strategyHelpButton" ClassName="WindowsForms10.BUTTON.app.0.2df101_r9_ad2" FrameworkId="WinForm" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="button" Name="" Orientation="None" ProcessId="19312" RuntimeId="42.525894" x="360" y="395" width="22" height="22" />
          <ComboBox AcceleratorKey="" AccessKey="" AutomationId="_strategyComboBox" ClassName="WindowsForms10.COMBOBOX.app.0.2df101_r9_ad2" FrameworkId="WinForm" HasKeyboardFocus="True" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="combo box" Name="Minimum Execution Size" Orientation="None" ProcessId="19312" RuntimeId="42.1509368" x="168" y="395" width="191" height="22">
               <Text AcceleratorKey="" AccessKey="" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="True" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="True" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="text" Name="Minimum Execution Size" Orientation="None" ProcessId="19312" RuntimeId="" x="-97" y="-197" width="168" height="16" />
               <Button AcceleratorKey="" AccessKey="Alt+Down Arrow" AutomationId="" ClassName="" FrameworkId="" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="button" Name="Close" Orientation="None" ProcessId="19312" RuntimeId="" x="343" y="396" width="15" height="20" />
          </ComboBox>
          <Text AcceleratorKey="" AccessKey="" AutomationId="_strategyLabel" ClassName="WindowsForms10.STATIC.app.0.2df101_r9_ad2" FrameworkId="WinForm" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="False" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="text" Name="Strategy" Orientation="None" ProcessId="19312" RuntimeId="42.198834" x="107" y="398" width="46" height="17" />
     </Pane>`

**Comment by brett-burkhart** [comment]
@timotiusmargo, okay...thinking out of the box, I was able to make this work.  I basically focus the combobox control, send the DOWN ARROW key to the control, then fetch the Text value and compare against the value I want to select.  I do this in a WHILE loop so it can cycle through all the items.  

    combobox = self.find_element_by_accessibility_id(AutomationId.SINGLE_ORDER_ENTRY_WINDOW_STRATEGY_COMBOBOX)

    while True:
        if self.strategy == value:
            break
        else:
            ActionChains(self._session).send_keys_to_element(combobox, Keys.ARROW_DOWN).perform()

Now this works just fine, it's not ideal, but it works for now.  Obviously I don't know how many items there are so right now this could do into an infinite loop.  I plan to update it to add a simple counter to prevent say more than 10 or so SendKeys() calls before probably raising an exception that the item could not be selected.

I'd still like to know why the automation tree is not updating or what the issues are, as well as a better approach to this.  Thanks!

**Comment by tobindh** [comment]
On 1.1, I can confirm the behavior - I'm also having problems trying to automate a ComboBox in WinForms.

After the ComboBox is selected to get the dropdown list, the page source is not updating with the list or list items, even when finding the element again after opening the list.  With the list open, the page source still only contains the text and button, even though Inspect.exe shows the list and items.

**Comment by hassanuz** [comment]
Hi @tobindh,

In older WinForms applications, the ComboBox would pop-up as a top-level window that is not parented by the same application UI tree, and as such it would be advisable to use a [desktop session](https://github.com/Microsoft/WinAppDriver/wiki/Frequently-Asked-Questions/289a8b325d3ddab9f08b4398c49163a9a136f607#when-and-how-to-create-a-desktop-session) to locate the top-level window to interact with. 

Marking this issue as closed. Please create a new ticket if you have any other questions! 

Thanks

**Comment by YouWhy** [comment]
@hassanuz  @timotiusmargo  I am seeing this issue.  Refer to issue: https://github.com/Microsoft/WinAppDriver/issues/679

**Comment by mbharath12** [comment]
Hi @hassanuz ,@VijayHugar, @timotiusmargo,

tried above solution popup toplevel session
but its not working

**Comment by mattboroi** [comment]
@kat-y @DHowett @hassanuz realizing you have a number of priorities if there's an opportunity to re-open this I would be happy to supply additional details regarding the same experience mentioned by others. Respectfully, the closed message does not appear to reflect on the majority of user experience reports and I can attest to the same.
