### ISSUE TITLE
Run outlook

### ISSUE THREAD

**Issue by NikitaTurakhia** [Microsoft/WinAppDriver#392]
Not able to click on anything after opening outlook -
This is what I am using for code :
  private const string WindowsApplicationDriverUrl = "http://127.0.0.1:4723";
        private const string CalculatorAppId = @"C:\Program Files\Microsoft Office\root\Office16\OUTLOOK.EXE";

        protected static WindowsDriver<WindowsElement> session;

        public static void Setup(TestContext context)
        {
            // Launch Calculator application if it is not yet launched
            if (session == null)
            {
                // Create a new session to bring up an instance of the Calculator application
                // Note: Multiple calculator windows (instances) share the same process Id
                DesiredCapabilities appCapabilities = new DesiredCapabilities();
                appCapabilities.SetCapability("app", CalculatorAppId);
                appCapabilities.SetCapability("deviceName", "LAPTOP-NIKITA");
                session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities);
                session.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(1.5));
                Assert.IsNotNull(session);

                // Set implicit timeout to 1.5 seconds to make element search to retry every 500 ms for at most three times
                session.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(1.5));
            }
        }

and in my next class I am trying yo select a tab 

 public class ScenarioStandard : CalculatorSession
    {
        private static WindowsElement header;
        private static WindowsElement calculatorResult;

        [TestMethod]
        public void Addition()
        {
            // Find the buttons by their names and click them in sequence to peform 1 + 7 = 8
            session.FindElementByName("View").Click();
       
        }
}

Getting error like this :  {"status":23,"value":{"error":"no such window","message":"Currently selected window has been closed"}}

**Comment by timotiusmargo** [comment]
Hello @NikitaTurakhia,

Microsoft Outlook application in general displays a splash screen on the startup. As a splash screen is indeed a valid top level application window, Windows Application Driver treats it as the main window that you can indeed automate and test. The failure you saw above is correctly telling you that the splash screen (window) was already closed as the it went away after the actual main window appears.

What you can do at that point is simply switch your session to the main application window. For example:
```c#
DesiredCapabilities appCapabilities = new DesiredCapabilities();
appCapabilities.SetCapability("app", YourAppId);
WindowsDriver<WindowsElement> session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities);
Assert.IsNotNull(session);

// Identify the current window handle. You can check through inspect.exe which window this is.
var currentWindowHandle = session.CurrentWindowHandle;

// Wait for 5 seconds or however long it is needed for the right window to appear/for the splash screen to be dismissed
Thread.Sleep(TimeSpan.FromSeconds(5));

// Return all window handles associated with this process/application.
// At this point hopefully you have one to pick from. Otherwise you can
// simply iterate through them to identify the one you want.
var allWindowHandles = session.WindowHandles;

// Assuming you only have only one window entry in allWindowHandles and it is in fact the correct one,
// switch the session to that window as follows. You can repeat this logic with any top window with the same
// process id (any entry of allWindowHandles)
session.SwitchTo().Window(allWindowHandles[0]);
```

Also have a look at issue #213 that has a different workaround for the same outcome. Hope this helps.

**Comment by okver2** [comment]
This workaround working every other time. Not possible to rely on it. I tried it using both Java and C#  and behavior is the same.  Will this issue be fixed soon?

**Comment by hassanuz** [comment]
Hi @okver2,

Can you describe the behavior for when it doesn't work?

**Comment by kazztr** [comment]
This works, thanks

**Comment by Kamilbrd** [comment]
Hello,

Also trying to automate outlook and the workaround does sometimes work but mostly fails. Don't know if this is the same issue mentioned above but for me  WindowHandles causes a 500 Internal Error (most of the times). Tried restarting the driver or running as admin did not work. The code is in c# using Visual Studio 2017 and run on Windows 10:

` var capabilities = new DesiredCapabilities();
                  capabilities.SetCapability("app", OutlookAppId);
                _driver = new WindowsDriver<WindowsElement>(new Uri ("http://127.0.0.1:4723"), capabilities);
                Thread.Sleep(TimeSpan.FromSeconds(20));
                var allWindowHandles = _driver.WindowHandles; 
                _driver.SwitchTo().Window(allWindowHandles[0]);`

Error from cmd: 

`==========================================
POST /session HTTP/1.1
Accept: application/json, image/png
Connection: Keep-Alive
Content-Length: 129
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723


HTTP/1.1 200 OK
Content-Length: 177
Content-Type: application/json

{"sessionId":"F0FBE301-BE1B-4724-B01A-310DC9269C6E","status":0,"value":{"app":"C:\\Program Files (x86)\\Microsoft Office\\root\\Office16\\OUTLOOK.EXE","platformName":"Windows"}}


==========================================
GET /session/F0FBE301-BE1B-4724-B01A-310DC9269C6E/window_handles HTTP/1.1
Accept: application/json, image/png
Host: 127.0.0.1:4723


HTTP/1.1 500 Internal Error`

The error message doesn't say much unfortunately and I was not able to find anything that would influence this. 
Any help much appreciated.
Thank you.

**Comment by timotiusmargo** [comment]
Hi @okver2, @Kamilbrd,

Waiting for a fixed amount of time until the splash screen is dismissed and the main window appears as I suggested was meant to be an example of how your test can switch to the main application. It was never meant to be used as a permanent solution to handle your application startup. However, you can easily replace the fixed time wait code with a simple loop that keep checking until the condition you expect finally takes place. As an example, below is a startup code for Microsoft Excel that will use **DesktopSession** to locate the main window once it appears and create a new session from it.

```c#
DesiredCapabilities appCapabilities = new DesiredCapabilities();
appCapabilities.SetCapability("app", @"C:\Program Files (x86)\Microsoft Office\root\Office16\EXCEL.EXE");
session = new WindowsDriver<WindowsElement>(new Uri(CommonTestSettings.WindowsApplicationDriverUrl), appCapabilities);
Assert.IsNotNull(session);
Assert.IsNotNull(session.SessionId);

if (session.Title != "Excel")
{
    // Create a desktop session to locate the Excel main window that appears after the splash screen
    DesiredCapabilities desktopCapabilities = new DesiredCapabilities();
    desktopCapabilities.SetCapability("app", "Root");
    var desktopSession = new WindowsDriver<WindowsElement>(new Uri(CommonTestSettings.WindowsApplicationDriverUrl), desktopCapabilities);

    for (int attempt = 0; attempt < 10; attempt++)
    {
        try
        {
            // Attempt to search for Excel main window using the desktop session
            var ExcelWindow = desktopSession.FindElementByName("Excel");
            var ExcelTopLevelWindowHandle = ExcelWindow.GetAttribute("NativeWindowHandle");
            ExcelTopLevelWindowHandle = (int.Parse(ExcelTopLevelWindowHandle)).ToString("x"); // Convert to Hex

            // Create session by attaching to Excel top level window
            appCapabilities = new DesiredCapabilities();
            appCapabilities.SetCapability("appTopLevelWindow", ExcelTopLevelWindowHandle);
            session = new WindowsDriver<WindowsElement>(new Uri(CommonTestSettings.WindowsApplicationDriverUrl), appCapabilities);

            if (session != null) break;
        }
        catch { }

        Thread.Sleep(TimeSpan.FromSeconds(3));
    }
}

Assert.IsNotNull(session);
Assert.IsTrue(session.Title == "Excel");
```
