### ISSUE TITLE
[WinAppDriver] [STDOUT] {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}

### ISSUE THREAD

**Issue by githubdhina** [Microsoft/WinAppDriver#393]
When clicking on an element, an unknown error occurred.
The element is located without any issues but while clicking on it, the following error appears

WinApp Driver Version: 1.0
Appium Version: 1.7.2

MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/1469e3b9-7033-4488-ad71-e8e92346fd86/touch/perform] to [POST http://127.0.0.1:4725/wd/hub/session/8E09AFF0-E6B3-4B04-92EF-CBE972952D2C/touch/perform] with body: {"actions":[{"action":"press","options":{"element":"42.2100174.2.1392"}},{"action":"wait","options":{"ms":1}},{"action":"release"}]}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session/8E09AFF0-E6B3-4B04-92EF-CBE972952D2C/touch/perform HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 132
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4725
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"actions":[{"action":"press","options":{"element":"42.2100174.2.1392"}},{"action":"wait","options":{"ms":1}},{"action":"release"}]}
[WinAppDriver] [STDOUT] HTTP/1.1 500 Internal Error
[WinAppDriver] [STDOUT] Content-Length: 133
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[MJSONWP] Encountered internal error running command:  {"w3cStatus":400,"jsonwp":{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}} ProxyRequestError: Could not proxy command to remote server. Original error: 500 - {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
    at JWProxy.proxy$ (C:\Users\AppData\Local\appium-desktop\app-1.5.0\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:152:13)
    at tryCatch (C:\Users\AppData\Local\appium-desktop\app-1.5.0\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\AppData\Local\appium-desktop\app-1.5.0\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\AppData\Local\appium-desktop\app-1.5.0\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\AppData\Local\appium-desktop\app-1.5.0\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)

**Comment by timotiusmargo** [comment]
Hi @githubdhina,

Thanks for bringing this issue. The `session/:sessionId/touch/perform` API endpoint is not currently supported in Windows Application Driver. A list of currently supported API endpoint can be found below:
https://github.com/Microsoft/WinAppDriver/tree/v1.0#supported-apis.

Would you consider using the following API instead to perform the touch action in your test scenario?
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/TouchClick.cs#L40

For a more involved touch action, you can also use the following API endpoint below:
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/TouchDownMoveUp.cs#L75
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/TouchDownMoveUp.cs#L48

**Comment by hassanuz** [comment]
Yes, you should be able to hit the API endpoints @timotiusmargo listed above through Appium.

**Comment by jsingh-qualitrol** [comment]
@timotiusmargo @hassanuz I am using following:
WinAppDriver -v0.9
Appium Version - 1.7.1
My application launches but doesn't perform any further action..

[Appium] Welcome to Appium v1.7.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"D:\\SSE_Build\\Release\\SmartSUB_UI\\SSEUiClient\\SSE.UI.Client.exe","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"app":"D:\\SSE_Build\\Release\\SmartSUB_UI\\SSEUiClient\\SSE.UI.Client.exe","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{},"alwaysMatch":{"platformName":"Windows"},"firstMatch":[]}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"D:\\SSE_Build\\Release\\SmartSUB_UI\\SSEUiClient\\SSE.UI.Client.exe","platformName":"Windows","deviceName":"WindowsPC"},{},{"desiredCapabilities":{"app":"D:\\SSE_Build\\Release\\SmartSUB_UI\\SSEUiClient\\SSE.UI.Client.exe","platformName":"Windows","deviceName":"WindowsPC"},"requiredCapabilities":{},"alwaysMatch":{"platformName":"Windows"},"firstMatch":[]}]
[BaseDriver] Event 'newSessionRequested' logged at 1528872515384 (12:18:35 GMT+0530 (India Standard Time))
[Appium] Creating new WindowsDriver (v0.5.0) session
[Appium] Capabilities:
[Appium]   app: 'D:\\SSE_Build\\Release\\SmartSUB_UI\\SSEUiClient\\SSE.UI.Client.exe'
[Appium]   platformName: 'Windows'
[Appium]   deviceName: 'WindowsPC'
[BaseDriver] The following capabilities were provided, but are not recognized by appium: app.
[BaseDriver] Session created with session id: 9ae4dd67-cad6-47f8-a01a-333c7a9cd331
[WinAppDriver] Verifying WinAppDriver is installed with correct checksum
[WinAppDriver] WinAppDriver changed state to 'starting'
[WinAppDriver] Killing any old WinAppDrivers on same port, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"4724 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I winappdriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
[WinAppDriver] No old WinAppDrivers seemed to exist
[WinAppDriver] Spawning winappdriver with: undefined 4724/wd/hub
[WinAppDriver] [STDOUT] Windows Application Driver Beta listening for requests at: http://127.0.0.1:4724/wd/hub
[WinAppDriver] WinAppDriver changed state to 'online'
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:4724/wd/hub/session] with body: {"desiredCapabilities":{"app":"D:\\SSE_Build\\Release\\SmartSUB_UI\\SSEUiClient\\SSE.UI.Client.exe","platformName":"Windows","deviceName":"WindowsPC"}}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] Address 'http://127.0.0.1:4724/wd/hub' is already in use
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] Failed to initialize: 0x80004005
[WinAppDriver] WinAppDriver exited unexpectedly with code 2147500037, signal null
[WinAppDriver] WinAppDriver changed state to 'stopped'
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session HTTP/1.1
[WinAppDriver] [STDOUT] Accept: */*
[WinAppDriver] [STDOUT] Connection: keep-alive
[WinAppDriver] [STDOUT] Content-Length: 151
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] SessionManager - Creating session
[WinAppDriver] [STDOUT] SessionManager - WinAppDriver succeeded loading MitaBroker
[WinAppDriver] [STDOUT] HTTP/1.1 500 Internal Error
[WinAppDriver] [STDOUT] Content-Length: 133
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[WinAppDriver] Deleting WinAppDriver session
[MJSONWP] Encountered internal error running command:  {"jsonwp":{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}} ProxyRequestError: Could not proxy command to remote server. Original error: 500 - {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
    at JWProxy.proxy$ (C:\Users\USSETest01\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:152:13)
    at tryCatch (C:\Users\USSETest01\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\USSETest01\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\USSETest01\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\USSETest01\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 5450 ms - 152

**Comment by hassanuz** [comment]
@jsingh-qualitrol,

Can you try the using the latest version of WinAppDriver? If the issue persists, please create a new thread. 

Thank you!

**Comment by jsingh-qualitrol** [comment]
@hassanuz 
I had tried to upgrade the lastest version but Appium 1.7.1 only works with 0.9version.

**Comment by hassanuz** [comment]
The latest Appium/WinAppDriver version should have solved this. Please create a new ticket if issue persists on those versions.
