### ISSUE TITLE
Selenium hub+Appium+winappdriver exits unexpectedly

### ISSUE THREAD

**Issue by pnagaraja1** [Microsoft/WinAppDriver#395]
Hello,

I am trying to run the grid setup in my local to run test on calculator app. It fails with the error given below.

[WinAppDriver] WinAppDriver exited unexpectedly with code 3221225477, signal null
[debug] [WinAppDriver] WinAppDriver changed state to 'stopped'

Steps followed:
1. Started the hub 
java -jar .\selenium-server-standalone-3.11.0.jar -role hub
2. Started the node
appium --nodeconfig '.\nodeconfig.json'

Nodeconfig.json: 
============
{
  "capabilities":
      [
        {
          "browserName": "",
          "maxInstances": 2,
          "platform":"WINDOWS",
      	"platformName": "WINDOWS",
          "deviceName": "WindowsPC",
          "app": "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"
        }
      ],
  "configuration":
  {
        "cleanUpCycle":2000, 
        "timeout":30000, 
        "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
        "url":"http://localhost:4723/wd/hub",
        "host":"localhost",
        "port":4723, 
        "maxSession":3,
        "register":true,
        "registerCycle":10000,
        "hub": "http://localhost:4444/grid/register",
        "hubPort":4444,
        "hubHost":"localhost",
        "nodeTimeout":120, 
        "nodePolling":2000
  }
}

However providing the "url" of other remote machines, it works. In local this error exists.

WinAppDriver version: 1.0
Appium version: 1.7.2
Appium-windows-driver: 1.0.0

Running the test gives below logs.

Debug log: 
=================
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App
","browserName":"","deviceName":"WindowsPC","maxInstances":1,"platform":"WINDOWS","platformName":"windows","server:CONFI
G_UUID":"8d9e4b12-3c9d-45d7-920d-a98f6e9827ca"},null,{"desiredCapabilities":{"app":"Microsoft.WindowsCalculator_8wekyb3d
8bbwe!App","browserName":"","deviceName":"WindowsPC","maxInstances":1,"platform":"WINDOWS","platformName":"windows","ser
ver:CONFIG_UUID":"8d9e4b12-3c9d-45d7-920d-a98f6e9827ca"},"firstMatch":[{"browserName":"","platformName":"windows","serve
r:CONFIG_UUID":"8d9e4b12-3c9d-45d7-920d-a98f6e9827ca"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1523429254483 (12:17:34 GMT+0530 (India Standard Time))
[Appium] Merged W3C capabilities {"desiredCapabilities":{"app":"Microsoft.Window... into desiredCapabilities object {"ap
p":"Microsoft.WindowsCalculator_8wekyb3d8bb...
[Appium] Creating new WindowsDriver (v1.0.0) session
[Appium] Capabilities:
[Appium]   app: Microsoft.WindowsCalculator_8wekyb3d8bbwe!App
[Appium]   browserName:
[Appium]   deviceName: WindowsPC
[Appium]   maxInstances: 1
[Appium]   platform: WINDOWS
[Appium]   platformName: windows
[Appium]   server:CONFIG_UUID: 8d9e4b12-3c9d-45d7-920d-a98f6e9827ca
[BaseDriver] The following capabilities were provided, but are not recognized by appium: app, browserName, maxInstances,
 platform, server:CONFIG_UUID.
[BaseDriver] Session created with session id: fe6dcc80-17ef-4f8c-affb-a6cc517eb384
[WinAppDriver] You must use WinAppDriver version 1.0
[WinAppDriver] Verifying WinAppDriver version 1.0 is installed via comparing the checksum.
[debug] [WinAppDriver] WinAppDriver changed state to 'starting'
[WinAppDriver] Killing any old WinAppDrivers on same port, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| f
indstr /R /C:"4724 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I winappdriver.exe`) do (IF NO
T %b=="" TASKKILL /F /PID %a))
[WinAppDriver] No old WinAppDrivers seemed to exist
[WinAppDriver] Spawning winappdriver with: 4724/wd/hub
**[WinAppDriver] WinAppDriver exited unexpectedly with code 3221225477, signal null
[debug] [WinAppDriver] WinAppDriver changed state to 'stopped'**
[HTTP] --> GET /wd/hub/status {}

**Comment by brendanconnolly** [comment]
Any update on this? My tests execute without issue when running WinAppDriver directly but I cannot run after attempting to run in a grid.

**Comment by pnagaraja1** [comment]
Still facing the same issue. No updates yet.

**Comment by drewcoo** [comment]
3221225477 is 0xc0000005 which is STATUS_ACCESS_VIOLATION from ntstatus.h among other things. So it's probably an AV bubbling up from who-knows-where in the OS. You may have some luck if you try to repro while running procmon and looking for the root cause of an AV.
https://docs.microsoft.com/en-us/sysinternals/downloads/procmon

Sorry I can't offer more help. I just happened to see this while trying to solve my own problem and thought that info might help. Good luck!
