### ISSUE TITLE
WinAppDriver Drag and Drop example for Java

### ISSUE THREAD

**Issue by guloz** [Microsoft/WinAppDriver#399]
I am having trouble with the drag and drop functionality. It looks like the element is being picked up but then not moved with the mouse as a result our tests fail.
Do you have an example code in java?

**Comment by hassanuz** [comment]
Hi @guloz,

There is a sample for this already on [our C# code. ](https://github.com/Microsoft/WinAppDriver/blob/8bb91f06ef9cbc798c88099a586c15d74fd17870/Tests/WebDriverAPI/Mouse.cs#L117).
