### ISSUE TITLE
Does this WinAppDriver Support WinPhone now?

### ISSUE THREAD

**Issue by EthanJiang** [Microsoft/WinAppDriver#4]
Hello

I am looking at the video https://channel9.msdn.com/Events/Build/2016/P499 and I am planning to try the WinappDriver. 

but as it said, next step will support Mobile. but the WinAppDriver can be used to test UWP app which can be run in WinPhone.

So I am confused about this. So the question is Does this WinAppDriver Support WinPhone now?

Thanks
Ethan

**Comment by yodurr** [comment]
Hi Ethan,

We do not support phone now, only PC including UWP apps that run on PC.  Our goal is to support apps running on phone and we're also looking into XBox.  We'll update the WinAppDriver documentation as plans become concrete.

**Comment by EthanJiang** [comment]
@yodurr Thanks for your reply. Could you provide an estimated time when you expect to support win phone?  one month?  or six months? or one year?

**Comment by yodurr** [comment]
A few details need to get ironed out before I can share timeline estimates.  We're working quickly.  Will keep you posted.

**Comment by EthanJiang** [comment]
@yodurr thanks

**Comment by Kamirya** [comment]
Hi, @yodurr 

I'm very interesting in the WinAppDriver Support WinPhone. Do you have any update about this now?

Thanks,
Ricky Song

**Comment by richardhall-piksel** [comment]
Hi @yodurr,

What @Kamirya said and also I am very interested in Xbox support too.
I was wondering if you had any further update since the last post I found from Dec '16:
https://github.com/Microsoft/WinAppDriver/issues/96

Thank you very much in advance,
RH
