### ISSUE TITLE
Problem with running app store application

### ISSUE THREAD

**Issue by dsavchenkov** [Microsoft/WinAppDriver#40]
Hi! 
I have problem with run application(example: camera)
![error](https://cloud.githubusercontent.com/assets/20097188/16280870/5dadabf4-38ca-11e6-96ed-75e4b304cfe5.png).
Can you help with this problem? 
I'm trying to use any account: admin, not admin, login as email. I'm always have this error.

**Comment by alakshmi1030** [comment]
Have you tried running one of our sample apps? The calculator sample app runs the application directly.

**Comment by dsavchenkov** [comment]
yes, i tried. in all cases the same result. Maybe i need to try run tests on Windows 10?

**Comment by alakshmi1030** [comment]
Yes, try running on Windows 10 PC and see if it works then. You might need to close File Explorer per your screenshot.

**Comment by dsavchenkov** [comment]
yeee, it's work on windows 10. I think, need to add requiments in additional information of this driver)
