### ISSUE TITLE
Automation approach for 'Unified Service Desk for Microsoft Dynamics 365' by WinAppDriver 

### ISSUE THREAD

**Issue by ant0908** [Microsoft/WinAppDriver#400]
Hi all, 

I'm looking for the best Automation approach for Unified Service Desk applications. 
Could you please provide information if it's possible to do with WinAppDriver? as I see that support only Universal Windows Platform (UWP) and Classic Windows (Win32) apps, and what about WPF? 

Thank you!

**Comment by hassanuz** [comment]
Yes, WinAppDriver supports testing all of the mentioned, including WPF applications.

**Comment by ant0908** [comment]
@hassanuzI I cannot get elements in the form and get next error( see attached
![error](https://user-images.githubusercontent.com/38247639/38740669-d10c491a-3f40-11e8-88e7-b39664199b34.PNG)
).  
[error.txt](https://github.com/Microsoft/WinAppDriver/files/1907701/error.txt)
code:
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability("app", "Root");
            capabilities.setCapability("app", "C:\\Program Files\\Microsoft Dynamics CRM USD\\USD\\UnifiedServiceDesk.exe");
            USDSession = new WindowsDriver(new URL("http://127.0.0.1:4723"), capabilities);
            USDSession.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
            USDResult = USDSession.findElementByAccessibilityId("UserInitials");
This error was genereted by UISpy.exe when I try inspect element in the form and application was lounched by WinAppDriver. When app was lounched manualy everithing is ok.

**Comment by dhapolapankaj** [comment]
Can we try other locators here?

**Comment by PandaMagnus** [comment]
A dump of the PageSource would be helpful, too.

**Comment by hassanuz** [comment]
Closing issue due to being idle.
