### ISSUE TITLE
WinAppDriver is not creating a session for WindowsForms wizard which is getting launched by Setup.exe.

### ISSUE THREAD

**Issue by RajneeshK2018** [Microsoft/WinAppDriver#402]
I am automating a scenario in which I need to automate the installation wizard of a software. While inspecting it displays the details of the installation wizard. 
![inspect](https://user-images.githubusercontent.com/33167724/38715770-c37acaf6-3efa-11e8-81a4-acc6dbe8763e.png)

I tried some of the approaches like below but none of them is working, as a result I am unable to click on the 'Next >' button on the wizard:

**Approach 1:**

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.SetCapability("app", "Root"); //start the session with the root node
WindowsDriver<WindowsElement> DesktopSession = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), capabilities);
/*
create the collection of all nodes(windows) with classname = "WindowsForms10.Window.8.app.0.13965fa_r9_ad1" from the inspector.
*/
var setupWindow = DesktopSession.FindElementsByClassName("WindowsForms10.Window.8.app.0.13965fa_r9_ad1");

here setupWindow  gives the count as 0.

**Approach 2:**
WindowsDriver<WindowsElement>  desktopSession2 = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), capabilities);
desktopSession2.FindElementByName("Qualitia Setup").FindElementByClassName("Next >").Click();

Here its throwing exception that window not found.

Please suggest a solution for this. Thank you.

**Comment by RajneeshK2018** [comment]
Can someone provide a help? Thanks.

**Comment by hassanuz** [comment]
Hi @RajneeshK2018,

Can you try using the automation ID and see if that is able to interact with the element?

**Comment by RajneeshK2018** [comment]
I tried using AutomationID, but no luck.

`capabilities.SetCapability("app", "Root");`
`var InstallerWindow = DesktopSession.FindElementByAccessibilityId("Welcome")`

It throws error "System.InvalidOperationException: 'An element could not be located on the page using the given search parameters.'"

Additional Information:
1. The "Qualitia Setup" window appears dynamically after double clicking on the Setup.exe
2. I also tried using White libraries, there also its not able to click on the 'Next' button
3. When trying the same with HP UFT, it identifies the button as WinObject instead of WinButton.

**Comment by hassanuz** [comment]
Hi @RajneeshK2018,

Before you do your query, can you paste the page source here? This will help us identify what the problem can be in selecting the right element.

**Comment by pereiraguilherme** [comment]
Hi guys, I have the same issue. When I run a setup.msi, the Drive UI Recorder returns all data from each button of the wizard application, but when I try to click on Next button, the code returns me a error message("org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters."). I'm using Java to test a installer UI. Can someone help me? Thank you!

**Comment by hassanuz** [comment]
Hi @pereiraguilherme,

Please do create a new issue with the pasted WinAppDriver.exe logs. 

Thank you!
