### ISSUE TITLE
How to get the ToggleSwitch state's text (OnContent/OffContent)

### ISSUE THREAD

**Issue by harvinders** [Microsoft/WinAppDriver#404]
In UWP apps it is possible to set the On/Off text for a `ToggleSwitch` control. 

I can find the on/off state from the `selected` property. Is there a way to get the actual text (OnContent/OffContent)? It would be great if it is possible as the tests would match what is there on the UI.

**Comment by timotiusmargo** [comment]
Hi @harvinders,

Yes depending on how you create your application UI, the [element.Text](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidelementidtext) property can be used to display the text of ToggleSwitch custom header and content. Please refer to this sample below taken from https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/UWPControls/ToggleSwitch.cs#L111:

```c#
public void Text()
{
    Assert.AreEqual("Toggle work Working", toggleSwitchElement.Text);
}
```

For default **ToggleSwitch** with no header and custom content, you can still get the text by finding all the text elements within the **ToggleSwitch** control and get the **Text** property of each element.

**Comment by harvinders** [comment]
> For default ToggleSwitch with no header and custom content, you can still get the text by **finding all the text elements within the ToggleSwitch control** and get the Text property of each element.

How do I find the text elements with the ToggleSwitch control?

**Comment by harvinders** [comment]
@timotiusmargo 

I have tried following code, without success

```
var toggleSwitchElement = Session.FindElementByAccessibilityId("ToggleSwitch");
var textBlocks  = toggleSwitchElement.FindElementsByClassName("TextBlock");
```
`toggleSwitchElement.FindElementsByClassName("TextBlock");` throws exception.


As you can see that inspect does show `TextBlocks` as children of the ToggleSwitch. But for whatever reason this is no accessible through the APIs. Is it a known issue or am I doing something wrong?

![image](https://user-images.githubusercontent.com/8557046/40035884-5d0d7d84-5847-11e8-9555-bd9d771f6bce.png)

**Comment by harvinders** [comment]
I am able to find a workaround for the issue. The reason we are not able to use UIAutomation to access the children of ToggleSwitch is the [AccessibilityView ](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Automation.Peers.AccessibilityView)value of `Raw` set for `OffContent` and `OnContent` properties. Pay attention to `AutomationProperties.AccessibilityView="Raw" `, this makes it visible to UIAutomation clients only when raw filter is used.

```
<ContentPresenter x:Name="OffContentPresenter"
    Grid.Row="1"
    Grid.RowSpan="3"
    Grid.Column="2"
    Opacity="0"
    Foreground="{TemplateBinding Foreground}"
    IsHitTestVisible="False"
    Content="{TemplateBinding OffContent}"
    ContentTemplate="{TemplateBinding OffContentTemplate}"
    HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}"
    VerticalAlignment="{TemplateBinding VerticalContentAlignment}"
    AutomationProperties.AccessibilityView="Raw" />
<ContentPresenter x:Name="OnContentPresenter"
    Grid.Row="1"
    Grid.RowSpan="3"
    Grid.Column="2"
    Opacity="0"
    Foreground="{TemplateBinding Foreground}"
    IsHitTestVisible="False"
    Content="{TemplateBinding OnContent}"
    ContentTemplate="{TemplateBinding OnContentTemplate}"
    HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}"
    VerticalAlignment="{TemplateBinding VerticalContentAlignment}"
    AutomationProperties.AccessibilityView="Raw"/>

```

To solve this, either WinAppDriver should be using the raw filter to look at the UIAutomation tree or we can re-template the ToggleSwitch control, without the `AutomationProperties.AccessibilityView="Raw"`.

**Comment by hassanuz** [comment]
Closing comment as original issue has been addressed - and workaround has been found.
