### ISSUE TITLE
Unable to connect Remotely. Default listening IP is always 127.0.0.1

### ISSUE THREAD

**Issue by NileshKSingh** [Microsoft/WinAppDriver#41]
Machine: Windows 10 64-bit

As per the documentation:
_"Default listening address is 127.0.0.1:4723. You can configure WinAppDriver.exe to listen to a different IP address and port if you run it as administrator."_

I tried to run in Admin Mode, but still The default listening IP and Port is showing as **127.0.0.1:4723** 
I am unable to connect it Remotely.

**Comment by alakshmi1030** [comment]
You can run a WinAppDriver test on a remote machine by specifying an IP and port from the command line. From your directory where WinAppDriver.exe is installed, the syntax is WinAppDriver.exe *IP* *Port*. 

Note that your port traffic must be open to inbound requests for this to work - you can detect the IP address of the machine you want to run the test on by running ipconfig. We will update the documentation with this information soon.
