### ISSUE TITLE
Failed to locate opened application window with appId: OUTLOOK.exe, and processId: 13708

### ISSUE THREAD

**Issue by NikitaTurakhia** [Microsoft/WinAppDriver#410]
Hello @timotiusmargo  

Whenever I try to run my 2 or more tests together it gives me this error : Failed to locate opened application window with appId: OUTLOOK.exe, and processId: 13708

my code is : 

if (session == null)
            {
                // Luanch outlook
                DesiredCapabilities appCapabilities = new DesiredCapabilities();
                appCapabilities.SetCapability("platormName", "Windows");
                appCapabilities.SetCapability("app", OutLookAppId);
                WindowsDriver<WindowsElement> Outlooksession = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities);
                

                // Create desktop session
                DesiredCapabilities caps = new DesiredCapabilities();
                caps.SetCapability("platormName", "Windows");
                caps.SetCapability("app", "Root");
                WindowsDriver<WindowsElement> DesktopSession = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), caps);
                Thread.Sleep(8000);
                // locate the main window of outlook using Desktop session
                WindowsElement outlookWindow = DesktopSession.FindElementByName("Inbox - nikita.shah@politemail.com - Outlook");
                var OutlookMainWindowHandle = outlookWindow.GetAttribute("NativeWindowHandle");
                OutlookMainWindowHandle = (int.Parse(OutlookMainWindowHandle)).ToString("x");

                // Attach outlook window to outlook session
                DesiredCapabilities OutlookCaps = new DesiredCapabilities();
                OutlookCaps.SetCapability("appTopLevelWindow", OutlookMainWindowHandle);
                session = new WindowsDriver<WindowsElement>(new Uri(WindowsApplicationDriverUrl), OutlookCaps);

                session.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(30));
                Console.WriteLine("title = " + session.Title);
            }

Please help me in this. i have been trying from last 3 days but I can not find the solution.

**Comment by timotiusmargo** [comment]
Hi @NikitaTurakhia,

Can you please include the JSON wire protocol log from `WinAppDriver.exe` console window? This will help us identifying where the problem is. :)

**Comment by hassanuz** [comment]
Hi @NikitaTurakhia,

If you are still facing this issue, please reopen or create a new ticket with the WinAppDriver.exe logs. We'll try to get back to you as soon as possible.

Thanks

**Comment by sudeeppaudyal** [comment]
POST /session HTTP/1.1
Accept: application/json, image/png
Connection: Keep-Alive
Content-Length: 241
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"desiredCapabilities":{"app":"C:\\Jericho\\richoLauncher.exe","deviceName":"WindowsPC","platformName":"Windows"},"capabilities":{"firstMatch":[{"app":"C:\\Jericho\\richoLauncher.exe","deviceName":"WindowsPC","platformName":"Windows"}]}}
HTTP/1.1 500 Internal Error
Content-Length: 168
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"Failed to locate opened application window with appId: C:\\richo\\richoLauncher.exe, and processId: 5664"}}

**Comment by sudeeppaudyal** [comment]
I am facing the same issue,would you please help.Thanks.
