### ISSUE TITLE
Appium documentation link generates 404

### ISSUE THREAD

**Issue by jpluimers** [Microsoft/WinAppDriver#411]
The [main readme points](https://github.com/Microsoft/WinAppDriver/blob/master/README.md#using-appium) to http://appium.io/slate/en/master/?ruby#windows-application-ui-testing which has vanished, and despite searching appium.io documentation, I could only find a heavily modified page at https://appium.io/docs/en/drivers/windows/ for which I'm not fully sure if it covers the late 2017 copy on The Internet Archive: https://web.archive.org/web/20171024045829/http://appium.io/slate/en/master/?ruby#undefined

If anybody finds a better page, please suggest one, otherwise, a decision needs to be made on the modified page ore the archived one.

**Comment by hassanuz** [comment]
Thanks for bringing this to our attention @jpluimers. I've update the link to point towards the most recent [Appium page for Windows Driver](https://appium.io/docs/en/drivers/windows/).

**Comment by jpluimers** [comment]
Thanks!

**Comment by yodurr** [comment]
It looks fine to me - where do you see it is broken?
