### ISSUE TITLE
SendKeys fails for password field on embedded browser under Windows app

### ISSUE THREAD

**Issue by gclouds** [Microsoft/WinAppDriver#414]
There is a HTML Dom inside it there are input fields with IDs are present.

```
DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("app", "C:\\Program Files\\Adobe\\NGL Reference Application\\NGLApp.exe");
		WindowsDriver nglRefAppSession = new WindowsDriver(new URL("http://127.0.0.1:4723"), capabilities);
		nglRefAppSession.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
```

//works fine
`nglRefAppSession.findElementByAccessibilityId("adobeid_username").sendKeys(userName);`

//doesnot works
`nglRefAppSession.findElementByAccessibilityId("adobeid_password").sendKeys(password);`

**Comment by timotiusmargo** [comment]
Sending key strokes to a standard XAML PasswordBox the same way with an EditBox. The only difference would be the masked value when retrieved from `Text` attribute.
