### ISSUE TITLE
XPATH not working

### ISSUE THREAD

**Issue by sunnysachdeva** [Microsoft/WinAppDriver#417]
HI ,

As you can see in the attached pic, I dont have any way other than to find element by XPATH.

I tried Window, AnnotationID in XPATH but none of them are working.Can any one pls help.

![image](https://user-images.githubusercontent.com/5293359/39881322-383c5dba-549e-11e8-88f6-4b7c87dbe85a.png)

```
DesiredCapabilities desktopCapabilities = new DesiredCapabilities();
    	desktopCapabilities.setCapability("app", "Root");
    	desktopCapabilities.setCapability("deviceName", "WindowsPC");
        driver = new RemoteWebDriver(new URL("http://127.0.0.1:4723"), desktopCapabilities);
        driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
jdaApp=driver.findElementByName("JDA Solutions");
jdaApp.findElement(By.xpath("//*[@AnnotationID='010000807C142900FCFFFFFF00000000']")).click();
```

**Comment by PandaMagnus** [comment]
What's the PageSource look like for this window? Could you get a parent element instead and then find this child element?

**Comment by hassanuz** [comment]
Hi @sunnysachdeva,

Can you also provide a screenshot of Inspect analyzing this element?

**Comment by sunnysachdeva** [comment]
@PandaMagnus I am new to windows desktop automation. Can you pls advise how to look for page source of an windows application.

**Comment by sunnysachdeva** [comment]
@hassanuz 
got some UI change so pasting new source...
![image](https://user-images.githubusercontent.com/5293359/40224749-b31d73aa-5aa4-11e8-8863-c8734e3273b8.png)

Even parent does not have any unique attributes. Why cant we use annotation id or window handle

Below is snapshot for parent
![image](https://user-images.githubusercontent.com/5293359/40224819-f3c36e28-5aa4-11e8-9691-02caa558f260.png)

**Comment by PandaMagnus** [comment]
@sunnysachdeva You can get at the page source through the session. Right after this line of code:
driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);

Write a line of code like:
var temp = driver.PageSource;

If you drop a breakpoint after this, you can inspect the variable, or you can save temp to a file. The two things to verify once you have the page source is:
1) Has the driver picked up the application yet (basically, is there anything in the page source yet. If not, it's probably just timing out before the application loads, and you can add in a wait before trying to search.)
2) Is the annotation ID present, but maybe under a different property? E.G., I have a WPF app where the "AutomationID" in XAML gets translated to "AccessibilityID" in WAP.

Depending on what the page source displays, it should be easier to determine why this isn't working.

**Comment by hassanuz** [comment]
Making issue as closed due to Panda's resolution.
