### ISSUE TITLE
Unable to launch Cordova Hybrid Windows Store Appx: Getting session Error

### ISSUE THREAD

**Issue by NileshKSingh** [Microsoft/WinAppDriver#42]
I am able to launch native windows application successfully by using the below code. But not able to launch Cordova Hybrid Windows App with same code. 

```
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("app", "com.XXXXXXXX.runtime_h365459jr9hy9m!App");
capabilities.setCapability("platform", "Windows");
driver = new RemoteWebDriver(new URL("http://XXXXXXXX.com:4723"), capabilities);
driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
```

I can see sometimes the application flashes and exited (in milliseconds) suddenly with the following error:-

> HTTP/1.1 500 Internal Error
> Content-Length: 101
> Content-Type: application/json
> 
> {"status":33,"value":{"error":"session not created","message":"A new session could not be created."}}

**Comment by divyaramachandran** [comment]
We are facing the same issue while trying to launch any app apart from the extensions "Microsoft.Windows<AppName>"

**Comment by yodurr** [comment]
For the cordova app you can get the App ID from the following location in your project:
\bld\Windows-x64\Debug\vs.appxrecipe

You'll see a <RegisteredUserModeAppID> tag in this file.  Use the value in the app field in your desired capabilities when creating the test session.

Please let me know if that works.

**Comment by nisarghimani** [comment]
I'm also facing a similar issue where I'm not able to launch the immersivecontrolpanel.

`caps = {:platformName => "WINDOWS", :platform => "WINDOWS", :deviceName => "mydevice", :app => "windows.immersivecontrolpanel_cw5n1h2txyewy!App"}
session = Selenium::WebDriver.for(:remote, :url => "http://XXXXXXXX.com:4723", :desired_capabilities => caps)`
