### ISSUE TITLE
Does WindowsDriver support the similar API as selenium for browser?

### ISSUE THREAD

**Issue by IreneAdler777** [Microsoft/WinAppDriver#422]
I would like to automate touch function on my web, but it seems that the TouchActions API must use with Appium, so I have to use WindowsDriver to open a Chrome browser, but unfortunately, I can't use driver.get(url) or driver.window_handles, so I think may be there is some more capabilities I need to add before I start a remote driver.

My code is as below:
`from appium import webdriver`
`desired_apps = {}`
`desired_caps["app"] = "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"`
`driver = webdriver.Remote(command_executor= 'http://127.0.0.1:4723', desired_capabilities =  desired_caps)`
`driver.get("https://www.google.com")#this line failed`
For Android, I can add appActivity and appPackage in the capabilities. But I am new dev on windowsdriver automation, is there a way I can use windowsdriver and appium with selenium browser API?

Thanks & Regards,
Xinda

**Comment by hassanuz** [comment]
Hi @IreneAdler777, 

This would scope to webdriver - I would recommend using Edge [WebDriver](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/) for web interactions.
