### ISSUE TITLE
What is the Windows Maximize Short Key for WinAppDriver ?

### ISSUE THREAD

**Issue by rajeeshmenoth** [Microsoft/WinAppDriver#423]
Hi,

I am not able to find any Keyboard.PressKey for Maximize the Current Window Screen.

> Eg : "Win + Up Arrow" ( Maximize )

**Comment by PandaMagnus** [comment]
Does it have to be a hotkey? I believe you can call into Selenium for this. I'm not on my computer with WAP installed, but I think it should be something like Session.Manage().Window.Maximize();

**Comment by rajeeshmenoth** [comment]
Hi @PandaMagnus ,

I am executing my Application through "WinAppDriver". Now I resolved this issue using the following short key.
`Keyboard.PressKey(Keys.Alt + Keys.Space + 'x');`

But I want to know if any Keys available for "Windows" or "Win"

**Comment by PandaMagnus** [comment]
@rajeeshmenoth WinAppDriver sits on top of Appium and Selenium, so there should be either a Selenium command, or an equivalent Appium command.

I just checked on my machine with WinAppDriver, and Session.Manage().Window.Maximize(); will work for a regular desktop app.

**Comment by PandaMagnus** [comment]
You mentioned Win + Up Arrow earlier. If that doesn't work, try Alt+Enter, then the X key. Alt+Enter should open the context menu for the application with focus, and hitting the "x" key should invoke the maximize command.

**Comment by timotiusmargo** [comment]
Hi @rajeeshmenoth,

Yes you can indeed invoke the **Win** + **Up Arrow** to maximize the application as follows:
```c#
session.Keyboard.SendKeys(Keys.Command + Keys.ArrowUp + Keys.Command);
```

Notice the use of `Keys.Command` for the **Win** button modifier at the end to release it. A different example of using the **Win** button can be found below:
https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/SendKeys.cs#L122

**Comment by rajeeshmenoth** [comment]
Hi @timotiusmargo ,

Perfect Answer ! Thank you.

**Comment by vaib-ag** [comment]
I am also facing the same issue, the only problem is my window is a child of the application window.
Hence In my case my window object is Webelement. 
> I can't use session handel as it will maximize or minimize the parent window.
>There seems to be no way to cast webelement to windowselement
>cant set attribute value to an object (Window.WindowVisualState:	Maximized (1))

**Comment by Michaelwan777** [comment]
> Hi @rajeeshmenoth,
> 
> Yes you can indeed invoke the **Win** + **Up Arrow** to maximize the application as follows:
> 
> ```cs
> session.Keyboard.SendKeys(Keys.Command + Keys.ArrowUp + Keys.Command);
> ```
> 
> Notice the use of `Keys.Command` for the **Win** button modifier at the end to release it. A different example of using the **Win** button can be found below:
> https://github.com/Microsoft/WinAppDriver/blob/v1.0/Tests/WebDriverAPI/SendKeys.cs#L122

Hi Timothy, Thank you so much for your instruction!
I wonder how to press key "CTRL" "Y".
I've tried in three ways but all fail:
1.
Actions builder = new Actions(session_S);
            builder.SendKeys(Keys.Control + "Y");
            builder.Perform();

 builder.SendKeys(Keys.Control + "Y");

2.
session_S.Keyboard.PressKey(Keys.Control + "Y");

3.
session_S.Keyboard.SendKey(Keys.Control + "Y");

Could you please help me in this issue? Thank you very much in advance!
