### ISSUE TITLE
How to completely close app that only minimizes to tray when click on "X" button

### ISSUE THREAD

**Issue by Bisu1909** [Microsoft/WinAppDriver#426]
Im testing a window application using appium + winappdriver. And it seems so far so good. 
But I cannot close the application completely. I've tried with .Quit() and .Dispose(), it only minimizes the application to the icons tray. 
Please help me on this, any ideas are welcome !

**Comment by hassanuz** [comment]
Hi @Bisu1909,

This is application behavior and is how the app is set by default. WinAppDriver interacts with the application in the same way an actual user would. 

If the application has a way to close it completely (some apps have File - > exit in the toolbar), you would have to repro those same steps using WinAppDriver to perform that action.

**Comment by Bisu1909** [comment]
@hassanuz Hi,

Yep thanks for your solution. I also find a workaround as to kill an app with batch file, and make WinAppDriver run that file in the onetimeteardown. Thanks for your support !

**Comment by hassanuz** [comment]
Awesome - glad to know @Bisu1909. Marking this as closed.
