### ISSUE TITLE
Unable to work with Spreadsheets or GridViews from DevExpress

### ISSUE THREAD

**Issue by eduarte** [Microsoft/WinAppDriver#429]
Hi 

I am trying to automate a WinForm application that is using DevExpress, I am getting issues to work with SpreadSheets or GridViews.

Basically the issue is that I am not able to get or set data to a specific row/column the only workaround is to create an Action and move the mouse to some coordinates, but this is not a good solution since our application may be running on different Screen Resolutions.

`
            _driver.Current.FindElementByName("FormContainer").Click();
            var spread = _driver.Current.FindElementByAccessibilityId("spreadsheet");
            Actions ac = new Actions(_driver.Current);
            ac.MoveToElement(spread).MoveByOffset(-600, -220).Click().SendKeys("11").Build().Perform();`

Can someone helping me on this?

**Comment by hassanuz** [comment]
Hi @eduarte,

Are you able to locate the XPath for the specific row/column? If so, you can iterate through the row/columns using that. You can locate the XPath using the new [UI Recorder tool](https://github.com/Microsoft/WinAppDriver/releases/tag/UiR_v1.0-RC).

**Comment by hassanuz** [comment]
Please open a new ticket if you are still experiencing this issue.
