### ISSUE TITLE
SendKeys special characters

### ISSUE THREAD

**Issue by jonstoneman** [Microsoft/WinAppDriver#43]
The release notes for 0.4-beta include "SendKeys functionality enabled for special characters".  I have tried simulating the enter key using `hello\n` but this does not appear to work.  Is this a bug or is there a different syntax for enter?  What other characters are supported?

**Comment by alakshmi1030** [comment]
Sending a \n character through SendKeys generates a new line in our test project, but it does not simulate an enter key. We are still working on enabling simulating key presses such as the enter key; escape characters seem to be working.

**Comment by ddelapasse2** [comment]
^Any progress on this?  I'm trying to force my app to log into Azure and to do this I need to enter the username and then TAB outside the field (Azure then redirects to a different login screen where I will fill in the password.  Any other workaround for this?  [NOTE: I am attempting to use this for UWP regression testing and so far it's been excellent!!!]

**Comment by timotiusmargo** [comment]
Thank you @jonstoneman & @ddelapasse2 ! This special character support is now implemented in v0.6-beta release.

Note that to sending a special character key is done through a special unicode character constant. E.g.
`editBox.SendKeys(OpenQA.Selenium.Keys.Tab);
editBox.SendKeys(OpenQA.Selenium.Keys.Enter);`

More examples can be found on https://github.com/Microsoft/WinAppDriver/blob/v0.6-beta/Tests/W3CWebDriver/ElementSendKeys.cs

**Comment by barisgul** [comment]
Hi @timotiusmargo ,
when I type to a text or special characters , driver types different text to notepad.exe as below. 
`
string text="This is some text and turkishbank.tiff /";
string symbols = "-=[]\\;',./~!@#$%^&*()_+{}|:\"<>?";

driver.FindElementByClassName("Edit").SendKeys(text);
driver.FindElementByClassName("Edit").SendKeys(symbols);

output1 : *-ğü,şiöç.~!@#$%^&*()_+{}|:"<>?
output2 : Thıs ıs some text and turkıshbankçtıff . `

**Comment by barisgul** [comment]
I found cause of the problem. When I change keyboard language from turkish to Eng(US),
 worked for me. Bu I want to use turkish keyboard. Is there any solution?

**Comment by hassanuz** [comment]
Thanks for reporting back @barisgul - multi-region keyboards are currently not supported. This is something we'll look into for a potential enhancement in the future.

**Comment by barisgul** [comment]
Hi @hassanuz 
Is there a release date for supporting the multi region keyboards?
We use winium for now but we want switch to WinnAppDriver in our framework. This is a very important issue for us.

**Comment by miksch123** [comment]
You can assign a string where you use the alt key and the number combination of the character that you want to have.
Example: string x = keys.Alt + keys.numpad9 + keys.numpad6 + keys.alt;
