### ISSUE TITLE
How to handle "Access Denied" Window popup using WinAppDriver ?

### ISSUE THREAD

**Issue by rajeeshmenoth** [Microsoft/WinAppDriver#430]
Hi,

I am not able to click on the Window popup using winappdriver. I already tried keypress event but no use.
  
![image](https://user-images.githubusercontent.com/8437883/40976219-0b8f02f2-68eb-11e8-8853-d447e44c310d.png)

**Comment by hassanuz** [comment]
Hi @rajeeshmenoth,

Thanks for reaching out. This is known, and is actually a security feature - posing a security risk is one of the reasons why WinAppDriver does not support this.

**Comment by rajeeshmenoth** [comment]
Hi,

Any proper solution for this ?

**Comment by PandaMagnus** [comment]
There *might* be a registry key you can set to automatically launch the application in Administrator mode. We've had mixed results with that at work with a different application (it works for a bit, then it doesn't.)

To get around this, I turned off UAC entirely on our test agents. This is super not recommended as it's a main security feature for Windows and requires admin privileges to do this. But I can confirm it works as a last resort.

**Comment by hassanuz** [comment]
Hi @rajeeshmenoth,

This is by design, WinAppDriver is not able to interact with elevated system prompts.
