### ISSUE TITLE
Not able to identify the element properties in inspector.

### ISSUE THREAD

**Issue by Kranthi9704** [Microsoft/WinAppDriver#431]
Hi Hassanuz,

When i search object properties using inspection then we are getting error message in inspector.`
![git](https://user-images.githubusercontent.com/6367159/41019030-87129e2c-697a-11e8-9fcf-f20424ce7144.png)
![git](https://user-images.githubusercontent.com/6367159/41019038-8d9c33ac-697a-11e8-873e-d96d12a5cbe1.png)

`

**Comment by PandaMagnus** [comment]
I'm going to guess that Inspect's functions seem to be outside the scope of WinAppDriver, unfortunately. However, you could try navigating to that page and dumping out the page source to see if WAP was able to find it (something like var temp = Session.PageSource, set a breakpoint right after it, and see what's listed. Alternatively, if you have logging set up you can log the page source and look at it after a test run). You should be able to isolate if WAP could find the control or not based on that.

**Comment by hassanuz** [comment]
Hi @Kranthi9704, 

Please do try out @PandaMagnus 's suggestion. I would also suggest trying out the new WinAppDriver UI Recorder tool - https://github.com/Microsoft/WinAppDriver/releases/tag/UiR_v1.0-RC - to see if this is able to retrieve the desired properties. Let us know if this is the case! 

Thanks
