### ISSUE TITLE
WInappdriver mapping vb6 objects

### ISSUE THREAD

**Issue by miguelpet** [Microsoft/WinAppDriver#435]
VB6 objects can't mapped correctly!
I have one visual basic applications with names defined, but when i will inspect the elements, the name don't show.
Testcomple able to find this elements correcty, in the sintax its something like [VBObject](txtTest)
Has something like this a can use with winappdriver?

Thanks all

**Comment by hassanuz** [comment]
Hi @miguelpet,

If Inspect.exe (in UIA mode) does not show the elements, then WinAppDriver will not be able to be used against it.
