### ISSUE TITLE
WinAPPDriverUI recorder doesn't launch in Windows 10

### ISSUE THREAD

**Issue by automationcalling** [Microsoft/WinAppDriver#437]
Hello Team,

As mentioned in the page https://github.com/Microsoft/WinAppDriver/releases/tag/UiR_v1.0-RC, I downloaded  zipped binaries and tried to launch WinAppDriverUiRecorder.exe, nothing happened.

I also tried with command prompt but no error or logs return. Later, I troubleshoot exe and change the compatibility setting but nothing works.

Could you please advise this WinAPPDriverUI recorder launch standalone without Visual studio?

Thanks,
Muthu

**Comment by hassanuz** [comment]
Hi @automationcalling,

Thanks for reaching out. We'll are looking into resolving this for future releases. In the meantime as a workaround, can you see if installing the following VC runtime link: https://go.microsoft.com/fwlink/?LinkId=746572 solves this issue for you? 

Thanks

**Comment by automationcalling** [comment]
Hi Hassan Uraizee,

The above VC runtime installer doesn't help me. After installation, even I reset the machine when I click on UI recorder.exe it doesn't bring up :-(.

**Comment by hassanuz** [comment]
Redownloading UI Recorder should resolve this now. Reopen issue if this still persists.

**Comment by ianceicys** [comment]
I am encountering the same issue, WinAppDriverUIRecorder is not launching on Windows 10 Build 1903.
