### ISSUE TITLE
POST /session/:sessionId/element/:id/value only sets the 1st character of a string

### ISSUE THREAD

**Issue by zumwald** [Microsoft/WinAppDriver#44]
Example (pseudo-javascript):

`// initialize driver`
`driver.setValue('//Edit', 'myusername@outlook.com');`
`// test continues`

The server receives a request like so:
==========================================
POST /session/213C7E07-0C10-4398-9C33-18480AC60E4E/element/42.13372574.2.465/value HTTP/1.1
Accept: application/json
Connection: keep-alive
Content-Length: 99
Content-Type: application/json; charset=UTF-8
Host: 127.0.0.1:4723
User-Agent: webdriverio/webdriverio/4.0.8

{"value":["m","y","u","s","e","r","n","a","m","e","@","o","u","t","l","o","o","k",".","c","o","m"]}
HTTP/1.1 200 OK
Content-Length: 63
Content-Type: application/json

{"sessionId":"213C7E07-0C10-4398-9C33-18480AC60E4E","status":0}

**Comment by timotiusmargo** [comment]
This is fixed in v0.6-beta. Sample test scenarios can be found on https://github.com/Microsoft/WinAppDriver/blob/v0.6-beta/Tests/W3CWebDriver/ElementSendKeys.cs

**Comment by rahulmr** [comment]
@zumwald Can you share your work with webdriverio ? Are you using wdio runner or using mocha with webdriverio standalone.
