### ISSUE TITLE
Navigate between elements on the 'Table' 

### ISSUE THREAD

**Issue by ant-skelia** [Microsoft/WinAppDriver#440]
Hi all, 
Maybe someone has existence hot to navigate between element on the Table? 
In my case, I can't use 'Name', because there are a lot of elements with the same name property.  
![image](https://user-images.githubusercontent.com/38521598/41911666-f5bec11c-7955-11e8-9aea-af08ef074599.png)

![image](https://user-images.githubusercontent.com/38521598/41911407-26e507e8-7955-11e8-8a8c-3e50955e7016.png)

And I am very disappointed that there are a lot of problems with access to element ByXpath and any real answers form support.

**Comment by ant-skelia** [comment]
And the answer is: winDriver.findElementByAccessibilityId("flyoutFormSection_ContentTable").findElement(By.name(sectionName)).click();

**Comment by hassanuz** [comment]
Glad to see that you found the solution @ant-skelia. You can use the UI Recorder to pick up the XPath, but in some cases you will have to remove the prefix in the XPath for it to be picked up.  

We're looking into improving XPath performance for our next release. 

Marking issue as closed.
