### ISSUE TITLE
WinAppDriver UI Recorder Supports Chromium Embedded Framework

### ISSUE THREAD

**Issue by ravimakkena** [Microsoft/WinAppDriver#443]
How to identify the objects in the CEF application (Desktop) using WinAppDriver UI Recorder or Inspect?

**Comment by SyberToto** [comment]
Hi @ravimakkena 
I'm also testing some hybrid application. My solution is to enable remote debug on CEF, and use a separate chromedriver to manipulate the web view. Here's the sample code:
```java
        ChromeOptions options = new ChromeOptions();
        options.setExperimentalOption("debuggerAddress", "127.0.0.1:" + cefPort);
        WebDriver webView = new ChromeDriver(options);
```
If you can start your application and set a remote debug port number on CEF, you may try my way. After all, chomedriver would be easier to use for web wiew.

**Comment by hassanuz** [comment]
Closing issue as work-around provided.

**Comment by bvglooks** [comment]
Is there a way to automate CEF hybrid application without opening the debugging port?

**Comment by srinivas15j1988** [comment]
Could you explain how u are enabling remote port for an existing application? (if source code of application is not available)

**Comment by SyberToto** [comment]
> Could you explain how u are enabling remote port for an existing application? (if source code of application is not available)

It depends on [if the existing app's implementation passes the command line arguments (with the same option name) to the CEF init function or not](https://bitbucket.org/chromiumembedded/cef-project/src/427d9e61f25a266a77f511d7c5ee6dba71c6f9b1/examples/shared/main_win.cc#lines-77). As the source code of the app is not available, the best shot we have is just to take a try with [--remote-debugging-port=XXXX](https://www.chromium.org/developers/how-tos/run-chromium-with-flags).
