### ISSUE TITLE
findElementByAccessibilityId is not working with 0.9

### ISSUE THREAD

**Issue by jsingh-qualitrol** [Microsoft/WinAppDriver#444]
Hi,
With Winappdriver 0.9 and APPium 1.7.1, i am not able to click on textbox with FindElementByAccessibilityId . in Java IEDName = driver.findElementByAccessibilityId("iedNameTextBox");
With Xpath i am able to locate.
Pls help..
I also tried to use latest Winapp driver. Unfortunately, Appium 1.7.1 only works with 0.9 beta version

**Comment by jsingh-qualitrol** [comment]
@timheuer @jonstoneman @cmaneu @martinwoodward @bitcrazed  Pls help

**Comment by timheuer** [comment]
@yodurr

**Comment by jsingh-qualitrol** [comment]
@timotiusmargo : pls help

**Comment by hassanuz** [comment]
Hi @jsingh-qualitrol,

Can you provide the WinAppDriver logs? Also, are you able to use Appium 1.8.1? 

Can you paste the XPath that is picked up from the UI REcorder tool?

Thanks

**Comment by jsingh-qualitrol** [comment]
Hi 
After upgrading to Appium 1.8.1 and Winappdriver V1.0 . This issue is resolved.

**Comment by hassanuz** [comment]
Great to hear.
