### ISSUE TITLE
Better Old Windows Error Message, Please!

### ISSUE THREAD

**Issue by drewcoo** [Microsoft/WinAppDriver#448]
When I was trying to get this automation going on AppVeyor I got the error message "WinAppDriver exited unexpectedly with code 3221225781." 3221225781 is probably 0xc0000135 which is probably STATUS_DLL_NOT_FOUND from ntstatus.h. Because my AppVeyor box might be old I checked and found it was.
```
    ver
    Microsoft Windows [Version 6.3.9600]
```
So the old OS must not have had a dll used by the code. Or that's the story I'm telling myself.

I know it's not supposed to work on old Windows but please don't close "won't fix." I have a feature request. I would like the error message to be a little smarter so that this is more obvious the next time someone runs into the problem. When your code fails here with 0xc0000135 you could check the OS version and give the user a better error message? Maybe something like "Try a recent OS, old codger." Well, you could probably come up with better verbiage.

I would give you a PR myself but I can't find the offending code so I assume it's some kind of secret closed source.

Thanks for considering this.

**Comment by hassanuz** [comment]
Hi @drewcoo,

We've implemented an installation block on the latest v1.1 RC. Closing ticket as this should be non-issue now. Thanks!
