### ISSUE TITLE
Dynamically generated Button doesn't respond to click command

### ISSUE THREAD

**Issue by mevans-probaris** [Microsoft/WinAppDriver#45]
I am developing an app and am trying to incorporate automated ui testing using this awesome(!) driver. In the app is a list of other devices related to the user's account in the app which is dynamically generated from a list pulled from our server, using a web call and displayed using an ItemsControl/DataTemplate. Part of the list is a button that has a dynamic name (based on id of device in our server) that will perform an action on the corresponding device. 
I am using the iOS appium library to send these commands, and clicking other (static) buttons work, but for some reason, trying to click this particular button does not work. The windows app driver acts as though it works, but the code behind the button does not execute. Of course the button works if _I_ click it, so I'm thinking it has something to do with being dynamically generated. 
The Windows App Driver does successfully find the button, and it does successfully describe to me some of its attributes, but for some reason sending the click command does nothing.

It finds the button:
![image](https://cloud.githubusercontent.com/assets/16564622/17117135/db7bebfe-5288-11e6-8202-61233df08f84.png)

Definitely the correct button:
![image](https://cloud.githubusercontent.com/assets/16564622/17117161/f8e51a12-5288-11e6-8853-d172532e5eec.png)

Clicking/Tapping do nothing, although report as successful:
![image](https://cloud.githubusercontent.com/assets/16564622/17117184/14c83d2c-5289-11e6-95bb-dc4dd2f531dd.png)

Again, it works if a human clicks it, but not if it goes through the windows app driver. And I have checked that the size isn't 0 and that it is enabled/displayed etc, all of which the win app driver correctly reports. It is just the click/tap action that seems not to work.

**Comment by yodurr** [comment]
Can you use the source API in release 0.4 to see if your element is showing up inside our internal UI tree?

**Comment by mevans-probaris** [comment]
Looking at the source, I see that it DOES appear in the page source, and all of its attributes appear to be normal (IsEnabled="True" IsOffscreen="False" etc). Its RuntimeId matches what the WinAppDriver reports as well. One thing is, the button appears in a pane with a scroll bar, could that possibly confuse it?

I've attached a screenshot of the win app driver log, a screenshot taken by the win app driver and the page source, both taken immediately following the click event. If there is any other information I can supply, please let me know.

[DynamicButtonBug.zip](https://github.com/Microsoft/WinAppDriver/files/388482/DynamicButtonBug.zip)

**Comment by timotiusmargo** [comment]
Hi Michael, thanks for the reporting the issue you encountered above. We recently released [v0.6-beta](https://github.com/Microsoft/WinAppDriver/releases/tag/v0.6-beta) that should generate a click action on any UI element instead of invoking specific pattern. Could you please give it a try and verify that it fixes the issue above?
