### ISSUE TITLE
Does it support WPF applications?

### ISSUE THREAD

**Issue by KarrySodhi** [Microsoft/WinAppDriver#451]
Hi,

Does this support automation of Wpf application? There is no mention of WPF. However, if UWP is supported should it support wpf as well?

Regards,
Karmjit Singh

**Comment by hassanuz** [comment]
Hi @KarrySodhi,

Yes, WinAppDriver supports UWP, Win32, WinForms, and WPF as well. If you are able to see the element tree using Inspect.exe, then WinAppDriver should be able to automate against it.

Thanks,
Hassan

**Comment by tusarranajan** [comment]
Hi,

Does it support UIA2 and UIA3.
I have a wpf Application with infragistics controls.When am trying to record its not working.
Thanks,
Tusar

**Comment by hassanuz** [comment]
Hi @tusarranajan,

Are you using the UI Recorder tool to record? Can you provide additional detail on what is not working? 

Thanks

**Comment by tusarranajan** [comment]
Hi Hassanuz,
i have a  wpf Application with infragistics controls. when i am trying to record ,no c# code is getting generated.
Thanks,
Tusar

**Comment by hassanuz** [comment]
Hi @tusarranajan,

Can you confirm if Inspect.exe can pick up the element attributes?

**Comment by hassanuz** [comment]
Closing as original issue answered.
