### ISSUE TITLE
Launching two windows for Outlook 2016 & OneNote 2016

### ISSUE THREAD

**Issue by rajeeshmenoth** [Microsoft/WinAppDriver#452]
Hi,

Two startup windows are opening while launching Outlook 2016 & OneNote 2016 using WinApp Driver. Other applications are working fine ( Word , Excel , PowerPoint, Adobe , etc).

Thanks & Regards
Rajeesh

**Comment by hassanuz** [comment]
Hi @rajeeshmenoth,

Can you clarify more on "startup windows"? Do you mean that Outlook and OneNote will open up two instances instead of one?

**Comment by rajeeshmenoth** [comment]
Hi,
