### ISSUE TITLE
Is there a way to activate the minimized window at the top?

### ISSUE THREAD

**Issue by yundg** [Microsoft/WinAppDriver#453]
If the application you want to control is blocked by another application, you can not control it.
Is there a way to activate it?

**Comment by hassanuz** [comment]
Hi @yundg,

Can you clarify if you mean minimized? or blocked? 

If it is minimized, try looking at [this](https://github.com/Microsoft/WinAppDriver/blob/8bb91f06ef9cbc798c88099a586c15d74fd17870/Tests/WebDriverAPI/Window.cs#L388).

If it is blocked, you can try switching to current window, as seen [here](https://github.com/Microsoft/WinAppDriver/blob/8bb91f06ef9cbc798c88099a586c15d74fd17870/Tests/WebDriverAPI/Window.cs#L155).
