### ISSUE TITLE
Problem with ComboBox when trying to change selection

### ISSUE THREAD

**Issue by martinikolaev** [microsoft/WinAppDriver#456]
Hello, I am experiencing the following issue with ComboBox:

**Scenario:**
1. Open Microsoft Timesheets Application
2. For each available week
2.1 Press Add Timesheet button
2.2 Select Week
2.3 Press Cancel button

**Expected Behavior:** 
1. The Driver will click on Add Sheet button
2. The  Driver will select the parsed week from ComboBox
3. The Driver will click Cancel button

**Observed behavior:**
After the first iteration is completed successfully, the second iteration is opening the drop down menu, but its throwing an exception that the element could not be found.

I have the example code here:

```
foreach (var week in dateProvider)
            {
                application.GetInstance<HomePage>()
                    .PressAddButton()
                    .SelectTimesheetPeriod(week)
                    .PressCancelButton();
            }
```

dateProvider is a List<string> which has 20 elements.

```
public class HomePage : Invoker
    {
        protected WindowsElement DatesComboBox => this.Driver.FindElementByAccessibilityId("timesheetPeriodField");
        
        public HomePage SelectTimesheetPeriod(string value)
        {
                        DatesComboBox.Click();

            DatesComboBox.FindElementByName(value).Click();

            return this;
        }
    }
```

Where value is something like "Mon, ‎Jul‎ 16 - Sun, May 22"

And just in case the GetInstance implementation to remove the suspicion: Its just returning me same instance of the Driver if its already instantiated.

```
public T GetInstance<T>() where T : GlobalStepInvoker, new()
        {
            if (this._instances.All(i => i.Key != typeof(T)))
            {
                var instance = new T();
                instance.WindowsDriver = this.Driver;
                this._instances.Add(typeof(T), instance);
            }
            return (T)this._instances[typeof(T)];
        }

```

I have tried with xpaths such as 
```
this.Driver.FindElementByXPath($"//ListItem[contains(@Name, '{value}')]");
this.Driver.FindElementByXPath($"//ListItem[starts-with(@Name, \"{value}\")]");

this.DatesComboBox.FindElementByXPath($"//ListItem[contains(@Name, '{value}')]");
this.DatesComboBox.FindElementByXPath($"//ListItem[starts-with(@Name, \"{value}\")]");

```
Also tried to select the same value again:

```
foreach (var week in dateProvider)
            {
                application.GetInstance<HomePage>()
                    .PressAddButton()
                    .SelectTimesheetPeriod(dateProvider[0])
                    .PressCancelButton();
            }
```
EDIT::
The UI Recorder provided by Microsoft recorded following this structure

```
"/Pane[@Name=\"Desktop 1\"][@ClassName=\"#32769\"]
/Window[@Name=\"Timesheets\"][@ClassName=\"ApplicationFrameWindow\"]
/Window[@Name=\"Timesheets\"][@ClassName=\"Windows.UI.Core.CoreWindow\"]
/Pane[@ClassName=\"Web Platform Embedding\"]
/Pane[@Name=\"Timesheets\"][@ClassName=\"Internet Explorer_Server\"]
/Pane[@Name=\"Time\"]
/Group[@AutomationId=\"newTimesheetPanel\"][@Name=\"New Timesheet Panel\"]
/ComboBox[@AutomationId=\"timesheetPeriodField\"]
/List[position()=2]
/ListItem[@Name=\"‎Mon‎, ‎Jul‎ ‎16 - ‎Sun‎, ‎Jul‎ ‎22\"]"
```

**but none changed the result, exact same behavior.**

I have checked  all the strings, they check-out so I am confident in my List of strings...

Any suggestions ? Am I missing something else ? Making a mistake or ? Or is a defect ?

**Comment by hassanuz** [comment]
Hi @martinikolaev,

For WinAppDriver to interact with the combo box, you would have to initiate a [desktop session ](https://github.com/Microsoft/WinAppDriver/wiki/Frequently-Asked-Questions/289a8b325d3ddab9f08b4398c49163a9a136f607#when-and-how-to-create-a-desktop-session) and interact with the combo box elements that way.

**Comment by HPramesh** [comment]
Hi,
Me too facing the similar kind of issue. Please suggest if it worked for anyone.

**Scenario:**
Word -> Ctrl + P -> Printer properties screen(parent screen) -> Click Printer popperties link -> <Printer> Document properties screen(child screen)

As soon as the desktop session is created to interact with the ComboBox elements in the child screen, the parent screen disappears and thus test fails when it returns to parent screen.

**Comment by djewiss** [comment]
Hi There,

We have the same problem, I abandoned clicking the ComboBox item, and went to sending keys to navigate down a list of the items. Here's what I did, I know it's not ideal, but it worked for me-

````
//this is the string we are looking for
internal string TheLanInterface => TestConfigAccessor.Settings.Net2CardLanAdapter;  
// automation id for the combobox                
internal WindowsElement InterfaceComboBox => Driver.FindElementByAccessibilityId("InterfaceComboBox");
internal ReadOnlyCollection<WindowsElement> LanPortCombBoxItems => Driver.FindElementsByClassName("RadComboBoxItem");

InterfaceComboBox.Click();
InterfaceComboBox.SendKeys(Keys.Home);
for (var i = 0; i <= LanPortCombBoxItems.Count; i++)
{
    if (TheLanInterface == LanPortCombBoxItems[i].Text)
    {
        InterfaceComboBox.SendKeys(Keys.Enter);
        break;
    }
    else
    {
        InterfaceComboBox.SendKeys(Keys.ArrowDown);
    }
}
````

**Comment by naeemakram** [comment]
I did the following to select a particular item in the combo box: 

```
            var combo = sessionAppWinForms.FindElementByAccessibilityId("comboBox1");            

            var comboOpen = combo.FindElementByName("Open");

            combo.SendKeys(Keys.Down);
            comboOpen.Click();

            var listItems = combo.FindElementsByTagName("ListItem");

            Debug.WriteLine($"Combo box items count: {listItems.Count}");
            

            foreach (var v in listItems)
            {
                Debug.WriteLine(v.Text);
                if (v.Text == "NJ")
                {
                    v.Click();
                }
            }
```

**Comment by hassanuz** [comment]
Closing issue. If anyone has anything to follow-up with, please create a new ticket.
