### ISSUE TITLE
Run windows application as administrator

### ISSUE THREAD

**Issue by AkoSiAlex** [Microsoft/WinAppDriver#458]
Hi,

I would like to confirm if winappdriver can run windows application as administrator? If yes can you share how to do that? 

Thank you in advance. :-)

Regards,
AkoSiAlex

**Comment by hassanuz** [comment]
Hi @AkoSiAlex,

For non-modern applications, they will be launched in the same context as WinAppDriver (e.g. if WinAppDriver is running at admin, then it will launch legacy application as admin).

**Comment by anupekshajain** [comment]
https://github.com/ap658n : Could you share the code snippet for launching winAppDriver in admin mode. TIA
