### ISSUE TITLE
It is impossible to change a default port without providing IP Address

### ISSUE THREAD

**Issue by denys-rwd** [Microsoft/WinAppDriver#46]
I want to change default server port without providing IP Address.
It is impossible to do.

Expected: WinAppDriver -port 80. 
Actual: WinAppDriver 172.52.22.161 80

The issue is IP is not static and after restart may be changed, today in order to change port I should write a script that extract IP address.

**Comment by yodurr** [comment]
The command to use is
WinAppDriver.exe 80

It's on the backlog to add better /? support to WinAppDriver.exe for these commands

That will cause it to run on default IP with port 80
provided you are running cmd as admin if you want to bind to port 80

**Comment by denys-rwd** [comment]
Great !
