### ISSUE TITLE
Documentation: WinAppDriver.exe does not install with Appium as the home page states

### ISSUE THREAD

**Issue by ronjonesjr** [Microsoft/WinAppDriver#460]
It doesn't appear that WinAppDriver.exe installs along with Appium (Desktop 1.6.2) as is stated on the WinAppDriver home/project page.

**Comment by ronjonesjr** [comment]
I'm not sure if I should post this on the Appium issue board as I can't find anywhere on the Appium site where it indicates that it installs the WinAppDriver for you.  Instead, it points you to the specific driver page (e.g. WinAppDriver) for setup instructions.  It does that http://appium.io/docs/en/about-appium/getting-started/?lang=en.  And that's where a reader is misled by the statement on the WinAPpDriver home page.

**Comment by hassanuz** [comment]
Hi @ronjonesjr, 

This is a bug and is being tracked here - https://github.com/appium/appium/issues/11110.

**Comment by hassanuz** [comment]
Closing as original bug closed.
