### ISSUE TITLE
How to manage Oracle application sessions using WinAppDriver?

### ISSUE THREAD

**Issue by vfilipescu** [Microsoft/WinAppDriver#461]
Hello all!

I've just discovered WinAppDriver capabilities to automate Windows applications, 
My current effort is to investigate if WinAppDriver can properly handle various Oracle applications which all spawn from a single Oracle desktop application. So my questions are so far:

1. Are there any recommended ways to create and use dedicated WindowsDriver<WindowsElement> sessions ?

2. Should there be a one-to-one correspondence between one WindowsDriver<WindowsElement>session and one Oracle application ? 

3. Should I firstly create a app=Root session before any other session? And should it have such similar details?
  getAutomationName: null
  getTitle: Desktop
  getSessionDetails: {app=Root, platformName=Windows}
  getWindowHandle: 0x00010010
  getWindowHandles[]

Note: The main Oracle application into discussion here can be associated with such a session:
  getAutomationName: null
  getTitle: CS - Login
  getSessionDetails: {app=C:\Program Files (x86)\Java\jre1.8.0_25\bin\jp2launcher.exe, platformName=Windows}
  getWindowHandle: 0x00060B40
  getWindowHandles[0x00060B40]

4. Is there a Java library of methods to handle a complex flow of user interactions between such non-native Windows application sessions? 

Thanks in advance for any feedback on this matter!
Cheers,
Vladimir

**Comment by hassanuz** [comment]
Hi @vfilipescu,

Great to have you on-board. Please see the following sequential responses to your questions - 

1. You can refer to our [samples](https://github.com/Microsoft/WinAppDriver/tree/v1.0/Samples) here as a resource on session creation and handling. 

2. You can instantiate a session for each unique top-level Window you want to target - one way would be to use a desktop session and [attach to different app-windows accordingly](https://github.com/Microsoft/WinAppDriver/wiki/Frequently-Asked-Questions/289a8b325d3ddab9f08b4398c49163a9a136f607#when-and-how-to-attach-to-an-existing-app-window). 

3. This is commonly referred to as the desktop session, and would depend on your particular use case. You can read more about instantiating a desktop/root session on our FAQ [here](https://github.com/Microsoft/WinAppDriver/wiki/Frequently-Asked-Questions#when-and-how-to-create-a-desktop-session). It doesn't necessarily matter when you create the desktop session. 

4. You can take a look at our [Java Calculator Sample](https://github.com/Microsoft/WinAppDriver/tree/v1.0/Samples/Java/CalculatorTest) for further reference on this - I recommend leveraging the [Selenium-WebDriver JARs](https://www.seleniumhq.org/docs/03_webdriver.jsp#setting-up-webdriver-project) and the [appium java client library](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.appium%22%20AND%20a%3A%22java-client%22). You'll want to use the `import io.appium.java_client.windows.WindowsDriver;` namespace. 

Feel free to reach out for any further questions!
