### ISSUE TITLE
Why does WinAppDriver require windows developer mode on ?

### ISSUE THREAD

**Issue by rajeeshmenoth** [Microsoft/WinAppDriver#462]
Hi 
WinAppDriver mandates that the Windows 10 machine must have Developer Mode turned ON. Why is this a necessity? What components/features of the Developer mode does WinAppDriver use?
Is it possible to download the Windows 10 Developer mode package apart from a windows update?
Thanks

**Comment by hassanuz** [comment]
Hi @rajeeshmenoth,

This question has been answered [here](https://github.com/Microsoft/WinAppDriver/issues/165) already. 

There shouldn't be a need to download any developer mode packages once developer mode is enabled for WinAppDriver to function.

**Comment by rajeeshmenoth** [comment]
Hi,

Thank you @hassanuz 👍
