### ISSUE TITLE
hello，I want to simulate a keyboard to send a keyword   like “ENTER”，but  the winappdriver  client told me  

### ISSUE THREAD

**Issue by freechenh** [Microsoft/WinAppDriver#464]
### WinAppDriver::CommandHandler::Appium::HandleCommandAsMidPoint - Command  is not recognized
the log  like this
![1](https://user-images.githubusercontent.com/24238297/43182252-4565a630-9013-11e8-9858-6f29c179bd5f.png)
![2](https://user-images.githubusercontent.com/24238297/43182255-49407f32-9013-11e8-8072-6b12d5d1f43c.png)

**Comment by hassanuz** [comment]
Hi @freechenh,

driver.keyevent (appium/device/keyvent) isn't an API supported by WinAppDriver - we recommend using send_keys (/session/:sessionId/element/elementID/value) as you have been for this.

**Comment by freechenh** [comment]
think you @hassanuz  I will try it

**Comment by freechenh** [comment]
thank you @hassanuz
