### ISSUE TITLE
hello，I want to remote an windows app,but the winappdriver told me "unknown error Failed to locate opened application window with appId: E:\\Program Files (x86)\\Thunder Network\\Thunder\\Program\\thunderstart.exe, and processId: 4896",please help me

### ISSUE THREAD

**Issue by freechenh** [Microsoft/WinAppDriver#465]
hello，I want to remote an windows app,but the winappdriver told me "unknown error Failed to locate opened application window with appId: E:\\Program Files (x86)\\Thunder Network\\Thunder\\Program\\thunderstart.exe, and processId: 4896",please help me
![unknown error](https://user-images.githubusercontent.com/24238297/43201479-38198f2c-904b-11e8-88ca-f664784047fe.png)

**Comment by freechenh** [comment]
this is my code
![code](https://user-images.githubusercontent.com/24238297/43201529-5b18dcee-904b-11e8-8c28-9682b0f2ab99.png)

**Comment by hassanuz** [comment]
Hi @freechenh,

Thanks for reaching out. For questions regarding WinAppDriver error responses like this in particular, we added a new section on our Wiki to address - please refer to [here](https://github.com/Microsoft/WinAppDriver/wiki/Common-Error-Messages/d75af95531a8cae3d29d5f4aa1a540ca9f64165d#failed-to-locate-opened-application-window-with-appid--and-process-). 

If that doesn't solve it for you, please continue to keep us updated on this thread. 

Thanks
