### ISSUE TITLE
WinAppDriver v1.0 Release Support get list item but v1.1 Preview Release doesn't support fetch list item

### ISSUE THREAD

**Issue by Donglee26** [Microsoft/WinAppDriver#466]
I can able to get list data in WinAppDriver v1.0, But i can't get list data in v1.1 Preview Release

My Test case Method

public class UserListTest {
		
		UserListPage.initialiazeUserListPage();
		List userListItem = UserListPage.userListView.findElements(By.className("ListViewItem"));if(userListItem.size()!=0)
		if (userListItem.size() != 0) {
			for (int i = 0; i < userListItem.size(); i++) {
				for (WebElement e : userListItem.get(i).findElements(By.name("userName"))) {
					System.out.println(e.getText());
				}
			}
		} else
		{
			Assert.fail("Folder doesn't have any user.");
		}
	}

My Page Object Module

public class UserListPage extends AppiumUtil {
	
	public static UserListPage initialiazeUserListPage() {
		return PageFactory.initElements(driver, UserListPage .class);
	}

       @FindBy ( xpath = "//List[@AutomationId='UserLV']" )
	public static WebElement userListView;

}

**Comment by OzBob** [comment]
@Donglee26 how did you modify Appium to work with the v1.1 Preview Relase?

**Comment by hassanuz** [comment]
Closing ticket as Appium has been updated to point to the latest WinAppDriver version by default.
