### ISSUE TITLE
Sample code for testing windows desktop app 

### ISSUE THREAD

**Issue by ChillarAnand** [Microsoft/WinAppDriver#471]
From: https://github.com/appium/sample-code/issues/162

How is the [app value for calculated here](https://github.com/Microsoft/WinAppDriver/blob/master/Samples/Python/calculatortest.py#L28)? How to get that value for 3rd party windows desktop apps?

I am trying to run a windows desktop app with appium, I tried giving it full path to exe file which also didn't work.

**Comment by timotiusmargo** [comment]
Hi @ChillarAnand,

When you are testing your own UWP application wit the source code available, you can simply get the `app` value from `AppX\vs.appxrecipe` file under `RegisteredUserModeAppID` entry.

If you don't have the source code, you may also run `Get-AppxPackages` in PowerShell and try to deduce the value yourself.
