### ISSUE TITLE
How do I implement Button down/ Click and Hold feature of appium in C#?

### ISSUE THREAD

**Issue by hinakanthed** [Microsoft/WinAppDriver#475]
I am trying to automate a wpf application through appium in C#. I want to select a menu option from the Tools tab in my application but I can't find any c# example to click and hold for the element to be visible.

**Comment by timotiusmargo** [comment]
Hi @hinakanthed,

Can you have a look at the `MouseDownMoveUp` test below?
https://github.com/Microsoft/WinAppDriver/blob/v1.1-RC/Tests/WebDriverAPI/Mouse.cs#L117

You can try the following sequence instead to perform the click and hold mouse interaction:
```c#
session.Mouse.MouseMove(appNameTitle.Coordinates);
session.Mouse.MouseDown(null); // Pass null as this command omit the given parameter
Thread.Sleep(TimeSpan.FromSeconds(3)); // Or however long you need to hold it for
session.Mouse.MouseUp(null); // Pass null as this command omit the given parameter
```

**Comment by hinakanthed** [comment]
@timotiusmargo,
Thanks for the suggestion. I will give this a try.
