### ISSUE TITLE
WinAppDriver failed to up

### ISSUE THREAD

**Issue by denys-rwd** [Microsoft/WinAppDriver#48]
I have configured WinAppDriver to listen on external IP (static), sometimes after restart it fails to up with following error. The WinAppDriver is configured to start on log on.

![image](https://cloud.githubusercontent.com/assets/18639833/17173526/043768f8-5404-11e6-82e7-b36245f63079.png)

Thanks in advance

**Comment by alakshmi1030** [comment]
Port 80 is reserved for HTTP, can you please try with a different port?

**Comment by denys-rwd** [comment]
I closed the issue , as IP address can be configured `*`.
https://github.com/Microsoft/WinAppDriver/issues/39
