### ISSUE TITLE
XPath sometimes does not work for search by Automation ID

### ISSUE THREAD

**Issue by mbnovick** [Microsoft/WinAppDriver#484]
I searched for an element by looking for its Automation ID, and found it. I clicked another element, but this did not cause original element to disappear from view. Then I searched for original element again. If I search using same XPath as I used before, I can't find element. If I search by FindElementsByAccessibilityId, then I do find the element. I think using XPath should still find element.

Here is essential part of C# program I used:
`string xpath = "//*[@AutomationId='ReportWizardGeneral_FileName']";
string automationId = "ReportWizardGeneral_FileName";

var sourceBefore = session.PageSource;
var listBefore = session.FindElementsByXPath(xpath).ToList();

typesElt.Click();

var listAfter = session.FindElementsByXPath(xpath).ToList();
var listByAccessibilityId = 
	session.FindElementsByAccessibilityId(automationId).ToList();
var sourceAfter = session.PageSource;

int beforeCount = listBefore.Count;	// 1
int afterCount = listAfter.Count; // 0
int countByAccessibilityId = listByAccessibilityId.Count; // 1
`
I've attached relevant JSON wire protocol output, as well as extract of page source before the click and after the click. The main difference in page source is that after clicking on an element a dropdown menu appears, but it does not cover up element I want to search for. Dropdown menu contains a list. A list similar to this list also appears in another place in page source after the click.

[jsonWire.txt](https://github.com/Microsoft/WinAppDriver/files/2307582/jsonWire.txt)

[shortSourceBefore.txt](https://github.com/Microsoft/WinAppDriver/files/2307587/shortSourceBefore.txt)
[shortSourceAfter.txt](https://github.com/Microsoft/WinAppDriver/files/2307588/shortSourceAfter.txt)

**Comment by hassanuz** [comment]
Hi @mbnovick,

Can you try using the [UI Recorder ](https://github.com/Microsoft/WinAppDriver/releases/tag/UiR_v1.0-RC) and report back what the generated XPath query is? Depending on how you set up your session, you may have to truncate the root node.

**Comment by Chintzz** [comment]
Hi,
I know that it may sound a little weird but try to add a Thread.sleep() before the xpath statement and check if the element is found by winappdriver. I was facing a similar issue when trying to run a script on rdp but it was working fine locally. After a lot of trial and error I found out that it was due to the element not being available on the screen. 
If you are able to identify the element after adding thread.sleep() ,then I would suggest to use explicit wait from selenium as implicit wait doesn't solve the problem.

**Comment by mbnovick** [comment]
I tried the suggestion @Chintzz recommended to no avail. I added a Sleep of 5 seconds after the click, but that did not help.

I also used UI Recorder, as suggested by @hassanuz 

The XPath query generated by UI Recorder is:
"/Pane[@Name=\"Desktop 1\"][@ClassName=\"#32769\"]/Window[@Name=\"App 7.10.0.38 \"][@ClassName=\"Window\"]/Window[@Name=\"Generate Report\"][@ClassName=\"Window\"]/Custom[@AutomationId=\"wizard\"]/Pane[starts-with(@Name,\"WPFComponents.Reports.MultipleReportWindow.ViewModels.GeneralSet\")][@ClassName=\"ScrollViewer\"]/Custom[@ClassName=\"GeneralSettingsPageView\"]/Edit[@AutomationId=\"ReportWizardGeneral_FileName\"]"

The XPath query is also stored in attached file, as is XML generated by UI Recorder for element of interest.
[uirecorderXpath.txt](https://github.com/Microsoft/WinAppDriver/files/2309682/uirecorderXpath.txt)
[uirecorderXml.txt](https://github.com/Microsoft/WinAppDriver/files/2309686/uirecorderXml.txt)

**Comment by Chintzz** [comment]
@mbnovick  - Try using @Name instead of @name. It should work fine.

**Comment by mbnovick** [comment]
It looks like GitHub is replacing uppercase @Name with lowercase@name. When I wrote uppercase and then look at Preview, I see name in lowercase. The file I attached earlier shows Name in uppercase. In any case I only use AutomationId to identify element, as mentioned in the C# code mentioned when I opened the issue. So it won't help to use @Name instead of @name, since I don't use either of them. The problem is "Why does WinAppDriver sometimes not find element when using XPath for AutomationId, when in same circumstances it always finds element if I search for AccessiblityId without using XPath?"

**Comment by mbnovick** [comment]
It looks like I need to write `@Name` and `@name` in GitHub, because if I write Name after at-sign then GitHub thinks I'm referring to GitHub user called "name". That explains uppercase/lowercase confusion, but still does not explain my original problem occurs.

**Comment by Chintzz** [comment]
@ mbnovick,
Try the following xpath
//*[contains(@AutomationId,'ReportWizardGeneral_FileName')]

**Comment by mbnovick** [comment]
But I can find the element if I use FindElementsByAccessibilityId. And I'm only trying to find the element at this point, not trying to click on it. Finally as far as I know the element is clickable at this point. It seems like there should be a different explanation of what's causing the problem.

**Comment by hassanuz** [comment]
Hi @mbnovick,

Would it be possible for you to share the app in question and the WinAppDriver script being used for this test?  

If it contains sensitive information, you can email it to hassan.uraizee@microsoft.com or winappdriverteam@microsoft.com if possible. This would help us reproduce this issue and resolve it as soon as possible.

Thanks

**Comment by timotiusmargo** [comment]
Hi @mbnovick,

We'd like to help you further by addressing this particular issue you reported. The information you provided so far is insufficient for us to identify or to reproduce the problem. It will be great if you can privately share the application and the steps/script to reproduce the issue so that we can make a proper fix for it.

**Comment by mbnovick** [comment]
I can't share the application I'm using because of security reasons. I think it will be necessary to close this issue for now. Maybe it can be reopened in future if WinAppDriver becomes open source so I can debug the problem I observed.

Another possibility would be to provide me with a version of WinAppDriver which creates log files that could be used to debug the problem. I still might have security issues releasing the data from the resulting logs. At this point I think there's no alternative other than to close the issue.
