### ISSUE TITLE
MouseWheel on some WindowsElement

### ISSUE THREAD

**Issue by Soloveykos** [Microsoft/WinAppDriver#485]
Is it possible to do MouseWheel on some WindowsElement? Could you please show example?
 - Actually I've found solution to click on scroll button PageDown. But would like to know if it's possible to MouseWheel scrolling on some WindowsElement.

**Comment by Fabian-t800** [comment]
Hello @hassanuz .
I've stumbled upon a similar issue.
I've got an element a volume bar, that I'd need to scroll using a mouse scroll. 
The element `IsScrollItemPatternAvailable:`	`true`, so technically I should be able to.
The import I've used is:
`from selenium.webdriver.common.touch_actions import TouchActions`
`tactions = TouchActions(self.driver)
        tactions.scroll(10, 10)
        tactions.perform()`

Please let me know if you would require any further information.
Thank in advance for your response!
Warm regards,
Fabian

**Comment by Soloveykos** [comment]
yep, thanks, already used.

чт, 6 февр. 2020 г. в 16:17, Fabian-t800 <notifications@github.com>:
