### ISSUE TITLE
NuGet Version causing problems

### ISSUE THREAD

**Issue by ycoliveira** [Microsoft/WinAppDriver#487]
Hey there, I've updated my solution NuGets and I started to have some problems with the DesiredCapabilities class.
It says ""Use of DesiredCapabilities has been deprecated in favor of browser-specific Options classes""
But I didnt found any solution for this for the winappdriver.
Since all the examples here still uses the desiredCapabilities class, how can I solve this problem?

**Comment by hassanuz** [comment]
Hi @ycoliveira,

Which NuGet packages are you using?

**Comment by ycoliveira** [comment]
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Appium.WebDriver" version="3.0.0.2" targetFramework="net452" />
  <package id="Castle.Core" version="4.3.1" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="11.0.2" targetFramework="net452" />
  <package id="Selenium.Support" version="3.14.0" targetFramework="net452" />
  <package id="Selenium.WebDriver" version="3.14.0" targetFramework="net452" />
  <package id="SpecFlow" version="2.4.0" targetFramework="net452" />
  <package id="SpecFlow.MsTest" version="2.4.0" targetFramework="net452" />
  <package id="System.ValueTuple" version="4.3.0" targetFramework="net452" />
</packages>

**Comment by ycoliveira** [comment]
<package id="Appium.WebDriver" version="3.0.0.2" targetFramework="net452" />
  <package id="Castle.Core" version="4.3.1" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="11.0.2" targetFramework="net452" />
  <package id="Selenium.Support" version="3.14.0" targetFramework="net452" />
  <package id="Selenium.WebDriver" version="3.14.0" targetFramework="net452" />
  <package id="SpecFlow" version="2.4.0" targetFramework="net452" />
  <package id="SpecFlow.MsTest" version="2.4.0" targetFramework="net452" />
  <package id="System.ValueTuple" version="4.3.0" targetFramework="net452" />

**Comment by ycoliveira** [comment]
<package id="Appium.WebDriver" version="3.0.0.2" targetFramework="net452" />
  <package id="Castle.Core" version="4.3.1" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="11.0.2" targetFramework="net452" />
  <package id="Selenium.Support" version="3.14.0" targetFramework="net452" />
  <package id="Selenium.WebDriver" version="3.14.0" targetFramework="net452" />
  <package id="SpecFlow" version="2.4.0" targetFramework="net452" />
  <package id="SpecFlow.MsTest" version="2.4.0" targetFramework="net452" />
  <package id="System.ValueTuple" version="4.3.0" targetFramework="net452" />

**Comment by ycoliveira** [comment]
Appium.WebDriver" version="3.0.0.2" targetFramework="net452" 
Castle.Core" version="4.3.1" targetFramework="net452"
Newtonsoft.Json" version="11.0.2" targetFramework="net452"
Selenium.Support" version="3.14.0" targetFramework="net452"
Selenium.WebDriver" version="3.14.0" targetFramework="net452" 
SpecFlow" version="2.4.0" targetFramework="net452" 
SpecFlow.MsTest" version="2.4.0" targetFramework="net452"
System.ValueTuple" version="4.3.0" targetFramework="net452"

**Comment by hassanuz** [comment]
Hi @ycoliveira,

Can you try using an older version of Selenium - specifically **version 3.0.1** and report back.

Thanks

**Comment by ycoliveira** [comment]
Working fine after downgrading Selenium to version 3.0.1

**Comment by hassanuz** [comment]
Great to hear!

**Comment by MihaMarkic** [comment]
But shouldn't this be addressed somehow? Sticking to (now very) old Selenium isn't a long term solution, or?
