### ISSUE TITLE
Newtonsoft.json

### ISSUE THREAD

**Issue by Soloveykos** [Microsoft/WinAppDriver#492]
Due to project reasons we have to use Newtonsoft.json version 10. As far as we can see the Appium uses Newtonsoft.json version 9. Could you please let us know if it's okay to use Newtonsoft.json 10? Maybe some issues could appear?

**Comment by hassanuz** [comment]
This will be a better question for the [Appium ](https://github.com/appium/appium/issues)/ Selenium project - so we can't confirm if anything will break using Newtonsoft.json version 9. 

It wouldn't hurt to try it out anyway, so if you do get a chance, please feel free to report back your findings!

**Comment by Soloveykos** [comment]
Seems no big issues found with using Newtonsoft.Json version 10, right now the tests are executed.

**Comment by hassanuz** [comment]
Great, thanks for reporting back!
