### ISSUE TITLE
is it possible to launch multiple desktop app?

### ISSUE THREAD

**Issue by barisgul** [Microsoft/WinAppDriver#495]
Hi,
I have more than one application to test. I want to launch two applications. (for example calculator and notepad.exe)
When I set capability as  **`appCapabilities.SetCapability("app", "Root");`** , i can handle both of applications but I dont want to use Root tag.
Can I use as below? Or another way?
**`appCapabilities.SetCapability("app", NotePad.exe);`
`appCapabilities.SetCapability("app", Calculator.exe);`
`session=new WindowsDriver<WindowsElement>(new Uri("http://10.X.X.X:4723/wd/hub"),                   appCapabilities);`**

or alternativly use different capabilties  as below?
**`capability1.SetCapability("app", NotePad.exe);` 
`capability2.SetCapability("app", Calculator.exe);`**

**Comment by PandaMagnus** [comment]
I don't see why the second one wouldn't work, as long as you are very explicit in your tests which one is being called for any given FindElement. If I have some time, I'll try it out this weekend, but it should be a simple enough test.

**Comment by barisgul** [comment]
Hello @PandaMagnus and @khouzam 
Thanks for your answers. I mean, can I use only one session for two applications? I want to manage multiple applications with only one driver. 
I have attached to notepad application while calculator was running and this solved my problem for now.
