### ISSUE TITLE
Collapsed all window on screen after "click". 

### ISSUE THREAD

**Issue by Schepetkov** [Microsoft/WinAppDriver#498]
Hell all, after I call "click" all window on screen is collapsed.
try:
session.Mouse.MouseMove(null, 1038, 404);
session.Mouse.Click(null);

and
Actions action = new Actions(session);
action.Click().Perform();

Result alway same. Can someone help me?

**Comment by hassanuz** [comment]
Hi @Schepetkov,

Would it be possible for you to share the WinAppDriver.exe log + your display DPI setting?

**Comment by Schepetkov** [comment]
Hi @hassanuz C:\Program Files (x86)\Windows Application Driver log.txt is empty. DPI is resolution? (1920 x 1080).

**Comment by Schepetkov** [comment]
Windows Application Driver listening for requests at: http://127.0.0.1:4723/
Press ENTER to exit.
==========================================
POST /session HTTP/1.1
Accept: application/json, image/png
Connection: Keep-Alive
Content-Length: 142
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723


HTTP/1.1 200 OK
Content-Length: 165
Content-Type: application/json

{"sessionId":"EF15320D-F360-4E37-897D-8527C990A3D9","status":0,"value":{"app":"C:\\Program Files (x86)\\Teslasuit\\1.0\\bin\\Launcher.exe","platformName":"Windows"}}


==========================================
POST /session/EF15320D-F360-4E37-897D-8527C990A3D9/timeouts HTTP/1.1
Accept: application/json, image/png
Content-Length: 31
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"type":"implicit","ms":1500.0}
HTTP/1.1 200 OK
Content-Length: 63
Content-Type: application/json

{"sessionId":"EF15320D-F360-4E37-897D-8527C990A3D9","status":0}


==========================================
POST /session/EF15320D-F360-4E37-897D-8527C990A3D9/element HTTP/1.1
Accept: application/json, image/png
Content-Length: 33
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723


HTTP/1.1 200 OK
Content-Length: 109
Content-Type: application/json

{"sessionId":"EF15320D-F360-4E37-897D-8527C990A3D9","status":0,"value":{"ELEMENT":"42.722348.4.-2147483644"}}


==========================================
POST /session/EF15320D-F360-4E37-897D-8527C990A3D9/moveto HTTP/1.1
Accept: application/json, image/png
Content-Length: 44
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723


HTTP/1.1 200 OK
Content-Length: 63
Content-Type: application/json

{"sessionId":"EF15320D-F360-4E37-897D-8527C990A3D9","status":0}


==========================================
POST /session/EF15320D-F360-4E37-897D-8527C990A3D9/click HTTP/1.1
Accept: application/json, image/png
Content-Length: 12
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723


HTTP/1.1 200 OK
Content-Length: 63
Content-Type: application/json

{"sessionId":"EF15320D-F360-4E37-897D-8527C990A3D9","status":0}


==========================================
DELETE /session/EF15320D-F360-4E37-897D-8527C990A3D9 HTTP/1.1
Accept: application/json, image/png
Host: 127.0.0.1:4723


HTTP/1.1 200 OK
Content-Length: 12
Content-Type: application/json

{"status":0}

**Comment by Schepetkov** [comment]
I finded bug, when I run first time all work well, but second try collapse all window for fix I need restart WinAppDriver.exe.

**Comment by hassanuz** [comment]
Hi @Schepetkov,

Can you answer the following questions: 

1) Are you running multiple-monitors? 
2) To change Display DPI settings, you can right click on Desktop -> Display Settings -> then adjust the "Change the size of text, apps, and other items" percentage to **100%**.
3) Can you share which coordinates you are trying to click? 

Thanks

**Comment by Schepetkov** [comment]
Hi @hassanuz , My DPI settings is 100% percent and I use only one monitor, about my coordinates I use "inspect.exe" and get current coordinate app button what I need click. How I write before if I start first time "WinAppDriver" all work well, but after second run my test when driver try click on the same button all my window is collapsed. How can I check why it hipping?

**Comment by hassanuz** [comment]
Hi @Schepetkov,

Can you try sharing your script code? We would like to try and reproduce this on our end.

Thanks

**Comment by hassanuz** [comment]
Hi @Schepetkov,

I'm marking this issue as closed. Please feel free to reopen if this persists. Also if you would f eel more comfortable privately sharing your script code (or any repro) please feel free to reach out to me directly via hassan.uraizee@microsoft.com 

Thanks
