### ISSUE TITLE
Getting FPS for an UWP App

### ISSUE THREAD

**Issue by sandeepdroid** [Microsoft/WinAppDriver#499]
Is there a good way to get/dump the FPS(frames per second) data for an UWP Application (for further analysis) while performing some operation using the WinAppDriver.

**Comment by hassanuz** [comment]
Hi @sandeepdroid,

You could look into using the [Windows Performance Toolkit](https://blogs.msdn.microsoft.com/ntdebugging/2008/04/03/windows-performance-toolkit-xperf/).
