### ISSUE TITLE
Support automation id

### ISSUE THREAD

**Issue by fasterfish** [Microsoft/WinAppDriver#5]
Good day!
Could you add support for searching elements by UI Automation ID?

**Comment by timotiusmargo** [comment]
Good day @fasterfish!

We have already supported searching element (and elements) using Automation ID. This is done through `AppiumWebElement.FindElementByAccessibilityId("AutomationId")`. For example, the following 2 lines search the element using Automation ID in the [AlarmClockTest](https://github.com/Microsoft/WinAppDriver/blob/master/Samples/AlarmClockTest/Scenario.cs) sample:

`
AlarmClockSession.FindElementByAccessibilityId("AddAlarmButton").Click();
AlarmClockSession.FindElementByAccessibilityId("AlarmNameTextBox").Clear();
`

More instruction on how to setup your test project can be found on https://github.com/Microsoft/WinAppDriver#create-test-project

**Comment by fasterfish** [comment]
Ok, thank you.
