### ISSUE TITLE
Command keys is not recognized

### ISSUE THREAD

**Issue by alexandru007** [Microsoft/WinAppDriver#50]
When trying to Press a key using Keyboard.PressKey(string KeyToPress) method I get a message that keys command is not recognized.

public void SendTABKeys()
        {
            AppSession.Keyboard.PressKey("Tab");
        }

==========================================
POST /session/E492B7B2-5F16-40F3-AB68-9F3B3046A32A/keys HTTP/1.1
Accept: application/json, image/png
Content-Length: 23
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"value":["T","a","b"]}
### WinAppDriver::CommandHandler::Session::HandleCommandAsMidPoint - Command keys is not recognized
HTTP/1.1 404 Not Found
Content-Length: 141
Content-Type: application/json

{"status":9,"value":{"error":"unknown command","message":"Command not recognized: POST: /session/E492B7B2-5F16-40F3-AB68-9F3B3046A32A/keys"}}

**Comment by timotiusmargo** [comment]
This is now implemented in v0.6-beta. A sample can be found in https://github.com/Microsoft/WinAppDriver/blob/v0.6-beta/Tests/W3CWebDriver/Keys.cs#L125

Note how sending a "Tab" key is done through a special unicode character constant. E.g.
`session.Keyboard.PressKey(OpenQA.Selenium.Keys.Home` + OpenQA.Selenium.Keys.Tab);`

**Comment by alexandru007** [comment]
Thanks, with v0.6-beta release sending keys works fine.
