### ISSUE TITLE
Is get screenshot implemented?

### ISSUE THREAD

**Issue by anunay1** [Microsoft/WinAppDriver#504]
I am trying to use get screen shot, but it shows an error "{"status":9,"value":{"error":"unknown command","message":"Command not recognized: GET: /session/8BEC409A-410D-459D-9AA3-69F34D4D7BDA/context"}}"

**Comment by hassanuz** [comment]
Hi @anunay1,

Screenshots are fully supported and implemented, you can check our GitHub repo for an example on [getting an element screenshot](https://github.com/Microsoft/WinAppDriver/blob/35a659232060a6e436cbb8393ae9a09bab12bc89/Tests/WebDriverAPI/Screenshot.cs#L42) or [a session screenshot](https://github.com/Microsoft/WinAppDriver/blob/35a659232060a6e436cbb8393ae9a09bab12bc89/Tests/WebDriverAPI/Screenshot.cs#L125).

However, somehow your code invoked a different endpoint that isn't actually supported. If you could share the code you wrote that invoked that command, that would be helpful. 

Thanks
