### ISSUE TITLE
Unable to select specific object

### ISSUE THREAD

**Issue by SanderW1989** [Microsoft/WinAppDriver#509]
The listed tables/objects on the right screen are returned at random whenever I run my test. 
![selectissue](https://user-images.githubusercontent.com/39696741/46806647-70596600-cd68-11e8-926b-c87ac09030d1.jpg)

Sometimes when I use XPath[1] it returns the first object/table, other times it returns the 3rd or 4th. Is there a way to resolve this sothat it will always return the same element?

The code I use is: 

//Sort by title
session.FindElementByXPath("//Tab[@ClassName =\"Pivot\"]/TabItem[@Name=\"Title\"][@ClassName=\"PivotItem\"]").Click();

//Select first table
session.FindElementByXPath("//Pane[@AutomationId =\"ScrollViewer\"]/Pane[@AutomationId=\"ScrollViewer\"][1]").Click();
 
//Sort by title
session.FindElementByXPath("//Tab[@ClassName =\"Pivot\"]/TabItem[@Name=\"Title\"][@ClassName=\"PivotItem\"]").Click();
  
//Select second table
session.FindElementByXPath("//Pane[@AutomationId =\"ScrollViewer\"]/Pane[@AutomationId=\"ScrollViewer\"][2]").Click();

**Comment by hassanuz** [comment]
Hi @SanderW1989,

It could be that the XPath being generated is incorrect - could you please share a [page source ](https://github.com/Microsoft/WinAppDriver/blob/35a659232060a6e436cbb8393ae9a09bab12bc89/Tests/WebDriverAPI/Source.cs#L39)as well? 

Thanks!
