### ISSUE TITLE
Calculator sample fails with Unimplemented Command

### ISSUE THREAD

**Issue by quincycs** [Microsoft/WinAppDriver#51]
I am just starting to evaluate this project, and havn't yet gotten anything to work (this is my first thing I tried).

Feels like somethings wrong with the sample?  Or the sample requires a newer driver than what is available?

"Unexpected error. Unimplemented Command: xpath locator strategy is not supported"

![image](https://cloud.githubusercontent.com/assets/2924643/17271105/ecd8c800-5638-11e6-9bea-c963a4868d92.png)

**Comment by NickAb** [comment]
What version of driver do you use? According to https://github.com/Microsoft/WinAppDriver/issues/6#issuecomment-233401873 XPath should have been added in v0.4-beta

**Comment by quincycs** [comment]
I just downloaded everything today (this morning).  So I assume latest.

**Comment by NickAb** [comment]
Not necessary the latest. It depends on a download link. A download link on a [README page](https://github.com/Microsoft/WinAppDriver) seems to point to different installer than a download link on a [releases page](https://github.com/Microsoft/WinAppDriver/releases). The latest version should be available at https://github.com/Microsoft/WinAppDriver/releases/latest

**Comment by quincycs** [comment]
Ohhhhhhhh

**Comment by quincycs** [comment]
@NickAb thx, i'll close this one and open a new issue that i'm seeing on v0.4
