### ISSUE TITLE
org.openqa.selenium.remote.RemoteWebElement cannot be cast to io.appium.java_client.windows.WindowsElement

### ISSUE THREAD

**Issue by sunnysachdeva** [Microsoft/WinAppDriver#510]
Hi ,

I am using Java binding of WinAppDriver and while finding element , I am getting below exception
**org.openqa.selenium.remote.RemoteWebElement cannot be cast to io.appium.java_client.windows.WindowsElement**

```
private static WindowsDriver<WindowsElement> winDriver = null;
@BeforeSuite
	public void bs() throws InterruptedException, MalformedURLException{
		try {
			launchApplication();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
public static void launchApplication() throws InterruptedException, MalformedURLException{
		DesiredCapabilities desktopCapabilities = new DesiredCapabilities();
		desktopCapabilities.setCapability("app", sqlPath);
		winDriver=new WindowsDriver<WindowsElement>(new URL("http://127.0.0.1:4723"), desktopCapabilities);
		winDriver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
		Thread.sleep(2000);
	}

@Test(enabled=true)
	public void a(){
		System.out.println(winDriver.getTitle());
		WindowsElement e=winDriver.findElementByXPath("//Button[@AutomationId='connect']");
		e.click();
	}
```

**Comment by hassanuz** [comment]
Looks like this is a binding issue (specific to Appium Java bindings) - can you try taking a look at this [thread over here](https://github.com/appium/java-client/issues/774)?

If that isn't the same, feel free to submit a newer ticket there. 

Thanks

**Comment by jshinn6788** [comment]
I am also getting the same issue. 

public class WindowsDriverBase {

    protected  WindowsDriver driver;
    
    WindowsElement edit_txt = (WindowsElement) driver.findElementByAccessibilityId("13");



    @Test
    public void startPower() {
        try {
            DesiredCapabilities appCapabilities = new DesiredCapabilities();
            appCapabilities.setCapability("app", "C:\\windows\\notepad.exe");
            driver = new WindowsDriver<WindowsElement>(new URL("http://127.0.0.1:4723"), appCapabilities);
            Assert.notNull(driver);
            edit_txt.sendKeys("testing");
           // driver.findElementByAccessibilityId("13").sendKeys("simlab1");
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("PowerMHS did not launch");
        }
    }
}
