### ISSUE TITLE
Unable to locate element on child window 

### ISSUE THREAD

**Issue by buscseik** [Microsoft/WinAppDriver#512]
I use MicroSIP client for my test automation and I have difficulty to find an element by xpath.
You can see the element that I am looking for on the picture. The LegacyAccessible.Value property that I am looking for. You can see also the source of the page in attached file.
[Source.txt](https://github.com/Microsoft/WinAppDriver/files/2507835/Source.txt)
![example](https://user-images.githubusercontent.com/20754053/47387917-b0293180-d708-11e8-8fa1-f4ec6f72a302.png)

I try to use the following xpath locator, but it fails
`//*[contains(@LegacyAccessible.Value,"413")]`

Any one has any suggestion what could be the problem?

**Comment by buscseik** [comment]
Hi @hassanuz,

Yes, I would like to evaluate the value stored in LegacyAccessible.Value. 
Also same value is being stored in Value.Value.  
I have tried already to fetch source, (source has been attached) and it does not contain any relevant information.

**Comment by hassanuz** [comment]
Hi @buscseik,

Can you try reattaching the source? Doesn't look like it went through. 

Thanks,
Hassan

**Comment by buscseik** [comment]
Hi @hassanuz ,

Here is the source:
[Source.txt](https://github.com/Microsoft/WinAppDriver/files/2507835/Source.txt)

Thanks,
Krisz

**Comment by hassanuz** [comment]
Hi @buscseik ,

Can you try using the [GetAttribute API](https://github.com/Microsoft/WinAppDriver/blob/35a659232060a6e436cbb8393ae9a09bab12bc89/Tests/WebDriverAPI/ElementAttribute.cs#L46) to fetch and confirm the Legacy value?

This is assuming you only want to evaluate the legacy value of a known element.
