### ISSUE TITLE
Notepad Sample issue and others - No route found. Setting content type to 'text/plain'

### ISSUE THREAD

**Issue by eliassal** [Microsoft/WinAppDriver#513]
No single solution is running in C# directory works. 
After trying several times the notepas solution provided in the zip file, using Faslabs.zip fil to revert to an old version as indicated at
https://github.com/appium/appium-dotnet-driver/issues/217 for resolving the 'Dispose' issue
Now whenever I run a test method, I get

> NotepadTest.ScenarioEditor.ClassInitialize threw exception. OpenQA.Selenium.WebDriverException: OpenQA.Selenium.WebDriverException: Unexpected error. The URL '/session' did not map to a valid resource.

Then I decided to hand code something very basic andI tried a very very simple basic test as follows

> DesiredCapabilities appCapabilities = new DesiredCapabilities();
> appCapabilities.SetCapability("app", @"C:\Windows\System32\notepad.exe");
> NotepadSession = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), appCapabilities);
> NotepadSession.FindElementByClassName("Edit").SendKeys("This is some text");
> 
> 

I am sure that appium is listening as i did a telnet to 127.0.0.1 port 4723, The message in the appium server log is

> No route found. Setting content type to 'text/plain'

in the Testmethod error log in Visual studio the message is

> Message: Test method CodedUIAppium.CodedUITest1.EditorEnterTextLocal threw exception:
> OpenQA.Selenium.WebDriverException: Unexpected error. The URL '/session' did not map to a valid resource
> 

Again, typing in the windows run dialogbox
C:\Windows\System32\notepad.exe
notepad opens without any issue. **What is missing?**

**Comment by hassanuz** [comment]
Hi @eliassal,

Do you mind downloading the latest [release](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.1) of WinAppDriver, running it locally (without Appium), and reporting back the behavior then running the same test code? 

If you can provide the following, that would be super helpful as well:

- Windows Build (start -> "winver") 
- WinAppDriver.exe logs

Thanks!

**Comment by 0GiS0** [comment]
Hi there!

I had the same behaviour that @eliassal said. And It's probably because you are launching appium instead of WinAppDriver.exe to execute your tests. Try to launch WinAppDriver.exe located in C:\Program Files (x86)\Windows Application Driver. I put that path as part of my enviroment variable Path.

Cheers,

**Comment by jshinn6788** [comment]
Hi, I'm getting an error:
![image](https://user-images.githubusercontent.com/38893571/59215856-563a8680-8b88-11e9-88e7-6737b3009cd7.png)
