### ISSUE TITLE
Parallel execution of one application

### ISSUE THREAD

**Issue by taddeuz** [Microsoft/WinAppDriver#515]
I want to run my tests parallel and I have to open three instances of the same application at the same time (but with other configuration of the app, but that's not the point). My code executes three applications (I have executed the WinAppDriver.exe with different ports on the Remote Machine). I use a ThreadLocal WindowsDriver and I want to interact with "removeDriver.get()" with each of the three apps. 
All three applications are openend, but when I try to interact with the applications, there are intersections. For example, if I enter text in application 1, 2 and 3, then the text will be entered in application 1 or 2 but not in three. So, it seems that the driver uses the wrong session/application? Maybe I have to switch to the active window of the current used driver? All three applications 
lie one above the other.

Here is my code:

```java
protected static ThreadLocal<WindowsDriver> remoteDriver = new ThreadLocal<WindowsDriver>();

    private static Logger log;
    
    static {
        log = Logger.getLogger(MyClass.class);
    }
    
    
    public static void start(String client) {
		try { 
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability("app", "pathtomyapp" + id);
            capabilities.setCapability("platformName", "Windows");
            capabilities.setCapability("deviceName", "WindowsPC");
            String remoteUrl = "http://" + config.getHost() + ":" + config.getPort() + "/wd/hub";
            log.info("Remote URL: " + remoteUrl);
            WindowsDriver driver = new WindowsDriver<WindowsElement>(new URL(remoteUrl), capabilities);
           	driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
           	remoteDriver.set(driver);
        }catch(Exception e){
        	e.printStackTrace();
        } finally {
        }
    }
    
    public static void stop() {
    	getDriver().quit();
    }
    
    public static void enterText(String element, String input) {
    	remoteDriver.get().findElementByAccessibilityId(element).sendKeys(input);
    }
```

**Comment by khouzam** [comment]
Hi @taddeuz,

While some things can occur in parallel it is not recommended to run multiple tests in this way. The way input (mouse, keyboard) works, it by sending keystrokes as it would from a physical keyboard. So when you sendKeys to an element, what actually happens is that the element is given focus and keys are sent, but if in the middle of sending those keys another element on the system gets focus the rest of the keys will be sent to the element that has focus, just as if someone had take the mouse as you're typing and selected another application. The same is true for mouse interactions, for example when you do a click, the mouse pointer will move to the location of the element and issue a click, just like a user would do.

If you were to run the tests in parallel to three different machines, then that should work, but on the same machine, you will have such conflicts.

**Comment by taddeuz** [comment]
So, there is no way to run the tests in parallel on one machine?

With selenium webdriver it is possible to run Tests in parallel with different browsers on one VM. Why its not possible with WAD?

I used winium before implementing WAD. winium has a Session problem with multiple executions, so I switched to WAD - because parallel executions should be possible (according to the wiki and some posts).

**Comment by taddeuz** [comment]
So, I have to use an own machine / VM for each application?

**Comment by hassanuz** [comment]
@taddeuz,

You can run tests concurrently, but as mentioned some interactions could conflict between different applications if more than one is targeted for focus or interaction simultaneously. This is independent from the testing framework if leveraging the operating system input stack and app focus.

**Comment by githubautocro** [comment]
> @khouzam
> 
> So, there is no way to run the tests in parallel on one machine?
> 
> With selenium webdriver it is possible to run Tests in parallel with different browsers on one VM. Why its not possible with WAD? Of course, Selenium is an other framework.
> 
> I used winium before implementing WAD. winium has a Session problem with multiple executions, so I switched to WAD - because parallel executions should be possible (according to the wiki and some posts).
> 
> Is there a way to switch to the application window of used session?

Yes, you can run parallel test on the same machine using winapp driver.
Just make sure you use different user sessions, and different winappdriver ports per session, you can set a user environment variable for the port value.
You get to also have in consideration in your code the session user when closing processes related to the apps you are testing and the winappdriver process.
Regards,
Orlando
