### ISSUE TITLE
Send_keys doesn't work in winapp driver with python 

### ISSUE THREAD

**Issue by Dwipro** [Microsoft/WinAppDriver#518]
Hi Team,
i am was doing automation windows application using python with Winapp driver using python .
when ever i am trying to send some text using this command self.driver.find_element_by_class_name("TextBox").send_keys("Test") , unable to send any text to application. 
i am writing script in python 2.7 , 
what ever requirement was given in instruction  for winapp driver  i have fulfilled . 
Can you please have look on this issue , i am stuck in middle of automation.

Regard,
Deepak kushwaha

**Comment by hassanuz** [comment]
Hi @Dwipro,

Can you provide the logs from WinAppDriver.exe? I've added the help wanted label to see if anyone from the community can chime in with a python example. 

Thanks

**Comment by Dwipro** [comment]
Hi hassanuz ,

Thanks for quick response, i have uninstalled Winapp driver and downloaded from GitHub V1.0  release , now it's working , send_keys working fine

**Comment by hassanuz** [comment]
Thanks for the update @Dwipro! Closing this issue.
