### ISSUE TITLE
How to get the first and last child? Need info 

### ISSUE THREAD

**Issue by anunay1** [Microsoft/WinAppDriver#522]
I want to get the first and last child of an element. 
Can you please let me know how can I do that? 

![image](https://user-images.githubusercontent.com/7989610/48704083-afa68c80-ec1b-11e8-9524-d2049b6fa06f.png)

**Comment by anunay1** [comment]
Thanks, for me xpath itself is not working, below is the xpath that is get from xpath recorder: 

string xp4 = "/Pane[@Name =\"Desktop 1\"][@ClassName=\"#32769\"]/Window[@Name=\"ABB.Robotics.Apps.Shell\"][@ClassName=\"ApplicationFrameWindow\"]/Window[@Name=\"ABB.Robotics.Apps.Shell\"][@ClassName=\"Windows.UI.Core.CoreWindow\"]/Pane[@AutomationId=\"SyntaxEditorControl\"]/Edit[@AutomationId=\"EditorView-Lower\"][@Name=\"Editor View\"]/Pane[@AutomationId=\"EditorLineNumberMargin\"][@Name=\"Editor Line Number Margin\"]";

And the error that I get from the server: 
==========================================
POST /session/12234DF5-3D65-4FCD-9199-669817E48733/element HTTP/1.1
Accept: application/json, image/png
Content-Length: 436
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"using":"xpath","value":"/Pane[@Name =\"Desktop 1\"][@ClassName=\"#32769\"]/Window[@Name=\"ABB.Robotics.Apps.Shell\"][@ClassName=\"ApplicationFrameWindow\"]/Window[@Name=\"ABB.Robotics.Apps.Shell\"][@ClassName=\"Windows.UI.Core.CoreWindow\"]/Pane[@AutomationId=\"SyntaxEditorControl\"]/Edit[@AutomationId=\"EditorView-Lower\"][@Name=\"Editor View\"]/Pane[@AutomationId=\"EditorLineNumberMargin\"][@Name=\"Editor Line Number Margin\"]"}

HTTP/1.1 404 Not Found
Content-Length: 139
Content-Type: application/json

{"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}

**Comment by anunay1** [comment]
can i get a response

**Comment by moonkey124** [comment]
First search for your '"Editor Line Number Margin" line number margin' element. After that all the children of this element seem to have the same class. Lets just assume the class is a TextBox. So you will now search for all elements with the class name coming after "Editor Line...". A list with all the textbox elements will be returned and you simply select the first and the last one.

Example:
```
var editorLineNumberElement = session.FindElementByAccessibilityId("specialAutomationIdYouGave");
var textBoxElements = editorLineNumberElement.FindElementsByClassName("TextBox");

var firstElement = textBoxElements.FirstOrDefault();
var lastElement = textBoxElements.LastOrDefault();

**Comment by anunay1** [comment]
That a ton the above code works for me
