### ISSUE TITLE
Verify browser opens up by Winappdriver

### ISSUE THREAD

**Issue by taitranvungle** [Microsoft/WinAppDriver#527]
I am using winappdriver to automate my Windows form app. There is a case that it need to click on a button then a web browser open up. Please advise me how to handle and work with this browser as selenium does. I am using python to develop my tests. Thank you!

**Comment by hassanuz** [comment]
Hi @taitranvungle,

Once the browser is open, you can create a new app session for the browser window and [switch to it](https://github.com/Microsoft/WinAppDriver/wiki/Frequently-Asked-Questions/289a8b325d3ddab9f08b4398c49163a9a136f607#when-and-how-to-attach-to-an-existing-app-window).

**Comment by rajivsai92** [comment]
How to create a browser session???

**Comment by jsaujla** [comment]
@taitranvungle could you please explain how you handle this situation? Have you used WinAppDriver and Selenium WebDriver both libraries?
I mean you use WinAppDriver to automate windows application actions and once web browser opened you use Selenium WebDriver and control already opened web browser session?
If above is true then could you please share how you achieve it?

**Comment by taitranvungle** [comment]
I create a new web driver instance using MicrosoftWebDriver at the first, then create a new WinAppDriver instance and work on it.
At the checkpoint, a button on Win app is pressed then a new tab of browser open up in existing web driver, we only need to switch to this new tab and verify items on it.
That's it.

**Comment by jsaujla** [comment]
@taitranvungle My test scenario starts with windows application. I create an object of "WindowsDriver", initialize it and windows application opens. I perform few test steps then click on a button which opens a new web browser window. So now WindowsDriver can't handle it. I need to know how you handle this situation with MicrosoftWebDriver. I mean if you create an object of MicrosoftWebDriver then how it initialized with the same session like WindowsDriver and control already opened web browser?
Do you have any code snippet, please?

**Comment by taitranvungle** [comment]
You need to open up a web driver first, then leave it open and open a Window driver to work.

Below is the code snippet 
`    def setUp(self):
        print("\nStarting ..." + self.__class__.__name__ + "." + self._testMethodName)
        self.browser = WebPage() # init new web driver
        self.browser_assertion = WebAssertions()
        url = "http://www.google.com"
        self.browser.gotoPage(url)
        time.sleep(4)
        self.driver = webdriver.Remote(AppiumBaseClass.hub, AppiumBaseClass.desired_caps) # init new win app driver
        # some stuff for page initialization here

    def tearDown(self):
        print("TearDown: Cleanup...")
        self.browser.closeBrowser()
        self.home_page.quitApp()
        print("\n.end of test")`
