### ISSUE TITLE
How to click the second element of SAME elements?

### ISSUE THREAD

**Issue by yihsuan-chen-s** [Microsoft/WinAppDriver#532]
Hi, Sorry for interrupting

I want to click the second element, here is the XML tree view sample:
- GridView
    - List Item
    - List Item   <------- Need To Click This Element
    - List Item
    - List Item

And all of these `List Item` are the same element, same AutomationID, same Name, same ClassName.

I use this path ***is workable*** to click the FIRST `List Item`
```session.FindElementByAccessibilityId("GridView").FindElementByXPath("./*[position()=1]").Click()```

But I use this path ***isn't workable*** to click the SECOND `List Item`
```session.FindElementByAccessibilityId("GridView").FindElementByXPath("./*[position()=2]").Click()```

Can someone help me for this situation?
Or can someone know how to click second element by index or something?

Hope to get the reply, thanks!
Regards

**Comment by moonkey124** [comment]
You could search for all List Items and then take the second element of it.

Example:
`var listItems = session.FindElementsByAccessibilityId("ListItem");`
`var secondItem = listItems[1];`
`session.Mouse.Click(secondItem.Coordinates);`

If you want to get always the first or last element I recommend you to use the same method
but for first simply do `var secondItem = listItems.FirstOrDefault();`
and for the last one `var secondItem = listItems.LastOrDefault();`

**Comment by yihsuan-chen-s** [comment]
@moonkey124 
Thanks for your reply!!

But it doesn't work for me, I'll get the compile error
`var secondItem = listItems[1];`
`var firstItem = listItems.FirstOrDefault();`

Seems that WindowsElement doesn't have `index` or something.

Here's my import package `using OpenQA.Selenium.Appium.Windows;`
