### ISSUE TITLE
Click in a MDI Tabed windows

### ISSUE THREAD

**Issue by macervera** [Microsoft/WinAppDriver#533]
Hi,
I'm trying to click on a tabbed  MDI window and I do not get it.

I can click on the typical tab-type components of the Windows with multiple information, since I locate them with the inspector. But I can't locate the tabs of the MDI windows. Neither does the "x" to close them.

I can capture the MDI window through his handler and all the elements of each of the MDI windows, but not the tab to select it and focus it (the windows is hide for the selected windows of the focused tab).

Any idea of ​​how you can access these elements?, are graphical elements or windows objects?

Thank you

**Comment by hassanuz** [comment]
Hi @macervera,

Can you clarify if you can see the MDI tabs using Inspect and which exact MDI application that you're using? 

Can you try seeing if you are able to access the tabbed elements from [UI Recorder](https://github.com/Microsoft/WinAppDriver/releases/tag/UiR_v1.0-RC)?

**Comment by macervera** [comment]
Hi,
  I can't see the MDI tabs using Inspect.

  The application is the typical VB application that have a Main form and open MDI tabbed windows when you click in the menu options.

  I try with UI Recorder and don't see the MDI tabs. The UI Recorder suggest me a click by coordinates.

Regards,

**Comment by macervera** [comment]
Hi again,
  When i use Inspector in order to see the tab, inspector show the MDI window. I download the Source and i can see the tab.
  It's possible click the tab using the MDI  windows or other functionality of WinAppDriver.
Regards,

**Comment by hassanuz** [comment]
Hi @macervera,

Are you using [Inspect.exe](https://docs.microsoft.com/en-us/windows/desktop/winauto/inspect-objects) or Appium Inspector? If Inspect.exe is unable to identify the MDI element, then WinAppDriver will not be able to interact against it. This is by design. 

Can you post a screenshot of Inspector identifying the element if I misunderstood? 

Thanks

**Comment by macervera** [comment]
Inspector.exe don't see the MDI tab, it only can "see" the MDI window.

There are a way to Bring to Front the MDI window? In .NET or VB i can use the BringToFront() method, can i use some similar method in WinAppDriver? this will simulate the tab click.
Regards,

**Comment by hassanuz** [comment]
Hi @macervera,

Is it "Inspect**or**" or "Inspect.exe"? If it isn't in Inspect.exe, then WinAppDriver will not be able to automate against it.

As far as bringing it to the front, perhaps you can try using a [SendKeys ](https://github.com/Microsoft/WinAppDriver/blob/v1.1/Tests/WebDriverAPI/SendKeys.cs#L62)from the session and see if you can send a "CRTL + TAB" command to iterate between the tabs?

**Comment by macervera** [comment]
Sorry, its inspec.exe.

  The control is a DevExpress control and dont expose the objects to be automated.

  I see in the DevExpress wiki that by default the DevExpress controls are hidden to the automation, in order to increase his performance. There are a control property (that must be setted by the development team in the source code) to show the control to the automation tools.

Thanks,
