### ISSUE TITLE
Visual Studio 2019 Preview Support

### ISSUE THREAD

**Issue by ianceicys** [Microsoft/WinAppDriver#535]
Is there any better support of win app driver with Visual Studio 2019? 

https://blogs.msdn.microsoft.com/visualstudio/2018/12/04/making-every-developer-more-productive-with-visual-studio-2019/

**Comment by hassanuz** [comment]
Hi @ianceicys,

WinAppDriver will be supported on VS2019 just as it is supported on the current Visual Studio. It doesn't really matter what the test client is, as they all should send the same HTTP requests under the hood anyway.

Was there a specific feature that you were looking for?

**Comment by markzvu** [comment]
hi @hassanuz 

I am also having some issues with WinAppDriver and VS2019.
I am able to create and open a project but all elements in VS app itself as menus, project explorer are not recognized. Will it be supported? is there an ETA?

Thanks

**Comment by markzvu** [comment]
@hassanuz, any update on this issue?

**Comment by hassanuz** [comment]
hi @markzvu,

It could be that the session that you're using is different for the project creation menu at bootup than to the VS2019 IDE it self. 

For example, I used to the following code to interact with the VS2019 toolbar, and was able to do so successfully. 

```
     Thread.Sleep(TimeSpan.FromSeconds(5));
     var allWindowHandles = session.WindowHandles;
     session.SwitchTo().Window(allWindowHandles[0]);
     Thread.Sleep(TimeSpan.FromSeconds(5));
     session.FindElementByName("Build").Click();
     session.FindElementByName("Clean Solution").Click();
```
Can you provide more clarification on what isn't working for you + the WinAppDriver.exe console output? 

Thanks

**Comment by markzvu** [comment]
@hassanuz 
Actually,   var allWindowHandles = session.WindowHandles;  did the trick for me.
In previous versions of VS this wasn't required and that's why i wasnt able to interact.
I'll add the proper modifications.

Thanks

**Comment by hassanuz** [comment]
Thanks for the update, @markzvu.
