### ISSUE TITLE
AlarmClockTest - test fails on FindElementsByName("Windows Application Driver Test Alarm");

### ISSUE THREAD

**Issue by quincycs** [Microsoft/WinAppDriver#54]
var alarmEntries = AlarmClockSession.FindElementsByName("Windows Application Driver Test Alarm");
Assert.IsTrue(alarmEntries.Count > 0);

The above assert fails.  Any guesses as to why?  known issue that will be resolved?

I was able to fix the sample with this below code...but the above code should work IMO b/c I see a button within the list item that has that exact name.   I'm now curious if there is limitations on what elements we can find/search?

var alarmEntries = AlarmClockSession.FindElementsByXPath("//ListItem[starts-with(@Name, \"Windows Application Driver\")]");
Assert.IsTrue(alarmEntries.Count > 0);

**Comment by khouzam** [comment]
Hi @quincycs,

The Alarm clock app the way it names the elements it creates, I've updated the samples to account for this (similar to your change) as well as making it more robust to different regional settings on the machine.

**Comment by quincycs** [comment]
thx - 2 things:

1: IMO its not regional issue.
With inspect i see the button with the exact name...why couldn't it be found?  
![image](https://cloud.githubusercontent.com/assets/2924643/17280101/67b0421e-574d-11e6-92ba-d726a9168978.png)


2: With your modified code, it fails for a different reason (parsing hours from datetime).  Ha this i think is regional issue

![image](https://cloud.githubusercontent.com/assets/2924643/17280045/ca393bae-574b-11e6-96cb-5fc39fe2fcea.png)

**Comment by khouzam** [comment]
Sorry, there were 2 issues with the test. There's a regional issue and it seems that my fix is not complete. I think I have another fix that does work for more time formats.

The second one is that the listView items aren't found because the alarm clock app has changed the way it is naming its elements. That's why the element is not found anymore.

I've created a fix with this pull request: https://github.com/Microsoft/WinAppDriver/pull/56

I've also added a fix for the Windows 10 Anniversary Update that seems to have changed the name of an element.

**Comment by quincycs** [comment]
take a look at my #1 screenshot. 

AlarmClockSession.FindElementsByName("Windows Application Driver Test Alarm");

If this code is run it comes up with 0 items found.  Why?  The screenshot shows it IS there.

**Comment by quincycs** [comment]
Shit I mean (1) in previous comment.  Didn't mean to reference a pull request:-/

**Comment by Nicothekrug** [comment]
Same here. FindElementsByName finds 0 elements no matter what i do.

**Comment by timotiusmargo** [comment]
We have recently updated the [AlarmClockTest](https://github.com/Microsoft/WinAppDriver/tree/master/Samples/C%23/AlarmClockTest) sample. Could you please retry?

**Comment by quincycs** [comment]
I downloaded the source for v0.5-beta  & installed v0.5-beta.

I verified that the sample now runs well!  (I ran it on RS1)

It runs similar code as before, so seems like an internal bug was also fixed to make the sample work.
