### ISSUE TITLE
ReadOnlyCollection Requires one Argument

### ISSUE THREAD

**Issue by sjagdish2007** [Microsoft/WinAppDriver#553]
The below piece of code was Originally posted by @timotiusmargo in https://github.com/Microsoft/WinAppDriver/issues/193#issuecomment-323240683_
```c#
Session.FindElementByAccessibilityId("control").cick(); // To open the dropdown list
WindowsElement comboListObj = SKTF_Session.FindElementByAccessibilityId("listobject"); // listobject is created
ReadOnlyCollection comboListCollection = comboListObj.FindElementsByTagName("ListItem");
```

When i tried to use the code for a similar situation (trying to select a ListItem), I get the error 'ReadOnlyCollection Requires one Argument'.

Can somebody pls help...

**Comment by hassanuz** [comment]
Hi @sjagdish2007,

Can you paste the exact call you're making + any app where we can repro this? 

Thanks

**Comment by hassanuz** [comment]
Please re-open once you have more information.
