### ISSUE TITLE
Does WinAppDriver supports WPF applications yet? 

### ISSUE THREAD

**Issue by vish28** [Microsoft/WinAppDriver#57]
I am trying to automate a WPF application using this awesome tool. Latest release 0.4, downloaded from GitHub.

During create session - server just do not respond/or take forever to respond (>20 minutes). Application indicated as the capability "app" launched fine.

Console looks like below:
 
![image](https://cloud.githubusercontent.com/assets/11184897/17348806/f804ffea-58cd-11e6-884f-3845f2463b7c.png)

Any ideas which can help here?

**Comment by alakshmi1030** [comment]
Could you take a look at the Notepad sample in our repo's sample folder? The sample specifies the executable name in the app capabilities. https://github.com/Microsoft/WinAppDriver/tree/master/Samples/C%23/NotepadTest

How are you launching this app within WinAppDriver? For classic Windows applications we specify the path to the app.
