### ISSUE TITLE
Notepad Test sample not working

### ISSUE THREAD

**Issue by csa0911** [Microsoft/WinAppDriver#573]
I am trying to run the NotepadTest sample. It starts to run but immediately exits

[1/18/2019 15:45:13 Informational] ------ Run test started ------
[1/18/2019 15:45:13 Informational] ========== Run test finished: 0 run (0:00:00.3065055) ==========

Any help please?

**Comment by wangfu91** [comment]
Hi, @csa0911 

Upgrade MSTest.TestAdapter & MSTest.TestFramework in NuGet Package Manager worked for me.

![image](https://user-images.githubusercontent.com/5633310/51540389-477d5c80-1e91-11e9-920f-e8438874c6ee.png)

**Comment by hassanuz** [comment]
Hi @csa0911,

Please try our [latest samples](https://github.com/Microsoft/WinAppDriver/tree/v1.1.1/Samples/C%23) to see if they are working for you.

Thanks

**Comment by timotiusmargo** [comment]
Hi @csa0911,

All of our samples are still using an older version of **MSTest**. Unfortunately some latest version of **VisualStudio** have a problem discovering/running these tests even though they build successfully. If you encounter this issue, you can change the following **VisualStudio** settings to fix it.

1. Select **Tools** > **Options...** > **Test**
2. Under *Active Solution*, uncheck *For improved performance, only use test adapters in test assembly folder or as specified in runsettings file*

I have updated the [Notepad Sample Test README.md](https://github.com/Microsoft/WinAppDriver/blob/v1.1.1/Samples/C%23/NotepadTest/README.md) with this information.
