### ISSUE TITLE
WinAppDriver supports WPF XBAP Application to automate?

### ISSUE THREAD

**Issue by Vasanthi30** [microsoft/WinAppDriver#574]
Hi Team,

Am trying to automate the WPF Browser Based application (XBAP) . Is WinAppDriver will support to automate this type of Applications.

Thanks,
Vasanthi

**Comment by hassanuz** [comment]
Hi @Vasanthi30,

Are you able to view the UI elements attribute data from either using Inspect.exe or UI Recorder? If you are able to do so, then there's a good chance that WinAppDriver will be able to automate against it.

**Comment by Vasanthi30** [comment]
Yes, am able to see the elements using inspect.exe and  UI Spy.
