### ISSUE TITLE
Playback test not able to identify and fill in "Sign In" popup window in Chrome browser

### ISSUE THREAD

**Issue by Deqmin** [Microsoft/WinAppDriver#575]
Hi,

I'm very new on coded ui and selenium coding so here the codes and right now I'm facing an issue after playback the test it not able to identify and fill in "Sign In" popup window to open the link.
Please help

```
var chromeService = ChromeDriverService.CreateDefaultService(@"C:\Program Files (x86)\Common Files\microsoft shared\VSTT\Cross Browser Selenium Components"); //navigate to the location of chromedriver.exe
var options = new ChromeOptions();

IWebDriver driver = new ChromeDriver(chromeService, options);
driver.Manage().Window.Maximize();
driver.Url = "http://server/5Nov_LinkXConfigurator/";

DesiredCapabilities appCapabilities = new DesiredCapabilities();
DesktopSession = new WindowsDriver<WindowsElement>(new Uri("http://server/5Nov_LinkXConfigurator/"), appCapabilities);

// Use the session to control the desktop
IWebElement chromeWindow = DesktopSession.FindElementByXPath(".//Window[contains(@ClassName,'Chrome') ]");
IWebElement SecurityPopupWindow = chromeWindow.FindElement(By.XPath(".//*[@Name='Sign in']"));

SecurityPopupWindow.FindElement(By.XPath(".//*[@Name='Username']")).SendKeys("sninadia");
SecurityPopupWindow.FindElement(By.XPath(".//*[@Name='Password']")).SendKeys("123");
```
![unable to continue](https://user-images.githubusercontent.com/46912431/51518248-38c68380-1e58-11e9-99be-322707b1fd65.JPG)

![123](https://user-images.githubusercontent.com/46912431/51520068-bb057680-1e5d-11e9-8824-ca659b7d0049.JPG)

**Comment by liljohnak** [comment]
@Deqmin Try this.

`SecurityPopupWindow.FindElement(By.XPath(".//*[@Name='Username'][2]")).SendKeys("sninadia");//index starting at 1`

Helpful resource.
https://blogs.msdn.microsoft.com/xmlteam/2011/09/26/effective-xml-part-2-how-to-kill-the-performance-of-an-app-with-xpath/
