### ISSUE TITLE
Unable to fetch children from desktop using Xpath

### ISSUE THREAD

**Issue by venkat2048** [Microsoft/WinAppDriver#583]
Hi,

@timotiusmargo 
I'm trying to get root desktop session and identify opened windows and written code as shown below:

            DesiredCapabilities DC = new DesiredCapabilities();
            DC.SetCapability("platFormName", "Windows");
            DC.SetCapability("app", "Root");
            DC.SetCapability("deviceName", "WindowsPC");
          
            session = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), DC);
   
            //For Line below it returns with windows list whose classname is 'Window'
            var openWindows = session.FindElementsByClassName("Window");

            Actual: //For Line below it returns NULL (Issue)
            openWindows = session.FindElementsByXPath("//*"); 

Expected: It should return all children under desktop

Please find the screenshots below:

Image1: Issue

![image](https://user-images.githubusercontent.com/46370754/51973065-7754d300-2442-11e9-8527-b7e3165986ef.png) 

Image2: Works with ClassName

![image](https://user-images.githubusercontent.com/46370754/51973390-242f5000-2443-11e9-8e96-4b387b70dc6b.png)

**Comment by timotiusmargo** [comment]
Hi @venkat2048,

Thanks for bringing it up. There is a known bug that causes the XPath element search to terminate early when it encounters duplicate **runtimeId**. For the time being you will need to use non XPath elements search until the issue is fixed.

**Comment by timotiusmargo** [comment]
Hi @venkat2048,

In WinAppDriver [v1.1.1](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.1.1) release, we properly handle the exception scenario where distinct elements share the same runtimeId. This issue prematurely terminate XPath element search in previous releases. Would you please give it a try?

**Comment by shoaibmansoor** [comment]
@timotiusmargo I am able to reproduce it with [v1.2.1](https://github.com/microsoft/WinAppDriver/releases/tag/v1.2.1) as well.

I can get page_source correctly and elements by other methods but find_elements_by_xpath doesn't work

Could you please look into this?
