### ISSUE TITLE
change device orientation

### ISSUE THREAD

**Issue by gouravtayal** [Microsoft/WinAppDriver#594]
Hi @hassanuz 
I want to change the orientation of my screen(Surface device) during automation, is it possible with winappdriver? can you suggest me someway.

**Comment by timotiusmargo** [comment]
Hi @gouravtayal,

WinAppDriver doesn't simulate orientation change event at the moment. However, if you only want to simulate the layout change, you can definitely write a script to change the display **orientation** in the **Display** section of **Settings** application.
