### ISSUE TITLE
Use velocity and pressure simulatneously

### ISSUE THREAD

**Issue by agangwan** [Microsoft/WinAppDriver#595]
I want to use the stylus stroke which considers both velocity and pressure. Currently, when I am trying to give both pressure and timespan in the sequence, only pressure field is considered and pressure is ignored. Consider below code sample:

CoordinateOrigin co = new CoordinateOrigin();
sequence.AddAction(device.CreatePointerMove(co, end.X, end.Y, TimeSpan.FromSeconds(1), new PenInfo { Pressure = 0.5f }));

The stroke drawn is with very less pressure which doesn't changes on changing the Pressure value given in above sample code. However, timespan works fine. If I give TimeSpan.Zero then the pressure work completely fine.

**Comment by timotiusmargo** [comment]
Hi @agangwan,

If I understand you correctly, you are trying to simulate a pen stroke (from point A to B) with a given pressure value C with certain speed specified by duration D. As an example, let's use the following value:

**Point A** (0, 0)
**Point B** (10, 10)
**Pressure C** 0.8 (80 % pressure)
**Duration D** 1 second (10 pixels/second in both axis)

As shown in the [Tutorial](https://github.com/Microsoft/WinAppDriver/tree/v1.1/Samples/C%23/StickyNotesTest#drawing-with-additional-pen-attributes) section of [Sticky Notes Sample](https://github.com/Microsoft/WinAppDriver/tree/v1.1/Samples/C%23/StickyNotesTest), you will need to construct the stroke as follows:
```C#
PointerInputDevice penDevice = new PointerInputDevice(PointerKind.Pen);
ActionSequence sequence = new ActionSequence(penDevice, 0);

// Draw line AB from point A (0, 0) to B (10, 10)
sequence.AddAction(penDevice.CreatePointerMove(CoordinateOrigin.Viewport, 0, 0, TimeSpan.Zero));
sequence.AddAction(penDevice.CreatePointerDown(PointerButton.PenContact, new PenInfo { Pressure = .8f }));
sequence.AddAction(penDevice.CreatePointerMove(CoordinateOrigin.Viewport, 10, 10, TimeSpan.FromSeconds(1)));
sequence.AddAction(penDevice.CreatePointerUp(PointerButton.PenContact));

session.PerformActions(new List<ActionSequence> { sequence });
```

In the above snippet, the `createPointerMove` set the starting **point A** while the following `createPointerDown` establish pen contact with **Pressure C** at **point A**. Any following pointer event will use this pressure value until it is specified to another value through a different pointer action. The following `createPointerMove` will then move the pen contact from **point A** to **point B** within **Duration D** generating even interpolation points in between. More examples of the pointer event usage can be found on that particular sample above.
