### ISSUE TITLE
Calculator is launched but org.openqa.selenium.UnsupportedCommandException is thrown and tests fail

### ISSUE THREAD

**Issue by umadevisk89** [Microsoft/WinAppDriver#596]
pom details 
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>CalculatorTest</groupId>
    <artifactId>CalculatorTest</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.141.59</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.11</version>
        </dependency>
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>7.0.0</version>
        </dependency>
    </dependencies>

</project>

Error log:

Feb 13, 2019 12:48:14 PM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: OSS
org.openqa.selenium.UnsupportedCommandException: Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'INENSETTYUL2C', ip: '10.87.240.253', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: io.appium.java_client.windows.WindowsDriver
Capabilities {app: Microsoft.WindowsCalculator..., javascriptEnabled: true, platform: ANY, platformName: ANY}
Session ID: 4A4FB6D1-0EDC-475B-8CB1-58F576BE2852
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.windows.WindowsDriver.execute(WindowsDriver.java:1)

Need help in resolving it.

**Comment by timotiusmargo** [comment]
Hi @umadevisk89.

It will help greatly if you can provide the log from the `WinAppDriver.exe` command window when this is failing. This information may also be embedded in the Appium log and was not included in the one you pasted above. Below is a sample log I am looking for.

```
==========================================
POST /session HTTP/1.1
Accept: application/json, image/png
Connection: Keep-Alive
Content-Length: 148
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"desiredCapabilities":{"app":"Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge","appArguments":"-private about:flags","platformName":"Windows"}}
HTTP/1.1 200 OK
Content-Length: 196
Content-Type: application/json

{"sessionId":"21DEF83A-9B6B-491C-9077-D557CE393E8A","status":0,"value":{"app":"Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge","appArguments":"-private about:flags","platformName":"Windows"}}


==========================================
POST /session/21DEF83A-9B6B-491C-9077-D557CE393E8A/keys HTTP/1.1
Accept: application/json, image/png
Content-Length: 17
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723

{"value":[""]}
HTTP/1.1 200 OK
Content-Length: 63
Content-Type: application/json

{"sessionId":"21DEF83A-9B6B-491C-9077-D557CE393E8A","status":0}
```

**Comment by umadevisk89** [comment]
Thanks for the reply @timotiusmargo .

Below is the log from WinAppDriver.exe

==========================================
POST /session HTTP/1.1
Accept-Encoding: gzip
Connection: Keep-Alive
Content-Length: 414
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.59 (java windows)

{
  "desiredCapabilities": {
    "app": "C:\\Program Files (x86)\\DellEMC\\Patch and Update Automation Tool\\Patch and Update Automation Tool.exe",
    "platformName": "Windows"
  },
  "capabilities": {
    "firstMatch": [
      {
        "appium:app": "C:\\Program Files (x86)\\DellEMC\\Patch and Update Automation Tool\\Patch and Update Automation Tool.exe",
        "platformName": "windows"
      }
    ]
  }
}
SessionManager - Creating session for C:\Program Files (x86)\DellEMC\Patch and Update Automation Tool\Patch and Update Automation Tool.exe
SessionManager - WinAppDriver succeeded loading MitaBroker
SessionManager - Application launched
SessionManager - Session successfully created: 321BC3D5-09B4-4810-B472-6622ADA6CFFD
HTTP/1.1 200 OK
Content-Length: 186
Content-Type: application/json

==========================================
GET /session/321BC3D5-09B4-4810-B472-6622ADA6CFFD HTTP/1.1
Accept-Encoding: gzip
Cache-Control: no-cache
Connection: Keep-Alive
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.59 (java windows)


HTTP/1.1 404 Not Found

**Comment by timotiusmargo** [comment]
Hi @umadevisk89,

The log you pasted above seems to show a really old version of WinAppDriver. Would you mind retrying the same scenario on the latest version of WinAppDriver (E.g. [version 1.1](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.1))?

**Comment by umadevisk89** [comment]
Hi @timotiusmargo ,

Using the latest version of WinAppDriver worked like charm.
Thanks for the help.
