### ISSUE TITLE
CalculatorTest doesn't run because it threw exceptions when instantiating the WindowsDriver object.

### ISSUE THREAD

**Issue by tetsushmz** [Microsoft/WinAppDriver#599]
Hi,

The exceptions are:

- Exception thrown: 'System.TypeLoadException' in appium-dotnet-driver.dll
- Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
- Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.dll

And then the Visual Studio 2017 pro V15.9.5 unit test session stopped. Of course, the Calculator app wasn't launched. The WinAppDriver remained there without showing nothing new after "Press ENTER to exit.". What am I doing wrong?

I downloaded the V1.1 WinAppDriver, installed, and ran it on Windows 10 64 bit V1809. I turned on the "Developer mode". I had to modify the CalculatorSession code (.ImplicitlyWait() to .ImplicitWait = ) to remove the compile error, by the way.

I would appreciate any suggestions.

Thanks,

Tetsu

**Comment by subhapuram** [comment]
hi ,

 i have to downgrade appium driver to 3.0.0.2 . uninstall existing driver and while installing now select the old one and then it should be running
I had to downgrade selenium driver also to 3.11.2.0 and then it worked

**Comment by timotiusmargo** [comment]
Hi @tetsushmz, @subhapuram,

The [CalculatorTest](https://github.com/Microsoft/WinAppDriver/tree/v1.1.1/Samples/C%23/CalculatorTest) sample and [README.md](https://github.com/Microsoft/WinAppDriver/blob/v1.1.1/Samples/C%23/CalculatorTest/README.md) was recently updated. Would you please give it a try?

**Comment by tetsushmz** [comment]
Hi @timotiusmargo ,

I tested V1.1.1 and verified it worked. I needed to uncheck the "For improved performance, only use test adapters in test assembly folder or as specified in runsettings file" setting, though.

Thanks so much.

**Comment by dahanj95** [comment]
I'm having the same problem. I have installed latest nugets and WinAppDriver and ran it, but my code would throw same exception when creating an instance of WindowsDriver.

https://ibb.co/YjfYW61 - These are the nugets I have.
