### ISSUE TITLE
Support XPath

### ISSUE THREAD

**Issue by fasterfish** [Microsoft/WinAppDriver#6]
Could you add support for searching elements by XPath (combine ClassName, Name and UI Automation ID)?

**Comment by AsafSaar** [comment]
Yes please!

**Comment by alakshmi1030** [comment]
xPath support should be added in as of the v0.4 beta release: https://github.com/Microsoft/WinAppDriver/releases/tag/v0.4-beta

Please download the latest installer from Github and let us know if you have any issues.
