### ISSUE TITLE
Screenshot has a little bit of background attached

### ISSUE THREAD

**Issue by minimalisticMe** [Microsoft/WinAppDriver#60]
Hey, I'm using `Appium` with `WinAppDriver` with `Visual Studio 2015 Community Edition` to Test a UWP application.

I was doing some screenshots for documentation with

```
var img = mySession.GetScreenshot();
img.SaveAsFile("D:\\myfile.jpg", ImageFormat.Png);
```

and after opening the file, there was some parts of the background (maybe 3-10 pixels) over the App border in the image. I don't know, whether this is related to `Appium` or `WinAppDriver`, but is there a way to fix this?
A workaround might be to crop the image myself with an Image Tool, like `IrfanView`, but I would like to avoid that.

**Comment by khouzam** [comment]
We're looking at improving the way screenshots are implemented.

**Comment by wuarthur** [comment]
Also screenshot seems to not include any of the extra popup windows

**Comment by miniksa** [comment]
A fix to this issue should be coming in v0.8.

**Comment by gouthamsam** [comment]
Issue is not yet fixed. Attached find the screenshot. Appium Desktop 1.0.
![carmoveleticon](https://cloud.githubusercontent.com/assets/17687271/26099258/897c217c-3a2a-11e7-9470-7ddd6b067f07.png)

**Comment by miniksa** [comment]
Appium Desktop is still using 0.7 version of WinAppDriver. When it is updated, this should be resolved.

**Comment by KiranBehara** [comment]
If we don't give the path by default where the screen shot will be saved.
Lets say if i say element.GetScreenshot();
