### ISSUE TITLE
how to find coordinates

### ISSUE THREAD

**Issue by winsri02** [Microsoft/WinAppDriver#601]

**Comment by hassanuz** [comment]
Hi @winsri02,

Can you provide more information on what you're looking for? 

We have a sticky-notes [sample](https://github.com/Microsoft/WinAppDriver/blob/35a659232060a6e436cbb8393ae9a09bab12bc89/Samples/C%23/StickyNotesTest/README.md#specifying-pointer-move-coordinates) that demonstrates how to use Pointer Coordinates.
