### ISSUE TITLE
[Question] Is there a better way to wait for a progress bar to complete?

### ISSUE THREAD

**Issue by liljohnak** [Microsoft/WinAppDriver#612]
Is there a better way to wait for a progress bar to complete?

```
var progressBar = mainWindow.FindElementByClassName("Window").FindElementByAccessibilityId("progressor");
      WebDriverWait waitProgressBar = new WebDriverWait(_session, new TimeSpan(0, 0, 15));
      waitProgressBar.PollingInterval = new TimeSpan(0, 0, 0, 0, 50);
      waitProgressBar.Until(driver =>
      {
        try
        {
          progressBar.GetScreenshot();
          return false;
        }
        catch (Exception)
        { }
        return true;
      }
      );
```

**Details if needed:**
![progressbar](https://user-images.githubusercontent.com/20760251/53265111-3db66700-3692-11e9-8e2b-3eb1094c9002.gif)
Desktop application.
During the course of testing this application, I would like to wait for controls to appear and disappear.  That is, running processes on the application that take longer than 5 seconds should alert the user with a progress bar.  This should temporarily pause the test until the progress bar is gone.
Per the above code this is what I could come up with that was responsive to my application, but I feel that this can be improved.  Are there any suggestions?

**Comment by hassanuz** [comment]
Hi @liljohnak,

This looks good. Perhaps you could change ".getScreenshot" to something else, like using the [Displayed](https://github.com/Microsoft/WinAppDriver/blob/35a659232060a6e436cbb8393ae9a09bab12bc89/Tests/WebDriverAPI/ElementDisplayed.cs#L39) property to verify.

**Comment by liljohnak** [comment]
Thank you @hassanuz properties took longer to give me a response, but methods failed instantly.

**Comment by Saif4** [comment]
Hi @hassanuz  when I use Displayed instead of GetScreenshot, I got error Non-invocable member RemoteWebElement.Displayed cannot be used like a method! Any suggestions?
