### ISSUE TITLE
Missing AutomationId on ComponentFactory.Krypton.Ribbon

### ISSUE THREAD

**Issue by marlamulero** [Microsoft/WinAppDriver#613]
We use Krypton (V 4.4.0) on our windows form to create ribbons for the menu. 

We have a main ribbon which holds additional tabs (like in Microsoft Word). This main ribbon has the **"File"** tab, when clicked it displays a collection [KryptonContextMenuItem()] of menu items but none of them display an AutomationId on the inspect.exe tool. 

The additional tabs (Path Planner) don't have the same issue, is just the squared window that comes up when "File" is clicked.

The krypton tool doesn't have a "name" member, just the "Text". The menu item names are set on the code as:
this->kryptonContextImportMesh->Text = L"Import Mesh...";

![krypton_menu](https://user-images.githubusercontent.com/47831828/53264746-3b074200-3691-11e9-9f39-e0d1c11d7493.PNG)

Any recommendations on how to solve this? I can't open the window shown by the **"File"** tab through my tests.

**Comment by hassanuz** [comment]
Hi @marlamulero,

If Inspect.exe can pick up the elements, then WinAppDriver will be able to automate / interact against it. If Inspect.exe or UI Recorder are not able to pick up these elements, then WinAppDriver will not able to automate against it.
