### ISSUE TITLE
the function "get_attribute" cat not get "LegacyIAccessible.DefaultAction"

### ISSUE THREAD

**Issue by Asmallsky** [Microsoft/WinAppDriver#619]
LegacyIAccessible.ChildId:	0
LegacyIAccessible.DefaultAction:	"按"
LegacyIAccessible.Description:	""
LegacyIAccessible.Help:	""
LegacyIAccessible.KeyboardShortcut:	""
LegacyIAccessible.Name:	"清除"
LegacyIAccessible.Role:	按下按钮 (0x2B)
LegacyIAccessible.State:	可设定焦点 (0x100000)
LegacyIAccessible.Value:	""

**Comment by ShyAlex** [comment]
Try "LegacyDefaultAction" rather than "LegacyIAccessible.DefaultAction".
