### ISSUE TITLE
Are Appium PageObjects.Attributes supported yet?

### ISSUE THREAD

**Issue by beyourselfman** [Microsoft/WinAppDriver#62]
Hello all,

I am trying to setup a test project using the page object pattern, as known from Selenium/Appium.

For this I am struggling to locate an ui element (ConvertButton) by its automationId using attributes, like this:

```
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using OpenQA.Selenium.Appium.iOS;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Appium.PageObjects.Attributes;

namespace BaseConverterUITest
{
    [TestClass]
    public class UnitTest1
    {

        protected const string AppDriverUrl = "http://127.0.0.1:4723";
        protected static IOSDriver<IOSElement> TestAppSession;
        protected static RemoteWebElement TestAppResult;

        [FindsByIOSUIAutomation(Accessibility = "automationId")]
        private IOSElement ConvertButton;
```

so it can be accessed in a later test method by doing

```
[TestMethod]
        public void ConvertBaseTest()
        {        
  
           // this works: 
           //ConvertButton = TestAppSession.FindElementByAccessibilityId("convert_button");
          
           // this does not work
           ConvertButton.Click();            
```

Alas, this leads to a NullReferenceException. What am I doing wrong here?

Best regards,

Michael

**Comment by alakshmi1030** [comment]
That command didn't get sent to our listening WinAppDriver server so it is unsupported for right now - I suggest taking a look at the Appium .NET Driver and see if it can be resolved there:

https://github.com/appium/appium-dotnet-driver

**Comment by alakshmi1030** [comment]
Please raise this issue on the Appium .NET Driver repo as mentioned earlier.
