### ISSUE TITLE
Splash Window  + currently selected window has been closed 

### ISSUE THREAD

**Issue by Haripriya-kadimetla** [Microsoft/WinAppDriver#621]
Hello there,

Working on win32 desktop application automation , the controls  on login window  are identified but after login unable to find the  main window , i have tried solutions provided like 
session.SwitchTo().Window(session.WindowHandles[0]); as the Window  doesn't exists ,it gives me error 

Can some one please suggest me with the issue ? 

Screenshots attached for more clarity

**Comment by timotiusmargo** [comment]
Hi @Haripriya-kadimetla,

We are looking at this issue and are working on a fix soon. Please stay tune.

**Comment by Haripriya-kadimetla** [comment]
Thank you  for your response ... i  could figure out  a workaround .

**Comment by timotiusmargo** [comment]
Hi @Haripriya-kadimetla,

For your information, WinAppDriver [v1.1.1](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.1.1) [GetWindowHandles](https://github.com/Microsoft/WinAppDriver/blob/v1.1.1/Tests/WebDriverAPI/Window.cs#L98) endpoint will now continue to work even when the current application window is closed/destroyed. This will allow you to enumerate through all application top level windows with the same **processId** until the session is terminated.
