### ISSUE TITLE
Unable to take a screenshot, missing ImageFormat

### ISSUE THREAD

**Issue by stzaske** [Microsoft/WinAppDriver#635]
I'm using Visual Studio 2019.  I created a new UWP Unit test project and attempted to create a simple test.  However I was not able to take a screenshot:

```screenshot.SaveAsFile(@"C:\AutomatedScreenshots\screenshot1.png", ImageFormat.Png);```

did not work as I was missing the ImageFormat enum.  Switching to a .Net Framework project solved my problem.

**Comment by timotiusmargo** [comment]
Thanks for sharing your finding @stzaske! We have a sample on how to save the screenshot you captured using `ScreenshotImageFormat` enum instead below:
https://github.com/Microsoft/WinAppDriver/blob/v1.1.1/Tests/WebDriverAPI/Screenshot.cs
