### ISSUE TITLE
Release version doesn't match version installed

### ISSUE THREAD

**Issue by bean601** [microsoft/WinAppDriver#639]
I've installed v1.1.1 from https://github.com/Microsoft/WinAppDriver/releases/tag/v1.1.1 and it gets installed as 1.1.4.0. Seeing this on Windows 10.

![image](https://user-images.githubusercontent.com/1154670/55070117-d96a3700-5085-11e9-922d-69c61e4318ae.png)

Also noticed it in version 1.1 that installed as 1.1.3.0.

**Comment by hassanuz** [comment]
We've had some internal builds, hence why the release version deviated. 

This should be resolved with v1.2.
