### ISSUE TITLE
RadioButton click event not triggered

### ISSUE THREAD

**Issue by ddelapasse2** [Microsoft/WinAppDriver#64]
Hi,

[I'm not sure if I should log this here or in Appium or in Selenium.  Please advise!]

I'm trying to create regression tests for my UWP app.  I've had success clicking buttons, but when I click a RadioButton the Click event is not being triggered.  It does select the item (ie the circle next to the text becomes solid), but why doesn't the click event occur?

**Xaml**
<RadioButton x:Name="downloadNew" Style="{ThemeResource NewRadioButtonSize}"  Click="actionRadio_Click" >Download New</RadioButton>

**Test Code**
AimSession = new IOSDriver<IOSElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities);
AimSession.FindElementByAccessibilityId("downloadNew").Click();

**Comment by khouzam** [comment]
We'll take a look.

**Comment by alakshmi1030** [comment]
Which version of WinAppDriver are you using? And also how are you testing whether the click event is triggered or not? I tried to repro and am able to see the radio button being selected but can't tell if the click event is being triggered.

**Comment by ddelapasse2** [comment]
Hi alakshmi1030!

I have version 0.4.  I'm testing against my app (trying to write a test harness for it).  When I click the radio button with the cursor manually the app reacts and proceeds to the next page.  When I "click" through my test app (which works great for other controls) the radio button shows as selected, but the event never triggered.

I can quickly create a tiny UWP app that would show this.  If I do, are you able to Sideload it onto a Win10 device?  Let me know if that would help.  I would love to use this product, but this issue is definitely a showstopper for me!

Looks like my xaml didn't make it into the original post so I'll try posting again.  It is:
`           <StackPanel x:Name="selectActionPanel" Orientation="Vertical" Padding="20,0,0,80">
                <TextBlock Style ="{ThemeResource NewTextBlockStyle}" Margin="0,4" FontWeight="Bold">I want to...</TextBlock>
                <RadioButton x:Name="downloadNew" Style="{ThemeResource NewRadioButtonSize}"  Click="actionRadio_Click" >download a new inspection to work on</RadioButton>
            </StackPanel>`

**Comment by ddelapasse2** [comment]
^Sorry, didn't mean to close this.

**Comment by khouzam** [comment]
Hi @ddelapasse2 
Yes, if you can share a repro project, it will be easier for us to investigate.

**Comment by alakshmi1030** [comment]
Hey @ddelapasse2 - could you try modifying the Click property in the Radio button to "Checked" See [here](https://msdn.microsoft.com/library/windows/apps/br227544) for more info on the Checked property for RadioButtons. Let us know if that works for you.

**Comment by ddelapasse2** [comment]
@alakshmi1030 , Yes!  I will try and let you know.

**Comment by ddelapasse2** [comment]
I added a Checked handler, but the code in the test harness stayed as:

AimSession.FindElementByAccessibilityId("overwriteCheckbox").Click();

Is that correct?  No change in behavior.  The screen didn't receive anything.

I've been away working on another project, but hope to return to this one later this week.  As soon as I do I'll make you a little test UWP app with a test harness so you can try it.

**Comment by ddelapasse2** [comment]
I recreated a small sample and the click is working there.  My app has several nested controls so I wonder if that is throwing it off?  I will debug further and let you know!

**Comment by alakshmi1030** [comment]
Hey @ddelapasse2 - are you still experiencing this issue? Please let us know.

**Comment by ddelapasse2** [comment]
OnCheck is working for me, so that is enough.  Thanks!

**Comment by HariniShiva** [comment]
Same issue i am also facing...how i can check checkBox present inside Stack panel?
        <StackPanel Grid.Row="4" Grid.Column="1" Grid.RowSpan="1" Grid.ColumnSpan="2" >
            <ListBox x:Name="lstBox_Tests" Background="White" IsEnabled="False" ItemsSource="{Binding DiagTestList}" HorizontalAlignment="Stretch" VerticalAlignment="Stretch">
                <ListBox.ItemTemplate>
                    <DataTemplate>
                        <CheckBox x:Name="chkBox_Tests" Content="{Binding TheText}" Tag="{Binding TheValue}" Checked="chkBox_Tests_Checked" Unchecked="chkBox_Tests_Unchecked" Height="10" />
                    </DataTemplate>
                </ListBox.ItemTemplate>
            </ListBox>
        </StackPanel>
