### ISSUE TITLE
UIRecorder reports incorrect XPath with multiple monitors

### ISSUE THREAD

**Issue by stzaske** [microsoft/WinAppDriver#646]
UIRecorder does not give me the correct XPath information for my applications if I have multiple Monitors and the app is on my "extended" 2nd monitor. For example with the Calculator app on my second monitor UIRecorder says the Xpath is:
```"/Pane[@ClassName=\"#32769\"][@Name=\"Desktop 1\"]"```

if I move the calculator to my main window the xpath changes to:
`"/Pane[@ClassName=\"#32769\"][@Name=\"Desktop 1\"]/Window[@ClassName=\"ApplicationFrameWindow\"][@Name=\"Calculator\"]/Window[@ClassName=\"Windows.UI.Core.CoreWindow\"][@Name=\"Calculator\"]"`

**Comment by JunlinZhu** [comment]
Try move cursor on top of Calculator on second screen and wait for UI to flash, and see if you still hit this issue.

**Comment by hassanuz** [comment]
Please
