### ISSUE TITLE
How to highlight the elements found while script is running

### ISSUE THREAD

**Issue by KiranBehara** [Microsoft/WinAppDriver#647]
Is there any method to highlight the element found while script is working. I would like to highlight the element with some circle on it or in some other way. 
It helps others in what exactly happening with elements while script is running and it helps in debugging too to understand till which element we navigated.
For example element.Drawhighlight() method in coded ui which highlights the element on the application.

**Comment by timotiusmargo** [comment]
Thanks for bringing this up @KiranBehara. Let's use the duplicate issue #661 to discuss further as it now has more participants.

**Comment by KiranBehara** [comment]
Duplicate issue #661
