### ISSUE TITLE
How to create Xpath for Windows applications

### ISSUE THREAD

**Issue by KiranBehara** [Microsoft/WinAppDriver#649]
For Web applications, DOM structure is followed and with the plug-ins available we can create the Xpath on fly by opening developer tools.

Do we have similar model for Windows application to create Xpath  ?

**Comment by anunay1** [comment]
The is a UI recorder that generates xpath you can try that. 
https://blogs.windows.com/buildingapps/2018/06/20/introducing-winappdriver-ui-recorder/

**Comment by KiranBehara** [comment]
Thank You!
