### ISSUE TITLE
Click action does not work on list items, divs, images (which are glyphs) and group controls.

### ISSUE THREAD

**Issue by sruthakeerthikotla** [Microsoft/WinAppDriver#65]
Hi,

We are using a UWP app built using AngularJS. Click action does not yield any result on the list items, divs, images (which are glyphs) and group controls. These controls are being identified though. Below is the html code we are using in our project which is not being clicked by the winappdriver framework.

[sample html code.txt](https://github.com/Microsoft/WinAppDriver/files/443972/sample.html.code.txt)

Hope to see a solution/fix soon.

Thanks!

**Comment by alakshmi1030** [comment]
Can you use the inspect.exe tool on your UWP app and see which elements are being rendered? Our [readme](https://github.com/Microsoft/WinAppDriver#inspecting-ui-elements) has instructions on how to use the inspect tool.

**Comment by sruthakeerthikotla** [comment]
I have done that and the elements are being identified as "Group" or "ListItem"

**Comment by timotiusmargo** [comment]
This is addressed in v0.6-beta. Could you please verify?

**Comment by bhashkargaur** [comment]
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: The system cannot find the file specified (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 13.26 seconds

Getting this issue . will someone please help me out in this.
