### ISSUE TITLE
How to execute WinAppDriver on Windows 8.1 pro

### ISSUE THREAD

**Issue by ledaivuong** [Microsoft/WinAppDriver#66]
Hi all,
  I am using Windows 8.1 PRO, when I open WinAppDriver that get notice: "Developer mode is not enabled. Enable it through Setting and restart Windows Application Driver. Press ENTER to exit". The problem is I really don't know how to enable Developer mode on Windows 8.1 PRO, I have tried to install Windows SDK, Windows Kits, enable test mode by command "Bcdedit.exe -set TESTSIGNING ON" but nothing helpful.
  I really grateful if you guy can give me some advise to over flow this stuck. @alakshmi1030

**Comment by alakshmi1030** [comment]
Will investigate this and get back to you.
