### ISSUE TITLE
Adding attachments to UWP Applications 

### ISSUE THREAD

**Issue by kviji** [Microsoft/WinAppDriver#668]
Hi,

I am using Winappdriver & Appium for automating my UWP application. 
I have a scenario where I can upload attachments as reference to my application.
Is this possible?

**Comment by naeemakram** [comment]
Please provide more details about your scenario. Are you trying to add attachments to an e-mail?

**Comment by kviji** [comment]
Hi @naeemakram,

I want to add an attachment that may be a zip file or PDF or image to.my application as a reference.
When I click the button, it launches the file explorer from where I can choose the file

**Comment by anunay1** [comment]
In the file name , use the kendkeys api to enter  the file name and click the open or upload button, it should work.

**Comment by kviji** [comment]
Hi @anunay1 ,

I will check if it works. We dont need to switch context to a different window?

**Comment by kviji** [comment]
Hi @anunay1 ,

I was able to use sendkeys api to enter file name
But Open button is not getting clicked.

WebElement open = driver.findElement(By.name("Open"));
        open.click();

I also tried         driver.findElementByAccessibilityId("1").click();
As for the Open button, the Automation ID shown in inspect was "1"

Although buton didnt get clicked, test passed. Checked the same using Expected conditions until element visible also.

Any thoughts.?

**Comment by anunay1** [comment]
use this as an alternative for open 
 session.Keyboard.SendKeys(OpenQA.Selenium.Keys.Enter);
if the test passed then there must be something wrong if the condition that you have put when you assert.

**Comment by kviji** [comment]
Hi @anunay1 

driver.findElement(By.name("Open").semdKeys(KEYS.ENTER);
This worked.
Thanks a lot for your spport

**Comment by anunay1** [comment]
Welcome, good that it worked for you.
