### ISSUE TITLE
UIRecorder not working when using a remote .exe application

### ISSUE THREAD

**Issue by cassiomc** [microsoft/WinAppDriver#673]
I would like to get the xpath of a remote application (the .exe is on the server, not locally) opened on Windows 10, but when I open the application and try to use UIRecorder clicking the mouse on the application components, the UIRecorder returns anything.

**Comment by JunlinZhu** [comment]
can you try running UIRecorder as admin?

**Comment by cassiomc** [comment]
Thanks @JunlinZhu ! Sorry the long delay to answer you.
Now the UIRecorder is able to record the actions but now I have other problem. After get the xpath, the Visual Studio couldn't find the element but if I execute on the local .exe it works. Is there some permission configuration on Visual Studio also? Another thing, I executed Visual Studio as administrator. Thanks!

**Comment by cassiomc** [comment]
It's working now!! I wasn't running the winappdriver.exe in a administrator cmd. Now the test found the element. I'm closing the case.
