### ISSUE TITLE
[Help] How do i wait for an element to disappear 

### ISSUE THREAD

**Issue by anunay1** [microsoft/WinAppDriver#688]
Hi 

I am using the below code for the element to disappear, 
try
            {   
                var wait = new WebDriverWait(session, TimeSpan.FromSeconds(30));
                wait.Until(visible => !session.FindElementByName(parameter).Displayed);
            }

            catch {  }
}

but it throws an exception, which is ok, as I can catch the exception, and move on, but this does not work 100%. Is there any other way to do the same.

**Comment by MissingPiece** [comment]
Isn't there a wait for expected condition "invisibility of an element"? Try that before trying to catch the exception.
