### ISSUE TITLE
"System.InvalidOperationException: An element command failed because the referenced element is no longer attached to the DOM." after running for 2hrs

### ISSUE THREAD

**Issue by anunay1** [Microsoft/WinAppDriver#689]
HI, 

I have a test that runs in an infinite loop, but after running for 2 hrs i get the exception:
"System.InvalidOperationException: An element command failed because the referenced element is no longer attached to the DOM."

I am not able to figure out why this exception happens. Urgent help will be highly appreciated.

**Comment by anunay1** [comment]
Closeing the bug

**Comment by cgetty12** [comment]
Did you come up with a good solution for this?

**Comment by lijinxinKing** [comment]
Did you come up with a good solution for this?
