### ISSUE TITLE
How to change Context from Native-View to Web-View for Debug Cordova Appx build

### ISSUE THREAD

**Issue by NileshKSingh** [Microsoft/WinAppDriver#69]
In Appium, Android and iOS debug builds have 2 context-views:
1) Native-View (by default)
2) Web-View

List of context-views can be retrieved by:
`((AppiumDriver<MobileElement>) driver).getContextHandles();`

Current activated context-view is determined by:
`((AppiumDriver<MobileElement>) driver).getContext();`

Context-View can be changed by:
`((AppiumDriver<MobileElement>) driver).context("WEB_VIEW_HYBRID_APP");`

=> Using WinAppDriver, How can I implement such methods for Win-10 hybrid applications?

**Comment by alakshmi1030** [comment]
We don't have multiple context support yet - but you can interact with the Webview of a Cordova app using WinAppDriver and the inspect.exe tool

**Comment by NileshKSingh** [comment]
The Windows Software Development Kit (SDK) for Windows 8.1 includes inspect.exe
How to get it for Windows-10 ?

**Comment by yodurr** [comment]
Inspect ships with Windows 10 sdk:
https://github.com/Microsoft/WinAppDriver#inspecting-ui-elements
