### ISSUE TITLE
an element could not be located on page using the given search

### ISSUE THREAD

**Issue by samkhayal** [microsoft/WinAppDriver#690]
can someone please help me with this , i am getting this error

{"using":"-windows uiautomation","value":"custom-background"}
HTTP/1.1 400 Bad Request
Content-Length: 102
Content-Type: application/json

{"status":32,"value":{"error":"invalid selector","message":"Invalid selector: -windows uiautomation"}}

i tried xpath in different ways even through te ui recorder and did not work for me

"/Pane[@name="Desktop 1"][@ClassName="#32769"]/Window[@name="CCH Axcess Login"][@ClassName="Window"]/Pane[@AutomationId="browser"]/Pane[@ClassName="Shell Embedding"]/Pane[@ClassName="Shell DocObject View"]/Pane[starts-with(@name,"https://**********")][@ClassName="Internet Explorer_Server"]/Pane[@AutomationId="custom-background"][@name="Wolters Kluwer Login"]

/Table/DataItem/Hyperlink[@name="792541"]/Text[@name="792541"]"

**Comment by MissingPiece** [comment]
Can you post what the inspect tool says and what xpath you're using to try to query?

**Comment by samkhayal** [comment]
I was able to resolve this issue thank you for the quick response Kevin ...

**Comment by samkhayal** [comment]
would you help me figure out how to find elements ? after logging into the first log in form the form closes and anew form opens where it has all the links on it . i checked the process id and it seems both use the same process id

**Comment by samkhayal** [comment]
> Can you post what the inspect tool says and what xpath you're using to try to query?
i got it resolved thanks ....
//*[contains(@Name,'Submit')]
would you help me figure out how to find elements ? after logging into the first log in form the form closes and anew form opens where it has all the links on it . i checked the process id and it seems both use the same process id

**Comment by samkhayal** [comment]
> Can you post what the inspect tool says and what xpath you're using to try to query?

would you help me figure out how to find elements ? after logging into the first log in form the form closes and anew form opens where it has all the links on it . i checked the process id and it seems both use the same process id

**Comment by MissingPiece** [comment]
@samkhayal I'm not quite sure what you're asking here?

Can you post screenshots of both the login form and then for with 'all the links on it'?
I can't quite picture what you're doing.

**Comment by samkhayal** [comment]
hi Kevin,

I will send the screenshots later. i have an issue with my vpn and unable
to connect to my work. the login window is seperate than the dashboard
window and so what happens is after you log in into the login page it
disappears and then a window flashes and then the dashboard opens. there is
an automation id but for some reason its not finding that window.

{"status":7,"value":{"error":"no such element","message":"An element could
not be located on the page using the given search parameters."}}

**Comment by samkhayal** [comment]
unfortunately  the application is down. what i am trying to do is to use the same process / runtimeid to create another windows element to set focus on it using findelement by id .. do you think this would work ?

**Comment by hassanuz** [comment]
@samkhayal, were you able to resolve your issue? I would recommend switching to a [desktop](https://github.com/microsoft/WinAppDriver/wiki/Frequently-Asked-Questions#when-and-how-to-create-a-desktop-session) session.
