### ISSUE TITLE
404 not found when running WinAppDriver manually 

### ISSUE THREAD

**Issue by imademethink** [microsoft/WinAppDriver#692]
Windows 10 + Developer mode
Download latest https://github.com/Microsoft/WinAppDriver/releases/tag/v1.1.1
Run command prompt in Admin mode
cd C:\Program Files (x86)\Windows Application Driver
WinAppDriver.exe // Run the exe

Now hit browser with http://127.0.0.1:4723
It shows  This 127.0.0.1 page can’t be found

Command prompt console logs:

C:\Program Files (x86)\Windows Application Driver>WinAppDriver.exe
Windows Application Driver listening for requests at: http://127.0.0.1:4723/
Press ENTER to exit.
==========================================
GET / HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Connection: keep-alive
Host: 127.0.0.1:4723
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
HTTP/1.1 404 Not Found

Please help to troubleshoot the issue. Do I need to revert back to older version.

**Comment by JunlinZhu** [comment]
There is no default web page on http://127.0.0.1:4723,  so getting 404 should be by-design. Try load http://127.0.0.1:4723/status:
{"build":{"revision":"8001","time":"Sat Mar  9 00:12:56 2019","version":"1.1.1903"},"os":{"arch":"amd64","name":"windows","version":"10.0.18362"}}

**Comment by hassanuz** [comment]
Marking issue as closed due to time-gap. Please reopen if issue persist.
