### ISSUE TITLE
Unable to click on TabItem Element

### ISSUE THREAD

**Issue by giocarmine** [microsoft/WinAppDriver#697]
Hello,

I have a WPF application with a main page containing 2 clickable tabs.

This is the xaml snippet:

```
  <TabControl x:Name="MainTabControl"
					Grid.Row="1"
					HorizontalAlignment="Stretch"
					Background="{DynamicResource ColorPanel5}"
					SelectedIndex="{Binding IndexMainTab, UpdateSourceTrigger=PropertyChanged, Mode=TwoWay}"
					VerticalAlignment="Stretch">
            
		<TabItem Name="FirstTabItem" MinWidth="100" Header="First" Style="{StaticResource ZeroHeader}">
			<MyNs:FirstUC/>
		</TabItem>
		<TabItem Name="SecondTabItem" MinWidth="100" Header="Second" Style="{StaticResource ZeroHeader}">
			<ClienteNs:SecondUC/>
		</TabItem>
	</TabControl>
```

i tried to access to the tab items using 

    session.FindElementByAccessibilityId("FirstTabItem");

But it didn't work.  
Looking at the Live Visual Tree i found out that the TextBox created to display the item has the name of the header, in this case "First". I tried to use that name but i wasn't able to find it either.

I was able to locate the tab item doing:

```
public WindowsElement GetMainWindowTabItem(WindowsDriver<WindowsElement> session)
{
    IReadOnlyCollection<WindowsElement> tabs = session.FindElementsByClassName("TabItem");

    foreach (WindowsElement element in tabs)
    {
        if (element.Text == "First")
        {
            return element;
        }
    }
}
```

With this i was able to get the element, but if i try to call .Click() on it i get the error:

    System.InvalidOperationException: An element command could not be completed because the element is not pointer- or keyboard interactable.

Any idea on how can i click on a tab item? what is the correct way to do it?
I didn't find any working example around..

Thanks

**Comment by JunlinZhu** [comment]
I created a simple WPF app with similar TabControl:

        <TabControl x:Name="MainTabControl"
                    Grid.Row="1"
                    HorizontalAlignment="Stretch"
                    SelectedIndex="{Binding IndexMainTab, UpdateSourceTrigger=PropertyChanged, Mode=TwoWay}"
                    VerticalAlignment="Stretch">

            <TabItem Name="FirstTabItem" MinWidth="100" Header="First">
                <TextBlock/>
            </TabItem>
            <TabItem Name="SecondTabItem" MinWidth="100" Header="Second">
                <TextBlock/>
            </TabItem>
        </TabControl>

and following UIRecorder generated code to click on the first Tab run successfully. Can you try to use UIRecorder for your scenario?

                Console.WriteLine("LeftClick on TabItem \"First\" at (21,13)");
                string xpath_LeftClickTabItemFirst_21_13 = "/Pane[@ClassName=\"#32769\"][@Name=\"Desktop 1\"]/Window[@ClassName=\"Window\"][@Name=\"MainWindow\"]/Tab[@AutomationId=\"MainTabControl\"]/TabItem[@Name=\"First\"][@AutomationId=\"FirstTabItem\"]";
                var winElem_LeftClickTabItemFirst_21_13 = desktopSession.FindElementByAbsoluteXPath(xpath_LeftClickTabItemFirst_21_13,1);
                if (winElem_LeftClickTabItemFirst_21_13 != null)
                {
                    winElem_LeftClickTabItemFirst_21_13.Click();
                }
                else
                {
                    Console.WriteLine($"Failed to find element using xpath: {xpath_LeftClickTabItemFirst_21_13}");
                    return;
                }

**Comment by giocarmine** [comment]
Hi Junlin,

Thanks for your reply. What type is the "desktopSession" you are using?
What i use is "WindowsDriver<WindowsElement>" and it doesn't have any "FindElementByAbsoluteXPath" method.  
I tried to use "FindElementByXPath" instead but i wasn't able to locate the element though..

**Comment by JunlinZhu** [comment]
DesktopSession.FindElementByAbsoluteXPath is defined in [https://github.com/Microsoft/WinAppDriver/tree/master/Tools/UIRecorder/UIRecorderTemplate](url)

You can try to use UIRecorder:
1) Build UIRecorder [https://github.com/Microsoft/WinAppDriver/tree/master/Tools/UIRecorder](url)  - (Select x86 or x64 as Solution Platform)
2) Launch UIRecorder as admin
3) Click on Recorder button
4) Move mouse cursor to any UI on desktop and wait for the UI to flash
5) Left/Right/Double click on flashing UI
6) Repeat Steps 4-5 (Keyboard input will also be recorded)
7) Click on UIRecorder Copy button to copy code to clipboard
8) Go to UIRecorderTemplate project under UIRecorder solution, and paste code in Program.cs as 
 
            try
            {
                //Paste generated code here



                //test complete
                bSuccess = true;
            }
            finally
            {
                Assert.AreEqual(bSuccess, true);
            }

9) Build and run UIRecorderTemplate project

You can see examples of UIRecorder generated automation code here [https://github.com/Microsoft/WinAppDriver/tree/master/Tests/AbsoluteXPath](url)

**Comment by giocarmine** [comment]
Hello Junlin,

i had some problems trying to build the UIRecorder and unfortunately i didn't have much time to spend on this.  
I have a working solution, it is not great but it works (the GetMainWindowTabItem() method).

Thanks for your advices

**Comment by Ruchita-shah** [comment]
@giocarmine  
I have facing same problem, Did you find any solution about this?
