### ISSUE TITLE
Unable to select item from telerik rad combobox

### ISSUE THREAD

**Issue by GaneshMucherla** [microsoft/WinAppDriver#701]
I am automating WPF applications where some controls are Telerik. I have a test scenario where i need to select an item from Telerik Rad ComboBox control.  I am able to find a way to use win app driver to select  an item from combo box.  Sample application code is below. Can you please suggest how to use WinApp driver for ComboBox controls

<telerik:RadComboBox x:Name="ViewerType" 
                                 Grid.Row="0" Grid.Column="1" Margin="5,0,0,0" 
                                 IsEditable="False" 
                                 IsReadOnly="True" 
                                 IsEnabled="True"
                                 ItemsSource="{Binding DummyTypeList, Mode=OneWay}" 
                                 SelectedValue="{Binding DummySettings.DummyViewer, Mode=TwoWay}"
                                 SelectedValuePath="DummyType">
                <telerik:RadComboBox.ItemTemplate>
            		<DataTemplate>
            			<StackPanel Orientation="Horizontal">
                            <TextBlock AutomationProperties.AutomationId="{Binding Description}" Text="{Binding Description}" />
            			</StackPanel>
            		</DataTemplate>
            	</telerik:RadComboBox.ItemTemplate>
				
                <i:Interaction.Behaviors>
                    <behaviors:RadComboBoxRightClickBehavior />
                </i:Interaction.Behaviors>

            </telerik:RadComboBox>

**Comment by hassanuz** [comment]
Hi @GaneshMucherla, Tim has a pretty good write-up on this thread over [here](https://github.com/microsoft/WinAppDriver/issues/318) - I suggest seeing if that answers a few of your CB questions.

**Comment by GaneshMucherla** [comment]
Thank you. I followed the links. Using Mouse, i am able to select the ComboBox item

**Comment by GaneshMucherla** [comment]
Issue resolved
