### ISSUE TITLE
Can't use session.Mouse.ContextClick()

### ISSUE THREAD

**Issue by JGjumpshot** [microsoft/WinAppDriver#705]
I am trying to perform a right click on my application and I can't find anything in the samples that show how to do this except for session.Mouse.ContextClick(). Visual Studio lets me know that this is deprecated, but there isn't any other documentation on how to use this. Is there something I'm missing? 

I do see that there is a message to use Action or the ActionBuilder class. How do I use these?

**Comment by jgkahua** [comment]
This is not depreciated.  How this works is that you need to specify the element as a parameter like so:

session.Mouse.ContextClick(element.Coordiantes);

By default, WinAppDriver is binded to find the coordinates by querying the inspection of UI elements in the session (the app you are testing).
