### ISSUE TITLE
Issue of touch events

### ISSUE THREAD

**Issue by rene-palalau** [Microsoft/WinAppDriver#71]
I have tested the latest release of the WinAppDriver with the purpose of creating automated touch UI tests. It seems that not all the touch interactions described in the JsonWireProtocol  are supported, especially the ones that we need for automated testing on the canvas.

We need a modality to start for example a one finger drag, two finger drag, gestures, specify exact location of fingers etc.. This type of interactions can be accomplished using the following endpoints:

POST

/session/:sessionId/touch/down

Finger down on the screen.

POST

/session/:sessionId/touch/up

Finger up on the screen.

POST

session/:sessionId/touch/move

Finger move on the screen.

But a request to any of these endpoints will return a response similar to this:
{
  "status": 9,
  "value": {
    "error": "unknown command",
    "message": "Command not recognized: POST: /session/785210A8-5764-43B4-8C3B-5E5F4E252904/touch/down"
  }
}

We are currently blocked on this part. Will these endpoints be supported in a future release? Are there any alternatives?

**Comment by khouzam** [comment]
We're looking at enhancing our touch support

**Comment by yodurr** [comment]
shipped in 0.9
