### ISSUE TITLE
Fail to launch share folder exe file: \\machinename\temp\test.exe

### ISSUE THREAD

**Issue by Travis-Sun** [microsoft/WinAppDriver#712]
My exe file is located in share folder. I can launch it manually, but can't lunch it with WinAppDriver. But if I copy the exe to local machine, it works. Does WinAppDriver not support lauch exe from share folder?

**Comment by aldobenitez** [comment]
I would need to know if it works as well

**Comment by danielsavi** [comment]
Are you getting any error msg? I'm not...

`appCapabilities.SetCapability("app", @"\\MYUNCPATH\test.exe");`

**Comment by hassanuz** [comment]
Please reopen if this persists on the latest v1.2 build.
