### ISSUE TITLE
What type of cast Im missing here when creating a List?

### ISSUE THREAD

**Issue by Saif4** [microsoft/WinAppDriver#718]
Im trying to create a list and store the values in that list with this code: 
IList<IWebElement> webElements = AccountWindowSession.FindElementsByTagName("ListItem");

But im getting this error:

Cannot implicitly convert type 'System.Collections.ObjectModel.ReadOnlyCollection<OpenQA.Selenium.Appium.Windows.WindowsElement>' to 'System.Collections.Generic.IList<OpenQA.Selenium.IWebElement>'. An explicit conversion exists (are you missing a cast?)

Can someone help?

**Comment by MikeSifanele** [comment]
var webElements = AccountWindowSession.FindElementsByTagName("ListItem");

**Comment by Saif4** [comment]
Thanks @MikeSifanele
