### ISSUE TITLE
[Help] How to identify elements which are not visible in inspect.exe

### ISSUE THREAD

**Issue by sachinrupadhyay** [microsoft/WinAppDriver#719]
Hi, We have a windows desktop based application which is built on WPF.
I was trying to Automate the same using WinAppDriver, in Java language (grovvy to be specific)
However, there are lot of instances where we are not able to locate certain elements, either by any of the locators.
I am not much aware of WPF, and i heard there is something called controls.

Now when i tried our application to automate using Ranorex, the same UI elements which was not visible in inspect.exe, Ranorex easily identifies them.

Please guide how such elements can be identified in WinAppDriver

**Comment by Hilarius86** [comment]
Did you try the (WinAppDriver) UIRecorder? It generates XPath strings you may find useful.

**Comment by Punniyakotti** [comment]
Even with UIRecorder I couldn't able to locate the item.
![excelcontrol](https://user-images.githubusercontent.com/4940456/58544474-f5718c80-821e-11e9-9050-ba0c91a38b83.jpg)
 I'm trying to locate the dropdown control in an Microsoft Excel cell and couldn't able to locate that control neither by inspect.exe nor by UIRecorder. Is there any other way  to locate this item? Any help here is appreciated.

**Comment by hassanuz** [comment]
Hi @sachinrupadhyay and @Punniyakotti, 

please tryout Junlin's workaround [here](https://github.com/microsoft/WinAppDriver/issues/725#issuecomment-497850905) and let us know if that does the trick.

**Comment by insachin** [comment]
This does not answers my question @hassanuz

**Comment by sangvvan** [comment]
Any one has solution for this issue?
