### ISSUE TITLE
Issue of pen events

### ISSUE THREAD

**Issue by rene-palalau** [Microsoft/WinAppDriver#72]
We would like to be able to simulate in a UWP application Pen events. These events would have to have PointerDeviceType == Pen and have the specific PointerPointProperties for Pen (such as IsBarrelButtonPressed, IsInverted, IsEraser, Pressure). 
Is there a way to express those with WinAppDriver?

**Comment by yodurr** [comment]
Not currently possible but we're investigating how we could add it.

**Comment by Tadimsky** [comment]
👍 
Would also love to get this feature - definitely want to be able to test our pen-focused app using WinAppDriver.

**Comment by hassanuz** [comment]
Closing issue. [WinAppDriver v1.1](https://github.com/Microsoft/WinAppDriver/releases/tag/v1.1-RC) has been released to add Pen / Multi-Touch automation.
