### ISSUE TITLE
Running **Winapp driver** test cases on headless mode

### ISSUE THREAD

**Issue by Dhatchuu47** [microsoft/WinAppDriver#721]
Hi All,

Do we have any update for running **Winapp driver** test cases on headless mode?. Our Requirement is to run test cases on Windows server 2016 machine through VSTS CI/CD process and mainly headless mode. 

I'm using Java language.

Do we have this option?

**Comment by hassanuz** [comment]
Hi @Dhatchuu47,

This **isn't** supported due to restrictions on the Windows OS in handling input injeciton.

**Comment by psutharsan** [comment]
I am running into the same issue, it works fine on active rdp but failed when it closes. We have selenium tests that have no problem running headless mode.

**Comment by fenchu** [comment]
Same issue, could anyone please address this, win OS should handle a headless mode.

**Comment by stefantinger** [comment]
As already mentioned by @hassanuz, this is a problem of the OS. WinAppDriver can't do anything about this.
