### ISSUE TITLE
Windows CalculatorTest example does not seem to work

### ISSUE THREAD

**Issue by Splinkle** [microsoft/WinAppDriver#730]
I am totally new to Appium, have followed the Windows driver setup documentation, and have reached to where it says to get CalculatorTest from github and fire up the tests.
I have Appium running on my windows machine (as administrator), the desktop client starts, and I can create a simple server with address 127.0.0.1:4723.
When I try to run the tests in CalculatorTest I get an error creating the session. Visual Studio say "Unexpected error. The URL '/session' did not map to a valid resource
Appium desktop says "No route found" "POST /session"
(Please see pictures for more info)

I assume I'm doing something wrong, but can't see what it is
![image](https://user-images.githubusercontent.com/24405784/58781325-e81c1f80-85db-11e9-9a3e-4ba3aae836f4.png)
![image](https://user-images.githubusercontent.com/24405784/58781340-ef432d80-85db-11e9-9bc7-cf8a69447f96.png)

**Comment by hassanuz** [comment]
Hi @Splinkle,

Please try appending **/wd/hub** at the end of the WindowsApplicrationDriverUrl, so ideally it would look like this: 

`private const string WindowsApplicationDriverUrl` = `http://127.0.0.1:4723/wd/hub`.

Appium requires this additional parameter to be able to properly redirect the call to WinAppDriver.exe.  

Thanks,
Hassan

**Comment by Splinkle** [comment]
Ah, thank you!  I missed that
