### ISSUE TITLE
WPF MVVM, after switching from the login-view to the main-view only the login-elements can be found.

### ISSUE THREAD

**Issue by FrenkieD** [microsoft/WinAppDriver#732]
My WPF MVVM application shows a login-view after startup. After entering a password, you can click the login button. If logging in is successful, the main-view will be shown. With WinAppDriver I'm able to: 
1. Start the application 
2. Find the password control 
3. Enter a password
4. Find the login-button
5. Click the login-button.

At this point the main-view is shown. The problem is this: when I search for elements that are on this main-view I can not find them. The only elements I can find are elelements that are on the login-view.

**Comment by anunay1** [comment]
Are you able to find the elements with inspect.exe

**Comment by FrenkieD** [comment]
Yes I am. I use the ClassName to find the elements. With the command session.FindElements(By.ClassName("Button")) I only find the buttons of the login-view. With inspect.exe I can find the two buttons on the main-view, furthermore inspect.exe shows that they do have ClassName=Button.

**Comment by anunay1** [comment]
Try using desktop session.

**Comment by FrenkieD** [comment]
Using a desktop session works. I'll try to re-write the tests. Thanks.

**Comment by anunay1** [comment]
Great, You are welcome.
