### ISSUE TITLE
WinAppDriver not able to work with winform Application

### ISSUE THREAD

**Issue by sameersakuja** [microsoft/WinAppDriver#734]
WinAppDriver not able to work with winform Application.

We are using WinAppDriver version 1.1 which fails to identify objects on Winforms giving 404 error.
Can you please provide the resolution for the same.

Code generated by WinAppUIRecorder is given below:

Console.WriteLine("LeftClick on \"Logon\" at (44,10)");
                string xp2 = "//Pane[@Name =\"Desktop
1\"][@ClassName=\"#32769\"]/Window[@AutomationId=\"Logon\"][@Name=\"System
Login\"]/Edit[@AutomationId=\"txtUser\"][@Name=\"User:\"]";
                var winElem2 = session.FindElementByXPath(xp2);
                if (winElem2 != null)
                {
                    winElem2.Click();
                }
                else
                {
                    Console.WriteLine($"Failed to find element {xp2}");
                    return;
                }

                // KeyboardInput
VirtualKeys=""KLEINR0"Keys.Tab"Crawford1"" CapsLock=False
NumLock=False ScrollLock=False
             Console.WriteLine("KeyboardInput
VirtualKeys=\"\"KLEINR0\"Keys.Tab\"Craw\"\" CapsLock=False
NumLock=False ScrollLock=False");
                winElem2.SendKeys("KLEINR0");

Below is the response which I received on WinAppDriver:

POST /session/3EFA9762-66A3-457F-B0AD-38336AA8F123/element HTTP/1.1
Accept: application/json, image/png
Content-Length: 32
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723
{"using":"name","value":"User:"}
HTTP/1.1 404 Not Found
Content-Length: 139
Content-Type: application/json
{"status":7,"value":{"error":"no such element","message":"An element
could not be located on the page using the given search parameters."}}

**Comment by JunlinZhu** [comment]
If UIRecorder generated xpath is used, you should see response from WinAppDriver like the following:

{"using":"xpath","value":"/Pane[@ClassName=\"#32769\"][@Name=\"Desktop 1\"]/Pane[@ClassName=\"Progman\"][@Name=\"Program Manager\"]/List[@ClassName=\"SysListView32\"][@Name=\"Desktop\"]/ListItem[@Name=\"This PC\"][starts-with(@AutomationId,\"ListViewItem-\")]"}

However your WinAppDriver response is: {"using":"name","value":"User:"}

Are you using the latest WinAppDriver?

**Comment by naeemakram** [comment]
Don't rely on the XML generated by the recorder. 
Search the controls through recorder and create your own code to access the application elements.

**Comment by sameersakuja** [comment]
Hi,
I am not using the XPath generated by the UIRecorder but using below code:

public class CMSSession
    {
        protected const string WindowsApplicationDriverUrl ="http://127.0.0.1:4723";
        private const string CMSAppId = @"C:\Program Files (x86)\Crawford\CMS\CMSProxy.exe";
        protected static WindowsDriver<WindowsElement> session;

        public static void Setup(TestContext context)
        {
            // Launch a new instance of CMS application
            if (session == null)
            {
                // Create a new session to launch CMS application
                DesiredCapabilities appCapabilities = new DesiredCapabilities();
                appCapabilities.SetCapability("app", CMSAppId);
               session = new WindowsDriver<WindowsElement>(new
Uri(WindowsApplicationDriverUrl), appCapabilities);
                // Set implicit timeout to 1.5 seconds to make element
search to retry every 500 ms for at most three times
                session.Manage().Timeouts().ImplicitWait =
TimeSpan.FromSeconds(5);
                session.FindElementByName("I Agree").Click();
                session.FindElementByName("User:").SendKeys("CROTHJ0");
}

I am using latest version of WinAppDriver v 1.0.1-Preview
I am able to launch the application and click on I Agree button but it fails to enter text on next screen objects like username and password.

Please do let me know if it supports winform application.

Below is the response which I received on WinAppDriver:
POST /session/3EFA9762-66A3-457F-B0AD-38336AA8F123/element HTTP/1.1
Accept: application/json, image/png
Content-Length: 32
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723
{"using":"name","value":"User:"}
HTTP/1.1 404 Not Found
Content-Length: 139
Content-Type: application/json
{"status":7,"value":{"error":"no such element","message":"An element
could not be located on the page using the given search parameters."}}

If possible we can schedule a call to discuss the issues and solutions.

Thanks in Advance,
Sameer Sukhija

**Comment by naeemakram** [comment]
Dear Sameer, 
I have used WinAppDriver for automation of a WinForms application of my own. I can tell for sure that the WinAppDriver supports WinForms. 
I think the control which you're trying to access after the click operation is not visible yet. 
After you click the "I Agree" button, try doing this: 
`System.Threading.Thread.Sleep(5000);`

The implicit wait doesn't always work I suppose. 
If adding a the sleep doesn't help, try using a different control property to search for the text-box. Maybe you could use AccessibilityID.

**Comment by anunay1** [comment]
> Hi,
> I am not using the XPath generated by the UIRecorder but using below code:
> 
> public class CMSSession
> {
> protected const string WindowsApplicationDriverUrl ="http://127.0.0.1:4723";
> private const string CMSAppId = @"C:\Program Files (x86)\Crawford\CMS\CMSProxy.exe";
> protected static WindowsDriver session;
> 
> ```
>     public static void Setup(TestContext context)
>     {
>         // Launch a new instance of CMS application
>         if (session == null)
>         {
>             // Create a new session to launch CMS application
>             DesiredCapabilities appCapabilities = new DesiredCapabilities();
>             appCapabilities.SetCapability("app", CMSAppId);
>            session = new WindowsDriver<WindowsElement>(new
> ```
> 
> Uri(WindowsApplicationDriverUrl), appCapabilities);
> // Set implicit timeout to 1.5 seconds to make element
> search to retry every 500 ms for at most three times
> session.Manage().Timeouts().ImplicitWait =
> TimeSpan.FromSeconds(5);
> session.FindElementByName("I Agree").Click();
> session.FindElementByName("User:").SendKeys("CROTHJ0");
> }
> 
> I am using latest version of WinAppDriver v 1.0.1-Preview
> I am able to launch the application and click on I Agree button but it fails to enter text on next screen objects like username and password.
> 
> Please do let me know if it supports winform application.
> 
> Below is the response which I received on WinAppDriver:
> POST /session/3EFA9762-66A3-457F-B0AD-38336AA8F123/element HTTP/1.1
> Accept: application/json, image/png
> Content-Length: 32
> Content-Type: application/json;charset=utf-8
> Host: 127.0.0.1:4723
> {"using":"name","value":"User:"}
> HTTP/1.1 404 Not Found
> Content-Length: 139
> Content-Type: application/json
> {"status":7,"value":{"error":"no such element","message":"An element
> could not be located on the page using the given search parameters."}}
> 
> If possible we can schedule a call to discuss the issues and solutions.
> 
> Thanks in Advance,
> Sameer Sukhija

{"using":"name","value":"User:"} this is wrong, it will be some text box. 
we can have a call to discuss the same.

**Comment by sameersakuja** [comment]
Hi,

Please let me know your available timings and your skype id to have a call on above topic

Thanks in Advance,
Sameer Sukhija

**Comment by anunay1** [comment]
I do not have a skype is we have a hangout session, my id is anunayathakur1@gmail.com

**Comment by naeemakram** [comment]
Hi, I've published a course about test automation using WinAppDriver. Given below is a special launch promo code(valid 4 days). 
[](https://www.udemy.com/course/appium-winappdriver-automation-testing/?couponCode=0B4AAB139DEA09114D95)
