### ISSUE TITLE
Accessing Clipboard

### ISSUE THREAD

**Issue by Senerader** [microsoft/WinAppDriver#745]
Hey, I am using WinAppDriver for an IDE test automation and I went in a situation where I was required to compare a specific portion of text inside an editor to a template. I am not able to access this portion of the text directly. You can either save the whole text inside of an editor to a string using **Element.Text;** or you can select this portion of the text, using IDE functionality and keyboard input, and copy it to the Clipboard using a keyboard shortcut **Ctrl + c**. 
I thought it would be possible to read data from the Windows Clipboard inside of my script, however, whenever I was trying to add the corresponding library (for Clipboard class), references inside of my program had become broken (not possible to use locators). 
All in all, I want to access the Window Clipboard to store the data inside to a string in order to perform some comparisons to relevant templates.
Could you, please, suggest a solution or give a hint of how is it possible to overcome the issue?
Thank you.

**Comment by riccione** [comment]
Could you share your code? I would like to see it and perhaps I can help you.

**Comment by Senerader** [comment]
Sure, for simplicity I will demonstrate it on NotepadTest sample:
`[TestMethod]
        public void EditorKeyboardShortcut()
        {
            // Type a known text sequence, select, copy, and paste it three times
            editBox.SendKeys("789");
            editBox.SendKeys(Keys.Control + "a" + Keys.Control); // Select all using Ctrl + A keyboard shortcut
            editBox.SendKeys(Keys.Control + "c" + Keys.Control); // Copy using Ctrl + C keyboard shortcut
`
Here **editBox** represents the main editor in a notepad, so firstly I send a text to the editor ("789"), select all the text inside of the editor using **Ctrl+a** shortcut, and, finally, I copy selected text by using "Ctrl+c" shortcut. My question is how can I access the text I have just copied to a windows clipboard in a C# script?

**Comment by stefantinger** [comment]
What do you mean by "references inside of my program had become broken (not possible to use locators)"? For accessing the Clipboard you can either use the WPF class from System.Windows or the Forms class from System.Windows.Forms. As a reference look this [stackoverflow post](https://stackoverflow.com/questions/3546016/how-to-copy-data-to-clipboard-in-c-sharp)

**Comment by Senerader** [comment]
I fixed the issue I was trying to describe.
Indeed, class **System.Windows.Forms** is required. Moreover, you have to add it in Visual Studio references in an explorer window manually, and then include the namespace to a script.
The problem was that when you include the namespace, nonprintable **Keys** enumerator from Appium and **Keys** from Windows Forms were conflicting because they have the same name.
So, in order to fix the issue, you just have to precede **Keys**, which I use to simulate non-printable keys, with the Appium namespace, not the Windows Forms one.
