### ISSUE TITLE
UIAutomationCore.h error C2146

### ISSUE THREAD

**Issue by dziegelmiller** [microsoft/WinAppDriver#746]
In Visual Studio 2019, UIAutomationCore.h causes compile errors C4430 then C2146:
Severity	Code	Description	Project	File	Line	Suppression State
Error	C4430	 missing type specifier - int assumed. Note: C++ does not support default-int	UIXPathLib	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\UIAutomationCore.h	41	
then
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2146	 syntax error: missing ';' before identifier 'IRawElementProviderSimple'	UIXPathLib	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\UIAutomationCore.h	41

**Comment by hassanuz** [comment]
Please reopen if you're still facing this issue on the latest version of VS2019.
