### ISSUE TITLE
WinAppDriver can't find element.

### ISSUE THREAD

**Issue by didhddldlq** [microsoft/WinAppDriver#747]
I'm developing a UI test program with WinAppDriver.

We use Visual Studio 2019 and WinAppDriver 1.1 version and inspect.

What I'm going to test function is Project Create With Visual Studio and our Extension Explorer.

I finished create project with WinAppDriver but WinAppDriver seems to not to find our extension explorer in visual studio 2019.

this is my code. firstLine projectName Click is not work.

![code](https://user-images.githubusercontent.com/16128186/60489587-a87e4b80-9cdf-11e9-8e82-5d5710d8b4d3.jpg)

in projectName "Site.FP_Planning1" is setting. 
![window](https://user-images.githubusercontent.com/16128186/60489588-a87e4b80-9cdf-11e9-9fb9-5079e91dfb96.jpg)

inspect also say that this element is called projectName.
![inspect](https://user-images.githubusercontent.com/16128186/60489782-22163980-9ce0-11e9-879b-9f5aea552f8e.jpg)

below is error message.
{"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}

Please tell me any solutions if exist.
Thank you.

ps. not our extend explorer but also solution explorer and team explorer can't found by WinAppDriver in visual studio 2019.

**Comment by riccione** [comment]
Use UIRecorder for location elements.

**Comment by didhddldlq** [comment]
I already have used UI Recorder but it doesn't work. I have try once again but there is status 7 error.
like this..
![xpatherror](https://user-images.githubusercontent.com/16128186/60778157-c7159400-a170-11e9-89b8-55795fbcdf9c.png)

**Comment by didhddldlq** [comment]
I did it, but there are problems in typing keyboard. session.KeyBoard.SendKeys is sometimes(*) return state 13 error. "unknown error","message":"An unknown error occurred in the remote end while processing the command."

if i reboot my computer, It works... so strange.
Anyone know why?
