### ISSUE TITLE
Samples fail when calling FindElementByXPath

### ISSUE THREAD

**Issue by jneidlinger** [Microsoft/WinAppDriver#75]
Running the calculator sample fails at lines like this:

`CalculatorSession.FindElementByXPath("//Button[@Name=\"One\"]").Click();`

Log:

![image](https://cloud.githubusercontent.com/assets/1914540/19353355/25ae2fca-9131-11e6-8a5a-f49fb7751451.png)

Using the latest release (v0.5-beta)

**Comment by yodurr** [comment]
It works for me.  What version of Windows are you running?  Could be a different version of the inbox Calculator.  Or the calculator is in a mode that doesn't have these buttons shown.

![image](https://cloud.githubusercontent.com/assets/11341342/19406072/2c27374e-9234-11e6-9b09-29986ff6aa6b.png)

**Comment by jneidlinger** [comment]
@yodurr  Hmm, this was on 10586. I just tried it on 14393 and it worked fine... so you're right, it's working...
Apologies for the noise. Closing.
