### ISSUE TITLE
UI Recorder Release

### ISSUE THREAD

**Issue by Tiberriver256** [microsoft/WinAppDriver#770]
Where can I download the latest release / zip of the UI Recorder? All the docs point to this repo but it's not in the releases section.

**Comment by hassanuz** [comment]
Hi @Tiberriver256, you can download a zip of the latest binaries from [here](https://github.com/microsoft/WinAppDriver/releases/tag/UIR-v1.1).

**Comment by Tiberriver256** [comment]
Thank you!
