### ISSUE TITLE
DBMS is not supported in your current installation

### ISSUE THREAD

**Issue by Iziksh** [microsoft/WinAppDriver#772]
Hi,
I'm trying to start our application .

Here are what I have done:

Java code for starting up a app:
capabilities.setCapability("app", "C:\\Apps\\IQ\\Environment\\IQ\\iq.exe");
capabilities.setCapability("platformName", "Windows");
capabilities.setCapability("deviceName", "WindowsPC");
CalculatorSession = new WindowsDriver (new URL("http://127.0.0.1:4723"), capabilities);
CalculatorSession.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);

The app launched (logged in  window opened)  but with error  **"DBMS sybase is not supported in your current installation"**

 The app shortcut properties including  ini file :
**Target:** C:\\Apps\\IQ\\Environment\\IQ\\iq.exe  C:\Apps\IQ\IQSystem\INI\IQ_A.ini 
  (The Target  including two path as you see )

How can i add the ini file to my test? 

Thanks

**Comment by naeemakram** [comment]
You can specify arguments in the DesiredCapabilities object. Use "appArguments" key for supplying app launch arguments.

**Comment by Iziksh** [comment]
@naeemakram  Thanks, it works!

**Comment by naeemakram** [comment]
Great, please like the answer! :)
