### ISSUE TITLE
Stop Task fails with an error around log file

### ISSUE THREAD

**Issue by ncksol** [microsoft/WinAppDriver#773]
We've started to get this error when running Stop task on WinAppDriver:
"Cannot find path 'C:\winappdriverlog.txt' because it does not exist."

This is running on our own agent. We've tried creating the file manually, but this only produced another error:
"Access to the path 'C:\winappdriverlog.txt' is denied.". 
Giving "Everyone" the "Full Control" permission to that file didn't help.

**Comment by alfonso-mireles** [comment]
Adding more to this issue. This was a direct fallout from a fix regarding this issue:
https://github.com/microsoft/WinAppDriver/issues/765

@hassanuz was working on this issue introduced by his fix.

**Comment by horoxix** [comment]
This issue is also blocking me. Thank you

**Comment by ncksol** [comment]
@horoxix as a temporary workaround I am running an Powershell Task with inline command:
(get-wmiobject -Class Win32_Process -Filter "name like 'WinAppDriver%'").terminate()

**Comment by horoxix** [comment]
> @horoxix as a temporary workaround I am running an Powershell Task with inline command:
> (get-wmiobject -Class Win32_Process -Filter "name like 'WinAppDriver%'").terminate()

Hey thank you @ncksol  I will try this. Just in place of the "Stop winappdriver" task? 

Thanks again!

**Comment by ncksol** [comment]
> > @horoxix as a temporary workaround I am running an Powershell Task with inline command:
> > (get-wmiobject -Class Win32_Process -Filter "name like 'WinAppDriver%'").terminate()
> 
> Hey thank you @ncksol I will try this. Just in place of the "Stop winappdriver" task?
> 
> Thanks again!

Yep. Just normal powershell task with "Inline" option and this code.

**Comment by horoxix** [comment]
Thank you @ncksol I truly appreciate it. 
Just tested and it worked great!

**Comment by rubberduck203** [comment]
I’m starting to really wonder about this tool. It seems the team has a habit of closing issues that haven’t actually been fixed.
