### ISSUE TITLE
WinAppDriver Prerelease Crashes when I want to click on an element

### ISSUE THREAD

**Issue by miksch123** [microsoft/WinAppDriver#777]
Hi. I have experienced a crash when I want to click on an element that might have the same name in different parts of the system. Now the way I handled this was finding all elements that match what can be found and then use the appropriate one. Unfortunately since today It ran into a crash and said that the element you wanted to click on has the same runtimeID.

**Comment by hassanuz** [comment]
Hi @miksch123, are you still experiencing this issue on the [v1.2 release](https://github.com/microsoft/WinAppDriver/releases/tag/v1.2-RC)?

**Comment by miksch123** [comment]
I did not really get a chance to test that as I was moving towards updating the winium we driver and trying to lift it out of its grave.

**Comment by miksch123** [comment]
It is still reproducible. The workaround for it is to find all elements with that location strategy name and then select based on unique parameters like size, location on the screen etc.
