### ISSUE TITLE
Working with the Windows taskbar

### ISSUE THREAD

**Issue by alexmirea** [Microsoft/WinAppDriver#78]
Hello, 

Is it possible to hook up WinAppDriver to the Windows taskbar?
I want to be able to open the Notification panel and click on the buttons in there.
I tried hooking up to the `explorer.exe` but that opens up a new File Explorer window.

Thank you!

**Comment by khouzam** [comment]
We have instructions on the readme.md file. Use inspect to find the notification panel and explore from there. You should be able to find the element by name "Notification Chevron" and take it from there.

**Comment by alexmirea** [comment]
@khouzam Thanks for the reply! Unfortunately I was unable to find a way to get the elements from the taskbar.
As I said the only idea I had was to start a session to `C:\Windows\explorer.exe`, is this the correct application that I have start a session with, for interacting with the Windows taskbar elements?
When I do this, a new file explorer window appears. I am able to find elements from that window, such as the search box etc, without any problems, but I cannot interact with the taskbar elements of Windows..

Please note that I did use `inspect.exe` to figure out the names, automation id of elements before trying anything. Interacting with the file explorer window that WinAppDriver opens when I use `C:\Windows\explorer.exe` as the app to start a session with, works ok.

The name I used to search by was found with `inspect.exe` as being `Action Center`
![explorer](https://cloud.githubusercontent.com/assets/5648025/19574716/3370fe2e-9714-11e6-8b7d-81c914d84ca5.png)

My feeling is that I need to start a WinAppDriver session with another application than`explorer.exe`

Thank you!

**Comment by timotiusmargo** [comment]
Hi @alexmirea,

You have the right idea and we do have the support for the scenario you are trying to cover. This scenario covered in the **AlarmClockTest** sample below:
https://github.com/Microsoft/WinAppDriver/tree/v0.6-beta/Samples/C%23/AlarmClockTest

As you can see in https://github.com/Microsoft/WinAppDriver/blob/v0.6-beta/Samples/C%23/AlarmClockTest/Scenario.cs, we create a desktop session as follows:
`
// Create a session for Desktop
DesiredCapabilities desktopCapabilities = new DesiredCapabilities();
desktopCapabilities.SetCapability("app", "Root");
DesktopSession = new IOSDriver<IOSElement>(new Uri(WindowsApplicationDriverUrl), desktopCapabilities);
`

This desktop session will not launch any app but will allow you to query anything under the root **Desktop** tree you see in the **Inspect** tool. This session will help you getting to the notification or other peripheral UI you may have. The **AlarmClockTest** sample uses this desktop session to dismiss the new notification popup on the taskbar as follows:
`
AppiumWebElement newNotification = DesktopSession.FindElementByName("New notification");
Assert.IsTrue(newNotification.FindElementByAccessibilityId("MessageText").Text.Contains(NewAlarmName));
newNotification.FindElementByName("Dismiss").Click();
`

You should be able to similarly create a desktop session to perform the scenario you need. However, please note that Windows system UI such as the **Action Center** changes from time to time. So your test script may need to be updated if there are changes to the **AccessibilityId/AutomationId** etc.

Tip: You can launch the **Action Center** using the **Window Keys + A** shortcut as you can find on https://github.com/Microsoft/WinAppDriver/blob/v0.6-beta/Tests/W3CWebDriver/Keys.cs#L162
`
// Lauch action center using Window Keys + A
session.Keyboard.PressKey(OpenQA.Selenium.Keys.Command + "a" + OpenQA.Selenium.Keys.Command);
`

**Comment by alexmirea** [comment]
@timotiusmargo Thank you very much! That sounds like a good way to do it! I will try it out and let you know how it goes.
