### ISSUE TITLE
SAP GUI Logon Pad click is not working always

### ISSUE THREAD

**Issue by Geraldf** [microsoft/WinAppDriver#788]
I try to use the automate SAP action, but I do have problems already during the Login via SAPGUI Login Pad.

I can find the element by using the "find_element_by_name" function. 
the the first click works fine `p71.click()`
it positions the mouse cursor  correctly and performs a mouse click.

But all subsequent click's to the element do not work. Only the mouse cursor get's positioned, but no click is performed. 

        def startP71(self): 
                p71= self.driver.find_element_by_name("[EMEA] ERP-P71")
                anmeld = self.driver.find_element_by_name("Anmelden")
                p71.click()
                if (anmeld.is_enabled()):
                    anmeld.click()
                else:
                    actionChains = ActionChains(self.driver)
                    actionChains.move_to_element(p71)
                    actionChains.click()
                    actionChains.perform()
                    self.driver.find_element_by_name("[EMEA] ERP-P71").click()
                    anmeld.click()

Looking to the appium log, I cannot see any issues. 
`[2019-08-05 04:29:44][WinAppDriver] [STDOUT] {"sessionId":"B556AACB-722D-4ED1-850B-4BC7CC08A9D4","status":0}`
`[2019-08-05 04:29:44][WD Proxy] Got response with status 200: {"sessionId":"B556AACB-722D-4ED1-850B-4BC7CC08A9D4","status":0}`
`[2019-08-05 04:29:44][WD Proxy] Replacing sessionId B556AACB-722D-4ED1-850B-4BC7CC08A9D4 with a7537e0c-cbc6-432b-a566-fe3677e5ea81`
`[2019-08-05 04:29:44][HTTP] <-- POST /wd/hub/session/a7537e0c-cbc6-432b-a566-fe3677e5ea81/click 200 766 ms - 63`
`[2019-08-05 04:29:44][HTTP]`

**Comment by jsa34** [comment]
I had an issue with clicking buttons and when I put a breakpoint in, it turned out there were multiple buttons that matched the button being clicked wasn't the "active" button, but a related, hidden element.

This might be your case - are there other related elements to the button that could be clicked to see if it works using that element's locator?

**Comment by Geraldf** [comment]
thanks for replying to my issue. Since the SAP Logon Pad is an Win32 application, I was using the `Inspect.exe` program to get the element name. I cannot see any other name, which could be hidden.

![2019-08-06 12_23_31-SAP GUI Logon Pad click is not working always · Issue #788 · microsoft_WinAppDri](https://user-images.githubusercontent.com/679932/62532700-4e742700-b845-11e9-8c08-e9f988523097.jpg)

**Comment by anunay1** [comment]
can you try the same with accessibility id like 
 session.FindElementByAccessibilityId("ListViewItem-1").click()

**Comment by Geraldf** [comment]
My issue is not a WinAppDriver issue. I could even recreate the behavior with manual mouse actions. 
It turned out, that when I manually position the mouse at the exact same position as the WinAppDriver is doing it, I can even manually recreate the same SAP behavior. 
So I used the `actionChains.move_to_element_with_offset(p71,3,3) ` to get the think working.
