### ISSUE TITLE
FindElementsByXPath should not throw NoSuchElementException

### ISSUE THREAD

**Issue by jneidlinger** [Microsoft/WinAppDriver#79]
The documented behavior for the "FindElements" flavors in Selenium is to return an empty collection when no elements are found, and not throw an exception.

FindElementsByAccessibilityId already does this properly, but FindElementsByXPath instead throws "OpenQA.Selenium.NoSuchElementException: An element could not be located on the page using the given search parameters."

I'd expect FindElementsByXPath to return an empty collection instead, matching the behavior of FindElementsByAccessibilityId.

Quote from official documentation:

> findElement should not be used to look for non-present elements, use findElements(By) and assert zero length response instead.

**Comment by yodurr** [comment]
I just hit this too.  Thanks for filing the bug.

**Comment by yodurr** [comment]
please test with the new 0.7 release.  thanks!
