### ISSUE TITLE
WinAppDriver Not Selecting Items from Pop Up menu Window

### ISSUE THREAD

**Issue by MumtazRashid** [microsoft/WinAppDriver#790]
We are testing our own application with WinAppDriver but it is having issues in switching between windows, I tried with drivers.getWindowHandles() 

def windowHandles = driver.getWindowHandles()
driver.switchTo().window(windowHandles[0]);
 Through above code I am able to switch to main window after login window, But after that when I click on one button which displays Pop Up menu Item window ,Its not able to select any menu item from it, All has unique name property, Even with Actions class it is not getting selected ,It is throwing execption NoSuchElement , Is there any way we can select menu item from popup winow ?

**Comment by moonkey124** [comment]
Try to find the popup first and then select the item in it. 
```
Session.FindElementByAccessibilityId("exampleMenuItemId").Click();
var menuPopup = Session.FindElementsByClassName("Popup").FirstOrDefault(p => p.Displayed);
if (menuPopup != null)
{
	var subMenuItem = menuPopup.FindElementByAccessibilityId("exampleSubMenuItemId");
	Session.Mouse.Click(subMenuItem.Coordinates);
}
```
