### ISSUE TITLE
No communication response when focus is on remote desktop

### ISSUE THREAD

**Issue by miksch123** [microsoft/WinAppDriver#798]
Hello I was working with WinAppDriver while having a remote desktop session to another machine. Weirdly enough every time i set focus on the remote desktop window while Winappdriver is running a test there will be no communication happening. Do you maybe know why that might be the case?

**Comment by hassanuz** [comment]
Can you expand further on "there will be no communicating happening"? 

What does the WinAppDriver.exe console window report? Does it work when you don't interact with the remote desktop window?

**Comment by miksch123** [comment]
closed as it was not reproducible anymore.
