### ISSUE TITLE
Does WinAppDriver Support Win32 Desktop App?

### ISSUE THREAD

**Issue by EthanJiang** [Microsoft/WinAppDriver#8]
Hello 

The document says that WinAppDriver supports Classic Windows App Testing. But I are not quite sure that how to understand the Classic windows apps.

So I still want to confirm here, Does WinAppDriver officially support Win32 Desktop App?

**Comment by yodurr** [comment]
It's a goal and is still being worked on.  We'll be adding more details over the coming weeks.  Thanks.

**Comment by EthanJiang** [comment]
@yodurr Thanks
