### ISSUE TITLE
Unable to click TextBLock inside SplitView

### ISSUE THREAD

**Issue by ddelapasse2** [Microsoft/WinAppDriver#80]
Hi,

I created a sample UWP app to show a problem I'm having.  I can click buttons in the hamburger menu, but there's a Textblock (back button) just above the hamburger and for some reason neither Click or Tap will work.

I doubt it's a bug, but probably something I'm doing wrong.  If someone could take a quick look I would really appreciate it!  I'm having a big problem with a mobile app's performance degrading after some amount of clicks and this would help me reproduce it so much easier!

I placed the example zip in google drive - there's only one test.
https://drive.google.com/file/d/0B2b6tVpnL4c3TEdXM0ZKbkZ4dnc/view?usp=sharing

thanks!!!

**Comment by timotiusmargo** [comment]
Thanks for the feedback @ddelapasse2!. We recently release [v0.6-beta](https://github.com/Microsoft/WinAppDriver/releases/tag/v0.6-beta) that should issue a click action on top of the TextBlock. Could you please verify if it addresses the problem you encounter?

**Comment by ddelapasse2** [comment]
Yes!  Fixed in v0.6-beta.  Thanks!!!
