### ISSUE TITLE
Exception in Appium console with win app driver 1.1.1

### ISSUE THREAD

**Issue by anunay1** [microsoft/WinAppDriver#800]
Hi, 
When I am trying to run win app driver 1.1.1 i get the below exception in appium console. 
![image](https://user-images.githubusercontent.com/7989610/62853659-a9f15980-bd0a-11e9-8a38-e642c83c4584.png)

Can anyone help?

**Comment by hassanuz** [comment]
Hi @anunay1 

Which version of Appium are you using?

**Comment by anunay1** [comment]
I am using 1.6.3

**Comment by anunay1** [comment]
updated appium to version 1.13.0, still getting the same error 
![image](https://user-images.githubusercontent.com/7989610/62913752-f42a1780-bdaa-11e9-855c-3273705c506a.png)

![image](https://user-images.githubusercontent.com/7989610/62913763-00ae7000-bdab-11e9-913a-366a074a3e44.png)

**Comment by anunay1** [comment]
@hassanuz : Any updates on this, is the issue with WAD or appium.
