### ISSUE TITLE
WPF: How to call ListView PreviewMouseLeftButtonUp click event

### ISSUE THREAD

**Issue by ThummalaJanardhanReddy** [microsoft/WinAppDriver#805]
Hi,
I have a ListView and on click of PreviewMouseLeftButtonUp I'm calling one common method and based on the ListViewItem name I'm calling different functions. Each function will create new child window and shows.
My Test cases are passing but child windows are not opening.

Thanks in advance.

**Comment by anunay1** [comment]
Can you share the winapp app logs.

**Comment by ThummalaJanardhanReddy** [comment]
> Can you share the winapp app logs.

Hi @anunay1 ,
Thanks for reply.I got the solution for above scenario and managed to work done. 
Thanks again. :)
