### ISSUE TITLE
Can't find form created by a MDI child

### ISSUE THREAD

**Issue by MihaMarkic** [microsoft/WinAppDriver#813]
I'm using a DevExpress PopupContainerEdit control that creates a new child Form upon clicking dropdown button. It is placed on a vanilla (top level) WinForms Form.
After dropdown is shown, I'm trying to get a handle on it. I first get WindowsElement of the form and then call its FindElementByName("XXX"). And that's fine, it works.

However, **when the same exact Form is a MDI child**, **I can't get the dropdown** no matter what. FindElementByName just throws the exception.
Test it by clicking the dropdown button and label on the right should say _Not Found_.

[Here is my sample](https://misc.rthand.com/mdi_sample.rar) (compiled code included, since DevExpress controls are commercial). Note both TestAsync() methods that do the search.

Driver is 1.0.1-preview, .net is 4.7.1

**Comment by MihaMarkic** [comment]
Here is what inspect says about that form
![image](https://user-images.githubusercontent.com/2194935/63222843-2671b580-c1ad-11e9-9bed-65091696235b.png)

**Comment by DLightstone** [comment]
I am certain you intend well, but few people wisely execute code from non-commerical sources.
The source code for the test will prove more useful.

**Comment by MihaMarkic** [comment]
@DLightstone Code is included in the sample.

**Comment by DLightstone** [comment]
@MihaMarkic 
I found a C# project. The project ap[pears to be the application program which will be tested
I did not find a program which would perform the testing.

There are a number of anomalies for you to consider.
(1)  You indicate  FindElementByName("XXX") as a means for getting access to a control.
The screen capture indicates "XXX" is an AutomationId.
When I retrieve a control for AutomationIds  I invoke FindElementByAccessibilityId

(2) You indicate using using a DevExpress PopupContainerEdit .
I quess PopupContainerEdit is a popup window.
Popups can be anchored to a form
Popups can be anchored to the root session.

The strategy for getting the control depends on the means by which it is anchored.
I use the following as appropriate

public static WindowsDriver<WindowsElement> FindRootPopupWindow(string popupName)
      {
         WindowsDriver<WindowsElement> currentSession;

         currentSession = GuiRootAccess.FindWindowSession(popupName, 1);
         Assert.IsNotNull(currentSession);
         Assert.IsNotNull(currentSession.SessionId);

         return (currentSession);

      }

      public static OpenQA.Selenium.Appium.AppiumWebElement FindAnchoredPopupWindow(string parentwindowName,
                                                                                    string popupName,
                                                                                    Int32 intDelayInSeconds)
      {
         Int32 intTimeout;
         OpenQA.Selenium.Appium.AppiumWebElement buttonElement;
         OpenQA.Selenium.Appium.AppiumWebElement CreateNewProjectWindow;
         Int32 loopCount;
         Int32 loopLimit;

         intTimeout = intDelayInSeconds + 10;
         CreateNewProjectWindow = GetRootWindow(parentwindowName, intTimeout);
         Assert.IsNotNull(CreateNewProjectWindow);

         loopCount = 0;
         loopLimit = (intDelayInSeconds + 2) / 3;
         // implicit timeout is 3
         buttonElement = null;
         while ((buttonElement == null) && (loopCount < loopLimit))
         {
            try
            {
               buttonElement = CreateNewProjectWindow.FindElementByName(popupName) as WindowsElement;
            }
            catch
            {
               loopCount = loopCount + 1;
               buttonElement = null;

            }
         }
         return (buttonElement);

      }

**Comment by MihaMarkic** [comment]
Hey @DLightstone 

Thanks for the input. 
Said that, yes, "testing" is done within the app for the sake of simplicity and shouldn't affect the outcome at all. It could be two separate apps, but that would yield the same. Plus it'd be harder to catch dropdown event.
It works when Form1 is the top form and doesn't when it's a MDI child. 
That makes 1, 2 working fine since it works in the former case.
As per popup window, it's a child of Form1, see
![image](https://user-images.githubusercontent.com/2194935/63245046-65604380-c25f-11e9-9e36-2653d93d5358.png)
and as such it's found when Form1 is TopLevel but not when it's a MDI Child.

**Comment by DLightstone** [comment]
I found the testing code. (I don't usually develop in C#. I barely know the language)

It is not clear to me what you are trying to accomplish. Possibilities are
(1) Characterize the prerelease of Microsoft.WinAppDriver.Appium.WebDriver
(2) Characterize the DevExpress drop-down  list control
(3) Develop a test procedure for a drop-down  list control.
(4) Formulate a strategy which would allow a application tester to test using a drop-down list
(5) Something else

Which ones (and I hope there is only 1)?
If more than one simplify your life. Eliminate all unknowns but one. 

I do not particularly like tests that involve manual operations. In this case activating the drop-down .
Using your test style, I would have placed a second command button on the form. 
The command button would have located the drop-down  control and clicked it to activate your test. 

Using a separate application and tester. The tester would located the drop-down  control and clicked it  

I see no real reason to catch the drop-down event during a test.
(1) The control probably has a means for extracting all its items. 
If you want to know them use it.
(2) The control probably has a means to directly set its value
If you want to test an application use it

Perhaps you can indicate why you want to capture the dropdown event. 

Finally years ago I discovered that it was possible to interfere with the operation of a hardware device simply by trying to observe its operation (via monitoring status registers). That possibility can not be precluded.

**Comment by MihaMarkic** [comment]
> It is not clear to me what you are trying to accomplish.

Isn't it clear by now? I'm trying to get a reference to the popup form. Which *works* when non MDI and doesn't when MDI.

**Comment by DLightstone** [comment]
What you want is very much clear. What you are trying to accomplish is a separate matter. 
More importantly you are more than a few unknowns to work against, so characterizing is more difficult.

Assume the bug is in the prerelease of Microsoft.WinAppDriver.Appium.WebDriver, the implementation of Inspect.exe and any other software Microsoft provided which is needed to construct the XML 

You might try to dynamically catch the XML the is being used at the time when you query for the missing control.

Something like the following might give you some insight
      public static void SaveSourceToFile( string strFile)
      {
         WindowsDriver<WindowsElement> session;

         session = Form1.Session;
         var source = session.PageSource;

         System.Xml.XmlDocument xmlDoc = new System.Xml.XmlDocument();
         System.Xml.XmlTextWriter w = new System.Xml.XmlTextWriter(strFile,
                                                                  System.Text.Encoding.BigEndianUnicode);
         xmlDoc.LoadXml(source);

         xmlDoc.WriteTo(w);
         w.Close();

      }

**Comment by hassanuz** [comment]
Closing original issue. @MihaMarkic, please create a new ticket for any remaining Qs.

**Comment by MihaMarkic** [comment]
@hassanuz What remaining Qs? The original problem wasn't addressed at all.
