### ISSUE TITLE
Run WinAppDriver on WIndows 7

### ISSUE THREAD

**Issue by QuantumDeveloper** [Microsoft/WinAppDriver#82]
Hi.
Just wanted to know is it possible to run WinAppDriver on WIndows 7 to automate desktop applications or it is completely not possible? 
For the current moment trying to run WinAppDriver.exe I receive error saying that **api-ms-win-core-version-l1-1-0.dll** is missing.
Is it expected?

**Comment by khouzam** [comment]
At this time we're only supporting running WinAppDriver on Windows 10. We don't have any plans currently to make it run on Windows 7. It will be able to automate an application that runs on Windows 7, but for the testing you'll have to run the application on Windows 10.

**Comment by QuantumDeveloper** [comment]
@khouzam Thanks for your answer.
BTW, does it supports testing of WPF applications?

**Comment by matthargett** [comment]
@khouzam will the source code be made available so I can contribute support for Windows 8.1 and/or 7?
