### ISSUE TITLE
HTTP/1.1 404 Not Found : Unable to locate UI elements using appium

### ISSUE THREAD

**Issue by vamank** [microsoft/WinAppDriver#821]
I have a custom windows desktop app QACTLauncher.exe that I am trying to automate using Appium. I use the following python code for the same. The app gets launched but the UI elements don't get recognised and it throws the error mentioned in the title.

Please find attached Python script logs (python_logs.txt) and winapp driver logs (win_app_log.txt)
[win_app_log.txt](https://github.com/microsoft/WinAppDriver/files/3521032/win_app_log.txt)
[python_logs.txt](https://github.com/microsoft/WinAppDriver/files/3521033/python_logs.txt)

Have tried https://github.com/Microsoft/WinAppDriver/issues/26 and solutions mentioned in that. Does not help. Please help.

Python code:
class SimpleQACTTests(unittest.TestCase):

    @classmethod

    def setUpClass(self):
        #set up appium
        desired_caps = {}
        desired_caps["app"] = r"C:\Users\asiahyd\AppData\Local\QACT 7.4\QACTLauncher.exe"
        # desired_caps["appTopLevelWindow"] = proc
        # desired_caps["platformName"] = "Windows"
        self.driver = webdriver.Remote(
            command_executor='http://127.0.0.1:4723',
            desired_capabilities= desired_caps)

    @classmethod
    def tearDownClass(self):
        self.driver.quit()
		
    def test_initialize(self):
        # time.sleep(3)
        # print (self.driver.window_handles)
        # print (self.driver.desired_capabilities)
        # self.driver.find_element_by_name("Connect To Device").click()
        WebDriverWait(self.driver, 10)
        button = self.driver.find_element_by_accessibility_id('m_connectTargetBtn').click()

**Comment by anunay1** [comment]
is the element shown using inspect.exe and what kind of application is this, WIN32,WPF or UWP

**Comment by anunay1** [comment]
if it's an QT application, i don't think WAD will help

**Comment by vamank** [comment]
It is a WPF application.

Got it resolved.
Had to get windows_handle for the launched App and then switch to that app using the same before making any UI actions.

**Comment by Ravi9562** [comment]
Hi below is the error I am getting while trying to run an application
"
POST //session/ HTTP/1.1
Accept: application/json
Accept-Encoding: identity
Connection: keep-alive
Content-Length: 277
Content-Type: application/json;charset=UTF-8
Host: 127.0.0.1:4723
User-Agent: appium/python 0.52 (selenium/3.141.0 (python windows))
X-Idempotency-Key: 59985125-c125-435b-94d9-ea260d7b508d

{"capabilities": {"firstMatch": [{"appium:app": "D:\\Teraterm\\teraterm\\ttermpro.exe", "platformName": "Windows", "appium:deviceName": "WindowsPC"}]}, "desiredCapabilities": {"app": "D:\\Teraterm\\teraterm\\ttermpro.exe", "platformName": "Windows", "deviceName": "WindowsPC"}}
HTTP/1.1 404 Not Found
"

below is the error I am getting while running script in pycharm
"
Traceback (most recent call last):
  File "C:/Users/tejaw/PycharmProjects/anurag/teraterm.py", line 8, in <module>
    driver = webdriver.Remote('http://127.0.0.1:4723/', desired_capabilities = desired_caps)
  File "D:\Python\Python38\lib\site-packages\appium\webdriver\webdriver.py", line 147, in __init__
    super(WebDriver, self).__init__(
  File "D:\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "D:\Python\Python38\lib\site-packages\appium\webdriver\webdriver.py", line 227, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, parameters)
  File "D:\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 208, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: 
"

I am trying to automate teraterm application. Please do help me

**Comment by harshkahlon** [comment]
> Hi below is the error I am getting while trying to run an application
> "
> POST //session/ HTTP/1.1
> Accept: application/json
> Accept-Encoding: identity
> Connection: keep-alive
> Content-Length: 277
> Content-Type: application/json;charset=UTF-8
> Host: 127.0.0.1:4723
> User-Agent: appium/python 0.52 (selenium/3.141.0 (python windows))
> X-Idempotency-Key: 59985125-c125-435b-94d9-ea260d7b508d
> 
> {"capabilities": {"firstMatch": [{"appium:app": "D:\Teraterm\teraterm\ttermpro.exe", "platformName": "Windows", "appium:deviceName": "WindowsPC"}]}, "desiredCapabilities": {"app": "D:\Teraterm\teraterm\ttermpro.exe", "platformName": "Windows", "deviceName": "WindowsPC"}}
> HTTP/1.1 404 Not Found
> "
> 
> below is the error I am getting while running script in pycharm
> "
> Traceback (most recent call last):
> File "C:/Users/tejaw/PycharmProjects/anurag/teraterm.py", line 8, in
> driver = webdriver.Remote('http://127.0.0.1:4723/', desired_capabilities = desired_caps)
> File "D:\Python\Python38\lib\site-packages\appium\webdriver\webdriver.py", line 147, in **init**
> super(WebDriver, self).**init**(
> File "D:\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in **init**
> self.start_session(capabilities, browser_profile)
> File "D:\Python\Python38\lib\site-packages\appium\webdriver\webdriver.py", line 227, in start_session
> response = self.execute(RemoteCommand.NEW_SESSION, parameters)
> File "D:\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "D:\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 208, in check_response
> raise exception_class(value)
> selenium.common.exceptions.WebDriverException: Message:
> "
> 
> I am trying to automate teraterm application. Please do help me

Hi Ravi , I am also facing the same issue. Did you get any solution?

**Comment by anunay1** [comment]
You need to create a root session in catch block and then switch to the top level window. more info in wiki

**Comment by Karo320** [comment]
Hey, could you explain what you mean by "create a root session in catch block and then switch to the top level window"? I just started with WinAppDriver and Im getting this error with my very first test. I cannot even start it. Or at least could you share link to wiki where I could read more about that?
Thanks!

**Comment by anunay1** [comment]
#1295 check this

**Comment by anunay1** [comment]
@Karo320 what exception do you get the console window

**Comment by Karo320** [comment]
> @Karo320 what exception do you get the console window

literally the same https://github.com/microsoft/WinAppDriver/issues/821#issuecomment-634425702
Sorry for Christmas-break-long delay :D
