### ISSUE TITLE
XPath issue on MS Outlook automation

### ISSUE THREAD

**Issue by nbulusanjr** [microsoft/WinAppDriver#822]
[strip down version.txt](https://github.com/microsoft/WinAppDriver/files/3523610/strip.down.version.txt)

 var newEmailButton= desktopSession.FindElement(By.XPath(".//Button[@Name='New Email']"));

WAD response:

[HTTP] {"using":"xpath","value":".//Button[@Name='New Email']"}
[MJSONWP (18d3991b)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/18d3991b-4a5f-44a0-8f96-c881d0851372/element' to command name 'findElement'
[WD Proxy] Proxying [POST /wd/hub/session/18d3991b-4a5f-44a0-8f96-c881d0851372/element] to [POST http://127.0.0.1:4724/wd/hub/session/A28CDC59-99FC-4AED-89E1-BCC3A5D7F2FA/element] with body: {"using":"xpath","value":".//Button[@Name='New Email']"}
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] ==========================================
[WinAppDriver] [STDOUT] POST /wd/hub/session/A28CDC59-99FC-4AED-89E1-BCC3A5D7F2FA/element HTTP/1.1
[WinAppDriver] [STDOUT] Accept: application/json, */*
[WinAppDriver] [STDOUT] Connection: close
[WinAppDriver] [STDOUT] Content-Length: 56
[WinAppDriver] [STDOUT] Content-Type: application/json; charset=utf-8
[WinAppDriver] [STDOUT] Host: 127.0.0.1:4724
[WinAppDriver] [STDOUT] User-Agent: appium
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"using":"xpath","value":".//Button[@Name='New Email']"}
[WinAppDriver] [STDOUT] HTTP/1.1 404 Not Found
[WinAppDriver] [STDOUT] Content-Length: 139
[WinAppDriver] [STDOUT] Content-Type: application/json
[WinAppDriver] [STDOUT] 
[WinAppDriver] [STDOUT] {"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}
[WD Proxy] Got an unexpected response: {"status":7,"value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters."}}

This query is working using xpath query analyzer however on WAD it doesn't work. I have attached here the strip down version of the XML.

**Comment by nbulusanjr** [comment]
Here is the generated xpath:

"/Pane[@ClassName=\"#32769\"][@Name=\"Desktop 1\"]/Window[@ClassName=\"rctrl_renwnd32\"][@Name=\"Inbox - myemail@domain.com - Outlook\"]/Pane[@ClassName=\"MsoCommandBarDock\"][@Name=\"MsoDockTop\"]/ToolBar[@ClassName=\"MsoCommandBar\"]/Pane[@ClassName=\"MsoWorkPane\"][@Name=\"Ribbon\"]/Pane[@ClassName=\"NUIPane\"]/Pane[@ClassName=\"NetUIHWNDElement\"]/Pane[@ClassName=\"NetUInetpane\"][@Name=\"Ribbon\"]/Pane[@ClassName=\"NetUIPanViewer\"][@Name=\"Lower Ribbon\"]/Group[@ClassName=\"NetUIOrderedGroup\"][@Name=\"Home\"]/Group[@ClassName=\"NetUIChunk\"][@Name=\"New\"]/Button[@ClassName=\"NetUIRibbonButton\"][@Name=\"New Email\"]"

**Comment by hassanuz** [comment]
We've made some XPath optimizations on the latest WAD v1.2 release. Please try that while enabling the experimental capability: 

`C#: appCapabilities.SetCapability("ms:experimental-webdriver", true);`

Reopen if the issue persists.
