### ISSUE TITLE
WinAppDriver not detecting element but Inspect.exe is detecting

### ISSUE THREAD

**Issue by YouWhy** [microsoft/WinAppDriver#827]
I am trying to automate the Local Group Policy editor functionality. I am able to automate the following path all the way up to the point where I have to select a value from a drop down. Please review to screen shot attached. The drop down list is populated in Inspect.exe, however, WinAppDriver is not loading that element in the page source and hence I am not able to take any action on it.
 I am also dumping the page source, see it attached.

[source.txt](https://github.com/microsoft/WinAppDriver/files/3535202/source.txt)

![WinAppDriverError](https://user-images.githubusercontent.com/39198291/63604784-3f55de80-c592-11e9-9fcb-cf544539e802.png)

My script is failing to detect the following xpath:
//Window[@Name='Local Group Policy Editor']/Window[@Name='Manage preview builds']/Pane[@AutomationId='tableLayoutFullForm']/Pane[@AutomationId='splitContainer']/Pane[starts-with(@ClassName,'WindowsForms10')]/Pane[@Name='Options:'][@AutomationId='flowLayoutPanelDynamic']/Pane[@Name='Options:'][@AutomationId='flowLayoutPanelSet the behavior for receiving preview builds:']/ComboBox[@Name='Set the behavior for receiving preview builds:'][@AutomationId='dropDownListSet the behavior for receiving preview builds:']**/List[@Name='Set the behavior for receiving preview builds:']/ListItem[@Name='Enable preview builds']**

**Comment by hassanuz** [comment]
@YouWhy,

I believe Inspect generates the Tree structure in a different way compared to WinAppDriver & UI Recorder. My personal recommendation is to use the XPath / Tree structure represented by UI Recorder since we developed that to be consistent with WinAppDriver.

I'm marking this issue as closed due to resolution.
