### ISSUE TITLE
Unable to send keys to data grid.

### ISSUE THREAD

**Issue by SanderW1989** [microsoft/WinAppDriver#847]
Issue resolved

**Comment by DLightstone** [comment]
How?

**Comment by SanderW1989** [comment]
The application under test was built to only accept (very specific) keyboard input on the top window level. After layering multiple sessions and windows (as mentioned in the Cortana WinAppDriver sample) I was easily able to resolve it like this: 

var eagleWindow = Helpers.DesktopSession.FindElementByName("MainWindow");
eagleWindowWindow.SendKeys(convertedBarcodeResult + Keys.Enter);

**Comment by DLightstone** [comment]
Thank you
