### ISSUE TITLE
Running test on remote Teamcity build agent 

### ISSUE THREAD

**Issue by AlexKovalnogov** [microsoft/WinAppDriver#850]
Hi!
I have task run test for win app on remote Teamcity build agent(it's virtual machine that included to domain of our company) ,I did all preparation set all in teamcity , install app on remote machine, etc. But one problem that I can't fix it's lock screen on virtual machine after about 10 minutes(it's settings for all PC of our company  that included to domain -group policy ) 

Due to security admin :
-  can't move out this machine from domain or set special rules for user on this machine  
-  Cant install logon utility that can login to windows via command prompt

What I did :
1. Try to add VBS script that imitate pushing on keyboard each minute but unfortunately it does not work maybe it happens because it is virtual machine and real key board is not connected   
 
I able to run test only when I'm connected to build agent via Remote Desktop in this case its real interactive mode
When screen lock  WinAppDriver can't find element and return 500 or when test runs and screen was locked 

Is there any workaround ,windows or driver settings?

**Comment by hassanuz** [comment]
I'm not aware of any OS workarounds, but perhaps you can try using the Actions API to invoke a T[ouch Input gesture](https://github.com/microsoft/WinAppDriver/blob/c33c66ba22b6cf2353146df28a5f8f3a54f762bd/Samples/C%23/PaintTest/ScenarioDraw.cs#L41) and that can do the trick? Haven't tried it myself, so no guarantee.

**Comment by AlexKovalnogov** [comment]
hassanuz tnx. I've found other workaround .Few days ago I understood that my script that imitate pushing keyboard stops after run test ( after winappdriver start but script process is present in task manager ) and I decided to add  2 steps in Teamcity kill process wscript.exe(it's my script) and next step run it again via command line
