### ISSUE TITLE
The video attachment is missing in the test summary

### ISSUE THREAD

**Issue by susmithamohan** [microsoft/WinAppDriver#858]
Hi, I have written multiple test cases using WinAppDriver, it works fine in the pipeline and the test summary gives only the Pass Fail count no video attachment is available along with it. I could not use the Hosted VS 2017 pool as my App is not able to be installed there so I am using a VM as an agent pool to run my UI tests alone. Could you please tell me if there are some other steps involved to record this UI Please?

**Comment by hassanuz** [comment]
Hi @susmithamohan,

A few things:

1. Have you tried the VS2019 pool? Most likely your app can be installed there. 
2. Do you have a [RunSettings ](https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/UITests/UITestSettings.runsettings) that is being called up by the VSTestRunner task? 

You would need to point the VSTest Task to the Runsettings for the video recording to be configured.

**Comment by susmithamohan** [comment]
Hi @hassanuz 

I will try implementing that in VS2019 pool. Thank you

I do have RunSettings, but have created a project with .net framework. so I keep getting the following error:
Starting test execution, please wait...
Test run will use DLL(s) built for framework .NETFramework,Version=v4.0 and platform X86. Following DLL(s) do not match framework/platform settings.
Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.dll is built for Framework .NETPortable,Version=v4.5,Profile=Profile259 and Platform AnyCPU.
Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll is built for Framework .NETFramework,Version=v4.5 and Platform AnyCPU.
Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll is built for Framework .NETFramework,Version=v4.5 and Platform AnyCPU.
Microsoft.VisualStudio.TestPlatform.TestFramework.dll is built for Framework .NETPortable,Version=v4.5,Profile=Profile259 and Platform AnyCPU.
Test Project 2.0.dll is built for Framework .NETFramework,Version=v4.7.2 and Platform AnyCPU.
Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.dll is built for Framework .NETPortable,Version=v4.5,Profile=Profile259 and Platform AnyCPU.
Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll is built for Framework .NETFramework,Version=v4.5 and Platform AnyCPU.
Microsoft.VisualStudio.TestPlatform.TestFramework.dll is built for Framework .NETPortable,Version=v4.5,Profile=Profile259 and Platform AnyCPU.
Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll is built for Framework .NETStandard,Version=v1.5 and Platform AnyCPU.
Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll is built for Framework .NETCore,Version=v5.0 and Platform AnyCPU.
Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll is built for Framework .NETFramework,Version=v4.5 and Platform AnyCPU.
Microsoft.VisualStudio.TestPlatform.TestFramework.dll is built for Framework .NETPortable,Version=v4.5,Profile=Profile259 and Platform AnyCPU.
Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll is built for Framework .NETPortable,Version=v4.5,Profile=Profile259 and Platform AnyCPU.
Microsoft.VisualStudio.TestPlatform.TestFramework.dll is built for Framework .NETPortable,Version=v4.5,Profile=Profile259 and Platform AnyCPU.
Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll is built for Framework .NETCore,Version=v5.0 and Platform AnyCPU.
Microsoft.VisualStudio.TestPlatform.TestFramework.dll is built for Framework .NETPortable,Version=v4.5,Profile=Profile259 and Platform AnyCPU.
Go to http://go.microsoft.com/fwlink/?LinkID=236877&clcid=0x409 for more details on managing these settings.

**Comment by susmithamohan** [comment]
Hi @hassanuz 

I am able to run my project locally and I can get the video inside TestResults folder. But I am not able to do so in pipeline. Do you think I should configure something differently ?

I am stuck in this so I am not able to proceed. Please help me out when you can.

Thanks you !

**Comment by susmithamohan** [comment]
Issue resolved. Thank you ! :)
