### ISSUE TITLE
Run tests on Windows Phone simulator

### ISSUE THREAD

**Issue by dzaiats** [Microsoft/WinAppDriver#86]
Hello,

Is it possible somehow to specify device name and run the tests on Windows Phone simulator?

Thank You

**Comment by timotiusmargo** [comment]
Hello @dzaiats, we don't support the scenario you mentioned above at the moment

**Comment by dzaiats** [comment]
Hello Timotius,

Thank You very much for Your answer! So, currently it's possible to run only on Desktop application, right?

**Comment by timotiusmargo** [comment]
Yes you are right
