### ISSUE TITLE
GetScreenshot WinAppDriver - UnKnown Error

### ISSUE THREAD

**Issue by Aishwarya-UR** [microsoft/WinAppDriver#862]
Hi,

While trying to use GetScreenshot on the WindowsElement, I'm getting the below exception:

"an unknown error occurred in the remote end while processing the command"

I tried casting the element to RemoteWebElement and then take screenshot, yet no luck.

I see that this issue is created on the similar lines, yet no proper resolution:
https://github.com/Microsoft/WinAppDriver/issues/660
Can someone please help?

**Comment by anunay1** [comment]
this works for me: 
  Screenshot screenshot = session.GetScreenshot();
            screenshot.SaveAsFile(screenShotFolder + filename + "_" + DateTime.Now.ToString("yyyy_MM_dd") + ".jpeg", ImageFormat.Jpeg);

**Comment by anunay1** [comment]
Can you share the code also

**Comment by Aishwarya-UR** [comment]
I see that you are using session variable to getScreenshot, but I'm using WindowsElement in that place to get screenshot. That's the only difference.
But I have solved it by using Bitmap for capturing the image.
 
Thanks for the response.

**Comment by alonrbar** [comment]
@Aishwarya-UR Can you please share a snippet of how you solved it using Bitmap?
I'm having a similar issue and would love to try that too.

**Comment by Aishwarya-UR** [comment]
@alonrbar Here it is, check if it helps you;

Bitmap bitmap = new Bitmap(currentControl.Rect.Width, currentControl.Rect.Height); //currentControl is a Windows element
                using (Graphics g = Graphics.FromImage(bitmap))
                    g.CopyFromScreen(new Point(currentControl.Rect.Left, currentControl.Rect.Top), Point.Empty, currentControl.Rect.Size);
                bitmap.Save(filePathToSave, ImageFormat.Png);

**Comment by alonrbar** [comment]
@Aishwarya-UR 
Amazing! Thank you!

**Comment by alonrbar** [comment]
By the way, you can enable syntax highlighting if you wrap the code snippet with three back ticks - [see GitHub docs here](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks). The [language identifier](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting) for C# is `csharp`. 

For instance:

```csharp
Bitmap bitmap = new Bitmap(currentControl.Rect.Width, currentControl.Rect.Height); //currentControl is a Windows element
```

**Comment by Aishwarya-UR** [comment]
@alonrbar - Glad it helped and thanks for the tip.

**Comment by abdulnoman666** [comment]
@alonrbar it worked for me. thanks for the help

**Comment by alonrbar** [comment]
@abdulnoman666 
No problem but I was just the one asking the question, the solution was actually shared by @Aishwarya-UR :)

**Comment by abdulnoman666** [comment]
@Aishwarya-UR  thanks for the solution. It worked :)
