### ISSUE TITLE
FindElementsByTagname doesn't work in this case

### ISSUE THREAD

**Issue by Exoow** [microsoft/WinAppDriver#863]
I'm trying to enter a date in the Date picker control.

Please observe the following code, which makes sure I am using the correct tagname: I can locate an element by its value (name), but using that element's tag name, I can't find it using the FindElementsByTagname method?

Edit: workaround using FindElementsByClassName("LoopingSelectorItem") works...
```
var picker = App.Session.FindElementByAccessibilityId("DatePickerFlyoutPresenter");
var list = picker.FindElementByAccessibilityId("MonthLoopingSelector");
Console.WriteLine(list.TagName); // ControlType.List
var monthByName = list.FindElementByName("september");
var monthsByTag = list.FindElementsByTagName(monthByName.TagName); // ControlType.ListItem
Console.WriteLine(monthsByTag.Count); // 0...
```

**Comment by anunay1** [comment]
Tag name  first letter should always been in capital letter for e.g if inspect shows tag name"list "
the it should be given as  session.FindElementByTagName("List")

**Comment by Exoow** [comment]
It is... "list" is a code variable?
