### ISSUE TITLE
How to identify an element when there is more than 1 instance exist with the same object properties

### ISSUE THREAD

**Issue by dillibabu123** [microsoft/WinAppDriver#865]
I need to click an Link element when there is more than 1 instance exist with the same object properties. When using inspect tool it is showing same properties for both instance of link object. How to click on 1 of the 2 instances of link object. 

Actually in UFT tool we can identify using index property like 0,1, 2 like this then it is identify and click respective instances but in WinAppDriver how to handle this. 
Please find the screenshot.
![SameObject_DifferentInstance](https://user-images.githubusercontent.com/55104669/64909435-94b48400-d729-11e9-8c2d-20b6bedaeb1a.png)

**Comment by anunay1** [comment]
It can be handled the same way in WAD also. using index property 
var names = session.findelementbyAccessiblityID("automationID")
names[index].click()

**Comment by DLightstone** [comment]
The question probably relates to which of the two you should work with.
use FindElementsByX and get them all.

If you need to distinguish between the two, WinAppDriver probably can't

**Comment by dillibabu123** [comment]
I am able to handle this scenarios with below code. Thanks guys for your suggestions.

 IList<WindowsElement> HPLink = App_Session.FindElementsByXPath(".//Text[@Name='N:JAMES,EDWARD']");
 HPLink[0].Click();
 HPLink[1].Click();

 string Acttext_1 = HPLink[0].GetAttribute("Name");
 string Acttext_2 = HPLink[1].GetAttribute("Name");
