### ISSUE TITLE
Dropdown list is opened and immediately closed after click like doubleclick

### ISSUE THREAD

**Issue by micheal650** [microsoft/WinAppDriver#869]
I used click() on a dropdown list but the dropdown list is opened and closed immediately so that I can't choose any item. pls someone help me for a idea. Thx a lot.

**Comment by anunay1** [comment]
Try giving some delay after you click on the drop down list

**Comment by micheal650** [comment]
@anumay1 thanks. But the Click() works like doubleclick and I do not have any chance to Set a delay after click. and Tap, MouseDown and Press are not successful top for me. The dropdown list closes immerdiately after click.

**Comment by micheal650** [comment]
@anumay1 thanks. But the Click() works like doubleclick and I do not have any chance to set a delay after click. and Tap, MouseDown and Press are not working successful for me too. The dropdown list closes immerdiately after click.

**Comment by Saif4** [comment]
Use the Mouse class

**Comment by Saif4** [comment]
Use the Mouse class 
Driver.Mouse.MouseMove(YourElement.Coordinates);
                Driver.Mouse.DoubleClick(null);
Something similar

**Comment by micheal650** [comment]
@Saif4 Thanks you, ist's working now
