### ISSUE TITLE
How to automate the content of WPF webbrowser control

### ISSUE THREAD

**Issue by schalla1** [microsoft/WinAppDriver#871]
Hi Team,

We are using winappdriver to automate the wpf application and selenium for web application. In one of the scenario, web application is opening through wpf webbrowser control(framework Id: Internet explorer). I couldnot able to identify the web/html controls inside the wpf webbrowser control. Please suggest best way to automate this scenario.

Thanks,
SravanChalla

**Comment by stu4355226** [comment]
My app was a web application in a winform webbrowser control. I was able to locate elements through winappdriver.

**Comment by hassanuz** [comment]
Hi @schalla1,

If inspect is able to pick up the elements, then WinAppDriver will be able to pick them up as well and automate against them. 

Otherwise, you'd have to use a hybrid solution of WebDriver in parallel for WinAppDriver.
