### ISSUE TITLE
Working with .NET Core projects

### ISSUE THREAD

**Issue by godrose** [microsoft/WinAppDriver#872]
I've been trying to make this work in .NET Core 3. Now when you have a simple WPF project it works but as soon as there is more complex stuff I cannot launch the app resulting in 'failed to locate opened application window with appid winappdriver' issue.
I tried to update the drivers and saw the the WinAppDriver for dotnet isn't kept up-to-date at all. Is it even alive?

**Comment by godrose** [comment]
Apparently not

**Comment by hassanuz** [comment]
It doesn't matter if  your app is .Net Core or not, WinAppDriver should work with it all the same. 

> I tried to update the drivers and saw the the WinAppDriver for dotnet isn't kept up-to-date at all. 

What drivers are you referencing here? There is no WinAppDriver specific to dotnet... 

If WinAppDriver is unable to launch the WPF window, then you could try [creating a desktop session ](https://github.com/microsoft/WinAppDriver/wiki/Frequently-Asked-Questions#when-and-how-to-create-a-desktop-session) and then try [attaching to your WPF app window](https://github.com/microsoft/WinAppDriver/wiki/Frequently-Asked-Questions#when-and-how-to-attach-to-an-existing-app-window).
