### ISSUE TITLE
Inspecting WPF validation

### ISSUE THREAD

**Issue by RussDev1124** [microsoft/WinAppDriver#873]
I'm kind of new to using winappdriver, or automated testing in general, unfortunately. I'm trying to use winappdriver on a WPF application that uses validators, and I want to detect that, after a Save button was clicked, that a certain UI element, which has WPF validation on it, has passed (or not). I'm using inspect.exe, and I'm not seeing any elements that hold anything related to the validation adorner! Can anyone help?

**Comment by khoachung89** [comment]
I'm not sure about the solution. However, as I know, WinAppDriver can only see what Inspect can see. If you cannot see the element you need in inspect, there is noway you can select them by WinAppDriver too. You may dump the PageSource of your session to see.
