### ISSUE TITLE
WinAppDriver not locating open button inside open file dialog box?

### ISSUE THREAD

**Issue by tanya1308** [microsoft/WinAppDriver#876]
I have made a application. in it's UI i have a button when i click on it an open file dialog box opens up i have mad this dialog box using the OpenFileDialog(). There is a open button inside this dialog box. I want to automate the UI TESTING of my application for which i need it to click on the open button but winappdriver is not able to locate and click on this button. i tried to locate it using automationid xpath name classname but nothing worked.

any suggestions?

**Comment by anunay1** [comment]
have you tried using the keyboard commands i.e. session.keyboard.SendKeys

**Comment by tanya1308** [comment]
yes i have tried to use keyboard command to press enter and the access key of the open button but gives me the error that this command is not supported

**Comment by anunay1** [comment]
please share the code

**Comment by anunay1** [comment]
And also the screen shot of the application if possible.

**Comment by tanya1308** [comment]
i used the inspect tool to get the various properties of this open button:

How found:	Mouse move (537,492)
hwnd=0x00020AA2 64bit
 class="Button"
 style=0x50030000 ex=0x4
Name:	"Open"
ControlType:	UIA_ButtonControlTypeId (0xC350)
LocalizedControlType:	"button"
BoundingRectangle:	{l:470 t:474 r:558 b:500}
IsEnabled:	true
IsOffscreen:	false
IsKeyboardFocusable:	true
HasKeyboardFocus:	false
AccessKey:	"Alt+o"
ProcessId:	8508
RuntimeId:	[2A.20AA2]
AutomationId:	"1"
FrameworkId:	"Win32"
ClassName:	"Button"
NativeWindowHandle:	0x20AA2
ProviderDescription:	"[pid:14388,providerId:0x20AA2 Main:Nested [pid:8508,providerId:0x20AA2 Annotation(parent link):Microsoft: Annotation Proxy (unmanaged:UIAutomationCore.dll); Main:Microsoft: MSAA Proxy (unmanaged:UIAutomationCore.dll)]; Hwnd(parent link):Microsoft: HWND Proxy (unmanaged:uiautomationcore.dll)]"
IsPassword:	false
HelpText:	""
LegacyIAccessible.ChildId:	0
LegacyIAccessible.DefaultAction:	"Press"
LegacyIAccessible.Description:	""
LegacyIAccessible.Help:	""
LegacyIAccessible.KeyboardShortcut:	"Alt+o"
LegacyIAccessible.Name:	"Open"
LegacyIAccessible.Role:	push button (0x2B)
LegacyIAccessible.State:	hot tracked,focusable (0x100080)
LegacyIAccessible.Value:	""
IsAnnotationPatternAvailable:	false
IsDragPatternAvailable:	false
IsDockPatternAvailable:	false
IsDropTargetPatternAvailable:	false
IsExpandCollapsePatternAvailable:	false
IsGridItemPatternAvailable:	false
IsGridPatternAvailable:	false
IsInvokePatternAvailable:	true
IsItemContainerPatternAvailable:	false
IsLegacyIAccessiblePatternAvailable:	true
IsMultipleViewPatternAvailable:	false
IsObjectModelPatternAvailable:	false
IsRangeValuePatternAvailable:	false
IsScrollItemPatternAvailable:	false
IsScrollPatternAvailable:	false
IsSelectionItemPatternAvailable:	false
IsSelectionPatternAvailable:	false
IsSpreadsheetItemPatternAvailable:	false
IsSpreadsheetPatternAvailable:	false
IsStylesPatternAvailable:	false
IsSynchronizedInputPatternAvailable:	false
IsTableItemPatternAvailable:	false
IsTablePatternAvailable:	false
IsTextChildPatternAvailable:	false
IsTextEditPatternAvailable:	false
IsTextPatternAvailable:	false
IsTextPattern2Available:	false
IsTogglePatternAvailable:	false
IsTransformPatternAvailable:	false
IsTransform2PatternAvailable:	false
IsValuePatternAvailable:	false
IsVirtualizedItemPatternAvailable:	false
IsWindowPatternAvailable:	false
IsCustomNavigationPatternAvailable:	false
FirstChild:	[null]
LastChild:	[null]
Next:	"Cancel" button
Previous:	"" pane
Other Props:	Object has no additional properties
Children:	Container has no children
Ancestors:	"Open" dialog
	"MedInsight VHI Preprocessor 1.0" window
	"Desktop 1" pane
	[ No Parent ]
Also i am attaching a screenshot of the open file dialog box which contains this open button
![Capture](https://user-images.githubusercontent.com/48258298/65305667-65769a80-dba1-11e9-83f4-815ab80bd5d7.JPG)

**Comment by tanya1308** [comment]
@anunay1  i used session.findElementByAccessibilityId("1").Click(); to get the open button clicked also i used session.findElementByName("Open").Click(); but nothing worked
i also tried to use session.Keyboard.SendKeys("Enter"); to press enter but it gave me error that this command is not supported

**Comment by anunay1** [comment]
It's should be session.keyboard.Sendkeys(Keys.Enter)

**Comment by tanya1308** [comment]
@anunay1  i tried that too but no luck

**Comment by anunay1** [comment]
What is the error that you get the the WAD console when you use session.keyboard.Sendkeys(Keys.Enter) because when I use i do not get any error. 
if possible please share the complete code, by hiding the proprietary part, also which version of WAD that you are using

**Comment by anunay1** [comment]
This worked for me for a notepad test: 
session.FindElementByName("File").Click();
            Thread.Sleep(1000);
            session.FindElementByAccessibilityId("2").Click();
            Thread.Sleep(1000);
            session.Keyboard.SendKeys(@"C:\Users\xxxx\Desktop\automationvnext.txt");
            Thread.Sleep(1000);
            session.Keyboard.SendKeys(Keys.Enter);

**Comment by anunay1** [comment]
please let me know if you want the complete VS solution.

**Comment by tanya1308** [comment]
i am using v1.1 of WAD
this is the command that i am using 
 session.Keyboard.SendKeys(Keys.Enter);
and this is the error i am getting in WAD console
### WinAppDriver::CommandHandler::Session::HandleCommandAsMidPoint - Command keys is not recognized
HTTP/1.1 404 Not Found
Content-Length: 141
Content-Type: application/json

{"status":9,"value":{"error":"unknown command","message":"Command not recognized: POST: /session/B2B11EDD-5689-4DCD-BB74-59A32E4AD897/keys"}}

**Comment by hassanuz** [comment]
I'd recommend switching to a [desktop session](https://github.com/microsoft/WinAppDriver/blob/master/Docs/FAQ.md#when-and-how-to-attach-to-an-existing-app-window) and using the absolute XPath generated from [UI Recorder](https://github.com/microsoft/WinAppDriver/releases/tag/UIR-v1.1).
