### ISSUE TITLE
Can't install the Selenium.WebDriver in the CalculatorTest in C#

### ISSUE THREAD

**Issue by koktsing** [microsoft/WinAppDriver#887]
Hi,

I downloaded the CalCulatorTest and would like to give it a try.
However, i am not able to build the project.
In order to build the project, I need to update/install the nuget packages.
However i am stucked now with Selenium.WebDriver.

My environment is a VDI without internet connection, which I am not sure if the problem is due to that.
I downloaded the selenium.webdriver.3.0.1.nupkg and other required packages from nuget website, and copied this package into the vdi.
I also configure a Package Resource Folder to point to the offline nuget packages I downloaded manually.

![image](https://user-images.githubusercontent.com/55833244/65676542-ac253280-e082-11e9-8e84-431a00d8e1bb.png)

![image](https://user-images.githubusercontent.com/55833244/65676630-d24ad280-e082-11e9-8b1f-ff7a36d50ed5.png)

I tried to use the Restore option to restore the package, but all packages can be installed except 
Selenium.WebDriver.3.0.1.

I also try another option, where I comment out the Selenium.WebDriver.3.0.1 package in the packages.config, later try with a manual install using 'Manual Packages for Solution'
![image](https://user-images.githubusercontent.com/55833244/65676997-674dcb80-e083-11e9-9a82-28f2f45357c2.png)

![image](https://user-images.githubusercontent.com/55833244/65677140-a67c1c80-e083-11e9-96f7-69e309a69f88.png)

here is the complete error return from the Package Manager output.

Attempting to gather dependency information for package 'Selenium.WebDriver.3.0.1' with respect to project 'CalculatorTest', targeting '.NETFramework,Version=v4.5'
Gathering dependency information took 61.71 ms
Attempting to resolve dependencies for package 'Selenium.WebDriver.3.0.1' with DependencyBehavior 'Lowest'
One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'Appium.WebDriver 3.0.0.1 constraint: Selenium.WebDriver (>= 3.0.1)', 'Selenium.Support 3.0.1 constraint: Selenium.WebDriver (>= 3.0.1)'
Resolving dependency information took 0 ms
Resolving actions to install package 'Selenium.WebDriver.3.0.1'
Resolved actions to install package 'Selenium.WebDriver.3.0.1'
Retrieving package 'Selenium.WebDriver 3.0.1' from 'CalculatorPackages'.
Adding package 'Selenium.WebDriver.3.0.1' to folder 'C:\Projects\CalculatorTest\packages'
Install failed. Rolling back...
Package 'Selenium.WebDriver.3.0.1' does not exist in project 'CalculatorTest'
Package 'Selenium.WebDriver.3.0.1' does not exist in folder 'C:\Projects\CalculatorTest\packages'
Executing nuget actions took 2.74 min
NU3008: The package integrity check failed.
Time Elapsed: 00:02:44.3588234

Please advise, thanks in advance.

**Comment by stu4355226** [comment]
Can you clean up your project and try to install "Microsoft.WinAppDriver.Appium.WebDriver" ? it should give you correct version of Selenium.WebDriver. Thanks

**Comment by hassanuz** [comment]
Hi @koktsing,

As @stu4355226 suggested, please try downloading the preview [WinAppDriver NuGet package](https://www.nuget.org/packages/Microsoft.WinAppDriver.Appium.WebDriver/1.0.1-Preview) and use that in lieu of the Appium.WebDriver. 

You should also be using Selenium.WebDriver version 3.8.0, Selenium.Support 3.8.0, Castle.Core v4.2.1, and Newtonsof.Json v10.0.3.

Please reopen ticket if this does not solve your issue.
