### ISSUE TITLE
How to get the Application id ?

### ISSUE THREAD

**Issue by EthanJiang** [Microsoft/WinAppDriver#9]
if i want to test Windows Alarms & Clock app, how can I get it's application id?.

In the example, it directly show the application id is 'Microsoft.WindowsAlarms_8wekyb3d8bbwe!App“. but how do I get it by myself? 

The note said : 
When testing the application you authored yourself, you can find the Application Id in the generetated AppX\vs.appxrecipe file under RegisteredUserNmodeAppID node. E.g. c24c8163-548e-4b84-a466-530178fc0580_scyf5npe3hv32!App

My understanding is if I develop an app by myself, so I can control the authority and get application id in this way. but for the other apps just like "Windows Alarms & Clock app", I don't own it, how can I get application id?

Thanks
Ethan

**Comment by AsafSaar** [comment]
You can find your avaialble win apps in the following registry key:
HKEY_CURRENT_USER\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppContainer\Storage

**Comment by jonstoneman** [comment]
I haven't tried it but it looks like you can use the `PackageFamilyName` value reported by the [`Get-AppxPackage`](https://technet.microsoft.com/en-us/library/hh856044.aspx?f=255&MSPPError=-2147217396) cmdlet with `!App` appended.

**Comment by alakshmi1030** [comment]
We verified that @jonstoneman's solution works and we will update the README documentation with this information.

**Comment by Tadimsky** [comment]
This doesn't seem to work for all apps - I'm trying to test mine and appending !App to the end of the PFN is not working.
Any other way to get the full AppId that WinAppDriver needs?

**Comment by gaurang011** [comment]
You can just run the application, Go to task manager & find out application by clicking on properties.
Refer attached screen
![capture](https://cloud.githubusercontent.com/assets/17120534/23114979/18970238-f768-11e6-9e6f-982090658797.JPG)

**Comment by sunnysachdeva** [comment]
![image](https://user-images.githubusercontent.com/5293359/47099132-42858d00-d252-11e8-8867-ba88edc8d323.png)

In my case, I am trying to find ApplicationId for SQL Server Management Studio. 
Can someone pls help

**Comment by khouzam** [comment]
Hi @sunnysachdeva,

You should really open a new issue instead of commenting on a closed one.

If you  take a look at the wiki section on [testing a classing windows application](https://github.com/Microsoft/WinAppDriver#testing-a-classic-windows-application) you only need to specify the exe filename of the application you are trying to launch. The AppId is only applicable to Modern or Universal applications.

**Comment by djivc** [comment]
For those that end up at this thread from historical purposes looking for an answer, check out this:

[Find the AUMID in Windows 10](https://jcutrer.com/windows/find-aumid#:~:text=Steps%20to%20get%20an%20App%E2%80%99s%20AUMID%20in%20Windows,box%20next%20to%20AppUserModelId%20and%20press%20OK.%20)
