### ISSUE TITLE
FindElementByXPath threw an exception 'System.InvalidOperationException' 

### ISSUE THREAD

**Issue by krabobor** [Microsoft/WinAppDriver#90]
I tried to use the latest release of WinAppDriver and run the CalculatorTest, but methods **FindElementByXPath** and **FindElementsByXPath** does not work and throw  an exception 'System.InvalidOperationException'. WindowsApplicationDriver v0.6-beta, VS 2015 update 3

screenshot: https://gyazo.com/25663c936df4562bb47db93f977ee00d

**Comment by ianceicys** [comment]
I too can repo this XPath issue with Visual Studio 2017 RC. 
Repo Video Here: https://www.youtube.com/watch?v=xvSfdrGcI1Y
http://i.imgur.com/NuHeweI.png
Are there any additional troubleshooting steps/logs?

I thought it could be a timeout issue but changing from 2 seconds to 4 seconds did not fix the failure. 
https://github.com/Microsoft/WinAppDriver/blob/master/Samples/C%23/CalculatorTest/BasicScenarios.cs#L39

**Comment by timotiusmargo** [comment]
The calculator app in the pre-Windows 10 anniversary edition didn't seem to have the '**Menu**' name. But in such case the XPath should return no such element error instead of unknown error. This is indeed a bug that we will look at.

A temporary workaround is probably by using the **NavButton** **AutomationId** to locate the item. Unfortunately, this will require Appium.WebDriver NuGet package to be added to the project to replace a more restricted Selenium.WebDriver.

**Comment by ianceicys** [comment]
I did find that I am able to successfully run the calculator test sample on Windows 10, Version 1607. 
OS Version: 10.0.14393 Build 14393.

**Comment by mauricekoster** [comment]
Just started today with WinAppDriver with the Calculator example. I also got errors using the FindElementByXPath method. If I change the code to FindElementByName it works.
I also tried the XPath FindElementByXPath("//Button[@AutomationId=\"NavButton\"]")
But this also does not work.
(PS: I am using a localized version of windows (Dutch in my case))

**Comment by ianceicys** [comment]
@mauricekoster I was able to get the calculator example working with both FindElementByName and FindElementBy XPath by upgrading to the the latest insider build of Windows 10. 
Could you try the following PR and see if it works for you?

What version of windows 10 are you running?

**Comment by mauricekoster** [comment]
Version: 10.0.14393 Build 14393

**Comment by yodurr** [comment]
please test with the new 0.7 release.  thanks!

**Comment by mauricekoster** [comment]
Seems to be working now. I only needed to translate the names to Dutch to make it work..

**Comment by yodurr** [comment]
Great!
