### ISSUE TITLE
How can i catch exception?

### ISSUE THREAD

**Issue by h10ne** [microsoft/WinAppDriver#900]
When an exception is thrown on a form, the test is marked as passed. How to catch an exception on the form and make the test failed?

**Comment by licanhua** [comment]
Are you talking about Windows Forms? Is the exception from test application or test framework? Will the exception caused a crash? How do the exception show in UI?

If the exception is from test application, most of time, we catch the exception and put it in a 'result' textbox. then in the test case, it checks if 'result' is IsDisplayed, or if 'result' is not OK.

**Comment by MinoEclairs** [comment]
@licanhua can you please elaborate your answer. my test application throws an exception in a dialog box. How can I catch it and make the test fail? Right now the winAppDriver is just ignoring it. 

the control type of the dialog box is : UIA_WindowControlTypeId (0xC370. it have NO name or any other unique identifier. 

Any help would be appreciated.

**Comment by licanhua** [comment]
There are lots of ways:
1. FindElementByClassName, FindElementByName, FindElementByTagName, FindElementByXPath may helps. I suggest you try [Appium-desktop](https://github.com/microsoft/WinAppDriver/blob/master/Docs/AuthoringTestScripts.md#inspecting-ui-elements). You can practice above locators one by one with Appium-desktop.
2. Don't focus only dialog id self. it has children, also it has parent. maybe one of them have id.
3. get PageSource, then do string search
4. add a id to the dialog box.

**Comment by MinoEclairs** [comment]
@licanhua I cannot add a id to the dialog box because I am not the developer of the application nor can I get the development team to add it for me. But thanks.
