### ISSUE TITLE
Environment setup when executing tests in parallel ?

### ISSUE THREAD

**Issue by fforjan** [microsoft/WinAppDriver#901]
Dear WinAppDriver people,

We are currently looking at migrating our CodedUI code to WinAppDriver and there is one use cases which is not clear.
Our current UI test infrastructure still using TFS 2013 Test controller /TFS 2013 Test agents architecture and as such, we can run all of our UI tests in 'parallel' on over 100 machines in less than 2 hours total.

Is there any way to achieve this with TFS 2017 or Azure Dev Ops ?

Regards !

**Comment by licanhua** [comment]
I guess you can still use TF2013 for WinAppDriver testing. Maybe your question would be: what test runner should I choose or how to migrate from TFS 2013 to TFS 2017/Azure Dev Ops.

First, let me ask what's difference to use CodedUI vs WinAppDriver?
1. You need to install WinAppDriver on my agents, and WinAppDriver is running in a sperate process, so you need to start/stop WinAppDriver by yourself.
2. Compared to CodeUI, WinAppDriver supports more test runners. MSTest, Jasmine, and any test runner selenium or appium supports.

So the final implemenation of parallel is determined by the test runner, I suggest you search "azure devops mstest parallel" or "azure devops selenium parallel".

Here are some topics when I search with above key words:
[Run tests in parallel for any test runner](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/parallel-testing-any-test-runner?view=azure-devops)
[Run tests in parallel using the Visual Studio Test task](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/parallel-testing-vstest?view=azure-devops)
[Parallel Testing in a Selenium Grid with VSTS](https://colinsalmcorner.com/post/parallel-testing-in-a-selenium-grid-with-vsts)

**Comment by fforjan** [comment]
We are also looking to drop TFS2013 at the same time, so it could be a short term option but also looking a our next gen test infrastructure.

In order to migrate our tests, we want to still continue to use C# as some of our testing involve WCF communication so we could reuse that code easily. So yes azure / 

VSTest seems the recommended option.
BUT as usual, i could always dig the documentation, **but one of our rules in our team is, if it seems we are the only one doing this, we may be doing it wrong.**
There is no way we are the only one trying to run WinAppDrivers with C# in parallel and surely there is a white paper/learn lessons from someone who tried to do this and its learning lesson.

Typically, the Azure Dev Ops machine with WinAppDriver were made available  in may/june this year and no words about running in parallel.
https://github.com/Microsoft/WinAppDriver/wiki/WinAppDriver-in-CI-with-Azure-Pipelines

In means everything run in the same machine. If we use on set of tests machine, is it recommended to deploy & run WinAppDriver each time as part of our application deployment? is it part of the test VMs and should be running all the time ? Is it part of the VMs and started when the VM starts ? But WinAppDriver is not a service - yeah I can host it with any service runner?

**Comment by licanhua** [comment]
deploy & run WinAppDriver each time as part of our application deployment?
It depends on. If you are using [Microsoft hosted agent](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops), and they are HostedVS2019 and HostedVS2017, WinAppDriver is pre-installed in these pipeline VMs. Otherwise you have to deploy it by yourself.
I don't think it supports it as service right now, You have two ways to start WinAppDriver:
1. Use [WinAppDriver Pipelines Task](https://marketplace.visualstudio.com/acquisition?itemName=WinAppDriver.winappdriver-pipelines-task)
2. Launch WinAppDriver.exe 

is it part of the test VMs and should be running all the time?
If you are using Microsoft hosted agent, each time you run the pipeline, you always got a new VM, so the VM should be recycled after the testing.
I used TFS test agents before, and they are always running. Even more, I need to update Windows and SDK by myself. I don't know if it's changed in Azure DevOps for self hosted agents.

**Comment by fforjan** [comment]
@licanhua  in our case for hosted agent, we managed via packer template, meaning we do not do any manual actions, just asked for the machien to be recreated to be re-installed. 
but the way you describe it seems for the case when the build agent and the test agent are the same. I'm interested when one build agent run the UI tests on multiple tests agents (i.e. multiple machines):
```
           +--- Test Agent 1
           |
BuildAgent --------Test Agent 2
           |
           +--- Test Agent 3
```

**Comment by licanhua** [comment]
@fforjan, Maybe you can reach out to the team described in https://devblogs.microsoft.com/devops/changes-to-coded-ui-test-in-visual-studio-2019/, and they may have more insights to the parallel testing and migration.

**Comment by PandaMagnus** [comment]
You want the VSTest task in Azure DevOps:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops

Specifically, you want to set the Distribution Batch Type in conjunction with the job's slicing:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#slicing

These two settings together will get ADO to batch up your tests and distribute them to multiple agents.

**Comment by fforjan** [comment]
Let's ping @hassanuz first :)

**Comment by hassanuz** [comment]
@fforjan, there isn't anything official detailing this from our side, but @PandaMagnus is correct on how you can enable this on DevOps by running tests using multiple agents in parallel where WinAppDriver is installed on each of them.

There is an example pipeline of this [here](https://dev.azure.com/stmoy/Xaml%20Controls%20Gallery/_build/results?buildId=316).

**Comment by fforjan** [comment]
@hassanuz  any recommendation for OnPrem agent setup ?

**Comment by hassanuz** [comment]
@fforjan, 

I'd recommend following the guide [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops). 

You'd want to
1. Use a Windows 10 image
1. Enable Developer Mode
1. Set the agent up as Interactive 
1. Have WinAppDriver pre-installed.

**Comment by hassanuz** [comment]
Closing this thread as the original issue answered. Feel free to create a new one for a different topic.
