### ISSUE TITLE
Code generated by UI recorder does not compile in player

### ISSUE THREAD

**Issue by eric-gilbertson** [microsoft/WinAppDriver#911]
Code generated by UI recorder does not compile in player. The code generated by recorder makes extensive use of desktopSession.FindElementByAbsoluteXPath() method which is not provide by the methods available in the player, eg OpenQA.Selenium.Appium.Windows.WindowsDriver()/WindowsElement(). Should this work?

**Comment by hassanuz** [comment]
Hi @eric-gilbertson,

UI Recorder code was intended to be used in conjunction with the [UI Recorder template](https://github.com/microsoft/WinAppDriver/tree/v1.1/Tools/UIRecorder/UIRecorderTemplate). You can paste this [snippet ](https://github.com/microsoft/WinAppDriver/blob/28cee06cea5cf375a136b27ec5c8b2f335a7f5c0/Tools/UIRecorder/UIRecorderTemplate/Program.cs#L52)into your source to enable it.
