### ISSUE TITLE
"Send(Keys.***)" all special characters do not work

### ISSUE THREAD

**Issue by susmithamohan** [microsoft/WinAppDriver#919]
I am running my test files in a self hosted agent. So, when I send "Enter" or "Tab" keys, its not recognized instead a block character is added. 

I configured it accordingly, so that the agent does not run on the server.

![block](https://user-images.githubusercontent.com/35349540/67019045-ac34b300-f0c1-11e9-93cd-dde88226c6f7.PNG)

I tried all these lines of code:

- session.FindElementByAccessibilityId("CarrierSearch").SendKeys(OpenQA.Selenium.Keys.Enter);
- session.FindElementByAccessibilityId("CarrierSearch").SendKeys(Keys.Return);
- session.FindElementByAccessibilityId("CarrierSearch").SendKeys(Keys.Enter);

**Comment by anunay1** [comment]
what version of win app driver are you using

**Comment by anunay1** [comment]
with 1.1 version it works fine.

**Comment by CodeNinja0615** [comment]
Profile.SendKeys("{Enter}");
