### ISSUE TITLE
How to package WinAppDriver to my program?

### ISSUE THREAD

**Issue by tigerphc** [microsoft/WinAppDriver#922]
Since WinAppDriver.exe should run before my test program run.
How can I make setup package for my program.
When I need to run my test program (.exe) in other PC, is it necessary to install WinAppDriver to the PC?

**Comment by hassanuz** [comment]
Yes, WinAppDriver will have to be installed on the PC that you want to run the tests on.

**Comment by hassanuz** [comment]
Assuming you have admin rights with UAC disabled, you can probably write a PowerShell script to download and install the latest WinAppDriver.exe.
