### ISSUE TITLE
Cannot be able to use session.Mouse.ContextClick() & sessionElement.Mouse.DoubleClick

### ISSUE THREAD

**Issue by BalarajAdappa** [microsoft/WinAppDriver#929]
Hi,
@hassanuz 
I am trying to perform a right click on my application and I can't find anything in the samples that show how to do this except for session.Mouse.ContextClick(). i am using Visual Studio 2019 to write test case, in c#,  

`session.Mouse.DoubleClick(element.Coordinates);`
`session.Mouse.ContextClick(element.Coordinates);`

when i run the above code , control goes to Catch block with exception.

**Comment by BalarajAdappa** [comment]
> What is the exception?

when i step into one of those above code line i am getting this exception:
An element command failed because the referenced element is no longer attached to the DOM.

**Comment by BalarajAdappa** [comment]
[Obsolete("Use the Actions or ActionBuilder class to simulate mouse input.")]
    public interface IMouse
    {
        //
        // Summary:
        //     Clicks at a set of coordinates using the primary mouse button.
        //
        // Parameters:
        //   where:
        //     An OpenQA.Selenium.Interactions.Internal.ICoordinates describing where to click.
        void Click(ICoordinates where);
        //
        // Summary:
        //     Clicks at a set of coordinates using the secondary mouse button.
        //
        // Parameters:
        //   where:
        //     A OpenQA.Selenium.Interactions.Internal.ICoordinates describing where to click.
        void ContextClick(ICoordinates where);
        //
        // Summary:
        //     Double-clicks at a set of coordinates.
        //
        // Parameters:
        //   where:
        //     A OpenQA.Selenium.Interactions.Internal.ICoordinates describing where to double-click.
        void DoubleClick(ICoordinates where);
        //
        // Summary:
        //     Presses the primary mouse button at a set of coordinates.
        //
        // Parameters:
        //   where:
        //     A OpenQA.Selenium.Interactions.Internal.ICoordinates describing where to press
        //     the mouse button down.
        void MouseDown(ICoordinates where);
        //
        // Summary:
        //     Moves the mouse to the specified set of coordinates.
        //
        // Parameters:
        //   where:
        //     A OpenQA.Selenium.Interactions.Internal.ICoordinates describing where to move
        //     the mouse to.
        void MouseMove(ICoordinates where);
        //
        // Summary:
        //     Moves the mouse to the specified set of coordinates.
        //
        // Parameters:
        //   where:
        //     A OpenQA.Selenium.Interactions.Internal.ICoordinates describing where to click.
        //
        //   offsetX:
        //     A horizontal offset from the coordinates specified in where.
        //
        //   offsetY:
        //     A vertical offset from the coordinates specified in where.
        void MouseMove(ICoordinates where, int offsetX, int offsetY);
        //
        // Summary:
        //     Releases the primary mouse button at a set of coordinates.
        //
        // Parameters:
        //   where:
        //     A OpenQA.Selenium.Interactions.Internal.ICoordinates describing where to release
        //     the mouse button.
        void MouseUp(ICoordinates where);
    }


this is obsolete ia that the reason i am not able to contextclick on element??

**Comment by anunay1** [comment]
That means that the page is refreshing and the element is no longer attached to DOM. . In the catch block use the same code. 
session.Mouse.DoubleClick(element.Coordinates);
session.Mouse.ContextClick(element.Coordinates);

**Comment by BalarajAdappa** [comment]
> That means that the page is refreshing and the element is no longer attached to DOM. . In the catch block use the same code.
> session.Mouse.DoubleClick(element.Coordinates);
> session.Mouse.ContextClick(element.Coordinates);

thanks for your response , as you mentioned it was refreshing, i solved .
