### ISSUE TITLE
Sendkeys does not enter file path saved in json file

### ISSUE THREAD

**Issue by Yaacovg** [microsoft/WinAppDriver#931]
I apologize for lack of clarity. I am relatively new to Appium and not a coder by profession.
I am working with a desktop application and coding tests in c# where data is taken from a json file.
The following code works:
var filePath = _session.FindElementByClassName("#32770").FindElementByClassName("Edit");
filePath.Click();
filePath.SendKeys(@"C:\Temp\resources\Office_2.png"); 

Now, instead of entering the path "C:\Temp\resources\Office_2.png" in the code , I want to reference it from a json file.
The json file includes:
  "Positions": [{
      "MapFilePath": "C:\Temp\resources\Office_2.png"
}]

There is a class with:
        public string MapFilePath { get; set; }

The code I would like to use is:
filePath.SendKeys(position.MapFilePath);

But, when I try to use this code nothing is entered in the specified Edit field.
What am I doing wrong and how do I fix it.

Thanx in advance

**Comment by naeemakram** [comment]
This question is not related to WinAppDriver. 
However, to learn how to use JSON in C# you may look at [JSON.Net ](https://www.newtonsoft.com/json)

**Comment by Yaacovg** [comment]
Sorry, still lost a little lost with Json.net.
Please walk me through it if you can.
Again, I'm not a programmer.

**Comment by NathanZook** [comment]
This is the wrong forum for this question.  Your error is in reading the JSON data from the file.  Save the results of the read into a string and examine that string.  Any difficulties you have with that need to be addressed elsewhere.
