### ISSUE TITLE
Without AppId Execution Switching Window

### ISSUE THREAD

**Issue by sseenivasan89** [microsoft/WinAppDriver#944]
Hi,
My application don't have app id and am using "root" but the execution is very slow. if i use "exe" path as app id the execution is good but problem is "exe" working till login window after login WinAppDriver could not find elements since the window has changed, i am not able to use attach window because i could not identify any elements after login
Assume this:
Login window using "exe" - Successful 
After login i need to get element to attach my current window (since the window changed from "exe" not working anymore

**Comment by fforjan** [comment]
Did you check if using session.LaunchApp(); is fixing the issue ?

https://github.com/microsoft/WinAppDriver/blob/c33c66ba22b6cf2353146df28a5f8f3a54f762bd/Docs/FAQ.md#what-to-do-when-an-application-has-a-splash-screen-or-winappdriver-fails-to-recognize-the-correct-window

I would do a launchApp asfter the login is done to resync to 'root' window ?

**Comment by sseenivasan89** [comment]
i can't use session.LaunchApp(), after login my .exe path will not work currently am using 'root' for my whole execution,
till login i can use .exe after that my window will change so i am not able to use .exe

**Comment by fforjan** [comment]
> till login i can use .exe after that my window will change so i am not able to use .exe
That's the point, after you did the login, what happen if you redo session.LaunchApp() ?

**Comment by sseenivasan89** [comment]
after login my window has changed so i can't get any elements from new window then how can i attach to session ?

**Comment by hassanuz** [comment]
See [this ](https://github.com/microsoft/WinAppDriver/wiki/Frequently-Asked-Questions#when-and-how-to-attach-to-an-existing-app-window) to attach to an existing app window.
