### ISSUE TITLE
Checkboxes and Radio-buttons are inspected as Buttons. Is there a way WinAppDriver can get the state of these elements?

### ISSUE THREAD

**Issue by ajujayapal** [microsoft/WinAppDriver#946]
Using inspect.exe on our AUT, shows checkboxes and radio-buttons as Buttons. Is there a way for WinAppDriver to get the on/off state of these elements?

![image](https://user-images.githubusercontent.com/16923804/68226492-c8888900-ffb7-11e9-971b-cf93676a78c3.png)

![image](https://user-images.githubusercontent.com/16923804/68226553-e0f8a380-ffb7-11e9-8c04-d6610e90237c.png)

**Comment by anunay1** [comment]
you can use   bool checkboxStatus = session.FindElementByName(name).Selected;

**Comment by ajujayapal** [comment]
> you can use bool checkboxStatus = session.FindElementByName(name).Selected;

That property for the checkbox (recognized as a button in my case) is always returning True, even when the checkbox is not selected.

I am using python with Selenium by the way.

**Comment by ajujayapal** [comment]
These same elements are identified correctly (as checkboxes/radio-buttons) in UFT (using just the built-in windows add-in and no ui-automation) but not inspect.exe. Can't understand why.

**Comment by ajujayapal** [comment]
Went with pywinauto library in python to work with these elements (checkboxes, radio-buttons) that are identified as "Buttons". pywinauto had a "ButtonWrapper" that can be used to workaround this. So, for now moving forward with pywinauto instead of WinAppDriver.
