### ISSUE TITLE
Is there any improvements for Desktop xpath searching in V1.2? ms:experimental-webdriver does not provide much performance

### ISSUE THREAD

**Issue by kozlydiy** [microsoft/WinAppDriver#947]
In several cases when i can not use static Name or AutomationId I need to have possibility search for both ClassName and part of Name. Using DeskTop session i can search for a special window for 30 seconds.

**Comment by hassanuz** [comment]
Hi @kozlydiy - Desktop / Root XPath hasn't been impacted by v1.2.
