### ISSUE TITLE
Putting tested application window into foreground

### ISSUE THREAD

**Issue by monsieurfop** [microsoft/WinAppDriver#948]
Hello,
When I'm starting my tests in VS the driver successfully starts the application of my chosing, but it is run in the background (VS is still visible and I can only see a new application icon in the taskbar).

Then the code goes on and clicks a button, which is behind my VS window and, of course, fails as a required windows did not open after clicking.

Is there a way to put the application window into foreground?

**Comment by b19910925** [comment]
Will the solution to the problem?
