### ISSUE TITLE
Remotely connecting to WinAppDriver

### ISSUE THREAD

**Issue by cdmyhre** [Microsoft/WinAppDriver#95]
Hello, 

Just have a quick question about the WinAppDriver.
Does the server only need to be on windows 10? Can other versions of Windows connect remotely, similar to Selenium Server?

**Comment by timotiusmargo** [comment]
Yes only the server (the part running on the test machine where the apps are installed) need to be on Windows 10. You can definitely connect remotely from other versions of Windows.

More information can be found on https://github.com/Microsoft/WinAppDriver/blob/master/README.md#running-on-a-remote-machine

**Comment by cdmyhre** [comment]
So to clarify, If I wanted to run test on an app installed on a Windows 7 machine. I could remotely connect to my  7 machine to the Windows 10 server running WinAppDriver for the tests?

**Comment by yodurr** [comment]
The important piece is the machine where your app is running needs to be Win10.  You currently can't test an app that is running on a Win7 machine.  

You can have the test runner or other tooling run on Win7 which communicate to the Win10 machine where your app and WinAppDriver are running.

**Comment by cdmyhre** [comment]
@yodurr Thank you very much for the clarification!

**Comment by yodurr** [comment]
@cdmyhre please upvote the request here.  Thanks!
https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/13518501-winappdriver-support-to-win-7-and-8

**Comment by ellnika** [comment]
@yodurr does the remote machine needs to be Windows? Will it work if I am running my tests from Mac and the app I am testing is on Win10?

**Comment by Drugesh** [comment]
> @yodurr does the remote machine needs to be Windows? Will it work if I am running my tests from Mac and the app I am testing is on Win10?
@ellnika 
Are you able to run remote app on windows apps from Mac?
