### ISSUE TITLE
Does it have full support for Xbox One?

### ISSUE THREAD

**Issue by alvipeo** [Microsoft/WinAppDriver#96]
How can I automate testing for anything running on Xbox One?

**Comment by yodurr** [comment]
This is something we're investigating but don't have anything to share at this time.  Thanks.

**Comment by yodurr** [comment]
@alvipeo you can upvote the ask for xbox support here.  Thanks!
https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/17164127-enable-winappdriver-for-xbox-and-mobile

**Comment by alvipeo** [comment]
ok, done. is that enough? ;)

**Comment by yodurr** [comment]
yeah, thanks
