### ISSUE TITLE
Unable to open UI with WinAppDriver

### ISSUE THREAD

**Issue by b19910925** [microsoft/WinAppDriver#960]
HI ALL, I wrote a UI. When I open the UI, I will verify the ID of the team developer to write the program. So I put the CPU of the team developer into the bin. After the UI is compiled successfully, the UI can be started, but it is started with WinAppDriver. Exe, I found that I can't load the bin I wrote. How can I solve it? Thank you.
`DesiredCapabilities appCapabilities = new DesiredCapabilities();

string a = Path.GetFullPath(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "..\\..\\..\\"));

string targetAppPath = Path.Combine(a, "SimulationTool", "bin", "x64", "Debug", "Image Test Utility.exe");

appCapabilities.SetCapability("app", targetAppPath);

WindowsDriver = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), appCapabilities);`

**Comment by hassanuz** [comment]
What type of App are you trying to open @b19910925?
