### ISSUE TITLE
How to use WinAppDriver for IOS

### ISSUE THREAD

**Issue by Prabu02101983** [microsoft/WinAppDriver#961]
I am using WinAppDriver to automate the windows app and I wanted to know is it possible to run the same code for IOS?

Is there any other option for it? Can any one help me on that?

**Comment by anunay1** [comment]
No you cannot.

**Comment by Prabu02101983** [comment]
Can I use Appium to test my WinappDriver workflow on IOS?

**Comment by anunay1** [comment]
can't understand what you mean?

**Comment by hassanuz** [comment]
There's some good reads online for crossplatform testing, e.g. this [one](https://blog.jayway.com/2016/06/30/cross-platform-testing-example-android-ios-using-appium/). 

You would have to make platform specific changes in your test case to account for UI variations and then use Appium to relay the test. 

The [Appium Issues board](https://github.com/appium/appium/issues) would be better suited for cross-platform test discussion, specifically with iOS.

**Comment by coolyouni** [comment]
> I am using WinAppDriver to automate the windows app and I wanted to know is it possible to run the same code for IOS?
> 
> Is there any other option for it? Can any one help me on that?

I need solution as customer is asking for cross platform
