### ISSUE TITLE
SendKeys is not working correctly

### ISSUE THREAD

**Issue by nhhai** [microsoft/WinAppDriver#965]
Device: Surface Pro
AppType: Desktop App
Server version: tried on both 1.1.1 and 1.2.0
Client: Java

When I use sendkeys to send a text that contains normal and capitalized characters, all the capitalized characters after the first will be the same as the first.
E.g: 
- `DemoAccount` will be typed as `DemoDccount`
- `abcdefghABCDEFGH` > `abcdefghAAAAAAAA`

Even if I use sendkeys on another element, this still occurs. E.g: send `Abcdef` on element1, then on element2 sends  `GHIJKabc`, the text on element2 will be `AAAAAabc`

**Comment by nhhai** [comment]
I also tried to switch my keyboard layout to `US` and `US International`, no luck.

**Comment by naeemakram** [comment]
I suppose this is either a logic issue or an application under test bug. What is printed in WinAppDriver console window when SendKeys method is called?

**Comment by nhhai** [comment]
Thank for the quick reply.
The payload json on the server log looks correct,, and the response status is 0 too.
Can you suggest what may cause this?

**Comment by nhhai** [comment]
Also, when I send `test@example.com` it typed as `test_example.com` instead

**Comment by nhhai** [comment]
I tried this on a windows element (e.g: the text box in Run windows), and it doesn't happen. This probably is a bug with Qt framework, I'll debug to find out the problem.

For people who may also encounter this, my work around is to copy the text into clipboard and send Ctrl + v (paste) instead.

Java code:
```
StringSelection selection = new StringSelection(value.toString());
Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
clipboard.setContents(selection, selection);
e.sendKeys(Keys.CONTROL + "v" + Keys.CONTROL);
```

**Comment by naeemakram** [comment]
One more thing, I once had a somewhat similar problem. I only learned later on that a key was stuck on my wireless keyboard which I was not using at the time. That key kept pressing at random times and it would send a character S here and there. It was a crazy scenario. Do make sure you don't have a stuck key screwing it up for you :)

**Comment by nhhai** [comment]
I'm sure it's not my hardware. Checked with other team members, it seems the text box has some kind of editing/fixing while typing on its own which caused the problem. I think we can close this. Thank you.

**Comment by Binabran** [comment]
@nhhai I'm having the exact same problem as yourself sending keys to a QT application, did you manage to find the source of the issue?
Also were you able to find a solution outside of your workaround?

**Comment by leshadubenyuk** [comment]
@nhhai I have same issue with Qt application. I wonder why this issue is closed? Was there a solution?
