### ISSUE TITLE
Support for DevExpress UI controls especially with the DataGrid using Appium+WinAppDriver

### ISSUE THREAD

**Issue by apoorvu** [microsoft/WinAppDriver#970]
I have an application that is built in Visual Studio 2019 and its a WPF application. I want to test the UI using **WinAppDriver+Appium** but I am not sure whether the customized grid and the controls of DevExpress would be recognized by the tool or not.
Is there any possibility wherein I get a 100% confirmation?

**Comment by anunay1** [comment]
Can inspect.exe find elements? If yes then WAD will work.

**Comment by licanhua** [comment]
You can verify it by [appium-desktop](https://github.com/appium/appium-desktop). It provides more functionality than inspect.exe.
