### ISSUE TITLE
Drag and Drop using Winapp driver for a UI Element

### ISSUE THREAD

**Issue by amittal004** [microsoft/WinAppDriver#971]
I have a plugin installed in visual studio that lets me create a form UI. Now I am trying to drag and drop an element on the form screen with help of an automation script using winapp driver which I am unable to do.

 

   ```
 var FindVSProjectWindow = DesktopSession.FindElementByName("SystemModeler4 - Microsoft Visual Studio  (Administrator)");
                if (FindVSProjectWindow != null)
                {
                    const int offset = 100;
    
                    var FindAttribute = DesktopSession.FindElementByName("VsClassViewMembersPane").FindElementByName("Attribute1");
                   
                    DesktopSession.Mouse.MouseMove(FindAttribute.Coordinates);
                    DesktopSession.Mouse.MouseDown(null); // Pass null as this command omit the given parameter
                    DesktopSession.Mouse.MouseMove(FindAttribute.Coordinates, offset, offset);
                    DesktopSession.Mouse.MouseUp(null); // Pass null as this command omit the given parameter
                    Thread.Sleep(TimeSpan.FromSeconds(1));
                }
```

I tried this code using an example from github but not happening.

**Comment by amittal004** [comment]
succeeded

**Comment by Milly89** [comment]
> succeeded

Hi guy, I just want to drag a component from a tool box to designer editor, and I used code example from github, but not work.
How do you succeeded? can you share me something ? Thanks.
![image](https://user-images.githubusercontent.com/64124223/112406855-f0fd5880-8d4f-11eb-8006-7b66713c67b8.png)
![image](https://user-images.githubusercontent.com/64124223/112406865-f78bd000-8d4f-11eb-9df8-03fbe2f9211c.png)

**Comment by Shakevg** [comment]
@Milly89 Try this c# code https://github.com/microsoft/WinAppDriver/issues/1223#issuecomment-741770991
