### ISSUE TITLE
An element command couldn't be completed because the element is not a pointer - or keyboard interactable 

### ISSUE THREAD

**Issue by dra123** [microsoft/WinAppDriver#973]
Hello all,
My scripts fail as the element is not clickable. I even tried to degrade Winappdriver to V0.9 but the 
element is not clickable yet. (Appium WebDriver 4.0.0)

My failing point is , unable to click don't save button to close the Notepad 

Could anyone please advise me ?

[Please note, scripts were run before 2 months but not now , It might be some upgrade issue ]

--------------------------------------------------------------------------------------------
POST /session/C75FE950-4885-4F46-B9DB-A6C940D3DF59/element/42.331874.3.-2147483647.331874.-2.5/click HTTP/1.1
Accept: application/json, image/png
Content-Length: 2
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.0 (.net windows)

{}
HTTP/1.1 400 Bad Request
Content-Length: 175
Content-Type: application/json

{"status":105,"value":{"error":"element not interactable","message":"An element command could not be completed because the element is not pointer- or keyboard interactable."}}

==========================================
DELETE /session/C75FE950-4885-4F46-B9DB-A6C940D3DF59 HTTP/1.1
Accept: application/json, image/png
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.0 (.net windows)

HTTP/1.1 200 OK
Content-Length: 63
Content-Type: application/json

{"sessionId":"C75FE950-4885-4F46-B9DB-A6C940D3DF59","status":0}

**Comment by hassanuz** [comment]
Is the [notepad sample](https://github.com/microsoft/WinAppDriver/tree/master/Samples/C%23/NotepadTest) working for you? 

We implemented [logic to handle don't save](https://github.com/microsoft/WinAppDriver/blob/f4449aaad63843311be7fdaeeff48d38ad60f357/Samples/C%23/NotepadTest/NotepadSession.cs#L67) as well which is working fine on my end.

**Comment by dra123** [comment]
Thank you @hassanuz  for the reply. I;m looking into it , Can you please provide the WinaAppDriver  and Appium Version supported to notepad sample script ?

**Comment by dra123** [comment]
@hassanuz , Also could you please confirm if the notpad sample working fine now ? I have used same code like you

**Comment by anunay1** [comment]
Yes its working at my end also.

**Comment by dra123** [comment]
@anunay1 , I'm using  Version 1809 (WIN10)
![image](https://user-images.githubusercontent.com/23474917/69123085-77ec5200-0ac6-11ea-9a29-cadf64fc7520.png)

**Comment by anunay1** [comment]
That seems ok, as I am using a lower version.

**Comment by dra123** [comment]
If i describe the issue more,

My scenario is :
![image](https://user-images.githubusercontent.com/23474917/69124629-4d9c9380-0aca-11ea-8e43-3c555d2c7357.png)

This is my implementation for last 2 steps and the error is coming after clicking the close button in notepad
![image](https://user-images.githubusercontent.com/23474917/69124943-c3a0fa80-0aca-11ea-96bc-765e1f5bba81.png)

![image](https://user-images.githubusercontent.com/23474917/69125039-e29f8c80-0aca-11ea-9340-583c3b5ba831.png)

After whole scenario run, driver is Quit 
![image](https://user-images.githubusercontent.com/23474917/69125110-137fc180-0acb-11ea-9aee-cc74857a2e08.png)

So the thing is, i couldn't close the note pad and click dont save button (Currently i commented dont save code line to find the issue)

@anunay1 @hassanuz , Could you advise me please ?

**Comment by anunay1** [comment]
Please share the solution

**Comment by dra123** [comment]
Please find it https://github.com/dra123/Test-Automation-Notepad/blob/test/Notepad%20TestAutomationSuite/Specflow/Steps/GetTimeDateAndSaveInNotepadSteps.cs

@anunay1 @hassanuz or anyone help me to fix this

**Comment by anunay1** [comment]
Zip the entire solution can upload to the bug.

**Comment by dra123** [comment]
@anunay1 , Sorry, I’m afraid I don’t follow you.

**Comment by dra123** [comment]
> Zip the entire solution can upload to the bug.

Sorry, I’m afraid I don’t follow you.

**Comment by anunay1** [comment]
I require the entire solution to debug at my end, please upload the entire solution

**Comment by dra123** [comment]
> I require the entire solution to debug at my end, please upload the entire solution

Please find it under https://github.com/dra123/Test-Automation-Notepad/tree/test .

**Comment by anunay1** [comment]
Thanks, I got the solution but you are using some excel, please share the excel as well.

**Comment by anunay1** [comment]
Hi after commenting the excel part, it works perfectly in my system. 

{"using":"name","value":"Close"}
HTTP/1.1 200 OK
Content-Length: 123
Content-Type: application/json

{"sessionId":"DA464960-07A3-41DC-8DAC-4D42C0B2ABDF","status":0,"value":{"ELEMENT":"42.2230116.2.-2147483647.2230116.-2.5"}}


==========================================
POST /session/DA464960-07A3-41DC-8DAC-4D42C0B2ABDF/element/42.2230116.2.-2147483647.2230116.-2.5/click HTTP/1.1
Accept: application/json, image/png
Content-Length: 2
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.0 (.net windows)

{}
HTTP/1.1 200 OK
Content-Length: 63
Content-Type: application/json

{"sessionId":"DA464960-07A3-41DC-8DAC-4D42C0B2ABDF","status":0}


==========================================
POST /session/DA464960-07A3-41DC-8DAC-4D42C0B2ABDF/element HTTP/1.1
Accept: application/json, image/png
Content-Length: 37
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.0 (.net windows)

{"using":"name","value":"Don't Save"}
HTTP/1.1 200 OK
Content-Length: 95
Content-Type: application/json

{"sessionId":"DA464960-07A3-41DC-8DAC-4D42C0B2ABDF","status":0,"value":{"ELEMENT":"42.529842"}}

==========================================

POST /session/DA464960-07A3-41DC-8DAC-4D42C0B2ABDF/element/42.529842/click HTTP/1.1
Accept: application/json, image/png
Content-Length: 2
Content-Type: application/json;charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/3.141.0 (.net windows)

{}
HTTP/1.1 200 OK
Content-Length: 63
Content-Type: application/json

{"sessionId":"DA464960-07A3-41DC-8DAC-4D42C0B2ABDF","status":0}

**Comment by anunay1** [comment]
Are you using mac or windows.

**Comment by dra123** [comment]
I'm using windows.

It may be my machine issue ?

**Comment by anunay1** [comment]
could be,

**Comment by dra123** [comment]
Thank you for looking into this @anunay1 , Could you tell me the Windows SDK build version on your machine ?

**Comment by anunay1** [comment]
10.0.17134.12

**Comment by dra123** [comment]
@an, Thank you so much for looked the issue. I think the problem might be an issue on my machine
