### ISSUE TITLE
Value of Button is empty

### ISSUE THREAD

**Issue by cFinch28** [microsoft/WinAppDriver#974]
![2019-11-18](https://user-images.githubusercontent.com/31553614/69049318-e3b7b780-09ff-11ea-84af-4904e6988341.png)
Testing a scheduling application, I need to find the values of buttons showing time or days and time. The buttons are separated into two or three parts I can click to change the value. However, inspect.exe cannot show the value of this button (For this example I expect "1Day(s)00:00"). I can find the button and the spinner as its child but there is no EditControl element. It doesn´t even recognize the in orange marked selected part of the button. Does anybody know how I can get access the value?

**Comment by anunay1** [comment]
Ask your developers to give inspect the access to view it, if inspect cannot find, then WAD will also not work.

**Comment by cFinch28** [comment]
Thank you for your response.
I am now trying to access it using the database
