### ISSUE TITLE
how to focusing Rightclick menu?

### ISSUE THREAD

**Issue by YeonwooJeong** [microsoft/WinAppDriver#976]
I could display rightclick menu but I couldn't click in menu
ex) Open click in menu

how to focusing rightclick menu?

this is my setup code

	@BeforeClass
	public static void setup() {
		try {
			DesiredCapabilities appCapabilities = new DesiredCapabilities();
			appCapabilities.setCapability("platformName", "Windows");
			appCapabilities.setCapability("deviceName", "WindowsPC");
			appCapabilities.setCapability("app", "Root");
			WindowSession = new WindowsDriver<WindowsElement>(new URL("http://127.0.0.1:4723"), appCapabilities);
			actions = new Actions(WindowSession);
			modules = new Modules(WindowSession);
			session = new Session(WindowSession);	}

I executed File explorer

    public void excute() {
    	DesiredCapabilities appCapabilities = new DesiredCapabilities();
		appCapabilities.setCapability("app", "C:\\Windows\\explorer.exe");
		try {
			ExplorerSession = new WindowsDriver(new URL("http://127.0.0.1:4723"), appCapabilities);
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		ExplorerSession.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
    }

and rightclick menu

    public void RightClick(String name) {
    	
		WebElement elementLocator = winapp.findElementByName(name);
		actions.contextClick(elementLocator).perform();
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }

**Comment by anunay1** [comment]
I was able to click using xpath : 

 WindowsElement element = WindowSession.FindElementByName("This PC");
            Actions actions = new Actions(WindowSession);
            actions.ContextClick(element).Perform();
            //WindowSession.FindElementByName("Context").FindElementByName("Collapse").Click();
            WindowSession.FindElementByXPath("/Pane[@ClassName=\"#32769\"][@Name=\"Desktop 1\"]/Menu[@ClassName=\"#32768\"][@Name=\"Context\"]/MenuItem[@Name=\"Collapse\"]").Click();

**Comment by YeonwooJeong** [comment]
> I was able to click using xpath :
> 
> WindowsElement element = WindowSession.FindElementByName("This PC");
> Actions actions = new Actions(WindowSession);
> actions.ContextClick(element).Perform();
> //WindowSession.FindElementByName("Context").FindElementByName("Collapse").Click();
> WindowSession.FindElementByXPath("/Pane[@ClassName="#32769"][@name="Desktop 1"]/Menu[@ClassName="#32768"][@name="Context"]/MenuItem[@name="Collapse"]").Click();

Thanks for your answer. I resolve this issue
However, the Thread.sleep (1000) code must be inserted to operate.
Does it take time to find the xpath?

**Comment by anunay1** [comment]
yes it takes 5 to 6 sec for xpath, if the issue i resolved, please close the bug.

**Comment by YeonwooJeong** [comment]
> yes it takes 5 to 6 sec for xpath, if the issue i resolved, please close the bug.

Thanks

**Comment by YeonwooJeong** [comment]
@anunay1  I have a question. how to focusing 2depth menu?

I get 2depth xpath in the same way but it doesn't work.

![image](https://user-images.githubusercontent.com/8816386/69213910-dc7fdd80-0ba8-11ea-80e2-8f030b23be61.png)

1depth succeed
fileExplorerSession.findElementByXPath("//Menu[@ClassName=\"#32768\"][@Name=\"컨텍스트\"]/MenuItem[@Name=\"보내기(N)\"]").click(); 


2depth failed
fileExplorerSession.findElementByXPath("//Menu[@ClassName=\"#32768\"][@Name=\"컨텍스트\"]/MenuItem[@Name=\"보내기(N)\"]/MenuItem[@Name=\"문서\"]").click();


what is problem?

**Comment by hassanuz** [comment]
@YeonwooJeong, were you able to resolve this? I'd recommend getting the XPath query from [UI Recorder](https://github.com/microsoft/WinAppDriver/releases/tag/UIR-v1.1) and trying that under a [desktop session](https://github.com/microsoft/WinAppDriver/wiki/Frequently-Asked-Questions#when-and-how-to-create-a-desktop-session).
