### ISSUE TITLE
EventFiring driver for desktop apps?

### ISSUE THREAD

**Issue by alexp1980** [microsoft/WinAppDriver#977]
I would like to use the ability to record events based on the winappdriver as you can with current web drivers (EventFiringWebDriver). Is this currently possible or if not will it be available to winappdriver at some point?

Regards

**Comment by alexp1980** [comment]
Realised this is not really the responsibility of the winappdriver

**Comment by anunay1** [comment]
@alexp1980 Were you able to achieve this, I am also trying the same but not able to accomplish.
