### ISSUE TITLE
There isn't possibility to find element by ID

### ISSUE THREAD

**Issue by erohinalexey** [microsoft/WinAppDriver#980]
Hi all
I try to use WinAppDriver for automation Desktop application. 

I created a new method for waiting visibility element:

    public void waitElementVisibilityByID(String locator) {
        Wait().until(ExpectedConditions.visibilityOfElementLocated(By.id(locator)));
    }

I get the following error: "org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.id"
"locator" - is an unique AutomationID in my Desktop application. 

But, when I changed method: 

    public void waitElementVisibilityByID(String locator) {
        Wait().until(ExpectedConditions.visibilityOfElementLocated(By.xpath(".//*[@AutomationId='"+locator+"']")));
    }

It works correctly. 
Why this happened? Why search by ID failed, but search by xpath is success? 
Where is my mistake?

**Comment by pm90pl** [comment]
You have to use FindElementByAccessibilityId locator strategy.

**Comment by erohinalexey** [comment]
I could use 
WebElement element = winDriver.findElementByAccessibilityId(locator);
but visibilityOfElementLocated method expects only the "By" type as parameter. 
So I use the following condition:
By.xpath(".//*[@AutomationId='"+locator+"']")
because By.id(locator) condition doesn't work in this case. 
How can I use FindElementByAccessibilityId locator strategy in this case?

**Comment by pm90pl** [comment]
You just have to subclass By as it's written in the Selenium API documentation:
https://selenium.dev/selenium/docs/api/java/

> public abstract class By
extends java.lang.Object
Mechanism used to locate elements within a document. In order to create your own locating mechanisms, it is possible to subclass this class and override the protected methods as required, though it is expected that all subclasses rely on the basic finding mechanisms provided through static methods of this class: public WebElement findElement(WebDriver driver) { WebElement element = driver.findElement(By.id(getSelector())); if (element == null) element = driver.findElement(By.name(getSelector()); return element; }

**Comment by erohinalexey** [comment]
The answer is not entirely clear.
The same mechanism successfully works in Selenium + Java.
But when using WinAppDriver + Java something strange happens.
It is impossible to find an element directly by ID (By.id). But if you look for it in combination with the xpath, then everything works. Is it normal? And then searching on the xpath works noticeably slower.

**Comment by pm90pl** [comment]
If you're using AutomationId to locate an element you have to use method findElementByAccessibilityId.
findElementById or by.id doesn't use AutomationId property - it uses RuntimeId
You can find more details here:
[https://www.automatetheplanet.com/automate-windows-desktop-apps-winappdriver/](https://www.automatetheplanet.com/automate-windows-desktop-apps-winappdriver/) 

By doesn't support findElementByAccessibilityId so if you have to pass an instance of this class, you have to extend it and implement finding by accessibility id.

**Comment by pm90pl** [comment]
More about RuntimeId - it's actually useless in finding conditions. 

> The RuntimeId is guaranteed to not change on a UIA element only for the lifetime of the element.

You can find more here:
[Don’t use the UIA RuntimeId property in your Find condition](https://blogs.msdn.microsoft.com/winuiautomation/2016/07/07/dont-use-the-uia-runtimeid-property-in-your-find-condition/)

**Comment by hassanuz** [comment]
Please reopen @erohinalexey if you still have questions.
