### ISSUE TITLE
.net 4.8 and Support for SizeOfSet and PositionInSet UIAutomation - impact for WinAppDriver ?

### ISSUE THREAD

**Issue by fforjan** [microsoft/WinAppDriver#987]
It seems .net 4.8 is adding the support of SizeOfSet and PositionInSet.

Are WinAppDriver taking advantage of this for workinf with virtualized list ?
(in fact the underlying question is, is there any advantage to switch to 4.8 and its support in WinAppDriver ?

**Comment by hassanuz** [comment]
WinAppDriver hasn't done any internal changes for 4.8, so I don't expect the experience to be too different from previous versions.
