### ISSUE TITLE
Not able to access Treeview objects in win32 application via winappdriver.

### ISSUE THREAD

**Issue by sajithraj** [microsoft/WinAppDriver#990]
Not able to access Treeview objects in win32 application via winappdriver. As objects are visible in inspect tool also. Kindly help me is there anymethod available to click node element in the tree.

**Comment by KitoCoding** [comment]
Sorry Sajithraj, you're going to have to supply more context to your issue.

**Comment by anunay1** [comment]
Please share some code

**Comment by sajithraj** [comment]
Thanks for the quick response. I will add few more content

Sajith
