### ISSUE TITLE
How to use SoftAsserty in WinAppDriver?

### ISSUE THREAD

**Issue by aryansalcedo05** [microsoft/WinAppDriver#997]
Can someone advise how to do SoftAssert like in TestNG or any ways to do SoftAssert logic to continue test cases even the assert is failed?

**Comment by licanhua** [comment]
You should ask this question on MSTest, JUnit or any test runner you are using.

A typical setup is like this:
TestRunner(JUnit, NUnit, MsTest) <-> selenium client/proxy <-> WinAppDriver <-> App under test.

WinAppDriver is in the middle and has no idea on this.

If you are using mstest, a possible implementation would like this: https://automationrhapsody.com/soft-assertions-c-unit-testing-frameworks-mstest-nunit-xunit-net/

**Comment by aryansalcedo05** [comment]
@licanhua  thank you for this.
